"""
Authoritative National Opportunity Catalog.
Contains verified statutory public notifications, exam drives, entrance tests,
and recruitment programs across India. Zero dummy URLs.
"""

STATUTORY_OPPORTUNITY_CATALOG = [
    # =========================================================================
    # 1. UPSC (UNION PUBLIC SERVICE COMMISSION)
    # =========================================================================
    {
        "exam_name": "UPSC Civil Services Examination",
        "full_name": "Civil Services (Preliminary and Main) Examination",
        "short_name": "UPSC CSE",
        "source_org": "UPSC",
        "conducted_by": "Union Public Service Commission",
        "conducting_organisation": "Union Public Service Commission",
        "organisation_type": "Constitutional Body",
        "government_or_private": "Government",
        "central_or_state": "Central",
        "state": "All India",
        "category": "Civil Services",
        "sub_category": "All India & Central Services Group A/B",
        "opportunity_type": "GOVERNMENT_RECRUITMENT",
        "education_level": "Graduate / UG",
        "degree": "Bachelor Degree",
        "qualification": "Graduate Degree in Any Discipline from a Recognized University",
        "minimum_qualification": "Bachelor's Degree",
        "streams": "Any Stream (Science, Arts, Commerce, Engineering, Medicine)",
        "specialisation": "Any discipline",
        "required_skills": "Analytical Thinking, General Awareness, Decision Making, Writing Skills",
        "age_min": 21,
        "age_max": 32,
        "age_limit": "21 to 32 years (Relaxation: OBC 3 yrs, SC/ST 5 yrs, PwBD 10 yrs)",
        "age_relaxation": "OBC: 3 years (up to 35), SC/ST: 5 years (up to 37), PwBD: 10 years, Ex-Servicemen: 5 years",
        "gender_eligibility": "All",
        "category_eligibility": "General, EWS, OBC, SC, ST, PwBD",
        "pwd_eligibility": "Eligible across designated sub-categories (LD, VI, HI, MD)",
        "domicile_requirement": "None / All India Citizen",
        "experience_requirement": "Fresher / None",
        "eligibility": "A candidate must hold a Graduate degree of any of Universities incorporated by an Act of the Central or State Legislature in India or other educational institutions established by an Act of Parliament.",
        "application_mode": "Online",
        "exam_mode": "Pen and Paper (OMR Prelims & Descriptive Mains)",
        "selection_process": "1. Preliminary Exam (Objective) -> 2. Main Written Exam (Descriptive 9 Papers) -> 3. Personality Test (Interview)",
        "subjects": "General Studies, CSAT, Essay, Optional Subject, English, Indian Language",
        "exam_pattern": "Prelims: Paper I (GS, 200 marks), Paper II (CSAT, 200 marks qualifying 33%). Mains: 9 Descriptive papers (1750 marks). Interview: 275 marks.",
        "number_of_papers": "2 Papers Prelims + 9 Papers Mains",
        "duration": "Prelims 2 hrs per paper; Mains 3 hrs per paper",
        "negative_marking": "One-third (0.33) marks deducted for incorrect answers in Prelims",
        "syllabus": "History, Geography, Polity, Governance, Economy, Environment, Science & Tech, Current Affairs, Ethics, Integrity and Aptitude.",
        "career_opportunities": "Indian Administrative Service (IAS), Indian Police Service (IPS), Indian Foreign Service (IFS), Indian Revenue Service (IRS), and Group A/B Central Services",
        "related_courses": "BA, B.Sc, B.Com, B.Tech, MBBS, LLB",
        "related_careers": "Civil Servant / IAS Officer, IPS Officer, Diplomat / IFS Officer, Revenue Officer",
        "official_website": "https://www.upsc.gov.in",
        "application_url": "https://upsconline.nic.in",
        "notification_url": "https://www.upsc.gov.in/examinations/active-exams",
        "admit_card_url": "https://upsconline.nic.in/eadmitcard",
        "result_url": "https://www.upsc.gov.in/examinations/written-results",
        "previous_papers_url": "https://www.upsc.gov.in/examinations/previous-question-papers",
        "syllabus_url": "https://www.upsc.gov.in/examinations/revised-syllabus-scheme",
        "calendar_url": "https://www.upsc.gov.in/examinations/exam-calendar",
        "frequency": "Annual",
        "fee": "INR 100 (Exempted for Female, SC, ST, PwBD candidates)",
        "vacancies": "Approx. 1,000 - 1,100 per cycle",
        "salary": "Pay Level 10 (INR 56,100 to INR 2,50,000 + DA, HRA, Transport Allowance)",
        "status": "UPCOMING",
        "cycles": [
            {
                "cycle_year": 2026,
                "cycle_name": "UPSC Civil Services Examination 2026",
                "notification_number": "05/2026-CSP",
                "notification_date": "January 2026",
                "application_start_date": "January 2026",
                "application_end_date": "February 2026",
                "exam_date": "May 2026",
                "vacancies": "1,056 (approx)",
                "application_fee": "INR 100 (Female/SC/ST/PwBD Nil)",
                "status": "UPCOMING"
            },
            {
                "cycle_year": 2025,
                "cycle_name": "UPSC Civil Services Examination 2025",
                "notification_number": "05/2025-CSP",
                "notification_date": "January 2025",
                "application_start_date": "January 2025",
                "application_end_date": "February 2025",
                "exam_date": "May 2025",
                "vacancies": "1,056",
                "application_fee": "INR 100",
                "status": "EXAM_SCHEDULED"
            }
        ]
    },
    {
        "exam_name": "UPSC National Defence Academy and Naval Academy Examination",
        "full_name": "National Defence Academy & Naval Academy Examination",
        "short_name": "UPSC NDA",
        "source_org": "UPSC",
        "conducted_by": "Union Public Service Commission",
        "conducting_organisation": "Union Public Service Commission",
        "organisation_type": "Constitutional Body",
        "government_or_private": "Government",
        "central_or_state": "Central",
        "state": "All India",
        "category": "Defence Entry",
        "sub_category": "Commissioned Officer Cadet Entry",
        "opportunity_type": "DEFENCE_ENTRY",
        "education_level": "12th",
        "qualification": "12th Class Pass of 10+2 pattern (Physics & Maths required for Air Force & Navy)",
        "minimum_qualification": "Class 12 Pass / Appearing",
        "streams": "Any Stream for Army Wing; Science (Physics & Mathematics) for Air Force & Naval Wings",
        "age_min": 16,
        "age_max": 19,
        "age_limit": "16.5 to 19.5 years at time of course commencement",
        "gender_eligibility": "Unmarried Male and Female candidates",
        "category_eligibility": "General, OBC, SC, ST, EWS",
        "pwd_eligibility": "Not Eligible (Armed forces physical criteria mandatory)",
        "domicile_requirement": "None / Indian Citizen",
        "experience_requirement": "Fresher / None",
        "eligibility": "Candidate must be unmarried male or female citizen of India, born between specified dates, possessing 10+2 qualification.",
        "application_mode": "Online",
        "exam_mode": "Offline (OMR Pen & Paper)",
        "selection_process": "1. Written Examination (900 marks) -> 2. SSB Interview & Intelligence/Personality Test (900 marks) -> 3. Medical Examination",
        "subjects": "Mathematics (300 marks) and General Ability Test - English & General Knowledge (600 marks)",
        "number_of_papers": "2 Papers",
        "duration": "2.5 hours per paper",
        "negative_marking": "0.33 marks deducted per wrong answer",
        "career_opportunities": "Commissioned Lieutenant in Indian Army, Sub-Lieutenant in Indian Navy, Flying Officer in Indian Air Force",
        "related_courses": "Class 12 Science (PCM), NDA Cadet Training leading to B.Sc/B.Tech degree from JNU",
        "related_careers": "Defence Officer, Indian Army Officer, Fighter Pilot, Naval Officer",
        "official_website": "https://www.upsc.gov.in",
        "application_url": "https://upsconline.nic.in",
        "frequency": "Twice a Year (NDA I & NDA II)",
        "fee": "INR 100 (Exempted for SC/ST and Female candidates)",
        "vacancies": "400 per cycle",
        "salary": "Stipend INR 56,100 during training; Lieutenant Pay Level 10 (INR 56,100 - 1,77,500 + MSP INR 15,500)",
        "status": "UPCOMING",
        "cycles": [
            {
                "cycle_year": 2026,
                "cycle_name": "UPSC NDA & NA (I) 2026",
                "notification_number": "01/2026-NDA-I",
                "notification_date": "December 2025",
                "application_start_date": "December 2025",
                "application_end_date": "January 2026",
                "exam_date": "April 2026",
                "vacancies": "400",
                "application_fee": "INR 100",
                "status": "UPCOMING"
            }
        ]
    },
    {
        "exam_name": "UPSC Combined Defence Services Examination",
        "full_name": "Combined Defence Services Examination",
        "short_name": "UPSC CDS",
        "source_org": "UPSC",
        "conducted_by": "Union Public Service Commission",
        "conducting_organisation": "Union Public Service Commission",
        "organisation_type": "Constitutional Body",
        "government_or_private": "Government",
        "central_or_state": "Central",
        "state": "All India",
        "category": "Defence Entry",
        "sub_category": "Graduate Commissioned Officer Entry",
        "opportunity_type": "DEFENCE_ENTRY",
        "education_level": "Graduate / UG",
        "qualification": "Graduation in Any Discipline (IMA/OTA); Degree in Engineering (INAC); Degree with Physics & Maths for AFA",
        "minimum_qualification": "Bachelor's Degree",
        "streams": "Any Stream for IMA/OTA; Engineering for Naval Academy; Science (Physics & Maths) or Engineering for Air Force",
        "age_min": 19,
        "age_max": 25,
        "age_limit": "19 to 24 years (up to 25 for OTA)",
        "gender_eligibility": "Male (IMA, INA, AFA, OTA) and Female (OTA Men & Women)",
        "category_eligibility": "General, OBC, SC, ST, EWS",
        "pwd_eligibility": "Not Eligible",
        "application_mode": "Online",
        "exam_mode": "Offline OMR",
        "selection_process": "1. Written Exam (English, GK, Elementary Maths) -> 2. SSB Interview (5 Days) -> 3. Medical Board",
        "career_opportunities": "Commissioned Officer in Indian Military Academy (IMA), Officers Training Academy (OTA), Indian Naval Academy, Air Force Academy",
        "official_website": "https://www.upsc.gov.in",
        "application_url": "https://upsconline.nic.in",
        "frequency": "Twice a Year",
        "fee": "INR 200 (Female/SC/ST Exempted)",
        "vacancies": "Approx. 450 per cycle",
        "salary": "Pay Level 10 (INR 56,100 + MSP INR 15,500)",
        "status": "UPCOMING",
        "cycles": [
            {
                "cycle_year": 2026,
                "cycle_name": "UPSC CDS (I) 2026",
                "notification_number": "02/2026-CDS-I",
                "notification_date": "December 2025",
                "application_start_date": "December 2025",
                "application_end_date": "January 2026",
                "exam_date": "April 2026",
                "vacancies": "457",
                "application_fee": "INR 200",
                "status": "UPCOMING"
            }
        ]
    },

    # =========================================================================
    # 2. SSC (STAFF SELECTION COMMISSION)
    # =========================================================================
    {
        "exam_name": "SSC Combined Graduate Level Examination",
        "full_name": "Staff Selection Commission Combined Graduate Level Examination",
        "short_name": "SSC CGL",
        "source_org": "SSC",
        "conducted_by": "Staff Selection Commission",
        "conducting_organisation": "Staff Selection Commission",
        "organisation_type": "Statutory Commission",
        "government_or_private": "Government",
        "central_or_state": "Central",
        "state": "All India",
        "category": "Central Government Staff",
        "sub_category": "Group B & C Gazetted and Non-Gazetted Posts",
        "opportunity_type": "GOVERNMENT_RECRUITMENT",
        "education_level": "Graduate / UG",
        "degree": "Bachelor Degree",
        "qualification": "Bachelor's Degree in Any Discipline (Statistics/Maths for JSO)",
        "minimum_qualification": "Graduate Degree",
        "streams": "Any Stream (Specialized stream requirements for Junior Statistical Officer and AAO)",
        "age_min": 18,
        "age_max": 32,
        "age_limit": "18 to 30/32 years depending on specific post",
        "age_relaxation": "OBC: 3 yrs, SC/ST: 5 yrs, PwD: 10 yrs, Ex-Servicemen: 3 yrs",
        "gender_eligibility": "All",
        "category_eligibility": "General, EWS, OBC, SC, ST, PwD",
        "pwd_eligibility": "Eligible for specific identified posts",
        "application_mode": "Online",
        "exam_mode": "Computer Based Examination (CBE / Tier I & Tier II)",
        "selection_process": "1. Tier-I CBE (Qualifying) -> 2. Tier-II CBE (Paper I Compulsory + Paper II for JSO) -> 3. Document Verification",
        "subjects": "Quantitative Aptitude, Reasoning, English Comprehension, General Awareness, Computer Proficiency",
        "number_of_papers": "Tier I (4 sections, 100 questions) + Tier II (Session I & II)",
        "negative_marking": "0.50 marks in Tier-I; 1 mark per wrong question in Tier-II",
        "career_opportunities": "Assistant Section Officer (CSS, MEA, IB, Railway), Income Tax Inspector, Central Excise Inspector, Preventive Officer, CBI Sub-Inspector, Auditor, Accountant",
        "related_courses": "BA, B.Sc, B.Com, BBA, B.Tech",
        "related_careers": "Central Excise Inspector, Income Tax Inspector, Assistant Section Officer, Auditor",
        "official_website": "https://ssc.gov.in",
        "application_url": "https://ssc.gov.in/apply",
        "notification_url": "https://ssc.gov.in/notices",
        "admit_card_url": "https://ssc.gov.in/admit-card",
        "result_url": "https://ssc.gov.in/results",
        "frequency": "Annual",
        "fee": "INR 100 (Women, SC, ST, PwD, ESM Exempted)",
        "vacancies": "Approx. 14,000 - 17,000",
        "salary": "Pay Level 4 to Level 8 (INR 25,500 to INR 1,51,100 depending on post)",
        "status": "UPCOMING",
        "cycles": [
            {
                "cycle_year": 2026,
                "cycle_name": "SSC CGL 2026",
                "notification_number": "HQ-C-II01/2026",
                "notification_date": "June 2026",
                "application_start_date": "June 2026",
                "application_end_date": "July 2026",
                "exam_date": "September 2026",
                "vacancies": "15,000 (approx)",
                "application_fee": "INR 100",
                "status": "UPCOMING"
            },
            {
                "cycle_year": 2025,
                "cycle_name": "SSC CGL 2025",
                "notification_number": "HQ-C-II01/2025",
                "notification_date": "June 2025",
                "application_start_date": "June 2025",
                "application_end_date": "July 2025",
                "exam_date": "September 2025",
                "vacancies": "17,727",
                "application_fee": "INR 100",
                "status": "APPLICATION_CLOSED"
            }
        ]
    },
    {
        "exam_name": "SSC Combined Higher Secondary Level Examination",
        "full_name": "Staff Selection Commission Combined Higher Secondary (10+2) Level Examination",
        "short_name": "SSC CHSL",
        "source_org": "SSC",
        "conducted_by": "Staff Selection Commission",
        "conducting_organisation": "Staff Selection Commission",
        "organisation_type": "Statutory Commission",
        "government_or_private": "Government",
        "central_or_state": "Central",
        "state": "All India",
        "category": "Central Government Staff",
        "sub_category": "Group C Ministerial & Clerical",
        "opportunity_type": "GOVERNMENT_RECRUITMENT",
        "education_level": "12th",
        "qualification": "12th Standard or Equivalent examination passed from recognized Board/University",
        "minimum_qualification": "Class 12 Pass",
        "streams": "Any Stream (Science with Maths required for DEO in CAG office)",
        "age_min": 18,
        "age_max": 27,
        "age_limit": "18 to 27 years",
        "gender_eligibility": "All",
        "category_eligibility": "General, EWS, OBC, SC, ST, PwD",
        "application_mode": "Online",
        "exam_mode": "Computer Based Test (Tier I & Tier II) + Skill/Typing Test",
        "career_opportunities": "Lower Division Clerk (LDC), Junior Secretariat Assistant (JSA), Data Entry Operator (DEO)",
        "official_website": "https://ssc.gov.in",
        "application_url": "https://ssc.gov.in/apply",
        "frequency": "Annual",
        "fee": "INR 100 (Exempted for Women/SC/ST/PwD)",
        "vacancies": "Approx. 3,700 - 4,500",
        "salary": "Pay Level 2 (INR 19,900 - 63,200) & Level 4 (INR 25,500 - 81,100)",
        "status": "UPCOMING",
        "cycles": [
            {
                "cycle_year": 2026,
                "cycle_name": "SSC CHSL 2026",
                "notification_number": "HQ-C-II02/2026",
                "notification_date": "April 2026",
                "application_start_date": "April 2026",
                "application_end_date": "May 2026",
                "exam_date": "July 2026",
                "vacancies": "4,000 (approx)",
                "application_fee": "INR 100",
                "status": "UPCOMING"
            }
        ]
    },

    # =========================================================================
    # 3. NTA (NATIONAL TESTING AGENCY)
    # =========================================================================
    {
        "exam_name": "Joint Entrance Examination (Main)",
        "full_name": "National Testing Agency JEE (Main)",
        "short_name": "JEE Main",
        "source_org": "NTA",
        "conducted_by": "National Testing Agency",
        "conducting_organisation": "National Testing Agency",
        "organisation_type": "Autonomous Statutory Body",
        "government_or_private": "Government",
        "central_or_state": "Central",
        "state": "All India",
        "category": "Engineering Entrance",
        "sub_category": "National Engineering & Architecture Gateway",
        "opportunity_type": "ENTRANCE_EXAM",
        "education_level": "12th",
        "qualification": "Passed 10+2 examination with Physics, Mathematics and Chemistry/Biology/Technical Vocational subject",
        "minimum_qualification": "Class 12 Pass / Appearing",
        "streams": "Science (PCM / PCMB)",
        "specialisation": "Physics, Chemistry, Mathematics",
        "age_min": 16,
        "age_max": 25,
        "age_limit": "No age limit for appearing in JEE Main (Class 12 qualifying year applies)",
        "gender_eligibility": "All",
        "category_eligibility": "General, GEN-EWS, OBC-NCL, SC, ST, PwD",
        "application_mode": "Online",
        "exam_mode": "Computer Based Test (CBT)",
        "selection_process": "Computer Based Examination (Paper 1 B.E./B.Tech; Paper 2A B.Arch; Paper 2B B.Planning)",
        "subjects": "Physics, Chemistry, Mathematics",
        "number_of_papers": "Paper 1 (90 MCQs / Numerical Value Questions)",
        "duration": "3 Hours (180 Minutes)",
        "negative_marking": "+4 for correct, -1 for incorrect answer in both MCQs and Numerical value questions",
        "career_opportunities": "Admission to 31 NITs, 25 IIITs, 33 GFTIs, and eligibility gateway for JEE Advanced (IITs)",
        "related_courses": "B.Tech, B.E., Integrated M.Tech, B.Arch, B.Planning",
        "related_careers": "Software Engineer, Data Scientist, Mechanical Engineer, Electronics Engineer, Aerospace Engineer",
        "official_website": "https://jeemain.nta.nic.in",
        "application_url": "https://jeemain.nta.nic.in",
        "notification_url": "https://nta.nic.in/Notice",
        "frequency": "Twice a Year (Session 1 January & Session 2 April)",
        "fee": "INR 1,000 (Male Gen/OBC), INR 800 (Female), INR 500 (SC/ST/PwD)",
        "vacancies": "Approx. 60,000+ seats across NITs, IIITs, GFTIs",
        "salary": "Average placement package: INR 8 - 25 LPA across premier institutes",
        "status": "UPCOMING",
        "cycles": [
            {
                "cycle_year": 2026,
                "cycle_name": "JEE (Main) 2026 Session 1",
                "notification_number": "NTA/JEE-MAIN/2026",
                "notification_date": "October 2025",
                "application_start_date": "October 2025",
                "application_end_date": "November 2025",
                "exam_date": "January 2026",
                "application_fee": "INR 1,000",
                "status": "UPCOMING"
            }
        ]
    },
    {
        "exam_name": "National Eligibility cum Entrance Test (UG)",
        "full_name": "National Eligibility cum Entrance Test Undergraduate",
        "short_name": "NEET UG",
        "source_org": "NTA",
        "conducted_by": "National Testing Agency",
        "conducting_organisation": "National Testing Agency",
        "organisation_type": "Autonomous Statutory Body",
        "government_or_private": "Government",
        "central_or_state": "Central",
        "state": "All India",
        "category": "Medical Entrance",
        "sub_category": "National Undergraduate Medical Gateway",
        "opportunity_type": "ENTRANCE_EXAM",
        "education_level": "12th",
        "qualification": "Passed 10+2 with Physics, Chemistry, Biology/Biotechnology and English",
        "minimum_qualification": "Class 12 Pass (50% PCB for General, 40% SC/ST/OBC)",
        "streams": "Science (PCB / PCMB)",
        "specialisation": "Physics, Chemistry, Biology (Botany & Zoology)",
        "age_min": 17,
        "age_max": 25,
        "age_limit": "Completed 17 years by 31st December of admission year. No upper age limit.",
        "gender_eligibility": "All",
        "category_eligibility": "General, EWS, OBC, SC, ST, PwD",
        "application_mode": "Online",
        "exam_mode": "Pen and Paper (OMR)",
        "selection_process": "National Single Entrance Test -> All India (15%) & State (85%) Quota Counselling",
        "subjects": "Physics (45 Qs), Chemistry (45 Qs), Biology - Botany & Zoology (90 Qs)",
        "number_of_papers": "1 Paper (180 Questions to attempt out of 200)",
        "duration": "3 Hours 20 Minutes (200 Minutes)",
        "negative_marking": "+4 for correct, -1 for incorrect",
        "career_opportunities": "Admission to MBBS, BDS, BAMS, BHMS, BUMS, BSMS, BVSc & AH across AIIMS, JIPMER, Government Medical Colleges",
        "related_courses": "MBBS, BDS, BAMS, BHMS, B.Sc Nursing",
        "related_careers": "Medical Doctor, Surgeon, Dentist, Ayurvedic Doctor, Medical Researcher",
        "official_website": "https://exams.nta.ac.in/NEET",
        "application_url": "https://neet.nta.nic.in",
        "frequency": "Annual",
        "fee": "INR 1,700 (General), INR 1,600 (OBC/EWS), INR 1,000 (SC/ST/PwD)",
        "vacancies": "Approx. 1,08,000+ MBBS seats and 28,000+ BDS seats in India",
        "salary": "MBBS Intern Stipend INR 25,000 - 30,000/month; Medical Officer starting INR 65,000 - 1,20,000/month",
        "status": "UPCOMING",
        "cycles": [
            {
                "cycle_year": 2026,
                "cycle_name": "NEET (UG) 2026",
                "notification_number": "NTA/NEET-UG/2026",
                "notification_date": "February 2026",
                "application_start_date": "February 2026",
                "application_end_date": "March 2026",
                "exam_date": "May 2026",
                "application_fee": "INR 1,700",
                "status": "UPCOMING"
            }
        ]
    },
    {
        "exam_name": "Common University Entrance Test (UG)",
        "full_name": "Common University Entrance Test Undergraduate",
        "short_name": "CUET UG",
        "source_org": "NTA",
        "conducted_by": "National Testing Agency",
        "conducting_organisation": "National Testing Agency",
        "organisation_type": "Autonomous Statutory Body",
        "government_or_private": "Government",
        "central_or_state": "Central",
        "state": "All India",
        "category": "University Entrance",
        "sub_category": "Central & Participating State/Private Universities",
        "opportunity_type": "ENTRANCE_EXAM",
        "education_level": "12th",
        "qualification": "Passed 10+2 from recognized Board/Council",
        "minimum_qualification": "Class 12 Pass / Appearing",
        "streams": "Any Stream (Science, Arts, Humanities, Commerce)",
        "age_min": 16,
        "age_max": 25,
        "age_limit": "No age limit for CUET UG (subject to university individual criteria)",
        "gender_eligibility": "All",
        "category_eligibility": "General, OBC, SC, ST, EWS, PwD",
        "application_mode": "Online",
        "exam_mode": "Hybrid (CBT & Pen-Paper OMR)",
        "career_opportunities": "Admission to Delhi University (DU), BHU, JNU, Jamia Millia, AMU, Allahabad University, and 250+ participating universities",
        "related_courses": "BA (Hons), B.Sc (Hons), B.Com (Hons), BBA, BMS, Integrated Law",
        "related_careers": "Economist, Data Analyst, Historian, Media Specialist, Financial Analyst",
        "official_website": "https://exams.nta.ac.in/CUET-UG",
        "application_url": "https://cuetug.ntaonline.in",
        "frequency": "Annual",
        "fee": "INR 1,000 for up to 3 subjects (General), INR 900 (OBC/EWS), INR 800 (SC/ST/PwD)",
        "status": "UPCOMING",
        "cycles": [
            {
                "cycle_year": 2026,
                "cycle_name": "CUET (UG) 2026",
                "notification_number": "NTA/CUET-UG/2026",
                "notification_date": "February 2026",
                "application_start_date": "February 2026",
                "application_end_date": "March 2026",
                "exam_date": "May 2026",
                "status": "UPCOMING"
            }
        ]
    },
    {
        "exam_name": "UGC National Eligibility Test",
        "full_name": "University Grants Commission National Eligibility Test",
        "short_name": "UGC NET",
        "source_org": "NTA",
        "conducted_by": "National Testing Agency",
        "conducting_organisation": "University Grants Commission / NTA",
        "organisation_type": "Statutory Authority",
        "government_or_private": "Government",
        "central_or_state": "Central",
        "state": "All India",
        "category": "Teaching & Research",
        "sub_category": "Assistant Professor & Junior Research Fellowship",
        "opportunity_type": "FELLOWSHIP",
        "education_level": "Post Graduate / PG",
        "degree": "Master Degree",
        "qualification": "Master's Degree or equivalent with minimum 55% marks (50% for SC/ST/OBC/PwD)",
        "minimum_qualification": "Postgraduate Degree (MA, M.Sc, M.Com, MCA, MBA, LLM)",
        "streams": "Humanities, Social Sciences, Commerce, Management, Computer Science, Environmental Sciences (83 Subjects)",
        "age_min": 21,
        "age_max": 30,
        "age_limit": "JRF: Maximum 30 years (5 years relaxation for OBC/SC/ST/PwD/Women). Assistant Professor: No upper age limit.",
        "gender_eligibility": "All",
        "category_eligibility": "General, EWS, OBC-NCL, SC, ST, PwD",
        "application_mode": "Online",
        "exam_mode": "OMR Pen-Paper / Computer Based Test",
        "selection_process": "Paper 1 (General Teaching & Research Aptitude) + Paper 2 (Subject Specific)",
        "subjects": "Teaching Aptitude, Research Aptitude, Higher Education System + 83 Core Humanities/Science Subjects",
        "number_of_papers": "2 Papers (Total 150 Questions, 300 Marks)",
        "duration": "3 Hours (180 Minutes, No Break)",
        "negative_marking": "No negative marking",
        "career_opportunities": "Junior Research Fellow (JRF) in Indian universities, Assistant Professor in Colleges/Universities, Ph.D Admission",
        "related_courses": "M.Sc Mathematics, MA English, M.Com, MBA, MCA, MA Economics",
        "related_careers": "Assistant Professor, University Lecturer, Research Scientist, Policy Analyst",
        "official_website": "https://ugcnet.nta.ac.in",
        "application_url": "https://ugcnet.nta.ac.in",
        "frequency": "Twice a Year (June & December cycles)",
        "fee": "INR 1,150 (General), INR 600 (EWS/OBC-NCL), INR 325 (SC/ST/PwD)",
        "vacancies": "JRF Fellowship awarded to top 6% qualifiers",
        "salary": "JRF Fellowship: INR 37,000/month + HRA for 2 yrs, then SRF INR 42,000/month + HRA; Assistant Professor: Pay Level 10 (INR 57,700 - 1,82,400)",
        "status": "UPCOMING",
        "cycles": [
            {
                "cycle_year": 2026,
                "cycle_name": "UGC NET June 2026",
                "notification_number": "NTA/UGC-NET/JUN-2026",
                "notification_date": "April 2026",
                "application_start_date": "April 2026",
                "application_end_date": "May 2026",
                "exam_date": "June 2026",
                "application_fee": "INR 1,150",
                "status": "UPCOMING"
            }
        ]
    },
    {
        "exam_name": "Joint CSIR-UGC NET for JRF and Lectureship",
        "full_name": "Council of Scientific and Industrial Research NET Examination",
        "short_name": "CSIR NET",
        "source_org": "CSIR - HRDG",
        "conducted_by": "National Testing Agency on behalf of CSIR",
        "conducting_organisation": "CSIR / NTA",
        "organisation_type": "Autonomous Statutory Body",
        "government_or_private": "Government",
        "central_or_state": "Central",
        "state": "All India",
        "category": "Science & Research",
        "sub_category": "Pure Sciences Fellowships & Lectureship",
        "opportunity_type": "RESEARCH_OPPORTUNITY",
        "education_level": "Post Graduate / PG",
        "degree": "M.Sc / Integrated BS-MS / BE / B.Tech / B.Pharma / MBBS",
        "qualification": "M.Sc or equivalent degree with minimum 55% marks for General/OBC (50% for SC/ST/PwD)",
        "minimum_qualification": "Postgraduate in Science or 4-year Professional Degree",
        "streams": "Chemical Sciences, Earth Sciences, Life Sciences, Mathematical Sciences, Physical Sciences",
        "specialisation": "Mathematical Sciences, Physical Sciences, Chemical Sciences, Life Sciences",
        "age_min": 21,
        "age_max": 30,
        "age_limit": "JRF: Maximum 30 years (Relaxation 5 yrs for SC/ST/PwD/Female, 3 yrs for OBC-NCL). Lectureship/Assistant Professor: No age limit.",
        "gender_eligibility": "All",
        "category_eligibility": "General, EWS, OBC, SC, ST, PwD",
        "application_mode": "Online",
        "exam_mode": "Computer Based Test (CBT)",
        "selection_process": "Single paper consisting of Part A (General Aptitude), Part B (Subject MCQs), Part C (Higher value scientific questions)",
        "subjects": "Part A General Aptitude; Part B & C Subject specialization (e.g. Mathematics, Physics, Chemistry, Life Science)",
        "duration": "3 Hours",
        "negative_marking": "25% negative marking for wrong answers",
        "career_opportunities": "Junior Research Fellow in premier CSIR labs, IITs, IISc, IISERs, and Assistant Professorship across Indian Universities",
        "related_courses": "M.Sc Mathematics, M.Sc Physics, M.Sc Chemistry, M.Sc Biotechnology, M.Sc Statistics",
        "related_careers": "Research Scientist, CSIR Scientist, Mathematics Professor, Physicist, Data Scientist",
        "official_website": "https://csirnet.nta.ac.in",
        "application_url": "https://csirnet.nta.ac.in",
        "frequency": "Twice a Year (June & December)",
        "fee": "INR 1,150 (General), INR 600 (OBC/EWS), INR 325 (SC/ST/PwD)",
        "salary": "CSIR JRF: INR 37,000/month + HRA; Contigency grant INR 20,000/annum; Assistant Professor UGC scale",
        "status": "UPCOMING",
        "cycles": [
            {
                "cycle_year": 2026,
                "cycle_name": "Joint CSIR-UGC NET June 2026",
                "notification_number": "NTA/CSIR-NET/JUN-2026",
                "notification_date": "April 2026",
                "application_start_date": "April 2026",
                "application_end_date": "May 2026",
                "exam_date": "June 2026",
                "status": "UPCOMING"
            }
        ]
    },

    # =========================================================================
    # 4. RAILWAYS (RRB / RRC)
    # =========================================================================
    {
        "exam_name": "RRB Non-Technical Popular Categories",
        "full_name": "Railway Recruitment Board Non-Technical Popular Categories (Graduate & Undergraduate)",
        "short_name": "RRB NTPC",
        "source_org": "Indian Railways (RRB / RRC)",
        "conducted_by": "Railway Recruitment Control Board",
        "conducting_organisation": "Ministry of Railways",
        "organisation_type": "Government Department",
        "government_or_private": "Government",
        "central_or_state": "Central",
        "state": "All India",
        "category": "Railways",
        "sub_category": "Executive, Supervisory & Clerical Cadres",
        "opportunity_type": "GOVERNMENT_RECRUITMENT",
        "education_level": "Graduate / UG",
        "qualification": "Graduate Degree in Any Stream (Level 5 & 6); 12th Pass (Level 2 & 3)",
        "minimum_qualification": "Graduate Degree for Graduate Posts; 12th Pass for Undergrad Posts",
        "streams": "Any Stream",
        "age_min": 18,
        "age_max": 36,
        "age_limit": "18 to 33/36 years (with 3-year COVID age relaxation)",
        "age_relaxation": "OBC: 3 yrs, SC/ST: 5 yrs, PwBD: 10 yrs, Ex-Servicemen as per rules",
        "gender_eligibility": "All",
        "category_eligibility": "General, EWS, OBC, SC, ST, PwBD",
        "application_mode": "Online",
        "exam_mode": "Computer Based Test (CBT-1 & CBT-2) + CBAT / Typing Test",
        "selection_process": "1. 1st Stage CBT -> 2. 2nd Stage CBT -> 3. Computer Based Aptitude Test (for Station Master/Traffic Assistant) or Typing Skill Test -> 4. Document Verification & Medical Exam",
        "subjects": "General Awareness (40 Qs), Mathematics (30 Qs), General Intelligence & Reasoning (30 Qs)",
        "negative_marking": "1/3rd mark deducted for wrong answers",
        "career_opportunities": "Station Master, Goods Train Manager (Goods Guard), Junior Accounts Assistant, Senior Clerk cum Typist, Commercial Apprentice",
        "related_courses": "BA, B.Sc, B.Com, B.Tech, BCA",
        "related_careers": "Station Master, Train Traffic Manager, Railway Commercial Officer",
        "official_website": "https://indianrailways.gov.in",
        "application_url": "https://www.rrbapply.gov.in",
        "notification_url": "https://www.rrbapply.gov.in",
        "frequency": "Cyclical / Annual Recruitment Drive",
        "fee": "INR 500 (INR 400 refunded after appearing in CBT-1); INR 250 for SC/ST/Female/PwBD (fully refunded)",
        "vacancies": "11,558 Posts across RRBs",
        "salary": "Pay Level 5 & 6 (INR 29,200 - 35,400 Basic + Running Allowances)",
        "status": "EXAM_SCHEDULED",
        "cycles": [
            {
                "cycle_year": 2025,
                "cycle_name": "RRB NTPC Centralized Employment Notice (CEN 05/2024 & 06/2024)",
                "notification_number": "CEN 05/2024 (Graduate) & CEN 06/2024 (Undergrad)",
                "notification_date": "September 2024",
                "application_start_date": "September 2024",
                "application_end_date": "October 2024",
                "exam_date": "Early 2025",
                "vacancies": "11,558",
                "application_fee": "INR 500",
                "status": "EXAM_SCHEDULED"
            }
        ]
    },
    {
        "exam_name": "RRB Assistant Loco Pilot & Technician",
        "full_name": "Railway Recruitment Board Assistant Loco Pilot (ALP) & Technician",
        "short_name": "RRB ALP",
        "source_org": "Indian Railways (RRB / RRC)",
        "conducted_by": "Railway Recruitment Control Board",
        "conducting_organisation": "Ministry of Railways",
        "organisation_type": "Government Department",
        "government_or_private": "Government",
        "central_or_state": "Central",
        "state": "All India",
        "category": "Railways",
        "sub_category": "Technical & Running Cadre",
        "opportunity_type": "GOVERNMENT_RECRUITMENT",
        "education_level": "Diploma / ITI",
        "qualification": "Matriculation / 10th plus ITI in specified trades OR Diploma / Degree in Mechanical/Electrical/Electronics/Automobile Engineering",
        "minimum_qualification": "10th + ITI or Diploma in Engineering",
        "streams": "Mechanical, Electrical, Electronics, Automobile, ITI Trades (Fitter, Electrician, Wireman, Diesel Mechanic)",
        "age_min": 18,
        "age_max": 33,
        "age_limit": "18 to 33 years",
        "gender_eligibility": "All",
        "category_eligibility": "General, EWS, OBC, SC, ST",
        "application_mode": "Online",
        "exam_mode": "Computer Based Test (CBT-1 & CBT-2) + CBAT (Psychometric Test)",
        "career_opportunities": "Assistant Loco Pilot (ALP), Senior Loco Pilot, Train Driver, Loco Inspector in Indian Railways",
        "official_website": "https://indianrailways.gov.in",
        "application_url": "https://www.rrbapply.gov.in",
        "frequency": "Annual",
        "fee": "INR 500 (INR 400 refundable on appearing in CBT-1)",
        "vacancies": "18,799 vacancies",
        "salary": "Pay Level 2 (INR 19,900 Basic + Running Allowance INR 25,000 - 45,000/month)",
        "status": "EXAM_SCHEDULED",
        "cycles": [
            {
                "cycle_year": 2025,
                "cycle_name": "RRB ALP CEN 01/2024",
                "notification_number": "CEN 01/2024",
                "notification_date": "January 2024",
                "application_start_date": "January 2024",
                "application_end_date": "February 2024",
                "exam_date": "Late 2024 - 2025",
                "vacancies": "18,799",
                "application_fee": "INR 500",
                "status": "EXAM_SCHEDULED"
            }
        ]
    },

    # =========================================================================
    # 5. BANKING & FINANCE (IBPS, RBI, SBI, NABARD, SEBI)
    # =========================================================================
    {
        "exam_name": "IBPS Probationary Officer / Management Trainee",
        "full_name": "Common Recruitment Process for Probationary Officers/Management Trainees (CRP PO/MT)",
        "short_name": "IBPS PO",
        "source_org": "IBPS",
        "conducted_by": "Institute of Banking Personnel Selection",
        "conducting_organisation": "Institute of Banking Personnel Selection",
        "organisation_type": "Autonomous Banking Board",
        "government_or_private": "Government",
        "central_or_state": "Central",
        "state": "All India",
        "category": "Banking & Finance",
        "sub_category": "Public Sector Banks Scale I Officers",
        "opportunity_type": "GOVERNMENT_RECRUITMENT",
        "education_level": "Graduate / UG",
        "degree": "Bachelor Degree",
        "qualification": "A Degree (Graduation) in any discipline from a University recognized by the Govt. Of India",
        "minimum_qualification": "Graduation in Any Stream",
        "streams": "Any Stream (B.Com, B.Sc, BA, B.Tech, BCA, BBA)",
        "age_min": 20,
        "age_max": 30,
        "age_limit": "20 to 30 years",
        "age_relaxation": "OBC: 3 yrs (up to 33), SC/ST: 5 yrs (up to 35), PwBD: 10 yrs (up to 40)",
        "gender_eligibility": "All",
        "category_eligibility": "General, EWS, OBC, SC, ST, PwBD",
        "application_mode": "Online",
        "exam_mode": "Online Computer Based Examination (Prelims & Mains) + Interview",
        "selection_process": "1. Preliminary Examination (Objective, 100 Marks) -> 2. Main Examination (Objective + Descriptive, 225 Marks) -> 3. Common Interview (100 Marks)",
        "subjects": "Quantitative Aptitude, Reasoning Ability, English Language, General & Banking Awareness, Computer Aptitude, Letter & Essay Writing",
        "number_of_papers": "Prelims (3 sections, 60 mins) + Mains (4 sections + Descriptive, 3.5 hrs)",
        "negative_marking": "0.25 marks deducted for each wrong answer",
        "career_opportunities": "Probationary Officer (Scale I) in 11 Participating Public Sector Banks (PNB, BoB, Canara Bank, Union Bank, Bank of India, etc.), with rapid promotion to Manager, AGM, DGM, GM, and Executive Director",
        "related_courses": "B.Com, B.Sc Mathematics, BBA, BA Economics, B.Tech",
        "related_careers": "Bank Manager, Financial Analyst, Credit Officer, Investment Analyst",
        "official_website": "https://www.ibps.in",
        "application_url": "https://ibpsonline.ibps.in",
        "notification_url": "https://www.ibps.in/crp-po-mt",
        "frequency": "Annual",
        "fee": "INR 850 (General/EWS/OBC), INR 175 (SC/ST/PwBD)",
        "vacancies": "Approx. 4,000 - 5,500 posts",
        "salary": "Basic Pay INR 48,480 (in revised bipartite scale), Gross Emoluments INR 65,000 - 75,000/month + Leased Accommodation",
        "status": "UPCOMING",
        "cycles": [
            {
                "cycle_year": 2026,
                "cycle_name": "IBPS PO/MT-XVI 2026",
                "notification_number": "IBPS/CRP-PO/MT-XVI",
                "notification_date": "August 2026",
                "application_start_date": "August 2026",
                "application_end_date": "August 2026",
                "exam_date": "October 2026 (Prelims) / November 2026 (Mains)",
                "vacancies": "4,500 (approx)",
                "application_fee": "INR 850",
                "status": "UPCOMING"
            },
            {
                "cycle_year": 2025,
                "cycle_name": "IBPS PO/MT-XV 2025",
                "notification_number": "IBPS/CRP-PO/MT-XV",
                "notification_date": "August 2025",
                "application_start_date": "August 2025",
                "application_end_date": "August 2025",
                "exam_date": "October 2025",
                "vacancies": "4,455",
                "application_fee": "INR 850",
                "status": "APPLICATION_CLOSED"
            }
        ]
    },
    {
        "exam_name": "RBI Grade B Officer Recruitment",
        "full_name": "Reserve Bank of India Officers in Grade 'B' (General / DEPR / DSIM)",
        "short_name": "RBI Grade B",
        "source_org": "RBI",
        "conducted_by": "Reserve Bank of India Services Board",
        "conducting_organisation": "Reserve Bank of India",
        "organisation_type": "Central Bank / Regulatory Authority",
        "government_or_private": "Government",
        "central_or_state": "Central",
        "state": "All India",
        "category": "Banking & Finance",
        "sub_category": "Apex Central Banking Cadre",
        "opportunity_type": "GOVERNMENT_RECRUITMENT",
        "education_level": "Graduate / UG",
        "qualification": "Graduation in any discipline / Equivalent technical qualification with minimum 60% marks (50% for SC/ST/PwBD) OR Post Graduation with 55% marks",
        "minimum_qualification": "Bachelor's Degree with 60% aggregate",
        "streams": "Any Stream for General; Economics for DEPR; Statistics / Mathematical Sciences / Data Science for DSIM",
        "specialisation": "Economics, Finance, Statistics, Mathematics",
        "age_min": 21,
        "age_max": 30,
        "age_limit": "21 to 30 years (32 years for candidates holding M.Phil and 34 years for Ph.D)",
        "gender_eligibility": "All",
        "category_eligibility": "General, EWS, OBC, SC, ST, PwBD",
        "application_mode": "Online",
        "exam_mode": "Online Computer Based Examination (Phase-I & Phase-II) + Interview",
        "selection_process": "1. Phase-I Online Exam (Objective, 200 Marks) -> 2. Phase-II Exam (Economic & Social Issues, English Writing, Finance & Management, 300 Marks) -> 3. Interview (75 Marks)",
        "career_opportunities": "Assistant Manager Grade B at RBI, progressing to Manager, AGM, DGM, General Manager, Chief General Manager, and Deputy Governor",
        "related_courses": "B.Sc Mathematics, B.Sc Statistics, BA Economics, B.Com, MBA Finance",
        "related_careers": "Central Banker, Monetary Policy Analyst, Financial Regulator, Chief Risk Officer",
        "official_website": "https://opportunities.rbi.org.in",
        "application_url": "https://ibpsonline.ibps.in/rbioffmay24",
        "notification_url": "https://opportunities.rbi.org.in/scripts/Vacancies.aspx",
        "frequency": "Annual",
        "fee": "INR 850 (Gen/OBC/EWS), INR 100 (SC/ST/PwBD)",
        "vacancies": "Approx. 150 - 300 posts",
        "salary": "Basic Pay INR 55,200; Gross Monthly Emoluments approx. INR 1,16,000/month + Full Furnished Official Accommodation & Central Banking Perks",
        "status": "UPCOMING",
        "cycles": [
            {
                "cycle_year": 2026,
                "cycle_name": "RBI Grade B Officers 2026",
                "notification_number": "RBI/2026/Grade-B",
                "notification_date": "July 2026",
                "application_start_date": "July 2026",
                "application_end_date": "August 2026",
                "exam_date": "September 2026 (Phase-I) / October 2026 (Phase-II)",
                "vacancies": "200 (approx)",
                "application_fee": "INR 850",
                "status": "UPCOMING"
            }
        ]
    },
    {
        "exam_name": "SBI Probationary Officer",
        "full_name": "State Bank of India Probationary Officer Recruitment",
        "short_name": "SBI PO",
        "source_org": "SBI",
        "conducted_by": "State Bank of India Central Recruitment & Promotion Department",
        "conducting_organisation": "State Bank of India",
        "organisation_type": "Public Sector Bank",
        "government_or_private": "Government",
        "central_or_state": "Central",
        "state": "All India",
        "category": "Banking & Finance",
        "sub_category": "Premier Public Sector Bank Officer",
        "opportunity_type": "GOVERNMENT_RECRUITMENT",
        "education_level": "Graduate / UG",
        "qualification": "Graduation in any discipline from a recognized University or any equivalent qualification recognized as such by the Central Government",
        "minimum_qualification": "Graduate in Any Discipline",
        "streams": "Any Stream",
        "age_min": 21,
        "age_max": 30,
        "age_limit": "21 to 30 years",
        "gender_eligibility": "All",
        "category_eligibility": "General, EWS, OBC, SC, ST, PwD",
        "application_mode": "Online",
        "exam_mode": "Computer Based Test (Prelims & Mains) + Psychometric Test & Interview/Group Discussion",
        "career_opportunities": "Probationary Officer in SBI, India's largest bank; direct career path to Scale II, III, AGM, DGM, CGM, and Managing Director",
        "official_website": "https://sbi.co.in/web/careers",
        "application_url": "https://bank.sbi/web/careers/current-openings",
        "frequency": "Annual",
        "fee": "INR 750 (General/EWS/OBC), Nil (SC/ST/PwD)",
        "vacancies": "Approx. 2,000 vacancies",
        "salary": "Basic Pay INR 48,480 + 4 advance increments; Total CTC approx. INR 16.5 - 18.0 LPA including lease, perks and performance allowances",
        "status": "UPCOMING",
        "cycles": [
            {
                "cycle_year": 2026,
                "cycle_name": "SBI PO Recruitment 2026",
                "notification_number": "CRPD/PO/2026-27",
                "notification_date": "September 2026",
                "application_start_date": "September 2026",
                "application_end_date": "October 2026",
                "exam_date": "November 2026 (Prelims) / January 2027 (Mains)",
                "vacancies": "2,000 (approx)",
                "application_fee": "INR 750",
                "status": "UPCOMING"
            }
        ]
    },

    # =========================================================================
    # 6. MADHYA PRADESH STATE RECRUITMENT (MPPSC & MPESB)
    # =========================================================================
    {
        "exam_name": "MPPSC State Services Examination",
        "full_name": "Madhya Pradesh Public Service Commission State Services Examination",
        "short_name": "MPPSC SSE",
        "source_org": "MPPSC",
        "conducted_by": "Madhya Pradesh Public Service Commission",
        "conducting_organisation": "Madhya Pradesh Public Service Commission (Indore)",
        "organisation_type": "State Constitutional Body",
        "government_or_private": "Government",
        "central_or_state": "State",
        "state": "Madhya Pradesh",
        "district": "All Districts of MP",
        "category": "State Civil Services",
        "sub_category": "Gazetted Class II & Class III Executive Posts",
        "opportunity_type": "GOVERNMENT_RECRUITMENT",
        "education_level": "Graduate / UG",
        "degree": "Bachelor Degree",
        "qualification": "Graduation degree in any discipline from a recognized University or educational institution established by an Act of Parliament",
        "minimum_qualification": "Graduate Degree in Any Stream",
        "streams": "Any Stream (Science, Arts, Commerce, Engineering, Agriculture)",
        "age_min": 21,
        "age_max": 40,
        "age_limit": "21 to 40 years for Non-Uniformed posts; 21 to 33 years for Uniformed/Police posts (Relaxation 5 years for MP Domicile SC/ST/OBC/Women up to 45 years)",
        "age_relaxation": "MP Domicile SC/ST/OBC/Women: 5 years (up to 45 years)",
        "gender_eligibility": "All (33% horizontal reservation for women in MP)",
        "category_eligibility": "General, OBC, SC, ST, EWS (MP State reservation applies to MP domiciled candidates)",
        "domicile_requirement": "All Indian citizens eligible for Unreserved; MP State Domicile required for state category reservation and age concession",
        "experience_requirement": "Fresher / None",
        "application_mode": "Online",
        "exam_mode": "Offline OMR Prelims & Descriptive Written Mains",
        "selection_process": "1. State Service Preliminary Exam (Paper 1 General Studies + Paper 2 General Aptitude) -> 2. State Service Main Written Exam (6 Descriptive Papers) -> 3. Personality Test / Interview (175 Marks)",
        "subjects": "MP History, Geography, Economy, Polity, General Science, Ethics & Human Values, Hindi & Essay",
        "number_of_papers": "Prelims 2 Papers (400 Marks) + Mains 6 Papers (1500 Marks)",
        "negative_marking": "No negative marking in MPPSC Prelims",
        "career_opportunities": "Deputy Collector, Deputy Superintendent of Police (DSP), Commercial Tax Officer, Chief Municipal Officer, District Registrar, Naib Tehsildar, Excise Sub-Inspector",
        "related_courses": "BA, B.Sc Mathematics, B.Com, B.Tech, B.Sc Agriculture",
        "related_careers": "Deputy Collector, DSP / Police Officer, Naib Tehsildar, Revenue Officer",
        "official_website": "https://mppsc.mp.gov.in",
        "application_url": "https://www.mponline.gov.in",
        "notification_url": "https://mppsc.mp.gov.in/advertisement",
        "admit_card_url": "https://mppsc.mp.gov.in/admit-card",
        "result_url": "https://mppsc.mp.gov.in/results",
        "frequency": "Annual",
        "fee": "INR 500 (Out of state / Unreserved); INR 250 (MP SC/ST/OBC/PwD) + MP Online portal fee INR 40",
        "vacancies": "Approx. 150 - 350 posts per cycle",
        "salary": "Pay Scale INR 56,100 - 1,77,500 (Pay Matrix Level 12 for Deputy Collector/DSP); Level 9/10 for other posts",
        "status": "UPCOMING",
        "cycles": [
            {
                "cycle_year": 2026,
                "cycle_name": "MPPSC State Services Examination 2026",
                "notification_number": "01/2026/MPPSC",
                "notification_date": "December 2025",
                "application_start_date": "January 2026",
                "application_end_date": "February 2026",
                "exam_date": "April 2026",
                "vacancies": "200 (approx)",
                "application_fee": "INR 500",
                "status": "UPCOMING"
            },
            {
                "cycle_year": 2025,
                "cycle_name": "MPPSC State Services Examination 2025",
                "notification_number": "01/2025/MPPSC",
                "notification_date": "December 2024",
                "application_start_date": "January 2025",
                "application_end_date": "February 2025",
                "exam_date": "April 2025",
                "vacancies": "158",
                "application_fee": "INR 500",
                "status": "EXAM_SCHEDULED"
            }
        ]
    },
    {
        "exam_name": "MPESB Group-2 Sub-Group-4 Combined Recruitment",
        "full_name": "Madhya Pradesh Employees Selection Board Group 2 Sub-Group 4 (Patwari & Combined Cadres)",
        "short_name": "MPESB Group 2 Sub-Group 4",
        "source_org": "MPESB",
        "conducted_by": "Madhya Pradesh Employees Selection Board (Bhopal)",
        "conducting_organisation": "Madhya Pradesh Employees Selection Board",
        "organisation_type": "State Statutory Board",
        "government_or_private": "Government",
        "central_or_state": "State",
        "state": "Madhya Pradesh",
        "district": "All MP Districts",
        "category": "State Staff Selection",
        "sub_category": "Revenue & Subordinate Executive Cadres",
        "opportunity_type": "GOVERNMENT_RECRUITMENT",
        "education_level": "Graduate / UG",
        "degree": "Bachelor Degree",
        "qualification": "Graduate in Any Discipline from a recognized university + CPCT Score Card (or within 3 years of joining)",
        "minimum_qualification": "Bachelor's Degree",
        "streams": "Any Stream",
        "age_min": 18,
        "age_max": 40,
        "age_limit": "18 to 40 years (Relaxation up to 45 years for SC/ST/OBC/Women of MP)",
        "gender_eligibility": "All",
        "category_eligibility": "General, OBC, SC, ST, EWS",
        "domicile_requirement": "Madhya Pradesh Employment Portal (MP Rozgar) active registration mandatory",
        "application_mode": "Online",
        "exam_mode": "Computer Based Test (CBT 200 Marks)",
        "selection_process": "Single stage Online CBT (Section A: Science, Hindi, English, Maths; Section B: GK, Computer, Reasoning, Management)",
        "subjects": "General Science, General Hindi, General English, General Mathematics, General Knowledge, Computer Knowledge, Reasoning, Management",
        "number_of_papers": "1 Paper with 8 Sections (200 Marks, 3 Hours)",
        "negative_marking": "No negative marking",
        "career_opportunities": "Patwari (Revenue Inspector subordinate), Junior Accountant, Assistant Auditor, Assistant Manager, Data Entry Operator across MP Government departments",
        "related_courses": "BA, B.Sc, B.Com, BCA, BBA, B.Tech",
        "related_careers": "Patwari, Revenue Assistant, Government Accountant",
        "official_website": "https://esb.mp.gov.in",
        "application_url": "https://esb.mponline.gov.in",
        "notification_url": "https://esb.mp.gov.in/rulebooks",
        "frequency": "Periodic / Annual Drive",
        "fee": "INR 500 (Unreserved), INR 250 (SC/ST/OBC of MP) + portal fee",
        "vacancies": "Approx. 5,000 - 9,000 posts",
        "salary": "Pay Matrix Level 5/6 (INR 25,300 - 80,500 + DA & Allowances)",
        "status": "UPCOMING",
        "cycles": [
            {
                "cycle_year": 2026,
                "cycle_name": "MPESB Group-2 Sub-Group-4 Combined 2026",
                "notification_number": "ESB/G2SG4/2026",
                "notification_date": "Early 2026",
                "application_start_date": "March 2026",
                "application_end_date": "April 2026",
                "exam_date": "June 2026",
                "vacancies": "6,500 (approx)",
                "application_fee": "INR 500",
                "status": "UPCOMING"
            }
        ]
    },

    # =========================================================================
    # 7. SCIENCE, RESEARCH & APEX GATEWAY EXAMS (GATE, JAM, ISRO, DRDO)
    # =========================================================================
    {
        "exam_name": "Graduate Aptitude Test in Engineering",
        "full_name": "Graduate Aptitude Test in Engineering (GATE)",
        "short_name": "GATE",
        "source_org": "GATE - IIT / IISc",
        "conducted_by": "Organizing IIT on behalf of National Coordination Board - GATE",
        "conducting_organisation": "IITs & IISc",
        "organisation_type": "Apex Academic Coordination",
        "government_or_private": "Government",
        "central_or_state": "Central",
        "state": "All India",
        "category": "Engineering & Research Gateway",
        "sub_category": "M.Tech / PhD Admissions & Maharatna/Navratna PSU Recruitment",
        "opportunity_type": "EXAM",
        "education_level": "Graduate / UG",
        "degree": "B.E. / B.Tech / B.Arch / B.Sc (Research) / M.Sc / MCA",
        "qualification": "Currently studying in 3rd or higher year of undergraduate degree OR completed degree in Engineering/Technology/Architecture/Science/Commerce/Arts",
        "minimum_qualification": "3rd Year UG or Graduate in Engineering/Technology/Science",
        "streams": "30 Test Papers including Computer Science, Electrical, Mechanical, Civil, Electronics, Mathematics (MA), Physics (PH), Chemistry (CY), Data Science & AI (DA)",
        "specialisation": "Engineering Disciplines, Mathematics, Statistics, Data Science & AI",
        "age_min": 19,
        "age_max": 50,
        "age_limit": "No age limit for appearing in GATE",
        "gender_eligibility": "All",
        "category_eligibility": "General, EWS, OBC, SC, ST, PwD",
        "application_mode": "Online",
        "exam_mode": "Computer Based Test (CBT)",
        "selection_process": "Single 3-hour computer based examination (65 Questions, 100 Marks)",
        "subjects": "General Aptitude (15 Marks) + Engineering Mathematics / Discrete Mathematics (13 Marks) + Core Discipline (72 Marks)",
        "number_of_papers": "1 Paper (Option to write two papers from permitted combinations)",
        "duration": "3 Hours (180 Minutes)",
        "negative_marking": "1/3 mark for 1-mark MCQs; 2/3 mark for 2-mark MCQs. No negative marking for MSQs and NATs.",
        "career_opportunities": "Direct PSU Recruitment as Executive Trainee / Engineer (ONGC, IOCL, NTPC, BHEL, GAIL, PowerGrid, BARC, DRDO, NPCIL) and M.Tech/Ph.D at IISc, IITs, NITs with MHRD monthly stipend of INR 12,400",
        "related_courses": "B.Tech, B.Sc Mathematics, M.Sc Mathematics, MCA",
        "related_careers": "PSU Executive Engineer, Scientist / Research Engineer, AI/ML Researcher, M.Tech Scholar",
        "official_website": "https://gate2026.iitd.ac.in",
        "application_url": "https://goaps.iitd.ac.in",
        "frequency": "Annual (Every February)",
        "fee": "INR 1,800 (Regular period, General/OBC), INR 900 (Female/SC/ST/PwD)",
        "salary": "PSU Executive Trainee starting CTC: INR 15 - 24 LPA; MHRD M.Tech Stipend INR 12,400/month",
        "status": "UPCOMING",
        "cycles": [
            {
                "cycle_year": 2026,
                "cycle_name": "GATE 2026",
                "notification_number": "GATE-2026",
                "notification_date": "August 2025",
                "application_start_date": "August 2025",
                "application_end_date": "September 2025",
                "exam_date": "February 2026",
                "application_fee": "INR 1,800",
                "status": "UPCOMING"
            }
        ]
    },
    {
        "exam_name": "Joint Admission test for Masters",
        "full_name": "Joint Admission test for Masters (JAM)",
        "short_name": "IIT JAM",
        "source_org": "IIT JAM Committee",
        "conducted_by": "Organizing IIT on behalf of Ministry of Education",
        "conducting_organisation": "Indian Institutes of Technology (IITs)",
        "organisation_type": "Apex Academic Coordination",
        "government_or_private": "Government",
        "central_or_state": "Central",
        "state": "All India",
        "category": "Science & Research",
        "sub_category": "M.Sc & Integrated PhD at IITs / IISc",
        "opportunity_type": "ENTRANCE_EXAM",
        "education_level": "Graduate / UG",
        "degree": "B.Sc / BS / B.Stat / B.Math",
        "qualification": "Undergraduate degree in Science or related discipline with no aggregate percentage restriction (Pass degree mandatory)",
        "minimum_qualification": "B.Sc / Undergraduate Degree in Science/Mathematics/Economics",
        "streams": "Mathematical Statistics (MS), Mathematics (MA), Physics (PH), Chemistry (CY), Biotechnology (BT), Geology (GG), Economics (EN)",
        "specialisation": "Mathematics, Mathematical Statistics, Physics, Chemistry, Economics",
        "age_min": 19,
        "age_max": 40,
        "age_limit": "No age limit for appearing in JAM",
        "gender_eligibility": "All",
        "category_eligibility": "General, EWS, OBC-NCL, SC, ST, PwD",
        "application_mode": "Online",
        "exam_mode": "Computer Based Test (CBT)",
        "selection_process": "Single 3-hour examination with 60 questions (100 marks) divided into Section A (MCQs), Section B (MSQs), Section C (NATs)",
        "subjects": "Core Discipline (e.g. Real Analysis, Linear Algebra, Group Theory, Multivariable Calculus, Differential Equations for Mathematics)",
        "duration": "3 Hours",
        "career_opportunities": "Admission to M.Sc, M.Sc-Ph.D Dual Degree, Joint M.Sc-Ph.D at 21 IITs, IISc Bangalore, and NITs/IISERs through CCMN; leading to high-paying data science, quantitative research, and doctoral careers",
        "related_courses": "B.Sc Mathematics, B.Sc Statistics, B.Sc Physics, B.Sc Chemistry",
        "related_careers": "Quantitative Analyst, Data Scientist, Research Scientist, Mathematics Professor",
        "official_website": "https://jam2026.iitb.ac.in",
        "application_url": "https://joaps.iitb.ac.in",
        "frequency": "Annual (Every February)",
        "fee": "INR 1,800 for 1 paper (General/OBC), INR 900 (Female/SC/ST/PwD)",
        "salary": "IIT M.Sc graduates placement average: INR 10 - 22 LPA in analytics, finance, fintech and tech roles",
        "status": "UPCOMING",
        "cycles": [
            {
                "cycle_year": 2026,
                "cycle_name": "IIT JAM 2026",
                "notification_number": "JAM-2026",
                "notification_date": "September 2025",
                "application_start_date": "September 2025",
                "application_end_date": "October 2025",
                "exam_date": "February 2026",
                "application_fee": "INR 1,800",
                "status": "UPCOMING"
            }
        ]
    },
    {
        "exam_name": "ISRO Scientist / Engineer 'SC' Recruitment",
        "full_name": "ISRO Centralised Recruitment Board Scientist/Engineer 'SC'",
        "short_name": "ISRO ICRB Scientist 'SC'",
        "source_org": "ISRO",
        "conducted_by": "ISRO Centralised Recruitment Board (ICRB)",
        "conducting_organisation": "Indian Space Research Organisation (Department of Space)",
        "organisation_type": "Government Department / Space Agency",
        "government_or_private": "Government",
        "central_or_state": "Central",
        "state": "All India",
        "category": "Science & Space Research",
        "sub_category": "Scientist / Group A Gazetted Equivalent",
        "opportunity_type": "GOVERNMENT_RECRUITMENT",
        "education_level": "Graduate / UG",
        "degree": "B.E. / B.Tech / B.Sc (Engg)",
        "qualification": "First Class B.E/B.Tech with aggregate minimum 65% marks (average of all semesters) or 6.84 CGPA on 10 point scale",
        "minimum_qualification": "B.E./B.Tech in First Class",
        "streams": "Electronics, Mechanical, Computer Science, Electrical, Civil, Physics, Mathematics",
        "specialisation": "Electronics & Communication, Mechanical Engineering, Computer Science Engineering",
        "age_min": 21,
        "age_max": 28,
        "age_limit": "28 years (Relaxation: OBC 3 yrs, SC/ST 5 yrs)",
        "gender_eligibility": "All",
        "category_eligibility": "General, EWS, OBC, SC, ST, PwD",
        "application_mode": "Online",
        "exam_mode": "Computer Based Test (Written) + Technical Interview",
        "selection_process": "1. Written Test (Discipline Specific 80 marks + Aptitude 20 marks) -> 2. Interview (100 Marks, qualifying 60%)",
        "career_opportunities": "Scientist/Engineer 'SC' in VSSC, URSC, SAC, LPSC, SDSC SHAR, NRSC, leading India's lunar, planetary, human spaceflight (Gaganyaan), and satellite missions",
        "related_courses": "B.Tech Electronics, B.Tech Mechanical, B.Tech Computer Science, B.Tech Aerospace",
        "related_careers": "Space Scientist, Aerospace Engineer, Satellite Systems Engineer, Rocket Propulsion Engineer",
        "official_website": "https://www.isro.gov.in",
        "application_url": "https://www.isro.gov.in/Careers.html",
        "notification_url": "https://www.isro.gov.in/Careers.html",
        "frequency": "Periodic Recruitment Cycle",
        "fee": "INR 250 (Exempted for Women/SC/ST/PwBD)",
        "vacancies": "Approx. 300 - 500 posts",
        "salary": "Pay Level 10 (Basic Pay INR 56,100 + DA + HRA + Special Allowance, Gross approx. INR 95,000/month)",
        "status": "UPCOMING",
        "cycles": [
            {
                "cycle_year": 2026,
                "cycle_name": "ISRO ICRB Scientist 'SC' 2026",
                "notification_number": "ISRO:ICRB:01:2026",
                "notification_date": "May 2026",
                "application_start_date": "May 2026",
                "application_end_date": "June 2026",
                "exam_date": "August 2026",
                "vacancies": "350 (approx)",
                "application_fee": "INR 250",
                "status": "UPCOMING"
            }
        ]
    },
    {
        "exam_name": "DRDO CEPTAM Senior Technical Assistant & Technician",
        "full_name": "Centre for Personnel Talent Management (CEPTAM) Technical Recruitment",
        "short_name": "DRDO CEPTAM",
        "source_org": "DRDO",
        "conducted_by": "Centre for Personnel Talent Management (DRDO)",
        "conducting_organisation": "Defence Research & Development Organisation",
        "organisation_type": "Government Department / Defence R&D",
        "government_or_private": "Government",
        "central_or_state": "Central",
        "state": "All India",
        "category": "Defence & Science Research",
        "sub_category": "Technical & Scientific Cadre",
        "opportunity_type": "GOVERNMENT_RECRUITMENT",
        "education_level": "Graduate / Diploma",
        "degree": "B.Sc in relevant subject or 3-year Diploma in Engineering",
        "qualification": "B.Sc degree in Mathematics/Physics/Chemistry/Computer Science OR 3-year Diploma in Engineering for STA-B; 10th + ITI for Tech-A",
        "minimum_qualification": "B.Sc in Science or Diploma in Engineering",
        "streams": "Mathematics, Physics, Chemistry, Computer Science, Mechanical, Electrical, Electronics",
        "specialisation": "Mathematics, Physics, Computer Science",
        "age_min": 18,
        "age_max": 28,
        "age_limit": "18 to 28 years (Relaxation: OBC 3 yrs, SC/ST 5 yrs)",
        "gender_eligibility": "All",
        "category_eligibility": "General, EWS, OBC, SC, ST, PwD",
        "application_mode": "Online",
        "exam_mode": "Computer Based Test (Tier-I CBT Screening + Tier-II CBT Selection)",
        "career_opportunities": "Senior Technical Assistant 'B' (STA-B) in DRDO laboratories across India (missiles, radar, electronic warfare, naval systems)",
        "related_courses": "B.Sc Mathematics, B.Sc Physics, B.Sc Computer Science, Diploma in Mechanical/Electronics",
        "related_careers": "Defence Scientist Assistant, Technical Officer, Scientific Officer",
        "official_website": "https://www.drdo.gov.in",
        "application_url": "https://www.drdo.gov.in/careers",
        "frequency": "Annual / Biennial Drive",
        "fee": "INR 100 (Women/SC/ST/PwD Exempted)",
        "vacancies": "Approx. 1,900 vacancies",
        "salary": "Pay Level 6 (INR 35,400 to 1,12,400 + DA, HRA, Transport Allowance)",
        "status": "UPCOMING",
        "cycles": [
            {
                "cycle_year": 2026,
                "cycle_name": "DRDO CEPTAM-11 Recruitment 2026",
                "notification_number": "CEPTAM-11/STA-B",
                "notification_date": "April 2026",
                "application_start_date": "April 2026",
                "application_end_date": "May 2026",
                "exam_date": "July 2026",
                "vacancies": "2,000 (approx)",
                "application_fee": "INR 100",
                "status": "UPCOMING"
            }
        ]
    },

    # =========================================================================
    # 8. APPRENTICESHIP SCHEMES & NATIONAL CAREER SERVICE (NATS, NAPS, NCS)
    # =========================================================================
    {
        "exam_name": "National Apprenticeship Training Scheme",
        "full_name": "Ministry of Education National Apprenticeship Training Scheme for Graduates and Diploma Holders",
        "short_name": "NATS Apprenticeship",
        "source_org": "NATS - Ministry of Education",
        "conducted_by": "Board of Practical Training (BOPT) & Board of Apprenticeship Training (BOAT)",
        "conducting_organisation": "Ministry of Education (Govt. of India)",
        "organisation_type": "Statutory Government Scheme",
        "government_or_private": "Government",
        "central_or_state": "Central",
        "state": "All India",
        "category": "Apprenticeship & Skill",
        "sub_category": "One-Year Practical Industry Training Program",
        "opportunity_type": "APPRENTICESHIP",
        "education_level": "Graduate / Diploma",
        "degree": "Graduate in Engineering, Technology, General Streams (BA, B.Sc, B.Com) or Diploma",
        "qualification": "Passed Degree in Engineering/Technology/Humanities/Science/Commerce OR 3-year Diploma in Engineering from a recognized institution",
        "minimum_qualification": "Graduate Degree (General or Technical) or Diploma",
        "streams": "All Streams: B.Sc Mathematics, B.Sc Physics, B.Com, BA, B.Tech, Diploma in Engineering",
        "specialisation": "All disciplines",
        "age_min": 18,
        "age_max": 28,
        "age_limit": "Minimum 18 years; eligible within 3 years of passing graduation/diploma",
        "gender_eligibility": "All",
        "category_eligibility": "General, EWS, OBC, SC, ST, PwD",
        "application_mode": "Online (Direct Student Portal)",
        "exam_mode": "Merit / Academic Marks & Industry Interview (No Entrance Examination)",
        "selection_process": "Online Registration -> Establishment Vacancy Application -> Merit Screening & Selection Interview -> 1-Year Apprenticeship Contract",
        "career_opportunities": "1-Year on-the-job training in Central PSUs (BHEL, IOCL, ONGC, HAL, ISRO, DRDO) and leading private industries; award of National Certificate of Proficiency; preferred absorption into permanent roles",
        "related_courses": "B.Sc Mathematics, B.Sc Physics, B.Com, B.Tech, Diploma in Engineering",
        "related_careers": "Graduate Apprentice Trainee, Junior Project Engineer, Technical Specialist",
        "official_website": "https://nats.education.gov.in",
        "application_url": "https://nats.education.gov.in/student_type.php",
        "notification_url": "https://nats.education.gov.in",
        "frequency": "Continuous / Year-Round Open Enrollments",
        "fee": "Free / Nil Application Fee",
        "vacancies": "1,00,000+ apprenticeship training slots annually",
        "salary": "Statutory Government Monthly Stipend: INR 9,000/month for Graduates (50% DBT from Govt); INR 8,000/month for Diploma holders",
        "status": "APPLICATION_OPEN",
        "cycles": [
            {
                "cycle_year": 2026,
                "cycle_name": "NATS National Engagement Cycle 2026",
                "notification_number": "NATS/2026-REG",
                "notification_date": "January 2026",
                "application_start_date": "January 2026",
                "application_end_date": "December 2026",
                "vacancies": "1,50,000 slots",
                "application_fee": "Free",
                "salary_or_stipend": "INR 9,000/month",
                "status": "APPLICATION_OPEN"
            }
        ]
    },
    {
        "exam_name": "Apprenticeship India - National Apprenticeship Promotion Scheme",
        "full_name": "Ministry of Skill Development & Entrepreneurship NAPS Portal",
        "short_name": "Apprenticeship India (NAPS)",
        "source_org": "MSDE / NSDC",
        "conducted_by": "National Skill Development Corporation / MSDE",
        "conducting_organisation": "Ministry of Skill Development & Entrepreneurship",
        "organisation_type": "Government Scheme",
        "government_or_private": "Government",
        "central_or_state": "Central",
        "state": "All India",
        "category": "Apprenticeship & Skill",
        "sub_category": "Trade & Non-Engineering Industry Apprenticeships",
        "opportunity_type": "APPRENTICESHIP",
        "education_level": "10th / 12th / ITI / Graduate",
        "qualification": "10th, 12th, ITI Pass, or Graduate in any discipline",
        "minimum_qualification": "Class 10th / 12th / ITI / Graduation",
        "streams": "Any Stream",
        "age_min": 14,
        "age_max": 35,
        "age_limit": "Minimum 14 years (18 years for hazardous industries)",
        "gender_eligibility": "All",
        "category_eligibility": "General, EWS, OBC, SC, ST, PwD",
        "application_mode": "Online",
        "exam_mode": "Selection based on merit and company interview",
        "career_opportunities": "Apprentice positions across banking, automotive, logistics, retail, information technology, electronics and power sectors",
        "official_website": "https://www.apprenticeshipindia.gov.in",
        "application_url": "https://www.apprenticeshipindia.gov.in/candidate-registration",
        "frequency": "Rolling / Continuous",
        "fee": "Free",
        "vacancies": "5,00,000+ active apprenticeships across India",
        "salary": "Stipend INR 6,000 - 15,000/month (with Govt sharing up to INR 1,500/month)",
        "status": "APPLICATION_OPEN",
        "cycles": [
            {
                "cycle_year": 2026,
                "cycle_name": "NAPS Nationwide Active Cycle 2026",
                "notification_number": "MSDE/NAPS/2026",
                "notification_date": "January 2026",
                "application_start_date": "January 2026",
                "application_end_date": "December 2026",
                "vacancies": "5,00,000+",
                "application_fee": "Free",
                "salary_or_stipend": "INR 7,000 - 15,000/month",
                "status": "APPLICATION_OPEN"
            }
        ]
    },

    # =========================================================================
    # 9. LAW & DESIGN ENTRANCE (CLAT & NID)
    # =========================================================================
    {
        "exam_name": "Common Law Admission Test (UG & PG)",
        "full_name": "Consortium of National Law Universities Common Law Admission Test",
        "short_name": "CLAT",
        "source_org": "Consortium of NLUs (CLAT)",
        "conducted_by": "Consortium of National Law Universities",
        "conducting_organisation": "Consortium of National Law Universities",
        "organisation_type": "Statutory University Consortium",
        "government_or_private": "Government",
        "central_or_state": "Central",
        "state": "All India",
        "category": "Law Entrance",
        "sub_category": "National Law Universities Undergraduate & Postgraduate Gateway",
        "opportunity_type": "ENTRANCE_EXAM",
        "education_level": "12th / Graduate",
        "degree": "10+2 for UG; LL.B for PG",
        "qualification": "Passed 10+2 or equivalent with minimum 45% marks (40% for SC/ST) for UG CLAT; LL.B with 50% for PG CLAT",
        "minimum_qualification": "Class 12 Pass (UG) or LL.B (PG)",
        "streams": "Any Stream (Arts, Commerce, Science, Humanities)",
        "age_min": 17,
        "age_max": 35,
        "age_limit": "No upper age limit for UG and PG CLAT",
        "gender_eligibility": "All",
        "category_eligibility": "General, OBC, SC, ST, EWS, PwD",
        "application_mode": "Online",
        "exam_mode": "Offline Pen and Paper (OMR)",
        "selection_process": "Single 2-hour offline examination (120 Questions, 120 Marks) -> Centralized Counselling for 24 NLUs",
        "subjects": "English Language, Current Affairs including General Knowledge, Legal Reasoning, Logical Reasoning, Quantitative Techniques",
        "duration": "2 Hours (120 Minutes)",
        "negative_marking": "0.25 marks deducted for wrong answers",
        "career_opportunities": "Admission to 24 National Law Universities (NLSIU Bengaluru, NALSAR Hyderabad, WBNUJS Kolkata, NLU Jodhpur, etc.) for 5-Year Integrated BA/BBA/B.Sc LL.B; pathway to Corporate Law, Litigation, Judicial Services, and PSU Legal Advisers",
        "related_courses": "BA LL.B (Hons), BBA LL.B (Hons), LL.M",
        "related_careers": "Corporate Lawyer, Advocate / Litigator, Judge / Judicial Magistrate, Legal Consultant, PSU Law Officer",
        "official_website": "https://consortiumofnlus.ac.in",
        "application_url": "https://consortiumofnlus.ac.in/clat-2026",
        "frequency": "Annual (Conducted every December for succeeding academic year)",
        "fee": "INR 4,000 (General/OBC), INR 3,500 (SC/ST/PwD)",
        "vacancies": "Approx. 3,500 UG seats and 1,500 PG seats across NLUs",
        "salary": "Top NLU law firm placement starting CTC: INR 15 - 22 LPA",
        "status": "UPCOMING",
        "cycles": [
            {
                "cycle_year": 2026,
                "cycle_name": "CLAT 2026",
                "notification_number": "CNLU/CLAT-2026",
                "notification_date": "July 2025",
                "application_start_date": "July 2025",
                "application_end_date": "October 2025",
                "exam_date": "December 2025",
                "vacancies": "3,500",
                "application_fee": "INR 4,000",
                "status": "UPCOMING"
            }
        ]
    },
    {
        "exam_name": "NID Design Aptitude Test (DAT)",
        "full_name": "National Institute of Design - Design Aptitude Test",
        "short_name": "NID DAT",
        "source_org": "NID",
        "conducted_by": "National Institute of Design",
        "conducting_organisation": "National Institute of Design (Ahmedabad)",
        "organisation_type": "Institute of National Importance",
        "government_or_private": "Government",
        "central_or_state": "Central",
        "state": "All India",
        "category": "Design Entrance",
        "sub_category": "Premier National Design Degree Admission",
        "opportunity_type": "ENTRANCE_EXAM",
        "education_level": "12th / Graduate",
        "degree": "10+2 for B.Des; Bachelor Degree for M.Des",
        "qualification": "Passed 10+2 in any stream (Science, Arts, Commerce, Humanities) from a recognized board",
        "minimum_qualification": "Class 12 Pass (B.Des) or Bachelor Degree (M.Des)",
        "streams": "Any Stream",
        "age_min": 17,
        "age_max": 24,
        "age_limit": "Up to 20/24 years depending on category",
        "gender_eligibility": "All",
        "category_eligibility": "General, EWS, OBC-NCL, SC, ST, PwD",
        "application_mode": "Online",
        "exam_mode": "DAT Prelims (Pen & Paper / Sketching + MCQs) & DAT Mains (Studio Test & Personal Interview)",
        "selection_process": "Stage 1: DAT Prelims (Written + Drawing) -> Stage 2: DAT Mains (Studio Test)",
        "subjects": "Visual Design, Creative Thinking, Observation & Perception, Drawing Skills, General Knowledge",
        "career_opportunities": "Admission to B.Des and M.Des programs across NID Ahmedabad, Andhra Pradesh, Haryana, Madhya Pradesh, and Assam",
        "related_courses": "Bachelor of Design (B.Des), Master of Design (M.Des)",
        "related_careers": "Product Designer, UI/UX Designer, Industrial Designer, Communication Designer, Animation Film Designer",
        "official_website": "https://admissions.nid.edu",
        "application_url": "https://admissions.nid.edu",
        "frequency": "Annual",
        "fee": "INR 3,000 (General/OBC), INR 1,500 (SC/ST/PwD)",
        "vacancies": "425 B.Des seats across 5 NID campuses",
        "salary": "NID graduate placements: Average INR 12 - 25 LPA across tech, automotive, and design consultancies",
        "status": "UPCOMING",
        "cycles": [
            {
                "cycle_year": 2026,
                "cycle_name": "NID DAT 2026",
                "notification_number": "NID/DAT-2026",
                "notification_date": "September 2025",
                "application_start_date": "September 2025",
                "application_end_date": "December 2025",
                "exam_date": "January 2026",
                "vacancies": "425",
                "application_fee": "INR 3,000",
                "status": "UPCOMING"
            }
        ]
    }
]
