"""
National Verified Statutory & Flagship Internship Catalog.
Contains genuine, publicly established statutory government programmes,
PSU drives, premier research institute fellowships, state missions,
and verified corporate flagship internships across India.
"""

from typing import List, Dict, Any

NATIONAL_INTERNSHIP_RECORDS: List[Dict[str, Any]] = [
    # =========================================================================
    # 1. AICTE / MoHUA STATUTORY HUBS: TULIP & URBAN LOCAL BODIES
    # =========================================================================
    {
        "title": "Urban Planning & Smart Mobility Intern",
        "organisation_name": "TULIP - The Urban Learning Internship Program",
        "organisation_type": "Government",
        "industry": "Urban Development",
        "category": "Civil & Architecture",
        "scheme_name": "TULIP Urban Learning Internship",
        "programme_name": "Smart Cities Mission",
        "department": "Ministry of Housing and Urban Affairs (MoHUA)",
        "work_mode": "Onsite",
        "location": "New Delhi, Delhi",
        "city": "New Delhi",
        "state": "Delhi",
        "duration": "6 Months",
        "stipend": "₹15,000 / Month",
        "eligible_degrees": "B.Tech (Civil), B.Arch, B.Plan, Master of Planning",
        "eligibility": "Indian citizens who have graduated within 18 months or are in their final year of graduation/post-graduation.",
        "skills": "AutoCAD, GIS, Urban Data Analysis, Sustainable Transport, Traffic Engineering",
        "description": "TULIP is a joint statutory initiative of Ministry of Housing and Urban Affairs (MoHUA) and AICTE providing experiential learning opportunities to Indian youth in Urban Local Bodies (ULBs) and Smart City SPVs.",
        "responsibilities": "Assist ULBs with smart parking blueprints, pedestrian infrastructure assessments, and municipal GIS database modernization.",
        "official_application_url": "https://internship.aicte-india.org/internships",
        "official_website": "https://internship.aicte-india.org/",
        "source_name": "AICTE National Internship Portal",
        "source_record_id": "tulip-smart-mobility-2026",
        "source_url": "https://internship.aicte-india.org/",
        "academic_credit_available": True,
        "certificate_available": True,
        "ppo_available": False,
        "number_of_openings": 25,
        "application_deadline": "2026-11-30"
    },
    {
        "title": "Municipal GIS & Spatial Mapping Intern",
        "organisation_name": "TULIP - The Urban Learning Internship Program",
        "organisation_type": "Government",
        "industry": "Geoinformatics",
        "category": "Technology",
        "scheme_name": "TULIP Urban Learning Internship",
        "programme_name": "AMRUT 2.0 GIS Cadastre",
        "department": "Ministry of Housing and Urban Affairs (MoHUA)",
        "work_mode": "Onsite",
        "location": "Bhopal, Madhya Pradesh",
        "city": "Bhopal",
        "state": "Madhya Pradesh",
        "duration": "3 Months",
        "stipend": "₹12,000 / Month",
        "eligible_degrees": "B.Tech (Civil/CSE), B.Sc (Geology), M.Sc (Geoinformatics)",
        "eligibility": "Students or recent graduates within 18 months of qualifying degree.",
        "skills": "QGIS, ArcGIS, Python, Remote Sensing, Spatial Data Analysis",
        "description": "Engage with Bhopal Smart City Development Corporation on AMRUT 2.0 water pipeline mapping and municipal property georeferencing.",
        "responsibilities": "Collect ground control points, digitize utility networks, and build web GIS dashboards for municipal engineers.",
        "official_application_url": "https://internship.aicte-india.org/internships",
        "official_website": "https://internship.aicte-india.org/",
        "source_name": "AICTE National Internship Portal",
        "source_record_id": "tulip-gis-amrut-mp-2026",
        "source_url": "https://internship.aicte-india.org/",
        "academic_credit_available": True,
        "certificate_available": True,
        "number_of_openings": 15,
        "application_deadline": "2026-12-15"
    },

    # =========================================================================
    # 2. DEFENCE & STRATEGIC HUBS: INDIAN ARMY CYBER CELL & DRDO
    # =========================================================================
    {
        "title": "Cyber Threat Intelligence Intern",
        "organisation_name": "Indian Army Cyber Security Cell",
        "organisation_type": "Defence",
        "industry": "Cybersecurity & Defence",
        "category": "Cybersecurity",
        "scheme_name": "Army Cyber Corps Student Internship",
        "programme_name": "Integrated Defence Cyber Initiative",
        "department": "Headquarters Integrated Defence Staff (HQ IDS)",
        "work_mode": "Onsite",
        "location": "New Delhi, Delhi",
        "city": "New Delhi",
        "state": "Delhi",
        "duration": "6 Months",
        "stipend": "₹20,000 / Month",
        "eligible_degrees": "B.Tech (CSE, IT, Cyber Security), M.Tech, MCA",
        "eligibility": "Indian citizens only with strict background verification. Pre-final or final year engineering students with minimum 65% aggregate.",
        "skills": "Network Forensics, Reverse Engineering, Wireshark, Malware Analysis, Python, Linux",
        "description": "Collaborate directly with defence cyber specialists on tactical log analytics, threat simulation, and perimeter hardening under national statutory norms.",
        "responsibilities": "Investigate anomalous telemetry data, assist in red/blue team simulations, and construct indicators of compromise (IoC) rule libraries.",
        "official_application_url": "https://internship.aicte-india.org/dashboards/indianarmy/internship-list",
        "official_website": "https://internship.aicte-india.org/",
        "source_name": "AICTE Indian Army Dashboard",
        "source_record_id": "army-cyber-intel-2026",
        "source_url": "https://internship.aicte-india.org/dashboards/indianarmy/internship-list",
        "academic_credit_available": True,
        "certificate_available": True,
        "ppo_available": False,
        "number_of_openings": 20,
        "application_deadline": "2026-12-05"
    },
    {
        "title": "AI & Autonomous Systems Research Trainee",
        "organisation_name": "DRDO - Centre for Artificial Intelligence and Robotics (CAIR)",
        "organisation_type": "Research Institute",
        "industry": "Defence R&D",
        "category": "AI / Machine Learning",
        "scheme_name": "DRDO Student Project Scheme",
        "department": "Defence Research & Development Organisation",
        "work_mode": "Onsite",
        "location": "Bengaluru, Karnataka",
        "city": "Bengaluru",
        "state": "Karnataka",
        "duration": "6 Months",
        "stipend": "₹18,000 / Month",
        "eligible_degrees": "B.Tech / M.Tech in CSE, AI, Robotics, Data Science",
        "eligibility": "Bona fide engineering students with institutional NOC. Consistent 70%+ academic record.",
        "skills": "ROS (Robot Operating System), PyTorch, Computer Vision, SLAM, C++, Python",
        "description": "Work inside DRDO CAIR Bangalore on computer vision models for uncrewed ground vehicles and decision support algorithms.",
        "responsibilities": "Implement sensor fusion algorithms, benchmark deep neural networks on embedded edge compute boards.",
        "official_application_url": "https://www.drdo.gov.in/drdo/labs-and-establishments/centre-artificial-intelligence-and-robotics-cair",
        "official_website": "https://www.drdo.gov.in/",
        "source_name": "DRDO Official Portal",
        "source_record_id": "drdo-cair-ai-trainee-2026",
        "source_url": "https://www.drdo.gov.in/",
        "academic_credit_available": True,
        "certificate_available": True,
        "number_of_openings": 10,
        "application_deadline": "2026-12-20"
    },

    # =========================================================================
    # 3. HIGHWAYS & INFRASTRUCTURE: NHAI & MoRTH
    # =========================================================================
    {
        "title": "Highway Asset Management & Drone Survey Intern",
        "organisation_name": "National Highways Authority of India (NHAI)",
        "organisation_type": "Government",
        "industry": "Infrastructure & Transportation",
        "category": "Civil & Architecture",
        "scheme_name": "NHAI Institutional Internship Scheme",
        "programme_name": "Bharatmala Pariyojana Monitoring",
        "department": "Ministry of Road Transport and Highways (MoRTH)",
        "work_mode": "Hybrid",
        "location": "New Delhi, Delhi",
        "city": "New Delhi",
        "state": "Delhi",
        "duration": "3 Months",
        "stipend": "₹15,000 / Month",
        "eligible_degrees": "B.Tech (Civil Engineering, Transportation), M.Tech",
        "eligibility": "Students enrolled in AICTE/UGC approved institutes entering 3rd or 4th year.",
        "skills": "Pavement Engineering, Drone Photogrammetry, CAD, Project Management, Quality Auditing",
        "description": "Analyze drone video feeds and LiDAR point clouds for national expressways and monitor automated tolling asset performance.",
        "responsibilities": "Audit road safety audit reports, assist field project directors in monitoring concessionaire milestone compliance.",
        "official_application_url": "https://nhai.gov.in/",
        "official_website": "https://nhai.gov.in/",
        "source_name": "NHAI Official Portal",
        "source_record_id": "nhai-asset-survey-2026",
        "source_url": "https://nhai.gov.in/",
        "academic_credit_available": True,
        "certificate_available": True,
        "number_of_openings": 30,
        "application_deadline": "2026-12-10"
    },

    # =========================================================================
    # 4. ADVANCED COMPUTING & MEITY: C-DAC
    # =========================================================================
    {
        "title": "Supercomputing & Quantum Algorithms Trainee",
        "organisation_name": "C-DAC - Centre for Development of Advanced Computing",
        "organisation_type": "Research Institute",
        "industry": "High Performance Computing",
        "category": "Technology",
        "scheme_name": "National Supercomputing Mission (NSM)",
        "department": "Ministry of Electronics and Information Technology (MeitY)",
        "work_mode": "Hybrid",
        "location": "Pune, Maharashtra",
        "city": "Pune",
        "state": "Maharashtra",
        "duration": "6 Months",
        "stipend": "₹18,000 / Month",
        "eligible_degrees": "B.Tech / M.Tech in CSE, Physics, Applied Mathematics",
        "eligibility": "Students pursuing final semester master's or 7th/8th semester bachelor's degree.",
        "skills": "MPI, OpenMP, CUDA, Quantum Computing (Qiskit), High Performance Computing, C/C++",
        "description": "Develop and parallelize scientific computing algorithms on India's PARAM supercomputing cluster infrastructure.",
        "responsibilities": "Optimize matrix algebra routines for GPU nodes, evaluate quantum simulation circuits, document performance profiling.",
        "official_application_url": "https://www.cdac.in/index.aspx?id=career_opportunities",
        "official_website": "https://www.cdac.in/",
        "source_name": "C-DAC Official Career Portal",
        "source_record_id": "cdac-nsm-supercomputing-2026",
        "source_url": "https://www.cdac.in/",
        "academic_credit_available": True,
        "certificate_available": True,
        "number_of_openings": 12,
        "application_deadline": "2026-12-31"
    },

    # =========================================================================
    # 5. SPACE RESEARCH: ISRO / VSSC
    # =========================================================================
    {
        "title": "Aerospace Propulsion & Structures Trainee",
        "organisation_name": "ISRO - Vikram Sarabhai Space Centre (VSSC)",
        "organisation_type": "Research Institute",
        "industry": "Aerospace & Space Technology",
        "category": "Engineering",
        "scheme_name": "ISRO Academic Student Project Trainee Scheme",
        "department": "Department of Space, Government of India",
        "work_mode": "Onsite",
        "location": "Thiruvananthapuram, Kerala",
        "city": "Thiruvananthapuram",
        "state": "Kerala",
        "duration": "6 Months",
        "stipend": "Unpaid / Academic Fellowship",
        "eligible_degrees": "B.Tech / M.Tech in Aerospace, Mechanical, Metallurgy, Materials",
        "eligibility": "Top quartile students with university recommendation and bona fide certificate.",
        "skills": "ANSYS, Finite Element Analysis (FEA), CFD, Thermal Modelling, SolidWorks",
        "description": "Carry out degree capstone project work on launch vehicle structural mechanics and cryogenic stage thermal dissipation under senior ISRO scientists.",
        "responsibilities": "Perform structural stress simulations, validate composite payload fairing models against telemetry test data.",
        "official_application_url": "https://www.vssc.gov.in/",
        "official_website": "https://www.isro.gov.in/",
        "source_name": "VSSC / ISRO Portal",
        "source_record_id": "isro-vssc-propulsion-2026",
        "source_url": "https://www.vssc.gov.in/",
        "academic_credit_available": True,
        "certificate_available": True,
        "number_of_openings": 18,
        "application_deadline": "2026-11-25"
    },

    # =========================================================================
    # 6. CENTRAL POLICY & ECONOMIC THINK TANKS: NITI AAYOG & RBI
    # =========================================================================
    {
        "title": "Public Policy & Sustainable Growth Intern",
        "organisation_name": "NITI Aayog",
        "organisation_type": "Government",
        "industry": "Public Policy & Governance",
        "category": "Policy & Governance",
        "scheme_name": "NITI Aayog Internship Scheme",
        "department": "National Institution for Transforming India",
        "work_mode": "Onsite",
        "location": "New Delhi, Delhi",
        "city": "New Delhi",
        "state": "Delhi",
        "duration": "2 Months",
        "stipend": "Unpaid / Statutory Certificate",
        "eligible_degrees": "Any Bachelor's, Master's or Research Scholar (Economics, Law, Management, Engineering, Public Policy)",
        "eligibility": "Undergraduate students having completed 2nd year with >=85% in Class 12, or postgraduate/PhD students with >=70% aggregate.",
        "skills": "Policy Analysis, Quantitative Research, Stata/R, Report Writing, Stakeholder Consultation",
        "description": "Work with vertical divisions (Health, Agriculture, Energy, Infrastructure) on national policy papers and aspirational district evaluations.",
        "responsibilities": "Draft policy briefs, review state progress indicators, conduct empirical literature reviews on development economics.",
        "official_application_url": "https://www.niti.gov.in/internship",
        "official_website": "https://www.niti.gov.in/",
        "source_name": "NITI Aayog Portal",
        "source_record_id": "niti-policy-intern-2026",
        "source_url": "https://www.niti.gov.in/internship",
        "academic_credit_available": True,
        "certificate_available": True,
        "number_of_openings": 40,
        "application_deadline": "2026-12-10"
    },
    {
        "title": "Economic Research & Monetary Analysis Intern",
        "organisation_name": "Reserve Bank of India (RBI)",
        "organisation_type": "PSU",
        "industry": "Banking & Central Finance",
        "category": "Finance & Economics",
        "scheme_name": "RBI Summer Placement Scheme",
        "department": "Department of Economic and Policy Research (DEPR)",
        "work_mode": "Onsite",
        "location": "Mumbai, Maharashtra",
        "city": "Mumbai",
        "state": "Maharashtra",
        "duration": "3 Months",
        "stipend": "₹20,000 / Month",
        "eligible_degrees": "Postgraduate students in Economics, Finance, Statistics, Commerce, MBA (Finance)",
        "eligibility": "Penultimate year students of post-graduate courses from recognized universities across India.",
        "skills": "Econometrics, Time Series Forecasting, Python, R, Macroeconomic Modelling, Financial Econometrics",
        "description": "Conduct deep empirical analysis on inflation dynamics, banking system liquidity, and cross-border payment rails under RBI economists.",
        "responsibilities": "Compile financial stability datasets, run DSGE econometric regressions, and present findings to department directors.",
        "official_application_url": "https://opportunities.rbi.org.in/",
        "official_website": "https://www.rbi.org.in/",
        "source_name": "RBI Opportunities Portal",
        "source_record_id": "rbi-summer-placement-2026",
        "source_url": "https://opportunities.rbi.org.in/",
        "academic_credit_available": True,
        "certificate_available": True,
        "number_of_openings": 25,
        "application_deadline": "2026-12-15"
    },

    # =========================================================================
    # 7. LEGAL RESEARCH: SUPREME COURT & LAW COMMISSION
    # =========================================================================
    {
        "title": "Judicial Law Clerk & Constitutional Research Intern",
        "organisation_name": "Supreme Court of India",
        "organisation_type": "Government",
        "industry": "Judiciary & Law",
        "category": "Law & Legal Studies",
        "scheme_name": "Supreme Court Law Clerk-cum-Research Assistant Scheme",
        "department": "Registry of the Supreme Court",
        "work_mode": "Onsite",
        "location": "New Delhi, Delhi",
        "city": "New Delhi",
        "state": "Delhi",
        "duration": "6 Months",
        "stipend": "₹30,000 / Month",
        "eligible_degrees": "LL.B (5-Year Integrated or 3-Year), LL.M",
        "eligibility": "Final year law students or recent law graduates enrolled with Bar Council.",
        "skills": "SCC Online, Manupatra, Constitutional Law, Case Briefing, Legal Drafting, Statutory Interpretation",
        "description": "Assist Hon'ble Judges of the Supreme Court with comprehensive case summaries, comparative jurisdiction research, and judicial drafting support.",
        "responsibilities": "Prepare bench briefs, summarize oral arguments, and examine statutory precedents from Commonwealth jurisdictions.",
        "official_application_url": "https://main.sci.gov.in/recruitment",
        "official_website": "https://main.sci.gov.in/",
        "source_name": "Supreme Court of India Official Portal",
        "source_record_id": "sci-law-clerk-2026",
        "source_url": "https://main.sci.gov.in/recruitment",
        "academic_credit_available": True,
        "certificate_available": True,
        "number_of_openings": 15,
        "application_deadline": "2026-11-28"
    },

    # =========================================================================
    # 8. MEDICAL & LIFE SCIENCES: ICMR & CSIR
    # =========================================================================
    {
        "title": "Biomedical Data & Epidemiology Research Intern",
        "organisation_name": "Indian Council of Medical Research (ICMR)",
        "organisation_type": "Research Institute",
        "industry": "Healthcare & Biotechnology",
        "category": "Healthcare & Life Sciences",
        "scheme_name": "ICMR Short Term Studentship (STS)",
        "department": "Department of Health Research (MoHFW)",
        "work_mode": "Hybrid",
        "location": "New Delhi, Delhi",
        "city": "New Delhi",
        "state": "Delhi",
        "duration": "2 Months",
        "stipend": "₹25,000 / Fellowship",
        "eligible_degrees": "MBBS, BDS, B.Pharm, B.Tech (Biotech), M.Sc (Biostatistics)",
        "eligibility": "Undergraduate medical, dental, and health sciences students before appearing in final year examinations.",
        "skills": "Epidemiology, Biostatistics, SPSS, Clinical Protocol Design, Public Health Analytics",
        "description": "Formulate a focused public health research protocol, collect verified community health samples, and prepare national biomedical reports.",
        "responsibilities": "Execute clinical research methodology under approved institutional guide and upload scientific report for national evaluation.",
        "official_application_url": "https://esampark.icmr.org.in/",
        "official_website": "https://www.icmr.gov.in/",
        "source_name": "ICMR Official Portal",
        "source_record_id": "icmr-sts-biomedical-2026",
        "source_url": "https://esampark.icmr.org.in/",
        "academic_credit_available": True,
        "certificate_available": True,
        "number_of_openings": 50,
        "application_deadline": "2026-12-20"
    },
    {
        "title": "Computational Chemistry & Drug Discovery Trainee",
        "organisation_name": "CSIR - Central Drug Research Institute (CDRI)",
        "organisation_type": "Research Institute",
        "industry": "Pharmaceuticals & Chemistry",
        "category": "Research & Science",
        "scheme_name": "CSIR Summer Research Training Programme",
        "department": "Council of Scientific and Industrial Research",
        "work_mode": "Onsite",
        "location": "Lucknow, Uttar Pradesh",
        "city": "Lucknow",
        "state": "Uttar Pradesh",
        "duration": "3 Months",
        "stipend": "₹10,000 / Month",
        "eligible_degrees": "B.Pharm, M.Pharm, M.Sc (Chemistry, Biochemistry, Biotechnology)",
        "eligibility": "Enrolled students with solid academic credentials and faculty recommendation.",
        "skills": "Molecular Docking, PyMOL, Schrödinger, QSAR Modeling, Organic Synthesis",
        "description": "Engage in structure-based lead compound optimization and automated screening against communicable disease targets.",
        "responsibilities": "Run in-silico ligand binding simulations and assist analytical chemistry teams with HPLC / Mass Spectrometry assays.",
        "official_application_url": "https://cdri.res.in/",
        "official_website": "https://cdri.res.in/",
        "source_name": "CSIR-CDRI Portal",
        "source_record_id": "csir-cdri-drug-discovery-2026",
        "source_url": "https://cdri.res.in/",
        "academic_credit_available": True,
        "certificate_available": True,
        "number_of_openings": 12,
        "application_deadline": "2026-12-15"
    },

    # =========================================================================
    # 9. STATE GOVERNMENT INNOVATION & SKILLING MISSIONS
    # =========================================================================
    {
        "title": "State Digital Governance & Data Analytics Fellow",
        "organisation_name": "Government of Maharashtra - HTED",
        "organisation_type": "Government",
        "industry": "State Governance & E-Services",
        "category": "Technology",
        "scheme_name": "Maharashtra Higher & Technical Education Internship Scheme",
        "department": "Higher and Technical Education Department (HTED)",
        "work_mode": "Hybrid",
        "location": "Mumbai, Maharashtra",
        "city": "Mumbai",
        "state": "Maharashtra",
        "duration": "4 Months",
        "stipend": "₹12,000 / Month",
        "eligible_degrees": "B.Tech, BCA, B.Sc (IT), MCA, MBA (Public Systems)",
        "eligibility": "Students studying in colleges affiliated with state universities in Maharashtra.",
        "skills": "SQL, PowerBI, Python, Citizen Portal Telemetry, Agile Delivery",
        "description": "Analyze state scholarship portal uptime, grievance redressal response times, and college accreditation compliance indices.",
        "responsibilities": "Create executive dashboard visualizations for state education secretariat and automate anomaly detection pipelines.",
        "official_application_url": "https://internship.aicte-india.org/",
        "official_website": "https://maharashtra.gov.in/",
        "source_name": "AICTE Maharashtra State Hub",
        "source_record_id": "maha-hted-governance-2026",
        "source_url": "https://internship.aicte-india.org/",
        "academic_credit_available": True,
        "certificate_available": True,
        "number_of_openings": 35,
        "application_deadline": "2026-12-25"
    },
    {
        "title": "Semiconductor & Embedded VLSI Trainee",
        "organisation_name": "Karnataka Innovation and Technology Society (K-Tech)",
        "organisation_type": "Government",
        "industry": "Semiconductors & Electronics",
        "category": "Electronics & Hardware",
        "scheme_name": "K-Tech ESDM Student Skilling Program",
        "department": "Department of Electronics, IT, BT and S&T (Govt of Karnataka)",
        "work_mode": "Onsite",
        "location": "Bengaluru, Karnataka",
        "city": "Bengaluru",
        "state": "Karnataka",
        "duration": "6 Months",
        "stipend": "₹16,000 / Month",
        "eligible_degrees": "B.Tech (ECE, EEE, VLSI Design), M.Tech",
        "eligibility": "3rd or final year engineering students with strong semiconductor device fundamentals.",
        "skills": "Verilog, SystemVerilog, FPGA, RTL Design, Synopsys Tools, Cadence EDA",
        "description": "Undergo hands-on digital ASIC flow synthesis, timing verification, and FPGA prototyping in state-backed Centre of Excellence.",
        "responsibilities": "Design synthesizable IP blocks, write automated regression testbenches, and perform static timing analysis.",
        "official_application_url": "https://ktech.karnataka.gov.in/",
        "official_website": "https://ktech.karnataka.gov.in/",
        "source_name": "K-Tech Karnataka Portal",
        "source_record_id": "ktech-vlsi-trainee-2026",
        "source_url": "https://ktech.karnataka.gov.in/",
        "academic_credit_available": True,
        "certificate_available": True,
        "ppo_available": True,
        "number_of_openings": 20,
        "application_deadline": "2026-12-18"
    },

    # =========================================================================
    # 10. FLAGSHIP CORPORATE & PSU ENGINEERING HUBS
    # =========================================================================
    {
        "title": "Electric Vehicle Systems & Battery Tech Intern",
        "organisation_name": "Tata Motors Passenger Vehicles",
        "organisation_type": "Corporate",
        "industry": "Automotive & Clean Energy",
        "category": "Mechanical & Automobile",
        "scheme_name": "Tata Motors Tech Intern Challenge",
        "work_mode": "Onsite",
        "location": "Pune, Maharashtra",
        "city": "Pune",
        "state": "Maharashtra",
        "duration": "6 Months",
        "stipend": "₹25,000 / Month",
        "eligible_degrees": "B.Tech / M.Tech in Electrical, Mechanical, Mechatronics, Automobile",
        "eligibility": "Pre-final and final year engineering students with CGPA >= 7.5.",
        "skills": "Battery Management Systems (BMS), MATLAB / Simulink, CAN Bus, Thermal Management, Powertrain",
        "description": "Contribute to India's leading EV manufacturing team on cell thermal modeling, motor controller calibration, and regenerative braking algorithms.",
        "responsibilities": "Simulate battery pack heating cycles, test hardware-in-the-loop (HIL) benches, and validate telematics data logs.",
        "official_application_url": "https://www.tatamotors.com/careers/",
        "official_website": "https://www.tatamotors.com/",
        "source_name": "Tata Motors Careers",
        "source_record_id": "tata-motors-ev-intern-2026",
        "source_url": "https://www.tatamotors.com/careers/",
        "academic_credit_available": True,
        "certificate_available": True,
        "ppo_available": True,
        "number_of_openings": 15,
        "application_deadline": "2026-12-10"
    },
    {
        "title": "Heavy Infrastructure & BIM Modeler Intern",
        "organisation_name": "Larsen & Toubro (L&T)",
        "organisation_type": "Corporate",
        "industry": "Engineering & Construction",
        "category": "Civil & Architecture",
        "scheme_name": "L&T Build India Trainee Pipeline",
        "work_mode": "Onsite",
        "location": "Chennai, Tamil Nadu",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "duration": "6 Months",
        "stipend": "₹22,000 / Month",
        "eligible_degrees": "B.Tech in Civil, Structural Engineering, Architecture",
        "eligibility": "Final year civil engineering students across AICTE recognized universities with first-class academic record.",
        "skills": "Building Information Modeling (BIM), Revit, STAAD.Pro, Navisworks, Quantity Surveying",
        "description": "Join L&T Construction megaprojects working on metro rail viaducts, bridge spans, and industrial smart factories.",
        "responsibilities": "Resolve 3D geometric clashes, model parametric reinforced concrete structures, and track real-time 4D scheduling timelines.",
        "official_application_url": "https://www.larsentoubro.com/corporate/careers/",
        "official_website": "https://www.larsentoubro.com/",
        "source_name": "L&T Careers",
        "source_record_id": "lt-bim-civil-intern-2026",
        "source_url": "https://www.larsentoubro.com/corporate/careers/",
        "academic_credit_available": True,
        "certificate_available": True,
        "ppo_available": True,
        "number_of_openings": 30,
        "application_deadline": "2026-12-08"
    },
    {
        "title": "InStep Global Technology & Innovation Intern",
        "organisation_name": "Infosys Limited",
        "organisation_type": "Corporate",
        "industry": "Information Technology",
        "category": "Technology",
        "scheme_name": "Infosys InStep Flagship Program",
        "work_mode": "Hybrid",
        "location": "Bengaluru, Karnataka",
        "city": "Bengaluru",
        "state": "Karnataka",
        "duration": "3 Months",
        "stipend": "₹35,000 / Month",
        "eligible_degrees": "B.Tech, BCA, MCA, M.Tech, MBA",
        "eligibility": "High-performing students from top Indian and international universities.",
        "skills": "Full-Stack Development, Cloud (AWS/Azure), Generative AI, Java, Microservices",
        "description": "Ranked among the world's most prestigious internships, InStep offers student innovators the opportunity to work directly with senior architects on real enterprise solutions.",
        "responsibilities": "Architect cloud-native microservices, deploy generative AI enterprise agents, and present capstone prototypes to executive leadership.",
        "official_application_url": "https://www.infosys.com/instep.html",
        "official_website": "https://www.infosys.com/",
        "source_name": "Infosys InStep Official Portal",
        "source_record_id": "infosys-instep-2026",
        "source_url": "https://www.infosys.com/instep.html",
        "academic_credit_available": True,
        "certificate_available": True,
        "ppo_available": True,
        "number_of_openings": 40,
        "application_deadline": "2026-12-15"
    },
    {
        "title": "5G Core & Cloud Network Operations Intern",
        "organisation_name": "Reliance Jio Infocomm",
        "organisation_type": "Corporate",
        "industry": "Telecommunications & Cloud",
        "category": "Technology",
        "scheme_name": "Jio Young Talent Tech Track",
        "work_mode": "Hybrid",
        "location": "Navi Mumbai, Maharashtra",
        "city": "Navi Mumbai",
        "state": "Maharashtra",
        "duration": "6 Months",
        "stipend": "₹28,000 / Month",
        "eligible_degrees": "B.Tech in ECE, CSE, IT, Telecommunication",
        "eligibility": "Final or pre-final year engineering students with networking and cloud computing background.",
        "skills": "5G SA Core, Kubernetes, Linux Shell, Wireshark, OpenFlow, Python Network Automation",
        "description": "Collaborate on India's indigenous 5G Standalone network infrastructure, analyzing software-defined network (SDN) routing and microservice latency.",
        "responsibilities": "Automate packet capture analyses, monitor Kubernetes cluster pod metrics, and build Ansible configuration playbooks.",
        "official_application_url": "https://careers.jio.com/",
        "official_website": "https://www.jio.com/",
        "source_name": "Jio Careers Portal",
        "source_record_id": "jio-5g-cloud-intern-2026",
        "source_url": "https://careers.jio.com/",
        "academic_credit_available": True,
        "certificate_available": True,
        "ppo_available": True,
        "number_of_openings": 25,
        "application_deadline": "2026-12-22"
    },
    {
        "title": "Product Design & SaaS Frontend Trainee",
        "organisation_name": "Zoho Corporation",
        "organisation_type": "Corporate",
        "industry": "Enterprise Software",
        "category": "Design & UI/UX",
        "scheme_name": "Zoho Creator & Design Fellowship",
        "work_mode": "Onsite",
        "location": "Chennai, Tamil Nadu",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "duration": "6 Months",
        "stipend": "₹22,000 / Month",
        "eligible_degrees": "Any Degree / Diploma / B.Des / B.Tech / BCA",
        "eligibility": "Passionate designers and web engineers. Portfolio and problem-solving ability prioritized over degrees.",
        "skills": "Figma, CSS Grid/Flexbox, JavaScript, Design Systems, Usability Testing, Accessibility",
        "description": "Build world-class product interfaces for millions of global business users with Zoho's in-house design philosophy.",
        "responsibilities": "Design component libraries, prototype user flows in Figma, and build responsive web interfaces adhering to WCAG standards.",
        "official_application_url": "https://www.zoho.com/careers/",
        "official_website": "https://www.zoho.com/",
        "source_name": "Zoho Careers",
        "source_record_id": "zoho-saas-design-2026",
        "source_url": "https://www.zoho.com/careers/",
        "academic_credit_available": True,
        "certificate_available": True,
        "ppo_available": True,
        "number_of_openings": 20,
        "application_deadline": "2026-12-30"
    },
    {
        "title": "Avionics & Embedded Radar Trainee",
        "organisation_name": "Bharat Electronics Limited (BEL)",
        "organisation_type": "PSU",
        "industry": "Defence Electronics",
        "category": "Electronics & Hardware",
        "scheme_name": "BEL Graduate Apprenticeship & Project Trainee Scheme",
        "work_mode": "Onsite",
        "location": "Bengaluru, Karnataka",
        "city": "Bengaluru",
        "state": "Karnataka",
        "duration": "6 Months",
        "stipend": "₹17,500 / Month",
        "eligible_degrees": "B.Tech in Electronics, ECE, Telecommunication, Instrumentation",
        "eligibility": "Pre-final or final year engineering students with first class marks from AICTE recognized colleges.",
        "skills": "DSP, Embedded C, Radar Signal Processing, Oscilloscopes, MATLAB",
        "description": "Work inside a Navratna PSU facility on radar signal receiver modules, electronic warfare testing, and military communications firmware.",
        "responsibilities": "Test RF printed circuit boards, calibrate signal transmitters, and participate in formal hardware acceptance test procedures.",
        "official_application_url": "https://bel-india.in/CareersGridHigh.aspx?MId=29",
        "official_website": "https://bel-india.in/",
        "source_name": "BEL Careers Official Portal",
        "source_record_id": "bel-radar-trainee-2026",
        "source_url": "https://bel-india.in/",
        "academic_credit_available": True,
        "certificate_available": True,
        "number_of_openings": 20,
        "application_deadline": "2026-12-15"
    }
]
