"""
scripts/careers_data_part2.py
Engineering, Manufacturing, Law, Government, and Management Sectors.
"""

ENGINEERING_CAREERS = [
    {
        "title": "Civil Engineer",
        "short_name": "Civil Engineer",
        "slug": "civil-engineer",
        "category": "Engineering & Manufacturing",
        "sub_category": "Structural & Infrastructure Engineering",
        "industry": "Construction & Infrastructure",
        "icon": "building",
        "short_description": "Plans, designs, constructs, and oversees infrastructure projects such as roads, bridges, dams, airports, and urban buildings.",
        "description": "Civil Engineers are the architects of modern physical society. They conceive, design, construct, and maintain foundational infrastructure systems while ensuring structural safety, environmental sustainability, and regulatory compliance.",
        "what_they_do": "They analyze structural blueprints, conduct soil and geotechnical surveys, calculate load stresses, oversee construction site safety and concrete curing, and ensure project delivery within timelines and budgets.",
        "day_to_day_work": "• Designing structural layouts using AutoCAD, STAAD.Pro, or Revit.\n• Inspecting project construction sites and verifying material quality (concrete slump, rebar).\n• Calculating structural loads, material quantities, and cost estimates.\n• Managing contractor schedules and worker safety compliance.\n• Resolving foundation and geotechnical engineering challenges.",
        "work_environment": "Construction sites, structural design engineering offices, infrastructure consultancies.",
        "work_modes": "On-site / Field Visits / Design Office",
        "minimum_qualification": "Undergraduate (B.Tech / B.E.)",
        "preferred_streams": "Science (PCM)",
        "required_subjects": "Mathematics, Physics, Chemistry",
        "technical_skills": "Structural Analysis, Geotechnical Engineering, Concrete Technology, AutoCAD, STAAD.Pro, Surveying, Project Management",
        "soft_skills": "Leadership, Site Safety Awareness, Problem Solving, Communication",
        "tools": "AutoCAD, STAAD.Pro, Revit Architecture, Primavera P6, Total Station",
        "certifications": "Chartered Engineer (India) - Institution of Engineers (IEI), Project Management Professional (PMP)",
        "experience_level": "Entry-Level to Senior",
        "career_growth": "Broad, steady trajectory progressing to Chief Structural Engineer, Project Director, or Infrastructure CEO.",
        "internship_roles": "Civil Site Engineering Intern, Structural Design Intern, Surveying Trainee",
        "entry_level_roles": "Graduate Engineer Trainee (GET), Junior Civil Engineer, Site Supervisor",
        "average_salary": "₹4 - ₹12 LPA (Indicative range)",
        "salary_indicative": "Entry-Level GET (0-2 yrs): ₹3.5 - 6 LPA | Project Engineer (3-6 yrs): ₹7 - 14 LPA | Project Director / Chief Engineer (7+ yrs): ₹18 - 40+ LPA. Indicative figures from National Career Service & Construction Sector Skill Council 2024.",
        "future_scope": "Surging national growth driven by massive government infrastructure initiatives (National Infrastructure Pipeline, PM Gati Shakti, Smart Cities).",
        "government_opportunities": "Central Public Works Department (CPWD - UPSC ESE), Railways (IRSE), NHAI, BRO, Military Engineer Services (MES), State PWDs, DMRC.",
        "private_opportunities": "Larsen & Toubro (L&T), Tata Projects, Shapoorji Pallonji, Afcons Infrastructure, DLF, Godrej Properties.",
        "higher_study_options": "M.Tech in Structural Engineering / Geotechnical Engineering, NICMAR (PGP in Advanced Construction Management).",
        "entrepreneurship_options": "Civil contracting firm, structural design consultancy, government contractor registration.",
        "source": "National Career Service (NCS) / Construction Skill Development Council of India (CSDCI)",
        "official_url": "https://www.ncs.gov.in",
        "verification_status": "VERIFIED",
        "courses": [{"course_id": 12, "type": "DIRECT"}, {"course_id": 44, "type": "ALTERNATIVE"}],
        "exams": [{"exam_id": 8, "importance": "PRIMARY"}, {"exam_id": 51, "importance": "PRIMARY"}, {"exam_id": 60, "importance": "PRIMARY"}, {"exam_id": 69, "importance": "PRIMARY"}],
        "routes": [
            {"title": "Path A: Standard Engineering Degree Route", "type": "COMMON", "steps": "Class 12 (PCM) -> JEE Main / State CET -> B.Tech Civil Engineering (4 yrs) -> Site Projects & Software (AutoCAD/STAAD) -> Campus GET or UPSC ESE / SSC JE."},
            {"title": "Path B: Polytechnic Diploma Route", "type": "ALTERNATIVE", "steps": "Class 10 -> Diploma in Civil Engineering (3 yrs) -> Junior Engineer (JE) exam or lateral B.Tech entry -> Civil Engineer."}
        ],
        "ladder": [
            {"stage": "Graduate Engineer Trainee (Site / Design)", "exp": "0-2 Years", "desc": "Assists in bar bending schedules, material testing, daily labor reports on site."},
            {"stage": "Site / Structural Engineer", "exp": "2-5 Years", "desc": "Supervises major structural pours, manages sub-contractors, checks design drawings."},
            {"stage": "Project Manager / Senior Structural Engineer", "exp": "5-9 Years", "desc": "Manages complete construction packages, controls multi-crore site budgets and timelines."},
            {"stage": "Project Director / Chief Engineer", "exp": "9+ Years", "desc": "Directs nationwide infrastructure megaprojects (metro lines, expressways, airports)."}
        ],
        "roadmaps": {
            "Class 10": "Focus on Geometry, Trigonometry, and Physics mechanics.",
            "Class 12": "Score high in PCM. Target top engineering institutes through JEE Main / Advanced.",
            "Graduation": "Master AutoCAD, STAAD.Pro, and structural analysis. Complete mandatory summer internships on active construction sites.",
            "Working Professional": "Prepare for UPSC Engineering Services Exam (ESE) or GATE for PSU jobs (NHPC, NTPC, IOCL), or earn PMP certification."
        }
    },
    {
        "title": "Mechanical Engineer",
        "short_name": "Mechanical Engineer",
        "slug": "mechanical-engineer",
        "category": "Engineering & Manufacturing",
        "sub_category": "Thermal, Mechanics & Manufacturing",
        "industry": "Manufacturing & Heavy Engineering",
        "icon": "gear-wide-connected",
        "short_description": "Designs, manufactures, and maintains mechanical systems, thermal equipment, industrial machinery, and automotive vehicles.",
        "description": "Mechanical Engineers apply principles of thermodynamics, materials science, mechanics, and fluid dynamics to create everything from miniature micro-sensors to massive industrial power plants, automobiles, and aerospace vehicles.",
        "what_they_do": "They create 3D computer-aided designs (CAD), conduct finite element analysis (FEA) to test structural stress, oversee automated factory production lines, and optimize thermal power systems.",
        "day_to_day_work": "• Designing machinery components in SolidWorks or CATIA.\n• Running thermal and finite element stress simulations (ANSYS).\n• Inspecting automated assembly line machinery and robotics.\n• Evaluating thermodynamic efficiency of engines, pumps, and turbines.\n• Coordinating with production and metallurgy teams on shop-floor quality.",
        "work_environment": "Manufacturing plants, automotive design studios, industrial research labs.",
        "work_modes": "On-site / Plant Floor / CAD Design Office",
        "minimum_qualification": "Undergraduate (B.Tech / B.E.)",
        "preferred_streams": "Science (PCM)",
        "required_subjects": "Mathematics, Physics, Chemistry",
        "technical_skills": "Thermodynamics, Fluid Mechanics, CAD/CAM (SolidWorks, CATIA), FEA (ANSYS), Manufacturing Processes, Material Science",
        "soft_skills": "Analytical Thinking, Shop Floor Safety, Problem Solving, Team Coordination",
        "tools": "SolidWorks, CATIA, ANSYS, AutoCAD, MATLAB, CNC Programming",
        "certifications": "Certified SolidWorks Professional (CSWP), Six Sigma Green Belt",
        "experience_level": "Entry-Level to Senior",
        "career_growth": "Exceptional long-term growth progressing to Chief Mechanical Engineer, Plant Head, or VP of Manufacturing Operations.",
        "internship_roles": "Mechanical Engineering Intern, CAD Design Trainee, Production Intern",
        "entry_level_roles": "Graduate Engineer Trainee (GET), Junior Design Engineer, Maintenance Engineer",
        "average_salary": "₹4.5 - ₹13 LPA (Indicative range)",
        "salary_indicative": "Entry-Level GET (0-2 yrs): ₹4 - 6.5 LPA | Design / Production Engineer (3-6 yrs): ₹7.5 - 15 LPA | Plant Head / Chief Engineer (7+ yrs): ₹18 - 42+ LPA. Indicative figures from National Career Service & Automotive Skills Development Council 2024.",
        "future_scope": "Sustained high demand, expanding into electric vehicles (EVs), robotics, automated manufacturing, and renewable thermal energy.",
        "government_opportunities": "BHEL, ONGC, NTPC, Indian Railways (Mechanical Wing), DRDO Scientist B, ISRO, Indian Navy (Technical Branch).",
        "private_opportunities": "Tata Motors, Mahindra & Mahindra, Larsen & Toubro, Maruti Suzuki, Thermax, Bosch, Cummins.",
        "higher_study_options": "M.Tech in Thermal / Machine Design / Robotics, MBA in Operations Management.",
        "entrepreneurship_options": "Precision CNC manufacturing workshop, industrial automation consultancy, custom component fabrication.",
        "source": "National Career Service (NCS) / Automotive Skills Development Council (ASDC)",
        "official_url": "https://www.ncs.gov.in",
        "verification_status": "VERIFIED",
        "courses": [{"course_id": 11, "type": "DIRECT"}, {"course_id": 44, "type": "ALTERNATIVE"}],
        "exams": [{"exam_id": 8, "importance": "PRIMARY"}, {"exam_id": 51, "importance": "PRIMARY"}, {"exam_id": 69, "importance": "PRIMARY"}, {"exam_id": 60, "importance": "PRIMARY"}],
        "routes": [
            {"title": "Path A: Standard Engineering Degree Route", "type": "COMMON", "steps": "Class 12 (PCM) -> JEE Main / State CET -> B.Tech Mechanical Engineering (4 yrs) -> Learn CAD (SolidWorks) & FEA (ANSYS) -> Campus GET or GATE PSU / UPSC ESE."}
        ],
        "ladder": [
            {"stage": "Graduate Engineer Trainee (GET)", "exp": "0-2 Years", "desc": "Handles equipment maintenance schedules, updates CAD drawings, monitors assembly line."},
            {"stage": "Design / Production Engineer", "exp": "2-5 Years", "desc": "Designs mechanical subsystems, conducts FEA stress simulations, improves line efficiency."},
            {"stage": "Manager - R&D / Operations", "exp": "5-8 Years", "desc": "Leads product engineering programs (e.g. EV powertrain), manages plant maintenance."},
            {"stage": "Plant Head / VP of Engineering", "exp": "8+ Years", "desc": "Directs total factory manufacturing operations, Capex investments, and plant safety."}
        ],
        "roadmaps": {
            "Class 10": "Focus on Physics mechanics (Newton's laws, work, energy, machines).",
            "Class 12": "Master Physics and Mathematics. Prepare for JEE Main / Advanced.",
            "Graduation": "Learn SolidWorks, CATIA, and ANSYS. Participate in BAJA SAE or Formula Student collegiate vehicle competitions.",
            "Working Professional": "Prepare for GATE to enter top PSUs (NTPC, BHEL, IOCL) or specialize in Electric Vehicle battery thermal management."
        }
    },
    {
        "title": "Electrical Engineer",
        "short_name": "Electrical Engineer",
        "slug": "electrical-engineer",
        "category": "Engineering & Manufacturing",
        "sub_category": "Power Systems & Electrical Infrastructure",
        "industry": "Power, Energy & Electricals",
        "icon": "lightning-charge",
        "short_description": "Designs, tests, and oversees the manufacturing and operation of electrical equipment, power grids, and renewable energy systems.",
        "description": "Electrical Engineers power modern society. They work on electricity generation, high-voltage transmission, smart electrical grids, renewable solar/wind integration, electric vehicle drivetrains, and industrial motor control circuits.",
        "what_they_do": "They design electrical power distribution schematics, specify switchgear and transformers, develop renewable power microgrids, ensure electrical substation safety, and program Programmable Logic Controllers (PLCs).",
        "day_to_day_work": "• Designing electrical single-line diagrams (SLD) in AutoCAD Electrical.\n• Performing load flow and short-circuit analysis using ETAP or MATLAB.\n• Testing high-voltage transformers, switchgear, and circuit breakers.\n• Commissioning solar photovoltaic (PV) inverters and battery storage systems.\n• Inspecting substation relay protections and automated power monitoring systems.",
        "work_environment": "Power substations, renewable energy solar/wind plants, manufacturing facilities, engineering design offices.",
        "work_modes": "On-site / Plant / Design Office",
        "minimum_qualification": "Undergraduate (B.Tech / B.E.)",
        "preferred_streams": "Science (PCM)",
        "required_subjects": "Mathematics, Physics, Chemistry",
        "technical_skills": "Power Systems Analysis, Electrical Machines, High Voltage Engineering, ETAP, MATLAB/Simulink, PLC/SCADA, Renewable Energy Integration",
        "soft_skills": "Safety Conscious, Systematic Problem Solving, Team Coordination, Precision",
        "tools": "ETAP, AutoCAD Electrical, MATLAB/Simulink, PSCAD, PLC Programming Tools",
        "certifications": "Certified Energy Manager (Bureau of Energy Efficiency - BEE), Chartered Engineer (IEI)",
        "experience_level": "Entry-Level to Senior",
        "career_growth": "Broad, vital career progressing to Substation Incharge, Chief Electrical Inspector, or VP of Power Infrastructure.",
        "internship_roles": "Electrical Engineering Intern, Substation Trainee, Renewable Energy Intern",
        "entry_level_roles": "Graduate Engineer Trainee (GET), Junior Electrical Engineer, Electrical Site Engineer",
        "average_salary": "₹4.5 - ₹13 LPA (Indicative range)",
        "salary_indicative": "Entry-Level GET (0-2 yrs): ₹4 - 6.5 LPA | Electrical Project Engineer (3-6 yrs): ₹7.5 - 15 LPA | Chief Electrical Engineer (7+ yrs): ₹18 - 40+ LPA. Indicative figures from National Career Service & Power Sector Skill Council 2024.",
        "future_scope": "Surging national demand driven by renewable energy targets (500 GW green energy by 2030), EV infrastructure, and smart grids.",
        "government_opportunities": "Power Grid Corporation of India (POWERGRID), NTPC, NHPC, State Electricity Boards (Discoms/Transcos), Indian Railways (Electrical Wing - IRSEE).",
        "private_opportunities": "Siemens India, ABB, Schneider Electric, Larsen & Toubro Power, Tata Power, Adani Power, Havells.",
        "higher_study_options": "M.Tech in Power Systems / Power Electronics, MBA in Energy Management.",
        "entrepreneurship_options": "Solar EPC contracting firm, industrial electrical panel manufacturing, energy auditing agency.",
        "source": "National Career Service (NCS) / Power Sector Skill Council (PSSC)",
        "official_url": "https://www.ncs.gov.in",
        "verification_status": "VERIFIED",
        "courses": [{"course_id": 13, "type": "DIRECT"}, {"course_id": 44, "type": "ALTERNATIVE"}],
        "exams": [{"exam_id": 8, "importance": "PRIMARY"}, {"exam_id": 51, "importance": "PRIMARY"}, {"exam_id": 69, "importance": "PRIMARY"}, {"exam_id": 60, "importance": "PRIMARY"}],
        "routes": [
            {"title": "Path A: Standard Electrical Engineering Degree", "type": "COMMON", "steps": "Class 12 (PCM) -> JEE Main / State CET -> B.Tech Electrical Engineering (4 yrs) -> Learn ETAP & MATLAB -> Campus GET or GATE PSU / UPSC ESE."}
        ],
        "ladder": [
            {"stage": "Electrical GET / Site Engineer", "exp": "0-2 Years", "desc": "Assists with substation testing, cable scheduling, breaker maintenance."},
            {"stage": "Electrical Project Engineer", "exp": "2-5 Years", "desc": "Designs power distribution single line diagrams, runs ETAP load flow simulations."},
            {"stage": "Senior Electrical Manager / DGM", "exp": "5-8 Years", "desc": "Oversees grid synchronization, transmission line execution, power purchase agreements."},
            {"stage": "Chief Electrical Engineer / VP of Power", "exp": "8+ Years", "desc": "Directs utility-scale power assets and corporate renewable energy roadmap."}
        ],
        "roadmaps": {
            "Class 10": "Focus on electricity, magnetism, electric circuits, and Ohm's Law in Physics.",
            "Class 12": "Master Electromagnetism, Alternating Current, and Calculus in Class 12.",
            "Graduation": "Learn ETAP, MATLAB/Simulink, and PLC programming. Complete internships in 220kV/400kV substations or solar plants.",
            "Working Professional": "Prepare for GATE (for POWERGRID, NTPC, BHEL) or clear the BEE Certified Energy Auditor exam."
        }
    },
    {
        "title": "Electronics & Communication Engineer",
        "short_name": "ECE Engineer",
        "slug": "electronics-communication-engineer",
        "category": "Engineering & Manufacturing",
        "sub_category": "Semiconductors, Embedded Systems & Telecom",
        "industry": "Semiconductors & Electronics",
        "icon": "cpu-fill",
        "short_description": "Designs, fabricates, and tests electronic semiconductor circuits, embedded systems, microprocessors, and communication networks.",
        "description": "Electronics and Communication Engineers drive the hardware revolution. They create integrated circuits (ICs), microcontrollers, 5G wireless telecommunication systems, satellite transponders, and Internet of Things (IoT) connected devices.",
        "what_they_do": "They write hardware description code in Verilog/VHDL, layout printed circuit boards (PCBs), program embedded firmware in C/C++, test wireless RF communication protocols, and design VLSI microchips.",
        "day_to_day_work": "• Designing digital and analog circuits in Cadence or KiCad.\n• Writing and simulating RTL designs in Verilog/SystemVerilog.\n• Programming embedded microcontrollers (ARM Cortex, ESP32, STM32) in C.\n• Testing RF signals, antennas, and noise reduction with oscilloscopes and spectrum analyzers.\n• Assisting in semiconductor tape-out and post-silicon validation.",
        "work_environment": "Semiconductor design labs, cleanroom fabrication facilities, electronics hardware labs.",
        "work_modes": "On-site / Hardware Lab / Hybrid",
        "minimum_qualification": "Undergraduate (B.Tech / B.E.)",
        "preferred_streams": "Science (PCM)",
        "required_subjects": "Mathematics, Physics, Chemistry",
        "technical_skills": "VLSI Design, Embedded C, Verilog/VHDL, Microcontrollers, PCB Design, Signal Processing, Digital Communication, FPGA",
        "soft_skills": "Precision, Analytical Problem Solving, Tenacity, Collaborative Engineering",
        "tools": "Cadence EDA, Synopsys, KiCad, Keil uVision, MATLAB, Oscilloscope, Logic Analyzer",
        "certifications": "Certified VLSI Design Engineer, Certified Embedded Systems Engineer",
        "experience_level": "Entry-Level to Senior",
        "career_growth": "Outstanding growth fueled by India's National Semiconductor Mission, progressing to Lead Silicon Architect or Hardware Director.",
        "internship_roles": "VLSI Intern, Embedded Systems Intern, Firmware Trainee",
        "entry_level_roles": "Associate Silicon Design Engineer, Embedded Firmware Engineer, Hardware Test Engineer",
        "average_salary": "₹5 - ₹16 LPA (Indicative range)",
        "salary_indicative": "Entry-Level GET (0-2 yrs): ₹4.5 - 7.5 LPA | VLSI / Embedded Engineer (3-6 yrs): ₹9 - 20 LPA | Lead Silicon Architect (7+ yrs): ₹24 - 55+ LPA. Indicative figures from India Electronics and Semiconductor Association (IESA) 2024.",
        "future_scope": "Explosive national growth driven by India's semiconductor fabrication plants (Semicon India), 5G/6G, and IoT hardware.",
        "government_opportunities": "ISRO Satellite Centre, DRDO (LRDE, DEAL), Bharat Electronics Limited (BEL), CDAC, Semi-Conductor Laboratory (SCL).",
        "private_opportunities": "Qualcomm, Intel, NVIDIA, Texas Instruments, AMD, MediaTek, Samsung Semiconductor, Bosch.",
        "higher_study_options": "M.Tech in VLSI Design / Embedded Systems, M.S. in Electrical & Computer Engineering.",
        "entrepreneurship_options": "Fabless semiconductor startup, IoT hardware product manufacturing, PCB design service bureau.",
        "source": "India Electronics and Semiconductor Association (IESA) / AICTE",
        "official_url": "https://www.iesaonline.org",
        "verification_status": "VERIFIED",
        "courses": [{"course_id": 10, "type": "DIRECT"}, {"course_id": 44, "type": "ALTERNATIVE"}],
        "exams": [{"exam_id": 8, "importance": "PRIMARY"}, {"exam_id": 51, "importance": "PRIMARY"}, {"exam_id": 69, "importance": "PRIMARY"}],
        "routes": [
            {"title": "Path A: Standard B.Tech ECE to VLSI / Embedded", "type": "COMMON", "steps": "Class 12 (PCM) -> JEE Main / State CET -> B.Tech ECE (4 yrs) -> Specialize in VLSI (Verilog/Cadence) or Embedded C -> Silicon / Hardware Engineer."}
        ],
        "ladder": [
            {"stage": "Junior Silicon / Embedded Engineer", "exp": "0-2 Years", "desc": "Writes testbenches, runs RTL synthesis, debugs firmware on microcontrollers."},
            {"stage": "VLSI / Hardware Engineer", "exp": "2-5 Years", "desc": "Owns IP block design, executes physical design (place and route), optimizes timing closure."},
            {"stage": "Senior Hardware Architect", "exp": "5-8 Years", "desc": "Designs system-on-chip (SoC) architectures, oversees silicon tape-out to fabs."},
            {"stage": "Director of Hardware Engineering", "exp": "8+ Years", "desc": "Directs global semiconductor product lines, foundry engagements, and chip packaging."}
        ],
        "roadmaps": {
            "Class 10": "Learn how semiconductor chips, transistors, and diodes work in basic science.",
            "Class 12": "Master Physics (Modern Physics, Semiconductor Devices) and Mathematics.",
            "Graduation": "Build embedded projects using Arduino/STM32, learn Verilog and digital design principles, design custom PCBs in KiCad.",
            "Working Professional": "Prepare for GATE to pursue M.Tech in VLSI from IITs or specialize in advanced FinFET / GAA node physical design."
        }
    },
    {
        "title": "Aerospace & Aeronautical Engineer",
        "short_name": "Aerospace Engineer",
        "slug": "aerospace-engineer",
        "category": "Engineering & Manufacturing",
        "sub_category": "Aeronautics, Space & Defence",
        "industry": "Aerospace & Defence",
        "icon": "send",
        "short_description": "Designs, tests, and manufactures aircraft, spacecraft, satellites, launch vehicles, and defence missiles.",
        "description": "Aerospace Engineers design flight vehicles operating within Earth's atmosphere (Aeronautical) and outside in outer space (Astronautical). They master aerodynamics, propulsion systems, structural dynamics, avionics, and orbital flight mechanics.",
        "what_they_do": "They model aerodynamic airflow over wings and fuselages, design rocket propulsion engines, conduct wind tunnel tests, select lightweight carbon-composite materials, and program flight control navigation systems.",
        "day_to_day_work": "• Running Computational Fluid Dynamics (CFD) aerodynamic simulations in ANSYS Fluent.\n• Designing structural airframe components in CATIA.\n• Calculating thrust, combustion efficiency, and thermal protection for propulsion systems.\n• Testing avionics sensor telemetry and guidance algorithms in MATLAB.\n• Reviewing flight safety compliance against DGCA and international aviation standards.",
        "work_environment": "Aerospace research laboratories, space launch centers, aircraft manufacturing hangars, defence facilities.",
        "work_modes": "On-site / Lab / Hangar",
        "minimum_qualification": "Undergraduate (B.Tech / B.E.)",
        "preferred_streams": "Science (PCM)",
        "required_subjects": "Physics, Mathematics, Chemistry",
        "technical_skills": "Aerodynamics, Propulsion Systems, Computational Fluid Dynamics (CFD), Flight Mechanics, CATIA, ANSYS, Avionics, Orbital Mechanics",
        "soft_skills": "Extreme Precision, High-Stakes Problem Solving, Teamwork, Tenacity",
        "tools": "ANSYS Fluent, CATIA V5, MATLAB/Simulink, OpenFOAM, NASA CEA",
        "certifications": "Aeronautical Society of India (AeSI) Professional Membership",
        "experience_level": "Entry-Level to Senior",
        "career_growth": "Prestigious career progression into Project Director for Launch Vehicles, Chief Aerodynamicist, or Space Mission Director.",
        "internship_roles": "Aerospace Research Intern, Aerodynamics Trainee, Space Systems Intern",
        "entry_level_roles": "Scientist/Engineer 'SC' (ISRO), Graduate Engineer Trainee, Aerodynamics Engineer",
        "average_salary": "₹6 - ₹18 LPA (Indicative range)",
        "salary_indicative": "Entry-Level / Scientist SC (0-2 yrs): ₹6 - 9.5 LPA | Senior Propulsion / Flight Engineer (3-6 yrs): ₹10 - 22 LPA | Mission Director / Chief Scientist (7+ yrs): ₹25 - 55+ LPA. Indicative figures from ISRO & Aerospace Industry 2024.",
        "future_scope": "Thriving national expansion propelled by ISRO space missions (Gaganyaan, Chandrayaan), defence aerospace (Tejas, AMCA), and private space-tech startups (Skyroot, Agnikul).",
        "government_opportunities": "ISRO (Indian Space Research Organisation), DRDO (ADE, DRDL, RCI), Hindustan Aeronautics Limited (HAL), National Aerospace Laboratories (NAL).",
        "private_opportunities": "Skyroot Aerospace, Agnikul Cosmos, Boeing India, Airbus India, Tata Advanced Systems, Collins Aerospace.",
        "higher_study_options": "M.Tech / M.S. in Aerospace Engineering (IIST, IIT Bombay, IIT Madras), Ph.D. in Hypersonics / Rocket Propulsion.",
        "entrepreneurship_options": "Commercial space-tech startup (satellite launch, drone manufacturing, earth observation).",
        "source": "Indian Space Research Organisation (ISRO) / AeSI",
        "official_url": "https://www.isro.gov.in",
        "verification_status": "VERIFIED",
        "courses": [{"course_id": 11, "type": "COMMON"}, {"course_id": 9, "type": "ALTERNATIVE"}],
        "exams": [{"exam_id": 8, "importance": "PRIMARY"}, {"exam_id": 9, "importance": "PRIMARY"}, {"exam_id": 69, "importance": "PRIMARY"}, {"exam_id": 29, "importance": "ALTERNATIVE"}],
        "routes": [
            {"title": "Path A: IIST / IIT Aerospace Route", "type": "COMMON", "steps": "Class 12 (PCM) -> JEE Advanced -> Indian Institute of Space Science and Technology (IIST) or IITs -> B.Tech Aerospace Engineering -> Direct absorption into ISRO as Scientist/Engineer 'SC'."},
            {"title": "Path B: Mechanical / Electronics to Aerospace", "type": "COMMON", "steps": "B.Tech Mechanical / ECE -> GATE in Aerospace / Mechanical -> M.Tech in Propulsion or Aerodynamics -> ISRO / HAL / Aerospace Startups."}
        ],
        "ladder": [
            {"stage": "Scientist/Engineer 'SC' / Junior Engineer", "exp": "0-2 Years", "desc": "Analyzes telemetry, runs CFD meshes, assists in rocket stage static testing."},
            {"stage": "Scientist/Engineer 'SD' / Flight Engineer", "exp": "2-5 Years", "desc": "Designs rocket propulsion injectors, airframe structures, autopilot control algorithms."},
            {"stage": "Scientist/Engineer 'SE/SF' / Team Lead", "exp": "5-9 Years", "desc": "Leads major subsystem packages (cryogenic engine, heat shield separation)."},
            {"stage": "Mission Director / Outstanding Scientist", "exp": "9+ Years", "desc": "Leads national satellite launch missions, deep-space exploration, or aerospace policy."}
        ],
        "roadmaps": {
            "Class 10": "Build deep curiosity about astronomy, aircraft, rockets, and space missions.",
            "Class 12": "Top scores in Physics and Mathematics. Prepare aggressively for JEE Advanced for IIST or IITs.",
            "Graduation": "Learn CATIA, ANSYS Fluent, and MATLAB. Build rockets/drones in university aero-design teams.",
            "Working Professional": "Clear ISRO Centralised Recruitment Board (ICRB) or GATE for advanced master's at IIST / IITs, or join premier spacetech startups."
        }
    }
]

print(f"Loaded {len(ENGINEERING_CAREERS)} Engineering Careers")
