"""
scripts/careers_data_extended.py
Extended National Career Dataset: Finance, Engineering, Law, and Government Sectors.
"""

FINANCE_CAREERS = [
    {
        "title": "Chartered Accountant (CA)",
        "short_name": "Chartered Accountant",
        "slug": "chartered-accountant",
        "category": "Finance, Banking & Accounting",
        "sub_category": "Accounting & Auditing",
        "industry": "Financial Services / Accounting",
        "icon": "cash-coin",
        "short_description": "Manages financial audits, tax planning, corporate governance, and statutory financial reporting under the ICAI.",
        "description": "Chartered Accountants are statutory financial authorities in India recognized under the Chartered Accountants Act, 1949. They audit corporate accounts, evaluate taxation strategies, advise on mergers and acquisitions, and ensure financial compliance with statutory laws.",
        "what_they_do": "They examine corporate balance sheets, conduct statutory audits, prepare direct and indirect tax returns (Income Tax, GST), provide forensic financial auditing, and advise boards on corporate capital restructuring.",
        "day_to_day_work": "• Reviewing general ledgers and corporate financial statements.\n• Conducting statutory and internal audits across corporate departments.\n• Calculating corporate tax liabilities and filing returns on Income Tax / GST portals.\n• Assessing financial risk, cost management, and capital allocation.\n• Advising corporate management on regulatory compliance with Companies Act.",
        "work_environment": "Audit firms (Big 4), corporate headquarters, financial consultancies, or private CA offices.",
        "work_modes": "On-site / Corporate Client Visits / Hybrid",
        "minimum_qualification": "ICAI Professional Qualification",
        "preferred_streams": "Commerce / Science with Maths",
        "required_subjects": "Accountancy, Mathematics / Economics",
        "technical_skills": "Statutory Auditing, Indian Accounting Standards (Ind AS), GST Compliance, Corporate Taxation, Financial Analysis, IFRS",
        "soft_skills": "Integrity, Attention to Detail, Analytical Rigor, Ethical Judgment, Communication",
        "tools": "TallyPrime, SAP ERP, Excel (Financial Modeling), Computax, Income Tax / GST Portals",
        "certifications": "Associate Member of the Institute of Chartered Accountants of India (ACA / FCA)",
        "experience_level": "Entry-Level to Senior",
        "career_growth": "Exceptional lifetime trajectory leading to Chief Financial Officer (CFO), Partner at Audit Firm, or Board Director.",
        "internship_roles": "ICAI Articleship (Practical Training - 2 Years)",
        "entry_level_roles": "Qualified Chartered Accountant, Audit Senior, Tax Consultant, Financial Analyst",
        "average_salary": "₹8 - ₹24 LPA (Indicative range)",
        "salary_indicative": "Newly Qualified CA (0-2 yrs): ₹7 - 12 LPA | Mid-Level / Manager (3-6 yrs): ₹14 - 26 LPA | Partner / CFO (7+ yrs): ₹30 - 80+ LPA. Indicative figures from ICAI Placement Committee Reports 2024.",
        "future_scope": "Statutory permanent necessity across all registered Indian corporations, banks, and enterprises.",
        "government_opportunities": "Indian Audit & Accounts Service (IAAS), SEBI, RBI, Serious Fraud Investigation Office (SFIO), PSUs.",
        "private_opportunities": "Big 4 (Deloitte, PwC, EY, KPMG), BDO, Grant Thornton, Tata Group, Reliance, top corporate firms.",
        "higher_study_options": "CPA (USA), CFA (Chartered Financial Analyst), DISA, Executive MBA from IIMs.",
        "entrepreneurship_options": "Independent CA practice firm, taxation and corporate consultancy, wealth advisory.",
        "source": "Institute of Chartered Accountants of India (ICAI)",
        "official_url": "https://www.icai.org",
        "verification_status": "VERIFIED",
        "courses": [{"course_id": 16, "type": "COMMON"}, {"course_id": 19, "type": "ALTERNATIVE"}, {"course_id": 45, "type": "ALTERNATIVE"}],
        "exams": [{"exam_id": 92, "importance": "PRIMARY"}],
        "routes": [
            {"title": "Path A: Foundation Route after 12th", "type": "COMMON", "steps": "Class 12 -> CA Foundation Exam -> CA Intermediate (8 months study) -> 2 Years Articleship Training -> CA Final Exam -> Member of ICAI."},
            {"title": "Path B: Direct Entry Route after Graduation", "type": "COMMON", "steps": "Graduation (Commerce 55%+ or Non-Commerce 60%+) -> Direct Entry to CA Intermediate -> Articleship Training -> CA Final -> Chartered Accountant."}
        ],
        "ladder": [
            {"stage": "CA Articled Assistant", "exp": "0-2 Years (Articleship)", "desc": "Assists with voucher auditing, physical stock verification, basic tax computation."},
            {"stage": "Associate CA / Audit Senior", "exp": "0-3 Years Post-Qual", "desc": "Leads field audit teams, finalizes statutory audit reports, handles corporate tax scrutiny."},
            {"stage": "Senior Manager / Associate Director", "exp": "3-7 Years", "desc": "Manages client audit portfolios, leads M&A financial due diligence."},
            {"stage": "Partner / Chief Financial Officer (CFO)", "exp": "7+ Years", "desc": "Directs firm equity partnership or leads total enterprise financial strategy and treasury."}
        ],
        "roadmaps": {
            "Class 10": "Focus on arithmetic, basic accountancy, and logical problem-solving.",
            "Class 12": "Choose Commerce with Mathematics. Score high in Accountancy, Economics, and Business Studies.",
            "Graduation": "Pursue B.Com alongside CA Intermediate. Dedicate full commitment to the mandatory 2-year practical articleship training.",
            "Working Professional": "Clear CA Final exams, earn certifications in Forensic Accounting or International Taxation (IFRS)."
        }
    },
    {
        "title": "Financial Analyst",
        "short_name": "Financial Analyst",
        "slug": "financial-analyst",
        "category": "Finance, Banking & Accounting",
        "sub_category": "Investment & Corporate Finance",
        "industry": "Financial Services / Banking",
        "icon": "cash-stack",
        "short_description": "Analyzes financial data, builds forecast models, and evaluates investments to guide corporate and institutional decision-making.",
        "description": "Financial Analysts assess the performance of stocks, bonds, corporate capital investments, and macroeconomic indicators. They build financial models, assess investment risks, and provide actionable recommendations to portfolio managers and corporate leaders.",
        "what_they_do": "They examine company balance sheets and cash flow statements, build Discounted Cash Flow (DCF) valuation models, conduct competitive market research, and prepare investment research notes.",
        "day_to_day_work": "• Constructing three-statement financial models and forecasting scenarios in Excel.\n• Monitoring industry trends, quarterly corporate earnings calls, and economic news.\n• Performing equity valuation using DCF and comparable company analysis (Comps).\n• Preparing PowerPoint pitch decks and financial advisory memos for leadership.\n• Tracking financial KPIs and variance analysis against corporate budgets.",
        "work_environment": "Investment banks, asset management firms, corporate finance divisions, financial consultancies.",
        "work_modes": "Hybrid / On-site",
        "minimum_qualification": "Undergraduate",
        "preferred_streams": "Commerce / Science with Maths / Economics",
        "required_subjects": "Mathematics, Economics, Accountancy",
        "technical_skills": "Financial Modeling, Valuation (DCF, Multiples), Financial Statement Analysis, Excel, Corporate Finance, Capital Markets",
        "soft_skills": "Analytical Rigor, Fast Problem Solving, Executive Presentation, Attention to Detail",
        "tools": "Microsoft Excel, Bloomberg Terminal, FactSet, Capital IQ, Power BI, Python",
        "certifications": "Chartered Financial Analyst (CFA Institute), Financial Risk Manager (FRM)",
        "experience_level": "Entry-Level to Senior",
        "career_growth": "Rapid progression into Investment Banking Associate, Portfolio Manager, or Chief Investment Officer (CIO).",
        "internship_roles": "Financial Analyst Intern, Equity Research Intern, Corporate Finance Trainee",
        "entry_level_roles": "Junior Financial Analyst, Research Associate, Corporate Finance Analyst",
        "average_salary": "₹5 - ₹16 LPA (Indicative range)",
        "salary_indicative": "Entry-Level (0-2 yrs): ₹4.5 - 7.5 LPA | Mid-Level / Senior Analyst (3-6 yrs): ₹9 - 18 LPA | VP of Finance / Portfolio Manager (7+ yrs): ₹22 - 50+ LPA. Indicative figures from CFA Institute & Banking Audits 2024.",
        "future_scope": "Consistently robust demand across India's booming capital markets, private equity, and venture ecosystems.",
        "government_opportunities": "SEBI Grade A Officer, RBI Grade B Officer, National Housing Bank, SBI Capital Markets.",
        "private_opportunities": "J.P. Morgan, Goldman Sachs, Morgan Stanley, HDFC AMC, ICICI Securities, CRISIL, corporate finance teams.",
        "higher_study_options": "MBA in Finance (IIMs, ISB), CFA Charter, Master's in Financial Engineering (MFE).",
        "entrepreneurship_options": "Independent investment research boutique, financial advisory firm, angel syndicate management.",
        "source": "CFA Institute / National Career Service (NCS)",
        "official_url": "https://www.cfainstitute.org",
        "verification_status": "VERIFIED",
        "courses": [{"course_id": 16, "type": "COMMON"}, {"course_id": 18, "type": "SPECIALIZED"}, {"course_id": 20, "type": "COMMON"}, {"course_id": 17, "type": "COMMON"}],
        "exams": [{"exam_id": 77, "importance": "PRIMARY"}, {"exam_id": 44, "importance": "ALTERNATIVE"}],
        "routes": [
            {"title": "Path A: Commerce / Economics + CFA Pathway", "type": "COMMON", "steps": "Class 12 -> B.Com / BA Economics -> Clear CFA Level 1 -> Financial Modeling Projects -> Equity Research / Financial Analyst."},
            {"title": "Path B: Engineering / BBA + Top MBA in Finance", "type": "COMMON", "steps": "Undergraduate degree -> CAT / GMAT -> Top IIM / XLRI Finance MBA -> Investment Banking or Financial Analyst campus hire."}
        ],
        "ladder": [
            {"stage": "Junior Financial Analyst", "exp": "0-2 Years", "desc": "Collects financial data, updates financial models, prepares peer company multiples."},
            {"stage": "Senior Financial Analyst / Associate", "exp": "2-5 Years", "desc": "Builds end-to-end valuation models, writes research reports, attends investor calls."},
            {"stage": "Vice President / Portfolio Manager", "exp": "5-9 Years", "desc": "Manages fund investment strategy, decides asset allocation, presents to institutional clients."},
            {"stage": "Chief Investment Officer (CIO) / CFO", "exp": "9+ Years", "desc": "Directs institutional asset portfolio of thousands of crores or enterprise treasury."}
        ],
        "roadmaps": {
            "Class 10": "Develop strong numerical ability and read business news to understand how companies work.",
            "Class 12": "Choose Commerce or Science with Mathematics. Master compound interest, algebra, and economics.",
            "Graduation": "Learn advanced Excel shortcuts, build DCF models on public Indian companies, and register for CFA Level 1 in final year.",
            "Working Professional": "Clear CFA Level 2 and Level 3, learn Python for financial data analysis, and master capital market regulation."
        }
    },
    {
        "title": "Commercial Banking Officer",
        "short_name": "Banking Officer (PO)",
        "slug": "banking-officer",
        "category": "Finance, Banking & Accounting",
        "sub_category": "Retail & Corporate Banking",
        "industry": "Banking & Financial Services",
        "icon": "bank",
        "short_description": "Manages branch operations, evaluates credit and loan applications, and drives retail and corporate financial services.",
        "description": "Commercial Banking Officers oversee financial operations within bank branches and commercial lending divisions. They evaluate retail and MSME loan proposals, manage treasury operations, ensure RBI compliance, and drive digital banking adoption.",
        "what_they_do": "They assess creditworthiness of loan applicants, disburse personal and commercial credit, handle foreign exchange transactions, manage branch customer service, and ensure strict Anti-Money Laundering (AML) and KYC compliance.",
        "day_to_day_work": "• Appraising credit proposals and evaluating collateral documentation.\n• Overseeing cash, clearing, and digital fund settlement operations.\n• Cross-selling financial products (mutual funds, insurance, government savings schemes).\n• Reviewing non-performing assets (NPAs) and coordinating recovery procedures.\n• Assisting retail and corporate customers with specialized banking requirements.",
        "work_environment": "Bank branches, corporate banking regional offices, commercial financial centers.",
        "work_modes": "On-site / Branch Operations",
        "minimum_qualification": "Undergraduate (Any Stream)",
        "preferred_streams": "Any Stream (Commerce / Economics / Engineering)",
        "required_subjects": "Graduation in any recognized discipline",
        "technical_skills": "Credit Appraisal, Banking Law & Practice, AML/KYC Compliance, Financial Statement Analysis, RBI Guidelines, Core Banking Solutions (CBS)",
        "soft_skills": "Customer Service, Integrity, Public Relations, Decisiveness, Team Leadership",
        "tools": "Finacle (Infosys), BaNCS (TCS), Credit Bureau Portals (CIBIL, Experian), Excel",
        "certifications": "JAIIB (Junior Associate of IIBF), CAIIB (Certified Associate of IIBF)",
        "experience_level": "Entry-Level to Senior",
        "career_growth": "Structured and prestigious career progression into Branch Manager, Chief Manager, DGM, General Manager, or Bank Director.",
        "internship_roles": "Banking Intern, Retail Credit Trainee, Customer Relationship Trainee",
        "entry_level_roles": "Probationary Officer (PO), Assistant Manager, Customer Service Associate",
        "average_salary": "₹5 - ₹12 LPA (Indicative range)",
        "salary_indicative": "Probationary Officer (0-2 yrs): ₹5 - 7.5 LPA | Branch Manager (3-6 yrs): ₹8 - 14 LPA | Chief Manager / AGM (7+ yrs): ₹16 - 28+ LPA. Indicative figures from Indian Banks' Association (IBA) 12th Bipartite Settlement 2024.",
        "future_scope": "Permanent essential pillar of the Indian economy with major financial inclusion and digital banking initiatives.",
        "government_opportunities": "IBPS PO, SBI PO, RBI Grade B, NABARD Grade A, SIDBI Assistant Manager, Bank of Baroda PO.",
        "private_opportunities": "HDFC Bank, ICICI Bank, Axis Bank, Kotak Mahindra Bank, IndusInd Bank, Federal Bank.",
        "higher_study_options": "MBA in Banking & Finance, CAIIB Certification, Certified Credit Professional (IIBF).",
        "entrepreneurship_options": "Micro-finance institution leadership, corporate debt syndication consultancy.",
        "source": "Indian Institute of Banking & Finance (IIBF) / IBPS",
        "official_url": "https://www.iibf.org.in",
        "verification_status": "VERIFIED",
        "courses": [{"course_id": 16, "type": "COMMON"}, {"course_id": 17, "type": "COMMON"}, {"course_id": 20, "type": "COMMON"}, {"course_id": 18, "type": "SPECIALIZED"}],
        "exams": [{"exam_id": 3, "importance": "PRIMARY"}, {"exam_id": 4, "importance": "PRIMARY"}, {"exam_id": 5, "importance": "ALTERNATIVE"}],
        "routes": [
            {"title": "Path A: Public Sector Banking Route (IBPS / SBI)", "type": "COMMON", "steps": "Graduation in any stream -> Prepare for IBPS PO / SBI PO Examination (Prelims + Mains + Interview) -> Probationary Officer -> Branch Manager."},
            {"title": "Path B: Private Sector Banking Route", "type": "COMMON", "steps": "Graduation (Commerce/BBA/Engg) -> Private Bank PO Program (e.g., ICICI Manipal, HDFC Future Bankers) or direct campus hiring -> Assistant Manager."}
        ],
        "ladder": [
            {"stage": "Probationary Officer / Assistant Manager (Scale I)", "exp": "0-2 Years", "desc": "Undergoes branch rotation in general banking, credit processing, foreign exchange."},
            {"stage": "Branch Manager / Manager (Scale II/III)", "exp": "2-6 Years", "desc": "Leads a bank branch, approves credit limits, oversees business growth and audit ratings."},
            {"stage": "Chief Manager / Assistant General Manager (Scale IV/V)", "exp": "6-10 Years", "desc": "Heads regional cluster or zonal corporate credit departments."},
            {"stage": "Deputy General Manager / General Manager (Scale VI/VII)", "exp": "10+ Years", "desc": "Sets policy for nationwide retail banking, risk management, or treasury."}
        ],
        "roadmaps": {
            "Class 10": "Build speed in mental arithmetic, percentages, and basic English comprehension.",
            "Class 12": "Complete Class 12 in any stream. Read daily national newspapers to stay updated on economic affairs.",
            "Graduation": "Complete graduation with good standing. Dedicate 6-12 months for Quantitative Aptitude, Reasoning, English, and Banking Awareness.",
            "Working Professional": "Clear JAIIB and CAIIB certifications immediately upon joining to earn accelerated increments and promotions."
        }
    },
    {
        "title": "Actuary",
        "short_name": "Actuary (FIAI)",
        "slug": "actuary",
        "category": "Finance, Banking & Accounting",
        "sub_category": "Actuarial Science & Risk",
        "industry": "Insurance & Risk Management",
        "icon": "calculator",
        "short_description": "Uses advanced mathematics, statistics, and financial theory to assess and manage financial risks in insurance and pensions.",
        "description": "Actuaries are elite mathematical risk specialists who evaluate the probability of future uncertain events such as illness, accidents, natural catastrophes, mortality, and economic downturns. They design insurance products, set premium pricing, and ensure company solvency.",
        "what_they_do": "They analyze mortality and morbidity data, construct actuarial risk models, calculate regulatory reserves, price life and general insurance contracts, and advise pension fund boards on long-term sustainability.",
        "day_to_day_work": "• Building complex probability and statistical risk models in R or Python.\n• Calculating insurance premiums and cash flow reserves (solvency margin).\n• Analyzing claims history to detect risk distribution anomalies.\n• Presenting financial valuation reports to the Appointed Actuary and IRDAI regulators.\n• Developing retirement benefit plans and asset-liability management (ALM) models.",
        "work_environment": "Insurance headquarters, reinsurance firms, global actuarial consultancies, pension authorities.",
        "work_modes": "Hybrid / Office",
        "minimum_qualification": "Undergraduate (Maths / Stats / Actuarial Science)",
        "preferred_streams": "Science (PCM) / Commerce with Maths",
        "required_subjects": "Mathematics, Statistics",
        "technical_skills": "Actuarial Mathematics, Stochastic Modeling, Probability Theory, Life Contingencies, R, Python, SQL, Financial Valuation",
        "soft_skills": "Exceptional Quantitative Aptitude, Problem Solving, Discretion, Strategic Judgment",
        "tools": "R, Python, Prophet Actuarial Software, Excel (VBA), SQL",
        "certifications": "Fellow of the Institute of Actuaries of India (FIAI) / IFoA (UK)",
        "experience_level": "Entry-Level to Senior",
        "career_growth": "Rare, highly compensated profession with direct progression to Appointed Actuary, Chief Risk Officer (CRO), or Insurance CEO.",
        "internship_roles": "Actuarial Intern, Actuarial Analyst Trainee, Risk Modeling Intern",
        "entry_level_roles": "Actuarial Analyst, Student Actuary, Valuation Associate",
        "average_salary": "₹7 - ₹25 LPA (Indicative range)",
        "salary_indicative": "Student Actuary (3-5 papers cleared): ₹5 - 9 LPA | Associate Actuary (7-10 papers): ₹12 - 22 LPA | Qualified Fellow Actuary (FIAI): ₹30 - 70+ LPA. Indicative figures from Institute of Actuaries of India (IAI) 2024.",
        "future_scope": "Extremely high global demand with zero unemployment for fully qualified Fellows across life, health, general insurance, and climate risk.",
        "government_opportunities": "Insurance Regulatory and Development Authority of India (IRDAI), Life Insurance Corporation (LIC), GIC Re, Employees' Provident Fund Organisation (EPFO).",
        "private_opportunities": "HDFC Life, ICICI Prudential, Max Life, Swiss Re, Munich Re, Willis Towers Watson, Milliman.",
        "higher_study_options": "M.Sc Actuarial Science, Fellowship of IAI / IFoA.",
        "entrepreneurship_options": "Boutique actuarial consulting firm, pension valuation consultancy.",
        "source": "Institute of Actuaries of India (IAI)",
        "official_url": "https://www.actuariesindia.org",
        "verification_status": "VERIFIED",
        "courses": [{"course_id": 1, "type": "COMMON"}, {"course_id": 39, "type": "DIRECT"}, {"course_id": 34, "type": "SPECIALIZED"}],
        "exams": [{"exam_id": 79, "importance": "PRIMARY"}],
        "routes": [
            {"title": "Path A: IAI Actuarial Exams Route", "type": "COMMON", "steps": "Class 12 (Maths) -> Clear ACET (Actuarial Common Entrance Test) -> Pursue B.Sc Statistics / Mathematics -> Clear 13 IAI Professional Exams while working as an Actuarial Analyst -> Fellow Actuary (FIAI)."}
        ],
        "ladder": [
            {"stage": "Actuarial Analyst (3-6 papers)", "exp": "0-2 Years", "desc": "Runs standard reserve calculations, cleans policyholder data, maintains Excel models."},
            {"stage": "Senior Actuarial Associate (7-10 papers)", "exp": "2-5 Years", "desc": "Builds pricing models for new insurance products, writes statutory valuation documentation."},
            {"stage": "Appointed Actuary / Chief Actuary", "exp": "5-10 Years (Fully Qualified)", "desc": "Legally signs off on insurance company solvency, pricing, and capital reserves."},
            {"stage": "Chief Risk Officer / Managing Director", "exp": "10+ Years", "desc": "Heads total enterprise enterprise risk, reinsurance treaties, and corporate strategy."}
        ],
        "roadmaps": {
            "Class 10": "Demonstrate passion and top-percentile performance in Mathematics.",
            "Class 12": "Score 90%+ in Mathematics. Master probability, calculus, and permutations/combinations.",
            "Graduation": "Pursue B.Sc in Statistics or Mathematics. Clear ACET and 3-4 initial IAI core actuarial papers (CB1, CB2, CM1, CS1).",
            "Working Professional": "Join an insurance company or actuarial consultancy as an analyst while completing remaining specialist exams for FIAI fellowship."
        }
    },
    {
        "title": "Cost and Management Accountant (CMA)",
        "short_name": "Cost Accountant (CMA)",
        "slug": "cost-management-accountant",
        "category": "Finance, Banking & Accounting",
        "sub_category": "Costing & Operational Management",
        "industry": "Manufacturing & Corporate Finance",
        "icon": "calculator-fill",
        "short_description": "Optimizes corporate cost structures, controls production expenditures, and ensures cost audit compliance under ICMAI.",
        "description": "Cost and Management Accountants specialize in strategic cost management, price determination, operational efficiency, and performance evaluation. They conduct statutory cost audits for manufacturing corporations and help executives optimize profit margins.",
        "what_they_do": "They design cost accounting systems, conduct cost audits under the Companies Act, analyze variances in materials and labor, establish product pricing strategies, and eliminate operational waste.",
        "day_to_day_work": "• Analyzing standard costing variances (material, labor, overheads).\n• Preparing statutory cost audit reports for industrial manufacturing lines.\n• Setting transfer pricing policies and optimizing supply chain expenditure.\n• Assisting factory management with capital expenditure (Capex) justification.\n• Managing corporate budgets and cost-benefit feasibility studies.",
        "work_environment": "Industrial manufacturing plants, corporate finance headquarters, or consulting practices.",
        "work_modes": "On-site / Corporate Plant Audits / Hybrid",
        "minimum_qualification": "ICMAI Professional Qualification",
        "preferred_streams": "Commerce / Science with Maths",
        "required_subjects": "Accountancy, Mathematics",
        "technical_skills": "Cost Auditing, Marginal Costing, Activity-Based Costing (ABC), Budgetary Control, Financial Management, SAP CO Module",
        "soft_skills": "Operational Thinking, Analytical Mindset, Negotiation, Problem Solving",
        "tools": "SAP (FICO / CO module), TallyPrime, Microsoft Excel (Financial Modeling)",
        "certifications": "Associate Member of the Institute of Cost Accountants of India (ACMA / FCMA)",
        "experience_level": "Entry-Level to Senior",
        "career_growth": "Steady trajectory leading to Head of Costing, VP of Supply Chain Finance, or Chief Financial Officer (CFO).",
        "internship_roles": "ICMAI Practical Training (15 Months)",
        "entry_level_roles": "Cost Trainee, Management Accountant, Plant Finance Officer",
        "average_salary": "₹6 - ₹15 LPA (Indicative range)",
        "salary_indicative": "Newly Qualified CMA (0-2 yrs): ₹5.5 - 9 LPA | Mid-Level Cost Controller (3-6 yrs): ₹10 - 18 LPA | Head of Costing / CFO (7+ yrs): ₹20 - 45+ LPA. Indicative figures from ICMAI Placement Reports 2024.",
        "future_scope": "Critical role in India's booming manufacturing sector (Make in India, PLI schemes, heavy industry).",
        "government_opportunities": "Indian Cost Accounts Service (ICoAS - UPSC), BHEL, ONGC, NTPC, Coal India, Indian Oil.",
        "private_opportunities": "Tata Motors, Larsen & Toubro, Reliance Industries, Mahindra, Maruti Suzuki, FMCG giants.",
        "higher_study_options": "CIMA (UK), CMA (USA), Executive MBA.",
        "entrepreneurship_options": "Independent Cost Accounting firm, cost reduction consulting practice.",
        "source": "Institute of Cost Accountants of India (ICMAI)",
        "official_url": "https://www.icmai.in",
        "verification_status": "VERIFIED",
        "courses": [{"course_id": 16, "type": "COMMON"}, {"course_id": 19, "type": "ALTERNATIVE"}],
        "exams": [{"exam_id": 94, "importance": "PRIMARY"}],
        "routes": [
            {"title": "Path A: ICMAI Foundation Route", "type": "COMMON", "steps": "Class 12 -> CMA Foundation -> CMA Intermediate (Group 1 & 2) -> 15 Months Practical Training -> CMA Final -> Qualified Cost Accountant."}
        ],
        "ladder": [
            {"stage": "CMA Practical Trainee", "exp": "0-1.5 Years", "desc": "Assists with inventory valuation, raw material reconciliation, cost center logging."},
            {"stage": "Plant Cost Accountant", "exp": "0-3 Years Post-Qual", "desc": "Manages plant cost sheets, reports production variances, tracks energy consumption."},
            {"stage": "Head of Cost Control / Finance Controller", "exp": "3-7 Years", "desc": "Optimizes supply chain expenditure, leads annual cost audit compliance."},
            {"stage": "Director of Finance / CFO", "exp": "7+ Years", "desc": "Sets enterprise pricing strategies, capital budgets, and manufacturing profitability."}
        ],
        "roadmaps": {
            "Class 10": "Build strong interest in math, business, and industry.",
            "Class 12": "Excel in Accountancy, Mathematics, and Economics.",
            "Graduation": "Pursue B.Com while clearing CMA Intermediate. Complete the 15-month practical training in a manufacturing PSU or top corporate.",
            "Working Professional": "Clear CMA Final, master SAP CO (Controlling) module, and lead industrial cost-saving transformations."
        }
    },
    {
        "title": "Company Secretary (CS)",
        "short_name": "Company Secretary",
        "slug": "company-secretary",
        "category": "Finance, Banking & Accounting",
        "sub_category": "Corporate Governance & Compliance",
        "industry": "Corporate Law & Governance",
        "icon": "file-earmark-check",
        "short_description": "Acts as the principal advisor on corporate governance, board procedures, and statutory compliance under ICSI.",
        "description": "Company Secretaries are key governance professionals recognized as Key Managerial Personnel (KMP) under the Companies Act, 2013. They ensure that corporate boards adhere to all statutory and legal mandates, organize board meetings, and manage shareholder relations.",
        "what_they_do": "They advise boards of directors on corporate governance, ensure compliance with SEBI listing regulations (LODR), handle filing of statutory forms with the Ministry of Corporate Affairs (MCA), and manage corporate restructuring.",
        "day_to_day_work": "• Preparing agendas and drafting minutes for Board of Directors and AGM meetings.\n• Ensuring continuous compliance with SEBI (LODR) regulations for listed entities.\n• Filing statutory returns and forms on the MCA-21 portal.\n• Managing corporate secretarial audits and legal due diligence.\n• Advising corporate leadership on insider trading regulations and corporate ethics.",
        "work_environment": "Corporate headquarters, listed company boardrooms, legal and secretarial firms.",
        "work_modes": "On-site / Corporate Office",
        "minimum_qualification": "ICSI Professional Qualification",
        "preferred_streams": "Commerce / Arts / Any Stream",
        "required_subjects": "Commercial Law, Business Studies, English",
        "technical_skills": "Companies Act 2013, SEBI Regulations (LODR), Secretarial Audits, Corporate Restructuring, Due Diligence, Drafting Legal Documents",
        "soft_skills": "Uncompromising Integrity, Executive Diplomacy, Meticulous Precision, Communication",
        "tools": "MCA-21 Portal, BSE/NSE Listing Portals, Diligent Boardbooks, Excel",
        "certifications": "Associate Member of the Institute of Company Secretaries of India (ACS / FCS)",
        "experience_level": "Entry-Level to Senior",
        "career_growth": "Direct executive growth to Head of Legal & Secretarial, Corporate Vice President, or Member of the Board.",
        "internship_roles": "ICSI Long-Term Practical Training (21 Months)",
        "entry_level_roles": "Assistant Company Secretary, Secretarial Officer, Compliance Executive",
        "average_salary": "₹6 - ₹16 LPA (Indicative range)",
        "salary_indicative": "Newly Qualified CS (0-2 yrs): ₹5 - 8 LPA | Mid-Level / Company Secretary (3-6 yrs): ₹10 - 18 LPA | Head of Legal & CS (7+ yrs): ₹22 - 50+ LPA. Indicative figures from ICSI Placement Audits 2024.",
        "future_scope": "Mandatory statutory requirement under Section 203 of the Companies Act for every listed company and large private firm.",
        "government_opportunities": "Ministry of Corporate Affairs (MCA), SEBI, Competition Commission of India (CCI), PSUs.",
        "private_opportunities": "Reliance Industries, Tata Sons, Infosys, HDFC, Larsen & Toubro, top law and secretarial consultancies.",
        "higher_study_options": "LLB (Law Degree - common complementary dual qualification), LLM in Corporate Law, MBA.",
        "entrepreneurship_options": "Practicing Company Secretary (PCS) firm, corporate legal compliance advisory.",
        "source": "Institute of Company Secretaries of India (ICSI)",
        "official_url": "https://www.icsi.edu",
        "verification_status": "VERIFIED",
        "courses": [{"course_id": 16, "type": "COMMON"}, {"course_id": 29, "type": "COMMON"}, {"course_id": 30, "type": "ALTERNATIVE"}],
        "exams": [{"exam_id": 93, "importance": "PRIMARY"}],
        "routes": [
            {"title": "Path A: ICSI Foundation / CSEET Route", "type": "COMMON", "steps": "Class 12 -> CSEET (CS Executive Entrance Test) -> CS Executive Program -> 21 Months Practical Training -> CS Professional Program -> Qualified CS."}
        ],
        "ladder": [
            {"stage": "CS Management Trainee", "exp": "0-2 Years", "desc": "Assists with secretarial documentation, ROC filings, drafts simple resolutions."},
            {"stage": "Company Secretary / Compliance Officer", "exp": "0-4 Years Post-Qual", "desc": "Key Managerial Personnel (KMP) signing statutory filings, manages board meetings."},
            {"stage": "Senior VP - Legal & Secretarial", "exp": "4-8 Years", "desc": "Heads investor relations, SEBI compliance, handles mergers and acquisitions legalities."},
            {"stage": "Board Director / Chief Governance Officer", "exp": "8+ Years", "desc": "Serves as institutional guardian of corporate ethics and board governance."}
        ],
        "roadmaps": {
            "Class 10": "Develop strong command over English writing and comprehension.",
            "Class 12": "Choose Commerce or Humanities with Commercial Law or Business Studies.",
            "Graduation": "Clear CSEET and CS Executive while pursuing B.Com or LLB (Law is a powerful combination with CS). Complete 21-month practical training.",
            "Working Professional": "Clear CS Professional, specialize in SEBI regulations and secretarial audits, or set up a PCS firm."
        }
    }
]

print(f"Loaded {len(FINANCE_CAREERS)} Finance Careers")
