"""
scripts/catalog_builder_part6.py
Authentic occupational profiles for Media, Design, Agriculture, Aviation, and Social Sciences.
"""

def get_media_careers():
    return [
        {
            "title": "Investigative Journalist & Reporter",
            "short_name": "Journalist / Reporter",
            "slug": "investigative-journalist",
            "category": "Media, Journalism & Digital Marketing",
            "sub_category": "Journalism & Mass Communication",
            "industry": "News Media & Broadcasting",
            "icon": "newspaper",
            "short_description": "Investigates, researches, and reports news stories, holding public and corporate institutions accountable.",
            "description": "Journalists report verifiable facts to the public. Investigative journalists uncover corruption, public policy failures, financial crimes, and human rights violations, acting as the Fourth Pillar of Indian democracy.",
            "what_they_do": "They interview sources, verify public documents through Right to Information (RTI) applications, write news articles, produce broadcast news packages, and report from breaking news ground zero.",
            "day_to_day_work": "• Cultivating and verifying confidential sources and whistleblowers.\n• Filing and analyzing Right to Information (RTI) government records.\n• Conducting field interviews and on-the-ground reporting.\n• Fact-checking claims and cross-referencing documentary evidence.\n• Writing news stories adhering to strict journalistic ethics and libel laws.",
            "work_environment": "Newsrooms, broadcast television studios, press conferences, field news beats.",
            "work_modes": "On-site / Field Reporting / Irregular Breaking News Hours",
            "minimum_qualification": "Undergraduate (BJMC / B.A. Journalism / English / Any Stream)",
            "preferred_streams": "Humanities / Any Stream",
            "required_subjects": "Journalism, English, Political Science",
            "technical_skills": "Investigative Reporting, RTI Research, Media Law & Defamation, News Writing, Audio/Video Editing, Fact-Checking",
            "soft_skills": "Fearless Inquisitiveness, Tenacity, Uncompromising Integrity, Storytelling",
            "tools": "RTI Portals, Recording Devices, Video Editing (Premiere Pro), Fact-Checking Tools",
            "certifications": "Degree from Indian Institute of Mass Communication (IIMC) or ACJ Chennai",
            "experience_level": "Entry-Level to Senior Editor",
            "career_growth": "Broad career path progressing to Bureau Chief, Senior Editor, News Anchor, or Editor-in-Chief.",
            "internship_roles": "Newsroom Reporting Intern, Desk Editorial Intern, Broadcast Intern",
            "entry_level_roles": "Trainee Journalist, Sub-Editor, Field Reporter, Copy Editor",
            "average_salary": "₹4 - ₹12 LPA (Indicative range)",
            "salary_indicative": "Trainee Reporter (0-2 yrs): ₹3.5 - 5.5 LPA | Senior Correspondent (3-6 yrs): ₹6.5 - 14 LPA | Editor-in-Chief (7+ yrs): ₹20 - 50+ LPA. Indicative figures from Press Council of India & Media Audits 2024.",
            "future_scope": "Continuous democratic importance adapting to digital multimedia, newsletter journalism, and podcast reporting.",
            "government_opportunities": "Press Information Bureau (PIB - Indian Information Service via UPSC), Doordarshan News, All India Radio.",
            "private_opportunities": "The Indian Express, The Hindu, NDTV, Times Group, Hindustan Times, BBC India, digital news publications.",
            "higher_study_options": "Master's in Journalism & Mass Communication (IIMC, ACJ), Nieman Fellowship.",
            "entrepreneurship_options": "Independent investigative digital media outlet, hyper-local news platform, podcast production company.",
            "source": "Press Council of India (PCI) / IIMC",
            "official_url": "https://iimc.gov.in",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 21, "type": "COMMON"}, {"course_id": 22, "type": "COMMON"}, {"course_id": 46, "type": "ALTERNATIVE"}],
            "exams": [{"exam_id": 79, "importance": "PRIMARY"}],
            "routes": [{"title": "Path A: Mass Communication Route (IIMC / ACJ)", "type": "COMMON", "steps": "Graduation in any stream -> Clear IIMC Entrance Exam or ACJ Entrance -> PG Diploma in Journalism (1 yr) -> Newsroom Campus Placement -> Trainee Reporter."}],
            "ladder": [
                {"stage": "Trainee Reporter / Sub-Editor", "exp": "0-2 Years", "desc": "Covers daily beat stories, rewires press releases, checks facts on the desk."},
                {"stage": "Senior Correspondent / Investigative Reporter", "exp": "2-5 Years", "desc": "Breaks investigative exposes, files RTIs, covers major state and national beats."},
                {"stage": "Bureau Chief / News Editor", "exp": "5-9 Years", "desc": "Directs city or national news bureau reporting teams, decides daily front-page layout."},
                {"stage": "Editor-in-Chief", "exp": "9+ Years", "desc": "Sets complete editorial voice and journalistic standards for major news organization."}
            ],
            "roadmaps": {
                "Class 10": "Read national newspapers every day and write short essays on current events.",
                "Class 12": "Choose Humanities, Commerce, or Science with strong English command.",
                "Graduation": "Complete Bachelor's degree (BA Journalism or English/History/Pol Science). Write for university newspapers and blog regularly.",
                "Working Professional": "Target premier journalism schools like IIMC New Delhi or Asian College of Journalism (ACJ) Chennai."
            }
        },
        {
            "title": "Digital Marketing Strategist",
            "short_name": "Digital Marketer",
            "slug": "digital-marketing-strategist",
            "category": "Media, Journalism & Digital Marketing",
            "sub_category": "Digital Marketing & Growth",
            "industry": "Marketing & Advertising",
            "icon": "megaphone",
            "short_description": "Drives customer acquisition, brand awareness, and revenue growth across digital search, social, and programmatic advertising channels.",
            "description": "Digital Marketing Strategists build online growth engines. They manage search engine optimization (SEO), pay-per-click advertising (Google Ads, Meta Ads), content marketing, email funnels, and performance marketing to convert web visitors into loyal paying customers.",
            "what_they_do": "They design performance ad campaigns, optimize conversion funnels (CRO), track Customer Acquisition Cost (CAC) and Lifetime Value (LTV), perform keyword research, and execute social media viral marketing campaigns.",
            "day_to_day_work": "• Managing and scaling paid ad budgets on Google Ads and Meta Ads Manager.\n• Analyzing website traffic, user bounce rates, and funnels in Google Analytics 4 (GA4).\n• Conducting technical SEO audits and keyword backlink strategies.\n• Designing automated email nurturing drips and push notification workflows.\n• Running A/B landing page conversion tests with creative design teams.",
            "work_environment": "Tech startups, digital advertising agencies, e-commerce brand offices, or remote.",
            "work_modes": "Remote / Hybrid / Office",
            "minimum_qualification": "Undergraduate (Any Stream)",
            "preferred_streams": "Any Stream (Commerce / BBA / Marketing preferred)",
            "required_subjects": "Marketing, Computer Applications, English",
            "technical_skills": "Search Engine Optimization (SEO), Performance Marketing (PPC), Google Analytics 4, Meta Ads, Email Automation, Conversion Rate Optimization (CRO), SQL basics",
            "soft_skills": "Creative Storytelling, Data-Driven Analytical Mindset, Fast Experimentation, Agility",
            "tools": "Google Ads, Meta Ads Manager, GA4, Semrush, Ahrefs, HubSpot, Mailchimp",
            "certifications": "Google Ads Search Certification, Meta Certified Digital Marketing Associate, HubSpot Inbound Marketing",
            "experience_level": "Entry-Level to Senior",
            "career_growth": "Rapid growth with progression to Growth Marketing Lead, VP of Marketing, or Chief Marketing Officer (CMO).",
            "internship_roles": "Digital Marketing Intern, SEO Intern, Social Media Intern",
            "entry_level_roles": "Digital Marketing Executive, SEO Analyst, Performance Marketing Associate",
            "average_salary": "₹4.5 - ₹15 LPA (Indicative range)",
            "salary_indicative": "Entry-Level Executive (0-2 yrs): ₹3.8 - 6.5 LPA | Growth Manager (3-6 yrs): ₹8 - 18 LPA | VP Marketing / CMO (7+ yrs): ₹22 - 50+ LPA. Indicative figures from IAMAI 2024.",
            "future_scope": "Surging demand driven by D2C brands, e-commerce, and the universal shift of advertising budgets from print/TV to digital.",
            "government_opportunities": "Digital India Social Media Wings, MyGov Digital Outreach, State Tourism Digital Boards.",
            "private_opportunities": "Zomato, Swiggy, Nykaa, Dentsu, Ogilvy, top D2C consumer brands and venture-backed startups.",
            "higher_study_options": "MBA in Marketing (IIMs), Master's in Strategic Brand Management.",
            "entrepreneurship_options": "Performance marketing agency, D2C brand founder, niche affiliate marketing network.",
            "source": "Internet and Mobile Association of India (IAMAI)",
            "official_url": "https://www.iamai.in",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 17, "type": "COMMON"}, {"course_id": 16, "type": "COMMON"}, {"course_id": 18, "type": "SPECIALIZED"}],
            "exams": [{"exam_id": 77, "importance": "PRIMARY"}, {"exam_id": 79, "importance": "ALTERNATIVE"}],
            "routes": [{"title": "Path A: Degree + Hands-On Digital Portfolio", "type": "COMMON", "steps": "Undergraduate degree (Any stream) -> Earn Google & Meta Ads certifications -> Manage live ad budgets / ranking blogs -> Performance Marketing Specialist."}],
            "ladder": [
                {"stage": "Digital Marketing Executive", "exp": "0-2 Years", "desc": "Sets up search and social ad sets, optimizes ad copy, reports weekly ROAS."},
                {"stage": "Growth Marketing Manager", "exp": "2-5 Years", "desc": "Manages multi-crore monthly ad spend, optimizes CAC:LTV unit economics, runs A/B tests."},
                {"stage": "Director of Performance Marketing", "exp": "5-8 Years", "desc": "Leads cross-functional growth teams across SEO, paid ads, lifecycle retention."},
                {"stage": "Chief Marketing Officer (CMO)", "exp": "8+ Years", "desc": "Owns total enterprise brand identity, multi-channel growth budget, and market share."}
            ],
            "roadmaps": {
                "Class 10": "Learn how social media algorithms, viral videos, and search engines work.",
                "Class 12": "Choose Commerce or Humanities with English and Business Studies.",
                "Graduation": "Complete BBA, B.Com, or any degree. Build a website and rank it on Google with SEO; run small paid ad campaigns with real budget.",
                "Working Professional": "Master Google Analytics 4, cohort retention, and programmatic advertising platforms."
            }
        }
    ]

def get_agriculture_careers():
    return [
        {
            "title": "Agricultural Scientist & Agronomist",
            "short_name": "Agricultural Scientist",
            "slug": "agricultural-scientist",
            "category": "Agriculture, Food Technology & Environment",
            "sub_category": "Crop Science & Sustainable Agriculture",
            "industry": "Agriculture & Bio-Sciences",
            "icon": "flower1",
            "short_description": "Researches crop genetics, soil fertility, climate-resilient farming, and agricultural biotechnology to maximize sustainable food production.",
            "description": "Agricultural Scientists and Agronomists develop high-yielding, drought-resistant crop varieties, optimize soil nutrient management, and pioneer precision farming techniques to ensure national food security and farmer prosperity.",
            "what_they_do": "They breed high-yield crop seeds, formulate organic and chemical soil fertility regimens, develop integrated pest management (IPM) protocols, analyze soil microbiomes, and train farmers in modern agricultural techniques.",
            "day_to_day_work": "• Designing crop trial plots at agricultural experimental research stations.\n• Analyzing soil chemistry (N-P-K levels, pH, organic carbon) in laboratories.\n• Hybridizing crop varieties for disease resistance and climate resilience.\n• Evaluating drip irrigation efficiency and precision farming sensors.\n• Publishing research papers and authoring farmer extension bulletins.",
            "work_environment": "ICAR research institutes, state agricultural universities, experimental farm stations, seed companies.",
            "work_modes": "On-site / Field Experiments / Laboratory",
            "minimum_qualification": "Postgraduate (M.Sc Agriculture) / Ph.D. in Agronomy / Genetics",
            "preferred_streams": "Science (PCB / Agriculture)",
            "required_subjects": "Agriculture, Biology, Chemistry",
            "technical_skills": "Plant Breeding, Soil Chemistry, Agronomy, Crop Physiology, Integrated Pest Management (IPM), Precision Agriculture, Biostatistics",
            "soft_skills": "Patience, Love for Nature and Farming, Scientific Rigor, Rural Empathy",
            "tools": "Soil Testing Kits, Spectrophotometer, GPS Yield Monitors, Experimental Farm Machinery",
            "certifications": "Agricultural Research Service (ARS) Examination (ASRB - ICAR)",
            "experience_level": "Scientist to Director General of ICAR",
            "career_growth": "Prestigious national scientific progression to Senior Scientist, Principal Scientist, or Vice-Chancellor of State Agricultural University.",
            "internship_roles": "Rural Agricultural Work Experience (RAWE - Integrated in B.Sc Agriculture)",
            "entry_level_roles": "Scientist (ARS - ICAR), Agricultural Research Officer, Agronomist",
            "average_salary": "₹7 - ₹16 LPA (Official 7th CPC Scientist Grade Pay Level 10 / ICAR Scales)",
            "salary_indicative": "Scientist (ARS Level 10): Basic ₹57,700 + DA + HRA = ~₹90,000/mo gross. Senior Scientist (Level 12): ₹79,800. Principal Scientist (Level 14): ₹1,44,200 basic. Corporate agritech roles range ₹6 - 22 LPA.",
            "future_scope": "Paramount national priority driven by climate change adaptation, organic farming, millet missions (Shree Anna), and AgriTech 4.0.",
            "government_opportunities": "Indian Council of Agricultural Research (ICAR - ARS Exam), State Agricultural Universities, NABARD (Grade A Officer).",
            "private_opportunities": "Bayer CropScience, Syngenta India, Corteva Agriscience, ITC Agri-Business, Godrej Agrovet, top seed enterprises.",
            "higher_study_options": "Ph.D. in Agronomy / Genetics & Plant Breeding (IARI New Delhi - Pusa Institute).",
            "entrepreneurship_options": "High-tech hydroponic vertical farm, bio-fertilizer manufacturing unit, agri-drone services enterprise.",
            "source": "Indian Council of Agricultural Research (ICAR) / ASRB",
            "official_url": "https://icar.org.in",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 7, "type": "DIRECT"}, {"course_id": 40, "type": "COMMON"}],
            "exams": [{"exam_id": 95, "importance": "PRIMARY"}, {"exam_id": 18, "importance": "ALTERNATIVE"}],
            "routes": [{"title": "Path A: ICAR AIEEA to Agricultural Research Service (ARS)", "type": "COMMON", "steps": "Class 12 (PCB/Agriculture) -> ICAR AIEEA-UG -> B.Sc (Hons) Agriculture (4 yrs) -> ICAR AIEEA-PG -> M.Sc Agriculture -> Clear ASRB ARS Examination -> Scientist (ICAR)."}],
            "ladder": [
                {"stage": "Scientist (ARS - ICAR)", "exp": "0-5 Years", "desc": "Conducts multi-location field crop trials, isolates drought-resistant seed lines, writes research papers."},
                {"stage": "Senior Scientist", "exp": "5-10 Years", "desc": "Directs national coordinated crop improvement projects (wheat, rice, pulses), releases certified varieties."},
                {"stage": "Principal Scientist / Head of Division", "exp": "10-18 Years", "desc": "Heads crop science division at national research institute, advises central ministry on MSP and crop policy."},
                {"stage": "Director / Vice-Chancellor / DG ICAR", "exp": "18+ Years", "desc": "Directs apex national agricultural research framework and international food security collaborations."}
            ],
            "roadmaps": {
                "Class 10": "Focus on plant biology, soils, and environmental science.",
                "Class 12": "Choose Science (PCB or Agriculture). Score high in Biology and Chemistry.",
                "Graduation": "Complete B.Sc (Hons) Agriculture from an ICAR-accredited university. Complete RAWE (Rural Agricultural Work Experience) village stay.",
                "Working Professional": "Clear ICAR PG entrance for master's at IARI New Delhi (Pusa), and prepare for the Agricultural Research Service (ARS) exam."
            }
        },
        {
            "title": "Food Safety Officer & Food Technologist",
            "short_name": "Food Safety Officer",
            "slug": "food-safety-officer",
            "category": "Agriculture, Food Technology & Environment",
            "sub_category": "Food Processing, Safety & Quality Assurance",
            "industry": "Food Processing & Safety Administration",
            "icon": "shield-check",
            "short_description": "Enforces national food hygiene standards, audits food processing factories, and ensures safe consumer food supply under FSSAI.",
            "description": "Food Safety Officers enforce the Food Safety and Standards Act, 2006 under the Food Safety and Standards Authority of India (FSSAI). They inspect commercial food establishments, collect samples for adulteration testing, and license food business operators (FBOs).",
            "what_they_do": "They inspect food manufacturing plants and restaurants, seize suspected adulterated food samples, send them to accredited public laboratories, prosecute food safety violators, and ensure adherence to national food standards.",
            "day_to_day_work": "• Inspecting food manufacturing plants, slaughterhouses, and commercial kitchens.\n• Collecting formal food samples adhering to legal chain-of-custody protocols.\n• Reviewing laboratory chemical and microbiological assay reports.\n• Issuing improvement notices, seizure orders, and filing criminal complaints.\n• Auditing food labels for nutritional accuracy and allergen declarations.",
            "work_environment": "State food safety commissionerates, food testing laboratories, food processing factories.",
            "work_modes": "On-site / Field Inspections / Lab",
            "minimum_qualification": "Undergraduate (B.Tech Food Tech / B.Sc Dairy Tech / Microbiology / Chemistry)",
            "preferred_streams": "Science (PCB / PCM)",
            "required_subjects": "Food Technology, Chemistry, Microbiology",
            "technical_skills": "Food Safety & Standards Act 2006, HACCP Principles, Food Adulteration Testing, Food Microbiology, Sensory Evaluation, FSSAI Licensing",
            "soft_skills": "Uncompromising Integrity, Regulatory Authority, Attention to Detail, Observation",
            "tools": "Food Sampling Kits, Refractometer, Moisture Analyzers, FoSCoS (FSSAI Portal)",
            "certifications": "FSSAI Food Safety Officer Examination, HACCP / ISO 22000 Lead Auditor",
            "experience_level": "Entry-Level to Senior",
            "career_growth": "Direct progression to Designated Officer (DO), State Food Safety Commissioner, or Corporate Quality Assurance Director.",
            "internship_roles": "Food Quality Testing Intern, Factory QA Trainee",
            "entry_level_roles": "Food Safety Officer (FSO), Quality Assurance Executive, Food Analyst",
            "average_salary": "₹4.5 - ₹12 LPA (Indicative range)",
            "salary_indicative": "Food Safety Officer (State PSC / FSSAI): Pay Level 7/8: Basic ₹44,900 - ₹47,600 + DA + HRA = ~₹75,000/mo gross. Corporate QA Managers in FMCG range ₹8 - 18 LPA.",
            "future_scope": "Surging national priority as consumer awareness of packaged food safety, adulteration, and organic certification explodes.",
            "government_opportunities": "FSSAI (Food Safety and Standards Authority of India), State Food Safety Departments via State PSCs.",
            "private_opportunities": "Nestlé, Amul, ITC Foods, Britannia, PepsiCo, Hindustan Unilever, accredited food testing labs.",
            "higher_study_options": "M.Tech in Food Technology (CFTRI Mysore, NIFTEM), M.Sc Food Microbiology.",
            "entrepreneurship_options": "NABL-accredited food testing laboratory, food safety compliance consultancy, artisanal food brand.",
            "source": "Food Safety and Standards Authority of India (FSSAI)",
            "official_url": "https://fssai.gov.in",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 6, "type": "COMMON"}, {"course_id": 3, "type": "COMMON"}],
            "exams": [{"exam_id": 38, "importance": "PRIMARY"}, {"exam_id": 39, "importance": "PRIMARY"}],
            "routes": [{"title": "Path A: Food Technology to FSSAI Officer", "type": "COMMON", "steps": "B.Tech Food Technology / B.Sc Chemistry/Microbiology -> Clear FSSAI / State PSC Food Safety Officer Exam -> Field Training -> Appointed as Food Safety Officer (FSO)."}],
            "ladder": [
                {"stage": "Food Safety Officer (FSO)", "exp": "0-5 Years", "desc": "Inspects food premises, collects legal samples, issues improvement notices."},
                {"stage": "Designated Officer (DO)", "exp": "5-10 Years", "desc": "Heads district food safety administration, sanctions prosecutions, issues food licenses."},
                {"stage": "Joint Commissioner / Director of Food Safety", "exp": "10-18 Years", "desc": "Coordinates statewide anti-adulteration drives, manages state public analyst laboratories."},
                {"stage": "Food Safety Commissioner", "exp": "18+ Years", "desc": "Apex regulatory authority governing food safety across an entire state or Union territory."}
            ],
            "roadmaps": {
                "Class 10": "Focus on Chemistry, Biology, and hygiene principles.",
                "Class 12": "Choose Science with Chemistry and Biology/Maths.",
                "Graduation": "Complete B.Tech in Food Technology or B.Sc in Chemistry/Microbiology from recognized universities (CFTRI, NIFTEM, State Agricultural Universities).",
                "Working Professional": "Prepare for the Central FSSAI or State PSC Food Safety Officer recruitment examinations."
            }
        }
    ]

def get_aviation_careers():
    return [
        {
            "title": "Commercial Airline Pilot",
            "short_name": "Commercial Pilot",
            "slug": "commercial-pilot",
            "category": "Aviation, Logistics & Supply Chain",
            "sub_category": "Flight Operations & Piloting",
            "industry": "Commercial Aviation & Airlines",
            "icon": "airplane",
            "short_description": "Commands commercial passenger and cargo aircraft, ensuring safe air navigation adhering to strict international aviation protocols.",
            "description": "Commercial Airline Pilots navigate multi-engine jet airliners transporting passengers and cargo safely across global air routes. They calculate flight routes, monitor automated flight management computers, manage weather deviations, and handle in-flight emergencies with calm precision.",
            "what_they_do": "They perform pre-flight aircraft walkaround inspections, review weather briefings and flight plans, take off and land heavy aircraft, communicate with Air Traffic Control (ATC), and command flight crews.",
            "day_to_day_work": "• Reviewing weather forecasts, NOTAMs, and fuel calculations in flight dispatch.\n• Conducting cockpit pre-flight checks and programming the Flight Management System (FMS).\n• Executing instrument takeoffs, climbs, cruise navigation, and precision landings.\n• Communicating with ATC radars and managing in-flight turbulence avoidance.\n• Debriefing flight performance and logging flight hours in the official DGCA logbook.",
            "work_environment": "Commercial airliner cockpits (A320, B737, B777, B787), international airports worldwide.",
            "work_modes": "Shift Duties / Irregular Flight Rosters / Domestic & International Layover Routes",
            "minimum_qualification": "Class 12 (Physics & Mathematics 50%+) + DGCA Commercial Pilot License (CPL)",
            "preferred_streams": "Science (PCM)",
            "required_subjects": "Physics, Mathematics",
            "technical_skills": "Instrument Flight Rules (IFR), Aircraft Systems, Aviation Meteorology, Air Navigation, Flight Management Systems (FMS), Multi-Crew Cooperation (MCC)",
            "soft_skills": "Supreme Situational Awareness, Calm Composure Under Pressure, Decisive Leadership, Quick Reflexes",
            "tools": "Glass Cockpit Avionics (Fly-by-Wire, PFD/ND), Full Flight Simulators (Level D), EFB (Electronic Flight Bag)",
            "certifications": "Commercial Pilot License (CPL) issued by DGCA India, Multi-Engine Instrument Rating (ME-IR), Type Rating (A320 / B737)",
            "experience_level": "First Officer to Airline Captain / Line Training Captain",
            "career_growth": "Highly prestigious career progressing from Junior First Officer to Senior First Officer, Captain (Commander), and Examiner.",
            "internship_roles": "Flight Training School Flying Hours (200 Flying Hours on Single & Multi-Engine Aircraft)",
            "entry_level_roles": "Junior First Officer, Second Officer",
            "average_salary": "₹15 - ₹40 LPA (Indicative range - highly compensated with flight duty allowances)",
            "salary_indicative": "First Officer (0-3 yrs): ₹14 - 24 LPA | Airline Captain / Commander (4-8 yrs): ₹35 - 65+ LPA | Senior Training Captain (8+ yrs): ₹70 - 1 Cr+ LPA. Indicative figures from DGCA & Indian Airline Schedules 2024.",
            "future_scope": "Explosive growth as Indian airlines (Air India, IndiGo, Akasa) have ordered over 1,500 new aircraft, creating the world's largest pilot demand.",
            "government_opportunities": "Indian Air Force (via AFCAT / CDS), Coast Guard Aviation, VIP Flight Squadrons.",
            "private_opportunities": "IndiGo, Air India, Vistara, Akasa Air, SpiceJet, global airlines (Emirates, Qatar Airways, Singapore Airlines).",
            "higher_study_options": "Airline Transport Pilot License (ATPL), Type Rating Instructor (TRI), Type Rating Examiner (TRE).",
            "entrepreneurship_options": "Private charter aviation service, flight training academy ownership.",
            "source": "Directorate General of Civil Aviation (DGCA India)",
            "official_url": "https://www.dgca.gov.in",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 2, "type": "COMMON"}, {"course_id": 1, "type": "COMMON"}],
            "exams": [{"exam_id": 24, "importance": "ALTERNATIVE"}, {"exam_id": 53, "importance": "ALTERNATIVE"}],
            "routes": [
                {"title": "Path A: Flying School Cadet Pilot Route", "type": "COMMON", "steps": "Class 12 (PCM) -> Clear DGCA Class 1 Medical -> Complete 200 hours flying at approved Flying Training Organisation (FTO / IGRUA) -> Clear DGCA CPL exams (Navigation, Meteorology, Air Regulations, Technical) -> Type Rating (A320/B737) -> Junior First Officer."},
                {"title": "Path B: Airline Cadet Pilot Program", "type": "COMMON", "steps": "Clear IndiGo / Air India Cadet Pilot Program entrance -> Structured training from zero to Type-Rated First Officer -> Direct airline induction."}
            ],
            "ladder": [
                {"stage": "Junior First Officer (Co-Pilot)", "exp": "0-2 Years", "desc": "Flies as second-in-command under Captain supervision, manages radio ATC and navigation."},
                {"stage": "Senior First Officer", "exp": "2-5 Years", "desc": "Accumulates 1,500+ hours, clears ATPL exams, handles complex weather approaches."},
                {"stage": "Airline Captain (Commander - 4 Stripes)", "exp": "5-10 Years", "desc": "Pilot-in-Command (PIC). Holds legal ultimate responsibility for aircraft, passengers, and flight safety."},
                {"stage": "Line Training Captain (LTC) / Examiner", "exp": "10+ Years", "desc": "Trains new airline pilots in Full Flight Simulators, conducts regulatory DGCA check-rides."}
            ],
            "roadmaps": {
                "Class 10": "Ensure excellent eyesight (correctable to 6/6) and build passion for aircraft.",
                "Class 12": "Score at least 50% in Physics and Mathematics (mandatory requirement under DGCA Civil Aviation Requirements).",
                "Graduation": "Complete DGCA Class 2 and Class 1 Medical examinations. Enroll in a flying academy (IGRUA Rae Bareli or premier international flight academy) for 200 flying hours.",
                "Working Professional": "Pass DGCA theory examinations, complete Multi-Engine Rating and A320/B737 Type Rating, and clear airline simulator evaluations."
            }
        }
    ]

def get_social_science_careers():
    return [
        {
            "title": "Public Policy Analyst",
            "short_name": "Policy Analyst",
            "slug": "public-policy-analyst",
            "category": "Social Sciences, Psychology & Public Policy",
            "sub_category": "Public Governance & Socioeconomic Policy",
            "industry": "Government & Policy Advisory",
            "icon": "graph-up-arrow",
            "short_description": "Evaluates public programs, analyzes socioeconomic data, and formulates evidence-based policies to solve complex societal challenges.",
            "description": "Public Policy Analysts examine government programs and societal challenges (poverty alleviation, healthcare access, education equity, urban infrastructure). They use econometric tools and qualitative field research to design actionable policy solutions.",
            "what_they_do": "They analyze large-scale government survey datasets (NSSO, NFHS, PLFS), conduct randomized control trials (RCTs), draft policy cabinet notes, evaluate welfare budget efficiency, and publish policy impact assessments.",
            "day_to_day_work": "• Analyzing socio-economic survey microdata using Stata, R, or Python.\n• Designing randomized evaluations and qualitative focus group interviews.\n• Evaluating policy trade-offs and drafting legislative policy briefs.\n• Meeting government bureaucrats and multilateral donors (World Bank, ADB).\n• Authoring research papers on governance, climate adaptation, and fiscal policy.",
            "work_environment": "Government policy units (NITI Aayog), think tanks, international development banks, university institutes.",
            "work_modes": "Hybrid / Office / Field Survey Visits",
            "minimum_qualification": "Postgraduate (Master's in Public Policy - MPP / Economics)",
            "preferred_streams": "Humanities / Economics / Any Stream",
            "required_subjects": "Economics, Political Science, Statistics",
            "technical_skills": "Econometrics, Stata/R, Policy Impact Evaluation, Randomized Control Trials (RCT), Cost-Benefit Analysis, Qualitative Field Research",
            "soft_skills": "Systemic Thinking, Intellectual Rigor, Communication, Empathy for Citizens",
            "tools": "Stata, R, Python, GIS Mapping, Excel (Advanced), SurveyCTO",
            "certifications": "Master in Public Policy (MPP) from NLSIU, IIM Bangalore, or global policy schools",
            "experience_level": "Entry-Level to Senior Policy Director",
            "career_growth": "High-impact trajectory progressing to Senior Policy Fellow, Country Director, or Government Chief Policy Advisor.",
            "internship_roles": "Policy Intern, Young Professional Trainee, Economic Research Intern",
            "entry_level_roles": "Research Associate, Junior Policy Analyst, Consultant (NITI Aayog)",
            "average_salary": "₹6 - ₹16 LPA (Indicative range)",
            "salary_indicative": "Entry-Level Associate (0-2 yrs): ₹5.5 - 8.5 LPA | Senior Policy Specialist (3-6 yrs): ₹10 - 20 LPA | Country Policy Lead / Director (7+ yrs): ₹24 - 55+ LPA. Indicative figures from NITI Aayog & Development Sector Audits 2024.",
            "future_scope": "Surging national demand as governments prioritize data-driven governance, outcome budgeting, and climate resilience.",
            "government_opportunities": "NITI Aayog Young Professionals / Consultants, Ministry of Finance, State Planning Commissions.",
            "private_opportunities": "J-PAL (Abdul Latif Jameel Poverty Action Lab), World Bank, Asian Development Bank (ADB), Dalberg, IDinsight, BCG Public Sector.",
            "higher_study_options": "Ph.D. in Public Policy / Economics, Harvard Kennedy School / LSE MPP.",
            "entrepreneurship_options": "Social impact advisory firm, development data analytics enterprise.",
            "source": "NITI Aayog / National Law School (NLSIU MPP)",
            "official_url": "https://www.niti.gov.in",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 20, "type": "DIRECT"}, {"course_id": 24, "type": "DIRECT"}, {"course_id": 22, "type": "COMMON"}],
            "exams": [{"exam_id": 41, "importance": "PRIMARY"}, {"exam_id": 1, "importance": "ALTERNATIVE"}],
            "routes": [{"title": "Path A: Economics / Humanities to Master in Public Policy (MPP)", "type": "COMMON", "steps": "B.A. Economics / Pol Science -> Master in Public Policy (NLSIU Bengaluru / IIM Bangalore / St. Stephen's) -> J-PAL / NITI Aayog Policy Analyst."}],
            "ladder": [
                {"stage": "Policy Research Associate", "exp": "0-2 Years", "desc": "Cleans survey datasets, conducts econometric regressions, manages field enumerator teams."},
                {"stage": "Policy Analyst / Consultant", "exp": "2-5 Years", "desc": "Designs policy pilot programs, drafts government cabinet notes, presents to secretaries."},
                {"stage": "Senior Policy Lead", "exp": "5-8 Years", "desc": "Heads national thematic vertical (health, education, energy), advises Chief Ministers."},
                {"stage": "Country Director / Senior Economic Advisor", "exp": "8+ Years", "desc": "Directs multi-million dollar social impact portfolios for international development banks."}
            ],
            "roadmaps": {
                "Class 10": "Read newspapers regularly and understand national social and economic challenges.",
                "Class 12": "Choose Humanities or Commerce with Economics and Mathematics.",
                "Graduation": "Complete B.A. in Economics or Political Science with strong econometric foundation.",
                "Working Professional": "Pursue an MPP (Master in Public Policy) from NLSIU Bengaluru or top global public policy schools."
            }
        }
    ]

print("Catalog builder part 6 ready.")
