"""
scripts/catalog_expanded_part9.py
Comprehensive Domain Expansion: Media, Design, Fine Arts, Performing Arts, Film, Sports, Hospitality
"""

def get_media_and_creative_careers():
    return [
        {
            "title": "Television Broadcast News Anchor",
            "short_name": "News Anchor",
            "slug": "broadcast-news-anchor",
            "category": "Media, Journalism & Digital Marketing",
            "sub_category": "Broadcast Journalism & Television",
            "industry": "Television News, Digital Media & Broadcasting",
            "icon": "tv",
            "short_description": "Presents prime-time news broadcasts, moderates high-stakes debates, and conducts live investigative interviews.",
            "description": "Broadcast News Anchors are the primary faces and voices of television news channels and digital broadcast networks. They present live breaking news, moderate heated political and current affairs debates, interview heads of state and ministers, and verify breaking news reports in real time with field correspondents and teleprompters.",
            "what_they_do": "They analyze daily news wires, write broadcast lead-ins, conduct live studio debate shows, interview newsmakers, and anchor live continuous coverage during national elections and crises.",
            "day_to_day_work": "• Reviewing news agency wire feeds (PTI, ANI, Reuters) and editorial rundowns.\n• Writing and editing broadcast scripts for the prime-time news bulletin.\n• Reading from studio teleprompters while listening to producer ear-prompters (IFB).\n• Moderating multi-guest panel debates on constitutional, political, and economic topics.\n• Handling unscripted breaking news developments live on air without panic.",
            "work_environment": "Television broadcast studios, control rooms, outdoor live broadcast sets.",
            "work_modes": "On-site / Studio / Live Set",
            "minimum_qualification": "Undergraduate (BJMC - Bachelor of Journalism & Mass Communication - 3 Years / B.A. Mass Media)",
            "preferred_streams": "Arts / Humanities / Any Stream with exceptional communication",
            "required_subjects": "Journalism, Media Law & Ethics, Political Science, English/Hindi",
            "technical_skills": "Teleprompter Reading, Live Broadcast Moderation, Voice Modulation, Breaking News Ad-Libbing, Media Law (Defamation/Contempt), PCR Studio Coordination",
            "soft_skills": "Composure Under Live Pressure, Authoritative Presence, Active Listening, Impartial Moderation",
            "tools": "Teleprompters, In-Ear Monitors (IFB), Studio Lighting, ENPS Newsroom Software, Microphones",
            "certifications": "Broadcast Editors' Association (BEA) Ethics, Press Club Accreditation",
            "experience_level": "Reporter to Senior Executive Editor & Anchor",
            "career_growth": "Advance to Senior Anchor, Special Correspondent, Managing Editor, or Editorial Director.",
            "internship_roles": "Newsroom Editorial Intern, Broadcast Production Trainee",
            "entry_level_roles": "Junior Reporter, Desk Sub-Editor, Associate Producer",
            "average_salary": "₹5.0 - ₹20.0+ LPA (Indicative range)",
            "salary_indicative": "Junior Newsroom Desk / Reporter: ₹4.5 - 7 LPA | Mid-Level Anchor (3-6 yrs): ₹8 - 16 LPA | Prime-Time Headline Anchor / Executive Editor: ₹20 - 50+ LPA. Indicative figures from national television news networks.",
            "future_scope": "Growing rapidly through 24x7 television news channels, OTT live news streaming, and digital YouTube/podcast news networks.",
            "government_opportunities": "Sansad TV (Lok Sabha / Rajya Sabha TV), Doordarshan News (DD News Senior Anchors), All India Radio (AIR).",
            "private_opportunities": "NDTV, India Today / Aaj Tak, Times Network, CNN-News18, ABP Network, Republic Media, BBC India.",
            "higher_study_options": "Master of Journalism & Mass Communication (MJMC), Master in International Broadcast Journalism.",
            "entrepreneurship_options": "Founding an independent digital video news network, investigative journalism channel, or podcast media company.",
            "source": "News Broadcasters & Digital Association (NBDA) / IIMC",
            "official_url": "https://www.iimc.gov.in",
            "verification_status": "VERIFIED",
            "is_lesser_known": False,
            "career_family": "Media & Storytelling",
            "interest_clusters": "Media, Language, Communication, Government, Society",
            "work_style": "Studio, Office",
            "reality_check": "Not just reading a script: Requires deep knowledge of national politics, the Indian Constitution, and world affairs to challenge panel guests.\nHigh stress: Operating live under intense camera lights where any slip of the tongue is broadcast instantly to millions.\nRequires starting as a ground field reporter or desk writer before earning a prime-time anchor chair.",
            "next_steps": "Earn a Bachelor's degree in Journalism (BJMC) or English/Political Science.\nPractice voice modulation, clear pronunciation, and reading news copy aloud.\nApply for the 1-year PG Diploma in Radio & TV Journalism at the Indian Institute of Mass Communication (IIMC) or AJK MCRC Jamia.",
            "courses": [{"course_id": 57, "type": "PRIMARY"}],
            "exams": [],
            "routes": [{"title": "Path A: Journalism Degree to News Anchor", "type": "PRIMARY", "steps": "12th (Any Stream) -> BJMC / IIMC Entrance -> Field Reporter -> Bulletins Anchor -> Prime-Time News Anchor."}],
            "ladder": [
                {"stage": "Trainee Reporter / Desk Writer", "exp": "0-2 Years", "desc": "Covers beat reports, writes teleprompter copy, coordinates field live inputs from PCR."},
                {"stage": "Bulletin Anchor / Special Correspondent", "exp": "2-6 Years", "desc": "Anchors daytime news bulletins, conducts field investigative reports, interviews leaders."},
                {"stage": "Prime-Time Anchor & Managing Editor", "exp": "6+ Years", "desc": "Hosts flagship 9 PM debate shows, shapes editorial channel stance, commands national viewership."}
            ]
        },
        {
            "title": "Textile & Print Pattern Designer",
            "short_name": "Textile Designer",
            "slug": "textile-print-designer",
            "category": "Design, Animation & Creative Arts",
            "sub_category": "Fashion & Textile Design",
            "industry": "Handlooms, Textile Mills, Apparel Brands & Home Furnishings",
            "icon": "palette",
            "short_description": "Develops woven fabric structures, handblock prints, digital patterns, and jacquard weaves.",
            "description": "Textile and Print Pattern Designers create the structural weave, knit patterns, and surface ornamentation for fabrics used in apparel, home furnishings, and luxury interior upholstery. Combining traditional Indian heritage weaves (Chanderi, Ikat, Banarasi, Kalamkari) with modern digital jacquard looms and CAD print design, they work with artisanal handloom clusters and industrial textile mills.",
            "what_they_do": "They design repeat print patterns in Adobe Illustrator, develop warp/weft weave specifications for jacquard and dobby looms, formulate natural dye recipes, and collaborate with rural craft clusters.",
            "day_to_day_work": "• Sketching botanical and geometric motifs and creating seamless pattern repeats in CAD.\n• Setting up weave structures (twill, satin, jacquard) using textile design software.\n• Working with artisanal handloom weavers in craft clusters on loom thread counts and yarn twists.\n• Formulating eco-friendly chemical and natural botanical dye recipes in dye laboratories.\n• Presenting seasonal textile swatch collections to apparel brands and home export houses.",
            "work_environment": "Textile mills, apparel design studios, craft weaver clusters, export houses.",
            "work_modes": "Studio / Workshop / Cluster",
            "minimum_qualification": "Undergraduate (Bachelor of Design - B.Des in Textile Design - 4 Years from NID / NIFT)",
            "preferred_streams": "Any Stream",
            "required_subjects": "Textile Science, Weaving, Print Design, Surface Ornamentation",
            "technical_skills": "Weave Structure Design, Repeat Pattern Creation, Jacquard CAD (NedGraphics), Natural Dyeing Chemistry, Handloom Cluster Collaboration, Fabric Testing",
            "soft_skills": "Deep Color Sensitivity, Tactile Texture Appreciation, Respect for Heritage Crafts, Creativity",
            "tools": "NedGraphics, Adobe Illustrator, Handlooms, Screen-Printing Tables, Spectrophotometers",
            "certifications": "B.Des in Textile Design from NIFT / NID",
            "experience_level": "Entry to Design Director",
            "career_growth": "Advance to Senior Textile Stylist, Head of Textile Design, or Creative Director of Home Fashion Brand.",
            "internship_roles": "Handloom Cluster Intern, Textile Mill Design Trainee",
            "entry_level_roles": "Junior Textile Designer, Print Stylist, Weaver Coordinator",
            "average_salary": "₹4.5 - ₹12.5 LPA (Indicative range)",
            "salary_indicative": "Junior Textile Designer post-NIFT: ₹4.5 - 6.5 LPA | Senior Print Designer in Export/Retail (3-6 yrs): ₹7.5 - 12 LPA | Design Director / Handloom Brand Founder: ₹14 - 28+ LPA. Indicative figures from NIFT placement reports.",
            "future_scope": "Growing rapidly as global sustainable fashion embraces natural Indian handlooms, organic khadi, and botanical dye textiles.",
            "government_opportunities": "Weavers' Service Centres (Office of the Development Commissioner for Handlooms), Central Silk Board, National Jute Board.",
            "private_opportunities": "Fabindia, Good Earth, Arvind Limited, Welspun India, Raymond, Jaypore, Sabyasachi Textiles, Masaba.",
            "higher_study_options": "Master of Design (M.Des in Textile Design), International Sustainable Textile Fellowships.",
            "entrepreneurship_options": "Founding an independent sustainable handloom textile label or home furnishing studio.",
            "source": "Development Commissioner for Handlooms (Ministry of Textiles) / NIFT",
            "official_url": "https://handlooms.nic.in",
            "verification_status": "VERIFIED",
            "is_lesser_known": False,
            "career_family": "Design & Aesthetics",
            "interest_clusters": "Design, Art, Creativity, Culture, Hands-on",
            "work_style": "Studio, Workshop, Outdoor",
            "reality_check": "Combines artistic motif sketching with rigorous technical yarn counts, warp densities, and dye chemistry.\nInvolves traveling to remote rural weaving villages (Maheshwar, Kanchipuram, Sambalpur) to work with traditional craftspeople.\nHigh tactile sensitivity: must be able to recognize fabric blends and thread finishes by touch.",
            "next_steps": "Practice drawing repeating patterns, understanding color wheel harmonies, and observing traditional textiles.\nAppear for the NIFT / NID Entrance Examination for B.Des in Textile Design.\nComplete the 4-year design program including mandatory rural craft cluster documentation.",
            "courses": [{"course_id": 30, "type": "PRIMARY"}],
            "exams": [],
            "routes": [{"title": "Path A: NIFT / NID Textile Route", "type": "PRIMARY", "steps": "12th (Any Stream) -> NIFT/NID Entrance -> B.Des Textile Design (4 yrs) -> Craft Cluster Residency -> Textile Designer."}],
            "ladder": [
                {"stage": "Junior Textile Designer", "exp": "0-2 Years", "desc": "Develops print repeats on CAD, prepares colorway separations, coordinates yarn dyeing samples."},
                {"stage": "Senior Textile / Print Designer", "exp": "2-6 Years", "desc": "Designs seasonal fabric collections for major fashion houses, oversees weaving production in mills."},
                {"stage": "Design Director / Brand Founder", "exp": "6+ Years", "desc": "Heads textile creative direction, showcases Indian handlooms globally, revitalizes endangered weaving crafts."}
            ]
        },
        {
            "title": "Interior Architect & Designer",
            "short_name": "Interior Designer",
            "slug": "interior-architect-designer",
            "category": "Architecture & Built Environment",
            "sub_category": "Interior Architecture & Spatial Design",
            "industry": "Interior Architecture, Luxury Residences & Commercial Spaces",
            "icon": "house-gear",
            "short_description": "Designs indoor built environments, luxury home interiors, corporate offices, and hospitality spaces.",
            "description": "Interior Architects and Designers transform bare building shells into functional, safe, aesthetically refined indoor living and working environments. They master spatial planning, ergonomic furniture layouts, architectural lighting design, acoustic treatment, HVAC air ducts, and curated material finishes for luxury residences, corporate offices, restaurants, and retail boutiques.",
            "what_they_do": "They draft space layouts and electrical/plumbing drawings in AutoCAD, build photorealistic 3D interior renders (3ds Max, SketchUp), select marble, wood, and fabrics, and supervise carpentry and MEP contractors on site.",
            "day_to_day_work": "• Meeting clients to understand living lifestyles, spatial storage needs, and aesthetic design tastes.\n• Drafting detailed 2D furniture layouts, ceiling lighting plans, and electrical schematics.\n• Developing photorealistic 3D walkthrough renderings using SketchUp, V-Ray, and 3ds Max.\n• Curating material sample moodboards (Italian marble, veneers, brass hardware, bespoke fabrics).\n• Visiting project sites to supervise civil masonry, false ceiling carpentry, and paint finishes.",
            "work_environment": "Interior design studios, ongoing construction and renovation interior sites, client offices.",
            "work_modes": "Studio / Site / Hybrid",
            "minimum_qualification": "Undergraduate (Bachelor of Interior Design - B.Des / B.Int.Arch - 4 Years from CEPT / NID / Accredited Colleges)",
            "preferred_streams": "Any Stream",
            "required_subjects": "Spatial Design, Drawing, Building Materials, Furniture Design",
            "technical_skills": "Space Planning, Architectural Drafting (AutoCAD), 3D Visualization (SketchUp/V-Ray), Interior Construction Detailing, Lighting Design, Millwork & Carpentry Joinery, MEP Coordination",
            "soft_skills": "Spatial Aesthetics, Client Relationship Diplomacy, Multi-Vendor Site Coordination, Eye for Detail",
            "tools": "AutoCAD, SketchUp, 3ds Max, V-Ray / Enscape, Photoshop, Material Swatch Boards",
            "certifications": "Institute of Indian Interior Designers (IIID) Professional Membership",
            "experience_level": "Junior Designer to Principal Interior Architect",
            "career_growth": "Advance to Senior Project Designer, Design Partner, or Principal of Independent Interior Architecture Studio.",
            "internship_roles": "Interior Design Studio Intern, Site Execution Trainee",
            "entry_level_roles": "Junior Interior Designer, 3D Visualizer, Site Execution Assistant",
            "average_salary": "₹4.5 - ₹15.0+ LPA (Indicative range)",
            "salary_indicative": "Junior Interior Designer: ₹4.0 - 6.5 LPA | Senior Project Designer (3-6 yrs): ₹8 - 14 LPA | Principal of Studio / High-End Residential Designer: ₹18 - 45+ LPA. Indicative figures from IIID industry surveys.",
            "future_scope": "Explosive multi-billion dollar growth fueled by the Indian real estate boom, luxury high-rise apartments, and experiential cafe/retail culture.",
            "government_opportunities": "CPWD Interior Wings, NBCC, Indian Railways Modern Station Redevelopment Interiors.",
            "private_opportunities": "Morphogenesis, Studio Lotus, Livspace, HomeLane, Gauri Khan Designs, Space Matrix, Gensler India, Top Luxury Developers.",
            "higher_study_options": "Master of Interior Design (M.Des), International Interior Architecture Master's (Politecnico di Milano, Pratt).",
            "entrepreneurship_options": "Founding an independent boutique interior architecture studio or bespoke furniture design brand.",
            "source": "Institute of Indian Interior Designers (IIID)",
            "official_url": "https://iiid.in",
            "verification_status": "VERIFIED",
            "is_lesser_known": False,
            "career_family": "Design & Aesthetics",
            "interest_clusters": "Design, Architecture, Art, Hands-on, Creativity",
            "work_style": "Studio, Construction Site, Office",
            "reality_check": "Not just picking cushions and paint colors: Demands technical understanding of civil partition walls, electrical conduits, plumbing traps, and false ceilings.\nInvolves managing dusty, noisy renovation sites and coordinating temperamental carpentry and electrical contractors.\nMust deliver projects on strict client move-in deadlines while managing multi-lakh budgets.",
            "next_steps": "Practice spatial sketching, understanding floor plan dimensions, and studying lighting.\nAppear for UCEED, NID DAT, or university entrances for 4-year B.Des in Interior Design (e.g. CEPT University Ahmedabad).\nBuild an execution portfolio showcasing space planning, detailed joinery drawings, and photorealistic 3D renders.",
            "courses": [{"course_id": 30, "type": "PRIMARY"}, {"course_id": 2, "type": "RELATED"}],
            "exams": [],
            "routes": [{"title": "Path A: Interior Design Route", "type": "PRIMARY", "steps": "12th (Any Stream) -> B.Des Interior Design (4 yrs) -> Studio Internship -> Project Interior Designer -> Principal Studio Owner."}],
            "ladder": [
                {"stage": "Junior Interior Designer / Draftsman", "exp": "0-2 Years", "desc": "Drafts AutoCAD electrical layouts, creates 3D renders, compiles vendor material quotes."},
                {"stage": "Project Interior Designer", "exp": "2-6 Years", "desc": "Leads client design presentations, selects luxury finishes, directs on-site carpentry and MEP execution."},
                {"stage": "Principal Interior Architect / Studio Founder", "exp": "6+ Years", "desc": "Heads high-end design firm, designs marquee luxury residences, featured in Architectural Digest India."}
            ]
        }
    ]

def get_fine_arts_and_performance_careers():
    return [
        {
            "title": "Fine Art Painter & Gallery Exhibitor",
            "short_name": "Fine Artist",
            "slug": "fine-art-painter",
            "category": "Design, Animation & Creative Arts",
            "sub_category": "Fine Arts & Painting",
            "industry": "Fine Arts, Art Galleries & Contemporary Visual Arts",
            "icon": "brush-fill",
            "short_description": "Creates original oil, acrylic, watercolor, and mixed-media paintings for gallery exhibitions and collectors.",
            "description": "Fine Art Painters are creative visual artists who explore philosophy, human emotion, social commentary, and abstract aesthetics through the medium of paint on canvas and paper. Holding a Bachelor of Fine Arts (BFA), they develop a distinct artistic vision and body of work, exhibit in prestigious galleries, participate in art biennials, and sell works to institutional and private art collectors.",
            "what_they_do": "They formulate conceptual artistic themes, prepare canvases with gesso, experiment with pigment textures, oils, and acrylics, write artist statements, collaborate with gallery curators, and showcase in solo and group art exhibitions.",
            "day_to_day_work": "• Spending daily dedicated studio hours sketching and developing new painting series.\n• Mixing oil paints, linseed mediums, and pigments to achieve desired luminescence.\n• Applying impasto textures, glazes, and color washes across large-format canvases.\n• Writing reflective artist statements explaining the philosophical concept of the artwork.\n• Meeting art gallery owners, curators, and collectors during exhibition preview openings.",
            "work_environment": "Private artist studios, art galleries, creative artist residencies, art fairs.",
            "work_modes": "Studio / Independent / Gallery",
            "minimum_qualification": "Undergraduate (Bachelor of Fine Arts - BFA in Painting - 4 Years from JJ School of Art / Shantiniketan / MSU Baroda)",
            "preferred_streams": "Any Stream (Passion for visual arts, drawing, and color expression)",
            "required_subjects": "Painting, Drawing, Art History, Aesthetics",
            "technical_skills": "Oil & Acrylic Painting Techniques, Color Theory & Harmony, Anatomical & Abstract Drawing, Compositional Balance, Canvas Stretching & Priming, Exhibition Preparation",
            "soft_skills": "Authentic Creative Vision, Intellectual Depth, Emotional Sensitivity, Resilience to Solitude",
            "tools": "Oil & Acrylic Paints, Palette Knives, Canvas Stretchers, Kolinsky Brushes, Easels, Fixatives",
            "certifications": "Lalit Kala Akademi National Award / Fellowship, BFA / MFA Degree",
            "experience_level": "Emerging Artist to Master Visual Artist",
            "career_growth": "Advance from Emerging Artist to Gallery-Represented Artist, Biennial Participant, and Established Contemporary Master.",
            "internship_roles": "Artist Assistant, Printmaking / Gallery Studio Apprentice",
            "entry_level_roles": "Practicing Artist, Art Studio Instructor, Gallery Assistant",
            "average_salary": "₹3.5 - ₹20.0+ LPA (Artwork Sale & Commission Model)",
            "salary_indicative": "Emerging Artist: ₹3.5 - 6.0 LPA through group shows and commissions | Mid-Career Gallery Artist: ₹8 - 18 LPA | Established Contemporary Artist: ₹20 - 50+ LPA (Major canvas works auctioning for ₹5 Lakhs to ₹50+ Lakhs). Indicative figures from Indian contemporary art auction houses.",
            "future_scope": "Growing global demand for Indian modern and contemporary art at international art fairs (India Art Fair, Kochi-Muziris Biennale, Venice Biennale).",
            "government_opportunities": "Lalit Kala Akademi, National Gallery of Modern Art (NGMA), Faculty in Government Fine Art Colleges.",
            "private_opportunities": "Prominent Art Galleries (Vadehra Art Gallery, Chemould Prescott Road, Nature Morte, Gallery Espace, Jhaveri Contemporary), Saffronart.",
            "higher_study_options": "Master of Fine Arts (MFA in Painting at MSU Baroda / Kala Bhavana Visva-Bharati Shantiniketan / Sir JJ School of Art).",
            "entrepreneurship_options": "Operating an independent art studio, selling limited edition fine art prints, or offering specialized fine art masterclasses.",
            "source": "Lalit Kala Akademi / Ministry of Culture",
            "official_url": "https://lalitkala.gov.in",
            "verification_status": "VERIFIED",
            "is_lesser_known": False,
            "career_family": "Design & Aesthetics",
            "interest_clusters": "Art, Creativity, Culture, Hands-on",
            "work_style": "Studio, Gallery",
            "reality_check": "Not a commercial 9-to-5 job with guaranteed monthly salary: income depends on artwork sales, gallery representation, and grants.\nRequires deep solitary discipline: spending weeks alone in the studio creating without external direction.\nSuccess requires building a unique, recognizable visual language that speaks authentically to viewers.",
            "next_steps": "Practice daily life drawing, still-life painting, and color composition in your sketchbook.\nApply for the Bachelor of Fine Arts (BFA Painting) entrance exams at premier art colleges (Sir JJ School of Art Mumbai, Faculty of Fine Arts MSU Baroda, Shantiniketan).\nComplete the 4-year BFA program and exhibit your work in graduation art shows and national youth exhibitions.",
            "courses": [{"course_id": 58, "type": "PRIMARY"}],
            "exams": [],
            "routes": [{"title": "Path A: BFA to Contemporary Artist", "type": "PRIMARY", "steps": "12th (Any Stream) -> BFA Painting (4 yrs) -> MFA (2 yrs) -> Solo Gallery Exhibition -> Gallery Representation -> Contemporary Master."}],
            "ladder": [
                {"stage": "Emerging Artist", "exp": "0-4 Years", "desc": "Participates in group exhibitions, applies for artist residencies, develops a cohesive visual voice."},
                {"stage": "Gallery-Represented Artist", "exp": "4-10 Years", "desc": "Holds solo exhibitions in major metros, sells works to private collectors, showcases at India Art Fair."},
                {"stage": "Established Contemporary Master", "exp": "10+ Years", "desc": "Exhibits in international biennials, works featured in major museum retrospectives and international auctions."}
            ]
        },
        {
            "title": "Feature Film Director",
            "short_name": "Film Director",
            "slug": "feature-film-director",
            "category": "Design, Animation & Creative Arts",
            "sub_category": "Film & Direction",
            "industry": "Cinema, Feature Films & OTT Series",
            "icon": "camera-reels-fill",
            "short_description": "Translates screenplays into cinematic reality, directs actors, and commands visual and auditory storytelling.",
            "description": "Film Directors are the primary artistic visionaries who control the artistic and dramatic aspects of a motion picture. Working from script development through principal photography to final sound mix, they guide actors' dramatic performances, collaborate with cinematographers on visual framing, work with production designers on sets, and direct editors in post-production.",
            "what_they_do": "They break down scripts into emotional beats, block actor staging on set, call 'Action' and 'Cut', select takes during filming, direct background music score composition, and make the ultimate creative decisions for the film.",
            "day_to_day_work": "• Conducting dramatic rehearsal sessions with lead actors to explore character subtext.\n• Collaborating with the Cinematographer and Production Designer on set framing and visual look.\n• Calling shots and directing dozens of cast and crew members on active film sets.\n• Reviewing daily camera rushes and editing rough cuts in the editing suite.\n• Working with sound designers and music composers on final theatrical surround-sound mixes.",
            "work_environment": "Film sets, soundstages, remote outdoor film locations, editing suites.",
            "work_modes": "On-site / Film Set / Location / Studio",
            "minimum_qualification": "Any Educational Background + Professional Diploma in Film Direction (FTII / SRFTI / Whistling Woods) or Industry Apprenticeship",
            "preferred_streams": "Any Stream (Storytelling passion, visual instinct, and leadership matter most)",
            "required_subjects": "Film Direction, Screenwriting, Film History, Dramatic Arts",
            "technical_skills": "Dramatic Actor Direction, Mise-en-Scène, Camera Blocking & Staging, Screenplay Analysis, Film Rhythm & Pacing, Audio-Visual Synchronization",
            "soft_skills": "Commanding Creative Leadership, Emotional Empathy, Relentless Vision, Decisiveness Under Chaos",
            "tools": "Director's Viewfinders, Script Breakdown Sheets, Monitor Video Village, Editing Suites",
            "certifications": "Indian Film and Television Directors' Association (IFTDA) Membership, FTII / SRFTI Alumni",
            "experience_level": "Assistant Director to Feature Film Director",
            "career_growth": "Advance from 3rd/2nd Assistant Director to Chief Associate Director, Debut Director, and Renowned Auteur / Producer.",
            "internship_roles": "Assistant Director (AD) Intern, Production Trainee",
            "entry_level_roles": "3rd Assistant Director, 2nd AD, Script Continuity Supervisor",
            "average_salary": "₹6.0 - ₹35.0+ LPA (Director Project Fee Model)",
            "salary_indicative": "Chief Associate Director: ₹6.0 - 12 LPA | Debut Independent Feature Director: ₹12 - 25 LPA per project | Established Commercial / OTT Director: ₹35 - 1.5+ Crore per film/series. Indicative figures from Indian film industry contracts.",
            "future_scope": "Booming demand across multi-language regional cinema (Hindi, Tamil, Telugu, Malayalam, Kannada, Bengali) and global OTT streaming networks.",
            "government_opportunities": "National Film Development Corporation (NFDC co-productions), Films Division of India, Doordarshan.",
            "private_opportunities": "Leading Film Studios (Yash Raj Films, Dharma Productions, Excel Entertainment, Mythri Movie Makers, Hombale Films), Netflix, Amazon Prime.",
            "higher_study_options": "Post-Graduate Diploma in Film Direction (FTII Pune / SRFTI Kolkata), International Film Schools (USC, AFI).",
            "entrepreneurship_options": "Founding an independent film production house, creative boutique studio, or ad-film agency.",
            "source": "Film and Television Institute of India (FTII) / IFTDA",
            "official_url": "https://www.ftii.ac.in",
            "verification_status": "VERIFIED",
            "is_lesser_known": False,
            "career_family": "Media & Storytelling",
            "interest_clusters": "Media, Creativity, Leadership, Art, People",
            "work_style": "Studio, Outdoor, Travel",
            "reality_check": "Ultimate creative captain: When a film succeeds, everyone takes credit; when a film flops, the director takes the full blame.\nInvolves grueling physical demands: Directing hundreds of crew members through 14-hour shoot days in extreme conditions.\nRequires starting as an Assistant Director (managing crowd continuity, call sheets) for years to learn the practical craft of filmmaking.",
            "next_steps": "Write and direct low-budget short films with your smartphone or DSLR to understand pacing and actor direction.\nApply for the 3-year Direction Diploma at FTII Pune or SRFTI Kolkata via the Joint Entrance Test (JET).\nWork as an Assistant Director (AD) under established feature film directors to learn professional set discipline.",
            "courses": [{"course_id": 57, "type": "PRIMARY"}],
            "exams": [],
            "routes": [{"title": "Path A: FTII Direction Route", "type": "PRIMARY", "steps": "Any Degree -> FTII JET Entrance -> 3-Yr Direction Diploma -> Assistant Director on Feature Films -> Debut Feature Director."}],
            "ladder": [
                {"stage": "Assistant Director (AD)", "exp": "0-4 Years", "desc": "Manages set continuity, coordinates actor call sheets, handles background artist crowd direction."},
                {"stage": "Associate Director / 1st AD", "exp": "4-8 Years", "desc": "Runs the daily film shoot schedule, executes action second-unit sequences, works intimately with the Director."},
                {"stage": "Feature Film Director / Auteur", "exp": "8+ Years", "desc": "Commands complete creative authority of theatrical feature films and high-budget OTT flagship series."}
            ]
        }
    ]
