"""
scripts/catalog_builder_part7.py
Remaining sectors to reach 126 authentic careers:
Design, Business, Science, Education, Media, Agriculture, Aviation, Social Sciences.
"""

def get_final_batch():
    return [
        # =====================================================================
        # DESIGN, ANIMATION & CREATIVE ARTS
        # =====================================================================
        {
            "title": "Graphic Designer & Visual Artist",
            "short_name": "Graphic Designer",
            "slug": "graphic-designer",
            "category": "Design, Animation & Creative Arts",
            "sub_category": "Graphic & Communication Design",
            "industry": "Design, Advertising & Creative Studios",
            "icon": "palette2",
            "short_description": "Creates visual concepts, brand identities, typography systems, and marketing assets for digital and print media.",
            "description": "Graphic Designers communicate ideas visually. They craft corporate brand identities, logos, marketing campaigns, packaging designs, publication layouts, and digital illustrations.",
            "what_they_do": "They conceptualize visual campaigns, design logos and brand style guides, lay out marketing assets, master typography and color palettes, and collaborate with copywriters and art directors.",
            "day_to_day_work": "• Designing brand collateral, marketing banners, and social assets in Photoshop and Illustrator.\n• Creating vector illustrations and custom typography layouts in Figma.\n• Collaborating with marketing teams on creative campaign briefs.\n• Preparing high-resolution artwork for print production and packaging.\n• Maintaining brand consistency across digital and print touchpoints.",
            "work_environment": "Design agencies, advertising firms, in-house creative departments, or remote.",
            "work_modes": "Remote / Hybrid / Creative Studio",
            "minimum_qualification": "Undergraduate (B.Des / BFA / Any Degree with Portfolio)",
            "preferred_streams": "Any Stream",
            "required_subjects": "Design, Fine Arts, English",
            "technical_skills": "Adobe Photoshop, Illustrator, InDesign, Typography, Color Theory, Brand Identity Design, Vector Art",
            "soft_skills": "Visual Creativity, Storytelling, Active Listening, Adaptability",
            "tools": "Adobe Creative Cloud (Photoshop, Illustrator, InDesign), Figma, Procreate, Canva",
            "certifications": "Adobe Certified Professional (Photoshop / Illustrator)",
            "experience_level": "Entry-Level to Senior",
            "career_growth": "Broad creative path progressing to Senior Visual Designer, Art Director, or Creative Director.",
            "internship_roles": "Graphic Design Intern, Visual Design Trainee, Creative Studio Intern",
            "entry_level_roles": "Junior Graphic Designer, Visual Designer, Brand Designer",
            "average_salary": "₹3.5 - ₹10 LPA (Indicative range)",
            "salary_indicative": "Entry-Level (0-2 yrs): ₹3 - 4.5 LPA | Senior Designer (3-6 yrs): ₹6 - 12 LPA | Creative Director (7+ yrs): ₹16 - 35+ LPA. Indicative figures from National Institute of Design 2024.",
            "future_scope": "Continuous strong demand across digital branding, social media, e-commerce packaging, and SaaS product marketing.",
            "government_opportunities": "Directorate of Advertising and Visual Publicity (DAVP - CBC), National Book Trust, Doordarshan, NID.",
            "private_opportunities": "Ogilvy, Dentsu, Leo Burnett, Swiggy, Zomato, boutique branding agencies.",
            "higher_study_options": "M.Des in Graphic Design (NID, IIT IDC), Master of Fine Arts (MFA).",
            "entrepreneurship_options": "Independent branding agency, freelance design practice, digital art and asset marketplace.",
            "source": "National Institute of Design (NID) / Media & Entertainment Skills Council",
            "official_url": "https://www.nid.edu",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 33, "type": "DIRECT"}, {"course_id": 14, "type": "ALTERNATIVE"}],
            "exams": [{"exam_id": 85, "importance": "PRIMARY"}, {"exam_id": 84, "importance": "PRIMARY"}],
            "routes": [{"title": "Path A: Formal Design Degree (NID / NIFT)", "type": "COMMON", "steps": "Class 12 -> NID DAT / UCEED -> B.Des Graphic Design -> Portfolio -> Brand Designer."}],
            "ladder": [
                {"stage": "Junior Graphic Designer", "exp": "0-2 Years", "desc": "Creates social graphics, banner resizing, supports senior art directors."},
                {"stage": "Senior Visual Designer", "exp": "2-5 Years", "desc": "Owns complete brand identity redesigns, directs photoshoot styles, defines visual guidelines."},
                {"stage": "Art Director", "exp": "5-8 Years", "desc": "Directs overall aesthetic vision for major advertising accounts and product packaging."},
                {"stage": "Creative Director", "exp": "8+ Years", "desc": "Heads agency creative department, wins national and international design awards."}
            ],
            "roadmaps": {
                "Class 10": "Practice sketching, digital illustration, and study typography in books and posters.",
                "Class 12": "Prepare for NID DAT, UCEED, or NIFT entrance exams.",
                "Graduation": "Complete B.Des or build a Behance/Dribbble portfolio showcasing 5 comprehensive brand identity projects.",
                "Working Professional": "Master 3D design, motion graphics (After Effects), and design systems."
            }
        },
        {
            "title": "3D Animator & Visual Effects (VFX) Artist",
            "short_name": "3D Animator / VFX",
            "slug": "3d-animator-vfx-artist",
            "category": "Design, Animation & Creative Arts",
            "sub_category": "Animation, VFX & Gaming",
            "industry": "Entertainment, Gaming & Media",
            "icon": "camera-reels",
            "short_description": "Creates 3D computer animations, character models, and cinematic visual effects for films, gaming, and television.",
            "description": "3D Animators and Visual Effects (VFX) Artists bring digital characters, environments, and fantastical worlds to life. They model 3D assets, rig skeletal animation, simulate fluid dynamics (fire, explosions, water), and composite live-action footage with CGI.",
            "what_they_do": "They sculpt 3D characters in ZBrush, keyframe animations in Maya, simulate particle effects in Houdini, composite movie shots in Nuke, and optimize real-time 3D assets for Unreal Engine.",
            "day_to_day_work": "• Modeling and texturing 3D photorealistic assets in Maya and Substance Painter.\n• Rigging character skeletons and animating character movement acting.\n• Simulating complex physics particles (smoke, fire, water, dust) in Houdini.\n• Compositing CGI visual layers with live film plates in Nuke.\n• Reviewing dailies with VFX Supervisors and film directors.",
            "work_environment": "Animation studios, VFX post-production facilities, video game studios.",
            "work_modes": "On-site / Studio Lab / Hybrid",
            "minimum_qualification": "Undergraduate (B.Sc Animation / B.Des / Diploma + Showreel)",
            "preferred_streams": "Any Stream",
            "required_subjects": "Animation, Computer Graphics, Fine Arts",
            "technical_skills": "3D Modeling, Character Animation, Rigging, Houdini VFX, Compositing (Nuke), Unreal Engine, Lighting & Rendering",
            "soft_skills": "Patience, Cinematic Eye, Attention to Real-World Physics, Collaboration",
            "tools": "Autodesk Maya, Houdini, ZBrush, Foundry Nuke, Unreal Engine, Blender",
            "certifications": "Autodesk Certified Professional (Maya), Unreal Engine Fellowship",
            "experience_level": "Entry-Level to Senior",
            "career_growth": "Global career progressing to Lead Animator, CG Supervisor, or VFX Director.",
            "internship_roles": "VFX Trainee, Junior 3D Artist, Roto/Paint Intern",
            "entry_level_roles": "Junior 3D Modeler, Roto Artist, Junior Animator",
            "average_salary": "₹4 - ₹12 LPA (Indicative range)",
            "salary_indicative": "Entry-Level Artist (0-2 yrs): ₹3.5 - 5.5 LPA | Senior VFX Artist (3-6 yrs): ₹7.5 - 15 LPA | VFX Supervisor (7+ yrs): ₹18 - 45+ LPA. Indicative figures from MESC 2024.",
            "future_scope": "Booming national growth powered by India's massive film VFX industry (RRR, Brahmastra) and international Hollywood outsourcing.",
            "government_opportunities": "National Film Development Corporation (NFDC), Children's Film Society, Doordarshan Animation.",
            "private_opportunities": "Technicolor India, DNEG, Redchillies VFX, MPC, Framestore, Ubisoft India, Rockstar Games India.",
            "higher_study_options": "Master's in Animation & VFX, Gobelins (Paris) / Vancouver Film School fellowships.",
            "entrepreneurship_options": "Boutique VFX studio, 3D architectural visualization agency, indie game development studio.",
            "source": "Media & Entertainment Skills Council (MESC)",
            "official_url": "https://mescindia.org",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 33, "type": "DIRECT"}, {"course_id": 14, "type": "ALTERNATIVE"}],
            "exams": [{"exam_id": 84, "importance": "PRIMARY"}],
            "routes": [{"title": "Path A: Animation Degree + Showreel Route", "type": "COMMON", "steps": "Class 12 -> B.Sc Animation / B.Des -> Specialize in 3D Modeling or FX -> Build high-impact 2-minute demo reel -> VFX Studio Artist."}],
            "ladder": [
                {"stage": "Junior VFX / Roto Artist", "exp": "0-2 Years", "desc": "Handles rotoscoping, clean plate prep, basic asset texturing."},
                {"stage": "3D Animator / Lighting Artist", "exp": "2-5 Years", "desc": "Keyframes character emotions, sets up photorealistic lighting and render passes."},
                {"stage": "Lead FX Artist / CG Supervisor", "exp": "5-8 Years", "desc": "Supervises procedural Houdini simulations, manages asset pipelines across studio."},
                {"stage": "VFX Supervisor / Creative Director", "exp": "8+ Years", "desc": "Collaborates directly with film directors on movie sets and directs post-production."}
            ],
            "roadmaps": {
                "Class 10": "Learn Blender (free 3D software) and study the 12 Principles of Animation.",
                "Class 12": "Build an artistic portfolio with life drawings, character sketches, and 3D models.",
                "Graduation": "Complete formal animation training and master industry tools (Maya, Houdini, Nuke). Create a specialized demo reel.",
                "Working Professional": "Learn real-time rendering in Unreal Engine 5 for virtual production and AAA game development."
            }
        },
        {
            "title": "Fashion Designer & Apparel Stylist",
            "short_name": "Fashion Designer",
            "slug": "fashion-designer",
            "category": "Design, Animation & Creative Arts",
            "sub_category": "Apparel, Textile & Lifestyle Design",
            "industry": "Fashion, Apparel & Retail",
            "icon": "scissors",
            "short_description": "Creates original clothing, footwear, and accessory designs, blending aesthetic trends with textile technology.",
            "description": "Fashion Designers conceptualize and execute clothing and lifestyle collections. They predict seasonal trends, select textile fabrics, create pattern cuts, manage garment construction, and showcase collections at fashion weeks.",
            "what_they_do": "They sketch garment silhouettes, develop mood boards, select sustainable fabrics and trims, create pattern prototypes, direct fitting sessions, and manage garment production runs.",
            "day_to_day_work": "• Sketching seasonal garment concepts in Adobe Illustrator and Procreate.\n• Sourcing textile fabrics and evaluating drape, texture, and weave.\n• Draping fabric on mannequins and creating technical pattern specifications.\n• Conducting fitting sessions with models and tailoring master tailors.\n• Managing fashion runway presentations and retail catalog styling.",
            "work_environment": "Fashion design studios, garment manufacturing export houses, fashion retail brands.",
            "work_modes": "On-site / Studio & Factory / Runway",
            "minimum_qualification": "Undergraduate (B.Des in Fashion Design - NIFT)",
            "preferred_streams": "Any Stream",
            "required_subjects": "Fashion Studies, Fine Arts, English",
            "technical_skills": "Fashion Illustration, Pattern Making, Garment Construction, Textile Science, Trend Forecasting, CLO 3D, Draping",
            "soft_skills": "Trend Vision, Creative Audacity, Material Empathy, Commercial Pragmatism",
            "tools": "CLO 3D, Adobe Illustrator, Sewing Machines, Pattern Grading Software, Mannequins",
            "certifications": "National Institute of Fashion Technology (NIFT) Degree",
            "experience_level": "Entry-Level to Senior",
            "career_growth": "Celebrity path progressing to Head of Design, Creative Director of Retail Brand, or eponymous fashion couture label.",
            "internship_roles": "Fashion Design Intern, Styling Assistant, Export House Merchandising Intern",
            "entry_level_roles": "Assistant Fashion Designer, Junior Stylist, Apparel Merchandiser",
            "average_salary": "₹4 - ₹12 LPA (Indicative range)",
            "salary_indicative": "Assistant Designer (0-2 yrs): ₹3.5 - 5.5 LPA | Senior Brand Designer (3-6 yrs): ₹7 - 14 LPA | Creative Director / Couture Label (7+ yrs): ₹20 - 50+ LPA. Indicative figures from NIFT 2024.",
            "future_scope": "Growing rapidly fueled by sustainable fashion, digital 3D garment sampling (CLO 3D), and India's multi-billion apparel retail market.",
            "government_opportunities": "National Institute of Fashion Technology (NIFT), Central Silk Board, Handloom Export Promotion Council (HEPC).",
            "private_opportunities": "Aditya Birla Fashion & Retail (ABFRL), Reliance Retail, Fabindia, Sabyasachi, Manish Malhotra, Zara India.",
            "higher_study_options": "M.Des in Fashion Design, Master of Fashion Management (MFM - NIFT).",
            "entrepreneurship_options": "Independent fashion label, sustainable clothing brand, custom bridal couture studio.",
            "source": "National Institute of Fashion Technology (NIFT) / Ministry of Textiles",
            "official_url": "https://www.nift.ac.in",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 33, "type": "DIRECT"}],
            "exams": [{"exam_id": 85, "importance": "ALTERNATIVE"}, {"exam_id": 84, "importance": "ALTERNATIVE"}],
            "routes": [{"title": "Path A: NIFT Fashion Design Route", "type": "COMMON", "steps": "Class 12 -> NIFT Entrance Examination (CAT + GAT + Situation Test) -> B.Des Fashion Design (4 yrs) -> Graduation Collection -> Assistant Designer."}],
            "ladder": [
                {"stage": "Assistant Designer / Styling Trainee", "exp": "0-2 Years", "desc": "Assists with tech packs, trims sourcing, pattern adjustments, fitting notes."},
                {"stage": "Fashion Designer", "exp": "2-5 Years", "desc": "Designs seasonal collections for commercial retail brands, directs sample development."},
                {"stage": "Head of Design / Creative Lead", "exp": "5-8 Years", "desc": "Sets brand seasonal trend direction, approves fabric selections across product categories."},
                {"stage": "Creative Director / Couture Label Founder", "exp": "8+ Years", "desc": "Shows at Lakme Fashion Week, defines national fashion trends, leads luxury retail business."}
            ],
            "roadmaps": {
                "Class 10": "Practice fashion figure sketching and observe global style trends.",
                "Class 12": "Prepare for NIFT entrance examinations (Creative Ability Test - CAT and General Ability Test - GAT).",
                "Graduation": "Complete B.Des at NIFT. Master pattern drafting, garment construction, and CLO 3D virtual fashion design.",
                "Working Professional": "Launch an independent sustainable label or lead womenswear/menswear collections for major fashion retail conglomerates."
            }
        },
        {
            "title": "Interior Designer & Space Planner",
            "short_name": "Interior Designer",
            "slug": "interior-designer",
            "category": "Design, Animation & Creative Arts",
            "sub_category": "Interior, Spatial & Architectural Design",
            "industry": "Interior Design, Architecture & Real Estate",
            "icon": "door-open",
            "short_description": "Plans and designs functional, aesthetically pleasing, and safe interior spaces for homes, offices, and commercial establishments.",
            "description": "Interior Designers manipulate architectural interiors to enhance human experience, workflow, and well-being. They select materials, color schemes, lighting, acoustic treatments, and custom furniture while adhering to building codes.",
            "what_they_do": "They produce 2D architectural floor plans, create 3D photorealistic room renders, select materials and furnishings, manage on-site contractor carpentry, and ensure project execution within budgets.",
            "day_to_day_work": "• Meeting clients to understand functional spatial needs and aesthetic preferences.\n• Drafting architectural floor layouts and electrical schematics in AutoCAD.\n• Creating 3D photorealistic interior renders in 3ds Max / SketchUp + V-Ray.\n• Selecting wood veneers, marbles, tiles, fabrics, and designer lighting fixtures.\n• Supervising on-site civil, carpentry, and electrical execution with contractors.",
            "work_environment": "Interior design studios, architectural firms, active client construction sites.",
            "work_modes": "On-site / Design Studio & Site Visits",
            "minimum_qualification": "Undergraduate (B.Des Interior Design / B.Arch / Diploma)",
            "preferred_streams": "Any Stream",
            "required_subjects": "Design, Mathematics (helpful)",
            "technical_skills": "Space Planning, AutoCAD, 3ds Max, V-Ray, SketchUp, Material Knowledge, Lighting Design, Building Codes",
            "soft_skills": "Client Empathy, Aesthetic Sophistication, Contractor Management, Budgeting",
            "tools": "AutoCAD, 3ds Max, V-Ray, SketchUp, Lumion, Photoshop, Material Samples",
            "certifications": "Institute of Indian Interior Designers (IIID) Professional Membership",
            "experience_level": "Entry-Level to Senior",
            "career_growth": "Broad, lucrative path progressing to Senior Space Planner, Design Partner, or independent interior firm founder.",
            "internship_roles": "Interior Design Intern, Site Trainee, 3D Visualizer Intern",
            "entry_level_roles": "Junior Interior Designer, 3D Visualizer, Site Coordinator",
            "average_salary": "₹4 - ₹12 LPA (Indicative range - plus execution project margins)",
            "salary_indicative": "Junior Designer (0-2 yrs): ₹3.5 - 5 LPA | Senior Interior Designer (3-6 yrs): ₹6.5 - 13 LPA | Interior Firm Principal (7+ yrs): ₹18 - 45+ LPA. Indicative figures from IIID 2024.",
            "future_scope": "Explosive growth driven by India's residential real estate boom, modern corporate offices, and luxury retail hospitality.",
            "government_opportunities": "CPWD Architecture & Interior Wing, NBCC, ITDC Hotel Renovations, Airport Authority of India (AAI).",
            "private_opportunities": "Livspace, HomeLane, Morphogenesis, Hafeez Contractor, leading boutique interior design studios.",
            "higher_study_options": "M.Des in Interior & Spatial Design, Master's in Sustainable Architecture.",
            "entrepreneurship_options": "Independent interior design studio, turnkey residential design-build firm, bespoke furniture atelier.",
            "source": "Institute of Indian Interior Designers (IIID)",
            "official_url": "https://www.iiid.in",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 33, "type": "DIRECT"}, {"course_id": 32, "type": "COMMON"}],
            "exams": [{"exam_id": 83, "importance": "PRIMARY"}, {"exam_id": 84, "importance": "ALTERNATIVE"}],
            "routes": [{"title": "Path A: Interior Design Degree Route", "type": "COMMON", "steps": "Class 12 -> NATA / UCEED / NID -> B.Des Interior Design / B.Arch -> 3D Portfolio -> Interior Designer."}],
            "ladder": [
                {"stage": "Junior Designer / Visualizer", "exp": "0-2 Years", "desc": "Drafts AutoCAD furniture details, models 3D rooms in SketchUp, prepares mood boards."},
                {"stage": "Interior Project Designer", "exp": "2-5 Years", "desc": "Manages complete residential or commercial turnkey fitouts, supervises site contractors."},
                {"stage": "Senior Associate / Design Lead", "exp": "5-8 Years", "desc": "Leads high-value corporate office or luxury hospitality interior architecture projects."},
                {"stage": "Principal Interior Architect / Studio Founder", "exp": "8+ Years", "desc": "Heads independent interior design practice handling multi-crore luxury estates."}
            ],
            "roadmaps": {
                "Class 10": "Develop interest in room layouts, furniture design, and drawing spatial perspectives.",
                "Class 12": "Choose any stream for Class 12 board exams.",
                "Graduation": "Complete B.Des Interior Design or B.Arch. Master AutoCAD, 3ds Max/SketchUp, and photorealistic V-Ray rendering.",
                "Working Professional": "Learn turnkey project management, HVAC/electrical coordination, and build relationships with luxury material suppliers."
            }
        },

        # =====================================================================
        # AVIATION & LOGISTICS
        # =====================================================================
        {
            "title": "Air Traffic Controller (ATC)",
            "short_name": "Air Traffic Controller",
            "slug": "air-traffic-controller",
            "category": "Aviation, Logistics & Supply Chain",
            "sub_category": "Aviation Operations & Airspace Management",
            "industry": "Civil Aviation & Airspace Management",
            "icon": "broadcast-pin",
            "short_description": "Directs aircraft movements on runways and in national airspace to prevent mid-air collisions and ensure efficient air transit.",
            "description": "Air Traffic Controllers coordinate the movement of thousands of aircraft across national airspace. They issue takeoff and landing clearances, maintain radar separation between aircraft, guide pilots during bad weather, and manage airport ground operations.",
            "what_they_do": "They monitor primary and secondary surveillance radars, issue speed and altitude directives to pilots, coordinate runway departures and arrivals, and execute emergency responses during aircraft distress.",
            "day_to_day_work": "• Monitoring radar consoles to maintain mandatory aircraft separation distances.\n• Issuing tactical radio clearances for taxi, takeoff, approach, and landing.\n• Managing air traffic flow during adverse monsoons and low visibility (CAT-III).\n• Coordinating airspace transitions with adjacent civil and military ATC sectors.\n• Responding immediately to aircraft emergencies (engine failure, medical diverts).",
            "work_environment": "Airport control towers, radar approach control centers, en-route area control centers.",
            "work_modes": "On-site / Shift Rotations / High-Stakes Concentration",
            "minimum_qualification": "Undergraduate (B.Sc with Physics & Maths / B.Tech)",
            "preferred_streams": "Science (PCM)",
            "required_subjects": "Physics, Mathematics",
            "technical_skills": "Air Traffic Management, Radar Separation, ICAO Aviation Regulations, Radio Telephony, Aerodrome Control, Meteorology",
            "soft_skills": "Supreme Situational Awareness, Calm Decisiveness Under Extreme Pressure, Spatial Reasoning, Clear Diction",
            "tools": "Radar Displays (TopSky / Raytheon), Radio Telephony Systems, Electronic Flight Strips",
            "certifications": "Selected through AAI Junior Executive (ATC) Examination, Trained at Civil Aviation Training College (CATC Allahabad)",
            "experience_level": "Junior Executive (ATC) to Executive Director (ATM)",
            "career_growth": "Structured sovereign career progressing to Senior Manager, Joint General Manager, Airport ATC Incharge, or Executive Director of Air Traffic Management.",
            "internship_roles": "CATC Allahabad Institutional & Simulator Training (6 Months)",
            "entry_level_roles": "Junior Executive (Air Traffic Control)",
            "average_salary": "₹12 - ₹22 LPA (Official Airports Authority of India PSU Pay Scale: E-1 Level Basic ₹40,000 - ₹1,40,000 + Stress & Rating Allowances)",
            "salary_indicative": "Junior Executive (Level E-1): Basic ₹40,000 + DA + HRA + Rating Allowance = ~₹90,000 - ₹1,10,000/month gross. Regular promotions through executive scales.",
            "future_scope": "Essential sovereign function expanding with 100+ new airports under the UDAN regional connectivity scheme and skyrocketing passenger air traffic.",
            "government_opportunities": "Airports Authority of India (AAI - Annual Junior Executive ATC Recruitment).",
            "private_opportunities": "Not applicable (Sovereign Airspace Control under AAI / Ministry of Civil Aviation).",
            "higher_study_options": "Departmental executive ratings, ICAO Airspace Management fellowships.",
            "entrepreneurship_options": "Not applicable (Government Service).",
            "source": "Airports Authority of India (AAI) / DGCA",
            "official_url": "https://www.aai.aero",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 2, "type": "DIRECT"}, {"course_id": 1, "type": "DIRECT"}, {"course_id": 9, "type": "COMMON"}],
            "exams": [{"exam_id": 8, "importance": "ALTERNATIVE"}],
            "routes": [{"title": "Path A: AAI Junior Executive (ATC) Examination", "type": "COMMON", "steps": "B.Sc (Physics & Maths 60%+) or B.Tech (Any branch with Physics/Maths in semesters) -> Clear AAI JE (ATC) Computer Based Exam -> Voice Test & Medical Test -> 6 Months training at CATC Allahabad -> Licensed Air Traffic Controller."}],
            "ladder": [
                {"stage": "Junior Executive (ATC)", "exp": "0-3 Years", "desc": "Earns Aerodrome and Approach radar ratings, manages local runway departures."},
                {"stage": "Assistant General Manager (ATM)", "exp": "3-8 Years", "desc": "Commands busy international approach sectors (e.g. Mumbai, Delhi approach control)."},
                {"stage": "Joint General Manager / Tower Incharge", "exp": "8-15 Years", "desc": "Heads complete airport air traffic management and emergency coordination."},
                {"stage": "Executive Director (Air Traffic Management)", "exp": "15+ Years", "desc": "Directs sovereign Indian airspace policy, satellite navigation (GAGAN), and ICAO treaties."}
            ],
            "roadmaps": {
                "Class 10": "Focus on mental math speed, spatial reasoning, and clear verbal communication.",
                "Class 12": "Score at least 60% in Physics and Mathematics in Class 12.",
                "Graduation": "Complete B.Sc (Physics & Mathematics) or any B.Tech degree with good academic standing.",
                "Working Professional": "Prepare for the AAI Junior Executive (ATC) recruitment exam focusing on Physics, Mathematics, Reasoning, and English."
            }
        },
        {
            "title": "Aircraft Maintenance Engineer (AME)",
            "short_name": "Aircraft Maintenance Engr",
            "slug": "aircraft-maintenance-engineer",
            "category": "Aviation, Logistics & Supply Chain",
            "sub_category": "Aviation Engineering & Airworthiness",
            "industry": "Commercial Aviation & MRO",
            "icon": "tools",
            "short_description": "Inspects, services, and signs airworthiness certificates for aircraft engines, avionics, and mechanical systems before takeoff.",
            "description": "Aircraft Maintenance Engineers (AME) ensure that every aircraft that takes to the skies is in flawless mechanical and electrical working condition. Under DGCA CAR 66 regulations, no commercial flight can legally depart without an AME's signed Certificate of Release to Service (CRS).",
            "what_they_do": "They inspect jet engines, maintain landing gear hydraulics, troubleshoot glass cockpit avionics, repair composite airframes, and sign off aircraft airworthiness certificates.",
            "day_to_day_work": "• Performing pre-flight transit inspections and daily turnaround line maintenance.\n• Troubleshooting turbofan engine faults using electronic diagnostic equipment.\n• Replacing avionics navigation sensors and flight control actuators.\n• Conducting heavy C-check and D-check hangar overhauls.\n• Signing the legal Certificate of Release to Service (CRS) in the aircraft maintenance log.",
            "work_environment": "Airport tarmac ramps, maintenance hangars, MRO repair facilities.",
            "work_modes": "On-site / Airport Shift Rotations / 24x7 Maintenance Schedules",
            "minimum_qualification": "Class 12 (Physics, Chemistry & Maths 50%+) + DGCA CAR 66 AME License",
            "preferred_streams": "Science (PCM)",
            "required_subjects": "Physics, Mathematics, Chemistry",
            "technical_skills": "Jet Engine Systems (Turbofans), Aircraft Hydraulics, Avionics Systems, DGCA CAR 66 Regulations, Airframe Composite Repair, Non-Destructive Testing (NDT)",
            "soft_skills": "Zero-Tolerance for Errors, Supreme Responsibility, Technical Precision, Composure",
            "tools": "Aviation Torque Wrenches, Borescopes, Avionics Test Rigs, Safety Lockwires",
            "certifications": "DGCA CAR 66 Aircraft Maintenance Engineer License (Category A, B1, or B2)",
            "experience_level": "AME Trainee to Chief of Maintenance / Airworthiness Director",
            "career_growth": "Critical technical career progressing to Type-Rated Licensed AME, Base Maintenance Manager, or Director of Airworthiness.",
            "internship_roles": "Hangar Practical Maintenance Training (2-3 Years)",
            "entry_level_roles": "Junior Technician, AME Trainee, Aircraft Maintenance Associate",
            "average_salary": "₹5 - ₹18 LPA (Indicative range)",
            "salary_indicative": "AME Trainee (0-2 yrs): ₹3.5 - 5.5 LPA | DGCA Licensed AME with Type Rating (3-6 yrs): ₹10 - 22 LPA | Base Maintenance Manager (7+ yrs): ₹25 - 50+ LPA. Indicative figures from DGCA & Aviation MRO Audits 2024.",
            "future_scope": "Explosive growth as India develops into a major global Aviation Maintenance, Repair, and Overhaul (MRO) hub.",
            "government_opportunities": "Air India Engineering Services Limited (AIESL), BSF Aviation Wing, Coast Guard Aviation, DGCA Airworthiness Directorate.",
            "private_opportunities": "IndiGo Engineering, Air India, GMR Aero Technic, Air Works, Pratt & Whitney India, Boeing MRO.",
            "higher_study_options": "DGCA Additional Type Ratings (Boeing 737, Airbus A320, B777, B787), B.Tech in Aeronautical Engineering.",
            "entrepreneurship_options": "Aviation component repair station, NDT inspection consultancy, aircraft detailing and ground support enterprise.",
            "source": "Directorate General of Civil Aviation (DGCA) / CAR 66",
            "official_url": "https://www.dgca.gov.in",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 44, "type": "COMMON"}, {"course_id": 11, "type": "ALTERNATIVE"}],
            "exams": [{"exam_id": 8, "importance": "ALTERNATIVE"}],
            "routes": [{"title": "Path A: DGCA Approved AME Institute Route", "type": "COMMON", "steps": "Class 12 (PCM 50%+) -> Enroll in DGCA-approved CAR 147 AME Training Institute -> Clear DGCA CAR 66 Module Exams -> Complete 2-3 years practical maintenance experience on active aircraft -> Licensed AME (Category B1 or B2)."}],
            "ladder": [
                {"stage": "AME Trainee / Technician", "exp": "0-2 Years", "desc": "Assists licensed engineers in line maintenance, checks tire pressures, oil levels, servicing."},
                {"stage": "Licensed AME (Category B1 / B2)", "exp": "2-5 Years", "desc": "Type-rated on A320 or B737. Legally authorizes Certificate of Release to Service (CRS)."},
                {"stage": "Hangar / Line Maintenance Manager", "exp": "5-9 Years", "desc": "Oversees airline fleet turnarounds, manages hundreds of technicians, handles AOG (Aircraft on Ground) emergencies."},
                {"stage": "Director of Engineering / Airworthiness", "exp": "9+ Years", "desc": "Directs entire airline fleet maintenance operations and regulatory safety compliance."}
            ],
            "roadmaps": {
                "Class 10": "Focus on mechanical systems, tools, and basic physics.",
                "Class 12": "Score at least 50% in Physics, Chemistry, and Mathematics.",
                "Graduation": "Enroll in a DGCA-approved CAR 147 AME institute. Clear all DGCA CAR 66 basic module examinations.",
                "Working Professional": "Accumulate required practical maintenance hours on commercial aircraft, secure airline type-rating (A320/B737), and receive full signing authorization."
            }
        },

        # =====================================================================
        # SOCIAL SCIENCES & HUMANITIES
        # =====================================================================
        {
            "title": "Development Economist",
            "short_name": "Development Economist",
            "slug": "development-economist",
            "category": "Social Sciences, Psychology & Public Policy",
            "sub_category": "Economic Policy & International Development",
            "industry": "International Development & Economic Policy",
            "icon": "graph-up",
            "short_description": "Analyzes economic data to design policies that reduce poverty, foster equitable growth, and improve human development indices.",
            "description": "Development Economists study the fiscal, monetary, trade, and social policies that drive prosperity in emerging economies. They research poverty alleviation, labor markets, agricultural markets, public health economics, and educational equity.",
            "what_they_do": "They analyze macroeconomic indicators, conduct econometrics regressions on national survey datasets, design randomized evaluations, publish policy research papers, and advise central banks and international institutions.",
            "day_to_day_work": "• Running econometric models and difference-in-differences regressions in Stata.\n• Analyzing data from the Periodic Labour Force Survey (PLFS) and National Family Health Survey (NFHS).\n• Evaluating the impact of government direct benefit transfer (DBT) schemes.\n• Writing policy white papers and macroeconomic forecasting reports.\n• Presenting findings to government economic advisors and multilateral funding organizations.",
            "work_environment": "Central research institutes, international development organizations (World Bank, IMF, ADB), universities.",
            "work_modes": "Hybrid / Research Office / Field Surveys",
            "minimum_qualification": "Postgraduate (M.A. / M.Sc in Economics / Ph.D.)",
            "preferred_streams": "Economics / Science with Maths / Humanities",
            "required_subjects": "Economics, Mathematics, Statistics",
            "technical_skills": "Microeconomics, Macroeconomics, Econometrics, Stata, R, Randomized Controlled Trials (RCTs), Survey Design, Fiscal Policy",
            "soft_skills": "Analytical Depth, Social Empathy, Critical Thinking, Academic Writing",
            "tools": "Stata, R, Python, EViews, Excel (Advanced), LaTeX",
            "certifications": "Indian Economic Service (IES - UPSC), UGC NET in Economics",
            "experience_level": "Research Associate to Chief Economist",
            "career_growth": "Prestigious international career progressing to Chief Economic Advisor to Government, World Bank Country Economist, or Professor.",
            "internship_roles": "Economic Research Intern, J-PAL Research Associate Trainee",
            "entry_level_roles": "Research Associate, Assistant Director (Indian Economic Service), Economic Analyst",
            "average_salary": "₹7 - ₹20 LPA (Indicative range)",
            "salary_indicative": "Research Associate (0-2 yrs): ₹6 - 9 LPA | IES Officer (Scale 10) / Senior Economist (3-6 yrs): ₹10 - 22 LPA | Chief Economist / World Bank Director (7+ yrs): ₹30 - 75+ LPA. Indicative figures from Indian Economic Service & World Bank 2024.",
            "future_scope": "High national and global importance as India navigates middle-income growth, demographic dividend, and green energy transition.",
            "government_opportunities": "Indian Economic Service (IES - UPSC), Reserve Bank of India (DEPR - Department of Economic and Policy Research), NITI Aayog.",
            "private_opportunities": "World Bank, International Monetary Fund (IMF), Asian Development Bank (ADB), J-PAL, CRISIL, Goldman Sachs Research.",
            "higher_study_options": "Ph.D. in Economics from Delhi School of Economics (DSE), ISI, London School of Economics (LSE), Harvard, MIT.",
            "entrepreneurship_options": "Economic consulting boutique, independent macroeconomic forecasting firm.",
            "source": "Indian Economic Service (IES) / Delhi School of Economics",
            "official_url": "https://www.upsc.gov.in",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 20, "type": "DIRECT"}, {"course_id": 24, "type": "DIRECT"}, {"course_id": 1, "type": "COMMON"}],
            "exams": [{"exam_id": 41, "importance": "PRIMARY"}, {"exam_id": 10, "importance": "ALTERNATIVE"}],
            "routes": [{"title": "Path A: Master's in Economics to IES / International Development", "type": "COMMON", "steps": "B.A. Economics (Hons) -> M.A. Economics from Delhi School of Economics / JNU / ISI -> Clear UPSC Indian Economic Service (IES) exam or join World Bank/J-PAL."}],
            "ladder": [
                {"stage": "Research Associate / Economic Analyst", "exp": "0-2 Years", "desc": "Cleans microdata, executes econometric regressions, assists in drafting reports."},
                {"stage": "Economist / Assistant Director (IES)", "exp": "2-5 Years", "desc": "Drafts policy analysis for Ministry of Finance, models inflation and GDP forecasts."},
                {"stage": "Senior / Lead Economist", "exp": "5-9 Years", "desc": "Leads country economic diagnostic reviews, designs national social protection schemes."},
                {"stage": "Chief Economic Advisor / Chief Economist", "exp": "9+ Years", "desc": "Authors Economic Survey of India or directs international developmental financing."}
            ],
            "roadmaps": {
                "Class 10": "Develop interest in national economy, GDP, banking, and current affairs.",
                "Class 12": "Score top marks in Economics and Mathematics.",
                "Graduation": "Complete B.A. (Hons) Economics with rigorous calculus, linear algebra, and statistics. Aim for master's at Delhi School of Economics, ISI, or JNU.",
                "Working Professional": "Prepare for the prestigious UPSC Indian Economic Service (IES) examination or pursue doctoral research."
            }
        },
        {
            "title": "Social Worker & Community Development Specialist",
            "short_name": "Social Worker (MSW)",
            "slug": "social-worker",
            "category": "Social Sciences, Psychology & Public Policy",
            "sub_category": "Community Development & Social Work",
            "industry": "Non-Profit, CSR & Social Development",
            "icon": "heart",
            "short_description": "Empowers vulnerable communities, manages grassroots welfare interventions, and drives corporate social responsibility (CSR) programs.",
            "description": "Professional Social Workers design and implement impactful grassroots programs to uplift marginalized communities. They work in child protection, women's empowerment, rural livelihoods, disability rehabilitation, and Corporate Social Responsibility (CSR).",
            "what_they_do": "They conduct participatory rural appraisals (PRA), mobilize community self-help groups (SHGs), manage NGO welfare projects, monitor CSR grant utilization, and advocate for human rights.",
            "day_to_day_work": "• Conducting community focus group discussions in rural villages and urban slums.\n• Mobilizing women's self-help groups (SHGs) and livelihood cooperatives.\n• Implementing Corporate Social Responsibility (CSR) projects funded by corporations.\n• Writing grant funding proposals and monitoring project outcomes.\n• Counseling families in distress and coordinating emergency welfare assistance.",
            "work_environment": "Grassroots non-profits, rural field locations, corporate CSR foundations, government welfare departments.",
            "work_modes": "Field Work / Community Mobilization / Office",
            "minimum_qualification": "Postgraduate (Master of Social Work - MSW / BSW)",
            "preferred_streams": "Any Stream (Humanities / Social Sciences preferred)",
            "required_subjects": "Social Work, Sociology, Psychology",
            "technical_skills": "Community Mobilization, Participatory Rural Appraisal (PRA), Project Lifecycle Management, CSR Regulations (Companies Act Sec 135), Monitoring & Evaluation (M&E)",
            "soft_skills": "Deep Empathy, Cultural Sensitivity, Resilience, Persuasive Community Leadership",
            "tools": "SurveyCTO, KoboToolbox, LogFrame Matrix, Excel, Field Assessment Kits",
            "certifications": "Master of Social Work (MSW) from Tata Institute of Social Sciences (TISS) or recognized university",
            "experience_level": "Entry-Level to Senior NGO Director",
            "career_growth": "Broad, noble career progressing to Project Director, CSR Head of Multinational Corporation, or UN Program Officer.",
            "internship_roles": "Social Work Concurrent Fieldwork (Integrated in MSW - 2 Days/Week Fieldwork)",
            "entry_level_roles": "Field Coordinator, Community Mobilizer, CSR Executive, Project Associate",
            "average_salary": "₹4 - ₹11 LPA (Indicative range)",
            "salary_indicative": "Entry-Level Field Worker (0-2 yrs): ₹3.5 - 5.5 LPA | CSR Program Manager (3-6 yrs): ₹7 - 14 LPA | Head of CSR / NGO Director (7+ yrs): ₹18 - 35+ LPA. Indicative figures from TISS & Social Sector Audits 2024.",
            "future_scope": "Surging demand driven by mandatory 2% Corporate Social Responsibility (CSR) spending in India and sustainable development goals (SDGs).",
            "government_opportunities": "Ministry of Women & Child Development, National Rural Livelihoods Mission (NRLM - Aajeevika), District Child Protection Units (DCPU).",
            "private_opportunities": "Tata Trusts, Reliance Foundation, Azim Premji Foundation, CRY, PRADAN, Teach For India, Bill & Melinda Gates Foundation.",
            "higher_study_options": "M.Phil / Ph.D. in Social Work from TISS Mumbai, Global Development Fellowships.",
            "entrepreneurship_options": "Founding an impactful non-profit organization (NGO), social enterprise cooperative, CSR impact auditing firm.",
            "source": "Tata Institute of Social Sciences (TISS) / National Association of Professional Social Workers in India",
            "official_url": "https://www.tiss.edu",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 20, "type": "COMMON"}, {"course_id": 21, "type": "COMMON"}, {"course_id": 22, "type": "COMMON"}],
            "exams": [{"exam_id": 79, "importance": "PRIMARY"}],
            "routes": [{"title": "Path A: Master of Social Work (TISS Route)", "type": "COMMON", "steps": "Graduation in any stream -> TISS Admission Test (CUET-PG) -> Master of Social Work (MSW) at TISS Mumbai -> CSR / Foundation Placement."}],
            "ladder": [
                {"stage": "Field Project Officer", "exp": "0-2 Years", "desc": "Implements village training, mobilizes youth groups, monitors field execution."},
                {"stage": "CSR / NGO Project Manager", "exp": "2-5 Years", "desc": "Manages multi-district welfare interventions, tracks grant budgets, writes impact reports."},
                {"stage": "Head of Corporate Social Responsibility (CSR)", "exp": "5-8 Years", "desc": "Directs multi-crore corporate CSR fund allocation complying with Companies Act 2013."},
                {"stage": "Country Director / Foundation Trustee", "exp": "8+ Years", "desc": "Heads national non-profit foundations or directs international UN human welfare programs."}
            ],
            "roadmaps": {
                "Class 10": "Participate in social service clubs, tree plantation, and volunteer in community events.",
                "Class 12": "Choose any stream for Class 12 board exams.",
                "Graduation": "Complete graduation in Social Sciences, Humanities, or any discipline. Volunteer with active grassroots NGOs.",
                "Working Professional": "Pursue an MSW from premier institutes like Tata Institute of Social Sciences (TISS) and master CSR project management."
            }
        }
    ]

print("Catalog builder part 7 ready.")
