"""
scripts/catalog_builder_part5.py
Authentic occupational profiles for Science, Education, Media, Design, Agriculture, Aviation, and Social Sciences.
"""

def get_science_careers():
    return [
        {
            "title": "Research Scientist (Physics)",
            "short_name": "Physicist / Scientist",
            "slug": "research-scientist-physics",
            "category": "Science, Research & Mathematics",
            "sub_category": "Physical Sciences & Fundamental Research",
            "industry": "Scientific Research & Development",
            "icon": "atom",
            "short_description": "Conducts theoretical and experimental research into the fundamental laws governing matter, energy, quantum mechanics, and the universe.",
            "description": "Physicists investigate the fundamental properties of the universe from subatomic particles to cosmological galaxies. They conduct research in condensed matter physics, quantum computing, nuclear physics, optics, and high-energy physics.",
            "what_they_do": "They formulate mathematical physical theories, design complex laboratory experiments, operate particle accelerators and lasers, simulate quantum systems, and publish peer-reviewed papers in international science journals.",
            "day_to_day_work": "• Designing and conducting laboratory experiments in optics, lasers, or cryogenics.\n• Formulating theoretical mathematical models and equations.\n• Writing computational physics simulations in Python, C++, or Fortran.\n• Analyzing data from experimental detectors and particle colliders.\n• Writing research grant proposals and peer-reviewed scientific papers.",
            "work_environment": "National physics research laboratories, atomic research centers, university physics departments.",
            "work_modes": "On-site / Cleanroom & Lab / Academic Office",
            "minimum_qualification": "Doctorate (Ph.D. in Physics)",
            "preferred_streams": "Science (PCM)",
            "required_subjects": "Physics, Mathematics",
            "technical_skills": "Quantum Mechanics, Statistical Physics, Electrodynamics, Mathematical Modeling, Python/C++, Laboratory Instrumentation, Cryogenics",
            "soft_skills": "Deep Intellectual Curiosity, Tenacity, Scientific Integrity, Critical Thinking",
            "tools": "MATLAB, Python (SciPy/NumPy), LabVIEW, Cryostats, Oscilloscopes, LaTeX",
            "certifications": "CSIR-UGC NET JRF, GATE in Physics",
            "experience_level": "Postdoctoral Fellow to Senior Scientist / Professor",
            "career_growth": "Prestigious academic trajectory progressing to Principal Scientist, Bhatnagar Awardee, or Director of Research Institute.",
            "internship_roles": "Summer Research Fellow (IASc-INSA-NASI), Research Project Trainee",
            "entry_level_roles": "Junior Research Fellow (JRF), Scientist 'C' (DRDO/ISRO), Postdoctoral Researcher",
            "average_salary": "₹7 - ₹18 LPA (Official 7th CPC Scientist grades / UGC Assistant Professor pay scales)",
            "salary_indicative": "JRF / Postdoc (0-3 yrs): ₹37,000 - ₹54,000/mo fellowship + HRA | Scientist C / Assistant Professor: Basic ₹67,700 - ₹1,00,000/mo + Perks | Director / Senior Professor: ₹1,80,000 - ₹2,25,000/mo. Indicative from CSIR & UGC 2024.",
            "future_scope": "Sustained high national priority fueled by the National Quantum Mission (₹6,000 Cr), semiconductor physics, and clean nuclear energy.",
            "government_opportunities": "BARC (Bhabha Atomic Research Centre), TIFR, IISc, DRDO, ISRO, CSIR-NPL, Inter-University Accelerator Centre (IUAC).",
            "private_opportunities": "Quantum computing research labs (IBM Quantum, Google Quantum AI), semiconductor research divisions.",
            "higher_study_options": "Postdoctoral Fellowships at top global physics institutes (CERN, MIT, Max Planck).",
            "entrepreneurship_options": "Deep-tech physics hardware startup, precision optical measurement instruments company.",
            "source": "Council of Scientific and Industrial Research (CSIR) / TIFR",
            "official_url": "https://www.csir.res.in",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 2, "type": "DIRECT"}, {"course_id": 35, "type": "DIRECT"}, {"course_id": 1, "type": "COMMON"}],
            "exams": [{"exam_id": 81, "importance": "PRIMARY"}, {"exam_id": 69, "importance": "PRIMARY"}, {"exam_id": 82, "importance": "PRIMARY"}],
            "routes": [{"title": "Path A: Standard Academic Physics Route", "type": "COMMON", "steps": "B.Sc Physics -> IIT JAM -> M.Sc Physics at IITs / IISc -> CSIR-UGC NET JRF / GATE -> Ph.D. in Physics -> Postdoc -> Research Scientist / Professor."}],
            "ladder": [
                {"stage": "Junior / Senior Research Fellow (JRF/SRF)", "exp": "0-5 Years (Ph.D.)", "desc": "Conducts doctoral thesis research, runs lab equipment, publishes 3+ papers."},
                {"stage": "Postdoctoral Fellow / Scientist C", "exp": "5-8 Years", "desc": "Independent research on quantum materials or particle detectors, presents at international conferences."},
                {"stage": "Principal Scientist / Associate Professor", "exp": "8-15 Years", "desc": "Secures multi-crore national research grants, leads dedicated physics lab, guides Ph.D. scholars."},
                {"stage": "Director of National Lab / Bhatnagar Laureate", "exp": "15+ Years", "desc": "Heads premier national science institution, shapes national science policy."}
            ],
            "roadmaps": {
                "Class 10": "Develop deep fascination with how nature, gravity, light, and atoms work.",
                "Class 12": "Top scores in Physics and Mathematics. Prepare for IISER IAT or JEE Advanced for IISc/IITs.",
                "Graduation": "Complete B.Sc in Physics with deep study of Classical Mechanics, Quantum Physics, and Electrodynamics. Clear IIT JAM.",
                "Working Professional": "Clear CSIR NET JRF in physical sciences to secure government fellowship for doctoral research at IISc, TIFR, or IITs."
            }
        },
        {
            "title": "Statistician & Biostatistician",
            "short_name": "Statistician",
            "slug": "statistician",
            "category": "Science, Research & Mathematics",
            "sub_category": "Mathematical & Statistical Sciences",
            "industry": "Scientific Research & Pharmaceuticals",
            "icon": "calculator-fill",
            "short_description": "Designs statistical experiments, clinical trials, and mathematical models to analyze complex empirical phenomena.",
            "description": "Statisticians apply mathematical theory to design surveys, analyze scientific experiments, and model uncertain phenomena. Biostatisticians specialize in biomedical clinical trials, analyzing whether new pharmaceutical drugs and medical interventions are safe and effective.",
            "what_they_do": "They design sample sizes for clinical trials and national surveys, analyze clinical trial efficacy (Phase I-IV), build survival models, run statistical hypothesis tests, and author regulatory submissions for drug authorities (FDA/CDSCO).",
            "day_to_day_work": "• Designing Statistical Analysis Plans (SAP) for human pharmaceutical clinical trials.\n• Writing statistical programs in SAS or R to analyze clinical trial patient data.\n• Conducting survival analysis (Kaplan-Meier curves, Cox proportional hazards).\n• Reviewing statistical validity of clinical study reports (CSR).\n• Presenting findings to clinical trial safety review boards and drug regulators.",
            "work_environment": "Pharmaceutical clinical research centers, academic research institutes, government statistical offices.",
            "work_modes": "Hybrid / Office / Remote",
            "minimum_qualification": "Postgraduate (M.Sc in Statistics / Biostatistics / ISI Degree)",
            "preferred_streams": "Science (PCM) / Commerce with Maths",
            "required_subjects": "Statistics, Mathematics",
            "technical_skills": "Biostatistics, SAS Programming, R, Survival Analysis, Clinical Trial Design, Hypothesis Testing, CDISC Standards (SDTM/ADaM)",
            "soft_skills": "Methodical Precision, Objective Skepticism, Clear Technical Communication",
            "tools": "SAS, R, Python, SPSS, Stata, MedCalc",
            "certifications": "Certified SAS Programmer, Indian Statistical Institute (ISI) Alumnus",
            "experience_level": "Entry-Level to Senior",
            "career_growth": "Highly compensated international trajectory progressing to Principal Biostatistician, Head of Clinical Data Science, or Director of Biostatistics.",
            "internship_roles": "Biostatistics Intern, Clinical Data Intern, Statistical Trainee",
            "entry_level_roles": "Junior Biostatistician, SAS Programmer, Statistical Analyst",
            "average_salary": "₹6 - ₹18 LPA (Indicative range)",
            "salary_indicative": "Entry-Level / SAS Programmer (0-2 yrs): ₹5.5 - 8.5 LPA | Senior Biostatistician (3-6 yrs): ₹11 - 22 LPA | Director of Biostatistics (7+ yrs): ₹25 - 55+ LPA. Indicative figures from Indian Society for Medical Statistics 2024.",
            "future_scope": "High sustained global demand as every drug, vaccine, and clinical medical intervention requires biostatistical validation.",
            "government_opportunities": "Indian Statistical Service (ISS - UPSC), ICMR National Institute of Medical Statistics (NIMS), MoSPI.",
            "private_opportunities": "Novartis, Pfizer, IQVIA, Syneos Health, Parexel, Biocon, Dr. Reddy's Laboratories.",
            "higher_study_options": "Ph.D. in Biostatistics / Statistics from ISI Kolkata or global universities.",
            "entrepreneurship_options": "Contract Research Organization (CRO) specializing in biostatistical analysis for pharmaceutical trials.",
            "source": "Indian Statistical Institute (ISI) / MoSPI",
            "official_url": "https://www.isical.ac.in",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 39, "type": "DIRECT"}, {"course_id": 1, "type": "COMMON"}, {"course_id": 34, "type": "COMMON"}],
            "exams": [{"exam_id": 40, "importance": "PRIMARY"}, {"exam_id": 82, "importance": "PRIMARY"}],
            "routes": [{"title": "Path A: ISI / Premier M.Sc Statistics Route", "type": "COMMON", "steps": "B.Sc Statistics / Maths -> Clear ISI Admission Test or IIT JAM -> M.Stat / M.Sc Statistics -> Learn SAS & CDISC standards -> Clinical Biostatistician."}],
            "ladder": [
                {"stage": "SAS Programmer / Associate Statistician", "exp": "0-2 Years", "desc": "Creates clinical tables, listings, and figures (TLFs) according to Statistical Analysis Plan."},
                {"stage": "Biostatistician", "exp": "2-5 Years", "desc": "Authors Statistical Analysis Plans, calculates sample size power, attends investigator meetings."},
                {"stage": "Senior Principal Biostatistician", "exp": "5-8 Years", "desc": "Interacts directly with US FDA and CDSCO regulators during new drug application (NDA) reviews."},
                {"stage": "Global Head of Biostatistics", "exp": "8+ Years", "desc": "Directs statistical methodology for global pharmaceutical pipelines of multi-billion dollar drugs."}
            ],
            "roadmaps": {
                "Class 10": "Excel in probability, frequency distributions, and arithmetic.",
                "Class 12": "Score top percentiles in Mathematics and Statistics.",
                "Graduation": "Pursue B.Sc in Statistics. Target the Indian Statistical Institute (ISI Kolkata/Delhi) or top university master's programs.",
                "Working Professional": "Earn Base and Advanced SAS certifications, master CDISC standards, or prepare for the UPSC Indian Statistical Service (ISS) exam."
            }
        },
        {
            "title": "Biotechnologist",
            "short_name": "Biotechnologist",
            "slug": "biotechnologist",
            "category": "Science, Research & Mathematics",
            "sub_category": "Biological & Life Sciences",
            "industry": "Biotechnology & Pharmaceuticals",
            "icon": "dna",
            "short_description": "Uses biological systems, cellular processes, and genetic engineering to develop medical drugs, agricultural crops, and industrial enzymes.",
            "description": "Biotechnologists harness the cellular and biomolecular processes of living organisms to create innovative products that heal, feed, and fuel the world. They work in biopharmaceuticals (vaccines, monoclonal antibodies), agricultural biotechnology (GMO crops), and industrial fermentation.",
            "what_they_do": "They clone DNA sequences, engineer recombinant proteins, optimize bioreactor cell cultures, purify monoclonal antibodies, analyze genomic data, and conduct quality control assays.",
            "day_to_day_work": "• Culturing mammalian or bacterial cell lines in automated bioreactors.\n• Performing recombinant DNA cloning, PCR amplification, and gel electrophoresis.\n• Purifying proteins using High-Performance Liquid Chromatography (HPLC).\n• Analyzing biological sequences using bioinformatics tools (BLAST, PyMOL).\n• Ensuring compliance with Good Laboratory Practices (GLP) and biosafety protocols.",
            "work_environment": "Biotechnology R&D laboratories, pharmaceutical pilot plants, cleanrooms.",
            "work_modes": "On-site / Wet Lab",
            "minimum_qualification": "Undergraduate (B.Tech in Biotechnology / B.Sc Biotechnology)",
            "preferred_streams": "Science (PCB / PCM)",
            "required_subjects": "Biology / Biotechnology, Chemistry, Physics",
            "technical_skills": "Recombinant DNA Technology, Cell Culture, Protein Purification (FPLC/HPLC), PCR, Western Blotting, Fermentation, Bioinformatics",
            "soft_skills": "Methodical Precision, Observation, Patience, Collaborative Research",
            "tools": "Bioreactors, HPLC, PCR Thermal Cyclers, Biosafety Cabinets, Gel Documentation Systems",
            "certifications": "CSIR-UGC NET JRF, GATE in Biotechnology, DBT-BET JRF",
            "experience_level": "Entry-Level to Senior",
            "career_growth": "Broad career path progressing to Senior Scientist, Upstream/Downstream Process Lead, or Biotech R&D Director.",
            "internship_roles": "Biotech R&D Intern, Cell Culture Trainee, Quality Control Intern",
            "entry_level_roles": "Junior Research Associate, QC Trainee, Bioprocess Associate",
            "average_salary": "₹4 - ₹12 LPA (Indicative range)",
            "salary_indicative": "Entry-Level (0-2 yrs): ₹3.5 - 5.5 LPA | Senior Biotech Scientist (3-6 yrs): ₹7.5 - 15 LPA | R&D Director / Head of Biologics (7+ yrs): ₹20 - 45+ LPA. Indicative figures from Department of Biotechnology (DBT) 2024.",
            "future_scope": "Surging national growth supported by India's BioE3 Policy 2024 (Biotechnology for Economy, Environment & Employment) targeting a $300 Billion bio-economy by 2030.",
            "government_opportunities": "Department of Biotechnology (DBT), National Institute of Immunology (NII), Centre for Cellular and Molecular Biology (CCMB), ICMR.",
            "private_opportunities": "Biocon, Serum Institute of India, Bharat Biotech, Dr. Reddy's Laboratories, Syngene International, Novozymes.",
            "higher_study_options": "M.Tech / M.Sc in Biotechnology, Ph.D. in Molecular Biology / Genetic Engineering.",
            "entrepreneurship_options": "Bio-manufacturing startup, diagnostic kit manufacturing, industrial enzyme formulation company.",
            "source": "Department of Biotechnology (DBT) / BIRAC",
            "official_url": "https://dbtindia.gov.in",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 6, "type": "DIRECT"}, {"course_id": 27, "type": "COMMON"}, {"course_id": 41, "type": "ALTERNATIVE"}],
            "exams": [{"exam_id": 8, "importance": "PRIMARY"}, {"exam_id": 69, "importance": "PRIMARY"}, {"exam_id": 81, "importance": "PRIMARY"}],
            "routes": [{"title": "Path A: Standard Biotechnology Route", "type": "COMMON", "steps": "Class 12 (PCB/PCM) -> B.Tech / B.Sc Biotechnology -> Clear GAT-B / GATE / CSIR NET -> M.Tech / M.Sc -> Biopharmaceutical Scientist."}],
            "ladder": [
                {"stage": "Research Associate / QC Analyst", "exp": "0-2 Years", "desc": "Maintains cell lines, runs standard ELISA assays, monitors bioreactor parameters."},
                {"stage": "Bioprocess Scientist", "exp": "2-5 Years", "desc": "Optimizes upstream fermentation yields or downstream chromatographic purification."},
                {"stage": "Principal Scientist / Group Leader", "exp": "5-8 Years", "desc": "Leads vaccine or biosimilar drug discovery programs, oversees clinical trial batch manufacturing."},
                {"stage": "VP of Biologics R&D", "exp": "8+ Years", "desc": "Directs corporate biotechnology pipelines, presents new drug dossiers to regulatory authorities."}
            ],
            "roadmaps": {
                "Class 10": "Focus on Biology, genetics, and cell theory.",
                "Class 12": "Choose Biology or Biotechnology with Chemistry.",
                "Graduation": "Complete B.Tech in Biotechnology or B.Sc in Biotechnology with extensive laboratory hands-on training.",
                "Working Professional": "Clear GATE Biotechnology or DBT-BET exam for government funded research fellowships in top biopharma institutes."
            }
        }
    ]

def get_education_careers():
    return [
        {
            "title": "School Teacher (Primary / Secondary)",
            "short_name": "School Teacher (TGT/PRT)",
            "slug": "school-teacher",
            "category": "Education, Teaching & Academia",
            "sub_category": "School Education & Pedagogy",
            "industry": "School Education",
            "icon": "easel",
            "short_description": "Educates school students, designs engaging classroom pedagogies, and shapes the foundational intellectual growth of children.",
            "description": "School Teachers guide the foundational academic, emotional, and social development of students. They teach core subjects (Mathematics, Science, Social Sciences, Languages), design innovative pedagogical lesson plans, conduct assessments, and foster creative curiosity.",
            "what_they_do": "They teach curricula adhering to CBSE, ICSE, or State Boards, create multimedia lesson plans, assess student learning outcomes, manage classroom discipline, and organize extracurricular clubs.",
            "day_to_day_work": "• Delivering interactive classroom lessons using smartboards and hands-on activities.\n• Preparing lesson plans, homework assignments, and assessment rubrics.\n• Evaluating exam answer scripts and providing constructive feedback.\n• Conducting parent-teacher meetings to discuss child progress.\n• Organizing school assemblies, science exhibitions, and annual day events.",
            "work_environment": "Government and private schools, digital smart classrooms, school laboratories.",
            "work_modes": "On-site / School Working Hours",
            "minimum_qualification": "Undergraduate (Graduation + B.Ed / D.El.Ed) + CTET Qualification",
            "preferred_streams": "Any Stream",
            "required_subjects": "Graduation in relevant teaching subject + B.Ed Degree",
            "technical_skills": "Pedagogy, Curriculum Design, Classroom Management, Learning Disability Identification, Formative Assessment, NEP 2020 Pedagogical Framework",
            "soft_skills": "Patience, Deep Compassion, Engaging Storytelling, Encouraging Demeanor",
            "tools": "Smartboards, Google Classroom, Microsoft Teams, Educational Games, Lesson Planners",
            "certifications": "Central Teacher Eligibility Test (CTET) / State TET (STET)",
            "experience_level": "PRT / TGT to Principal",
            "career_growth": "Steady and noble career progression to Senior Subject Teacher (PGT), Vice Principal, or School Principal.",
            "internship_roles": "School Teaching Internship (Integrated in B.Ed - 16 Weeks)",
            "entry_level_roles": "Primary Teacher (PRT), Trained Graduate Teacher (TGT)",
            "average_salary": "₹4 - ₹9 LPA (Central government KVS/NVS scales pay Level 6/7: ₹44,900 - ₹55,000/mo basic + perks)",
            "salary_indicative": "PRT / TGT (Government KVS/NVS): Basic ₹35,400 - ₹44,900 + DA (50%+) + HRA = ~₹55,000 - ₹75,000/month. Private schools range from ₹25,000 - ₹60,000/month depending on city and school tier.",
            "future_scope": "Permanent, irreplaceable noble human profession reinforced by the National Education Policy (NEP 2020).",
            "government_opportunities": "Kendriya Vidyalaya Sangathan (KVS), Navodaya Vidyalaya Samiti (NVS), DSSSB Delhi, State Government Schools via TET.",
            "private_opportunities": "Delhi Public School (DPS), Ryan International, The Mother's International, premium international schools.",
            "higher_study_options": "M.Ed (Master of Education), Post Graduate Teacher (PGT) qualification, Ph.D. in Education.",
            "entrepreneurship_options": "Founding an innovative primary school, educational learning center, ed-tech content platform.",
            "source": "National Council for Teacher Education (NCTE) / CBSE / KVS",
            "official_url": "https://ncte.gov.in",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 48, "type": "DIRECT"}, {"course_id": 1, "type": "COMMON"}, {"course_id": 21, "type": "COMMON"}, {"course_id": 20, "type": "COMMON"}],
            "exams": [{"exam_id": 25, "importance": "PRIMARY"}, {"exam_id": 86, "importance": "PRIMARY"}, {"exam_id": 31, "importance": "ALTERNATIVE"}],
            "routes": [{"title": "Path A: Graduation + B.Ed + CTET Route", "type": "COMMON", "steps": "Graduation in teaching subject (50%+) -> B.Ed Degree (2 yrs) -> Clear CTET (Paper 1 & 2) -> KVS / DSSSB Teacher Recruitment -> Trained Graduate Teacher (TGT)."}],
            "ladder": [
                {"stage": "Trained Graduate Teacher (TGT)", "exp": "0-5 Years", "desc": "Teaches classes 6 to 10 in specific subject, manages homeroom class, organizes school activities."},
                {"stage": "Post Graduate Teacher (PGT)", "exp": "5-10 Years", "desc": "Teaches classes 11 and 12 board students, prepares pupils for competitive entrances."},
                {"stage": "Vice Principal / Academic Coordinator", "exp": "10-15 Years", "desc": "Manages academic timetables, teacher development workshops, school examination administration."},
                {"stage": "School Principal / Director of Education", "exp": "15+ Years", "desc": "Heads entire institution, leads school vision, board affiliation, and community relations."}
            ],
            "roadmaps": {
                "Class 10": "Demonstrate passion for learning and helping classmates understand difficult concepts.",
                "Class 12": "Score well in Class 12 in the subject you wish to teach (Science, Arts, or Commerce).",
                "Graduation": "Complete graduation in your teaching discipline. Enroll in a 2-year NCTE-recognized B.Ed program with school teaching internship.",
                "Working Professional": "Clear CTET (Central Teacher Eligibility Test) Paper 1 & 2 conducted by CBSE, and prepare for KVS/NVS recruitments."
            }
        },
        {
            "title": "College / University Assistant Professor",
            "short_name": "Assistant Professor",
            "slug": "college-professor",
            "category": "Education, Teaching & Academia",
            "sub_category": "Higher Education & Academic Research",
            "industry": "Higher Education & Universities",
            "icon": "mortarboard",
            "short_description": "Teaches undergraduate and postgraduate university students while conducting original academic research and publishing scholarship.",
            "description": "Assistant Professors in colleges and universities educate higher education students and advance human knowledge through specialized research. They deliver university lectures, mentor master's and Ph.D. dissertations, author academic textbooks, and secure research grants.",
            "what_they_do": "They teach university degree courses, design academic syllabi, conduct advanced scholarly research, write research papers in peer-reviewed journals, and evaluate university examinations.",
            "day_to_day_work": "• Delivering undergraduate and postgraduate university lectures.\n• Guiding Ph.D. scholars and master's students on dissertation research.\n• Writing scholarly papers for publication in Scopus / Web of Science indexed journals.\n• Managing research grants funded by UGC, DST, or CSIR.\n• Participating in university academic council meetings and curriculum reviews.",
            "work_environment": "Central and state university campuses, premier colleges, research seminar halls.",
            "work_modes": "On-site / Campus Academic Schedule",
            "minimum_qualification": "Postgraduate (Master's 55%+) + UGC NET / CSIR NET Qualification or Ph.D.",
            "preferred_streams": "Any Stream",
            "required_subjects": "Master's degree in relevant academic discipline",
            "technical_skills": "Higher Education Pedagogy, Academic Research Methodology, Scholarly Writing, Grant Proposal Writing, Dissertation Mentorship",
            "soft_skills": "Intellectual Eloquence, Scholarly Integrity, Engaging Lecture Delivery, Mentorship",
            "tools": "Learning Management Systems (Moodle, Blackboard), SPSS, Zotero, LaTeX, JSTOR",
            "certifications": "UGC NET / CSIR NET, Ph.D. under UGC Regulations 2018",
            "experience_level": "Assistant Professor to Senior Professor / Vice Chancellor",
            "career_growth": "Highly revered academic progression to Associate Professor, Full Professor, Dean, and Vice-Chancellor.",
            "internship_roles": "Graduate Teaching Assistant (GTA) during Ph.D.",
            "entry_level_roles": "Assistant Professor (Academic Level 10)",
            "average_salary": "₹8 - ₹20 LPA (Official 7th CPC UGC Pay Scale: Entry Basic ₹57,700/mo + DA + HRA)",
            "salary_indicative": "Assistant Professor (Level 10): Basic ₹57,700 + DA (50%+) + HRA = ~₹95,000/mo gross. Associate Professor (Level 13A): Basic ₹1,31,400. Full Professor (Level 14): Basic ₹1,44,200. Vice-Chancellor: Fixed ₹2,10,000/mo.",
            "future_scope": "Growing rapidly as hundreds of new central universities, IITs, IIMs, and private universities expand higher education capacity.",
            "government_opportunities": "Central Universities (DU, JNU, BHU, Hyderabad), State Universities, National Institutes (IITs, NITs, IIMs).",
            "private_opportunities": "Ashoka University, BITS Pilani, O.P. Jindal Global University, Manipal, Amity, Shiv Nadar University.",
            "higher_study_options": "Post-Doctoral Fellowships, D.Litt / D.Sc degrees.",
            "entrepreneurship_options": "Academic publishing imprint, university research think tank, educational consulting.",
            "source": "University Grants Commission (UGC) / Ministry of Education",
            "official_url": "https://www.ugc.gov.in",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 24, "type": "DIRECT"}, {"course_id": 34, "type": "DIRECT"}, {"course_id": 46, "type": "DIRECT"}, {"course_id": 47, "type": "DIRECT"}],
            "exams": [{"exam_id": 10, "importance": "PRIMARY"}, {"exam_id": 80, "importance": "PRIMARY"}],
            "routes": [{"title": "Path A: Master's + UGC NET + Ph.D. Route", "type": "COMMON", "steps": "Bachelor's -> Master's degree (55%+) in relevant discipline -> Clear UGC NET / CSIR NET -> Complete Ph.D. with published research -> University Assistant Professor."}],
            "ladder": [
                {"stage": "Assistant Professor (Level 10-12)", "exp": "0-8 Years", "desc": "Teaches UG/PG courses, conducts Ph.D. research, publishes 4+ peer-reviewed papers."},
                {"stage": "Associate Professor (Level 13A)", "exp": "8-12 Years", "desc": "Directs academic research vertical, mentors doctoral scholars, leads grant projects."},
                {"stage": "Professor (Level 14/15)", "exp": "12+ Years", "desc": "Heads university academic department, authors seminal books, shapes academic curricula."},
                {"stage": "Dean / Vice-Chancellor", "exp": "20+ Years", "desc": "Academic and executive head of entire university, appointed by the President / Governor."}
            ],
            "roadmaps": {
                "Class 10": "Demonstrate genuine intellectual curiosity and love for reading scholarly books.",
                "Class 12": "Score well in board exams and select the academic discipline you are truly passionate about.",
                "Graduation": "Complete Bachelor's and Master's with top academic marks (minimum 55% for UGC criteria). Prepare for UGC NET.",
                "Working Professional": "Clear UGC NET JRF to secure funded doctoral fellowship, enroll in Ph.D. program, and publish research papers."
            }
        }
    ]

print("Catalog builder part 5 ready.")
