"""
scripts/catalog_builder_part3.py
Authentic occupational profiles for Government, Business, Science, Education, Media,
Design, Agriculture, Aviation, and Social Sciences.
"""

def get_government_remaining():
    return [
        {
            "title": "IFS Officer (Indian Foreign Service)",
            "short_name": "IFS Diplomat",
            "slug": "ifs-officer",
            "category": "Government, Defence & Civil Services",
            "sub_category": "Diplomacy & International Relations",
            "industry": "Ministry of External Affairs / Government of India",
            "icon": "globe-americas",
            "short_description": "Represents India's diplomatic, strategic, and economic interests in foreign embassies, high commissions, and the United Nations.",
            "description": "Indian Foreign Service (IFS) officers represent the sovereign diplomatic corps of India. They negotiate bilateral and multilateral treaties, protect Indian citizens abroad, promote Indian trade and culture, and advance national interests at global forums like the UN.",
            "what_they_do": "They manage foreign relations at Indian Embassies worldwide, negotiate international agreements on trade, climate, and security, coordinate high-level state visits, and manage consular and visa operations.",
            "day_to_day_work": "• Drafting diplomatic cables and geopolitical assessment reports for New Delhi.\n• Negotiating bilateral treaty terms with foreign ministry officials.\n• Assisting Indian diaspora community and coordinating emergency evacuations.\n• Facilitating international trade and commercial partnerships for Indian businesses.\n• Preparing speaking points and policy briefs for Minister of External Affairs.",
            "work_environment": "Indian Embassies worldwide, Ministry of External Affairs (Jawaharlal Nehru Bhawan, New Delhi), United Nations.",
            "work_modes": "Diplomatic Postings Abroad (typically 3-year rotations) / New Delhi MEA Headquarters",
            "minimum_qualification": "Undergraduate (Any Recognized Degree)",
            "preferred_streams": "Any Stream (Humanities / International Relations advantageous)",
            "required_subjects": "Graduation in any discipline",
            "technical_skills": "Diplomacy, International Law, Geopolitics, Foreign Languages (Assigned Compulsory Foreign Language), Protocol, Negotiation",
            "soft_skills": "Supreme Cultural Tact, Emotional Poise, Executive Elegance, National Patriotism",
            "tools": "Secure Diplomatic Communications, Consular Visa Systems, MEA Portals",
            "certifications": "Selected through UPSC Civil Services Examination (CSE), Trained at Sushma Swaraj Institute of Foreign Service (SSIFS)",
            "experience_level": "Third Secretary to Foreign Secretary / Ambassador",
            "career_growth": "Apex diplomatic trajectory progressing to Ambassador of India, Permanent Representative to the UN, or Foreign Secretary of India.",
            "internship_roles": "SSIFS Diplomatic Training & Foreign Language Posting (2 Years)",
            "entry_level_roles": "Third Secretary / Under Secretary (MEA)",
            "average_salary": "₹12 - ₹30 LPA (Official 7th CPC Pay Scale + Substantial Foreign Allowances in foreign currency covering housing, staff, education)",
            "salary_indicative": "Basic Pay: Level 10 (₹56,100) to Level 17 (₹2,25,000) + Foreign Allowance (typically $3,000 - $8,000/month depending on cost of living in posted country). Fully furnished diplomatic residence provided.",
            "future_scope": "Growing global stature as India's geopolitical voice in the Global South, G20, BRICS, and Quad expands.",
            "government_opportunities": "UPSC Civil Services Examination (Selected in top ranks alongside IAS).",
            "private_opportunities": "Not applicable (Sovereign Diplomatic Service). Post-retirement: Strategic think tanks, international corporate boards.",
            "higher_study_options": "Diplomatic Academy Specializations, Master's in International Relations under MEA sponsorship.",
            "entrepreneurship_options": "Not applicable (Civil Service).",
            "source": "Ministry of External Affairs (MEA) / UPSC / SSIFS",
            "official_url": "https://www.mea.gov.in",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 22, "type": "COMMON"}, {"course_id": 20, "type": "COMMON"}, {"course_id": 21, "type": "COMMON"}],
            "exams": [{"exam_id": 1, "importance": "PRIMARY"}],
            "routes": [{"title": "Path A: UPSC Civil Services Examination Route", "type": "COMMON", "steps": "Graduation in any stream -> Clear UPSC CSE (Rank typically within top 100-150) -> Allotted Indian Foreign Service -> SSIFS Training + Foreign Language Learning -> First posting abroad as Third Secretary."}],
            "ladder": [
                {"stage": "Third / Second Secretary", "exp": "0-4 Years", "desc": "Mastering compulsory foreign language, manages consular and visa operations abroad."},
                {"stage": "First Secretary / Counsellor", "exp": "4-10 Years", "desc": "Heads political or commercial division in embassy, leads trade and bilateral talks."},
                {"stage": "Minister / Deputy Chief of Mission (DCM)", "exp": "10-20 Years", "desc": "Second-in-command of major embassy (e.g. Washington, London, Beijing)."},
                {"stage": "Ambassador / Permanent Representative to UN / Foreign Secretary", "exp": "20+ Years", "desc": "Appointed by President of India as Ambassador Extraordinary and Plenipotentiary or Foreign Secretary."}
            ],
            "roadmaps": {
                "Class 10": "Read world history, geography, and develop passion for international affairs.",
                "Class 12": "Excel in humanities, commerce, or science. Learn an international language if interested.",
                "Graduation": "Complete graduation with deep interest in geopolitics, Indian foreign policy, and world history. Prepare for UPSC CSE.",
                "Working Professional": "Clear UPSC CSE with top rank and commit to serving India on the global diplomatic stage."
            }
        },
        {
            "title": "State Civil Services Officer (SDM / DSP)",
            "short_name": "State PSC Officer",
            "slug": "state-civil-services-officer",
            "category": "Government, Defence & Civil Services",
            "sub_category": "State Public Administration & Policing",
            "industry": "State Governments / Public Administration",
            "icon": "award-fill",
            "short_description": "Executes state-level administrative governance, revenue collection, and law enforcement as Sub-Divisional Magistrate or DSP.",
            "description": "State Civil Services officers (selected through State Public Service Commissions like UPPSC, BPSC, MPPSC, MPSC, RPSC) are the executive bedrock of state administration. They manage tehsils and sub-divisions, implement state welfare schemes, and maintain public order.",
            "what_they_do": "They preside over sub-divisional revenue courts as SDM, command police circles as Deputy Superintendent of Police (DSP), implement rural development schemes, and enforce state regulations.",
            "day_to_day_work": "• Hearing land revenue and demarcation disputes in SDM court.\n• Inspecting fair price ration shops and primary health centers.\n• Overseeing law and order bandobast during elections and festivals.\n• Coordinating relief during droughts, floods, or local crop damage.\n• Implementing state welfare grants and beneficiary disbursement.",
            "work_environment": "Tehsil offices, Sub-Divisional Magistrate courts, District Collectorates, Police Sub-Divisions.",
            "work_modes": "On-site / Field Inspections / Government Office",
            "minimum_qualification": "Undergraduate (Any Recognized Degree)",
            "preferred_streams": "Any Stream",
            "required_subjects": "Graduation in any discipline",
            "technical_skills": "State Land Revenue Code, Criminal Procedure, Public Welfare Administration, State Geography & Culture, Disaster Relief",
            "soft_skills": "Public Empathy, Decisive Leadership, Local Language Fluency, Integrity",
            "tools": "State Land Records Portal (Bhulekh), e-District Portal, CCTNS",
            "certifications": "Selected through State Public Service Commission (State PCS Examination)",
            "experience_level": "Entry-Level to Senior Administrative Officer",
            "career_growth": "Direct progression into Additional District Magistrate (ADM), District Magistrate / SSP, and induction into IAS/IPS through promotion quota.",
            "internship_roles": "State Administrative Academy Training (1 Year)",
            "entry_level_roles": "Sub-Divisional Magistrate (SDM), Deputy Collector, Deputy Superintendent of Police (DSP), Block Development Officer (BDO)",
            "average_salary": "₹8 - ₹18 LPA (State Pay Scale Pay Band-3 / Level 10 + Government Residence, Official Vehicle)",
            "salary_indicative": "Deputy Collector / DSP: Basic ₹56,100 + DA + HRA + State perks. Equivalent to Central Pay Level 10. Promotional induction into IAS/IPS after 12-18 years of meritorious service.",
            "future_scope": "Permanent, highly prestigious administrative office carrying direct local executive authority across millions of citizens in every state.",
            "government_opportunities": "UPPSC, MPPSC, BPSC, MPSC, RPSC, TNPSC, WBPSC, KPSC State Civil Services Examinations.",
            "private_opportunities": "Not applicable (State Civil Service).",
            "higher_study_options": "In-Service State Administrative Training, Master's in Public Policy.",
            "entrepreneurship_options": "Not applicable (State Civil Service).",
            "source": "State Public Service Commissions (UPPSC / BPSC / MPPSC)",
            "official_url": "https://uppsc.up.nic.in",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 20, "type": "COMMON"}, {"course_id": 22, "type": "COMMON"}, {"course_id": 23, "type": "COMMON"}, {"course_id": 9, "type": "COMMON"}],
            "exams": [{"exam_id": 87, "importance": "PRIMARY"}, {"exam_id": 88, "importance": "PRIMARY"}, {"exam_id": 89, "importance": "PRIMARY"}, {"exam_id": 90, "importance": "PRIMARY"}, {"exam_id": 91, "importance": "PRIMARY"}],
            "routes": [{"title": "Path A: State Public Service Commission (PCS) Route", "type": "COMMON", "steps": "Graduation in any stream -> Clear State PCS Prelims -> Clear State PCS Mains (including State GK) -> Interview -> State Administrative Training -> Deputy Collector / DSP."}],
            "ladder": [
                {"stage": "Deputy Collector / SDM / DSP", "exp": "0-5 Years", "desc": "Commands sub-division or police circle, manages local revenue and law enforcement."},
                {"stage": "Additional District Magistrate (ADM) / Additional SP", "exp": "5-12 Years", "desc": "Directs district revenue, civil supplies, or district police operations."},
                {"stage": "District Magistrate / SSP (Promoted to IAS / IPS)", "exp": "12-20 Years", "desc": "Inducted into the Indian Administrative / Police Service by President of India, heads full district."},
                {"stage": "Special Secretary / Joint Secretary to State Government", "exp": "20+ Years", "desc": "Leads state government departments and directs state welfare policies."}
            ],
            "roadmaps": {
                "Class 10": "Learn state history, geography, and master the regional state language alongside English.",
                "Class 12": "Complete Class 12 in any stream of your choice.",
                "Graduation": "Complete graduation. Study General Studies (History, Polity, Economy) along with deep study of the state's specific history, culture, and economy.",
                "Working Professional": "Prepare for State PSC examination with extensive answer-writing practice and state-specific mock tests."
            }
        },
        {
            "title": "Central Excise & Customs Inspector",
            "short_name": "GST & Customs Inspector",
            "slug": "central-excise-customs-inspector",
            "category": "Government, Defence & Civil Services",
            "sub_category": "Revenue Enforcement & Customs",
            "industry": "Ministry of Finance / CBIC",
            "icon": "shield-lock",
            "short_description": "Enforces Goods & Services Tax (GST), inspects international maritime and air cargo, and combats contraband smuggling.",
            "description": "Inspectors of Central GST and Customs (selected through the SSC CGL examination) serve under the Central Board of Indirect Taxes and Customs (CBIC). They audit manufacturing units, inspect international shipments at seaports and airports, and combat tax evasion and smuggling.",
            "what_they_do": "They conduct preventive anti-evasion raids, examine import-export cargo at ports, manage anti-smuggling operations at international airports, inspect bonded warehouses, and audit GST returns.",
            "day_to_day_work": "• Examining import/export shipping bills and physical cargo at container freight stations.\n• Operating airport international passenger baggage scanners and profiling suspicious travelers.\n• Conducting search and seizure operations at tax-evading commercial premises.\n• Verifying input tax credit (ITC) claims on the GST portal.\n• Drafting seizure memos and panchnamas for confiscated goods.",
            "work_environment": "International seaports, international airports, GST Commissionerates, preventive intelligence offices.",
            "work_modes": "On-site / Port / Airport Shift Duties / Field Operations",
            "minimum_qualification": "Undergraduate (Any Recognized Degree) + Physical Fitness Standards",
            "preferred_streams": "Any Stream",
            "required_subjects": "Graduation in any discipline",
            "technical_skills": "Customs Act 1962, CGST Act 2017, Anti-Smuggling Procedures, Cargo Inspection, Search & Seizure Law, Physical Fitness",
            "soft_skills": "Alertness, Moral Integrity, Physical Resilience, Decisiveness Under Pressure",
            "tools": "Container Scanners, ICES (Indian Customs EDI System), GSTN Portals, Narcotics Test Kits",
            "certifications": "Selected through SSC Combined Graduate Level (SSC CGL) Examination, Trained at NACIN",
            "experience_level": "Inspector to Commissioner of Customs & GST",
            "career_growth": "Direct progression into Superintendent of GST/Customs, Assistant Commissioner (IRS promotion quota), and Joint Commissioner.",
            "internship_roles": "NACIN Academy Training (3 Months)",
            "entry_level_roles": "Inspector (Central GST), Inspector (Preventive Officer), Inspector (Examiner)",
            "average_salary": "₹7 - ₹14 LPA (Official 7th CPC: Pay Level 7 Basic ₹44,900 + DA + HRA + Uniform Allowance)",
            "salary_indicative": "Inspector (Pay Level 7): Basic ₹44,900 + DA (50%+) + HRA (30% in X cities) = ~₹75,000 - 85,000/month gross. Regular time-bound promotions to Superintendent (Level 8/9).",
            "future_scope": "Permanent, powerful sovereign enforcement authority at the frontline of India's multi-trillion-dollar foreign trade and GST collection.",
            "government_opportunities": "Staff Selection Commission Combined Graduate Level (SSC CGL) Examination.",
            "private_opportunities": "Not applicable (Central Government Service). Post-retirement: Customs broker compliance, corporate indirect tax consulting.",
            "higher_study_options": "Departmental exams for promotion to Assistant Commissioner (IRS Cadre).",
            "entrepreneurship_options": "Not applicable (Central Government Service).",
            "source": "Staff Selection Commission (SSC) / CBIC / NACIN",
            "official_url": "https://ssc.gov.in",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 16, "type": "COMMON"}, {"course_id": 20, "type": "COMMON"}, {"course_id": 9, "type": "COMMON"}],
            "exams": [{"exam_id": 2, "importance": "PRIMARY"}, {"exam_id": 56, "importance": "PRIMARY"}],
            "routes": [{"title": "Path A: SSC CGL Examination Route", "type": "COMMON", "steps": "Graduation in any discipline -> Meet physical standards (Walking, Cycling, Height/Chest) -> Clear SSC CGL Tier 1 & Tier 2 -> NACIN Training -> Appointed as Inspector of Central GST / Preventive Officer."}],
            "ladder": [
                {"stage": "Inspector (GST / Preventive Officer / Examiner)", "exp": "0-6 Years", "desc": "Inspects cargo, conducts anti-evasion raids, verifies input tax credits."},
                {"stage": "Superintendent of Central GST / Customs", "exp": "6-15 Years", "desc": "Gazetted Officer (Group B). Adjudicates tax demands, manages airport customs shifts."},
                {"stage": "Assistant Commissioner of Customs & GST (IRS Cadre)", "exp": "15-20 Years", "desc": "Group A Indian Revenue Service cadre, heads entire customs division or GST circle."},
                {"stage": "Joint Commissioner / Commissioner", "exp": "20+ Years", "desc": "Directs full seaport or airport customs commissionerate."}
            ],
            "roadmaps": {
                "Class 10": "Build speed and accuracy in basic arithmetic, algebra, and English comprehension.",
                "Class 12": "Complete Class 12 in any stream. Maintain good health and physical fitness.",
                "Graduation": "Complete graduation. Dedicate focused preparation for SSC CGL (Quantitative Aptitude, Reasoning, English, General Awareness, and Computer Knowledge).",
                "Working Professional": "Practice full-length SSC CGL computer-based mock tests with negative marking awareness."
            }
        }
    ]

print("Catalog builder part 3 ready.")
