"""
scripts/catalog_expanded_part6.py
Domain Q: Sports & Fitness (4 careers)
Domain R: Hospitality & Tourism (4 careers)
Domain S: Aviation (3 careers)
Domain T: Maritime & Shipping (3 careers)
Domain U: Logistics & Supply Chain (3 careers)
Domain V: Architecture & Built Environment (3 careers)
"""

def get_sports_and_fitness_careers():
    return [
        {
            "title": "Sports Physiotherapist",
            "short_name": "Sports Physio",
            "slug": "sports-physiotherapist",
            "category": "Healthcare & Medical Sciences",
            "sub_category": "Sports Medicine & Rehabilitation",
            "industry": "Professional Sports, Athletic Teams & Sports Medicine",
            "icon": "activity",
            "short_description": "Prevents, assesses, treats, and rehabilitates athletic injuries for professional sportspersons.",
            "description": "Sports Physiotherapists are specialized healthcare professionals who work with professional athletes, national sports teams (cricket, football, athletics, hockey), and sports academies. They specialize in sports injury prevention, emergency pitch-side trauma management, biomechanical movement analysis, and rapid athletic return-to-play rehabilitation.",
            "what_they_do": "They manage acute injuries on the sports pitch (ACL tears, hamstring strains, shoulder dislocations), design athlete conditioning routines, perform dry needling and manual therapy, and optimize athletic biomechanics.",
            "day_to_day_work": "• Providing pitch-side emergency medical management during live professional matches.\n• Conducting pre-season musculoskeletal screenings and biomechanical movement assessments.\n• Designing progressive return-to-sport rehabilitation protocols following orthopedic surgeries.\n• Applying therapeutic sports taping, dry needling, and joint mobilization techniques.\n• Monitoring athlete fatigue biomarkers and recovery modalities (cryotherapy, compression).",
            "work_environment": "Professional sports stadiums, national sports camps (SAI / BCCI), sports medicine clinics, team travel tours.",
            "work_modes": "On-site / Pitch-side / Clinic / Touring",
            "minimum_qualification": "Postgraduate (MPT in Sports Physiotherapy / Sports Medicine - 2 Years after BPT)",
            "preferred_streams": "Science (PCB)",
            "required_subjects": "Physiotherapy, Biomechanics, Exercise Physiology, Anatomy",
            "technical_skills": "Acute Sports Trauma Care, Pitch-side Emergency Protocols, Biomechanical Motion Analysis, Kinesiology Taping, Dry Needling, Return-to-Play Testing",
            "soft_skills": "Rapid Calmness Under Live Stadium Pressure, Athlete Empathy, Team Collaboration, High Energy",
            "tools": "Kinesiology Tape, Isokinetic Dynamometers, Force Plates, Cryotherapy Chambers, Ultrasound Therapy Units",
            "certifications": "Indian Association of Physiotherapists (IAP) Sports Specialty Certification, BLS / Sports First Aid",
            "experience_level": "Entry to Head Team Physiotherapist",
            "career_growth": "Advance to Senior Team Physio (IPL / ISL franchises), National Team Head Physiotherapist (BCCI / SAI), or Sports Clinic Director.",
            "internship_roles": "Sports Team Physio Intern, SAI Camp Trainee",
            "entry_level_roles": "Junior Sports Physiotherapist, Academy Physio, Rehab Associate",
            "average_salary": "₹5.5 - ₹18.0+ LPA (Indicative range)",
            "salary_indicative": "Academy / Clinic Physio: ₹5.5 - 8.5 LPA | Franchise League Team Physio (IPL / ISL / PKL): ₹12 - 25+ LPA | National Team Head Physio: ₹25 - 50+ LPA. Indicative figures from professional sports league contracts.",
            "future_scope": "Explosive growth with India's booming commercial sports leagues (IPL, WPL, ISL, Pro Kabaddi, Ultimate Kho Kho) and Olympic training schemes (TOPS).",
            "government_opportunities": "Sports Authority of India (SAI), National Centres of Excellence (NCOE), Armed Forces Sports Medicine Division, Indian Railways Sports Promotion Board.",
            "private_opportunities": "BCCI, IPL Franchises (CSK, MI, RCB), ISL Football Clubs, Reliance Foundation Youth Sports, Inspire Institute of Sport (IIS Bellary).",
            "higher_study_options": "Ph.D. in Sports Biomechanics, International Fellowships in Sports Rehabilitation.",
            "entrepreneurship_options": "Founding a high-performance sports rehabilitation center or private athletic performance lab.",
            "source": "Sports Authority of India (SAI) / Indian Association of Physiotherapists (IAP)",
            "official_url": "https://sportsauthorityofindia.nic.in",
            "verification_status": "VERIFIED",
            "is_lesser_known": False,
            "career_family": "Sports & Movement",
            "interest_clusters": "Sports, Healthcare, Helping, Science, Hands-on",
            "work_style": "Clinic, Outdoor, Travel",
            "reality_check": "High-pressure, live-televised environment: Making split-second decisions on whether a star player can continue playing.\nInvolves grueling travel schedules touring with sports teams across different cities and time zones.\nRequires a formal Bachelor of Physiotherapy (BPT - 4.5 yrs) followed by an MPT in Sports; cannot be entered through casual gym fitness courses.",
            "next_steps": "Pass Class 12 with Physics, Chemistry, and Biology.\nComplete the 4.5-year Bachelor of Physiotherapy (BPT) including 6 months of hospital internship.\nComplete a 2-year Master of Physiotherapy (MPT) in Sports Physiotherapy and apprentice with professional sports teams.",
            "courses": [{"course_id": 51, "type": "PRIMARY"}],
            "exams": [],
            "routes": [{"title": "Path A: Standard Sports Physio Route", "type": "PRIMARY", "steps": "12th (PCB) -> BPT (4.5 yrs) -> Hospital Internship -> MPT Sports (2 yrs) -> Sports Academy Physio -> National Team Physio."}],
            "ladder": [
                {"stage": "Academy / Junior Team Physio", "exp": "0-3 Years", "desc": "Manages youth athletes, provides basic sports massage and taping, monitors rehab exercises."},
                {"stage": "Franchise League Team Physiotherapist", "exp": "3-8 Years", "desc": "Leads pitch-side trauma, designs recovery protocols, coordinates player return-to-play with coaches."},
                {"stage": "Head of Sports Medicine / National Lead", "exp": "8+ Years", "desc": "Directs high-performance sports medicine for national Olympic contingents or national cricket boards."}
            ]
        },
        {
            "title": "High-Performance Sports Coach",
            "short_name": "Sports Coach",
            "slug": "high-performance-sports-coach",
            "category": "Education, Teaching & Academia",
            "sub_category": "Sports Coaching & Performance",
            "industry": "Professional Sports, Coaching Academies & National Federations",
            "icon": "trophy",
            "short_description": "Trains athletes, develops tactical game plans, and guides champions to national and Olympic podiums.",
            "description": "High-Performance Sports Coaches develop the technical skills, tactical decision-making, physical conditioning, and mental resilience of athletes competing at state, national, and Olympic levels. Certified through the Netaji Subhas National Institute of Sports (NSNIS Patiala) or international sports federations, they design periodized training regimens and direct competitive game strategies.",
            "what_they_do": "They analyze video footage of opponent tactics, conduct tactical skill drills, plan annual training periodization, mentor athletes through losses, and manage sports teams from sidelines.",
            "day_to_day_work": "• Running 5 AM morning technical drills, footwork, and sports-specific tactical sessions.\n• Analyzing game video telemetry to identify mechanical and strategic flaws in athlete performance.\n• Designing periodized training macrocycles (preparation, pre-competition, peak competition, transition).\n• Calling tactical tactical timeouts and substituting players during live matches.\n• Instilling mental resilience, discipline, and sportsmanship in competitive squads.",
            "work_environment": "Sports academies, outdoor stadiums, indoor training courts, national sports camps.",
            "work_modes": "On-site / Court / Field / Travel",
            "minimum_qualification": "Diploma in Sports Coaching from NSNIS Patiala (1 Year) or Bachelor of Physical Education (B.P.Ed)",
            "preferred_streams": "Any Stream (Personal competitive sports participation background essential)",
            "required_subjects": "Sports Science, Kinesiology, Coaching Pedagogy",
            "technical_skills": "Tactical Game Strategy, Periodization Planning, Biomechanical Video Analysis, Skill Acquisition Drills, Sports Psychology Basics, Anti-Doping Regulations (WADA/NADA)",
            "soft_skills": "Inspirational Leadership, Tough-Love Mentorship, Tactical Acumen, Clear Communication Under Fire",
            "tools": "Dartfish Video Analysis, Stopwatches, Agility Ladders, Cones, Ball Launching Machines, Tactical Boards",
            "certifications": "NSNIS Diploma in Sports Coaching, AFC / FIFA / ICC / BWF Coaching Licenses",
            "experience_level": "Grassroots Coach to National Head Coach",
            "career_growth": "Advance to Senior Academy Coach, State Team Coach, National Head Coach, or Olympic High-Performance Director.",
            "internship_roles": "Assistant Academy Coach, SAI Coaching Trainee",
            "entry_level_roles": "Junior Sports Coach, Assistant Coach, School Sports Instructor",
            "average_salary": "₹4.5 - ₹16.0+ LPA (Indicative range)",
            "salary_indicative": "Grassroots Academy Coach: ₹4.5 - 7 LPA | SAI / State Government Coach (Pay Level 7-10): ₹7 - 12 LPA | National / Franchise Head Coach: ₹15 - 40+ LPA plus performance bonuses for medal wins. Indicative figures from SAI and national sports federations.",
            "future_scope": "Growing exponentially through government initiatives like Khelo India, target Olympic podium funding, and commercial sports academies.",
            "government_opportunities": "Sports Authority of India (SAI Coach Cadre), State Sports Directorates, Indian Railways, Services Sports Control Board.",
            "private_opportunities": "Pullela Gopichand Badminton Academy, Mary Kom Boxing Academy, Tata Football Academy, JSW Sports, Professional Sports Clubs.",
            "higher_study_options": "Master of Sports Coaching (M.Sc Sports Coaching at NSNIS Patiala), International Elite Coaching Diplomas.",
            "entrepreneurship_options": "Founding an independent sports training academy or private athletic talent development facility.",
            "source": "Netaji Subhas National Institute of Sports (NSNIS Patiala) / SAI",
            "official_url": "https://nsnis.org",
            "verification_status": "VERIFIED",
            "is_lesser_known": False,
            "career_family": "Sports & Movement",
            "interest_clusters": "Sports, Outdoor, Leadership, Teaching, People",
            "work_style": "Outdoor, Stadium, Travel",
            "reality_check": "Demands early morning hours (often on the field by 5:00 AM) and working weekends/holidays during sports seasons.\nCoaching results are stark and public: Winning medals brings acclaim, while losing streaks bring intense scrutiny.\nRequires personal experience as a competitive player at district, state, or national levels.",
            "next_steps": "Actively compete in your chosen sport at district, university, or state championships.\nEarn a Bachelor of Physical Education (B.P.Ed) or any Bachelor's degree.\nAppear for the entrance examination for the prestigious 1-year Diploma in Sports Coaching at NSNIS Patiala.",
            "courses": [{"course_id": 60, "type": "PRIMARY"}],
            "exams": [],
            "routes": [{"title": "Path A: NSNIS Coaching Route", "type": "PRIMARY", "steps": "Competitive Athlete Background -> Graduation / B.P.Ed -> NSNIS Patiala Diploma in Coaching -> SAI / Academy Coach -> National Coach."}],
            "ladder": [
                {"stage": "Assistant Academy Coach", "exp": "0-3 Years", "desc": "Conducts warm-ups, feeds practice balls, teaches foundational fundamentals to young batches."},
                {"stage": "High-Performance Coach", "exp": "3-8 Years", "desc": "Coaches state/national-level competitors, plans tactical game strategies, travels with athletes to tournaments."},
                {"stage": "National Head Coach / Director of Coaching", "exp": "8+ Years", "desc": "Leads national team at Asian Games and Olympics, shapes national coaching curriculum, awarded Dronacharya Award."}
            ]
        }
    ]

def get_hospitality_and_tourism_careers():
    return [
        {
            "title": "Executive Chef / Head Culinary Artist",
            "short_name": "Executive Chef",
            "slug": "executive-chef-culinary",
            "category": "Hospitality & Tourism",
            "sub_category": "Culinary Arts & Food Production",
            "industry": "Fine Dining, Luxury Hotels & Gastronomy",
            "icon": "fire",
            "short_description": "Commands professional commercial kitchens, designs gourmet menus, and leads fine-dining culinary arts.",
            "description": "Executive Chefs (Head Chefs) are the master culinary leaders of luxury hotel dining, Michelin-starred restaurants, and high-end catering. They conceive innovative culinary recipes, source artisanal seasonal ingredients, manage food costs and inventory, enforce strict kitchen sanitation (HACCP), and orchestrate brigade-style commercial kitchens under extreme dinner rush pressure.",
            "what_they_do": "They design seasonal restaurant menus, create signature gourmet recipes, oversee the kitchen brigade (sous chefs, chef de parties), manage multi-lakh food budgets, and inspect every plate before it leaves the kitchen pass.",
            "day_to_day_work": "• Inspecting fresh daily deliveries of seafood, meats, exotic vegetables, and spices.\n• Conceptualizing and tasting new seasonal tasting menu dishes with the sous chef.\n• Directing the fast-paced dinner service from the kitchen pass (calling orders, plating standards).\n• Calculating food cost percentages and optimizing kitchen recipe yields to maintain profitability.\n• Enforcing strict HACCP food safety standards and kitchen commercial hygiene.",
            "work_environment": "Commercial restaurant kitchens, luxury hotel food production areas, private dining ateliers.",
            "work_modes": "On-site / Kitchen / Cooking Floor",
            "minimum_qualification": "Undergraduate (BHM / B.Sc in Hospitality & Hotel Administration / Culinary Arts - 3-4 Years)",
            "preferred_streams": "Any Stream",
            "required_subjects": "Food Production, Culinary Arts, Kitchen Management, Food Safety",
            "technical_skills": "Classical French & Indian Culinary Techniques, Menu Engineering, Food Cost Control, Kitchen Brigade Leadership, Molecular Gastronomy, HACCP Food Safety Compliance",
            "soft_skills": "Palate Refinement, Kitchen Leadership, Composure in High Heat, Relentless Perfectionism",
            "tools": "Chef's Knives, Combi-Steam Ovens, Sous-Vide Circulators, Blast Chillers, Commercial Induction Woks",
            "certifications": "NCHMCT Degree, Indian Federation of Culinary Associations (IFCA) Certification, HACCP Certified",
            "experience_level": "Commis Chef to Executive Chef",
            "career_growth": "Advance from Commis to Demi Chef de Partie, Chef de Partie, Sous Chef, Executive Sous Chef, and Executive Chef.",
            "internship_roles": "Kitchen Industrial Trainee, Commis Trainee",
            "entry_level_roles": "Commis III, Trainee Chef, Junior Line Cook",
            "average_salary": "₹5.0 - ₹22.0+ LPA (Indicative range)",
            "salary_indicative": "Commis Chef post-BHM: ₹3.5 - 5.5 LPA | Sous Chef (4-7 yrs): ₹8 - 14 LPA | Executive Chef in 5-Star Luxury Hotel: ₹18 - 40+ LPA. Indicative figures from luxury hospitality chains (Taj, Oberoi, Marriott).",
            "future_scope": "Continuous strong demand in India's booming fine-dining restaurant culture, luxury destination resorts, and international cruise ships.",
            "government_opportunities": "ITDC Luxury Hotels (Ashok Group), State Tourism Development Hotels, Indian Railways IRCTC Executive Catering.",
            "private_opportunities": "Taj Hotels (IHCL), The Oberoi Group, ITC Hotels, Marriott International, Hyatt, Accor, Standalone Fine Dining Restaurants.",
            "higher_study_options": "Master in Culinary Arts (Le Cordon Bleu, Culinary Institute of America), Certified Master Chef (CMC).",
            "entrepreneurship_options": "Founding an independent restaurant, artisanal bakery, boutique catering company, or culinary academy.",
            "source": "National Council for Hotel Management and Catering Technology (NCHMCT) / IFCA",
            "official_url": "https://nchm.gov.in",
            "verification_status": "VERIFIED",
            "is_lesser_known": False,
            "career_family": "Hospitality & Gastronomy",
            "interest_clusters": "Food, Art, Hands-on, Creativity, Business",
            "work_style": "Kitchen, Hotel",
            "reality_check": "Not like relaxed TV cooking shows: Involves working 10 to 14 hours on your feet in intense heat, steam, and sharp knife hazards.\nInvolves working peak hours on weekends, festival holidays, and late nights when others celebrate.\nRequires climbing the strict, disciplined military-style kitchen brigade ladder step-by-step from peeling potatoes as a Commis.",
            "next_steps": "Pass Class 12 in any stream.\nAppear for the NCHM JEE entrance examination for admission into premier Institutes of Hotel Management (IHM Pusa, IHM Mumbai, etc.) or culinary academies.\nComplete 3-year B.Sc in Hospitality & Hotel Administration with food production specialization, and secure luxury kitchen training.",
            "courses": [{"course_id": 61, "type": "PRIMARY"}],
            "exams": [],
            "routes": [{"title": "Path A: IHM Culinary Route", "type": "PRIMARY", "steps": "12th (Any Stream) -> NCHM JEE -> IHM B.Sc Hospitality (3 yrs) -> Kitchen Industrial Training -> Commis Chef -> Sous Chef -> Executive Chef."}],
            "ladder": [
                {"stage": "Commis Chef / Line Cook", "exp": "0-3 Years", "desc": "Prepares mise-en-place, operates specific kitchen stations (tandoor, butchery, sauté) under supervision."},
                {"stage": "Sous Chef / Senior Chef de Partie", "exp": "3-8 Years", "desc": "Second-in-command, runs daily kitchen shifts, orders daily supplies, ensures recipe execution."},
                {"stage": "Executive Chef / Director of Culinary", "exp": "8+ Years", "desc": "Commands multiple hotel restaurants and banquet kitchens, designs menus, wins culinary awards."}
            ]
        },
        {
            "title": "Luxury Hotel General Manager",
            "short_name": "Hotel GM",
            "slug": "luxury-hotel-general-manager",
            "category": "Hospitality & Tourism",
            "sub_category": "Hotel & Resort Management",
            "industry": "Luxury Hospitality, Hotels & Resorts",
            "icon": "building",
            "short_description": "Commands the overall operations, financial profitability, guest experience, and staff of 5-star luxury hotels.",
            "description": "General Managers (GMs) of luxury hotels and palaces are the ultimate executive leaders of hospitality properties. They oversee all operational departments—including Food & Beverage, Front Office, Housekeeping, Sales & Marketing, Revenue Management, and Engineering. They ensure world-class guest luxury experiences, maintain international brand standards, and deliver profitability to hotel property owners.",
            "what_they_do": "They manage multi-crore property revenue strategies (RevPAR, Average Daily Rate), host high-profile VIP dignitaries, direct hotel departmental heads, ensure flawless guest service, and manage hotel asset upkeep.",
            "day_to_day_work": "• Reviewing daily RevPAR (Revenue Per Available Room), occupancy percentage, and banquet revenue.\n• Greeting arriving heads of state, corporate CEOs, and high-net-worth VIP guests in the lobby.\n• Conducting daily morning operational meetings with all hotel department heads.\n• Inspecting presidential suites, kitchens, and public areas for world-class luxury standards.\n• Analyzing guest feedback scores and implementing operational service improvements.",
            "work_environment": "5-star luxury hotels, heritage palace properties, luxury beach resorts.",
            "work_modes": "On-site / Hotel / Front-of-House",
            "minimum_qualification": "Undergraduate (Bachelor of Hotel Management - BHM / B.Sc Hospitality from IHM - 3-4 Years)",
            "preferred_streams": "Any Stream",
            "required_subjects": "Hospitality Management, Front Office, F&B Service, Hotel Accounting",
            "technical_skills": "Hotel Revenue Management (RevPAR, ADR, Yield Management), Luxury Service Standards, Property Management Systems (Opera PMS), Hotel P&L Auditing, Crisis & Security Management",
            "soft_skills": "Exceptional Polish & Elegance, Warm Diplomatic Charm, Executive Presence, Crisis Calmness",
            "tools": "Oracle Opera PMS, Micros POS, Revenue Management Analytics (IDeaS), Hotel Guest Feedback Portals",
            "certifications": "Certified Hotel Administrator (CHA) by AHLA, Graduate of OCLD (Oberoi Centre of Learning and Development) or Taj Management Training Programme (TMTP)",
            "experience_level": "Management Trainee to Hotel General Manager",
            "career_growth": "Advance from Management Trainee to Operations Manager, Resident Manager, Hotel GM, and Area Vice President.",
            "internship_roles": "Hotel Management Trainee, Operational Department Intern",
            "entry_level_roles": "Management Trainee (Front Office / F&B), Assistant Manager",
            "average_salary": "₹10.0 - ₹35.0+ LPA (Indicative range)",
            "salary_indicative": "Hotel Management Trainee post-IHM: ₹4.5 - 7 LPA | Executive Assistant Manager / Resident Manager: ₹12 - 20 LPA | General Manager of 5-Star Luxury Hotel: ₹25 - 55+ LPA plus luxury suite accommodation, dining privileges, and executive bonuses. Indicative figures from luxury hospitality industry surveys.",
            "future_scope": "Flourishing career with India's booming luxury travel market, destination weddings, and international hotel chain expansion.",
            "government_opportunities": "ITDC Hotel General Managers, State Tourism Corporation Flagship Properties.",
            "private_opportunities": "The Indian Hotels Company Limited (Taj, Vivanta, SeleQtions), The Oberoi Group, ITC Luxury Collection, Marriott International (The Ritz-Carlton, St. Regis), Hyatt Hotels.",
            "higher_study_options": "Master of Business Administration (MBA in Hospitality / General Management at Cornell University or EHL Switzerland).",
            "entrepreneurship_options": "Founding an independent boutique heritage resort, luxury glamping property, or hotel asset management consultancy.",
            "source": "NCHMCT / Hotel Association of India (HAI)",
            "official_url": "https://hotelassociationofindia.com",
            "verification_status": "VERIFIED",
            "is_lesser_known": False,
            "career_family": "Hospitality & Gastronomy",
            "interest_clusters": "Travel, Business, People, Leadership, Culture",
            "work_style": "Hotel, Office",
            "reality_check": "Luxury hotels never close: GMs often live on the property and are on duty 24x7 to resolve crises.\nRequires immense personal poise and charm while handling demanding, high-profile guests.\nRequires rising through competitive corporate management trainee programs like OCLD (Oberoi) or TMTP (Taj).",
            "next_steps": "Pass Class 12 in any stream with good English communication.\nAppear for NCHM JEE to enroll in premier IHMs (Pusa, Mumbai, Bangalore) or apply for the Oberoi STEP program.\nCrack premier corporate management training programs (OCLD, TMTP) upon graduation to fast-track toward General Management.",
            "courses": [{"course_id": 61, "type": "PRIMARY"}],
            "exams": [],
            "routes": [{"title": "Path A: IHM to Luxury Hotel GM", "type": "PRIMARY", "steps": "12th (Any Stream) -> IHM BHM (3 yrs) -> Corporate Management Trainee (OCLD/Taj) -> Assistant Manager -> Resident Manager -> General Manager."}],
            "ladder": [
                {"stage": "Management Trainee / Assistant Manager", "exp": "0-4 Years", "desc": "Manages front desk operations, coordinates VIP guest arrivals, handles daily guest escalations."},
                {"stage": "Director of Operations / Resident Manager", "exp": "4-10 Years", "desc": "Second-in-command of hotel, supervises all operational departments, optimizes daily room yield and banqueting."},
                {"stage": "General Manager (Luxury Hotel / Palace)", "exp": "10+ Years", "desc": "Complete operational and financial custodian of 5-star luxury property, drives multimillion-dollar profitability."}
            ]
        }
    ]

def get_aviation_maritime_and_built_environment_careers():
    return [
        {
            "title": "Aircraft Maintenance Engineer (AME)",
            "short_name": "AME Engineer",
            "slug": "aircraft-maintenance-engineer-ame",
            "category": "Aviation, Logistics & Supply Chain",
            "sub_category": "Aircraft Maintenance & Aerospace Engineering",
            "industry": "Commercial Aviation, MRO & Aircraft Engineering",
            "icon": "airplane-engines",
            "short_description": "Inspects, repairs, overhauls, and certifies commercial aircraft for safe, airworthy flight under DGCA license.",
            "description": "Aircraft Maintenance Engineers (AMEs) are statutorily licensed aviation professionals certified by the Directorate General of Civil Aviation (DGCA under CAR 66). They inspect, repair, overhaul, and sign the official 'Certificate of Release to Service' (CRS) for commercial jetliners (Airbus A320, Boeing 737, 777). Without an AME's legal signature, no commercial aircraft can legally take off.",
            "what_they_do": "They inspect jet turbine engines, avionics navigation systems, landing gears, and hydraulic flight controls, troubleshoot electronic instrument errors, and conduct pre-flight transit inspections.",
            "day_to_day_work": "• Performing pre-flight and post-flight transit turnaround technical inspections on airport tarmac.\n• Inspecting high-bypass turbofan engines with high-resolution optical video-borescopes.\n• Troubleshooting flight computer error codes using onboard centralized fault display systems (CFDS).\n• Replacing aircraft brake assemblies, landing gear tires, and avionics flight management computers.\n• Signing the legally binding Certificate of Release to Service (CRS) in the aircraft technical logbook.",
            "work_environment": "Airport tarmac ramps, aircraft maintenance hangars (MRO facilities), line maintenance stations.",
            "work_modes": "On-site / Airport Tarmac / Hangar",
            "minimum_qualification": "DGCA CAR 66 Basic AME Training (2-3 Years) / B.Sc in AME or B.Tech in Aerospace/Aeronautical",
            "preferred_streams": "Science (PCM)",
            "required_subjects": "Physics, Mathematics, Chemistry",
            "technical_skills": "Jet Engine Overhaul, Avionics Systems, Aircraft Hydraulic & Pneumatic Systems, Airframe Structural Inspection, DGCA Civil Aviation Requirements (CAR 66 / CAR 145), Borescope Inspection",
            "soft_skills": "Zero-Error Precision, Extreme Technical Integrity, Physical Stamina, Methodical Troubleshooting",
            "tools": "Aircraft Maintenance Manuals (AMM), Video Borescopes, Calibrated Torque Wrenches, Multi-meters, Hydraulic Test Rigs",
            "certifications": "DGCA CAR 66 AME License (Category B1 for Mechanical/Engines or Category B2 for Avionics/Electrical)",
            "experience_level": "AME Trainee to Post-Holder Chief Engineer",
            "career_growth": "Advance from Trainee Technician to Licensed AME (Category A -> B1/B2), Quality Assurance Manager, or Base Maintenance Director.",
            "internship_roles": "Line Maintenance Apprentice, MRO Hangar Trainee",
            "entry_level_roles": "Junior AME Technician, Aircraft Maintenance Apprentice, Line Support Assistant",
            "average_salary": "₹5.0 - ₹18.0+ LPA (Indicative range)",
            "salary_indicative": "AME Trainee Technician: ₹3.5 - 5 LPA | Licensed Type-Rated AME (A320 / B737 certified): ₹10 - 18 LPA | Senior Base Maintenance Engineer / Post-Holder: ₹22 - 35+ LPA. Indicative figures from major Indian airlines (IndiGo, Air India).",
            "future_scope": "Massive, booming shortage: Indian airlines have placed historic mega-orders for over 1,500 new aircraft, requiring thousands of licensed AMEs.",
            "government_opportunities": "Directorate General of Civil Aviation (DGCA Airworthiness Officers), Pawan Hans Helicopters, Border Security Force (BSF Air Wing), Hindustan Aeronautics Limited (HAL).",
            "private_opportunities": "IndiGo, Air India, Akasa Air, SpiceJet, Air Works India, GMR Aero Technic MRO, Boeing India, Airbus India.",
            "higher_study_options": "Type-Rating Certifications on Boeing 777 / 787 Dreamliner / Airbus A350, Aircraft Systems Engineering.",
            "entrepreneurship_options": "Establishing an independent aviation ground support or component overhaul workshop.",
            "source": "Directorate General of Civil Aviation (DGCA India)",
            "official_url": "https://www.dgca.gov.in",
            "verification_status": "VERIFIED",
            "is_lesser_known": False,
            "career_family": "Machines & Aviation",
            "interest_clusters": "Machines, Aviation, Science, Hands-on",
            "work_style": "Airport, Hangar, Outdoor",
            "reality_check": "Massive legal and criminal responsibility: Signing the Flight Release means taking personal legal accountability for the airworthiness and safety of 200+ passenger lives.\nInvolves working on open airport tarmacs in extreme summer heat (45°C), cold night winds, and torrential rains.\nAME is a specialized DGCA statutory licensing route: university engineering degrees alone do not confer the legal right to certify aircraft without clearing DGCA module exams.",
            "next_steps": "Pass Class 12 with Physics, Chemistry, and Mathematics (PCM) with at least 50% marks.\nEnroll in a DGCA-approved Aircraft Maintenance Engineering (AME) training institute (Category B1.1 or B2).\nClear DGCA CAR 66 module exams and complete required practical maintenance experience on commercial aircraft to earn the AME License.",
            "courses": [{"course_id": 1, "type": "RELATED"}],
            "exams": [],
            "routes": [{"title": "Path A: DGCA CAR 66 AME Route", "type": "PRIMARY", "steps": "12th (PCM) -> DGCA Approved AME Institute -> Clear DGCA Module Exams -> Practical Aircraft Experience -> Type Rating -> Licensed AME."}],
            "ladder": [
                {"stage": "AME Trainee / Technician", "exp": "0-3 Years", "desc": "Carries out line checks and repairs under supervision of licensed engineers, logs required maintenance hours."},
                {"stage": "Licensed Aircraft Maintenance Engineer (B1/B2)", "exp": "3-8 Years", "desc": "Signs official Certificate of Release to Service (CRS), conducts transit line maintenance and borescope inspections."},
                {"stage": "Base Maintenance Manager / Quality Auditor", "exp": "8+ Years", "desc": "Oversees full heavy C-checks and D-checks inside hangars, liaises with DGCA on airline airworthiness audits."}
            ]
        },
        {
            "title": "Merchant Navy Deck Navigating Officer",
            "short_name": "Merchant Navy Officer",
            "slug": "merchant-navy-deck-officer",
            "category": "Aviation, Logistics & Supply Chain",
            "sub_category": "Maritime & Nautical Science",
            "industry": "Commercial Shipping, Ocean Logistics & Cargo Vessels",
            "icon": "water",
            "short_description": "Navigates massive ocean-going cargo ships, oil tankers, and container vessels across international waters.",
            "description": "Merchant Navy Deck Officers (Navigating Officers) operate and navigate massive commercial ocean vessels—including container ships, crude oil supertankers (VLCCs), chemical carriers, and bulk carriers across international oceans. Licensed by the Directorate General of Shipping (DGS), they maintain navigational bridge watches, operate radar and GPS charts (ECDIS), and oversee cargo loading.",
            "what_they_do": "They navigate multi-thousand ton ships through international sea lanes, operate electronic navigation instruments, monitor celestial and coastal positions, supervise cargo loading/discharge at ports, and command emergency maritime safety.",
            "day_to_day_work": "• Standing 4-hour navigational bridge watches at sea, monitoring radar and AIS for collision avoidance (COLREGs).\n• Plotting voyage routes on Electronic Chart Display and Information Systems (ECDIS).\n• Supervising cargo loading, lashing, and ballast water tanks during port docking operations.\n• Conducting weekly safety drills for lifeboats, firefighting systems, and sea survival gear.\n• Calculating astronomical star positions using sextants and marine chronometers for backup navigation.",
            "work_environment": "Commercial ocean vessels at sea (container ships, bulk carriers, tankers), international commercial seaports.",
            "work_modes": "At Sea / Ship / Worldwide Travel",
            "minimum_qualification": "Undergraduate (B.Sc Nautical Science - 3 Years) or Diploma in Nautical Science (DNS - 1 Year) from DGS-approved maritime institutes",
            "preferred_streams": "Science (PCM)",
            "required_subjects": "Physics, Mathematics, Chemistry",
            "technical_skills": "Celestial & Terrestrial Navigation, Electronic Chart Display (ECDIS), Collision Regulations (COLREGs), Cargo Handling & Stowage, Ship Stability & Ballast, Maritime Law (SOLAS, MARPOL)",
            "soft_skills": "Mental Resilience in Ocean Isolation, Vigilant Discipline, Decisive Bridge Leadership, Physical Fitness",
            "tools": "Marine Radar / ARPA, ECDIS Electronic Charts, Magnetic Compass, Sextant, VHF Marine Radio, Gyrocompass",
            "certifications": "Certificate of Competency (CoC as Second Mate / Chief Mate / Master Mariner) issued by DG Shipping, STCW Certificates",
            "experience_level": "Deck Cadet to Captain / Master Mariner",
            "career_growth": "Advance from Deck Cadet to 3rd Officer, 2nd Officer, Chief Officer, and Captain (Master Mariner).",
            "internship_roles": "Deck Cadet (12 to 18 months mandatory structured shipboard training at sea)",
            "entry_level_roles": "Deck Cadet, 3rd Navigating Officer",
            "average_salary": "₹8.0 - ₹28.0+ LPA (Tax-Exempt NRI Dollar Earnings)",
            "salary_indicative": "Deck Cadet: ₹35,000 - 55,000 monthly stipend at sea | 3rd / 2nd Officer: ₹1.5 - 3.5 Lakhs per month ($2,000 - $4,500/mo) | Captain / Master Mariner: ₹6 - 12 Lakhs per month ($8,000 - $15,000/mo) often tax-free under NRI status. Indicative figures from international shipping lines.",
            "future_scope": "Essential global trade career: Over 90% of global trade travels by sea; Indian officers are among the most respected and sought-after seafarers globally.",
            "government_opportunities": "Directorate General of Shipping (Nautical Surveyors via UPSC), Shipping Corporation of India (SCI), Port Trusts (Harbor Pilots).",
            "private_opportunities": "Maersk Line, Mediterranean Shipping Company (MSC), Anglo-Eastern, Fleet Management, Teekay Tankers, Synergy Marine Group, Scorpio Tankers.",
            "higher_study_options": "Master Mariner Certificate of Competency (FG), M.Sc in Maritime Affairs (World Maritime University, Sweden).",
            "entrepreneurship_options": "Marine cargo surveyancy, maritime chartering brokerage, or ship crewing agency.",
            "source": "Directorate General of Shipping (DGS India) / Indian Maritime University (IMU)",
            "official_url": "https://www.dgshipping.gov.in",
            "verification_status": "VERIFIED",
            "is_lesser_known": False,
            "career_family": "Machines & Aviation",
            "interest_clusters": "Travel, Machines, Outdoor, Leadership, Hands-on",
            "work_style": "Ship, Outdoor, Travel",
            "reality_check": "Involves prolonged separation from family: contracts typically require spending 4 to 6 continuous months at sea.\nStrict medical and vision standards: Flawless 6/6 eyesight and zero color blindness are mandatory.\nHigh financial reward: Substantial dollar salaries with tax-exempt non-resident Indian (NRI) status if sailing over 183 days a year.",
            "next_steps": "Pass Class 12 with Physics, Chemistry, and Mathematics (PCM) with at least 60% aggregate and 50% in English.\nAppear for the Indian Maritime University Common Entrance Test (IMU-CET).\nSecure company sponsorship from a premier shipping line and enroll in a DGS-approved B.Sc Nautical Science or DNS program.",
            "courses": [{"course_id": 62, "type": "PRIMARY"}],
            "exams": [],
            "routes": [{"title": "Path A: IMU-CET Nautical Route", "type": "PRIMARY", "steps": "12th (PCM 60%+) -> IMU-CET Exam -> Company Sponsorship -> B.Sc Nautical Science (3 yrs) -> Cadetship at Sea -> 2nd Mate CoC -> 3rd Officer."}],
            "ladder": [
                {"stage": "Deck Cadet", "exp": "0-2 Years", "desc": "Completes structured training book, assists in bridge watches and cargo deck operations during sea voyages."},
                {"stage": "3rd / 2nd Navigating Officer", "exp": "2-6 Years", "desc": "Maintains navigational watches at sea, manages bridge navigational equipment, prepares passage plans."},
                {"stage": "Chief Officer / Captain (Master Mariner)", "exp": "6+ Years", "desc": "Complete commander of the vessel, responsible for ship safety, multi-million dollar cargo, and crew lives."}
            ]
        },
        {
            "title": "Registered Professional Architect",
            "short_name": "Architect",
            "slug": "registered-professional-architect",
            "category": "Architecture & Built Environment",
            "sub_category": "Architectural Design & Planning",
            "industry": "Architecture, Urban Design & Construction",
            "icon": "building-gear",
            "short_description": "Designs residential, commercial, and civic buildings, balancing structural safety, sustainability, and spatial aesthetics.",
            "description": "Architects are statutory professionals licensed by the Council of Architecture (COA) under the Architects Act 1972. They conceptualize, design, and detail the built environment—including residential housing, commercial skyscrapers, airports, civic museums, and sustainable smart buildings. They integrate aesthetic beauty with structural safety, building services, environmental bioclimatic design, and municipal bylaws.",
            "what_they_do": "They sketch architectural concepts, model BIM (Building Information Modeling) parametric buildings in Revit, create detailed construction execution drawings, select sustainable building materials, and supervise construction site progress.",
            "day_to_day_work": "• Meeting clients to understand functional spatial requirements and project budgets.\n• Creating conceptual architectural floor plans, sections, and 3D visual renderings.\n• Designing detailed parametric BIM models in Autodesk Revit with structural and MEP coordination.\n• Ensuring architectural drawings comply with local municipal building bylaws and fire safety codes.\n• Visiting construction sites to inspect structural concrete casting and finishing workmanship.",
            "work_environment": "Architectural design studios, construction sites, client offices.",
            "work_modes": "Studio / Site / Hybrid",
            "minimum_qualification": "Undergraduate (Bachelor of Architecture - B.Arch - 5 Years recognized by Council of Architecture)",
            "preferred_streams": "Science (PCM) with Mathematics mandatory",
            "required_subjects": "Mathematics, Physics, Chemistry, Architectural Drawing",
            "technical_skills": "Building Information Modeling (BIM - Revit), Architectural Drafting (AutoCAD), Bioclimatic Design, Construction Details, Municipal Building Bylaws, Structural Systems Basics, Sustainable Architecture (IGBC/LEED)",
            "soft_skills": "Spatial Imagination, Design Aesthetics, Client Persuasion, Multidisciplinary Coordination",
            "tools": "Autodesk Revit, AutoCAD, SketchUp, Rhino / Grasshopper, Enscape / Lumion, V-Ray",
            "certifications": "Council of Architecture (COA) Registration (Mandatory to use the title 'Architect'), IGBC Accredited Professional",
            "experience_level": "Junior Architect to Principal Architect",
            "career_growth": "Advance to Senior Project Architect, Associate Partner, or Principal Architect / Studio Founder.",
            "internship_roles": "Architectural Intern (compulsory 1-semester professional practice training)",
            "entry_level_roles": "Junior Architect, Architectural Draftsman, BIM Modeler",
            "average_salary": "₹4.5 - ₹14.0+ LPA (Indicative range)",
            "salary_indicative": "Junior Architect post-B.Arch: ₹4.5 - 6.5 LPA | Senior Project Architect (3-6 yrs): ₹8 - 14 LPA | Principal Architect / Studio Owner: ₹18 - 45+ LPA. Indicative figures from Council of Architecture and architectural studio surveys.",
            "future_scope": "Continuous strong demand driven by India's massive urban transformation, green building mandates, and infrastructure growth.",
            "government_opportunities": "Central Public Works Department (CPWD Architects via UPSC), DDA, NBCC, State Housing Boards, Military Engineer Services (MES).",
            "private_opportunities": "Hafeez Contractor, Morphogenesis, HCP Design (Central Vista architects), RSP Architects, Gensler India, Studio Lotus.",
            "higher_study_options": "Master of Architecture (M.Arch), Master of Urban Design, Master in Sustainable Architecture.",
            "entrepreneurship_options": "Establishing an independent architectural design firm, interior architecture studio, or sustainable design consultancy.",
            "source": "Council of Architecture (COA)",
            "official_url": "https://www.coa.gov.in",
            "verification_status": "VERIFIED",
            "is_lesser_known": False,
            "career_family": "Architecture & Built Environment",
            "interest_clusters": "Architecture, Design, Art, Science, Hands-on",
            "work_style": "Studio, Construction Site, Office",
            "reality_check": "Under Indian law (Architects Act 1972), no one can call themselves an 'Architect' without completing a 5-year B.Arch degree and registering with the Council of Architecture (COA).\nRequires a 5-year rigorous undergraduate degree program with continuous design studio submissions and juries.\nCombines artistic spatial creativity with strict engineering physics, municipal laws, and contractor management.",
            "next_steps": "Study Mathematics, Physics, and Chemistry in Class 12.\nAppear for NATA (National Aptitude Test in Architecture) conducted by COA or JEE Main (Paper 2A - B.Arch).\nEnroll in a 5-year B.Arch degree program at a COA-recognized institution, complete professional training, and register with COA.",
            "courses": [{"course_id": 2, "type": "PRIMARY"}],
            "exams": [{"exam_id": 8, "importance": "RECOMMENDED"}],
            "routes": [{"title": "Path A: Standard B.Arch Route", "type": "PRIMARY", "steps": "12th (PCM) -> NATA / JEE Paper 2 -> B.Arch (5 yrs) -> Practical Training -> COA Registration -> Licensed Architect."}],
            "ladder": [
                {"stage": "Junior Architect / BIM Modeler", "exp": "0-3 Years", "desc": "Drafts municipal submission drawings, builds 3D Revit models, prepares construction detail sheets."},
                {"stage": "Project Architect", "exp": "3-7 Years", "desc": "Leads architectural design of residential or commercial complexes, coordinates structural/MEP engineers, inspects sites."},
                {"stage": "Principal Architect / Partner", "exp": "7+ Years", "desc": "Founding partner of architectural firm, designs landmark civic buildings, wins national design competitions."}
            ]
        }
    ]
