"""
scripts/catalog_builder_part11.py
Final 18 careers bringing total national database to 127 authentic occupational pathways.
"""

def get_final_18_careers():
    return [
        # --- MEDIA (6) ---
        {
            "title": "Content Strategist & Writer",
            "short_name": "Content Strategist",
            "slug": "content-strategist-writer",
            "category": "Media, Journalism & Digital Marketing",
            "sub_category": "Content Strategy & Brand Storytelling",
            "industry": "Digital Media & Brand Publishing",
            "icon": "pen",
            "short_description": "Plans, creates, and governs engaging content across digital platforms to educate audiences and build brand trust.",
            "description": "Content Strategists define what content is created, for whom, in what format, and on which channels. They manage editorial calendars, write high-authority long-form guides, craft thought-leadership pieces, and ensure content aligns with brand tone.",
            "what_they_do": "They develop editorial style guides, conduct content gap audits, author in-depth research articles, write thought leadership for executive leaders, and analyze content engagement metrics.",
            "day_to_day_work": "• Researching audience search intent and drafting long-form educational articles.\n• Interviewing company subject matter experts for thought leadership white papers.\n• Planning quarterly editorial content calendars with graphic designers.\n• Editing and proofreading articles drafted by freelance and junior writers.\n• Tracking content reading times, organic traffic, and newsletter subscriber signups.",
            "work_environment": "Digital agencies, SaaS tech firms, media houses, or remote.",
            "work_modes": "Remote / Hybrid / Office",
            "minimum_qualification": "Undergraduate (Any Stream)",
            "preferred_streams": "Humanities / English / Mass Comm",
            "required_subjects": "English, Journalism, Creative Writing",
            "technical_skills": "Content Strategy, SEO Writing, Editorial Planning, Copyediting, CMS (WordPress), Storytelling, Analytics",
            "soft_skills": "Empathy for Readers, Intellectual Curiosity, Attention to Tone, Creative Flair",
            "tools": "WordPress, Notion, Grammarly, Ahrefs, Google Docs, Clearscope",
            "certifications": "HubSpot Content Marketing Certification",
            "experience_level": "Entry-Level to Senior",
            "career_growth": "Broad career path progressing to Managing Editor, Head of Content, or VP of Brand Communications.",
            "internship_roles": "Content Writing Intern, Editorial Trainee",
            "entry_level_roles": "Junior Content Writer, Content Associate, Copywriter",
            "average_salary": "₹4 - ₹11 LPA (Indicative range)",
            "salary_indicative": "Content Writer (0-2 yrs): ₹3.5 - 5 LPA | Content Strategist (3-6 yrs): ₹7 - 13 LPA | Head of Content (7+ yrs): ₹16 - 32+ LPA. Indicative figures from IAMAI 2024.",
            "future_scope": "Continuous strong demand as high-quality, authentic human storytelling becomes the ultimate differentiator in the age of AI.",
            "government_opportunities": "MyGov Content Cell, National Book Trust, Sahitya Akademi, Digital India Content Portals.",
            "private_opportunities": "Razorpay, Swiggy, Zoho, Freshworks, top tech publications (YourStory, Inc42), digital creative agencies.",
            "higher_study_options": "Master's in Creative Writing / English Literature, PG Diploma in Journalism.",
            "entrepreneurship_options": "Content marketing agency, niche digital newsletter media brand, publishing consultancy.",
            "source": "Internet and Mobile Association of India (IAMAI)",
            "official_url": "https://www.iamai.in",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 21, "type": "DIRECT"}, {"course_id": 46, "type": "DIRECT"}],
            "exams": [{"exam_id": 79, "importance": "PRIMARY"}],
            "routes": [{"title": "Path A: Writing Portfolio to Content Strategist", "type": "COMMON", "steps": "Graduation in any stream -> Build portfolio of 10+ published articles on Medium / Substack -> Junior Content Writer -> Content Strategist."}],
            "ladder": [
                {"stage": "Content Writer", "exp": "0-2 Years", "desc": "Writes blog posts, email newsletters, and website copy adhering to brand guidelines."},
                {"stage": "Content Strategist", "exp": "2-5 Years", "desc": "Audits user search journeys, defines editorial voice, writes tier-1 white papers."},
                {"stage": "Managing Editor / Content Lead", "exp": "5-8 Years", "desc": "Directs team of in-house writers and videographers, runs brand media publications."},
                {"stage": "Head of Content / VP Brand Narrative", "exp": "8+ Years", "desc": "Directs total enterprise storytelling and thought leadership presence across the globe."}
            ],
            "roadmaps": {
                "Class 10": "Read widely across fiction, history, and science, and write personal daily journals.",
                "Class 12": "Score top marks in English and Social Sciences.",
                "Graduation": "Complete B.A. in English, Journalism, or any stream. Start a blog or Substack newsletter to build an authentic writing portfolio.",
                "Working Professional": "Master SEO search intent, content distribution systems, and executive thought leadership."
            }
        },
        {
            "title": "News Anchor & Broadcast Journalist",
            "short_name": "News Anchor",
            "slug": "news-anchor-broadcast-journalist",
            "category": "Media, Journalism & Digital Marketing",
            "sub_category": "Broadcast Journalism & Television",
            "industry": "Television & Digital Video News",
            "icon": "camera-video",
            "short_description": "Presents breaking news live on television and digital video channels, moderates primetime debates, and interviews public figures.",
            "description": "News Anchors are the public face and voice of broadcast news networks. They deliver live breaking news bulletins, moderate panel discussions with politicians and experts, conduct high-stakes interviews, and report from live field events.",
            "what_they_do": "They read teleprompters during live studio broadcasts, question debate panelists on live television, verify breaking developments in real-time, and host special documentary features.",
            "day_to_day_work": "• Reviewing rundown scripts with news producers and executive editors.\n• Reading live teleprompters with calm poise, clear voice modulation, and diction.\n• Moderating heated live primetime debates with political spokespersons.\n• Conducting live interviews with government ministers and domain experts.\n• Breaking urgent news flashes during live studio feeds.",
            "work_environment": "Broadcast news television studios, digital video sets, live field press setups.",
            "work_modes": "On-site / Studio Broadcast / Shift Timings",
            "minimum_qualification": "Undergraduate (BJMC / B.A. Mass Comm / English / Any Stream)",
            "preferred_streams": "Humanities / Any Stream",
            "required_subjects": "Mass Communication, English, Political Science",
            "technical_skills": "Live Broadcast Anchoring, Teleprompter Reading, Voice Modulation & Diction, Television Production, On-Camera Poise, Media Ethics",
            "soft_skills": "Quick Wit, Calm Under Live Pressure, Confident Body Language, Fearless Questioning",
            "tools": "Studio Teleprompters, Live IFB Earpieces, Rundown Systems (iNEWS), Microphones",
            "certifications": "Degree from Indian Institute of Mass Communication (IIMC) / Asian College of Journalism (ACJ)",
            "experience_level": "Entry-Level to Senior Primetime Anchor",
            "career_growth": "High-visibility trajectory progressing to Senior Primetime Anchor, Managing Editor, or Television Channel Head.",
            "internship_roles": "Broadcast Newsroom Intern, Teleprompter Operator Trainee, Production Assistant",
            "entry_level_roles": "Junior Reporter, Associate Producer, Bulletin Anchor (Day Shifts)",
            "average_salary": "₹5 - ₹18 LPA (Indicative range - star primetime anchors earn substantial remuneration)",
            "salary_indicative": "Bulletin Anchor (0-2 yrs): ₹4 - 6.5 LPA | Senior Anchor / Debate Host (3-6 yrs): ₹8 - 20 LPA | Primetime Star Anchor (7+ yrs): ₹25 - 75+ LPA. Indicative figures from News Broadcasters Federation 2024.",
            "future_scope": "Growing across streaming video news, digital YouTube news channels, and 24x7 television networks.",
            "government_opportunities": "Doordarshan News (DD News), Sansad TV (Parliament Television), All India Radio.",
            "private_opportunities": "NDTV, India Today Group, Times Now, Republic Media, CNN-News18, digital video news channels.",
            "higher_study_options": "Master's in Broadcast Journalism, Media Management.",
            "entrepreneurship_options": "Independent digital video news channel, podcast network, media training academy.",
            "source": "News Broadcasters Federation (NBF) / IIMC",
            "official_url": "https://iimc.gov.in",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 21, "type": "COMMON"}, {"course_id": 22, "type": "COMMON"}],
            "exams": [{"exam_id": 79, "importance": "PRIMARY"}],
            "routes": [{"title": "Path A: Broadcast Journalism Degree Route", "type": "COMMON", "steps": "Graduation -> PG Diploma in Broadcast Journalism (IIMC / ACJ) -> Studio Screen Test -> Day Bulletin Anchor -> Primetime Anchor."}],
            "ladder": [
                {"stage": "Trainee Reporter / Desk Associate", "exp": "0-2 Years", "desc": "Writes news tickers, assists senior producers, anchors early morning short bulletins."},
                {"stage": "News Anchor / Special Correspondent", "exp": "2-5 Years", "desc": "Anchors regular hourly news bulletins, reports from live breaking news locations."},
                {"stage": "Senior Primetime Anchor", "exp": "5-9 Years", "desc": "Hosts 8 PM / 9 PM flagship debate shows, conducts marquee interviews with ministers."},
                {"stage": "Managing Editor / Channel Head", "exp": "9+ Years", "desc": "Sets editorial line for 24x7 news channel, directs overall broadcast programming."}
            ],
            "roadmaps": {
                "Class 10": "Practice reading out loud, participate in public speaking, elocutions, and debates.",
                "Class 12": "Choose Humanities, Commerce, or Science with English for board exams.",
                "Graduation": "Complete Bachelor's in Journalism or English. Practice on-camera speaking and develop neutral, clear diction.",
                "Working Professional": "Pass studio screen tests at broadcast networks or launch a successful digital news YouTube format."
            }
        },
        {
            "title": "Social Media Manager & Growth Specialist",
            "short_name": "Social Media Manager",
            "slug": "social-media-manager",
            "category": "Media, Journalism & Digital Marketing",
            "sub_category": "Social Media Strategy & Community Growth",
            "industry": "Digital Media & Consumer Brands",
            "icon": "share",
            "short_description": "Builds and engages brand communities across Instagram, YouTube, LinkedIn, and X through creative viral content.",
            "description": "Social Media Managers oversee a brand's voice and community across social platforms. They tap into cultural moments (moment marketing), create short-form viral videos (Reels, Shorts), manage influencer collaborations, and foster passionate digital communities.",
            "what_they_do": "They design social media content calendars, script and produce engaging short-form video reels, manage influencer marketing campaigns, monitor social sentiment, and respond to community feedback.",
            "day_to_day_work": "• Brainstorming creative moment marketing memes and trending cultural hooks.\n• Shooting and editing short-form video Reels on CapCut / Premiere Pro.\n• Writing punchy social copy and community polls on X, LinkedIn, and Instagram.\n• Onboarding and negotiating collaboration deliverables with social influencers.\n• Tracking social reach, engagement rates, and viral video analytics.",
            "work_environment": "D2C brand headquarters, creative marketing agencies, tech companies, or remote.",
            "work_modes": "Remote / Hybrid / Creative Studio",
            "minimum_qualification": "Undergraduate (Any Stream)",
            "preferred_streams": "Any Stream",
            "required_subjects": "Mass Communication, Marketing, English",
            "technical_skills": "Social Media Algorithms, Short-Form Video Editing (CapCut/Premiere), Copywriting, Influencer Campaign Management, Trend Jacking, Social Analytics",
            "soft_skills": "High Cultural Relevance, Humor, Creativity, Fast Execution, Community Empathy",
            "tools": "Instagram, YouTube Studio, X Analytics, CapCut, Premiere Pro, Sprout Social, Canva",
            "certifications": "Meta Certified Social Media Marketing Professional",
            "experience_level": "Entry-Level to Senior",
            "career_growth": "Rapid growth progressing to Head of Social Media, Director of Digital Engagement, or Chief Marketing Officer.",
            "internship_roles": "Social Media Intern, Content Creator Trainee, Meme Marketing Intern",
            "entry_level_roles": "Social Media Executive, Community Manager, Content Creator",
            "average_salary": "₹3.8 - ₹11 LPA (Indicative range)",
            "salary_indicative": "Social Media Executive (0-2 yrs): ₹3.5 - 5 LPA | Social Media Lead (3-6 yrs): ₹7 - 14 LPA | Head of Social & Community (7+ yrs): ₹18 - 35+ LPA. Indicative figures from IAMAI 2024.",
            "future_scope": "Surging demand as video-first social platforms dominate modern consumer discovery, shopping, and entertainment.",
            "government_opportunities": "MyGov India Social Media Team, State Police Social Media Cells (UP Police, Mumbai Police creative teams).",
            "private_opportunities": "Swiggy, Zomato, Durex, Netflix India, top D2C consumer brands, leading digital creative agencies (Schbang, Dentsu Webchutney).",
            "higher_study_options": "MBA in Marketing, Master's in Digital Media.",
            "entrepreneurship_options": "Independent social media agency, influencer talent management agency, creator media brand.",
            "source": "Internet and Mobile Association of India (IAMAI)",
            "official_url": "https://www.iamai.in",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 17, "type": "COMMON"}, {"course_id": 21, "type": "COMMON"}],
            "exams": [{"exam_id": 79, "importance": "PRIMARY"}],
            "routes": [{"title": "Path A: Creator Portfolio to Social Media Lead", "type": "COMMON", "steps": "Undergraduate degree -> Build personal or brand social channel to 10K+ followers -> Social Media Executive -> Social Media Manager."}],
            "ladder": [
                {"stage": "Social Media Executive", "exp": "0-2 Years", "desc": "Publishes daily posts, responds to DMs and comments, edits video Reels."},
                {"stage": "Social Media Manager", "exp": "2-5 Years", "desc": "Defines brand voice, executes viral moment marketing campaigns, directs influencer budgets."},
                {"stage": "Director of Social & Community", "exp": "5-8 Years", "desc": "Heads multi-platform digital community, integrates social commerce with brand sales."},
                {"stage": "Chief Brand Officer", "exp": "8+ Years", "desc": "Owns total brand presence in modern digital culture and consumer mindshare."}
            ],
            "roadmaps": {
                "Class 10": "Learn video editing on smartphones and observe what makes social content go viral.",
                "Class 12": "Choose any stream for Class 12 board exams.",
                "Graduation": "Complete graduation. Build a creative social portfolio or run a niche theme page demonstrating real organic follower growth.",
                "Working Professional": "Master performance social strategies, paid amplification, and brand community engagement."
            }
        },
        {
            "title": "Video Producer & Video Editor",
            "short_name": "Video Producer",
            "slug": "video-producer-editor",
            "category": "Media, Journalism & Digital Marketing",
            "sub_category": "Video Production & Post-Production",
            "industry": "Film, Digital Video & OTT Entertainment",
            "icon": "film",
            "short_description": "Directs, shoots, edits, and produces cinematic video content for OTT streaming platforms, YouTube, television, and commercials.",
            "description": "Video Producers and Editors bring visual stories to life. They manage end-to-end video workflows: from script breakdown, lighting, and camera cinematography on sets to non-linear video editing, color grading, sound design, and final delivery.",
            "what_they_do": "They manage video shoots, operate cinema cameras and lighting, edit footage in Premiere Pro or DaVinci Resolve, perform color grading, mix audio tracks, and deliver finished video masters.",
            "day_to_day_work": "• Planning video production shoot schedules and shot lists.\n• Directing cinematography, multi-camera angles, and studio lighting setups.\n• Editing documentary, corporate, or commercial video cuts in Premiere Pro.\n• Color grading log footage in DaVinci Resolve using calibrated monitors.\n• Mixing dialogue, background music, and foley sound effects.",
            "work_environment": "Film production sets, video editing post-production suites, digital media studios.",
            "work_modes": "On-site / Studio & Set / Hybrid",
            "minimum_qualification": "Undergraduate (Film & TV Production / B.Sc Digital Filmmaking / Any Degree + Video Showreel)",
            "preferred_streams": "Any Stream",
            "required_subjects": "Film Studies, Visual Arts, English",
            "technical_skills": "Non-Linear Video Editing (NLE), Cinematography, Color Grading (DaVinci Resolve), Audio Mixing, Storyboarding, Lighting Techniques",
            "soft_skills": "Visual Rhythm, Patience, Creative Collaboration, Attention to Pacing",
            "tools": "Adobe Premiere Pro, DaVinci Resolve, Final Cut Pro, Cinema Cameras (Sony FX3, RED, Arri), After Effects",
            "certifications": "FTII Pune / SRFTI Kolkata Film Diploma, DaVinci Resolve Certified Colorist",
            "experience_level": "Entry-Level to Senior",
            "career_growth": "Broad creative career progressing to Senior Film Editor, Executive Producer, or Commercial Film Director.",
            "internship_roles": "Assistant Editor Intern, Production Assistant, Post-Production Trainee",
            "entry_level_roles": "Assistant Video Editor, Junior Videographer, Video Associate",
            "average_salary": "₹4 - ₹12 LPA (Indicative range)",
            "salary_indicative": "Assistant Editor (0-2 yrs): ₹3.5 - 5.5 LPA | Video Producer / Lead Editor (3-6 yrs): ₹7 - 15 LPA | Executive Producer / Commercial Director (7+ yrs): ₹20 - 50+ LPA. Indicative figures from FTII & MESC 2024.",
            "future_scope": "Surging demand fueled by OTT streaming platforms (Netflix, Amazon Prime, Hotstar), YouTube creators, and video advertising.",
            "government_opportunities": "Films Division of India, Doordarshan, National Film Development Corporation (NFDC), FTII.",
            "private_opportunities": "Yash Raj Films, Dharma Productions, TVF (The Viral Fever), Netflix India, pocket Aces, advertising production houses.",
            "higher_study_options": "Master's / Diploma in Film Direction & Editing (FTII Pune, SRFTI Kolkata).",
            "entrepreneurship_options": "Independent video production company, ad film production boutique, YouTube creator studio.",
            "source": "Film and Television Institute of India (FTII) / MESC",
            "official_url": "https://www.ftii.ac.in",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 21, "type": "COMMON"}, {"course_id": 33, "type": "ALTERNATIVE"}],
            "exams": [{"exam_id": 79, "importance": "PRIMARY"}],
            "routes": [{"title": "Path A: FTII / Film School to Video Producer", "type": "COMMON", "steps": "Graduation in any stream -> FTII JET (Joint Entrance Test) -> 3-Year Diploma in Editing / Direction at FTII Pune -> Commercial Video Producer."}],
            "ladder": [
                {"stage": "Assistant Video Editor / Camera Assistant", "exp": "0-2 Years", "desc": "Syncs audio, logs footage, creates rough assembly cuts, manages camera lenses."},
                {"stage": "Video Editor / Producer", "exp": "2-5 Years", "desc": "Cuts commercial ads, color grades in DaVinci, manages full video production shoot."},
                {"stage": "Senior Film Editor / Supervising Producer", "exp": "5-8 Years", "desc": "Edits feature films or OTT web series, works directly with top directors."},
                {"stage": "Executive Producer / Commercial Director", "exp": "8+ Years", "desc": "Directs high-budget television commercials, web series, and theatrical feature films."}
            ],
            "roadmaps": {
                "Class 10": "Start shooting and editing short films on your smartphone using CapCut or DaVinci Resolve.",
                "Class 12": "Choose any stream for Class 12 board exams.",
                "Graduation": "Complete graduation while building a video portfolio. Prepare for the Joint Entrance Test (JET) for FTII Pune or SRFTI Kolkata.",
                "Working Professional": "Master DaVinci Resolve color grading, narrative dramatic pacing, and commercial client directing."
            }
        },
        {
            "title": "Copywriter & Advertising Specialist",
            "short_name": "Copywriter",
            "slug": "copywriter-advertising-specialist",
            "category": "Media, Journalism & Digital Marketing",
            "sub_category": "Creative Advertising & Conceptual Copy",
            "industry": "Advertising & Creative Communications",
            "icon": "chat-quote",
            "short_description": "Crafts memorable advertising taglines, commercial scripts, and persuasive marketing copy that moves consumers to action.",
            "description": "Copywriters are the wordsmiths behind iconic advertising campaigns. They write television commercial scripts, radio jingles, print headlines, billboard punchlines, and digital brand anthems that define culture.",
            "what_they_do": "They interpret client advertising briefs, brainstorm creative campaign concepts alongside Art Directors, write TV commercial dialogues, craft catchy taglines, and write persuasive digital copy.",
            "day_to_day_work": "• Brainstorming creative campaign conceptual angles with Art Directors.\n• Writing 30-second television commercial (TVC) scripts and voiceovers.\n• Crafting witty billboard headlines and print magazine copy.\n• Pitching creative advertising ideas to corporate brand marketing managers.\n• Attending ad film shoots to make on-the-spot script adjustments with directors.",
            "work_environment": "Advertising agency creative departments, in-house creative brand labs.",
            "work_modes": "Hybrid / Creative Agency / Ad Shoots",
            "minimum_qualification": "Undergraduate (Any Stream + Creative Portfolio)",
            "preferred_streams": "Humanities / English / Commerce",
            "required_subjects": "English, Advertising, Creative Writing",
            "technical_skills": "Concept Ideation, Scriptwriting (TVC/Radio), Headline Writing, Brand Voice Definition, Storyboarding, Advertising Law",
            "soft_skills": "Wit, Linguistic Playfulness, Lateral Thinking, Empathy for Consumers, Thick Skin for Feedback",
            "tools": "Microsoft Word, Google Docs, Notion, Keynote, Final Draft",
            "certifications": "Miami Ad School / MICA Ahmedabad Fellowships",
            "experience_level": "Junior Copywriter to Executive Creative Director (ECD)",
            "career_growth": "Celebrated creative trajectory progressing to Creative Director, Executive Creative Director (ECD), or Chief Creative Officer (CCO).",
            "internship_roles": "Copywriting Trainee, Creative Agency Intern",
            "entry_level_roles": "Junior Copywriter, Copy Trainee, Creative Writer",
            "average_salary": "₹4.5 - ₹15 LPA (Indicative range)",
            "salary_indicative": "Junior Copywriter (0-2 yrs): ₹4 - 6.5 LPA | Creative Director (3-6 yrs): ₹10 - 20 LPA | Executive Creative Director (7+ yrs): ₹28 - 70+ LPA. Indicative figures from Advertising Agencies Association of India 2024.",
            "future_scope": "Enduring creative necessity where original, witty, culturally nuanced human writing cannot be automated by generic AI tools.",
            "government_opportunities": "Directorate of Advertising & Visual Publicity (DAVP / CBC), National Health Campaign Copywriting.",
            "private_opportunities": "Ogilvy India, McCann Worldgroup, Dentsu Creative, BBDO, Lowe Lintas, Leo Burnett India.",
            "higher_study_options": "M.A. in Advertising / MICA Ahmedabad Brand Communication Programs.",
            "entrepreneurship_options": "Boutique creative advertising hot-shop, brand naming and identity studio.",
            "source": "Advertising Agencies Association of India (AAAI) / MICA",
            "official_url": "https://aaai.in",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 21, "type": "COMMON"}, {"course_id": 46, "type": "COMMON"}],
            "exams": [{"exam_id": 79, "importance": "PRIMARY"}],
            "routes": [{"title": "Path A: Creative Portfolio to Top Ad Agency", "type": "COMMON", "steps": "Graduation in any stream -> Build spec portfolio of 5 creative mock advertising campaigns -> Agency creative test -> Junior Copywriter at Ogilvy / McCann."}],
            "ladder": [
                {"stage": "Junior Copywriter", "exp": "0-2 Years", "desc": "Writes social copy, radio scripts, assists senior creative directors on campaign pitches."},
                {"stage": "Senior Copywriter", "exp": "2-5 Years", "desc": "Authors iconic TV commercial scripts, creates multi-channel campaign taglines."},
                {"stage": "Creative Director (CD)", "exp": "5-8 Years", "desc": "Directs creative output for major multi-crore national brand accounts, leads pitch teams."},
                {"stage": "Chief Creative Officer (CCO)", "exp": "8+ Years", "desc": "Apex creative leader of advertising network, wins Cannes Lions and Effies awards."}
            ],
            "roadmaps": {
                "Class 10": "Read poetry, comic strips, punchlines, and memorize classic Indian advertising lines.",
                "Class 12": "Choose Humanities, Commerce, or Science with English for board exams.",
                "Graduation": "Complete graduation. Create mock 'spec' ad campaigns for brands you love showing creative problem-solving.",
                "Working Professional": "Apply to premier advertising agencies with your creative book (spec portfolio) or attend ad schools like Miami Ad School."
            }
        },
        {
            "title": "Technical Writer",
            "short_name": "Technical Writer",
            "slug": "technical-writer",
            "category": "Media, Journalism & Digital Marketing",
            "sub_category": "Technical Communication & Documentation",
            "industry": "Information Technology & Software",
            "icon": "file-code",
            "short_description": "Translates complex software architectures, APIs, and engineering systems into clear developer guides and user documentation.",
            "description": "Technical Writers create documentation that helps developers, system administrators, and everyday users understand and use complex software and hardware. They write developer API documentation, user manuals, release notes, and SDK tutorials.",
            "what_they_do": "They collaborate with software engineers, test APIs using Postman, write Markdown documentation in Git repositories (Docs-as-Code), generate API references using Swagger/OpenAPI, and maintain developer documentation portals.",
            "day_to_day_work": "• Testing REST APIs in Postman and documenting endpoints, headers, and response payloads.\n• Writing clear step-by-step developer integration tutorials in Markdown.\n• Managing documentation pull requests and version control in GitHub.\n• Reviewing release notes with product managers and QA leads prior to software releases.\n• Designing interactive API documentation portals using Docusaurus or GitBook.",
            "work_environment": "Global tech enterprises, SaaS startups, open-source software foundations.",
            "work_modes": "Remote / Hybrid / Office",
            "minimum_qualification": "Undergraduate (B.Tech / BCA / B.Sc CS / B.A. English with Tech Aptitude)",
            "preferred_streams": "Science (PCM) / Computer Applications / English",
            "required_subjects": "Computer Science, English",
            "technical_skills": "Docs-as-Code, Markdown, Git/GitHub, API Documentation (OpenAPI/Swagger), Basic Programming (JSON, Python/JS), Information Architecture, Docusaurus",
            "soft_skills": "Crystal-Clear Explanatory Writing, Intellectual Curiosity, Attention to Precision",
            "tools": "Git, GitHub, VS Code, Postman, Swagger, Docusaurus, Confluence, Markdown",
            "certifications": "Society for Technical Communication (STC) Certified Professional Technical Communicator (CPTC)",
            "experience_level": "Entry-Level to Senior",
            "career_growth": "Broad, stable tech career progressing to Lead Technical Writer, Documentation Architect, or Head of Developer Relations (DevRel).",
            "internship_roles": "Technical Writing Intern, Documentation Trainee",
            "entry_level_roles": "Associate Technical Writer, Junior Documentation Specialist",
            "average_salary": "₹5 - ₹14 LPA (Indicative range)",
            "salary_indicative": "Entry-Level (0-2 yrs): ₹4.5 - 7 LPA | Senior Technical Writer (3-6 yrs): ₹8.5 - 16 LPA | Documentation Architect (7+ yrs): ₹18 - 35+ LPA. Indicative figures from STC India 2024.",
            "future_scope": "Surging demand across developer-first software platforms, cloud infrastructure APIs (AWS, Stripe, Razorpay), and open-source ecosystems.",
            "government_opportunities": "CDAC Technical Documentation Wings, NIC Developer Portals, DRDO Technical Documentation.",
            "private_opportunities": "Google, Microsoft, Amazon, Cisco, Razorpay, Postman, Oracle, Red Hat India.",
            "higher_study_options": "Master's in Technical Communication, MCA, M.Tech in Software Engineering.",
            "entrepreneurship_options": "Technical documentation consultancy, developer relations content agency.",
            "source": "Society for Technical Communication (STC India)",
            "official_url": "https://www.stc.org",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 9, "type": "COMMON"}, {"course_id": 14, "type": "COMMON"}, {"course_id": 21, "type": "ALTERNATIVE"}],
            "exams": [{"exam_id": 8, "importance": "ALTERNATIVE"}],
            "routes": [{"title": "Path A: Tech Degree to Technical Writer", "type": "COMMON", "steps": "B.Tech CSE / BCA / B.Sc CS -> Learn Markdown, Git & API Documentation -> Contribute to open-source docs on GitHub -> Technical Writer."}],
            "ladder": [
                {"stage": "Associate Technical Writer", "exp": "0-2 Years", "desc": "Updates user guides, verifies API code snippets, formats Markdown documentation."},
                {"stage": "Technical Writer", "exp": "2-5 Years", "desc": "Documents complex cloud microservices APIs, designs developer quick-start guides."},
                {"stage": "Lead Documentation Architect", "exp": "5-8 Years", "desc": "Directs developer documentation portal (Docs-as-Code), oversees information architecture."},
                {"stage": "Head of Developer Experience / DevRel", "exp": "8+ Years", "desc": "Owns total developer onboarding journey, documentation tooling, and SDK guides."}
            ],
            "roadmaps": {
                "Class 10": "Learn basic coding and develop clear explanatory writing skills.",
                "Class 12": "Choose Science or Computer Science for board exams.",
                "Graduation": "Complete B.Tech CSE, BCA, or B.A. English with coding electives. Learn Git, Markdown, and test APIs with Postman.",
                "Working Professional": "Earn the STC certification and build a public GitHub portfolio of open-source software documentation."
            }
        },

        # --- EDUCATION (4) ---
        {
            "title": "Instructional Designer & Curriculum Developer",
            "short_name": "Instructional Designer",
            "slug": "instructional-designer",
            "category": "Education, Teaching & Academia",
            "sub_category": "Educational Technology & Instructional Design",
            "industry": "EdTech & Corporate Training",
            "icon": "journal-code",
            "short_description": "Designs effective digital learning experiences, interactive e-learning modules, and corporate training curricula using cognitive learning science.",
            "description": "Instructional Designers apply cognitive psychology and adult learning theories (ADDIE model, Bloom's Taxonomy) to design engaging digital learning programs. They transform dense academic and technical subject matter into interactive e-learning modules, microlearning videos, and simulations.",
            "what_they_do": "They analyze learning needs, create storyboards for digital courses, design interactive modules in Articulate Storyline, develop evaluation assessments, and manage Learning Management Systems (LMS).",
            "day_to_day_work": "• Analyzing target learner skill gaps and drafting learning objective frameworks.\n• Storyboarding interactive e-learning screens, scenarios, and quizzes.\n• Authoring e-learning modules in Articulate 360 and Adobe Captivate.\n• Collaborating with subject matter experts (SMEs), voiceover artists, and animators.\n• Uploading SCORM/xAPI packages to corporate LMS platforms and tracking completion rates.",
            "work_environment": "EdTech enterprises, corporate learning & development (L&D) divisions, university online learning centers.",
            "work_modes": "Remote / Hybrid / Office",
            "minimum_qualification": "Undergraduate (Any Stream) + Post Graduate Diploma in Instructional Design / M.Ed",
            "preferred_streams": "Any Stream (Education / Psychology / English / Tech)",
            "required_subjects": "Education, Cognitive Psychology, English",
            "technical_skills": "Instructional Design Models (ADDIE, SAM), Bloom's Taxonomy, Articulate Storyline 360, Storyboarding, SCORM/xAPI, LMS Administration, Microlearning",
            "soft_skills": "Pedagogical Empathy, Analytical Structuring, Creative Storytelling, Collaboration",
            "tools": "Articulate Storyline 360, Adobe Captivate, Moodle, Canvas, Camtasia, Canva",
            "certifications": "Certified Professional in Learning and Performance (ATD), PG Diploma in Instructional Design",
            "experience_level": "Entry-Level to Senior",
            "career_growth": "Broad career path progressing to Senior Instructional Designer, Lead Learning Architect, or Head of Learning & Development (L&D).",
            "internship_roles": "Instructional Design Intern, E-Learning Authoring Trainee",
            "entry_level_roles": "Junior Instructional Designer, E-Learning Developer, Content Developer",
            "average_salary": "₹4.5 - ₹12 LPA (Indicative range)",
            "salary_indicative": "Entry-Level (0-2 yrs): ₹4 - 6 LPA | Senior Instructional Designer (3-6 yrs): ₹7.5 - 14 LPA | Head of L&D / Learning Architect (7+ yrs): ₹18 - 36+ LPA. Indicative figures from Association for Talent Development (ATD) 2024.",
            "future_scope": "Surging demand driven by online university degrees, corporate workforce upskilling, and edtech platforms.",
            "government_opportunities": "SWAYAM Portal (Ministry of Education), NCERT CIET (Central Institute of Educational Technology), IGNOU.",
            "private_opportunities": "UpGrad, Coursera India, NIIT, Infosys Wingspan, Accenture L&D, corporate universities of major banks.",
            "higher_study_options": "M.Ed in Educational Technology, Master's in Instructional Systems Design.",
            "entrepreneurship_options": "Custom e-learning content studio, corporate training consultancy, digital course creation agency.",
            "source": "Association for Talent Development (ATD) / NCERT-CIET",
            "official_url": "https://ciet.ncert.gov.in",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 48, "type": "DIRECT"}, {"course_id": 21, "type": "COMMON"}],
            "exams": [{"exam_id": 79, "importance": "PRIMARY"}],
            "routes": [{"title": "Path A: Education / Humanities to Instructional Design", "type": "COMMON", "steps": "Graduation in any stream -> Post Graduate Diploma in Instructional Design (Symbiosis / SNDT) -> Master Articulate 360 -> E-Learning Instructional Designer."}],
            "ladder": [
                {"stage": "Junior Instructional Designer", "exp": "0-2 Years", "desc": "Builds Articulate Storyline screens, drafts quiz questions, storyboards simple modules."},
                {"stage": "Instructional Designer", "exp": "2-5 Years", "desc": "Interviews subject matter experts, applies ADDIE frameworks, designs gamified simulations."},
                {"stage": "Lead Learning Architect", "exp": "5-8 Years", "desc": "Directs curriculum design for enterprise certification academies, manages ID teams."},
                {"stage": "Head of Learning & Development (L&D)", "exp": "8+ Years", "desc": "Owns corporate enterprise skill strategy, executive leadership academies, and learning budgets."}
            ],
            "roadmaps": {
                "Class 10": "Explore how online tutorials, explainer videos, and learning apps make education easy to understand.",
                "Class 12": "Choose any stream for board exams.",
                "Graduation": "Complete graduation in Education, English, Psychology, or Computer Applications. Study Bloom's Taxonomy and the ADDIE model.",
                "Working Professional": "Master Articulate Storyline 360, create an e-learning module portfolio, and earn ATD certification."
            }
        },
        {
            "title": "Special Education Teacher",
            "short_name": "Special Educator",
            "slug": "special-education-teacher",
            "category": "Education, Teaching & Academia",
            "sub_category": "Inclusive & Special Education",
            "industry": "Inclusive Education & Rehabilitation",
            "icon": "universal-access-circle",
            "short_description": "Educates children with special learning needs, autism, intellectual disabilities, ADHD, and sensory impairments using adaptive pedagogies.",
            "description": "Special Education Teachers are certified professionals who adapt general education curricula to meet the unique learning needs of students with neurodevelopmental, physical, or cognitive differences. Under RCI mandates and the RPwD Act 2016, they champion inclusive education.",
            "what_they_do": "They formulate Individualized Education Programs (IEP), teach braille and sign language, adapt academic exams, use sensory multisensory learning aids, and collaborate with parents, speech therapists, and clinical psychologists.",
            "day_to_day_work": "• Formulating and tracking Individualized Education Programs (IEP) for each student.\n• Delivering multisensory lessons for students with autism, dyslexia, or ADHD.\n• Adapting school learning materials, font sizes, and worksheets for low-vision pupils.\n• Supporting inclusive classrooms alongside mainstream school teachers.\n• Conducting counseling sessions with parents to reinforce home learning strategies.",
            "work_environment": "Inclusive mainstream schools, special education resource rooms, child rehabilitation centers.",
            "work_modes": "On-site / School Hours / Clinical Resource Room",
            "minimum_qualification": "Undergraduate (B.Ed in Special Education from an RCI-recognized institute)",
            "preferred_streams": "Any Stream",
            "required_subjects": "Special Education, Psychology",
            "technical_skills": "Individualized Education Program (IEP) Design, Braille Instruction, Indian Sign Language (ISL), Multisensory Pedagogy, Behavioral Modification, RPwD Act 2016",
            "soft_skills": "Supreme Patience, Deep Unconditional Empathy, Resilience, Encouraging Positivity",
            "tools": "Tactile Learning Aids, Braille Slates, Adaptive Keyboards, Sensory Room Equipment, Visual Schedules",
            "certifications": "Rehabilitation Council of India (RCI) License as Registered Special Educator",
            "experience_level": "Entry-Level to Senior",
            "career_growth": "Noble career path progressing to Head of Inclusive Education, School Vice-Principal, or Director of Child Rehabilitation.",
            "internship_roles": "Special Education School Internship (Integrated in B.Ed Special Education)",
            "entry_level_roles": "Special Educator, Resource Teacher, Learning Support Specialist",
            "average_salary": "₹4 - ₹9 LPA (Indicative range)",
            "salary_indicative": "Special Educator (0-2 yrs): ₹3.5 - 5 LPA | Senior Inclusive Lead (3-6 yrs): ₹6 - 10 LPA | Head of Inclusive Center (7+ yrs): ₹12 - 25+ LPA. Indicative figures from RCI 2024.",
            "future_scope": "Surging demand as the Supreme Court mandates special educators in every school and NEP 2020 prioritizes full inclusion.",
            "government_opportunities": "Kendriya Vidyalayas, State Government Inclusive Education Samagra Shiksha wings, National Institutes (NIEPVD, NIEPID).",
            "private_opportunities": "DPS, Ryan, inclusive private international schools, child development foundations, private resource centers.",
            "higher_study_options": "M.Ed in Special Education, Ph.D. in Disability Studies.",
            "entrepreneurship_options": "Special education learning center, inclusive child development academy.",
            "source": "Rehabilitation Council of India (RCI) / Ministry of Social Justice and Empowerment",
            "official_url": "https://www.rehabcouncil.nic.in",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 48, "type": "DIRECT"}],
            "exams": [{"exam_id": 25, "importance": "PRIMARY"}, {"exam_id": 86, "importance": "PRIMARY"}],
            "routes": [{"title": "Path A: B.Ed Special Education to RCI License", "type": "COMMON", "steps": "Graduation in any stream (50%+) -> B.Ed in Special Education (Learning Disability / Autism / Visual / Hearing) from RCI-recognized institute -> RCI Registration -> Licensed Special Educator."}],
            "ladder": [
                {"stage": "Junior Special Educator", "exp": "0-2 Years", "desc": "Implements IEP goals, conducts remedial reading sessions, assists in resource rooms."},
                {"stage": "Special Educator / Case Lead", "exp": "2-5 Years", "desc": "Designs independent IEPs, coordinates accommodations for board examinations."},
                {"stage": "Head of Inclusive Education", "exp": "5-8 Years", "desc": "Directs school-wide inclusive policy, trains mainstream teachers on differentiation."},
                {"stage": "Director of Child Rehabilitation / NGO Founder", "exp": "8+ Years", "desc": "Owns multidisciplinary special education and child development centers."}
            ],
            "roadmaps": {
                "Class 10": "Develop empathy, patience, and kindness towards children with special needs.",
                "Class 12": "Choose any stream for Class 12 board exams.",
                "Graduation": "Complete graduation in any stream. Enroll in a 2-year RCI-approved B.Ed in Special Education (ID / ASD / LD).",
                "Working Professional": "Register with the Rehabilitation Council of India (RCI) and master modern Assistive Technologies for learning."
            }
        },

        # --- FINANCE (Remaining 4) ---
        {
            "title": "Forensic Accountant & Fraud Investigator",
            "short_name": "Forensic Accountant",
            "slug": "forensic-accountant",
            "category": "Finance, Banking & Accounting",
            "sub_category": "Financial Crime & Forensic Auditing",
            "industry": "Financial Investigation & Forensic Auditing",
            "icon": "search",
            "short_description": "Investigates financial crimes, corporate fraud, money laundering, and embezzlements to provide expert witness testimony in court.",
            "description": "Forensic Accountants are the financial detectives of the corporate world. They reconstruct falsified accounting ledgers, trace diverted corporate funds across offshore shell companies, investigate banking fraud, and testify as expert witnesses in economic offenses courts.",
            "what_they_do": "They analyze bank transactions and accounting data for fraud indicators, interview corporate employees suspected of embezzlement, perform digital forensic email reviews, and author investigative reports for law enforcement agencies.",
            "day_to_day_work": "• Reconstructing manipulated general ledgers and hidden accounting entries.\n• Tracing illicit fund flows through offshore accounts and shell entities.\n• Conducting forensic investigative interviews with corporate suspects.\n• Extracting and analyzing digital accounting evidence using forensic software.\n• Preparing formal forensic audit reports for filing before courts and the Serious Fraud Investigation Office (SFIO).",
            "work_environment": "Forensic accounting advisory firms, Big 4 forensic teams, law enforcement bureaus.",
            "work_modes": "Hybrid / On-site / Corporate Client Audits",
            "minimum_qualification": "Professional Qualification (Chartered Accountant / Certified Fraud Examiner - CFE)",
            "preferred_streams": "Commerce / Finance / Law",
            "required_subjects": "Accountancy, Auditing, Commercial Law",
            "technical_skills": "Forensic Auditing, Fraud Investigation, Digital Evidence Preservation, Fund Trail Analysis, Benami Transaction Tracking, PMLA Act",
            "soft_skills": "Investigative Skepticism, Tenacity, Uncompromising Integrity, Discretion",
            "tools": "IDEA Data Analysis, ACL Analytics, EnCase Forensic, Microsoft Excel, i2 Analyst's Notebook",
            "certifications": "Certified Fraud Examiner (CFE - ACFE), Forensic Accounting and Fraud Detection (FAFD - ICAI)",
            "experience_level": "Entry-Level to Senior",
            "career_growth": "High-prestige career progressing to Forensic Partner, Head of Financial Crime Investigation, or Independent Expert Witness.",
            "internship_roles": "Forensic Audit Intern, Financial Crime Trainee",
            "entry_level_roles": "Forensic Accounting Associate, Fraud Analyst",
            "average_salary": "₹7 - ₹18 LPA (Indicative range)",
            "salary_indicative": "Forensic Associate (0-2 yrs): ₹6 - 9 LPA | Forensic Manager (3-6 yrs): ₹12 - 22 LPA | Forensic Partner / Director (7+ yrs): ₹28 - 65+ LPA. Indicative figures from ACFE India 2024.",
            "future_scope": "Surging demand driven by Insolvency and Bankruptcy Code (IBC) forensic audits, banking NPA investigations, and anti-money laundering enforcement.",
            "government_opportunities": "Serious Fraud Investigation Office (SFIO), Enforcement Directorate (ED), Central Bureau of Investigation (CBI Economic Offences Wing), SEBI.",
            "private_opportunities": "Big 4 Forensic Services (Deloitte, PwC, EY, KPMG), Alvarez & Marsal, Kroll, Grant Thornton, forensic risk consultancies.",
            "higher_study_options": "Master's in Forensic Accounting, CFE Certification, Law Degree (LLB).",
            "entrepreneurship_options": "Independent forensic accounting firm, corporate fraud intelligence agency.",
            "source": "Association of Certified Fraud Examiners (ACFE) / ICAI FAFD",
            "official_url": "https://www.acfe.com",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 16, "type": "COMMON"}, {"course_id": 30, "type": "ALTERNATIVE"}],
            "exams": [{"exam_id": 92, "importance": "PRIMARY"}],
            "routes": [{"title": "Path A: Chartered Accountant + CFE Route", "type": "COMMON", "steps": "Clear CA / B.Com -> Complete ICAI Certificate on Forensic Accounting & Fraud Detection (FAFD) -> Clear CFE exam -> Forensic Auditor."}],
            "ladder": [
                {"stage": "Forensic Associate", "exp": "0-2 Years", "desc": "Analyzes bank statements for round-tripping, tags suspicious journal entries, indexes digital evidence."},
                {"stage": "Forensic Investigator / Manager", "exp": "2-5 Years", "desc": "Conducts witness interviews, traces benami assets, drafts comprehensive court-ready forensic reports."},
                {"stage": "Senior Director - Forensic Practice", "exp": "5-8 Years", "desc": "Leads multi-thousand-crore bank fraud investigations, serves as expert witness before NCLT/CBI courts."},
                {"stage": "Forensic Partner / Practice Head", "exp": "8+ Years", "desc": "Heads firm's dispute and investigation practice, advises corporate boards on crisis fraud management."}
            ],
            "roadmaps": {
                "Class 10": "Develop sharp investigative curiosity, attention to detail, and mathematical problem-solving.",
                "Class 12": "Choose Commerce with Accountancy and Mathematics for board exams.",
                "Graduation": "Complete B.Com and pursue CA or LLB. Master accounting manipulation detection and bank statement reconciliation.",
                "Working Professional": "Earn the Certified Fraud Examiner (CFE) credential and learn computer-assisted auditing tools (IDEA, ACL)."
            }
        },
        {
            "title": "Fintech Product Specialist",
            "short_name": "Fintech Specialist",
            "slug": "fintech-product-specialist",
            "category": "Finance, Banking & Accounting",
            "sub_category": "Financial Technology & Digital Payments",
            "industry": "Financial Technology (Fintech) & Banking",
            "icon": "phone-flip",
            "short_description": "Designs and scales digital payment architectures, lending algorithms, neo-banking apps, and UPI financial infrastructure.",
            "description": "Fintech Product Specialists bridge financial regulations and technology. They build innovative financial products: UPI payment gateways, digital lending micro-loans, robo-advisory platforms, and neo-banking mobile apps that transform how citizens transact.",
            "what_they_do": "They design digital payment flows, integrate core banking APIs, optimize lending underwriting risk algorithms, ensure RBI digital lending and PPI compliance, and build high-conversion checkout experiences.",
            "day_to_day_work": "• Designing UPI, credit line, or wallet checkout user flows.\n• Integrating payment gateway APIs and banking webhooks with engineers.\n• Modeling automated digital lending credit criteria with risk analysts.\n• Auditing compliance against RBI digital payment guidelines and KYC norms.\n• Tracking payment success rates, drop-offs, and transaction latency.",
            "work_environment": "Fintech unicorn headquarters, modern digital banking tech hubs, or remote.",
            "work_modes": "Hybrid / Tech Office / Remote",
            "minimum_qualification": "Undergraduate (B.Tech / BBA / B.Com) + Fintech Knowledge",
            "preferred_streams": "Engineering / Commerce / Computer Applications",
            "required_subjects": "Finance, Computer Science, Economics",
            "technical_skills": "Digital Payments (UPI, IMPS, Cards), API Banking, Digital Lending Regulations, Underwriting Algorithms, Product Lifecycle, SQL",
            "soft_skills": "User Empathy, Problem Solving, Regulatory Awareness, Cross-Functional Collaboration",
            "tools": "Jira, Postman, SQL, Figma, Amplitude, Metabase",
            "certifications": "Fintech Certifications from IIMs / IITs, Certified Scrum Product Owner",
            "experience_level": "Entry-Level to Senior",
            "career_growth": "Rapid growth progressing to Senior Fintech PM, VP of Payments, or Chief Fintech Officer.",
            "internship_roles": "Fintech Product Intern, Digital Banking Trainee",
            "entry_level_roles": "Associate Product Manager (Fintech), Product Analyst, Payment Operations Associate",
            "average_salary": "₹7 - ₹22 LPA (Indicative range)",
            "salary_indicative": "APM (0-2 yrs): ₹6 - 11 LPA | Fintech Product Manager (3-6 yrs): ₹14 - 26 LPA | VP Payments / CPO (7+ yrs): ₹30 - 75+ LPA. Indicative figures from Indian Fintech Placement Audits 2024.",
            "future_scope": "World-leading growth powered by India's digital public infrastructure (India Stack, UPI, Account Aggregator, ONDC).",
            "government_opportunities": "National Payments Corporation of India (NPCI), Reserve Bank Innovation Hub (RBIH), UIDAI.",
            "private_opportunities": "Razorpay, PhonePe, Paytm, CRED, Pine Labs, Groww, Zerodha, Jupiter, standard private digital banking wings.",
            "higher_study_options": "MBA in Finance & Technology, Master's in Financial Technology.",
            "entrepreneurship_options": "Founding an innovative fintech startup (embedded finance, cross-border remittance, SME credit).",
            "source": "Fintech Association for Consumer Empowerment (FACE) / NPCI",
            "official_url": "https://www.npci.org.in",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 9, "type": "COMMON"}, {"course_id": 14, "type": "COMMON"}, {"course_id": 16, "type": "COMMON"}, {"course_id": 18, "type": "SPECIALIZED"}],
            "exams": [{"exam_id": 8, "importance": "ALTERNATIVE"}, {"exam_id": 77, "importance": "ALTERNATIVE"}],
            "routes": [{"title": "Path A: Tech / Finance Degree to Fintech PM", "type": "COMMON", "steps": "B.Tech / B.Com -> Understand UPI protocols & payment gateway APIs -> Product Analyst in Fintech -> Fintech Product Manager."}],
            "ladder": [
                {"stage": "Fintech Product Analyst", "exp": "0-2 Years", "desc": "Monitors payment transaction success rates, logs API integration bugs, tests user KYC flows."},
                {"stage": "Fintech Product Manager", "exp": "2-5 Years", "desc": "Owns payment gateway or digital lending product lines, leads engineering sprints, ensures RBI compliance."},
                {"stage": "Head of Payments / Lending", "exp": "5-8 Years", "desc": "Directs core business vertical processing thousands of crores monthly, negotiates banking alliances."},
                {"stage": "Chief Product Officer (CPO) / Fintech Founder", "exp": "8+ Years", "desc": "Sets enterprise fintech vision, raises venture capital, shapes digital public finance."}
            ],
            "roadmaps": {
                "Class 10": "Observe how UPI, QR codes, and digital wallets function in daily life.",
                "Class 12": "Choose Commerce or Science with Mathematics or Computer Science.",
                "Graduation": "Complete B.Tech, B.Com, or BCA. Study how banking APIs work and test payment sandboxes (Razorpay / Cashfree APIs).",
                "Working Professional": "Master RBI digital lending guidelines, Account Aggregator frameworks, and financial product metrics."
            }
        },

        # --- DESIGN (Remaining 2) ---
        {
            "title": "Commercial Photographer & Cinematographer",
            "short_name": "Commercial Photographer",
            "slug": "commercial-photographer",
            "category": "Design, Animation & Creative Arts",
            "sub_category": "Photography, Imaging & Visual Arts",
            "industry": "Commercial Photography & Advertising",
            "icon": "camera",
            "short_description": "Creates professional high-end photographic imagery for commercial advertising, fashion campaigns, luxury architecture, and editorial media.",
            "description": "Commercial Photographers master lighting, visual composition, camera optics, and post-processing to create images that sell products and define luxury brands. They specialize in fashion photography, commercial food styling, automotive shoots, and architectural interiors.",
            "what_they_do": "They design studio strobe lighting setups, direct commercial model shoots, operate medium-format digital camera systems, retouch and color-grade RAW imagery in Capture One, and deliver high-resolution commercial assets.",
            "day_to_day_work": "• Setting up studio strobe lights, softboxes, and reflectors for commercial product shoots.\n• Directing fashion models and commercial actors during editorial shoots.\n• Tethering high-resolution medium format cameras to digital monitors for client review.\n• Retouching skin blemishes, color grading, and compositing in Photoshop.\n• Pitching creative visual concepts to advertising art directors.",
            "work_environment": "Commercial photography studios, outdoor location sets, advertising client sets.",
            "work_modes": "On-site / Studio & Field Shoots / Flexible Commercial Schedule",
            "minimum_qualification": "Undergraduate (Degree / Diploma in Photography / Fine Arts + Visual Portfolio)",
            "preferred_streams": "Any Stream",
            "required_subjects": "Photography, Visual Arts, Physics of Light",
            "technical_skills": "Studio Strobe Lighting, Medium Format Digital Backs, Raw Processing (Capture One), Retouching (Photoshop), Composition, Commercial Licensing",
            "soft_skills": "Visual Empathy, Client Direction, Creative Eye, High Detail Orientation",
            "tools": "Digital Cinema & Medium Format Cameras (Phase One, Hasselblad, Sony A7R), Studio Strobes (Profoto), Capture One, Photoshop",
            "certifications": "All India Photographers Union / Master Photography Credentials",
            "experience_level": "Assistant Photographer to Celebrity Commercial Photographer",
            "career_growth": "Celebrity path progressing to Ace Fashion/Ad Photographer, Film Cinematographer, or Commercial Studio Director.",
            "internship_roles": "Lighting Assistant, Digital Tech Intern, Second Camera Operator",
            "entry_level_roles": "Assistant Photographer, Digital Retoucher, Studio Assistant",
            "average_salary": "₹4 - ₹15 LPA (Indicative range - plus commercial client day-rates)",
            "salary_indicative": "Assistant Photographer (0-2 yrs): ₹3 - 5 LPA | Commercial Photographer (3-6 yrs): ₹8 - 18 LPA | Established Advertising / Celebrity Photographer (7+ yrs): ₹30 - 80+ LPA (charging ₹1-5 Lakhs per day of shoot). Indicative figures from MESC 2024.",
            "future_scope": "Continuous strong demand across e-commerce product imagery, luxury fashion, real estate architectural showcases, and advertising.",
            "government_opportunities": "Photo Division of India (Ministry of Information & Broadcasting), Archaeological Survey of India (ASI Documentation).",
            "private_opportunities": "Vogue India, Harper's Bazaar, advertising agencies (Ogilvy, Dentsu), e-commerce brands (Myntra, Nykaa, Amazon).",
            "higher_study_options": "Master of Fine Arts (MFA) in Photography, International Masterclasses.",
            "entrepreneurship_options": "Independent commercial photography studio, visual production rental house, fine art photography gallery.",
            "source": "Media & Entertainment Skills Council (MESC) / Photo Division",
            "official_url": "https://mescindia.org",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 33, "type": "ALTERNATIVE"}, {"course_id": 21, "type": "COMMON"}],
            "exams": [{"exam_id": 79, "importance": "PRIMARY"}],
            "routes": [{"title": "Path A: Apprentice to Commercial Photographer", "type": "COMMON", "steps": "Degree/Diploma in Photography or Fine Arts -> Work 2-3 years as lighting assistant to a top commercial photographer -> Build commercial portfolio -> Independent Commercial Photographer."}],
            "ladder": [
                {"stage": "Assistant Photographer / Digital Tech", "exp": "0-2 Years", "desc": "Sets up Profoto lighting stands, manages tethered capture in Capture One, handles camera lenses."},
                {"stage": "Commercial Photographer", "exp": "2-5 Years", "desc": "Shoots catalogue and e-commerce campaigns, manages studio lighting setups, retouches assets."},
                {"stage": "Senior Advertising / Fashion Photographer", "exp": "5-9 Years", "desc": "Shoots national billboard campaigns, magazine covers, commands premium commercial day rates."},
                {"stage": "Celebrity Photographer / Visual Director", "exp": "9+ Years", "desc": "Celebrated master artist, shoots international luxury campaigns, directs cinematic visual identity."}
            ],
            "roadmaps": {
                "Class 10": "Learn the exposure triangle (Aperture, Shutter Speed, ISO) on a manual DSLR or mirrorless camera.",
                "Class 12": "Choose any stream for Class 12 board exams.",
                "Graduation": "Complete a degree in Visual Arts or Photography, or apprentice directly under an established commercial photographer.",
                "Working Professional": "Master studio lighting (key, fill, rim lighting) and build a portfolio website displaying fashion, architecture, or product photography."
            }
        }
    ]

print("Catalog builder part 11 ready.")
