"""
scripts/catalog_builder_part2.py
Authentic occupational profiles for Law, Government, and Business & Management sectors.
"""

def get_law_remaining():
    return [
        {
            "title": "Legal Advisor / In-House Counsel",
            "short_name": "In-House Counsel",
            "slug": "in-house-counsel",
            "category": "Law & Legal Services",
            "sub_category": "Corporate & Commercial Law",
            "industry": "Corporate Legal Departments",
            "icon": "building-check",
            "short_description": "Serves as the internal legal counsel for a corporation, managing commercial contracts, risk mitigation, and regulatory compliance.",
            "description": "In-House Legal Counsels work directly inside corporations. Unlike law firm lawyers who service multiple clients, in-house lawyers partner with internal business teams (sales, engineering, HR, marketing) to review commercial agreements, protect proprietary IP, resolve employment disputes, and minimize legal liabilities.",
            "what_they_do": "They draft and negotiate customer and vendor contracts, oversee intellectual property protection, advise executive management on corporate risk, manage external litigation counsel, and ensure adherence to local and international business regulations.",
            "day_to_day_work": "• Reviewing, drafting, and redlining commercial Master Services Agreements (MSAs).\n• Advising product teams on privacy laws (DPDP Act, GDPR) and terms of service.\n• Managing corporate disputes, cease-and-desist notices, and pre-litigation settlements.\n• Partnering with HR on employment law compliance, termination policies, and POSH audits.\n• Briefing external litigation advocates on ongoing court proceedings.",
            "work_environment": "Corporate headquarters of multinational corporations, technology startups, conglomerates.",
            "work_modes": "Hybrid / Corporate Office",
            "minimum_qualification": "Undergraduate (BA LLB / BBA LLB / LLB)",
            "preferred_streams": "Any Stream",
            "required_subjects": "Law, English, Business Studies",
            "technical_skills": "Commercial Contract Drafting, Regulatory Compliance, Employment Law, IP Protection, Risk Mitigation, Dispute Resolution",
            "soft_skills": "Business Acumen, Pragmatic Risk Balancing, Negotiation, Clear Executive Communication",
            "tools": "Contract Lifecycle Management (CLM) Software, DocuSign, Microsoft Word, SCC Online",
            "certifications": "Bar Council of India Enrolment",
            "experience_level": "Entry-Level to Senior",
            "career_growth": "Direct executive progression to Legal Director, VP Legal, or General Counsel (GC).",
            "internship_roles": "In-House Legal Intern, Corporate Legal Trainee",
            "entry_level_roles": "Legal Executive, Associate Legal Counsel, Contract Specialist",
            "average_salary": "₹6 - ₹18 LPA (Indicative range)",
            "salary_indicative": "Entry-Level Counsel (0-2 yrs): ₹5.5 - 9 LPA | Senior Legal Counsel (3-6 yrs): ₹12 - 24 LPA | General Counsel (7+ yrs): ₹28 - 75+ LPA. Indicative figures from Indian Corporate Counsel Association (ICCA) 2024.",
            "future_scope": "Growing exponentially as modern companies bring legal functions in-house to reduce external law firm billing.",
            "government_opportunities": "Legal Officer in Public Sector Undertakings (ONGC, BHEL, NTPC, IOCL via CLAT PG).",
            "private_opportunities": "Tata Group, Reliance Industries, Google India, Microsoft India, Flipkart, Swiggy, Infosys.",
            "higher_study_options": "LLM in Corporate Law / International Business Law, Executive MBA.",
            "entrepreneurship_options": "Legal-tech contract management agency, fractional General Counsel consulting.",
            "source": "Indian Corporate Counsel Association (ICCA) / BCI",
            "official_url": "https://www.barcouncilofindia.org",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 29, "type": "DIRECT"}, {"course_id": 30, "type": "DIRECT"}, {"course_id": 31, "type": "SPECIALIZED"}],
            "exams": [{"exam_id": 75, "importance": "PRIMARY"}, {"exam_id": 76, "importance": "PRIMARY"}],
            "routes": [{"title": "Path A: Law Degree to In-House Counsel", "type": "COMMON", "steps": "5-Year or 3-Year LLB -> 2-3 years at a corporate law firm or direct in-house hire -> In-House Legal Counsel."}],
            "ladder": [
                {"stage": "Legal Executive / Contract Specialist", "exp": "0-2 Years", "desc": "Reviews standard NDAs, vendor contracts, maintains company contract repository."},
                {"stage": "Legal Counsel", "exp": "2-5 Years", "desc": "Negotiates customer master agreements, advises product teams on regulatory compliance."},
                {"stage": "Senior Legal Counsel / Lead", "exp": "5-8 Years", "desc": "Heads commercial legal for business division, handles complex disputes and IP licensing."},
                {"stage": "General Counsel / VP Legal", "exp": "8+ Years", "desc": "Member of corporate executive committee, reports directly to CEO / Board of Directors."}
            ],
            "roadmaps": {
                "Class 10": "Develop strong English reading, writing, and logical comprehension.",
                "Class 12": "Prepare for CLAT / AILET or choose Commerce/Humanities.",
                "Graduation": "Complete LLB with focus on Contract Law, Company Law, and Intellectual Property. Intern at both corporate legal departments and law firms.",
                "Working Professional": "Master Contract Lifecycle Management (CLM) tools, commercial negotiation, and data privacy regulations (DPDP Act)."
            }
        },
        {
            "title": "Cyber Law Specialist",
            "short_name": "Cyber Lawyer",
            "slug": "cyber-law-specialist",
            "category": "Law & Legal Services",
            "sub_category": "Technology, Cyber & Privacy Law",
            "industry": "Information Technology / Legal Services",
            "icon": "shield-lock-fill",
            "short_description": "Advises on data protection, privacy compliance, cyber crime prosecution, electronic evidence, and digital technology regulations.",
            "description": "Cyber Lawyers specialize in the intersection of digital technology and the legal system. They advise on data privacy compliance (India's Digital Personal Data Protection Act 2023, EU GDPR), cyber crime investigation, electronic contracts, and online intermediary liability.",
            "what_they_do": "They draft data protection policies and privacy terms, advise on cybersecurity incident disclosure, handle cyber crime complaints before police cyber cells, and represent clients in technology disputes.",
            "day_to_day_work": "• Auditing corporate privacy policies against the Digital Personal Data Protection (DPDP) Act 2023.\n• Advising corporate security teams on legal reporting of cyber incidents to CERT-In.\n• Drafting Data Processing Agreements (DPAs) and cloud cross-border transfer contracts.\n• Representing victims of online financial fraud or corporate data theft.\n• Adducing electronic records and Section 65B evidence certificates before courts.",
            "work_environment": "Corporate law firms, tech corporate headquarters, specialized cyber law chambers.",
            "work_modes": "Hybrid / Office",
            "minimum_qualification": "Undergraduate (LLB / BA LLB)",
            "preferred_streams": "Any Stream (Science / CS background advantageous)",
            "required_subjects": "Law, Computer Science (helpful)",
            "technical_skills": "Information Technology Act 2000, DPDP Act 2023, GDPR, Electronic Evidence (BSA), Cyber Crime Investigation, Cloud Contracts",
            "soft_skills": "Technological Curiosity, Fast Analytical Problem Solving, Clear Advisory",
            "tools": "Digital Forensics Reports, CERT-In Incident Reporting Portal, SCC Online",
            "certifications": "Certified Information Privacy Professional (CIPP/A), Post Graduate Diploma in Cyber Law",
            "experience_level": "Entry-Level to Senior",
            "career_growth": "Rapid growth with transition to Data Protection Officer (DPO), Tech Law Partner, or Cyber Legal Director.",
            "internship_roles": "Cyber Law Intern, Tech Policy Intern, Privacy Advisory Intern",
            "entry_level_roles": "Junior Cyber Lawyer, Privacy Analyst, Tech Legal Associate",
            "average_salary": "₹5.5 - ₹16 LPA (Indicative range)",
            "salary_indicative": "Entry-Level Associate (0-2 yrs): ₹5 - 8 LPA | Senior Cyber Counsel / DPO (3-6 yrs): ₹10 - 20 LPA | Tech Law Partner (7+ yrs): ₹25 - 60+ LPA. Indicative figures from Data Security Council of India (DSCI) 2024.",
            "future_scope": "Surging national priority driven by India's DPDP Act 2023, AI regulation, and escalating cyber warfare risks.",
            "government_opportunities": "CERT-In Legal Wing, National Cyber Security Coordinator (NCSC), Police Cyber Cells, MeitY Legal Cell.",
            "private_opportunities": "Top law firms (Trilegal, CAM, SAM), Google, Meta, Microsoft, Amazon, Big 4 privacy consultancies.",
            "higher_study_options": "LLM in Technology & Cyber Law, CIPP/E / CIPP/A Privacy Certifications.",
            "entrepreneurship_options": "Independent cyber law boutique firm, data protection compliance consultancy.",
            "source": "Data Security Council of India (DSCI) / MeitY",
            "official_url": "https://www.dsci.in",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 29, "type": "DIRECT"}, {"course_id": 30, "type": "DIRECT"}, {"course_id": 31, "type": "SPECIALIZED"}],
            "exams": [{"exam_id": 75, "importance": "PRIMARY"}, {"exam_id": 76, "importance": "PRIMARY"}],
            "routes": [{"title": "Path A: Law Degree with Cyber Law Specialization", "type": "COMMON", "steps": "LLB -> Specialization in IT Act 2000 & DPDP Act 2023 -> Earn CIPP certification -> Tech / Privacy Lawyer."}],
            "ladder": [
                {"stage": "Junior Cyber Legal Associate", "exp": "0-2 Years", "desc": "Drafts basic website privacy policies, reviews cookie consent flows, assists in cyber fraud filings."},
                {"stage": "Privacy Counsel / Cyber Lawyer", "exp": "2-5 Years", "desc": "Conducts Data Protection Impact Assessments (DPIA), advises on CERT-In compliance."},
                {"stage": "Data Protection Officer (DPO) / Tech Partner", "exp": "5-8 Years", "desc": "Statutory head of enterprise data privacy, leads multi-jurisdiction technology litigation."},
                {"stage": "Chief Privacy Officer / Global Policy Head", "exp": "8+ Years", "desc": "Shapes international tech governance frameworks, advises national government cyber committees."}
            ],
            "roadmaps": {
                "Class 10": "Learn how the internet, personal data, and cybersecurity work.",
                "Class 12": "Prepare for CLAT / law entrance exams with interest in digital technology.",
                "Graduation": "Complete LLB with specialized electives in Cyber Law, Intellectual Property, and Artificial Intelligence regulations.",
                "Working Professional": "Earn the CIPP (Certified Information Privacy Professional) credential and master compliance under the DPDP Act 2023."
            }
        },
        {
            "title": "Intellectual Property (IP) Attorney",
            "short_name": "IP Attorney",
            "slug": "ip-attorney",
            "category": "Law & Legal Services",
            "sub_category": "Intellectual Property & Patents",
            "industry": "Legal Services / IP & Patents",
            "icon": "lightbulb-fill",
            "short_description": "Protects and enforces rights to intellectual creations, patents, trademarks, copyrights, and industrial trade secrets.",
            "description": "Intellectual Property (IP) Attorneys help inventors, artists, and corporations secure and defend their legal rights to patents, brand trademarks, artistic copyrights, and design patents. They prosecute patent applications and litigate infringement in High Courts.",
            "what_they_do": "They draft patent specifications, conduct prior-art searches, register brand trademarks, litigate trademark and copyright infringement, and draft patent licensing and royalty agreements.",
            "day_to_day_work": "• Drafting comprehensive patent claims and technical specifications.\n• Conducting trademark availability and prior-art patentability searches.\n• Filing trademark and patent applications before the Indian Patent Office (CGPDTM).\n• Arguing opposition hearings before the Controller of Patents and Trademarks.\n• Drafting cease-and-desist notices and injunction lawsuits for counterfeit products.",
            "work_environment": "Specialized IP law firms, corporate patent departments, High Court chambers.",
            "work_modes": "Hybrid / Office / Courtroom",
            "minimum_qualification": "Undergraduate (LLB) + Science/Engg degree (mandatory for Registered Patent Agent)",
            "preferred_streams": "Science (PCM / PCB) + Law",
            "required_subjects": "Science / Engineering + Law Degree",
            "technical_skills": "Patent Drafting, Trademark Law, Copyright Infringement, Prior Art Search, Patent Agent Exam, IP Licensing, Trade Secrets",
            "soft_skills": "Technical Curiosity, Analytical Precision, Persuasive Drafting, Scientific Skepticism",
            "tools": "Indian Patent Registry Portal, USPTO Database, Google Patents, WIPO Patentscope",
            "certifications": "Registered Patent Agent (Indian Patent Office), Bar Council of India Enrolment",
            "experience_level": "Entry-Level to Senior",
            "career_growth": "High career path progressing to IP Partner, Head of Corporate IP, or Intellectual Property Judge.",
            "internship_roles": "Patent Drafting Intern, Trademark Intern, IP Litigation Intern",
            "entry_level_roles": "Patent Analyst, Trademark Associate, Junior IP Attorney",
            "average_salary": "₹6 - ₹18 LPA (Indicative range)",
            "salary_indicative": "Entry-Level Associate (0-2 yrs): ₹5.5 - 8 LPA | Senior IP Counsel (3-6 yrs): ₹10 - 20 LPA | IP Partner (7+ yrs): ₹25 - 65+ LPA. Indicative figures from Intellectual Property India & Leading IP Law Firms 2024.",
            "future_scope": "Booming national growth driven by India's record patent filings, biotechnology innovations, semiconductor layout designs, and startup trademarking.",
            "government_opportunities": "Examiner of Patents & Designs (CGPDTM - UPSC), Controller of Patents, Intellectual Property Division (Delhi High Court).",
            "private_opportunities": "Anand and Anand, Remfry & Sagar, K&S Partners, LexOrbis, pharmaceutical and tech corporate patent teams.",
            "higher_study_options": "LLM in Intellectual Property Law, WIPO Academy Specializations.",
            "entrepreneurship_options": "Boutique patent filing and trademark prosecution agency, IP valuation consultancy.",
            "source": "Controller General of Patents, Designs and Trade Marks (CGPDTM) / BCI",
            "official_url": "https://ipindia.gov.in",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 29, "type": "DIRECT"}, {"course_id": 30, "type": "DIRECT"}, {"course_id": 9, "type": "ALTERNATIVE"}, {"course_id": 27, "type": "ALTERNATIVE"}],
            "exams": [{"exam_id": 75, "importance": "PRIMARY"}, {"exam_id": 76, "importance": "PRIMARY"}],
            "routes": [{"title": "Path A: Science / Tech Degree + LLB (Dual Route)", "type": "COMMON", "steps": "B.Tech / B.Sc / B.Pharm -> 3-Year LLB -> Clear Indian Patent Agent Examination -> Register as Patent Attorney."}],
            "ladder": [
                {"stage": "Junior Patent / Trademark Associate", "exp": "0-2 Years", "desc": "Conducts prior art searches, files trademark forms, responds to office examination reports."},
                {"stage": "Patent Attorney / Senior Associate", "exp": "2-5 Years", "desc": "Drafts complex patent claims, appears in Patent Office opposition hearings."},
                {"stage": "IP Litigation Partner", "exp": "5-8 Years", "desc": "Argues patent infringement trials in High Court IP Divisions, negotiates royalty agreements."},
                {"stage": "Senior Partner / Head of IP", "exp": "8+ Years", "desc": "Heads firm's patent prosecution portfolio, manages global pharmaceutical patent battles."}
            ],
            "roadmaps": {
                "Class 10": "Cultivate strong passion for science, inventions, and gadgets.",
                "Class 12": "Choose Science (PCM or PCB) for 12th board exams.",
                "Graduation": "Complete B.Tech, B.Sc, or B.Pharm, followed by LLB. Science degree is mandatory to become a Registered Patent Agent in India.",
                "Working Professional": "Clear the Patent Agent Examination conducted by the Indian Patent Office and practice before the Patent Office and High Courts."
            }
        },
        {
            "title": "Legal Researcher & Policy Analyst",
            "short_name": "Policy Analyst",
            "slug": "legal-researcher-policy-analyst",
            "category": "Law & Legal Services",
            "sub_category": "Public Policy & Legal Research",
            "industry": "Think Tanks & Public Policy",
            "icon": "book-half",
            "short_description": "Researches legal reforms, drafts legislative bills, analyzes public policy impacts, and advises parliamentary bodies.",
            "description": "Legal Researchers and Policy Analysts examine the real-world impact of laws and formulate evidence-based policy reforms. They work with research think tanks, parliamentary committees, judicial academies, and international bodies to shape future legislation.",
            "what_they_do": "They analyze comparative foreign legislation, author policy white papers, draft model bills for parliamentary debate, evaluate regulatory impact, and advise civil society on legal justice reforms.",
            "day_to_day_work": "• Researching constitutional and statutory legal jurisprudence.\n• Drafting policy briefs and legislative reform recommendations for government ministries.\n• Analyzing quantitative justice data (court pendency, prison statistics, legal aid).\n• Conducting stakeholder consultations with industry, civil society, and legal experts.\n• Publishing research reports and op-eds in leading national journals and newspapers.",
            "work_environment": "Think tanks, policy research institutes, legislative research offices, universities.",
            "work_modes": "Hybrid / Office / Field Consultations",
            "minimum_qualification": "Undergraduate (Law / Public Policy / Political Science)",
            "preferred_streams": "Humanities / Law / Economics",
            "required_subjects": "Law, Political Science, English, Economics",
            "technical_skills": "Legal Research, Legislative Drafting, Policy Impact Evaluation, Qualitative Analysis, Constitutional Law, Jurisprudence",
            "soft_skills": "Critical Thinking, Intellectual Rigor, Objective Analysis, Persuasive Writing",
            "tools": "SCC Online, Manupatra, LexisNexis, JSTOR, Zotero, Excel",
            "certifications": "LAMP Fellowship (PRS Legislative Research) or equivalent",
            "experience_level": "Entry-Level to Senior",
            "career_growth": "Prestigious trajectory into Think Tank Director, Policy Fellow at global universities, or Government Senior Policy Advisor.",
            "internship_roles": "Policy Research Intern, Legislative Intern (with Member of Parliament), Law Commission Intern",
            "entry_level_roles": "Research Associate, Junior Policy Analyst, Legislative Assistant",
            "average_salary": "₹4.5 - ₹12 LPA (Indicative range)",
            "salary_indicative": "Research Associate (0-2 yrs): ₹4 - 6.5 LPA | Senior Policy Fellow (3-6 yrs): ₹8 - 15 LPA | Research Director / Head of Policy (7+ yrs): ₹18 - 35+ LPA. Indicative figures from PRS & Policy Think Tanks 2024.",
            "future_scope": "Growing importance as India modernizes criminal laws (BNS, BNSS, BSA) and creates complex regulations in tech, climate, and finance.",
            "government_opportunities": "Law Commission of India, NITI Aayog Policy Units, Legislative Department (Ministry of Law & Justice), State Law Academies.",
            "private_opportunities": "Vidhi Centre for Legal Policy, PRS Legislative Research, Centre for Policy Research (CPR), Observer Research Foundation (ORF).",
            "higher_study_options": "Master's in Public Policy (MPP - NLSIU / IIMs), LLM in Comparative Law, Ph.D. in Law & Policy.",
            "entrepreneurship_options": "Independent policy advisory firm, public affairs and regulatory risk consultancy.",
            "source": "Vidhi Centre for Legal Policy / PRS Legislative Research",
            "official_url": "https://vidhilegalpolicy.in",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 29, "type": "DIRECT"}, {"course_id": 30, "type": "DIRECT"}, {"course_id": 22, "type": "COMMON"}, {"course_id": 20, "type": "COMMON"}],
            "exams": [{"exam_id": 75, "importance": "PRIMARY"}, {"exam_id": 79, "importance": "ALTERNATIVE"}],
            "routes": [{"title": "Path A: Law Degree to Policy Think Tank", "type": "COMMON", "steps": "BA LLB -> LAMP Fellowship (PRS) or Judicial Clerkship -> Join premier legal policy think tank (Vidhi, CPR) -> Senior Policy Analyst."}],
            "ladder": [
                {"stage": "Research Associate", "exp": "0-2 Years", "desc": "Conducts literature reviews, analyzes statutory sections, assists in drafting reports."},
                {"stage": "Research Fellow / Policy Analyst", "exp": "2-5 Years", "desc": "Leads thematic research projects, drafts model bills, interacts with government departments."},
                {"stage": "Senior Fellow / Program Lead", "exp": "5-8 Years", "desc": "Heads judicial reform or tech policy vertical, advises parliamentary standing committees."},
                {"stage": "Director / Executive Trustee", "exp": "8+ Years", "desc": "Sets think tank strategic research agenda and shapes national legal reform discourse."}
            ],
            "roadmaps": {
                "Class 10": "Read widely on history, governance, and current affairs.",
                "Class 12": "Choose Humanities, Commerce, or Science with strong English and Social Sciences.",
                "Graduation": "Pursue Law (BA LLB) or Political Science/Economics. Publish research articles in student law reviews.",
                "Working Professional": "Apply for the competitive LAMP Fellowship (work with a Member of Parliament for one year) or join institutes like Vidhi."
            }
        },
        {
            "title": "Compliance & Regulatory Officer",
            "short_name": "Compliance Officer",
            "slug": "compliance-officer",
            "category": "Law & Legal Services",
            "sub_category": "Corporate Governance & Compliance",
            "industry": "Banking, Financial Services & Healthcare",
            "icon": "clipboard-check",
            "short_description": "Ensures an organization complies with external statutory laws, regulatory mandates, and internal ethical standards.",
            "description": "Compliance and Regulatory Officers ensure that corporations and financial institutions operate strictly within statutory boundaries set by regulators like RBI, SEBI, IRDAI, and CDSCO. They conduct internal audits, prevent financial crimes, and report to boards of directors.",
            "what_they_do": "They design corporate compliance frameworks, conduct Anti-Money Laundering (AML) monitoring, review transactions for regulatory compliance, manage regulatory inspection audits, and train employees on ethical compliance.",
            "day_to_day_work": "• Monitoring transactions for suspicious Anti-Money Laundering (AML) flags.\n• Interpreting circulars and guidelines issued by RBI, SEBI, or IRDAI.\n• Conducting compliance risk assessments across business units.\n• Filing statutory compliance certificates with regulatory authorities.\n• Investigating internal whistle-blower complaints and ethical breaches.",
            "work_environment": "Commercial banks, financial brokerages, fintech firms, pharmaceutical companies.",
            "work_modes": "Hybrid / Office",
            "minimum_qualification": "Undergraduate (Law / Commerce / CS / Finance)",
            "preferred_streams": "Commerce / Law / Finance",
            "required_subjects": "Commercial Law, Banking, Auditing",
            "technical_skills": "Regulatory Compliance, Anti-Money Laundering (AML/CFT), SEBI Regulations, RBI Master Directions, KYC Auditing, Risk Management",
            "soft_skills": "High Moral Integrity, Attention to Detail, Objective Independence, Diplomatic Communication",
            "tools": "AML Screening Software (Actimize, LexisNexis Bridger), Regulatory Portals, Excel",
            "certifications": "Certified Anti-Money Laundering Specialist (ACAMS), Certified Compliance & Ethics Professional (CCEP)",
            "experience_level": "Entry-Level to Senior",
            "career_growth": "Direct progression to Chief Compliance Officer (CCO), reporting directly to the Board Audit Committee.",
            "internship_roles": "Compliance Intern, Regulatory Affairs Trainee, AML Analyst Intern",
            "entry_level_roles": "Junior Compliance Officer, AML Analyst, Regulatory Associate",
            "average_salary": "₹5 - ₹15 LPA (Indicative range)",
            "salary_indicative": "Entry-Level Analyst (0-2 yrs): ₹4.5 - 7 LPA | Compliance Manager (3-6 yrs): ₹9 - 18 LPA | Chief Compliance Officer (7+ yrs): ₹24 - 55+ LPA. Indicative figures from ACAMS & Banking Audits 2024.",
            "future_scope": "Consistently essential as financial penalties for regulatory non-compliance from RBI and SEBI reach historic highs.",
            "government_opportunities": "SEBI Grade A Officer, RBI Grade B Officer, Financial Intelligence Unit (FIU-IND).",
            "private_opportunities": "HDFC Bank, ICICI Bank, Zerodha, Groww, PhonePe, standard multinational banks and fintechs.",
            "higher_study_options": "CS (Company Secretary), LLM in Banking Law, MBA in Finance.",
            "entrepreneurship_options": "Regulatory compliance audit agency, AML compliance screening firm.",
            "source": "Association of Certified Anti-Money Laundering Specialists (ACAMS) / SEBI",
            "official_url": "https://www.acams.org",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 16, "type": "COMMON"}, {"course_id": 29, "type": "COMMON"}, {"course_id": 30, "type": "COMMON"}],
            "exams": [{"exam_id": 44, "importance": "PRIMARY"}, {"exam_id": 5, "importance": "ALTERNATIVE"}],
            "routes": [{"title": "Path A: Law / Commerce to Compliance Officer", "type": "COMMON", "steps": "B.Com / LLB / CS -> Learn AML & Banking Regulations -> ACAMS Certification -> Bank / Fintech Compliance Officer."}],
            "ladder": [
                {"stage": "AML / Compliance Analyst", "exp": "0-2 Years", "desc": "Reviews customer KYC alerts, investigates transaction monitoring exceptions."},
                {"stage": "Compliance Officer", "exp": "2-5 Years", "desc": "Interprets new RBI/SEBI circulars, manages regulatory filing schedules."},
                {"stage": "Senior Manager - Regulatory Compliance", "exp": "5-8 Years", "desc": "Leads interactions during central bank inspection audits, drafts board compliance reports."},
                {"stage": "Chief Compliance Officer (CCO)", "exp": "8+ Years", "desc": "Statutory guardian of enterprise compliance, independent access to Board Audit Committee."}
            ],
            "roadmaps": {
                "Class 10": "Focus on arithmetic, ethics, and general business awareness.",
                "Class 12": "Choose Commerce or Humanities with Business Studies or Law.",
                "Graduation": "Complete B.Com, LLB, or CS. Understand financial regulations and Anti-Money Laundering laws.",
                "Working Professional": "Earn the globally recognized ACAMS certification and specialize in Fintech or Banking compliance."
            }
        }
    ]

print("Catalog builder part 2 ready.")
