"""
scripts/catalog_expanded_part11.py
Additional Authentic Careers for Skilled Trades, Agriculture, Government, Sports, and Archives
"""

def get_skilled_and_environmental_careers():
    return [
        {
            "title": "Master Plumber & Piping Systems Specialist",
            "short_name": "Master Plumber",
            "slug": "master-plumber-piping-specialist",
            "category": "Skilled Trades & Vocational Careers",
            "sub_category": "Plumbing & Piping Trades",
            "industry": "Commercial Construction, Water Utilities & Plumbing",
            "icon": "droplet-half",
            "short_description": "Installs, tests, and maintains high-pressure water supply, sanitation drainage, and gas piping systems.",
            "description": "Master Plumbers and Piping Specialists assemble, install, and repair complex water supply networks, stormwater drainage, hydronic heating, and gas pipelines in high-rise residential towers, commercial hospitals, and industrial plants. Certified through ITI Plumber and the Indian Plumbing Skills Council (IPSC), they read isometric piping schematics, weld copper and PPR pipes, test backflow preventers, and maintain sanitary hygiene.",
            "what_they_do": "They cut and join PVC, CPVC, and copper pipes, install commercial sanitary fixtures and water heaters, test water pressure with hydrostatic pumps, inspect sewer lines with drain cameras, and repair leaks.",
            "day_to_day_work": "• Reading architectural and plumbing isometric drawings for high-rise building piping risers.\n• Joining and soldering copper and solvent-welding CPVC water distribution lines.\n• Installing booster pumps, water pressure regulators, and grease interceptors in commercial kitchens.\n• Conducting hydrostatic pressure testing to certify zero leaks in freshly laid pipeline grids.\n• Clearing stubborn blockages using motorized drain augers and CCTV pipe inspection cameras.",
            "work_environment": "Commercial building sites, industrial plants, residential complexes, utility trenches.",
            "work_modes": "On-site / Construction Site / Workshop",
            "minimum_qualification": "Vocational Certificate (ITI Plumber - 1 Year) / IPSC Skill Certification",
            "preferred_streams": "Class 10 / Class 12 Pass (Any Stream)",
            "required_subjects": "Basic Mathematics, Trade Practical, Plumbing Theory",
            "technical_skills": "Isometric Piping Blueprints, CPVC/PPR/Copper Pipe Jointing, Drainage & Venting Systems, Hydrostatic Pressure Testing, Backflow Prevention, Sanitary Fixture Installation",
            "soft_skills": "Physical Stamina, Problem-Solving Under Pressure, Clean Workmanship, Customer Reliability",
            "tools": "Pipe Threaders, Pipe Cutters, Hydrostatic Pressure Test Pumps, Drain Augers, Inspection Cameras, Soldering Torches",
            "certifications": "National Trade Certificate (NTC) in Plumber Trade, Indian Plumbing Skills Council (IPSC) Certification",
            "experience_level": "Apprentice to Licensed Plumbing Contractor",
            "career_growth": "Advance to Senior Plumbing Supervisor, Project Plumbing Engineer, or Licensed Plumbing Contractor.",
            "internship_roles": "Plumbing Apprentice under National Apprenticeship Promotion Scheme (NAPS)",
            "entry_level_roles": "Junior Plumber, Pipefitter Assistant, Maintenance Plumber",
            "average_salary": "₹3.0 - ₹8.5 LPA (Indicative range)",
            "salary_indicative": "Entry-Level Plumber: ₹3.0 - 4.5 LPA | Commercial Plumbing Supervisor (3-6 yrs): ₹5.0 - 7.5 LPA | Licensed Plumbing Contractor / Gulf Overseas Specialist: ₹9.0 - 18+ LPA. Indicative figures from IPSC and construction contractor surveys.",
            "future_scope": "Continuous strong demand driven by urban high-rise construction, luxury bathrooms, and national piped drinking water schemes (Jal Jeevan Mission).",
            "government_opportunities": "Municipal Water Supply Boards (DJB, BWSSB, CMWSSB), Military Engineer Services (MES), CPWD, Indian Railways.",
            "private_opportunities": "Larsen & Toubro Construction, Shapoorji Pallonji, Jaquar & Company, Kohler India, Ashirvad Pipes, Supreme Industries.",
            "higher_study_options": "Diploma in Civil / Environmental Engineering, Advanced Firefighting Piping Certifications.",
            "entrepreneurship_options": "Founding an independent plumbing contracting firm, emergency plumbing services company, or water treatment sales agency.",
            "source": "Indian Plumbing Skills Council (IPSC) / DGT",
            "official_url": "https://ipsc.in",
            "verification_status": "VERIFIED",
            "is_lesser_known": False,
            "career_family": "Skilled Trades",
            "interest_clusters": "Hands-on, Trades, Practical, Machines",
            "work_style": "Construction Site, Workshop, Outdoor",
            "reality_check": "Involves physically demanding manual labor in wet, cramped, and muddy utility trenches.\nRequires strict hygiene precautions when working around sewer drainage and wastewater lines.\nHighly respected skilled trade with high earning potential for reliable independent master contractors.",
            "next_steps": "Pass Class 10 from any recognized board.\nEnroll in the 1-year ITI Plumber trade course at a government or recognized private ITI.\nComplete 1 year of paid apprenticeship under NAPS and earn your National Apprenticeship Certificate (NAC).",
            "courses": [{"course_id": 64, "type": "PRIMARY"}],
            "exams": [],
            "routes": [{"title": "Path A: ITI Plumber Route", "type": "PRIMARY", "steps": "Class 10 -> ITI Plumber (1 yr) -> National Apprenticeship (1 yr) -> Junior Plumber -> Plumbing Contractor."}],
            "ladder": [
                {"stage": "Plumbing Apprentice", "exp": "0-2 Years", "desc": "Cuts pipes, carries materials, glues fittings, assists in sanitary fixture installations."},
                {"stage": "Commercial Plumbing Technician / Supervisor", "exp": "2-6 Years", "desc": "Installs vertical riser pipes, carries out hydrostatic pressure tests, reads building blueprints."},
                {"stage": "Licensed Plumbing Contractor", "exp": "6+ Years", "desc": "Contracts multi-lakh plumbing installations for high-rise apartment towers, employs teams of plumbers."}
            ]
        },
        {
            "title": "Forest Range Officer (FRO)",
            "short_name": "Forest Range Officer",
            "slug": "forest-range-officer",
            "category": "Government, Defence & Civil Services",
            "sub_category": "Forestry & Wildlife Protection",
            "industry": "Forest Conservation, Wildlife Protection & Government Forestry",
            "icon": "tree-fill",
            "short_description": "Commands a forest range, enforces anti-poaching laws, prevents forest fires, and conserves timber reserves.",
            "description": "Forest Range Officers (FROs) are gazetted state forest officers who hold territorial executive charge of a forest range (often encompassing 10,000 to 50,000+ hectares of forest land). Armed and empowered under the Wildlife Protection Act and Indian Forest Act, they lead anti-poaching patrols, combat illegal timber smuggling, manage forest nurseries, suppress seasonal wildfires, and protect endangered wildlife habitats.",
            "what_they_do": "They command forest guards and beat watchers, inspect timber harvest operations, investigate wildlife crime, organize community social forestry programs, and direct wildfire firefighting crews.",
            "day_to_day_work": "• Directing armed anti-poaching patrols through deep forest beats and wildlife corridors.\n• Investigating incidents of illicit sandalwood/teak logging and registering Forest Offense Reports.\n• Operating fire watchtowers and deploying blowers to fight dry-season forest canopy fires.\n• Overseeing government afforestation nurseries and sapling plantation targets.\n• Resolving human-wildlife conflict incidents (wild elephant herds, tiger cattle-lifting) with local villagers.",
            "work_environment": "Forest ranges, wildlife sanctuaries, range offices in forested areas, outdoor jungle tracks.",
            "work_modes": "Field / Jungle / Government Office",
            "minimum_qualification": "Undergraduate (Bachelor's Degree in Forestry, Agriculture, Botany, Zoology, Geology, Physics, Chemistry, Maths, or Engineering)",
            "preferred_streams": "Science (PCB / PCM / Forestry / Agriculture)",
            "required_subjects": "Forestry / Science subjects + Physical Endurance standards",
            "technical_skills": "Forest Law Enforcement, Silviculture Practices, Wildlife Crime Investigation, Forest Fire Management, GPS Boundary Demarcation, Social Forestry",
            "soft_skills": "Courage in Wilderness, Wilderness Survival, Decisive Field Command, Community Tact",
            "tools": "Field GPS, VHF Forest Wireless Radios, Service Sidearms / Rifles, Forest Fire Fighting Blowers",
            "certifications": "State Public Service Commission (State Forest Service Exam), Induction Training at Central Academy for State Forest Service (CASFOS)",
            "experience_level": "Range Officer to Deputy Conservator of Forests (DCF)",
            "career_growth": "Advance from Forest Range Officer to Assistant Conservator of Forests (ACF), Deputy Conservator of Forests (DCF / DFO), and Chief Conservator of Forests.",
            "internship_roles": "Range Officer Trainee at CASFOS Dehradun / Coimbatore",
            "entry_level_roles": "Forest Range Officer (FRO)",
            "average_salary": "₹7.0 - ₹14.0 LPA (State 7th Pay Commission Scale)",
            "salary_indicative": "Forest Range Officer (Pay Level 8/9): ₹47,600 basic + DA + Special Forest Allowances (~₹7.0 - 9.5 LPA in hand) | Assistant Conservator of Forests (ACF): ₹10 - 15 LPA plus official government accommodation inside forest reserve and government 4x4 Gypsy vehicle.",
            "future_scope": "Essential sovereign role as India expands its forest cover under national climate commitments and combats organized international wildlife trafficking.",
            "government_opportunities": "State Forest Departments across India (Himachal Pradesh, Uttarakhand, Madhya Pradesh, Karnataka, Assam, Kerala, etc.), Ministry of Environment, Forest & Climate Change.",
            "private_opportunities": "State government gazetted post; post-retirement roles include wildlife trusts (WWF, WTI) and environmental consultancies.",
            "higher_study_options": "Master's in Forestry / Wildlife Management, Wildlife Forensics training.",
            "entrepreneurship_options": "Not applicable during active government service.",
            "source": "Ministry of Environment, Forest and Climate Change / State Forest Departments",
            "official_url": "https://moef.gov.in",
            "verification_status": "VERIFIED",
            "is_lesser_known": False,
            "career_family": "Public Administration",
            "interest_clusters": "Nature, Government, Outdoor, Leadership, Science",
            "work_style": "Field, Outdoor, Jungle",
            "reality_check": "Challenging wilderness living: Range quarters are often located in remote forest reserves with limited mobile connectivity.\nPersonal physical danger: Facing armed poachers, illegal timber mafias, and dangerous wild animals on foot patrols.\nRequires passing physical walking endurance tests (e.g. 25 km walk in 4 hours for males, 14 km for females) conducted by state PSCs.",
            "next_steps": "Earn a Bachelor's degree in Forestry (B.Sc Forestry), Agriculture, Zoology, Botany, or Engineering.\nAppear for the State Forest Service (Forest Range Officer) Examination conducted by your State Public Service Commission.\nPass the physical fitness walking test, medical inspection, and complete 2 years of rigorous training at CASFOS (Dehradun, Coimbatore, or Burnihat).",
            "courses": [{"course_id": 68, "type": "PRIMARY"}, {"course_id": 8, "type": "RELATED"}],
            "exams": [{"exam_id": 34, "importance": "RECOMMENDED"}],
            "routes": [{"title": "Path A: State Forest Service Route", "type": "PRIMARY", "steps": "B.Sc Forestry / Science -> State PSC Forest Service Exam -> 25km Walking Test -> CASFOS Training -> Forest Range Officer."}],
            "ladder": [
                {"stage": "Forest Range Officer (FRO)", "exp": "0-6 Years", "desc": "Commands territorial forest range, leads anti-poaching operations, manages tree plantations and fires."},
                {"stage": "Assistant Conservator of Forests (ACF)", "exp": "6-12 Years", "desc": "Supervises multiple forest ranges, handles departmental timber auctions and forest court cases."},
                {"stage": "Divisional Forest Officer (DFO)", "exp": "12+ Years", "desc": "Commands entire district forest division or National Park, manages wildlife protection and eco-tourism."}
            ]
        },
        {
            "title": "Sports Performance & Biometrics Data Analyst",
            "short_name": "Sports Data Analyst",
            "slug": "sports-performance-data-analyst",
            "category": "Education, Teaching & Academia",
            "sub_category": "Sports Science & Analytics",
            "industry": "Professional Sports Leagues, Cricket Analytics & High Performance",
            "icon": "graph-up",
            "short_description": "Analyzes athlete GPS telemetry, match video tracking, and biometrics to optimize athletic tactics.",
            "description": "Sports Performance Data Analysts translate real-time player biometric data, GPS tracking vests, and video telemetry into actionable tactical strategies for coaches and professional sports teams (IPL, ISL, PKL, national federations). They evaluate bowler release speeds, player fatigue load limits, football passing heatmaps, and opponent batting weaknesses using statistical programming.",
            "what_they_do": "They analyze Hawkeye ball-tracking data, GPS metabolic work rates, build predictive player injury models, code match video events in real time, and deliver tactical briefing dashboards to head coaches.",
            "day_to_day_work": "• Downloading and analyzing GPS tracking vest telemetry (distance covered, sprint velocities, player load).\n• Coding live match events and tag markers during professional matches for video analysis.\n• Building match strategy reports on opponent strengths, shot selections, and bowling pitch maps.\n• Tracking player physiological fatigue thresholds to alert medical staff of impending hamstring injuries.\n• Presenting interactive PowerBI / Tableau analytics dashboards to head coaches and team analysts.",
            "work_environment": "Professional sports franchise dugouts, performance analysis rooms, sports analytics labs.",
            "work_modes": "Hybrid / Stadium / Office / Touring",
            "minimum_qualification": "Undergraduate (B.Sc / B.Tech in Statistics, Data Science, Sports Science, or Computer Science)",
            "preferred_streams": "Science (Maths / Statistics / Computer Science) with intense sports passion",
            "required_subjects": "Statistics, Sports Science, Data Analytics",
            "technical_skills": "Sports Analytics Modeling, Python / R for Sports Data, GPS Performance Metrics (Catapult/STATSports), Ball Tracking Analysis (Hawk-Eye), Video Tagging (Dartfish, Hudl), Tableau / PowerBI",
            "soft_skills": "Translating Data into Simple Coachable Insights, High Passion for Sports, Rapid Turnaround",
            "tools": "Catapult GPS, Hudl Sportscode, Python (pandas, matplotlib), Hawk-Eye Data, Tableau",
            "certifications": "Catapult Certified Sports Analyst, Hudl Sportscode Certification",
            "experience_level": "Junior Analyst to Head of Sports Analytics",
            "career_growth": "Advance to Senior Team Analyst, Performance Director of Sports Franchise, or Head of Cricket Analytics.",
            "internship_roles": "Sports Analytics Intern, Video Analysis Trainee",
            "entry_level_roles": "Junior Sports Analyst, Performance Tagging Associate, Video Analyst",
            "average_salary": "₹5.0 - ₹15.0+ LPA (Indicative range)",
            "salary_indicative": "Junior Sports Analyst: ₹5.0 - 7.5 LPA | Franchise League Team Analyst (IPL / ISL, 3-6 yrs): ₹9 - 18 LPA | Head of High-Performance Analytics: ₹18 - 35+ LPA. Indicative figures from sports analytics agencies (CricViz, Sportradar, IPL teams).",
            "future_scope": "Explosive growth as every professional cricket, football, and kabaddi team relies on data-driven player auctions, tactics, and workload management.",
            "government_opportunities": "Sports Authority of India (High Performance Analytics division), National Cricket Academy (NCA Bengaluru).",
            "private_opportunities": "IPL Franchises (CSK, MI, KKR, RR), ISL Football Clubs, CricViz, Sportradar, Kadamba Technologies, JSW Sports.",
            "higher_study_options": "M.Sc in Sports Analytics / Sports Science, International Master's in Sports Data.",
            "entrepreneurship_options": "Founding an independent sports data analytics platform, grassroots scouting service, or sports betting intelligence consultancy.",
            "source": "Sports Authority of India (SAI) / International Sports Analytics Associations",
            "official_url": "https://sportsauthorityofindia.nic.in",
            "verification_status": "VERIFIED",
            "is_lesser_known": True,
            "career_family": "Sports & Movement",
            "interest_clusters": "Sports, Numbers, Technology, Analysis",
            "work_style": "Stadium, Office, Travel",
            "reality_check": "Not just watching matches for fun: Involves hours of painstakingly tagging video footage frame-by-frame and cleaning messy GPS telemetry datasets.\nMust communicate with coaches who may not be mathematical: insights must be simple, practical, and tactically actionable on the pitch.\nHigh-pressure matchday schedules: Delivering opponent analysis reports at midnight before an afternoon match.",
            "next_steps": "Learn Python data analysis libraries (pandas, seaborn) and practice on public cricket (Cricsheet) or football datasets.\nLearn video analysis software (Hudl Sportscode / Dartfish) and build a portfolio of public sports tactical breakdown articles or videos.\nPitch your analysis to sports analytics firms (CricViz) or intern with state cricket associations or football clubs.",
            "courses": [{"course_id": 16, "type": "PRIMARY"}, {"course_id": 60, "type": "RELATED"}],
            "exams": [],
            "routes": [{"title": "Path A: Data to Sports Analytics", "type": "PRIMARY", "steps": "B.Sc Stats / B.Tech -> Python & Hudl Portfolio -> Sports Analytics Intern -> Franchise Video Analyst -> Head of Analytics."}],
            "ladder": [
                {"stage": "Performance Tagging Analyst", "exp": "0-2 Years", "desc": "Tags live video markers, downloads player GPS metrics, generates routine post-match fitness summaries."},
                {"stage": "Team Performance Analyst", "exp": "2-6 Years", "desc": "Travels with squad, designs opponent match tactics, advises coaches on player workload rotation."},
                {"stage": "Head of High Performance & Scouting", "exp": "6+ Years", "desc": "Directs player recruitment auction analytics, builds predictive injury AI algorithms for franchise."}
            ]
        },
        {
            "title": "Rare Manuscripts & Antiquarian Book Conservator",
            "short_name": "Manuscript Conservator",
            "slug": "rare-manuscripts-conservator",
            "category": "Education, Teaching & Academia",
            "sub_category": "Library & Archival Science",
            "industry": "National Libraries, Archives & Rare Document Conservation",
            "icon": "book",
            "short_description": "Restores and preserves centuries-old palm-leaf manuscripts, parchment, and ancient handwritten texts.",
            "description": "Rare Manuscripts and Antiquarian Book Conservators specialize in the chemical stabilization, physical repair, and preventive conservation of delicate historical paper documents, ancient palm-leaf manuscripts (Tala-patra), leather bindings, and medieval hand-written codices. Working in national archives, oriental research institutes, and royal libraries, they preserve irreplaceable cultural heritage.",
            "what_they_do": "They fumigate insect-damaged manuscripts, deacidify brittle aged paper, repair torn folios using Japanese tissue and wheat starch paste, condition dry palm leaves with lemongrass oil, and bind historic volumes.",
            "day_to_day_work": "• Examining 300-year-old handmade paper manuscripts for acidity, foxing stains, and insect tunneling.\n• Conducting non-aqueous chemical deacidification using calcium hydroxide / magnesium solutions.\n• Repairing leaf losses and paper tears using fine Japanese Kozo tissue and reversible starch paste.\n• Treating brittle palm leaves with natural botanical oils (citronella, lemongrass) to restore flexibility.\n• Constructing archival phase boxes and micro-climate enclosures for ancient scrolls.",
            "work_environment": "Conservation laboratories in National Archives, state oriental manuscript libraries, museum archives.",
            "work_modes": "On-site / Lab / Library / Archive",
            "minimum_qualification": "Postgraduate (M.A. / M.Sc in Conservation of Cultural Property / BLIS with Paper Conservation specialization)",
            "preferred_streams": "Humanities / Chemistry / Library Science / Fine Arts",
            "required_subjects": "Paper Chemistry, Material Conservation, Archival Science, History",
            "technical_skills": "Paper Deacidification, Palm-Leaf Manuscript Conservation, Japanese Tissue Mending, Leather Bookbinding, Reversible Paste Chemistry, Leaf Casting, Micro-climate Enclosures",
            "soft_skills": "Surgical Fine Hand Delicacy, Infinite Patience, Intellectual Reverence for History",
            "tools": "Paper Suction Tables, Preservation Leaf Casting Machines, PH Test Pens, Bone Folders, Scalpels, Weights",
            "certifications": "National Archives of India (NAI) School of Archival Studies Diploma in Conservation",
            "experience_level": "Assistant Conservator to Chief Scientific Officer (Archives)",
            "career_growth": "Advance to Senior Paper Conservator, Head of Preservation (National Archives), or Rare Book Consultant.",
            "internship_roles": "Paper Conservation Intern, Manuscript Restoration Trainee",
            "entry_level_roles": "Junior Paper Conservator, Bookbinder, Archival Restoration Assistant",
            "average_salary": "₹4.5 - ₹12.5 LPA (Indicative range)",
            "salary_indicative": "Junior Paper Conservator: ₹4.5 - 6.5 LPA | Senior Manuscript Conservator (3-7 yrs): ₹7.5 - 12 LPA | Chief of Preservation in National Archives: ₹14 - 24+ LPA. Indicative figures from National Archives of India.",
            "future_scope": "Critical national mission: Millions of priceless ancient Sanskrit, Persian, Tamil, and Pali manuscripts in Indian institutions need urgent scientific conservation under the National Mission for Manuscripts (NMM).",
            "government_opportunities": "National Mission for Manuscripts (NMM), National Archives of India (NAI New Delhi), National Library (Kolkata), Khuda Bakhsh Oriental Public Library (Patna), Tanjore Saraswathi Mahal Library.",
            "private_opportunities": "The Asiatic Society, INTACH Conservation Centres, Rare Book Auction Houses, Private Palace Heritage Libraries.",
            "higher_study_options": "Ph.D. in Paper & Material Conservation, International Fellowships at British Library or Library of Congress.",
            "entrepreneurship_options": "Founding an independent rare book and family heritage document restoration studio.",
            "source": "National Mission for Manuscripts (NMM) / National Archives of India",
            "official_url": "https://namami.gov.in",
            "verification_status": "VERIFIED",
            "is_lesser_known": True,
            "career_family": "Library & Archival",
            "interest_clusters": "History, Science, Culture, Hands-on, Art",
            "work_style": "Lab, Library, Archive",
            "reality_check": "Extremely slow, solitary, and painstaking work: Restoring a single fragile handwritten folio can take several days of microscopic manual mending.\nRequires chemical safety: Working with organic solvents, deacidification baths, and biological mold inhibitors.\nA deeply peaceful, noble calling preserving the physical memories of human civilization.",
            "next_steps": "Earn a Bachelor's degree in Chemistry, History, Fine Arts, or Library Science.\nComplete the Certificate / Diploma in Care & Conservation of Books, Manuscripts and Archives at the National Archives of India (NAI New Delhi).\nApprentice under master paper and manuscript conservators at recognized archival centers.",
            "courses": [{"course_id": 65, "type": "PRIMARY"}, {"course_id": 31, "type": "RELATED"}],
            "exams": [],
            "routes": [{"title": "Path A: NAI Archival Conservation Route", "type": "PRIMARY", "steps": "B.A. / B.Sc -> NAI Diploma in Manuscript Conservation -> NMM Project Conservator -> Master Manuscript Conservator."}],
            "ladder": [
                {"stage": "Assistant Paper Conservator", "exp": "0-3 Years", "desc": "Carries out surface cleaning, deacidifies brittle paper, repairs tears using Japanese tissue."},
                {"stage": "Senior Manuscript Conservator", "exp": "3-8 Years", "desc": "Restores fragile palm-leaf collections, executes leaf-casting repairs, rebinds ancient leather codices."},
                {"stage": "Chief of Conservation / Director", "exp": "8+ Years", "desc": "Heads national archival preservation laboratories, sets national conservation guidelines for libraries."}
            ]
        }
    ]
