"""
scripts/catalog_expanded_part7.py
Domain W: Skilled Trades & Vocational Careers (5 careers)
Domain X: Beauty & Wellness (2 careers)
Domain Y: Library, Information & Knowledge (2 careers)
Domain Z: Research & Academia (3 careers)
"""

def get_skilled_trades_and_vocational_careers():
    return [
        {
            "title": "Licensed Master Electrician & Industrial Wireman",
            "short_name": "Master Electrician",
            "slug": "master-electrician-wireman",
            "category": "Skilled Trades & Vocational Careers",
            "sub_category": "Electrical & Industrial Trades",
            "industry": "Electrical Infrastructure, Manufacturing & Power Distribution",
            "icon": "lightning-charge",
            "short_description": "Installs, tests, maintains, and repairs industrial high-voltage electrical switchgear, transformers, and circuitry.",
            "description": "Master Electricians and Industrial Wiremen are skilled technical tradespeople who install, calibrate, maintain, and troubleshoot complex electrical distribution systems in factories, commercial high-rises, and substations. Certified through ITI Electrical and state electrical licensing boards (Wireman / Supervisor License), they work with high-voltage panels, motor control centers (MCC), transformers, and PLC systems.",
            "what_they_do": "They read industrial electrical schematics, pull high-load cables, wire circuit breaker distribution boards, test earth resistance, program variable frequency drives (VFDs), and maintain industrial electrical safety.",
            "day_to_day_work": "• Interpreting single-line electrical diagrams (SLD) and building electrical layouts.\n• Installing electrical distribution boards, circuit breakers (MCBs/MCCBs), and busbars.\n• Measuring circuit voltages, current load balance, and insulation resistance with Meggers.\n• Troubleshooting industrial electric motors, contactors, and variable frequency drives (VFDs).\n• Ensuring compliance with National Electrical Code (NEC) and Central Electricity Authority (CEA) safety norms.",
            "work_environment": "Industrial factory floors, construction sites, power substations, commercial buildings.",
            "work_modes": "On-site / Workshop / Plant Floor",
            "minimum_qualification": "Vocational Certificate (ITI Electrician - 2 Years) / Polytechnic Diploma in Electrical Engineering",
            "preferred_streams": "Class 10 / Class 12 Pass (Science or Any Stream)",
            "required_subjects": "Basic Physics, Electrical Trade Theory, Engineering Drawing",
            "technical_skills": "Single Line Diagrams (SLD), Three-Phase Motor Control, High-Voltage Switchgear, Megger Insulation Testing, Earth Pit Resistance, PLC/VFD Basics, Electrical Safety (LOTO)",
            "soft_skills": "Disciplined Safety Caution, Analytical Fault Tracing, Manual Dexterity, Physical Agility",
            "tools": "Digital Multimeters, Meggers (Insulation Testers), Clamp Meters, Wire Strippers, Conduit Benders, Hydraulic Crimping Tools",
            "certifications": "National Trade Certificate (NTC) by NCVT, State Electrical Licensing Board 'Supervisor' or 'Wireman' License",
            "experience_level": "Apprentice to Master Electrical Contractor",
            "career_growth": "Advance to Senior Electrical Technician, Plant Electrical Supervisor, Maintenance Head, or Licensed Electrical Contractor.",
            "internship_roles": "Apprentice Electrician (under National Apprenticeship Promotion Scheme - NAPS)",
            "entry_level_roles": "Junior Electrician, Industrial Wireman, Maintenance Technician",
            "average_salary": "₹3.0 - ₹9.0+ LPA (Indicative range)",
            "salary_indicative": "Entry-Level Wireman: ₹3.0 - 4.5 LPA | Industrial Electrical Supervisor (3-6 yrs): ₹5.5 - 8.5 LPA | Licensed Electrical Contractor / Gulf Overseas Technician: ₹10 - 20+ LPA. Indicative figures from National Skill Development Corporation (NSDC) and industrial sector skill councils.",
            "future_scope": "Booming demand across smart infrastructure, solar power installations, industrial automation, and rapid electrification.",
            "government_opportunities": "Indian Railways (Loco Maintenance & Electrical General), State Electricity Boards (DISCOMs), Power Grid Corporation of India, BHEL, DRDO, CPWD.",
            "private_opportunities": "Larsen & Toubro, Tata Power, Schneider Electric, Siemens India, ABB India, Voltas, Havells, Manufacturing plants.",
            "higher_study_options": "Diploma in Electrical Engineering (lateral entry to 2nd year for ITI holders), Advanced Automation Certifications.",
            "entrepreneurship_options": "Starting a licensed electrical contracting firm, solar installation company, or industrial motor rewinding workshop.",
            "source": "Directorate General of Training (DGT) / National Council for Vocational Training (NCVT)",
            "official_url": "https://dgt.gov.in",
            "verification_status": "VERIFIED",
            "is_lesser_known": False,
            "career_family": "Skilled Trades",
            "interest_clusters": "Hands-on, Trades, Machines, Practical",
            "work_style": "Workshop, Factory, Construction Site",
            "reality_check": "Electrical safety is zero-compromise: Requires strict discipline following Lockout/Tagout (LOTO) protocols to prevent lethal electric shocks.\nInvolves active physical work: climbing ladders, working in confined panels, and pulling heavy copper cables.\nHigh dignity of labor: skilled master electricians are indispensable in every modern factory and infrastructure project.",
            "next_steps": "Pass Class 10 with Science and Mathematics.\nEnroll in a 2-year ITI Electrician course at a government or recognized private Industrial Training Institute (ITI).\nComplete 1 year of paid apprenticeship under NAPS and appear for the All India Trade Test (AITT) to earn the National Apprenticeship Certificate (NAC).",
            "courses": [{"course_id": 64, "type": "PRIMARY"}],
            "exams": [],
            "routes": [{"title": "Path A: ITI Trade Route", "type": "PRIMARY", "steps": "Class 10 -> ITI Electrician (2 yrs) -> National Apprenticeship (1 yr) -> State Wireman / Supervisor License -> Master Electrician / Contractor."}],
            "ladder": [
                {"stage": "Apprentice / Junior Wireman", "exp": "0-2 Years", "desc": "Assists senior electricians, pulls cables, cuts conduits, installs junction boxes and lighting fixtures."},
                {"stage": "Industrial Electrician / Supervisor", "exp": "2-6 Years", "desc": "Maintains 415V switchgear, troubleshoots motor control panels, conducts regular insulation resistance audits."},
                {"stage": "Master Electrical Contractor / Plant Lead", "exp": "6+ Years", "desc": "Directs electrical installations for entire factory complexes or commercial high-rises, signs statutory fitness certificates."}
            ]
        },
        {
            "title": "Solar Photovoltaic Grid Installation Technician",
            "short_name": "Solar Technician",
            "slug": "solar-pv-installation-technician",
            "category": "Skilled Trades & Vocational Careers",
            "sub_category": "Renewable Energy & Solar Trades",
            "industry": "Solar Energy, Rooftop Solar & Clean Power",
            "icon": "sun",
            "short_description": "Installs, tests, commissions, and maintains rooftop solar panels, grid inverters, and battery storage systems.",
            "description": "Solar PV Installation Technicians (Suryamitra) install, wire, test, and commission rooftop and utility-scale solar photovoltaic electricity generation systems. Certified through the Skill Council for Green Jobs (SCGJ), they mount solar panel arrays, align tilt angles for maximum solar irradiance, wire DC string cables, connect grid-tie inverters, and maintain battery energy storage systems (BESS).",
            "what_they_do": "They assemble mounting structures on rooftops, install solar PV modules, connect DC combiner boxes and lightning arresters, install grid-tied solar inverters, and monitor digital kilowatt-hour (kWh) net-metering generation.",
            "day_to_day_work": "• Surveying rooftop orientations and shading using solar pathfinders and digital compasses.\n• Anchoring structural aluminum mounting rails and torqueing solar PV panels securely.\n• Terminating MC4 waterproof solar connectors and DC cabling adhering to polarity standards.\n• Installing and commissioning solar string inverters, charge controllers, and earthing electrodes.\n• Troubleshooting solar array output drops using thermal imaging cameras to spot micro-cracks.",
            "work_environment": "Building rooftops (residential, commercial, industrial), solar parks, outdoor electrical substations.",
            "work_modes": "On-site / Rooftop / Outdoor",
            "minimum_qualification": "Vocational Certificate (Suryamitra Solar PV Technician / ITI Electrical or Fitter - 1-2 Years)",
            "preferred_streams": "Class 10 / Class 12 Pass (Science or Any Stream)",
            "required_subjects": "Basic Electrical, Solar Energy Principles",
            "technical_skills": "Solar PV Module Mounting, String Inverter Commissioning, MC4 Crimping, Net Metering Setup, Earth Resistance Testing, Thermal Imaging Inspection, Rooftop Safety",
            "soft_skills": "Working Safely at Heights, Methodical Wiring, Customer Reassurance, Hands-on Reliability",
            "tools": "Solar Crimping Tools, Digital Multimeters, Solar Irradiance Meters, Thermal Infrared Cameras, Safety Harnesses & Fall Arresters",
            "certifications": "Suryamitra Skill Development Program Certificate by Skill Council for Green Jobs (SCGJ) / National Institute of Solar Energy (NISE)",
            "experience_level": "Entry to Solar Project Supervisor",
            "career_growth": "Advance to Solar Project Lead, Operations & Maintenance (O&M) Manager, or Solar EPC Entrepreneur.",
            "internship_roles": "Solar Installation Apprentice, Rooftop Survey Trainee",
            "entry_level_roles": "Solar Technician, Rooftop Installer, Solar O&M Executive",
            "average_salary": "₹3.0 - ₹8.0 LPA (Indicative range)",
            "salary_indicative": "Junior Solar Installer: ₹3.0 - 4.5 LPA | Experienced Solar Project Technician (3-5 yrs): ₹5.0 - 7.5 LPA | Solar EPC Contractor / O&M Lead: ₹8.5 - 16+ LPA. Indicative figures from Skill Council for Green Jobs.",
            "future_scope": "Surging exponential demand with the PM Surya Ghar: Muft Bijli Yojana targeting 1 crore rooftop solar households across India.",
            "government_opportunities": "National Institute of Solar Energy (NISE), State Renewable Energy Development Agencies (SEDA), Solar Energy Corporation of India (SECI).",
            "private_opportunities": "Tata Power Solar, Adani Solar, Vikram Solar, Waaree Energies, CleanMax, Rooftop Solar EPC startups.",
            "higher_study_options": "Diploma in Renewable Energy Engineering, B.Voc in Renewable Energy Technology.",
            "entrepreneurship_options": "Starting a local rooftop solar sales, installation, and cleaning maintenance business under PM Surya Ghar Yojana.",
            "source": "National Institute of Solar Energy (NISE) / Skill Council for Green Jobs",
            "official_url": "https://nise.res.in",
            "verification_status": "VERIFIED",
            "is_lesser_known": False,
            "career_family": "Skilled Trades",
            "interest_clusters": "Hands-on, Trades, Nature, Machines",
            "work_style": "Rooftop, Outdoor, Workshop",
            "reality_check": "Involves working on high building rooftops under direct sunlight and heat.\nMust adhere strictly to fall protection safety harnesses and electrical DC safety protocols.\nHigh-growth green trade directly contributing to clean energy independence.",
            "next_steps": "Pass Class 10 or 12 or complete ITI in Electrical/Wireman/Fitter.\nEnroll in the government-funded 3-month Suryamitra Skill Development Program accredited by NISE and SCGJ.\nGain on-site rooftop installation experience with local solar EPC companies.",
            "courses": [{"course_id": 64, "type": "PRIMARY"}],
            "exams": [],
            "routes": [{"title": "Path A: Suryamitra Vocational Route", "type": "PRIMARY", "steps": "Class 10/12/ITI -> Suryamitra Certification (NISE) -> Rooftop Solar Installer -> Solar Project Supervisor -> Solar EPC Entrepreneur."}],
            "ladder": [
                {"stage": "Solar Installer / Apprentice", "exp": "0-2 Years", "desc": "Mounts rooftop panels, crimps MC4 connectors, pulls DC cables under senior technician supervision."},
                {"stage": "Solar Commissioning Technician", "exp": "2-5 Years", "desc": "Connects inverters, tests net metering, conducts thermal camera audits, trains clients on solar apps."},
                {"stage": "Solar Project Supervisor / EPC Founder", "exp": "5+ Years", "desc": "Manages commercial megawatt solar installations, runs private solar rooftop contracting company."}
            ]
        },
        {
            "title": "Electric Vehicle (EV) Powertrain Maintenance Technician",
            "short_name": "EV Technician",
            "slug": "ev-maintenance-technician",
            "category": "Skilled Trades & Vocational Careers",
            "sub_category": "Automotive & Electric Mobility Trades",
            "industry": "Electric Mobility, EV Manufacturing & Automotive Service",
            "icon": "ev-station",
            "short_description": "Diagnoses, services, and repairs electric vehicle high-voltage batteries, electric drive motors, and charging systems.",
            "description": "Electric Vehicle (EV) Maintenance Technicians specialize in the advanced mechanical and electrical systems of modern electric cars, electric two-wheelers, and commercial electric buses. Certified through Automotive Skills Development Council (ASDC) programs, they troubleshoot high-voltage lithium-ion battery packs, Battery Management Systems (BMS), regenerative braking, and DC fast-charging ports.",
            "what_they_do": "They isolate high-voltage systems safely (using Class 0 insulated gloves), diagnose electric motor and inverter faults using diagnostic scan tools, monitor cell balancing, and repair electric vehicle thermal management circuits.",
            "day_to_day_work": "• Connecting OEM computerized diagnostic scanners to analyze EV controller error codes.\n• Checking individual lithium-ion battery cell voltages, temperatures, and State of Health (SoH).\n• Servicing high-voltage inverter power electronics and permanent magnet synchronous motors (PMSM).\n• Inspecting regenerative braking mechanisms, high-voltage interlock loops (HVIL), and wiring looms.\n• Testing EV charging port connectors (Type 2, CCS2) for insulation and thermal performance.",
            "work_environment": "EV authorized service centers, electric fleet maintenance hubs, EV manufacturing assembly plants.",
            "work_modes": "On-site / Workshop / Service Bay",
            "minimum_qualification": "Vocational Certificate (ITI Motor Mechanic / Electrician + EV Technician Certification by ASDC - 1-2 Years)",
            "preferred_streams": "Class 10 / Class 12 Pass (Science or Technical stream)",
            "required_subjects": "Basic Automotive Mechanics, High-Voltage Electrical Systems",
            "technical_skills": "High-Voltage Battery Safety (400V/800V), Battery Management System (BMS) Diagnostics, Inverter Power Electronics, Regenerative Braking, CAN Bus Diagnostics, EV Charging Standards (CCS2, CHAdeMO)",
            "soft_skills": "High Safety Consciousness, Methodical Fault Diagnosis, Continuous Technology Learning, Dexterity",
            "tools": "OEM EV Diagnostic Scanners, High-Voltage Insulated Toolkits (1000V rated), Insulation Multimeters, Battery Cell Balancers",
            "certifications": "Automotive Skills Development Council (ASDC) Certified EV Service Technician, ARAI EV Safety Training",
            "experience_level": "Entry to Senior EV Diagnostic Master",
            "career_growth": "Advance to Senior EV Diagnostic Technician, EV Service Workshop Manager, or Electric Fleet Technical Lead.",
            "internship_roles": "EV Service Apprentice, Battery Testing Intern",
            "entry_level_roles": "Junior EV Technician, Service Associate, Battery Assembly Assistant",
            "average_salary": "₹3.5 - ₹9.5 LPA (Indicative range)",
            "salary_indicative": "Junior EV Technician: ₹3.5 - 5 LPA | Certified High-Voltage Diagnostic Specialist (3-5 yrs): ₹6.0 - 9.5 LPA | EV Service Center Manager / Fleet Technical Head: ₹10 - 18+ LPA. Indicative figures from Automotive Skills Development Council (ASDC).",
            "future_scope": "Rapidly growing demand as India transitions to electric mobility across two-wheelers (Ola, Ather), three-wheelers, and electric city buses.",
            "government_opportunities": "State Road Transport Corporations (servicing municipal electric bus fleets - DTC Delhi, BEST Mumbai, BMTC Bengaluru), ARAI Pune.",
            "private_opportunities": "Tata Motors Passenger Electric Mobility, Ather Energy, Ola Electric, Mahindra Last Mile Mobility, Hero Electric, BluSmart Mobility, MG Motor India.",
            "higher_study_options": "Diploma in EV Technology, B.Voc in Automotive Mechatronics.",
            "entrepreneurship_options": "Starting a multi-brand electric two-wheeler service center or EV battery reconditioning and swapping hub.",
            "source": "Automotive Skills Development Council (ASDC) / ARAI",
            "official_url": "https://www.asdc.org.in",
            "verification_status": "VERIFIED",
            "is_lesser_known": False,
            "career_family": "Skilled Trades",
            "interest_clusters": "Hands-on, Machines, Trades, Technology",
            "work_style": "Workshop, Factory",
            "reality_check": "Involves working with lethal high voltages (up to 400V-800V DC): requires absolute adherence to high-voltage safety interlocks and insulated protective equipment.\nDistinct from traditional petrol/diesel mechanics: requires diagnosing software codes, CAN bus signals, and electronic controllers rather than changing engine oil.\nHigh-technology skilled trade of the future.",
            "next_steps": "Pass Class 10 or 12 or complete ITI in Motor Mechanic Vehicle or Electrician.\nEnroll in an ASDC-accredited Electric Vehicle Service Technician certification program.\nApprentice at an authorized EV service center (Tata Motors EV, Ather, Ola) to gain hands-on high-voltage certification.",
            "courses": [{"course_id": 64, "type": "PRIMARY"}],
            "exams": [],
            "routes": [{"title": "Path A: ASDC EV Technician Route", "type": "PRIMARY", "steps": "Class 10/12/ITI -> ASDC Certified EV Technician Training -> Service Apprenticeship -> High-Voltage EV Technician -> Workshop Manager."}],
            "ladder": [
                {"stage": "Apprentice EV Technician", "exp": "0-2 Years", "desc": "Carries out mechanical suspension and tire maintenance, assists in charging port diagnostics under supervision."},
                {"stage": "High-Voltage EV Diagnostic Technician", "exp": "2-5 Years", "desc": "Independently de-energizes EV high-voltage systems, diagnoses BMS software faults, replaces battery modules."},
                {"stage": "EV Service Workshop Manager / Fleet Head", "exp": "5+ Years", "desc": "Manages entire commercial electric fleet depot operations, oversees technician safety training and battery disposal."}
            ]
        }
    ]

def get_beauty_wellness_and_research_careers():
    return [
        {
            "title": "Clinical Aesthetician & Advanced Skincare Therapist",
            "short_name": "Clinical Aesthetician",
            "slug": "clinical-aesthetician",
            "category": "Beauty, Wellness & Personal Services",
            "sub_category": "Aesthetics & Advanced Skincare",
            "industry": "Dermatology Clinics, Medi-Spas & Medical Aesthetics",
            "icon": "sparkles",
            "short_description": "Performs advanced non-invasive skin therapies, chemical peels, laser hair reduction, and hydra-facials.",
            "description": "Clinical Aestheticians are trained skincare professionals who operate in medical cosmetology clinics and dermatology centers under the supervision of dermatologists. They evaluate skin types, perform advanced non-invasive clinical skincare therapies—including chemical peels, microdermabrasion, hydra-facials, and laser hair reduction—and guide clients on evidence-based daily skincare regimens.",
            "what_they_do": "They analyze skin barrier health with diagnostic skin scanners, administer superficial chemical peels (glycolic, salicylic), operate diode/alexandrite aesthetic lasers for hair reduction, and perform sterile medical facials.",
            "day_to_day_work": "• Conducting computerized facial skin barrier and pigmentation diagnostics.\n• Performing customized hydra-dermabrasion and chemical exfoliation protocols.\n• Operating diode laser systems for safe, non-invasive hair reduction treatments.\n• Advising clients on active dermatological skincare ingredients (retinoids, hyaluronic acid, vitamin C).\n• Maintaining sterile clinic room disinfection and client medical documentation.",
            "work_environment": "Dermatology clinics, medical aesthetic centers, premium medi-spas.",
            "work_modes": "On-site / Clinic / Medi-Spa",
            "minimum_qualification": "Vocational Diploma in Clinical Cosmetology / Aesthetics (CIDESCO / CIBTAC / VLCC Institute - 1-2 Years)",
            "preferred_streams": "Any Stream (Life Sciences or Beauty & Wellness background helpful)",
            "required_subjects": "Skin Anatomy & Physiology, Cosmetic Chemistry, Laser Physics Basics",
            "technical_skills": "Skin Typology Analysis (Fitzpatrick Scale), Chemical Peels Application, Medical Facial Protocols, Aesthetic Laser Operation, Hygiene & Infection Control, Active Cosmeceutical Knowledge",
            "soft_skills": "Refined Client Manner, Gentle Touch, Empathetic Listening, Discretion",
            "tools": "Hydra-Facial Machines, Skin Diagnostic Analyzers, Diode Aesthetic Lasers, Micro-Needling Devices, High-Frequency Wands",
            "certifications": "CIDESCO International Diploma in Beauty Therapy / Aesthetics, CIBTAC UK Certification, Beauty & Wellness Sector Skill Council (B&WSSC) Certificate",
            "experience_level": "Entry to Head Aesthetician",
            "career_growth": "Advance to Senior Clinical Aesthetician, Medi-Spa Director, or Clinical Aesthetic Trainer.",
            "internship_roles": "Cosmetology Clinic Intern, Aesthetician Trainee",
            "entry_level_roles": "Junior Aesthetician, Skincare Therapist, Laser Technician Assistant",
            "average_salary": "₹3.5 - ₹10.0+ LPA (Indicative range)",
            "salary_indicative": "Junior Aesthetician: ₹3.5 - 5.5 LPA | Experienced Aesthetic Specialist (3-5 yrs): ₹6.0 - 10 LPA | Lead Aesthetician in High-End Dermatology Clinic: ₹10 - 18+ LPA. Indicative figures from B&WSSC and clinical aesthetics networks.",
            "future_scope": "Booming industry driven by growing urban awareness of dermatological skincare, anti-aging therapies, and non-invasive medical aesthetics.",
            "government_opportunities": "Beauty & Wellness Sector Skill Council (B&WSSC certified master trainer roles).",
            "private_opportunities": "Kaya Skin Clinic, Oliva Skin & Hair Clinic, VLCC Healthcare, Kosmoderma, Premium Dermatology Centers, Luxury 5-Star Hotel Medi-Spas.",
            "higher_study_options": "Advanced CIDESCO Post-Graduate Diploma in Medical Aesthetics, Cosmeceutical Formulation Studies.",
            "entrepreneurship_options": "Founding a boutique skincare studio, medi-spa, or personalized aesthetic clinic.",
            "source": "Beauty & Wellness Sector Skill Council (B&WSSC) / CIDESCO International",
            "official_url": "https://bwssc.in",
            "verification_status": "VERIFIED",
            "is_lesser_known": False,
            "career_family": "Beauty & Wellness",
            "interest_clusters": "Healthcare, Hands-on, People, Beauty",
            "work_style": "Clinic, Studio",
            "reality_check": "Aestheticians are non-medical skincare specialists: they do NOT perform invasive medical procedures or prescribe prescription medications (Dermatologists holding MBBS + MD Dermatology handle medical diseases and injectables).\nRequires strict sterile hygiene and infection control to protect client skin barriers.\nDemands deep technical understanding of cosmetic chemistry and skin histology.",
            "next_steps": "Complete Class 12 in any stream.\nEnroll in an accredited 1 to 2-year Diploma in Clinical Aesthetics from a recognized institution (e.g. CIDESCO-affiliated academy or VLCC Institute).\nComplete clinical internships in dermatology clinics and gain certification in laser and peel safety.",
            "courses": [{"course_id": 64, "type": "RELATED"}],
            "exams": [],
            "routes": [{"title": "Path A: CIDESCO Aesthetics Route", "type": "PRIMARY", "steps": "Class 12 (Any Stream) -> CIDESCO International Diploma in Aesthetics -> Dermatology Clinic Internship -> Clinical Aesthetician."}],
            "ladder": [
                {"stage": "Junior Skincare Therapist", "exp": "0-2 Years", "desc": "Performs medical facials, cleans skin diagnostic tools, assists senior aestheticians."},
                {"stage": "Clinical Aesthetician / Laser Specialist", "exp": "2-5 Years", "desc": "Independently administers chemical peels, diode lasers, hydra-dermabrasion, advises skincare routines."},
                {"stage": "Lead Aesthetician / Clinic Manager", "exp": "5+ Years", "desc": "Manages clinical aesthetics protocols across multi-location clinics, trains junior therapists."}
            ]
        },
        {
            "title": "Pure Mathematics Researcher & Number Theorist",
            "short_name": "Mathematician",
            "slug": "pure-mathematics-researcher",
            "category": "Science, Research & Mathematics",
            "sub_category": "Pure Mathematics & Theoretical Research",
            "industry": "Academic Research, Cryptography & Theoretical Sciences",
            "icon": "infinity",
            "short_description": "Researches abstract mathematical structures, prime number theory, algebraic geometry, and cryptographic algorithms.",
            "description": "Pure Mathematics Researchers and Number Theorists explore fundamental mathematical truths, abstract algebraic structures, topology, and the deep properties of prime numbers. Working in premier institutes like TIFR, CMI, and IISc, their discoveries form the theoretical foundation for modern computer cryptography, quantum computing, topological physics, and data security.",
            "what_they_do": "They formulate and prove novel mathematical theorems, investigate long-standing conjectures (Riemann Hypothesis, Langlands Program), publish in leading mathematics journals, and lecture advanced graduate scholars.",
            "day_to_day_work": "• Reading advanced mathematical preprints on arXiv in algebraic geometry and analytic number theory.\n• Working through rigorous formal proofs on chalkboards, investigating deep symmetries.\n• Collaborating with international research mathematicians on collaborative theorem proofs.\n• Writing mathematical research papers in LaTeX with rigorous epsilon-delta precision.\n• Lecturing university undergraduate and doctoral scholars on abstract algebra and topology.",
            "work_environment": "Mathematics research institutes (TIFR, CMI, IMSc), university mathematics departments.",
            "work_modes": "Office / Library / Academic Campus",
            "minimum_qualification": "Postgraduate (M.Sc / Integrated M.Sc in Mathematics -> Ph.D. in Pure Mathematics)",
            "preferred_streams": "Science (PCM) with intense love for Mathematics",
            "required_subjects": "Pure Mathematics, Abstract Algebra, Real & Complex Analysis, Number Theory",
            "technical_skills": "Rigorous Mathematical Proof, Abstract Algebra (Groups, Rings, Fields), Algebraic Geometry, Analytic Number Theory, Topology, Cryptographic Number Theory, LaTeX",
            "soft_skills": "Deep Intellectual Curiosity, High Abstract Thinking, Tenacity on Unsolved Problems, Solitary Focus",
            "tools": "LaTeX, Overleaf, arXiv, Mathematica, SageMath, Magma Computational Algebra",
            "certifications": "CSIR-UGC NET JRF in Mathematical Sciences, National Board for Higher Mathematics (NBHM) Fellowship",
            "experience_level": "Doctoral Scholar to Professor of Mathematics",
            "career_growth": "Advance to Assistant Professor, Associate Professor, Full Professor, and Bhatnagar Awardee / FNASc.",
            "internship_roles": "Summer Mathematics Research Fellow (TIFR VSRP / IMSc Summer Program)",
            "entry_level_roles": "Postdoctoral Research Fellow, Assistant Professor of Mathematics, Cryptographic Scientist",
            "average_salary": "₹8.0 - ₹20.0+ LPA (Indicative range)",
            "salary_indicative": "NBHM / CSIR Doctoral Fellow: ₹4.5 - 5.5 LPA stipend | Postdoctoral Fellow: ₹7 - 9 LPA | Assistant Professor at TIFR/IISc/IIT (7th CPC Level 12): ₹12 - 18 LPA | Senior Professor: ₹20 - 32+ LPA. Indicative figures from TIFR and IISc pay scales.",
            "future_scope": "Fundamental intellectual powerhouse: Pure number theory powers modern post-quantum cryptography and blockchain security.",
            "government_opportunities": "Tata Institute of Fundamental Research (TIFR Mumbai), Chennai Mathematical Institute (CMI), Institute of Mathematical Sciences (IMSc Chennai), IISc Bengaluru, IITs.",
            "private_opportunities": "Cryptography R&D divisions in tech giants (Google Research, Microsoft Research Cryptography Group), Quantitative algorithmic trading firms.",
            "higher_study_options": "Postdoctoral Research Fellowships (Princeton IAS, Cambridge, IHES France).",
            "entrepreneurship_options": "Founding an advanced cryptographic security and zero-knowledge proof technology startup.",
            "source": "National Board for Higher Mathematics (NBHM) / TIFR",
            "official_url": "https://www.nbhm.dae.gov.in",
            "verification_status": "VERIFIED",
            "is_lesser_known": False,
            "career_family": "Scientific Discovery",
            "interest_clusters": "Numbers, Science, Research, Analysis",
            "work_style": "Office, School, Library",
            "reality_check": "Pure mathematics is abstract proof, NOT numerical calculation: it deals with logical axioms, infinite sets, and abstract dimensions rather than arithmetic.\nRequires solving problems where no formula exists yet; researchers can spend months or years working on a single stubborn proof.\nOne of the most intellectually pure and timeless pursuits in human civilization.",
            "next_steps": "Pass Class 12 with exceptional marks in Mathematics.\nAppear for the entrance exams for premier mathematics institutes: CMI Entrance Exam, ISI Entrance Exam, or KVPY/JEE for IISc.\nComplete B.Sc (Hons) / B.Math at CMI, ISI, or IISc, and secure the NBHM Fellowship for doctoral research.",
            "courses": [{"course_id": 16, "type": "PRIMARY"}],
            "exams": [{"exam_id": 33, "importance": "PRIMARY"}],
            "routes": [{"title": "Path A: CMI / ISI to Mathematics Ph.D.", "type": "PRIMARY", "steps": "12th (PCM) -> CMI / ISI Entrance -> B.Math / B.Sc Maths (3 yrs) -> NBHM Fellowship -> Ph.D. in Mathematics -> Mathematics Professor."}],
            "ladder": [
                {"stage": "Doctoral Scholar (NBHM / CSIR JRF)", "exp": "0-5 Years", "desc": "Takes advanced graduate courses, writes original dissertation theorems in algebraic geometry or number theory."},
                {"stage": "Postdoctoral Fellow / Assistant Professor", "exp": "5-10 Years", "desc": "Publishes breakthroughs in international journals (Annals of Mathematics), teaches advanced analysis."},
                {"stage": "Full Professor / Chair of Mathematics", "exp": "10+ Years", "desc": "Heads national mathematical research groups, mentors Ph.D. scholars, recognized with national academy honors."}
            ]
        }
    ]
