"""
scripts/catalog_builder_part8.py
Final batch of authentic occupational profiles completing all 14 sectors to 126 careers.
"""

def get_final_comprehensive_batch():
    return [
        # --- BUSINESS & MANAGEMENT ---
        {
            "title": "Business Analyst",
            "short_name": "Business Analyst",
            "slug": "business-analyst",
            "category": "Business, Management & Consulting",
            "sub_category": "Business Analysis & Systems",
            "industry": "Information Technology / Consulting",
            "icon": "clipboard-data",
            "short_description": "Translates complex business needs into precise technology specifications, bridging corporate stakeholders and software engineers.",
            "description": "Business Analysts evaluate organizational processes, identify inefficiencies, gather user requirements, and construct business requirement documents (BRDs). They ensure engineering teams build software that directly delivers business value.",
            "what_they_do": "They interview business stakeholders, document user stories and functional specifications (FRDs), create process flow diagrams in Visio, model data relationships, and conduct User Acceptance Testing (UAT).",
            "day_to_day_work": "• Conducting requirement discovery workshops with product and sales leaders.\n• Drafting Business Requirement Documents (BRD) and functional specifications.\n• Modeling As-Is and To-Be business process workflows in BPMN.\n• Running sprint planning backlog grooming with engineering teams.\n• Leading User Acceptance Testing (UAT) signoffs before product release.",
            "work_environment": "IT campuses, corporate finance offices, consulting hubs.",
            "work_modes": "Hybrid / Office / Remote",
            "minimum_qualification": "Undergraduate (B.Tech / BBA / B.Com / BCA)",
            "preferred_streams": "Any Stream",
            "required_subjects": "Business Studies, Mathematics / Computer Science",
            "technical_skills": "Requirement Elicitation, User Stories, BPMN, SQL, Agile/Scrum, UAT Testing, Wireframing, Excel",
            "soft_skills": "Stakeholder Facilitation, Active Listening, Clear Documentation, Problem Solving",
            "tools": "Jira, Confluence, Microsoft Visio, Lucidchart, SQL, Excel, Balsamiq",
            "certifications": "Certified Business Analysis Professional (CBAP - IIBA), Agile Certified Practitioner (PMI-ACP)",
            "experience_level": "Entry-Level to Senior",
            "career_growth": "Broad career path progressing to Lead Business Analyst, Product Owner, or Strategy Consultant.",
            "internship_roles": "Business Analyst Intern, Requirements Engineering Trainee",
            "entry_level_roles": "Associate Business Analyst, Junior Requirements Analyst, Systems Analyst",
            "average_salary": "₹5 - ₹14 LPA (Indicative range)",
            "salary_indicative": "Entry-Level (0-2 yrs): ₹4.5 - 7 LPA | Senior Business Analyst (3-6 yrs): ₹8 - 16 LPA | Lead BA / Product Owner (7+ yrs): ₹18 - 36+ LPA. Indicative figures from IIBA 2024.",
            "future_scope": "Consistently essential as every digital product, ERP rollout, and system integration requires precise business analysis.",
            "government_opportunities": "National Informatics Centre (NIC), Digital India Project Management Units, State e-Governance Cells.",
            "private_opportunities": "TCS, Infosys, Accenture, Cognizant, Deloitte, Amazon, Flipkart, standard banking technology divisions.",
            "higher_study_options": "MBA in Systems / Business Analytics, Master's in Management Information Systems (MIS).",
            "entrepreneurship_options": "Business process re-engineering consultancy, software requirements advisory firm.",
            "source": "International Institute of Business Analysis (IIBA)",
            "official_url": "https://www.iiba.org",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 9, "type": "COMMON"}, {"course_id": 14, "type": "COMMON"}, {"course_id": 17, "type": "COMMON"}, {"course_id": 18, "type": "SPECIALIZED"}],
            "exams": [{"exam_id": 8, "importance": "ALTERNATIVE"}, {"exam_id": 77, "importance": "ALTERNATIVE"}],
            "routes": [{"title": "Path A: Engineering / Management to Business Analyst", "type": "COMMON", "steps": "B.Tech / BBA -> Learn SQL, Jira, and Agile methodologies -> IIBA ECBA certification -> Junior Business Analyst."}],
            "ladder": [
                {"stage": "Associate Business Analyst", "exp": "0-2 Years", "desc": "Documents user stories, tracks Jira sprint tickets, assists in UAT test cases."},
                {"stage": "Business Analyst", "exp": "2-5 Years", "desc": "Facilitates stakeholder discovery, authors complete BRDs, designs process flows."},
                {"stage": "Senior Business Analyst / Product Owner", "exp": "5-8 Years", "desc": "Owns product feature roadmap, signs off on architectural feasibility with tech leads."},
                {"stage": "Head of Business Analysis / Practice Lead", "exp": "8+ Years", "desc": "Directs enterprise analysis framework across hundreds of consulting projects."}
            ],
            "roadmaps": {
                "Class 10": "Develop logical thinking, structured writing, and clear verbal communication.",
                "Class 12": "Choose Commerce or Science with Mathematics or Computer Science.",
                "Graduation": "Complete B.Tech, BBA, or BCA. Learn SQL queries, Agile Scrum ceremonies, and Jira software.",
                "Working Professional": "Earn the IIBA CBAP credential and specialize in fintech, healthcare, or supply chain business systems."
            }
        },
        {
            "title": "Entrepreneur / Startup Founder",
            "short_name": "Startup Founder",
            "slug": "entrepreneur-startup-founder",
            "category": "Business, Management & Consulting",
            "sub_category": "Venture Creation & Entrepreneurship",
            "industry": "Startups & Venture Creation",
            "icon": "rocket-takeoff",
            "short_description": "Identifies market opportunities, secures seed capital, builds innovative product prototypes, and scales new commercial ventures.",
            "description": "Entrepreneurs identify unaddressed consumer and industrial pain points, build minimum viable products (MVPs), assemble founding teams, raise venture capital, and build fast-growing, scalable business enterprises.",
            "what_they_do": "They discover customer problems, build product prototypes, pitch to angel investors and venture capitalists (VCs), hire key team members, achieve product-market fit (PMF), and drive growth.",
            "day_to_day_work": "• Meeting customers to understand unmet needs and refine product offerings.\n• Pitching to angel investors and venture capital firms for seed and Series A funding.\n• Recruiting founding engineers, product managers, and growth leaders.\n• Monitoring runway, monthly cash burn, unit economics, and churn rates.\n• Managing corporate governance, legal incorporation, and intellectual property.",
            "work_environment": "Startup incubators, co-working spaces, remote, high-intensity entrepreneurial hubs.",
            "work_modes": "Flexible / Intensive All-Hours Founder Mindset",
            "minimum_qualification": "Any Educational Background (Passion, Resilience & Execution Skills)",
            "preferred_streams": "Any Stream",
            "required_subjects": "Entrepreneurial Execution, Business Strategy",
            "technical_skills": "Product-Market Fit Discovery, Venture Capital Fundraising, Unit Economics Modeling, MVP Prototyping, Growth Hacking",
            "soft_skills": "Relentless Resilience, Persuasive Vision, High Risk Tolerance, Decisive Leadership",
            "tools": "Notion, Pitch Decks, Cap Table Management (Carta), Stripe, Google Workspace",
            "certifications": "Startup India DPIIT Recognition, Incubation at IIT/IIM Incubators",
            "experience_level": "Founder / CEO",
            "career_growth": "Venture trajectory progressing to Series A/B funded startup, Unicorn valuation, or public stock listing (IPO).",
            "internship_roles": "Early-Stage Startup EIR (Entrepreneur in Residence) Trainee",
            "entry_level_roles": "Founder, Co-Founder & CEO, Founding Team Member",
            "average_salary": "Equity Ownership + Living Founder Stipend (₹6 - ₹25 LPA salary, potential multi-crore equity wealth)",
            "salary_indicative": "Early Stage (0-2 yrs): Modest founder stipend ₹5 - 10 LPA + significant equity ownership (20-80%). Post-Funding (Series A+): ₹15 - 35 LPA + high-value equity stock options. Potential wealth generated via liquidity events and IPOs.",
            "future_scope": "Vibrant national priority supported by Startup India, DPIIT tax holidays, Atal Innovation Mission, and India's vibrant venture capital ecosystem.",
            "government_opportunities": "Startup India Seed Fund Scheme, BIRAC Biotechnology Grants, MeitY TIDE 2.0 grants, Atal Incubation Centres.",
            "private_opportunities": "Sequoia (Peak XV), Accel, Elevation Capital, Lightspeed, Blume Ventures, Y Combinator, Techstars.",
            "higher_study_options": "MBA in Entrepreneurship (Stanford, Harvard, IIMs), Fellowships.",
            "entrepreneurship_options": "Primary vehicle of entrepreneurship.",
            "source": "Startup India / Department for Promotion of Industry and Internal Trade (DPIIT)",
            "official_url": "https://www.startupindia.gov.in",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 9, "type": "COMMON"}, {"course_id": 17, "type": "COMMON"}, {"course_id": 18, "type": "COMMON"}, {"course_id": 16, "type": "COMMON"}],
            "exams": [{"exam_id": 8, "importance": "ALTERNATIVE"}, {"exam_id": 77, "importance": "ALTERNATIVE"}],
            "routes": [{"title": "Path A: Build and Launch Startup Route", "type": "COMMON", "steps": "Identify authentic customer friction point -> Build Minimum Viable Product (MVP) -> Test with 100 passionate early users -> Register under Startup India -> Raise Angel / Seed funding -> Scale venture."}],
            "ladder": [
                {"stage": "Ideation & MVP Prototype", "exp": "0-1 Years", "desc": "Validates problem, builds MVP with low-code or founding tech team, gets first 50 users."},
                {"stage": "Product-Market Fit & Seed Stage", "exp": "1-3 Years", "desc": "Achieves strong retention, raises seed funding ($500K-$2M), hires core team."},
                {"stage": "Growth & Scaling (Series A-C)", "exp": "3-7 Years", "desc": "Scales customer acquisition, builds management layers, expands to international markets."},
                {"stage": "Mature Enterprise / Public IPO", "exp": "7+ Years", "desc": "Leads profitable commercial corporation, rings the bell at National Stock Exchange (NSE)."}
            ],
            "roadmaps": {
                "Class 10": "Read biographies of innovative founders (Steve Jobs, Ratan Tata, Narayana Murthy). Start a small school project or initiative.",
                "Class 12": "Learn coding, business, or design. Build curiosity about how companies solve problems and make money.",
                "Graduation": "Build real projects, participate in university hackathons, intern at fast-growing venture-backed startups to learn how they operate.",
                "Working Professional": "Identify an authentic problem in your industry, build an MVP, apply to premier incubators (Y Combinator, IIT Incubators), and launch."
            }
        },
        {
            "title": "Marketing Manager",
            "short_name": "Marketing Manager",
            "slug": "marketing-manager",
            "category": "Business, Management & Consulting",
            "sub_category": "Marketing & Brand Growth",
            "industry": "Consumer Goods, Technology & Retail",
            "icon": "bullseye",
            "short_description": "Designs and executes comprehensive marketing campaigns to build consumer demand, brand equity, and market share.",
            "description": "Marketing Managers lead the overall marketing strategy for a brand or product line. They integrate market research, consumer psychology, pricing strategies, product packaging, and advertising campaigns across digital, print, and television channels.",
            "what_they_do": "They manage marketing budgets, lead creative advertising agencies, execute product launch campaigns, analyze consumer brand perception, and coordinate trade promotions with regional sales teams.",
            "day_to_day_work": "• Reviewing market share data and brand health tracking metrics.\n• Briefing advertising and creative agencies on upcoming seasonal campaigns.\n• Approving TV commercial storyboards, social creative assets, and influencer partnerships.\n• Coordinating with trade marketing teams on retail shelf placement and dealer schemes.\n• Tracking Return on Marketing Investment (ROMI) across channels.",
            "work_environment": "Corporate brand headquarters, FMCG regional hubs, advertising studios.",
            "work_modes": "Hybrid / Corporate Office / Consumer Field Visits",
            "minimum_qualification": "Undergraduate (BBA / B.Com / Any Degree) + MBA in Marketing preferred",
            "preferred_streams": "Commerce / Humanities / Management",
            "required_subjects": "Marketing, Consumer Behavior, Economics",
            "technical_skills": "Brand Strategy, Go-to-Market (GTM) Planning, Market Research, Advertising Campaign Management, Media Planning, Budgeting",
            "soft_skills": "Consumer Empathy, Creative Vision, Persuasive Leadership, Analytical Mindset",
            "tools": "Nielsen Retail Audits, Kantar Brand Health, Google Analytics, Excel, PowerPoint",
            "certifications": "MBA in Marketing from top b-schools, Chartered Institute of Marketing (CIM)",
            "experience_level": "Entry-Level to Senior",
            "career_growth": "Direct executive progression to Brand Director, VP Marketing, or Chief Commercial Officer (CCO).",
            "internship_roles": "Marketing Intern, Brand Management Trainee, Market Research Intern",
            "entry_level_roles": "Assistant Brand Manager, Marketing Associate, Product Marketing Specialist",
            "average_salary": "₹6 - ₹18 LPA (Indicative range)",
            "salary_indicative": "Assistant Brand Manager (0-2 yrs): ₹5.5 - 9 LPA | Marketing Manager (3-6 yrs): ₹12 - 22 LPA | VP Marketing / Chief Marketing Officer (7+ yrs): ₹28 - 70+ LPA. Indicative figures from Indian FMCG & Tech Audits 2024.",
            "future_scope": "Consistently vital across consumer goods (FMCG), consumer electronics, automotive, and digital consumer internet companies.",
            "government_opportunities": "National Cooperative Development Corporation (NCDC), State Tourism Marketing Boards, Spices Board of India.",
            "private_opportunities": "Hindustan Unilever, Procter & Gamble, Nestlé, ITC, Marico, Samsung, Coca-Cola, D2C brands.",
            "higher_study_options": "MBA in Marketing (IIMs, FMS, XLRI), Executive Leadership Programs.",
            "entrepreneurship_options": "Consumer brand founder (D2C), marketing strategy consultancy, boutique creative agency.",
            "source": "Advertising Standards Council of India (ASCI) / Top B-School Placement Audits",
            "official_url": "https://www.ascionline.in",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 18, "type": "DIRECT"}, {"course_id": 17, "type": "COMMON"}, {"course_id": 16, "type": "COMMON"}],
            "exams": [{"exam_id": 77, "importance": "PRIMARY"}, {"exam_id": 78, "importance": "PRIMARY"}],
            "routes": [{"title": "Path A: Premier MBA in Marketing Route", "type": "COMMON", "steps": "Graduation in any stream -> CAT / XAT -> Top IIM / FMS / MDI / XLRI Marketing MBA -> On-campus FMCG placement as Assistant Brand Manager."}],
            "ladder": [
                {"stage": "Assistant Brand Manager", "exp": "0-2 Years", "desc": "Manages packaging updates, runs digital creative shoots, tracks retail Nielsen market share."},
                {"stage": "Marketing / Brand Manager", "exp": "2-5 Years", "desc": "Owns entire brand P&L, directs multi-crore national TV/digital campaigns, launches new SKUs."},
                {"stage": "Category / Marketing Director", "exp": "5-9 Years", "desc": "Directs category portfolio (e.g. skin care, beverages), leads regional expansion strategy."},
                {"stage": "Chief Marketing Officer (CMO)", "exp": "9+ Years", "desc": "Owns enterprise-wide brand reputation, global marketing budget, and customer growth."}
            ],
            "roadmaps": {
                "Class 10": "Observe television commercials, billboards, and consumer packaging. Ask why people choose one brand over another.",
                "Class 12": "Choose Commerce or Humanities with English, Business Studies, and Economics.",
                "Graduation": "Complete BBA, B.Com, or any degree with active involvement in marketing fests. Prepare for CAT/XAT for top marketing b-schools.",
                "Working Professional": "Master brand positioning, consumer journey mapping, and full-funnel digital integration."
            }
        },
        {
            "title": "Operations Manager",
            "short_name": "Operations Manager",
            "slug": "operations-manager",
            "category": "Business, Management & Consulting",
            "sub_category": "Operations & Operational Excellence",
            "industry": "Manufacturing, E-Commerce & Services",
            "icon": "gear",
            "short_description": "Oversees the daily operational systems of an organization, ensuring productivity, cost efficiency, and quality execution.",
            "description": "Operations Managers are the operational backbone of businesses. They ensure that facilities, employees, supply chains, customer service centers, and IT systems run smoothly, on time, and within allocated budget constraints.",
            "what_they_do": "They design operational workflows, monitor Key Performance Indicators (KPIs), allocate manpower, troubleshoot daily operational bottlenecks, and implement cost-saving process improvements.",
            "day_to_day_work": "• Reviewing daily operational throughput, SLA metrics, and error rates.\n• Allocating shift staffing and managing vendor contracts.\n• Troubleshooting immediate logistics, IT, or facility breakdowns.\n• Implementing Lean / Six Sigma continuous improvement initiatives.\n• Preparing monthly operational cost reports and productivity forecasts for executives.",
            "work_environment": "Corporate hubs, operational service centers, distribution facilities.",
            "work_modes": "On-site / Facility Management / Hybrid",
            "minimum_qualification": "Undergraduate (BBA / B.Tech / B.Com / Any Stream) + MBA in Operations preferred",
            "preferred_streams": "Any Stream (Engineering / Management advantageous)",
            "required_subjects": "Operations Management, Business Administration",
            "technical_skills": "Operations Management, Process Optimization, SLA Tracking, KPI Dashboards, Quality Assurance, Six Sigma, Budget Management",
            "soft_skills": "Pragmatic Problem Solving, Decisive Crisis Leadership, Clear Direction, Tenacity",
            "tools": "Jira, Asana, Microsoft Excel (Advanced), ERP Systems (SAP/Oracle), Power BI",
            "certifications": "Six Sigma Green Belt / Black Belt, Project Management Professional (PMP)",
            "experience_level": "Entry-Level to Senior",
            "career_growth": "Broad corporate path progressing to VP of Operations, General Manager, or Chief Operating Officer (COO).",
            "internship_roles": "Operations Intern, Process Improvement Trainee",
            "entry_level_roles": "Operations Executive, Operations Associate, Facility Coordinator",
            "average_salary": "₹5 - ₹15 LPA (Indicative range)",
            "salary_indicative": "Operations Executive (0-2 yrs): ₹4 - 6.5 LPA | Operations Manager (3-6 yrs): ₹8 - 16 LPA | Chief Operating Officer (7+ yrs): ₹24 - 55+ LPA. Indicative figures from Corporate Operations Audits 2024.",
            "future_scope": "Universal necessity across hospitals, e-commerce, banking service centers, hospitality, and manufacturing.",
            "government_opportunities": "Airport Operations (AAI), Postal Operations, Railway Operations, Port Trust Operations.",
            "private_opportunities": "Amazon Operations, Flipkart, Swiggy, Uber Operations, Marriott, Apollo Hospitals, standard corporate service hubs.",
            "higher_study_options": "MBA in Operations Management (IIM Mumbai / SPJIMR), PMP Certification.",
            "entrepreneurship_options": "Facilities management enterprise, business process outsourcing (BPO) company, operational consulting.",
            "source": "Operations Management Association / AICTE",
            "official_url": "https://www.ncs.gov.in",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 17, "type": "COMMON"}, {"course_id": 18, "type": "DIRECT"}, {"course_id": 9, "type": "COMMON"}],
            "exams": [{"exam_id": 77, "importance": "PRIMARY"}, {"exam_id": 78, "importance": "ALTERNATIVE"}],
            "routes": [{"title": "Path A: Degree + Operations Experience Route", "type": "COMMON", "steps": "Undergraduate degree -> Operations Associate -> Learn Six Sigma & Process Automation -> Operations Manager."}],
            "ladder": [
                {"stage": "Operations Associate", "exp": "0-2 Years", "desc": "Monitors shift tickets, tracks SLA compliance, resolves customer escalation tickets."},
                {"stage": "Operations Manager", "exp": "2-5 Years", "desc": "Manages full facility or operational team, drives Kaizen cost savings, tracks budget."},
                {"stage": "Director of Operations", "exp": "5-8 Years", "desc": "Directs multi-city operational hubs, designs enterprise standard operating procedures (SOPs)."},
                {"stage": "Chief Operating Officer (COO)", "exp": "8+ Years", "desc": "Second-in-command of corporation, directs complete business execution and infrastructure."}
            ],
            "roadmaps": {
                "Class 10": "Develop organizational skills, arithmetic proficiency, and leadership in school activities.",
                "Class 12": "Choose any stream for Class 12 board exams.",
                "Graduation": "Complete BBA, B.Tech, or B.Com. Learn process mapping, advanced Excel, and study Six Sigma principles.",
                "Working Professional": "Earn PMP and Six Sigma Black Belt certifications, and master automated ERP operations."
            }
        },

        # --- SCIENCE & MATHEMATICS ---
        {
            "title": "Mathematician & Mathematical Modeler",
            "short_name": "Mathematician",
            "slug": "mathematician",
            "category": "Science, Research & Mathematics",
            "sub_category": "Pure & Applied Mathematics",
            "industry": "Scientific Research & Quantitative Finance",
            "icon": "infinity",
            "short_description": "Researches fundamental mathematical theories and develops complex quantitative models for technology, finance, and cryptography.",
            "description": "Mathematicians expand the frontiers of pure mathematical theory (algebra, topology, number theory) and apply quantitative equations to solve real-world problems in cryptography, quantum computing, quantitative algorithmic trading, and aerospace trajectories.",
            "what_they_do": "They prove mathematical theorems, construct differential equation models, design encryption algorithms (elliptic curve, post-quantum cryptography), analyze big data topologies, and publish research papers.",
            "day_to_day_work": "• Formulating and proving mathematical theorems using abstract algebra and analysis.\n• Developing computational mathematical models in Python, MATLAB, or SageMath.\n• Modeling financial derivatives and stochastic differential equations for quant funds.\n• Designing cryptographic algorithms for cybersecurity systems.\n• Delivering university mathematical lectures and writing scholarly research monographs.",
            "work_environment": "Premier mathematical institutes (TIFR, CMI, ISI, IMSc), university departments, quantitative hedge funds.",
            "work_modes": "Academic Office / Research Environment / Hybrid",
            "minimum_qualification": "Doctorate (Ph.D. in Mathematics)",
            "preferred_streams": "Science (PCM) with Mathematics",
            "required_subjects": "Mathematics",
            "technical_skills": "Abstract Algebra, Real & Complex Analysis, Differential Equations, Topology, Cryptography, Stochastic Calculus, Numerical Analysis, Python/MATLAB",
            "soft_skills": "Profound Logical Rigor, Abstract Conceptualization, Creative Problem Solving, Extreme Focus",
            "tools": "LaTeX, MATLAB, Python (SciPy/SymPy), SageMath, Mathematica, R",
            "certifications": "CSIR-UGC NET JRF in Mathematical Sciences, NBHM (National Board for Higher Mathematics) Fellowship",
            "experience_level": "Research Scholar to Professor / Principal Quantitative Researcher",
            "career_growth": "Prestigious academic trajectory to Senior Professor, Bhatnagar Awardee, or Partner at Global Quantitative Hedge Funds.",
            "internship_roles": "Summer Mathematical Research Fellow (NBHM / MTTS Program)",
            "entry_level_roles": "NBHM Doctoral Fellow, Assistant Professor, Quantitative Analyst (Quant)",
            "average_salary": "₹8 - ₹25 LPA (Academic scales / substantially higher ₹30 - 80+ LPA in Quantitative Finance)",
            "salary_indicative": "Academic Postdoc / Assistant Professor (0-3 yrs): ₹8 - 14 LPA (UGC Scales) | Quantitative Researcher in Finance (2-5 yrs): ₹25 - 60+ LPA + bonuses | Senior Professor / Bhatnagar Awardee (7+ yrs): ₹20 - 30 LPA academic.",
            "future_scope": "Growing exponentially with the rise of quantum computing algorithms, post-quantum cryptography, and algorithmic quantitative finance.",
            "government_opportunities": "TIFR (Tata Institute of Fundamental Research), Chennai Mathematical Institute (CMI), Institute of Mathematical Sciences (IMSc), DRDO Scientific Analysis Group (SAG).",
            "private_opportunities": "Tower Research Capital, Jane Street, WorldQuant, Citadel, Microsoft Research, Google Quantum AI.",
            "higher_study_options": "Postdoctoral Fellowships at Institute for Advanced Study (Princeton), IHES France.",
            "entrepreneurship_options": "Cryptographic security startup, quantitative mathematical risk modeling firm.",
            "source": "National Board for Higher Mathematics (NBHM) / CMI / TIFR",
            "official_url": "https://www.nbhm.dae.gov.in",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 1, "type": "DIRECT"}, {"course_id": 34, "type": "DIRECT"}],
            "exams": [{"exam_id": 81, "importance": "PRIMARY"}, {"exam_id": 82, "importance": "PRIMARY"}],
            "routes": [{"title": "Path A: CMI / ISI to Pure Mathematics Ph.D.", "type": "COMMON", "steps": "B.Sc (Hons) Mathematics at CMI / ISI / IIT -> M.Sc Mathematics -> NBHM / CSIR NET JRF -> Ph.D. in Mathematics -> Postdoc -> Mathematician / Professor."}],
            "ladder": [
                {"stage": "Doctoral Research Fellow (Ph.D.)", "exp": "0-5 Years", "desc": "Proves new mathematical conjectures, presents at national algebra/analysis seminars."},
                {"stage": "Postdoctoral Researcher / Assistant Professor", "exp": "5-8 Years", "desc": "Publishes in prestigious international mathematics journals (Annals of Mathematics, Inventiones)."},
                {"stage": "Associate Professor / Senior Quant", "exp": "8-15 Years", "desc": "Mentors doctoral students, designs breakthrough algorithms for cryptography or finance."},
                {"stage": "Full Professor / Bhatnagar Laureate", "exp": "15+ Years", "desc": "Recognized national authority in mathematics, elected Fellow of Indian Academy of Sciences."}
            ],
            "roadmaps": {
                "Class 10": "Participate in Regional Mathematical Olympiad (RMO) and cultivate deep love for mathematical proofs.",
                "Class 12": "Top scores in Mathematics. Prepare for Chennai Mathematical Institute (CMI) and Indian Statistical Institute (ISI) entrance exams.",
                "Graduation": "Complete B.Sc in Mathematics with rigorous proof-based courses (Topology, Abstract Algebra, Real Analysis). Clear IIT JAM or NBHM.",
                "Working Professional": "Clear CSIR-UGC NET JRF or NBHM Ph.D. fellowship, enroll in doctoral research at TIFR, CMI, or IMSc."
            }
        },
        {
            "title": "Space Scientist / Astrophysicist",
            "short_name": "Astrophysicist",
            "slug": "space-scientist-astrophysicist",
            "category": "Science, Research & Mathematics",
            "sub_category": "Astronomy, Astrophysics & Space Science",
            "industry": "Space Sciences & Astronomy",
            "icon": "stars",
            "short_description": "Investigates celestial bodies, galaxies, black holes, gravitational waves, and the cosmic origin of the universe.",
            "description": "Astrophysicists explore the universe beyond Earth using optical telescopes, radio antennas (GMRT), space observatories (AstroSat), and gravitational wave detectors (LIGO-India). They study stellar evolution, exoplanets, dark matter, and cosmological radiation.",
            "what_they_do": "They analyze astronomical observational data from space telescopes, run magnetohydrodynamic cosmic simulations on supercomputers, model black hole accretion disks, and participate in planetary exploration missions.",
            "day_to_day_work": "• Analyzing spectroscopic and radio astronomy data from GMRT or space telescopes.\n• Writing computational astrophysics simulations in Python and C++ on supercomputing clusters.\n• Planning observation time proposals for international optical and radio telescopes.\n• Modeling gravitational wave signals from merging neutron stars and black holes.\n• Authoring scientific papers for publication in Astrophysical Journal or Monthly Notices of the RAS.",
            "work_environment": "Astronomical observatories, space science institutes, university physics departments.",
            "work_modes": "On-site / Observatory Control Center / Academic Lab",
            "minimum_qualification": "Doctorate (Ph.D. in Astrophysics / Astronomy / Physics)",
            "preferred_streams": "Science (PCM)",
            "required_subjects": "Physics, Mathematics",
            "technical_skills": "Astrophysical Modeling, Radio Astronomy, Stellar Physics, Gravitational Wave Physics, General Relativity, Python (Astropy), High-Performance Computing",
            "soft_skills": "Cosmic Curiosity, Scientific Patience, Tenacity, Teamwork in Global Consortia",
            "tools": "Astropy, CASA (Common Astronomy Software Applications), Python, DS9, Topcat, LaTeX",
            "certifications": "CSIR-UGC NET JRF in Physical Sciences, JEST (Joint Entrance Screening Test)",
            "experience_level": "Postdoctoral Fellow to Senior Scientist / Observatory Director",
            "career_growth": "Prestigious trajectory progressing to Principal Investigator of Space Telescope Missions, Observatory Director, or Fellow of the Royal Astronomical Society.",
            "internship_roles": "Visiting Students' Research Programme (VSRP - TIFR), IUCAA Summer School Intern",
            "entry_level_roles": "Research Fellow (JRF), Scientist 'SC' (ISRO Space Sciences), Postdoctoral Fellow",
            "average_salary": "₹7 - ₹18 LPA (Official 7th CPC Scientist Grade / UGC Academic Pay Scales)",
            "salary_indicative": "Research Fellow / Postdoc (0-3 yrs): ₹37,000 - ₹54,000/mo fellowship + HRA | Scientist SC/SD (3-6 yrs): ₹67,700 - ₹1,10,000/mo basic + perks | Director / Senior Professor: ₹1,80,000 - ₹2,25,000/mo.",
            "future_scope": "Surging national growth powered by mega-science projects: LIGO-India, Thirty Meter Telescope (TMT), Square Kilometre Array (SKA), and ISRO planetary probes.",
            "government_opportunities": "IUCAA Pune, Indian Institute of Astrophysics (IIA Bengaluru), TIFR, ISRO (Space Science Programme Office), PRL Ahmedabad.",
            "private_opportunities": "Space observatory consultancies, computational data science divisions, international astronomy consortia.",
            "higher_study_options": "Postdoctoral Fellowships at NASA Goddard, Max Planck Institute for Astronomy, ESO.",
            "entrepreneurship_options": "Astronomical instrumentation startup, educational planetarium and sky-watching enterprise.",
            "source": "Inter-University Centre for Astronomy and Astrophysics (IUCAA) / ISRO",
            "official_url": "https://www.iucaa.in",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 2, "type": "DIRECT"}, {"course_id": 35, "type": "DIRECT"}, {"course_id": 1, "type": "COMMON"}],
            "exams": [{"exam_id": 81, "importance": "PRIMARY"}, {"exam_id": 69, "importance": "PRIMARY"}, {"exam_id": 82, "importance": "PRIMARY"}],
            "routes": [{"title": "Path A: Physics Degree to Astrophysics Ph.D.", "type": "COMMON", "steps": "B.Sc Physics -> IIT JAM / JEST -> M.Sc Physics / Astrophysics -> Clear JEST / CSIR NET JRF -> Ph.D. at IUCAA / IIA / TIFR -> Postdoc -> Space Scientist."}],
            "ladder": [
                {"stage": "Ph.D. Scholar / JRF", "exp": "0-5 Years", "desc": "Processes space telescope data, models cosmic spectra, writes doctoral thesis."},
                {"stage": "Postdoctoral Researcher / Scientist SC", "exp": "5-8 Years", "desc": "Leads observational campaigns at Giant Metrewave Radio Telescope (GMRT), publishes in Nature/ApJ."},
                {"stage": "Principal Scientist / Associate Professor", "exp": "8-15 Years", "desc": "Serves as Instrument Scientist on space telescope missions (e.g. AstroSat), mentors Ph.D. scholars."},
                {"stage": "Observatory Director / Mission PI", "exp": "15+ Years", "desc": "Heads national astronomical observatories and directs India's deep-space science exploration."}
            ],
            "roadmaps": {
                "Class 10": "Read popular science books on astronomy (Carl Sagan, Stephen Hawking) and learn night sky constellations.",
                "Class 12": "Excel in Physics (optics, gravitation, electromagnetic spectrum) and Mathematics (calculus).",
                "Graduation": "Complete B.Sc Physics with deep focus on modern physics and computational coding (Python). Clear IIT JAM or JEST.",
                "Working Professional": "Clear JEST (Joint Entrance Screening Test) for premier doctoral research at IUCAA, IIA, or TIFR."
            }
        },

        # --- EDUCATION ---
        {
            "title": "Educational & School Counsellor",
            "short_name": "School Counsellor",
            "slug": "educational-counsellor",
            "category": "Education, Teaching & Academia",
            "sub_category": "Student Welfare & Guidance",
            "industry": "School & Higher Education",
            "icon": "person-heart",
            "short_description": "Guides students through academic choices, emotional challenges, career discovery, and personal development.",
            "description": "Educational and School Counsellors support the mental, emotional, and academic well-being of students. They administer career aptitude assessments, counsel students through exam stress and peer pressure, and guide university admissions.",
            "what_they_do": "They conduct one-on-one student counseling sessions, administer psychometric career assessments, organize career discovery fairs, conduct anti-bullying workshops, and advise parents on child development.",
            "day_to_day_work": "• Conducting confidential student counseling for anxiety, stress, and behavioral issues.\n• Administering career discovery assessments (interests, aptitudes, personality).\n• Advising high school students on university stream choices and entrance exam strategies.\n• Organizing mental health awareness sessions and study skills workshops.\n• Collaborating with school principals and special educators on student support plans.",
            "work_environment": "Schools, university counseling centers, private career guidance centers.",
            "work_modes": "On-site / School Office / Hybrid",
            "minimum_qualification": "Postgraduate (M.A. / M.Sc in Psychology / Guidance & Counselling)",
            "preferred_streams": "Humanities / Psychology / Any Stream",
            "required_subjects": "Psychology, Child Development, Education",
            "technical_skills": "Psychological Counseling, Career Aptitude Assessment, Crisis Intervention, Adolescent Psychology, Psychometrics, NEP 2020 Guidance Framework",
            "soft_skills": "Deep Empathy, Non-Judgmental Listening, Unconditional Positive Regard, Ethical Discretion",
            "tools": "Standardized Psychometric Career Inventories, Assessment Questionnaires, Student Portals",
            "certifications": "RCI Licensed Vocational Counselor / Diploma in Guidance & Counselling (NCERT)",
            "experience_level": "Entry-Level to Senior",
            "career_growth": "Broad career path progressing to Head of Student Welfare, Director of Counseling, or independent career counseling practice founder.",
            "internship_roles": "School Counseling Intern, Child Guidance Trainee",
            "entry_level_roles": "School Counselor, Career Guidance Associate, Student Welfare Officer",
            "average_salary": "₹4 - ₹10 LPA (Indicative range)",
            "salary_indicative": "School Counselor (0-2 yrs): ₹3.5 - 5 LPA | Senior Counselor (3-6 yrs): ₹6 - 11 LPA | Private Career Advisory Practice (7+ yrs): ₹15 - 30+ LPA. Indicative figures from NCERT & School Boards 2024.",
            "future_scope": "Surging demand as CBSE mandates full-time trained counselors in every affiliated school, coupled with rising adolescent mental health awareness.",
            "government_opportunities": "Kendriya Vidyalaya Sangathan (KVS), Navodaya Vidyalayas, NCERT Department of Educational Psychology, District Child Protection Units.",
            "private_opportunities": "Delhi Public School, The Shri Ram School, international baccalaureate (IB) schools, university admission counseling firms.",
            "higher_study_options": "Ph.D. in Counseling Psychology, NCERT Diploma in Guidance and Counselling.",
            "entrepreneurship_options": "Independent career discovery center, adolescent mental health clinic, digital counseling platform.",
            "source": "NCERT (Department of Educational Psychology and Foundations of Education) / CBSE",
            "official_url": "https://ncert.nic.in",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 21, "type": "COMMON"}, {"course_id": 48, "type": "ALTERNATIVE"}],
            "exams": [{"exam_id": 79, "importance": "PRIMARY"}, {"exam_id": 10, "importance": "ALTERNATIVE"}],
            "routes": [{"title": "Path A: Psychology Master's to School Counselor", "type": "COMMON", "steps": "B.A./B.Sc Psychology -> M.A./M.Sc Counseling Psychology or NCERT Diploma in Guidance & Counselling -> School Counselor."}],
            "ladder": [
                {"stage": "Junior Counselor", "exp": "0-2 Years", "desc": "Conducts basic orientation sessions, administers standardized career interest inventories."},
                {"stage": "School Counselor", "exp": "2-5 Years", "desc": "Provides individual therapy for adolescent stress, advises high schoolers on university choices."},
                {"stage": "Head of Counseling & Well-being", "exp": "5-8 Years", "desc": "Heads multidisciplinary student wellness department, leads crisis intervention protocols."},
                {"stage": "Director of Guidance / Private Practice Founder", "exp": "8+ Years", "desc": "Directs private career counselling firm guiding thousands of students across the nation."}
            ],
            "roadmaps": {
                "Class 10": "Develop interest in listening to people, understanding human emotions, and helping friends resolve conflicts.",
                "Class 12": "Choose Humanities with Psychology for 12th board exams.",
                "Graduation": "Complete B.A./B.Sc in Psychology with top grades. Complete master's in Counseling Psychology or NCERT diploma.",
                "Working Professional": "Master psychometric assessment interpretation and gain expertise in modern career pathways (AI, Design, Law, Global degrees)."
            }
        },

        # --- MEDIA ---
        {
            "title": "Public Relations (PR) Specialist",
            "short_name": "PR Specialist",
            "slug": "pr-specialist",
            "category": "Media, Journalism & Digital Marketing",
            "sub_category": "Corporate Communications & Public Relations",
            "industry": "Corporate Communications & Media Relations",
            "icon": "broadcast",
            "short_description": "Builds and protects positive public reputation, manages media communications, and directs crisis brand response.",
            "description": "Public Relations (PR) Specialists manage the spread of information between an individual or organization and the public. They craft press releases, pitch stories to major journalists, coordinate executive interviews, and handle crisis communications to protect brand reputation.",
            "what_they_do": "They author press releases, build relationships with senior editors and journalists, manage media press conferences, prepare executive leadership for interviews, and defuse PR crises.",
            "day_to_day_work": "• Drafting and distributing official corporate press releases and media advisories.\n• Pitching trend stories and executive quotes to national journalists and editors.\n• Preparing Q&A briefing documents for corporate CEOs prior to live media interviews.\n• Monitoring brand sentiment and media coverage across print, TV, and digital portals.\n• Managing rapid response crisis communication during corporate controversies.",
            "work_environment": "PR agencies, corporate communications departments, political campaign headquarters.",
            "work_modes": "Hybrid / Agency Office / Media Events",
            "minimum_qualification": "Undergraduate (BJMC / B.A. English / Mass Communication / Any Stream)",
            "preferred_streams": "Humanities / Any Stream",
            "required_subjects": "Mass Communication, English, Public Relations",
            "technical_skills": "Media Relations, Press Release Drafting, Crisis Communication, Brand Reputation Management, Media Monitoring, Event Press Management",
            "soft_skills": "Persuasive Diplomacy, Quick Thinking, Network Building, Composure Under Public Scrutiny",
            "tools": "PR Newswire, Meltwater, Cision, Google Alerts, Media Contact Lists, Canva",
            "certifications": "Public Relations Society of India (PRSI) Professional Membership",
            "experience_level": "Entry-Level to Senior",
            "career_growth": "Fast-paced corporate career progressing to PR Account Director, VP of Corporate Communications, or Chief Communications Officer (CCO).",
            "internship_roles": "PR Agency Intern, Media Relations Trainee, Corporate Communications Intern",
            "entry_level_roles": "PR Associate, Media Coordinator, Corporate Communications Executive",
            "average_salary": "₹4.5 - ₹14 LPA (Indicative range)",
            "salary_indicative": "Entry-Level PR Associate (0-2 yrs): ₹4 - 6.5 LPA | PR Account Manager (3-6 yrs): ₹8 - 16 LPA | Head of Corporate Communications (7+ yrs): ₹22 - 50+ LPA. Indicative figures from PRCAI 2024.",
            "future_scope": "High corporate demand driven by 24x7 social media scrutiny, brand vulnerability, and investor communications.",
            "government_opportunities": "Press Information Bureau (PIB - Indian Information Service), State Information Departments, PSUs.",
            "private_opportunities": "Edelman India, Genesis BCW, Adfactors PR, MSL India, corporate communications teams of Tata, Reliance, Amazon.",
            "higher_study_options": "Master's in Corporate Communications / PR, MBA in Marketing.",
            "entrepreneurship_options": "Boutique PR agency, specialized crisis communications consulting firm, personal branding agency.",
            "source": "Public Relations Consultants Association of India (PRCAI) / PRSI",
            "official_url": "https://prcai.org",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 21, "type": "COMMON"}, {"course_id": 46, "type": "COMMON"}],
            "exams": [{"exam_id": 79, "importance": "PRIMARY"}],
            "routes": [{"title": "Path A: Mass Communication / PR Degree Route", "type": "COMMON", "steps": "Graduation in any stream -> Post Graduate Diploma in PR & Advertising (IIMC / Xavier Institute of Communications) -> Top PR Agency Hire."}],
            "ladder": [
                {"stage": "PR Associate / Media Executive", "exp": "0-2 Years", "desc": "Drafts press releases, creates media tracking dossiers, pitches journalists on phone/email."},
                {"stage": "PR Account Manager", "exp": "2-5 Years", "desc": "Manages client retainer accounts, strategizes feature placements in Tier-1 national media."},
                {"stage": "Vice President / PR Practice Head", "exp": "5-8 Years", "desc": "Leads high-stakes crisis communications, handles IPO press conferences and investor relations."},
                {"stage": "Chief Communications Officer (CCO)", "exp": "8+ Years", "desc": "Directs overall corporate narrative, government public affairs, and global executive reputation."}
            ],
            "roadmaps": {
                "Class 10": "Read national newspapers, cultivate excellent English writing, and observe how brands manage public news.",
                "Class 12": "Choose Humanities, Commerce, or Science with English for Class 12 board exams.",
                "Graduation": "Complete Bachelor's degree with focus on Journalism, English, or Mass Media. Intern at a reputed PR agency.",
                "Working Professional": "Master crisis management, develop trusted relationships with business journalists, and learn digital reputation analytics."
            }
        },

        # --- GOVERNMENT & SECURITY ---
        {
            "title": "Intelligence & Security Officer (IB ACIO)",
            "short_name": "Intelligence Officer (IB)",
            "slug": "intelligence-officer-ib",
            "category": "Government, Defence & Civil Services",
            "sub_category": "National Intelligence & Counter-Espionage",
            "industry": "Ministry of Home Affairs / Intelligence Bureau",
            "icon": "incognito",
            "short_description": "Gathers tactical intelligence, monitors counter-espionage threats, and safeguards national internal security under the Intelligence Bureau.",
            "description": "Intelligence Officers in the Intelligence Bureau (IB) collect, analyze, and act upon covert security intelligence to protect the territorial integrity of India against terrorism, espionage, insurgency, and cross-border security threats.",
            "what_they_do": "They operate intelligence collection networks, monitor signals and communications intelligence (SIGINT), conduct counter-espionage investigations, analyze threat indicators, and brief national security leadership.",
            "day_to_day_work": "• Reviewing intelligence alerts and signals intercepts.\n• Running source networks in border and sensitive security sectors.\n• Conducting counter-espionage inquiries and security background verifications.\n• Preparing high-level intelligence assessment dossiers for Ministry of Home Affairs.\n• Coordinating tactical security alerts with state police and armed forces.",
            "work_environment": "IB Headquarters (New Delhi), State Subsidiary Intelligence Bureaus (SIBs), border surveillance posts.",
            "work_modes": "On-site / Sensitive Field Assignments / Round-the-Clock Operational Readiness",
            "minimum_qualification": "Undergraduate (Any Recognized Degree) + Security Clearance",
            "preferred_streams": "Any Stream",
            "required_subjects": "Graduation in any discipline",
            "technical_skills": "Intelligence Analysis, Counter-Terrorism, SIGINT Monitoring, Cyber Intelligence, Source Management, National Security Law",
            "soft_skills": "Absolute Discretion, Mental Composure, Sharp Observation, Patriotic Commitment",
            "tools": "Classified Intelligence Databases, Signals Monitoring Equipment, Encrypted Communications",
            "certifications": "Selected through IB ACIO-II Examination, Trained at National Intelligence Academy (Shivpuri)",
            "experience_level": "Assistant Central Intelligence Officer (ACIO) to Joint Director / Director (IB)",
            "career_growth": "Prestige-filled sovereign career progressing from ACIO-II to ACIO-I, Deputy Central Intelligence Officer (DCIO), Joint Director, or Director of Intelligence Bureau.",
            "internship_roles": "National Intelligence Academy Training (6 Months)",
            "entry_level_roles": "Assistant Central Intelligence Officer Grade II (ACIO-II)",
            "average_salary": "₹8 - ₹16 LPA (Official 7th CPC Pay Level 7 Basic ₹44,900 + 20% Special Security Allowance + Perks)",
            "salary_indicative": "ACIO-II (Level 7): Basic ₹44,900 + DA (50%+) + 20% Special Security Allowance (SSA) = ~₹85,000 - ₹95,000/month gross. High allowances for hardship postings.",
            "future_scope": "Permanent, highly classified sovereign function expanding into cyber intelligence, economic security, and counter-drone warfare.",
            "government_opportunities": "Intelligence Bureau ACIO-II Examination (Ministry of Home Affairs), R&AW Deputation.",
            "private_opportunities": "Not applicable (Classified Intelligence Service). Post-retirement: Corporate security risk intelligence.",
            "higher_study_options": "Departmental intelligence specializations, National Cyber Forensics Training.",
            "entrepreneurship_options": "Not applicable (Intelligence Service).",
            "source": "Intelligence Bureau (IB) / Ministry of Home Affairs",
            "official_url": "https://www.mha.gov.in",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 9, "type": "COMMON"}, {"course_id": 20, "type": "COMMON"}, {"course_id": 22, "type": "COMMON"}],
            "exams": [{"exam_id": 42, "importance": "PRIMARY"}],
            "routes": [{"title": "Path A: IB ACIO-II Examination Route", "type": "COMMON", "steps": "Graduation in any stream -> Clear IB ACIO Tier-1 (CBT) -> Clear IB ACIO Tier-2 (Descriptive English & Essay) -> Interview & Psychometric Assessment -> National Intelligence Academy Training -> ACIO-II."}],
            "ladder": [
                {"stage": "ACIO-II / Field Officer", "exp": "0-4 Years", "desc": "Gathers tactical ground intelligence, handles source coordination, conducts background investigations."},
                {"stage": "ACIO-I / DCIO", "exp": "4-10 Years", "desc": "Gazetted Officer. Leads regional intelligence units, manages SIGINT and cyber desks."},
                {"stage": "Assistant Director / Joint Director", "exp": "10-20 Years", "desc": "Directs state Subsidiary Intelligence Bureau (SIB) operations or national counter-terror vertical."},
                {"stage": "Special Director / Director of IB (DIB)", "exp": "20+ Years", "desc": "Directs India's premier internal intelligence agency, briefs the Prime Minister and National Security Advisor."}
            ],
            "roadmaps": {
                "Class 10": "Maintain high physical fitness, mental sharpness, and broad general knowledge.",
                "Class 12": "Complete Class 12 in any stream of your choice.",
                "Graduation": "Complete graduation with focus on current affairs, national security, quantitative reasoning, and English essay writing.",
                "Working Professional": "Prepare for the IB ACIO-II examination with special focus on current geopolitical affairs, internal security challenges, and analytical writing."
            }
        }
    ]

print("Catalog builder part 8 ready.")
