"""
scripts/catalog_builder_part9.py
Final Expansion: Completing Agriculture, Aviation, Business, Design, Education,
Finance, Government, Healthcare, Media, Science, and Social Sciences.
"""

def get_expansion_batch():
    return [
        # --- AGRICULTURE (6 careers) ---
        {
            "title": "Horticulture Specialist",
            "short_name": "Horticulturist",
            "slug": "horticulture-specialist",
            "category": "Agriculture, Food Technology & Environment",
            "sub_category": "Horticulture & Floriculture",
            "industry": "Agriculture & Plant Sciences",
            "icon": "flower2",
            "short_description": "Specializes in the intensive cultivation, breeding, post-harvest handling, and commercial management of fruits, vegetables, flowers, and ornamental plants.",
            "description": "Horticulture Specialists focus on high-value fruits, vegetables, flowers, spices, and landscape plants. They design greenhouse polyhouses, optimize hydroponic nutrient solutions, manage orchards, and lead high-tech floriculture exports.",
            "what_they_do": "They manage orchard grafting and pruning, design protected greenhouse cultivation environments, optimize drip fertigation systems, manage cold storage post-harvest handling, and develop exotic fruit varieties.",
            "day_to_day_work": "• Managing greenhouse climate, humidity, and fertigation controls.\n• Conducting plant grafting, tissue culture, and cross-pollination experiments.\n• Diagnosing fungal and viral horticultural plant diseases.\n• Advising commercial fruit orchard growers on export standards.\n• Designing urban landscape and floriculture displays.",
            "work_environment": "Commercial fruit orchards, polyhouse greenhouses, botanical gardens, plant tissue culture labs.",
            "work_modes": "On-site / Farm & Greenhouse / Lab",
            "minimum_qualification": "Undergraduate (B.Sc Horticulture / Agriculture)",
            "preferred_streams": "Science (PCB / Agriculture)",
            "required_subjects": "Biology, Agriculture, Chemistry",
            "technical_skills": "Pomology, Olericulture, Floriculture, Tissue Culture, Hydroponics, Post-Harvest Cold Chain, Fertigation",
            "soft_skills": "Patience, Botany Passion, Attention to Detail, Practical Farm Execution",
            "tools": "Soil & Leaf Moisture Analyzers, Refractometers, Greenhouse Automation Systems",
            "certifications": "ICAR AIEEA Qualification / State Horticulture Officer",
            "experience_level": "Entry-Level to Senior",
            "career_growth": "Direct progression to District Horticulture Officer (DHO), Plant Plantation Manager, or Commercial Agri-Business Director.",
            "internship_roles": "Horticulture Farm Intern, Tissue Culture Trainee",
            "entry_level_roles": "Horticulture Officer, Plantation Assistant, Greenhouse Supervisor",
            "average_salary": "₹4 - ₹11 LPA (Indicative range)",
            "salary_indicative": "Entry-Level / State Officer (0-2 yrs): ₹3.8 - 6 LPA | Farm / Plantation Manager (3-6 yrs): ₹7 - 14 LPA | Commercial Export Director (7+ yrs): ₹16 - 32+ LPA. Indicative figures from National Horticulture Board (NHB) 2024.",
            "future_scope": "Surging national growth driven by the Mission for Integrated Development of Horticulture (MIDH), vertical farming, and high-value fruit/flower exports.",
            "government_opportunities": "State Horticulture Departments (via State PSC), National Horticulture Board (NHB), ICAR-IIHR (Bengaluru).",
            "private_opportunities": "Mahindra Agri Solutions, Godrej Agrovet, commercial floriculture exporters, organic fruit estates.",
            "higher_study_options": "M.Sc Horticulture (Pomology / Floriculture), Ph.D. in Horticulture.",
            "entrepreneurship_options": "Commercial polyhouse strawberry/bell-pepper farm, plant tissue culture nursery, hydroponic vegetable farm.",
            "source": "National Horticulture Board (NHB) / ICAR",
            "official_url": "https://nhb.gov.in",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 7, "type": "DIRECT"}, {"course_id": 40, "type": "COMMON"}],
            "exams": [{"exam_id": 95, "importance": "PRIMARY"}, {"exam_id": 18, "importance": "ALTERNATIVE"}],
            "routes": [{"title": "Path A: B.Sc Horticulture Route", "type": "COMMON", "steps": "Class 12 (PCB/Agri) -> ICAR AIEEA-UG / State Agri CET -> B.Sc (Hons) Horticulture (4 yrs) -> District Horticulture Officer or Corporate Plantation Manager."}],
            "ladder": [
                {"stage": "Junior Horticulturist / Farm Trainee", "exp": "0-2 Years", "desc": "Manages nursery saplings, monitors greenhouse drip systems, logs harvest yields."},
                {"stage": "Horticulture Officer / Plantation Manager", "exp": "2-5 Years", "desc": "Directs 100+ acre fruit orchards, manages cold-chain post-harvest operations."},
                {"stage": "Senior Plantation Director / DHO", "exp": "5-8 Years", "desc": "Heads district horticulture schemes or oversees multi-estate commercial agri exports."},
                {"stage": "Vice President - Agri Fresh / Chief Horticulturist", "exp": "8+ Years", "desc": "Directs national fresh produce supply chains for major retail supermarket networks."}
            ],
            "roadmaps": {
                "Class 10": "Focus on plant biology, gardening, and natural ecosystems.",
                "Class 12": "Choose Science with Biology or Agriculture for board exams.",
                "Graduation": "Complete B.Sc Horticulture from an ICAR-recognized university. Complete tissue culture and greenhouse internships.",
                "Working Professional": "Prepare for State Horticulture Officer recruitment or specialize in commercial hydroponics and protected cultivation."
            }
        },
        {
            "title": "Agricultural Extension Officer",
            "short_name": "Agri Extension Officer",
            "slug": "agricultural-extension-officer",
            "category": "Agriculture, Food Technology & Environment",
            "sub_category": "Agricultural Outreach & Rural Training",
            "industry": "Agriculture & Rural Development",
            "icon": "broadcast-pin",
            "short_description": "Acts as the vital bridge between agricultural scientists and farmers, demonstrating modern farming techniques and government welfare schemes.",
            "description": "Agricultural Extension Officers bring laboratory research to the grassroots farm field. They train farmers in climate-resilient seeds, soil testing, balanced fertilizer usage, micro-irrigation, and assist in enrolling for government welfare schemes like PM-KISAN.",
            "what_they_do": "They conduct frontline field demonstrations, organize farmer training workshops at Krishi Vigyan Kendras (KVK), promote soil health cards, facilitate farmer producer organizations (FPOs), and advise on crop pest management.",
            "day_to_day_work": "• Visiting rural villages to conduct farmer crop demonstration days.\n• Distributing Soil Health Cards and explaining balanced N-P-K dosages.\n• Training farmers on pest management and bio-pesticide applications.\n• Assisting smallholder farmers in forming Farmer Producer Organizations (FPOs).\n• Reporting regional crop damage to district agriculture officers.",
            "work_environment": "Krishi Vigyan Kendras (KVKs), block agricultural offices, rural farming villages.",
            "work_modes": "Field Work / Rural Travel / Office",
            "minimum_qualification": "Undergraduate (B.Sc Agriculture)",
            "preferred_streams": "Science (PCB / Agriculture)",
            "required_subjects": "Agriculture, Biology",
            "technical_skills": "Agricultural Extension Pedagogy, Soil Health Interpretation, Integrated Pest Management (IPM), Farmer Producer Organizations (FPO), Rural Communication",
            "soft_skills": "Rural Empathy, Public Speaking in Regional Dialects, Patience, Respect for Farmers",
            "tools": "Soil Testing Mini-Kits, Digital Projectors, Kisan Call Centre Software, GPS",
            "certifications": "Selected through State Agricultural Officer Recruitment (State PSC / Dept of Agriculture)",
            "experience_level": "Entry-Level to Senior",
            "career_growth": "Steady civil service career progressing to Block Agriculture Officer (BAO), District Agriculture Officer (DAO), or Joint Director of Agriculture.",
            "internship_roles": "Rural Agricultural Work Experience (RAWE - Integrated in B.Sc)",
            "entry_level_roles": "Agricultural Extension Officer (AEO), Village Agriculture Assistant (VAA), KVK Subject Matter Specialist",
            "average_salary": "₹4.5 - ₹10 LPA (State Pay Scale Pay Band 2: Basic ₹35,400 - ₹44,900 + DA + Field Allowance)",
            "salary_indicative": "AEO (Level 6/7): Basic ₹35,400 - ₹44,900 + DA (50%+) + HRA = ~₹55,000 - ₹70,000/month gross. Regular promotions through district administrative hierarchy.",
            "future_scope": "Essential sovereign outreach pillar driving agricultural modernization, natural farming missions, and digital agriculture portals.",
            "government_opportunities": "State Agriculture Departments (via State PSC), Krishi Vigyan Kendras (ICAR KVKs), NABARD.",
            "private_opportunities": "Agri-input companies (Tata Rallis, UPL, Coromandel), micro-finance rural units, farmer cooperative federations.",
            "higher_study_options": "M.Sc in Agricultural Extension, MBA in Agri-Business Management.",
            "entrepreneurship_options": "Custom hiring center for farm machinery, input dealership and modern farmer advisory clinic.",
            "source": "Ministry of Agriculture & Farmers Welfare / ICAR",
            "official_url": "https://agricoop.nic.in",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 7, "type": "DIRECT"}],
            "exams": [{"exam_id": 95, "importance": "PRIMARY"}, {"exam_id": 18, "importance": "ALTERNATIVE"}],
            "routes": [{"title": "Path A: B.Sc Agriculture to State Extension Officer", "type": "COMMON", "steps": "B.Sc (Hons) Agriculture -> State Public Service Commission Agricultural Officer Exam -> Field Training -> Agricultural Extension Officer."}],
            "ladder": [
                {"stage": "Village Agriculture Assistant / AEO", "exp": "0-4 Years", "desc": "Conducts block demonstrations, verifies crop insurance surveys, trains farmer clusters."},
                {"stage": "Block Agriculture Officer (BAO)", "exp": "4-10 Years", "desc": "Heads block agricultural administration, oversees certified seed and fertilizer distribution."},
                {"stage": "District Agriculture Officer (DAO)", "exp": "10-18 Years", "desc": "Directs entire district agricultural output, manages drought relief and MSP procurement."},
                {"stage": "Joint Director / Director of Agriculture", "exp": "18+ Years", "desc": "Directs statewide agricultural policy and farmer welfare schemes for millions of farming families."}
            ],
            "roadmaps": {
                "Class 10": "Develop appreciation for rural life, agriculture, and farmers.",
                "Class 12": "Choose Science with Biology or Agriculture for board exams.",
                "Graduation": "Complete B.Sc (Hons) Agriculture with rural village stay (RAWE). Master communication in regional state language.",
                "Working Professional": "Prepare for the State Agricultural Officer / Extension Officer examination conducted by State PSCs."
            }
        },
        {
            "title": "Soil & Water Conservation Specialist",
            "short_name": "Soil Conservation Specialist",
            "slug": "soil-water-conservationist",
            "category": "Agriculture, Food Technology & Environment",
            "sub_category": "Natural Resource Management & Soil Science",
            "industry": "Agriculture & Water Resources",
            "icon": "water",
            "short_description": "Designs watershed structures, checks soil erosion, and restores degraded agricultural land to ensure sustainable water and soil security.",
            "description": "Soil and Water Conservationists protect precious natural resources. They design check dams, contour bunding, rainwater harvesting aquifers, and afforestation plans to prevent topsoil erosion, enhance groundwater tables, and combat desertification.",
            "what_they_do": "They survey watershed topographies using GIS, design check dams and farm ponds, analyze soil degradation and salinity, evaluate groundwater recharge, and direct government watershed rehabilitation schemes.",
            "day_to_day_work": "• Surveying watershed contours using GIS mapping and total station instruments.\n• Designing masonry check dams, gully plugs, and percolation tanks.\n• Analyzing soil cores for erosion indices, compaction, and nutrient leaching.\n• Overseeing construction of farm ponds and rainwater harvesting recharge pits.\n• Advising village panchayats on contour plowing and cover crop planting.",
            "work_environment": "Watershed development projects, rural catchments, government irrigation and soil conservation offices.",
            "work_modes": "Field Engineering / Site Surveys / Office",
            "minimum_qualification": "Undergraduate (B.Tech Agricultural Engineering / B.Sc Agriculture / Civil Engg)",
            "preferred_streams": "Science (PCM / PCB)",
            "required_subjects": "Agriculture, Civil Engineering, Mathematics, Physics",
            "technical_skills": "Watershed Hydrology, Soil Mechanics, GIS & Remote Sensing, Check Dam Engineering, Rainwater Harvesting, Land Degradation Mapping",
            "soft_skills": "Field Endurance, Environmental Dedication, Community Mobilization, Systematic Analysis",
            "tools": "QGIS, ArcGIS, Total Station, Soil Infiltrometers, Hydrological Modeling Software (HEC-HMS)",
            "certifications": "Selected through State Soil Conservation Officer Exam / UPSC Indian Forest Service",
            "experience_level": "Entry-Level to Senior",
            "career_growth": "Broad civil engineering and natural resources path progressing to Watershed Project Director, Superintending Engineer, or Director of Soil Conservation.",
            "internship_roles": "Watershed Survey Intern, Soil Testing Trainee",
            "entry_level_roles": "Soil Conservation Officer, Junior Engineer (Watershed), Hydrology Trainee",
            "average_salary": "₹4.5 - ₹12 LPA (Indicative range)",
            "salary_indicative": "Entry-Level Officer (0-2 yrs): ₹4 - 6.5 LPA | Senior Watershed Specialist (3-6 yrs): ₹8 - 15 LPA | Director of Soil & Water (7+ yrs): ₹18 - 38+ LPA. Indicative figures from Central Soil and Water Conservation Research Institute 2024.",
            "future_scope": "Paramount national priority driven by groundwater depletion, climate change droughts, and the Jal Shakti Abhiyan watershed mission.",
            "government_opportunities": "State Watershed Development Departments, Ministry of Jal Shakti, Central Ground Water Board (CGWB), ICAR-IISWC.",
            "private_opportunities": "Water EPC firms (Jain Irrigation, Netafim), corporate CSR watershed foundations (ITC Mission Sunehra Kal, Tata Trusts).",
            "higher_study_options": "M.Tech in Soil & Water Conservation Engineering / Water Resources.",
            "entrepreneurship_options": "Watershed surveying consultancy, rainwater harvesting contracting firm, drip irrigation dealership.",
            "source": "ICAR-Indian Institute of Soil and Water Conservation (IISWC) / Ministry of Jal Shakti",
            "official_url": "https://www.cswcrtiweb.org",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 7, "type": "DIRECT"}, {"course_id": 12, "type": "COMMON"}],
            "exams": [{"exam_id": 95, "importance": "PRIMARY"}, {"exam_id": 51, "importance": "ALTERNATIVE"}],
            "routes": [{"title": "Path A: Agri Engineering / Agriculture Route", "type": "COMMON", "steps": "B.Tech Agricultural Engineering / B.Sc Agriculture -> State Soil Conservation Officer Exam -> Appointed as Soil Conservation Officer."}],
            "ladder": [
                {"stage": "Junior Soil Conservation Officer", "exp": "0-3 Years", "desc": "Surveys farm contours, oversees farm pond excavation, tests soil infiltration rates."},
                {"stage": "Watershed Development Specialist", "exp": "3-8 Years", "desc": "Designs multi-village watershed programs, manages check dam engineering contracts."},
                {"stage": "District Soil Conservation Officer / Project Lead", "exp": "8-15 Years", "desc": "Heads district water resources restoration, coordinates with district collector."},
                {"stage": "Director of Watershed & Soil Conservation", "exp": "15+ Years", "desc": "Directs statewide watershed policy, groundwater recharge mandates, and flood mitigation."}
            ],
            "roadmaps": {
                "Class 10": "Focus on geography, water cycle, and environmental conservation.",
                "Class 12": "Choose Science (PCM or PCB) for board exams.",
                "Graduation": "Complete B.Tech in Agricultural Engineering or Civil Engineering, or B.Sc Agriculture with focus on hydrology and GIS.",
                "Working Professional": "Master GIS satellite mapping (QGIS) and prepare for state soil conservation and water resource engineering recruitments."
            }
        },
        {
            "title": "Dairy Technologist",
            "short_name": "Dairy Technologist",
            "slug": "dairy-technologist",
            "category": "Agriculture, Food Technology & Environment",
            "sub_category": "Dairy Science & Food Processing",
            "industry": "Dairy Industry & FMCG",
            "icon": "cup-straw",
            "short_description": "Manages industrial milk processing, quality assurance, and manufacturing of dairy products like cheese, butter, and infant formulas.",
            "description": "Dairy Technologists oversee the industrial transformation of raw milk into hygienic, nutritious consumer dairy products. They supervise pasteurization, spray-drying of milk powders, fermentation of yogurt and cheese, and cold-chain distribution logistics.",
            "what_they_do": "They analyze milk composition (fat, SNF, adulterants), calibrate industrial pasteurizers and homogenizers, formulate dairy products, enforce microbiological safety standards, and manage high-volume dairy processing plants.",
            "day_to_day_work": "• Testing incoming raw milk tankers for fat, SNF, and chemical adulterants.\n• Operating automated milk processing lines (pasteurizers, separators, homogenizers).\n• Supervising clean-in-place (CIP) sterilization cycles of stainless steel tanks.\n• Formulating specialized dairy foods (probiotics, infant nutrition, ice creams).\n• Managing plant cold-chain dispatch maintaining temperature below 4°C.",
            "work_environment": "Industrial dairy processing plants, milk testing laboratories, cheese manufacturing plants.",
            "work_modes": "On-site / Plant Floor & Lab / Shift Rotations",
            "minimum_qualification": "Undergraduate (B.Tech Dairy Technology / B.Sc Dairy Science)",
            "preferred_streams": "Science (PCM / PCB)",
            "required_subjects": "Chemistry, Physics, Mathematics / Biology",
            "technical_skills": "Dairy Chemistry, Dairy Microbiology, Dairy Plant Engineering, Quality Assurance (FSSAI/HACCP), Pasteurization, Spray Drying, CIP Protocols",
            "soft_skills": "Hygienic Rigor, Shop Floor Leadership, Operational Discipline, Attention to Detail",
            "tools": "MilkoTesters, Lactometers, Pasteurizer Control Panels, Milk Autoclaves, Spectrophotometers",
            "certifications": "Selected through National Dairy Research Institute (NDRI) Entrance / State Dairy Federation Exams",
            "experience_level": "Entry-Level to Senior",
            "career_growth": "Direct progression to Plant Quality Manager, Dairy Plant Head, or General Manager of Dairy Cooperative Federation.",
            "internship_roles": "Dairy Plant In-Plant Training (Integrated in B.Tech Dairy Tech - 6 Months)",
            "entry_level_roles": "Technical Officer, Dairy Processing Trainee, Quality Control Assistant",
            "average_salary": "₹4.5 - ₹12 LPA (Indicative range)",
            "salary_indicative": "Technical Officer (0-2 yrs): ₹4 - 6 LPA | Dairy Plant Manager (3-6 yrs): ₹8 - 15 LPA | General Manager / Dairy Plant Head (7+ yrs): ₹18 - 38+ LPA. Indicative figures from NDRI & Indian Dairy Association 2024.",
            "future_scope": "Massive continuous growth supported by India being the world's largest milk producer with thriving cooperative federations (Amul, Mother Dairy, Nandini).",
            "government_opportunities": "National Dairy Development Board (NDDB), ICAR-National Dairy Research Institute (NDRI), State Dairy Cooperative Federations.",
            "private_opportunities": "Amul (GCMMF), Mother Dairy, Nestlé India, Britannia, Danone, Heritage Foods, Hatsun Agro.",
            "higher_study_options": "M.Tech in Dairy Technology / Dairy Chemistry (NDRI Karnal), MBA in Agri-Business Management.",
            "entrepreneurship_options": "Commercial artisanal cheese dairy, organic A2 milk dairy farm, specialized dairy dessert manufacturing.",
            "source": "Indian Dairy Association (IDA) / ICAR-NDRI",
            "official_url": "https://www.ndri.res.in",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 7, "type": "COMMON"}, {"course_id": 6, "type": "ALTERNATIVE"}],
            "exams": [{"exam_id": 95, "importance": "PRIMARY"}],
            "routes": [{"title": "Path A: ICAR AIEEA to B.Tech Dairy Technology Route", "type": "COMMON", "steps": "Class 12 (PCM) -> ICAR AIEEA-UG -> B.Tech Dairy Technology at ICAR-NDRI Karnal or State Dairy Colleges (4 yrs) -> Campus hire at Amul / Nestlé / Mother Dairy."}],
            "ladder": [
                {"stage": "Technical Officer / Shift Incharge", "exp": "0-2 Years", "desc": "Monitors pasteurizer operations, tests milk batches, manages clean-in-place sanitation."},
                {"stage": "Quality Assurance Manager / Production Manager", "exp": "2-5 Years", "desc": "Oversees full dairy manufacturing line (butter, milk, powder), manages FSSAI audits."},
                {"stage": "Dairy Plant Head", "exp": "5-9 Years", "desc": "Directs 5 lakh+ liters/day processing plant, manages thousands of cooperative milk routes."},
                {"stage": "Managing Director / CEO of Dairy Federation", "exp": "9+ Years", "desc": "Directs statewide milk union operations, sets farmer procurement milk prices."}
            ],
            "roadmaps": {
                "Class 10": "Focus on chemistry, microbiology, and physics.",
                "Class 12": "Score high in Physics, Chemistry, and Mathematics (PCM is standard eligibility for B.Tech Dairy Tech).",
                "Graduation": "Complete B.Tech Dairy Technology at premier institutes like ICAR-NDRI Karnal. Complete intensive plant training.",
                "Working Professional": "Master automated PLC-SCADA dairy processing systems and FSSAI ISO 22000 food safety certifications."
            }
        },

        # --- AVIATION (3 careers) ---
        {
            "title": "Freight & Warehouse Logistics Planner",
            "short_name": "Logistics Planner",
            "slug": "freight-warehouse-logistics-planner",
            "category": "Aviation, Logistics & Supply Chain",
            "sub_category": "Freight Forwarding, Warehousing & Multimodal Logistics",
            "industry": "Logistics, Warehousing & Freight",
            "icon": "box-seam",
            "short_description": "Plans international multimodal freight movements, optimizes warehouse storage layouts, and manages customs clearance pipelines.",
            "description": "Freight and Logistics Planners direct the global movement of containerized freight across maritime ships, cargo aircraft, freight trains, and highway trucks. They negotiate shipping line freight rates, manage warehouse layout storage, and coordinate customs clearance.",
            "what_they_do": "They calculate shipping cargo space, coordinate ocean and air freight bookings with shipping lines, manage Warehouse Management Systems (WMS), file Bills of Lading, and track container delivery milestones.",
            "day_to_day_work": "• Booking container freight slots with ocean carriers and air cargo airlines.\n• Optimizing warehouse pallet racking and inventory slotting in WMS software.\n• Coordinating with customs house agents (CHAs) on export-import duty clearance.\n• Tracking multimodal container GPS locations and managing port demurrage risks.\n• Negotiating freight contract rates with trucking logistics operators.",
            "work_environment": "Inland container depots (ICDs), seaport freight stations, logistics hub headquarters.",
            "work_modes": "Hybrid / Logistics Hub / Office",
            "minimum_qualification": "Undergraduate (Any Stream)",
            "preferred_streams": "Commerce / Management / Engineering",
            "required_subjects": "Logistics, Business Studies, Mathematics",
            "technical_skills": "Multimodal Freight Planning, Warehouse Management Systems (WMS), Incoterms 2020, Customs Clearance, Bill of Lading, Container Optimization",
            "soft_skills": "Problem Solving Under Time Pressure, Carrier Negotiation, Multitasking, Coordination",
            "tools": "WMS Software (Manhattan, Blue Yonder), SAP Logistics, CargoWise, Excel (Advanced)",
            "certifications": "FIATA Diploma in Freight Forwarding, Certified Logistics Associate (CLA)",
            "experience_level": "Entry-Level to Senior",
            "career_growth": "Direct progression to Freight Operations Manager, Regional Logistics Director, or Head of Global Freight.",
            "internship_roles": "Logistics Operations Intern, Freight Forwarding Trainee",
            "entry_level_roles": "Logistics Coordinator, Freight Forwarder, Warehouse Supervisor",
            "average_salary": "₹4.5 - ₹12 LPA (Indicative range)",
            "salary_indicative": "Logistics Coordinator (0-2 yrs): ₹3.8 - 6 LPA | Freight Operations Manager (3-6 yrs): ₹8 - 15 LPA | Head of Multimodal Logistics (7+ yrs): ₹18 - 38+ LPA. Indicative figures from Logistics Sector Skill Council 2024.",
            "future_scope": "Explosive national growth driven by India's National Logistics Policy, Dedicated Freight Corridors (DFC), and inland dry ports.",
            "government_opportunities": "Container Corporation of India (CONCOR), Central Warehousing Corporation (CWC), Port Trusts.",
            "private_opportunities": "Maersk India, DHL Global Forwarding, Kuehne+Nagel, Delhivery, Allcargo Logistics, DP World.",
            "higher_study_options": "MBA in Logistics & Supply Chain Management, IATA Cargo Agent Diplomas.",
            "entrepreneurship_options": "Licensed freight forwarding agency, customs brokerage firm, specialized e-commerce fulfillment warehouse.",
            "source": "Logistics Sector Skill Council (LSC) / FIATA",
            "official_url": "https://lsc-india.com",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 17, "type": "COMMON"}, {"course_id": 16, "type": "COMMON"}, {"course_id": 18, "type": "SPECIALIZED"}],
            "exams": [{"exam_id": 77, "importance": "ALTERNATIVE"}],
            "routes": [{"title": "Path A: Degree + Logistics Certification Route", "type": "COMMON", "steps": "B.Com / BBA / B.Tech -> FIATA / IATA Freight Forwarding certification -> Freight Operations Coordinator."}],
            "ladder": [
                {"stage": "Logistics Coordinator", "exp": "0-2 Years", "desc": "Coordinates container bookings, prepares shipping bills, tracks truck dispatches."},
                {"stage": "Freight / Warehouse Manager", "exp": "2-5 Years", "desc": "Manages 200,000+ sq ft warehouse distribution center, negotiates carrier contracts."},
                {"stage": "Head of Multimodal Logistics", "exp": "5-8 Years", "desc": "Directs nationwide road, rail, and port logistics, reduces transit times by 20%."},
                {"stage": "Director of Global Logistics", "exp": "8+ Years", "desc": "Heads international ocean/air shipping logistics across worldwide trade lanes."}
            ],
            "roadmaps": {
                "Class 10": "Focus on geography, trade routes, arithmetic, and world maps.",
                "Class 12": "Choose Commerce or Science for Class 12 board exams.",
                "Graduation": "Complete BBA, B.Com, or B.Tech with focus on logistics and supply chain. Learn Incoterms and customs documentation.",
                "Working Professional": "Master CargoWise / SAP logistics software and earn the FIATA international freight forwarding diploma."
            }
        },

        # --- DESIGN (4 careers) ---
        {
            "title": "Game Designer & Developer",
            "short_name": "Game Designer",
            "slug": "game-designer-developer",
            "category": "Design, Animation & Creative Arts",
            "sub_category": "Interactive Entertainment & Game Systems",
            "industry": "Video Games & Interactive Media",
            "icon": "controller",
            "short_description": "Designs game mechanics, interactive storylines, character progression systems, and programs playable video games.",
            "description": "Game Designers craft the core rules, mechanics, level designs, balance systems, and interactive experiences of video games. They collaborate with 3D artists, game programmers, and audio engineers to build captivating games across PC, console, and mobile platforms.",
            "what_they_do": "They write Game Design Documents (GDD), prototype gameplay mechanics in Unity or Unreal Engine, balance difficulty curves, design virtual economies, and script interactive quests.",
            "day_to_day_work": "• Writing Game Design Documents (GDD) specifying player abilities, combat systems, and physics.\n• Prototyping gameplay mechanics in Unity (C#) or Unreal Engine (Blueprints / C++).\n• Designing 3D level layouts and placing interactive environmental triggers.\n• Playtesting game builds, gathering player telemetry, and tuning difficulty balance.\n• Collaborating with 3D artists, animators, and sound designers on asset integration.",
            "work_environment": "Game development studios, indie game teams, interactive media labs, or remote.",
            "work_modes": "Remote / Hybrid / Game Studio",
            "minimum_qualification": "Undergraduate (B.Tech CS / B.Sc Game Design / Any Degree + Playable Portfolio)",
            "preferred_streams": "Science (PCM) / Any with CS or Design",
            "required_subjects": "Computer Science, Mathematics, Design",
            "technical_skills": "Game Mechanics Design, Unity Engine (C#), Unreal Engine (C++/Blueprints), Level Design, Game Balancing, Physics Engines, Git",
            "soft_skills": "Player Empathy, Creative Imagination, Iterative Prototyping, Systems Thinking",
            "tools": "Unity, Unreal Engine 5, Visual Studio, Blender, Jira, Miro",
            "certifications": "Unity Certified Associate / Professional, Unreal Engine Certification",
            "experience_level": "Entry-Level to Senior",
            "career_growth": "Broad, exciting career path progressing to Lead Game Designer, Creative Game Director, or Studio Head.",
            "internship_roles": "Game Design Intern, Unity Developer Intern, Level Design Trainee",
            "entry_level_roles": "Junior Game Designer, Associate Game Programmer, Level Designer",
            "average_salary": "₹4.5 - ₹15 LPA (Indicative range)",
            "salary_indicative": "Entry-Level Designer (0-2 yrs): ₹4 - 6.5 LPA | Senior Game Designer (3-6 yrs): ₹8 - 18 LPA | Creative Game Director (7+ yrs): ₹20 - 45+ LPA. Indicative figures from India Game Developer Conference (IGDC) 2024.",
            "future_scope": "Explosive growth as India becomes a global gaming superpower, driven by 500M+ mobile gamers, AAA game studios, and esports.",
            "government_opportunities": "Animation, Visual Effects, Gaming and Comics (AVGC) Task Force National Initiatives, CDAC.",
            "private_opportunities": "Ubisoft India, Rockstar Games India, Electronic Arts (EA India), Nazara Technologies, Dream11, Krafton India, indie game studios.",
            "higher_study_options": "M.Des in Game Design (NID), M.S. in Computer Science (Game Technology).",
            "entrepreneurship_options": "Indie video game studio, mobile casual game publisher, gamification agency for enterprises.",
            "source": "India Game Developer Conference (IGDC) / MESC",
            "official_url": "https://indiagdc.com",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 9, "type": "COMMON"}, {"course_id": 14, "type": "COMMON"}, {"course_id": 33, "type": "DIRECT"}],
            "exams": [{"exam_id": 8, "importance": "PRIMARY"}, {"exam_id": 84, "importance": "ALTERNATIVE"}],
            "routes": [{"title": "Path A: Computer Science / Game Design Degree to Studio", "type": "COMMON", "steps": "B.Tech CSE / B.Des -> Learn Unity & C# -> Build and publish 2 playable games on Steam / itch.io -> Game Studio Portfolio hire."}],
            "ladder": [
                {"stage": "Junior Game Designer / Level Designer", "exp": "0-2 Years", "desc": "Blocks out 3D level greyboxes, scripts basic puzzle triggers, tunes enemy spawn values."},
                {"stage": "Game Designer", "exp": "2-5 Years", "desc": "Designs core combat loop, balances in-game economy, writes complete GDD specifications."},
                {"stage": "Lead Game Designer", "exp": "5-8 Years", "desc": "Oversees gameplay systems across entire AAA or mobile game title, directs design team."},
                {"stage": "Creative Director / Studio Head", "exp": "8+ Years", "desc": "Sets game vision, pitches to global publishers, directs multi-million dollar game franchise."}
            ],
            "roadmaps": {
                "Class 10": "Analyze what makes your favorite games fun, challenging, and rewarding to play.",
                "Class 12": "Learn C# or Python, understand 3D vectors, and experiment with building small 2D games.",
                "Graduation": "Learn Unity or Unreal Engine 5. Build and deploy at least 2 complete playable games on itch.io or Google Play.",
                "Working Professional": "Master systemic game design, monetization ethics, and multiplayer networking architectures."
            }
        },
        {
            "title": "Industrial & Ergonomic Product Designer",
            "short_name": "Industrial Designer",
            "slug": "industrial-product-designer",
            "category": "Design, Animation & Creative Arts",
            "sub_category": "Industrial, Physical Product & Ergonomic Design",
            "industry": "Consumer Electronics, Automotive & Hardware",
            "icon": "box",
            "short_description": "Designs the form, ergonomics, physical aesthetics, and human usability of manufactured consumer hardware and machinery.",
            "description": "Industrial Designers shape physical consumer products: smartphones, smart home appliances, electric vehicles, medical hardware, ergonomic office furniture, and power tools. They blend aesthetic styling with manufacturing engineering and user ergonomics.",
            "what_they_do": "They sketch physical concepts, model parametric 3D CAD surfaces in Rhino or SolidWorks, create physical 3D-printed foam prototypes, conduct ergonomic anthropometric testing, and coordinate manufacturing tooling with plastic injection molders.",
            "day_to_day_work": "• Sketching form concepts and ideating physical product silhouettes on digital tablets.\n• Building complex Class-A surface 3D CAD models in Rhinoceros or SolidWorks.\n• 3D-printing rapid prototypes and testing grip comfort and tactile feel.\n• Selecting materials, colors, and surface finishes (CMF - Color, Material, Finish).\n• Collaborating with mechanical and tooling engineers on injection molding feasibility.",
            "work_environment": "Industrial design studios, consumer tech hardware labs, automotive styling centers.",
            "work_modes": "On-site / Design Studio & Workshop / Rapid Prototyping Lab",
            "minimum_qualification": "Undergraduate (B.Des Industrial / Product Design - NID / IIT)",
            "preferred_streams": "Any Stream (Science / Engineering background advantageous)",
            "required_subjects": "Design, Mathematics, Physics",
            "technical_skills": "Concept Sketching, 3D CAD (Rhino, SolidWorks), Ergonomics / Anthropometry, Rapid Prototyping (3D Printing), CMF Design, Injection Molding Principles",
            "soft_skills": "Visual Refinement, Form Sensitivity, Empathy for Human Touch, Practical Engineering Sense",
            "tools": "Rhinoceros 3D, SolidWorks, KeyShot (Rendering), Wacom Tablet, 3D Printers, CNC Mills",
            "certifications": "B.Des / M.Des from NID or IIT Industrial Design Centre (IDC)",
            "experience_level": "Entry-Level to Senior",
            "career_growth": "Prestigious international career progressing to Lead Industrial Designer, VP of Hardware Design, or Chief Design Officer (CDO).",
            "internship_roles": "Industrial Design Intern, CMF Trainee, Model Shop Intern",
            "entry_level_roles": "Junior Industrial Designer, Hardware Product Designer, CAD Surface Modeler",
            "average_salary": "₹5 - ₹16 LPA (Indicative range)",
            "salary_indicative": "Junior Designer (0-2 yrs): ₹4.5 - 7 LPA | Senior Industrial Designer (3-6 yrs): ₹9 - 18 LPA | Head of Hardware Design (7+ yrs): ₹22 - 45+ LPA. Indicative figures from NID & Hardware Tech Audits 2024.",
            "future_scope": "Surging national demand powered by India's electronics hardware manufacturing revolution (Make in India, smart home IoT, EV styling).",
            "government_opportunities": "National Institute of Design (NID), Defence Research and Development Organisation (DEBEL ergonomics), IIT Tech Parks.",
            "private_opportunities": "Tata Elxsi, Titan Company, Havells, Godrej, Ather Energy, Boat, Samsung Design Delhi, top global hardware studios.",
            "higher_study_options": "M.Des in Industrial Design (NID Ahmedabad, IDC IIT Bombay), Royal College of Art (RCA London).",
            "entrepreneurship_options": "Boutique industrial design studio, consumer hardware hardware brand, sustainable lifestyle product company.",
            "source": "National Institute of Design (NID) / India Design Council",
            "official_url": "https://www.nid.edu",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 33, "type": "DIRECT"}, {"course_id": 11, "type": "COMMON"}],
            "exams": [{"exam_id": 84, "importance": "PRIMARY"}, {"exam_id": 85, "importance": "PRIMARY"}],
            "routes": [{"title": "Path A: NID / IIT UCEED Industrial Design Route", "type": "COMMON", "steps": "Class 12 -> UCEED / NID DAT -> B.Des in Industrial / Product Design (4 yrs) -> Hands-on Model Workshop Portfolio -> Consumer Hardware Designer."}],
            "ladder": [
                {"stage": "Junior Industrial Designer", "exp": "0-2 Years", "desc": "Sketches form variants, builds 3D CAD models in Rhino, preps KeyShot photorealistic renders."},
                {"stage": "Industrial Designer", "exp": "2-5 Years", "desc": "Owns physical product styling from concept to factory tooling, specifies CMF materials."},
                {"stage": "Senior Design Lead", "exp": "5-8 Years", "desc": "Directs design language for entire product lines (e.g. smart wearables, EV scooters)."},
                {"stage": "Chief Design Officer / Head of Industrial Design", "exp": "8+ Years", "desc": "Defines corporate physical design identity, wins Red Dot and iF International Design Awards."}
            ],
            "roadmaps": {
                "Class 10": "Practice sketching everyday physical objects in 3D perspective and understand materials (plastics, metals, glass).",
                "Class 12": "Prepare for UCEED (IITs) and NID DAT entrance exams. Build spatial visualization ability.",
                "Graduation": "Complete B.Des in Industrial Design. Master Rhinoceros 3D, SolidWorks, and KeyShot rendering with physical prototypes.",
                "Working Professional": "Specialize in sustainable circular materials, user ergonomics, and manufacturing tooling tolerances."
            }
        },

        # --- EDUCATION (Remaining) ---
        {
            "title": "Postgraduate Teacher (PGT)",
            "short_name": "PGT Teacher",
            "slug": "postgraduate-teacher-pgt",
            "category": "Education, Teaching & Academia",
            "sub_category": "Senior Secondary School Education",
            "industry": "School Education & Coaching",
            "icon": "book",
            "short_description": "Teaches senior secondary students (Classes 11 & 12) in specialized disciplines like Physics, Chemistry, Mathematics, Accountancy, or History.",
            "description": "Postgraduate Teachers (PGT) educate high school students in Classes 11 and 12. They master deep subject specialization, guide students through rigorous board examinations (CBSE/ICSE), and mentor them for national competitive entrance exams.",
            "what_they_do": "They deliver advanced subject lectures, conduct laboratory practical experiments in science labs, evaluate senior secondary board answer scripts, and prepare students for competitive examinations like JEE, NEET, and CUET.",
            "day_to_day_work": "• Delivering advanced subject lectures to Class 11 and 12 students.\n• Conducting physics, chemistry, biology, or computer science lab practicals.\n• Designing rigorous sample papers, pre-board exams, and grading student papers.\n• Providing targeted remedial mentorship to students struggling with board curricula.\n• Guiding students on university entrance examination preparation.",
            "work_environment": "Senior secondary schools, junior colleges, senior academic classrooms.",
            "work_modes": "On-site / School Working Hours",
            "minimum_qualification": "Postgraduate (Master's in Subject 50%+) + B.Ed Degree",
            "preferred_streams": "Relevant Academic Stream",
            "required_subjects": "Master's degree in teaching subject (Physics, Chemistry, Maths, History, etc.) + B.Ed",
            "technical_skills": "Advanced Subject Mastery, Board Exam Pedagogy, Senior Secondary Laboratory Instruction, Assessment Rubrics, Remedial Teaching",
            "soft_skills": "Inspiring Mentorship, Patience, Intellectual Passion, Clear Communication",
            "tools": "Science Laboratories, Digital Smartboards, Board Exam Question Banks",
            "certifications": "Selected through KVS PGT / NVS PGT / DSSSB PGT Recruitment Examinations",
            "experience_level": "PGT to Vice Principal / Principal",
            "career_growth": "Prestigious academic trajectory progressing to Vice Principal, Principal, or National Textbook Committee Member.",
            "internship_roles": "Senior Secondary Teaching Internship (Integrated in B.Ed)",
            "entry_level_roles": "Postgraduate Teacher (PGT), Senior School Faculty",
            "average_salary": "₹6 - ₹12 LPA (Official Central Government Pay Level 8 Basic ₹47,600/mo + DA + HRA + Benefits)",
            "salary_indicative": "PGT (Government KVS/NVS Pay Level 8): Basic ₹47,600 + DA (50%+) + HRA = ~₹75,000 - ₹90,000/month gross. Leading private schools and entrance coaching academies pay ₹8 - 25+ LPA for star teachers.",
            "future_scope": "Continuous strong demand as high school board performance and entrance exam preparation remain paramount for Indian families.",
            "government_opportunities": "Kendriya Vidyalaya Sangathan (KVS PGT), Navodaya Vidyalaya Samiti (NVS PGT), DSSSB PGT, State Model Inter Colleges.",
            "private_opportunities": "Delhi Public School, The Heritage School, DAV Public Schools, leading competitive entrance coaching institutes (Allen, Aakash).",
            "higher_study_options": "M.Ed, Ph.D. in Subject / Education, In-Service Academic Fellowships.",
            "entrepreneurship_options": "Specialized coaching institute, digital education YouTube academy, board exam preparatory publications.",
            "source": "Kendriya Vidyalaya Sangathan (KVS) / CBSE / NCTE",
            "official_url": "https://kvsangathan.nic.in",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 48, "type": "DIRECT"}, {"course_id": 34, "type": "COMMON"}, {"course_id": 35, "type": "COMMON"}, {"course_id": 36, "type": "COMMON"}, {"course_id": 24, "type": "COMMON"}],
            "exams": [{"exam_id": 32, "importance": "PRIMARY"}, {"exam_id": 26, "importance": "PRIMARY"}],
            "routes": [{"title": "Path A: Master's Degree + B.Ed to PGT", "type": "COMMON", "steps": "Bachelor's -> Master's degree in teaching subject (M.Sc / M.A. / M.Com 50%+) -> B.Ed Degree (2 yrs) -> Clear KVS / NVS / DSSSB PGT Examination -> Appointed as PGT."}],
            "ladder": [
                {"stage": "Postgraduate Teacher (PGT)", "exp": "0-6 Years", "desc": "Teaches classes 11 & 12, conducts board practicals, guides university entrance prep."},
                {"stage": "Senior PGT / Academic Coordinator", "exp": "6-12 Years", "desc": "Coordinates senior school academic syllabus, oversees pre-board examination setting."},
                {"stage": "Vice Principal", "exp": "12-18 Years", "desc": "Manages senior school administration, teacher performance appraisals, board affiliations."},
                {"stage": "School Principal / Regional Education Commissioner", "exp": "18+ Years", "desc": "Directs complete educational institution and shapes CBSE educational curriculum."}
            ],
            "roadmaps": {
                "Class 10": "Develop passion for deep subject understanding rather than rote memorization.",
                "Class 12": "Score top marks in Class 12 in the subject you wish to master.",
                "Graduation": "Complete Bachelor's and Master's degree (M.Sc / M.A. / M.Com) in your chosen discipline with at least 50% marks. Complete a 2-year B.Ed program.",
                "Working Professional": "Prepare for national KVS/NVS PGT examinations focusing on your specialized subject, teaching methodology, and general reasoning."
            }
        },

        # --- HEALTHCARE (Remaining 1) ---
        {
            "title": "Speech-Language Pathologist & Audiologist",
            "short_name": "Audiologist / Speech Pathologist",
            "slug": "audiologist-speech-pathologist",
            "category": "Healthcare & Medical Sciences",
            "sub_category": "Allied Health Sciences & Communication Disorders",
            "industry": "Healthcare & Hearing Sciences",
            "icon": "soundwave",
            "short_description": "Diagnoses and treats speech, language, voice, fluency, and hearing disorders across children and adults.",
            "description": "Audiologists and Speech-Language Pathologists assess hearing loss, fit advanced hearing aids and cochlear implants, and treat speech impediments (stuttering, aphasia, articulation disorders, and swallowing difficulties after stroke).",
            "what_they_do": "They perform pure-tone audiometry, program digital hearing aids and cochlear implants, deliver speech therapy for stuttering and speech delays, and rehabilitate stroke patients suffering from aphasia.",
            "day_to_day_work": "• Conducting diagnostic audiometry tests inside soundproof booths.\n• Programming and tuning digital hearing aids and cochlear implant processors.\n• Conducting speech therapy sessions for children with articulation delays and autism.\n• Rehabilitating swallowing disorders (dysphagia) in hospital ICU stroke patients.\n• Educating families on communication strategies and assistive auditory devices.",
            "work_environment": "ENT hospitals, hearing and speech clinics, rehabilitation centers, cochlear implant clinics.",
            "work_modes": "On-site / Clinical",
            "minimum_qualification": "Undergraduate (BASLP - Bachelor of Audiology & Speech-Language Pathology)",
            "preferred_streams": "Science (PCB / PCM)",
            "required_subjects": "Physics, Chemistry, Biology / Mathematics",
            "technical_skills": "Pure-Tone Audiometry, Speech Therapy, Cochlear Implant Programming, Hearing Aid Fitting, Dysphagia Rehabilitation, Acoustic Analysis",
            "soft_skills": "Patience, Deep Compassion, Attentive Listening, Encouraging Demeanor",
            "tools": "Diagnostic Audiometer, Tympanometer, Hearing Aid Fitting Software, Speech Therapy Flashcards",
            "certifications": "Rehabilitation Council of India (RCI) License as Registered Audiologist / Speech Pathologist",
            "experience_level": "Entry-Level to Senior",
            "career_growth": "Broad, specialized career progressing to Chief Audiologist, Cochlear Implant Specialist, or private hearing clinic owner.",
            "internship_roles": "Clinical Audiology & Speech Internship (1 Year Integrated in BASLP)",
            "entry_level_roles": "Junior Audiologist, Speech-Language Pathologist, Hearing Aid Specialist",
            "average_salary": "₹4 - ₹11 LPA (Indicative range)",
            "salary_indicative": "Entry-Level (0-2 yrs): ₹3.5 - 5 LPA | Senior Audiologist / Cochlear Specialist (3-6 yrs): ₹6.5 - 13 LPA | Private Clinic Owner (7+ yrs): ₹15 - 35+ LPA. Indicative figures from AIISH & RCI 2024.",
            "future_scope": "Surging demand driven by universal newborn hearing screenings, cochlear implant subsidies, and aging populations with hearing loss.",
            "government_opportunities": "All India Institute of Speech and Hearing (AIISH Mysore), AIIMS ENT, District Disability Rehabilitation Centres (DDRC).",
            "private_opportunities": "Cochlear India, Sonova (Phonak), Demant (Oticon), Apollo Hospitals, specialized hearing aid clinics.",
            "higher_study_options": "MASLP (Master of Audiology & Speech-Language Pathology), Ph.D. in Hearing and Speech Sciences.",
            "entrepreneurship_options": "Independent hearing and speech diagnostic clinic, hearing aid retail dispensing franchise.",
            "source": "All India Institute of Speech and Hearing (AIISH) / RCI",
            "official_url": "https://www.aiishmysore.in",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 6, "type": "ALTERNATIVE"}, {"course_id": 2, "type": "ALTERNATIVE"}],
            "exams": [{"exam_id": 7, "importance": "PRIMARY"}, {"exam_id": 79, "importance": "ALTERNATIVE"}],
            "routes": [{"title": "Path A: BASLP Degree to Licensed Audiologist Route", "type": "COMMON", "steps": "Class 12 (PCB/PCM) -> AIISH Entrance Exam / NEET -> BASLP Degree (3 yrs + 1 yr Internship) -> RCI Registration -> Licensed Audiologist & Speech Pathologist."}],
            "ladder": [
                {"stage": "Audiology Intern / Assistant", "exp": "0-2 Years", "desc": "Performs screening audiometry, assists with pediatric speech therapy sessions."},
                {"stage": "Speech-Language Pathologist / Audiologist", "exp": "2-5 Years", "desc": "Programs cochlear implants, conducts independent aphasia and stuttering rehabilitation."},
                {"stage": "Senior Specialist / Clinic Incharge", "exp": "5-8 Years", "desc": "Heads ENT audiology department, conducts forensic hearing loss assessments."},
                {"stage": "Director of Hearing Care / Private Clinic Owner", "exp": "8+ Years", "desc": "Owns chain of audiology diagnostic and speech therapy centers."}
            ],
            "roadmaps": {
                "Class 10": "Focus on human biology, sound physics, and empathy for people with disabilities.",
                "Class 12": "Score well in Physics, Chemistry, and Biology/Mathematics.",
                "Graduation": "Complete the 4-year BASLP program at premier institutes like AIISH Mysore, AYJNISHD Mumbai, or AIIMS.",
                "Working Professional": "Register with the Rehabilitation Council of India (RCI) and specialize in pediatric cochlear implant programming or neurogenic speech disorders."
            }
        }
    ]

print("Catalog builder part 9 ready.")
