"""
scripts/catalog_builder_part10.py
Final 34 careers bringing total national database to 135 authentic occupational pathways.
"""

def get_master_completion_batch():
    return [
        # --- BUSINESS (3) ---
        {
            "title": "Brand Manager",
            "short_name": "Brand Manager",
            "slug": "brand-manager",
            "category": "Business, Management & Consulting",
            "sub_category": "Marketing & Brand Growth",
            "industry": "FMCG & Consumer Brands",
            "icon": "award",
            "short_description": "Defines brand positioning, emotional resonance, product packaging, and long-term consumer brand equity.",
            "description": "Brand Managers own the public persona, market perception, and consumer loyalty of a commercial brand. They analyze consumer behavioral trends, guide product redesigns, manage multimillion-dollar advertising accounts, and safeguard brand equity.",
            "what_they_do": "They analyze brand health tracking metrics, brief creative advertising agencies on brand campaigns, oversee product packaging aesthetics, design product launch activations, and coordinate with distribution sales teams.",
            "day_to_day_work": "• Reviewing quarterly brand penetration and consumer recall numbers.\n• Directing advertising campaigns across digital, television, and print.\n• Redesigning product packaging for improved on-shelf visual disruption.\n• Managing brand sponsorship and celebrity endorsement partnerships.\n• Coordinating with product development teams on consumer fragrance, taste, or texture testing.",
            "work_environment": "Corporate brand headquarters, creative agency studios, consumer focus group facilities.",
            "work_modes": "Hybrid / Office / Market Research Visits",
            "minimum_qualification": "Postgraduate (MBA in Marketing)",
            "preferred_streams": "Commerce / Humanities / Management",
            "required_subjects": "Marketing, Brand Strategy, Consumer Psychology",
            "technical_skills": "Brand Equity Measurement, Consumer Insights, Positioning Frameworks, Media Planning, P&L Ownership, Kantar/Nielsen Analytics",
            "soft_skills": "Creative Intuition, Persuasive Presentation, Commercial Acumen, Empathy",
            "tools": "Kantar BrandZ, Nielsen Scantrack, PowerPoint, Google Analytics, Excel",
            "certifications": "MBA in Marketing from premier business schools",
            "experience_level": "Assistant Brand Manager to Chief Brand Officer",
            "career_growth": "Direct executive progression to Category Director, Marketing Vice President, or Managing Director.",
            "internship_roles": "Brand Management Intern, FMCG Marketing Summer Trainee",
            "entry_level_roles": "Assistant Brand Manager, Brand Executive",
            "average_salary": "₹8 - ₹20 LPA (Indicative range)",
            "salary_indicative": "Assistant Brand Manager (0-2 yrs): ₹7 - 12 LPA | Brand Manager (3-6 yrs): ₹14 - 24 LPA | Brand Director / CMO (7+ yrs): ₹30 - 75+ LPA. Indicative figures from Top B-School FMCG Placement Audits 2024.",
            "future_scope": "Essential corporate leadership role across consumer goods, personal care, retail, and tech consumer brands.",
            "government_opportunities": "State Tourism Brand Cells, Khadi & Village Industries Commission (KVIC), Coffee/Tea Boards of India.",
            "private_opportunities": "Hindustan Unilever, ITC, Nestlé, Marico, Tata Consumer Products, Britannia, L'Oréal India.",
            "higher_study_options": "Executive Leadership at Harvard / INSEAD, Master's in Strategic Brand Design.",
            "entrepreneurship_options": "Founding an independent D2C consumer brand, boutique brand strategy consultancy.",
            "source": "Advertising Standards Council of India (ASCI) / Top B-School Placement Audits",
            "official_url": "https://www.ascionline.in",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 18, "type": "DIRECT"}, {"course_id": 17, "type": "COMMON"}],
            "exams": [{"exam_id": 77, "importance": "PRIMARY"}],
            "routes": [{"title": "Path A: Top Tier MBA Route", "type": "COMMON", "steps": "Graduation -> CAT 99%+ -> Top IIM / FMS / XLRI -> FMCG Campus Placement -> Assistant Brand Manager."}],
            "ladder": [
                {"stage": "Assistant Brand Manager", "exp": "0-2 Years", "desc": "Manages packaging updates, tracks market share, audits digital ad creative."},
                {"stage": "Brand Manager", "exp": "2-5 Years", "desc": "Owns total brand P&L, launches new product variants, leads national commercial campaigns."},
                {"stage": "Senior Brand / Category Director", "exp": "5-8 Years", "desc": "Directs multiple brand portfolios, manages hundreds of crores of media spend."},
                {"stage": "Chief Brand Officer (CBO) / CMO", "exp": "8+ Years", "desc": "Defines enterprise brand strategy and global market positioning."}
            ],
            "roadmaps": {
                "Class 10": "Analyze your favorite brands and understand why you prefer them.",
                "Class 12": "Choose Commerce or Humanities with English and Business Studies.",
                "Graduation": "Complete BBA, B.Com, or any degree. Prepare for CAT/XAT for top marketing schools.",
                "Working Professional": "Master consumer insights, quantitative market testing, and full-funnel digital brand building."
            }
        },
        {
            "title": "Business Development Manager",
            "short_name": "BD Manager",
            "slug": "business-development-manager",
            "category": "Business, Management & Consulting",
            "sub_category": "Enterprise Sales & Strategic Partnerships",
            "industry": "B2B Technology & Corporate Services",
            "icon": "graph-up-arrow",
            "short_description": "Identifies high-value B2B commercial opportunities, structures enterprise partnerships, and drives corporate revenue growth.",
            "description": "Business Development Managers drive top-line revenue for corporations. They prospect enterprise clients, build executive relationships, negotiate multi-million rupee commercial contracts, and structure strategic channel distribution alliances.",
            "what_they_do": "They prospect decision-makers, deliver executive capability pitches, negotiate complex pricing and Master Services Agreements, manage enterprise sales pipelines, and cultivate key commercial partnerships.",
            "day_to_day_work": "• Prospecting and meeting C-level corporate executives for enterprise contracts.\n• Delivering tailored commercial solution pitches alongside technical architects.\n• Structuring multi-year service contracts and enterprise license agreements.\n• Managing sales pipeline forecasting in Salesforce CRM.\n• Attending national industry conferences to generate qualified commercial leads.",
            "work_environment": "Corporate regional offices, client headquarters, industry trade summits.",
            "work_modes": "Hybrid / Frequent Client Travel / Office",
            "minimum_qualification": "Undergraduate (BBA / B.Tech / B.Com / Any Degree) + MBA preferred",
            "preferred_streams": "Any Stream",
            "required_subjects": "Business Management, Marketing, Economics",
            "technical_skills": "Enterprise B2B Sales, Contract Negotiation, Pipeline Management, Solution Selling, Value Proposition Modeling, CRM Management",
            "soft_skills": "Persuasive Charisma, High Resilience, Active Listening, Executive Presence",
            "tools": "Salesforce CRM, HubSpot, LinkedIn Sales Navigator, ZoomInfo, Excel",
            "certifications": "Certified Sales Professional (CSP), Challenger Sales Training",
            "experience_level": "Entry-Level to Senior",
            "career_growth": "Lucrative career path progressing to VP of Sales, Chief Commercial Officer (CCO), or Chief Revenue Officer (CRO).",
            "internship_roles": "Business Development Intern, Enterprise Sales Trainee",
            "entry_level_roles": "Business Development Executive (BDE), Inside Sales Associate",
            "average_salary": "₹5 - ₹16 LPA (Indicative range - plus uncapped sales commission bonuses)",
            "salary_indicative": "BDE (0-2 yrs): ₹4 - 7 LPA + commissions | BD Manager (3-6 yrs): ₹10 - 20 LPA + commissions | VP Sales / CRO (7+ yrs): ₹30 - 80+ LPA. Indicative figures from B2B Tech Sales Audits 2024.",
            "future_scope": "Universal necessity across IT services, SaaS platforms, industrial equipment, and fintech enterprises.",
            "government_opportunities": "Public Sector PSU Commercial Wings (BHEL, IOCL, GAIL), Trade Promotion Councils.",
            "private_opportunities": "Salesforce India, Microsoft, Zoho, Freshworks, Razorpay, Tata Consultancy Services, high-growth B2B SaaS startups.",
            "higher_study_options": "MBA in Marketing & Sales, Executive Leadership Programs.",
            "entrepreneurship_options": "B2B sales advisory agency, corporate lead generation enterprise, distribution franchise.",
            "source": "Enterprise Sales Association / AICTE",
            "official_url": "https://www.ncs.gov.in",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 17, "type": "COMMON"}, {"course_id": 18, "type": "DIRECT"}, {"course_id": 9, "type": "COMMON"}],
            "exams": [{"exam_id": 77, "importance": "PRIMARY"}],
            "routes": [{"title": "Path A: Degree to B2B Technology Sales", "type": "COMMON", "steps": "B.Tech / BBA -> Inside Sales Associate -> Master Solution Selling -> Enterprise Business Development Manager."}],
            "ladder": [
                {"stage": "Business Development Associate", "exp": "0-2 Years", "desc": "Prospects enterprise leads, conducts discovery calls, qualifies inbound pipeline."},
                {"stage": "Enterprise BD Manager", "exp": "2-5 Years", "desc": "Closes multi-crore annual contracts, leads complex commercial contract negotiations."},
                {"stage": "Head of Enterprise Sales / Alliances", "exp": "5-8 Years", "desc": "Manages national enterprise sales team, structures channel distribution agreements."},
                {"stage": "Chief Revenue Officer (CRO)", "exp": "8+ Years", "desc": "Owns total corporate revenue engine, global sales territories, and commercial pricing."}
            ],
            "roadmaps": {
                "Class 10": "Participate in debates, school sales fests, and build active persuasion skills.",
                "Class 12": "Complete Class 12 in any stream.",
                "Graduation": "Complete BBA, B.Tech, or B.Com. Practice public speaking, professional networking, and learn CRM software.",
                "Working Professional": "Master consultative selling frameworks (Challenger Sale, MEDDIC) and enterprise contract negotiation."
            }
        },
        {
            "title": "Retail & E-Commerce Category Manager",
            "short_name": "Category Manager",
            "slug": "category-manager",
            "category": "Business, Management & Consulting",
            "sub_category": "E-Commerce & Merchandising",
            "industry": "E-Commerce & Modern Retail",
            "icon": "cart4",
            "short_description": "Owns the end-to-end profit & loss, assortment selection, pricing, and vendor ecosystem for a specific product category.",
            "description": "Category Managers operate like CEOs of their specific product category (electronics, fashion, grocery, beauty) within e-commerce giants and modern retail chains. They curate product assortments, negotiate vendor margins, and drive gross merchandise value (GMV).",
            "what_they_do": "They analyze market category trends, onboard top commercial brands and sellers, set dynamic pricing algorithms, manage promotional sales events (Big Billion Days, Great Indian Festival), and optimize category profit margins.",
            "day_to_day_work": "• Analyzing daily GMV, gross margin, customer conversion, and out-of-stock rates.\n• Negotiating procurement margins and exclusive launch deals with brand manufacturers.\n• Curating high-converting homepage banners and promotional flash deals.\n• Planning seasonal festival inventory buildups with supply chain fulfillment teams.\n• Reviewing customer product reviews and return rates to weed out defective sellers.",
            "work_environment": "Corporate e-commerce headquarters (Flipkart, Amazon, Myntra, Reliance Retail).",
            "work_modes": "Hybrid / Office",
            "minimum_qualification": "Undergraduate (BBA / B.Tech / B.Com) + Top MBA preferred",
            "preferred_streams": "Commerce / Engineering / Management",
            "required_subjects": "Marketing, Economics, Operations",
            "technical_skills": "P&L Management, Gross Merchandise Value (GMV) Optimization, Vendor Negotiation, Pricing Strategy, SQL, E-Commerce Analytics, Inventory Turn",
            "soft_skills": "High Commercial Aggression, Negotiation, Fast Decision Making, Analytical Rigor",
            "tools": "Microsoft Excel (Advanced), SQL, Power BI, Tableau, Seller Portals",
            "certifications": "MBA from top business schools (IIMs, XLRI, SPJIMR)",
            "experience_level": "Associate to Category Director",
            "career_growth": "Rapid progression to Senior Category Manager, Category Director, or VP of E-Commerce.",
            "internship_roles": "Category Management Intern, Retail Merchandising Trainee",
            "entry_level_roles": "Associate Category Manager, Assistant Buyer, Vendor Operations Associate",
            "average_salary": "₹7 - ₹18 LPA (Indicative range)",
            "salary_indicative": "Associate Category Manager (0-2 yrs): ₹6 - 10 LPA | Category Manager (3-6 yrs): ₹14 - 24 LPA | Category Director / VP (7+ yrs): ₹28 - 65+ LPA. Indicative figures from Indian E-Commerce Placement Audits 2024.",
            "future_scope": "Surging growth fueled by India's $150+ Billion e-commerce market, quick commerce (Blinkit, Zepto, Instamart), and omnichannel retail.",
            "government_opportunities": "Open Network for Digital Commerce (ONDC Initiatives), GeM (Government e-Marketplace Category Management).",
            "private_opportunities": "Amazon India, Flipkart, Myntra, Blinkit, Zepto, Nykaa, Tata CLiQ, Reliance Retail.",
            "higher_study_options": "MBA from premier institutions, Executive Retail Management Fellowships.",
            "entrepreneurship_options": "D2C retail brand, e-commerce brand aggregator, third-party marketplace seller agency.",
            "source": "Retailers Association of India (RAI) / Top B-School Audits",
            "official_url": "https://rai.net.in",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 18, "type": "DIRECT"}, {"course_id": 17, "type": "COMMON"}, {"course_id": 9, "type": "COMMON"}],
            "exams": [{"exam_id": 77, "importance": "PRIMARY"}],
            "routes": [{"title": "Path A: Top MBA to Category Manager Route", "type": "COMMON", "steps": "B.Tech / B.Com -> CAT -> Top IIM / SPJIMR -> On-campus e-commerce placement -> Category Manager."}],
            "ladder": [
                {"stage": "Associate Category Manager", "exp": "0-2 Years", "desc": "Manages brand onboarding, tracks product catalog quality, audits promotional pricing."},
                {"stage": "Category Manager", "exp": "2-5 Years", "desc": "Owns category P&L of ₹100-500 Crores, negotiates brand exclusivity, runs festival sales."},
                {"stage": "Category Director", "exp": "5-8 Years", "desc": "Heads major multi-thousand crore division (e.g. Smartphones & Consumer Electronics)."},
                {"stage": "VP - Retail / Business Head", "exp": "8+ Years", "desc": "Owns entire marketplace category portfolio and executive commercial strategy."}
            ],
            "roadmaps": {
                "Class 10": "Observe retail shopping patterns, discounts, and e-commerce apps.",
                "Class 12": "Choose Commerce or Science with Mathematics.",
                "Graduation": "Complete BBA, B.Com, or B.Tech. Master Excel, SQL, and data analytics. Prepare for CAT.",
                "Working Professional": "Learn unit economics, margin structures, and vendor contract negotiations."
            }
        },

        # --- SCIENCE (5) ---
        {
            "title": "Analytical Chemist",
            "short_name": "Analytical Chemist",
            "slug": "analytical-chemist",
            "category": "Science, Research & Mathematics",
            "sub_category": "Chemical Sciences & Laboratory Analysis",
            "industry": "Pharmaceuticals & Chemical Analysis",
            "icon": "eyedropper",
            "short_description": "Uses advanced chemical instrumentation to determine the exact composition, purity, and safety of pharmaceutical drugs and chemical substances.",
            "description": "Analytical Chemists determine what matter is and how much of it exists. They use sophisticated spectroscopic and chromatographic instruments to ensure that pharmaceuticals, food products, water supplies, and chemicals meet rigorous regulatory purity and safety standards.",
            "what_they_do": "They operate HPLC, GC-MS, and spectrophotometers, validate analytical testing methods for regulatory submissions, conduct stability studies on new drugs, and investigate chemical impurities.",
            "day_to_day_work": "• Operating HPLC and Gas Chromatography (GC) systems for drug assays.\n• Developing and validating analytical test methods adhering to ICH guidelines.\n• Testing pharmaceutical drug batches for organic and inorganic impurities.\n• Maintaining meticulous laboratory notebooks complying with Good Laboratory Practices (GLP).\n• Calibrating precision chemical instrumentation and preparing testing reagents.",
            "work_environment": "Pharmaceutical R&D laboratories, quality control (QC) labs, testing consultancies.",
            "work_modes": "On-site / Analytical Wet Lab",
            "minimum_qualification": "Postgraduate (M.Sc in Analytical Chemistry / Chemistry)",
            "preferred_streams": "Science (PCM / PCB)",
            "required_subjects": "Chemistry",
            "technical_skills": "HPLC, Gas Chromatography-Mass Spectrometry (GC-MS), Method Validation (ICH Guidelines), Spectroscopy (UV-Vis, FTIR), GLP/GMP Compliance, Titration",
            "soft_skills": "Meticulous Attention to Detail, Analytical Rigor, Integrity, Safety Focus",
            "tools": "HPLC Systems (Waters, Agilent), GC-MS, FTIR Spectrometer, Karl Fischer Titrator, Empower Software",
            "certifications": "CSIR-UGC NET JRF in Chemical Sciences, NABL Laboratory Assessor",
            "experience_level": "Entry-Level to Senior",
            "career_growth": "Direct progression to Analytical Method Development (AMD) Lead, Head of QC, or VP of Quality Operations.",
            "internship_roles": "Analytical QC Intern, Wet Chemistry Trainee",
            "entry_level_roles": "Quality Control Chemist, Analytical Chemist Trainee, Lab Analyst",
            "average_salary": "₹3.8 - ₹10 LPA (Indicative range)",
            "salary_indicative": "Entry-Level Chemist (0-2 yrs): ₹3.5 - 5 LPA | Senior Analytical Scientist (3-6 yrs): ₹6.5 - 12 LPA | Head of Quality Control (7+ yrs): ₹16 - 32+ LPA. Indicative figures from Indian Chemical Society 2024.",
            "future_scope": "Permanent, non-negotiable regulatory requirement across India's massive pharmaceutical export industry.",
            "government_opportunities": "Central Drug Testing Laboratories (CDTL), Indian Pharmacopoeia Commission (IPC), CSIR Laboratories.",
            "private_opportunities": "Sun Pharma, Dr. Reddy's Laboratories, Cipla, Lupin, Biocon, Eurofins, SGS India.",
            "higher_study_options": "Ph.D. in Analytical Chemistry, Post-Doctoral Fellowships.",
            "entrepreneurship_options": "NABL-accredited chemical testing laboratory, pharmaceutical method development consultancy.",
            "source": "Indian Chemical Society / Indian Pharmacopoeia Commission",
            "official_url": "https://ipc.gov.in",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 3, "type": "DIRECT"}, {"course_id": 36, "type": "DIRECT"}],
            "exams": [{"exam_id": 81, "importance": "PRIMARY"}, {"exam_id": 82, "importance": "PRIMARY"}],
            "routes": [{"title": "Path A: M.Sc Chemistry to Analytical Scientist", "type": "COMMON", "steps": "B.Sc Chemistry -> M.Sc Analytical Chemistry -> Hands-on HPLC training -> Pharmaceutical QC Chemist."}],
            "ladder": [
                {"stage": "QC Chemist / Analyst", "exp": "0-2 Years", "desc": "Runs routine raw material assays on HPLC, performs dissolution testing, logs data in Empower."},
                {"stage": "Analytical Method Development Scientist", "exp": "2-5 Years", "desc": "Develops new HPLC/GC test methods for novel drug molecules, compiles validation dossiers."},
                {"stage": "Senior Manager - Quality Control", "exp": "5-8 Years", "desc": "Manages 50+ lab chemists, faces US FDA and WHO regulatory plant audits."},
                {"stage": "Director of Quality Operations", "exp": "8+ Years", "desc": "Heads global pharmaceutical quality compliance across dozens of manufacturing plants."}
            ],
            "roadmaps": {
                "Class 10": "Focus on chemical formulas, reactions, and laboratory safety.",
                "Class 12": "Score top marks in Chemistry for Class 12 board exams.",
                "Graduation": "Complete B.Sc Chemistry and M.Sc Analytical Chemistry with intensive hands-on instrumentation training (HPLC, UV-Vis).",
                "Working Professional": "Master chromatography software (Empower) and US FDA 21 CFR Part 11 electronic data integrity rules."
            }
        },
        {
            "title": "Microbiologist",
            "short_name": "Microbiologist",
            "slug": "microbiologist",
            "category": "Science, Research & Mathematics",
            "sub_category": "Biological & Microbial Sciences",
            "industry": "Healthcare, Pharmaceuticals & Food Safety",
            "icon": "virus",
            "short_description": "Studies microscopic organisms including bacteria, viruses, fungi, and algae to treat infectious diseases and produce bioproducts.",
            "description": "Microbiologists explore the world of microscopic life. They investigate pathogen transmission, develop antibacterial vaccines and antibiotics, engineer beneficial microbes for industrial fermentation, and ensure sterility in hospitals and pharmaceutical manufacturing plants.",
            "what_they_do": "They isolate and culture microbial strains, conduct antibiotic susceptibility testing, identify bacterial pathogens under microscopes, test pharmaceutical water for endotoxins, and research viral mutations.",
            "day_to_day_work": "• Culturing bacterial and fungal specimens on specialized agar plates.\n• Performing Gram staining and identifying microbial colonies under oil-immersion microscopes.\n• Conducting bioburden testing and sterility testing in cleanroom isolators.\n• Testing bacterial endotoxins using Limulus Amebocyte Lysate (LAL) assays.\n• Maintaining microbial culture collections and preparing biosafety documentation.",
            "work_environment": "Hospital clinical microbiology labs, pharmaceutical sterility suites, food testing labs.",
            "work_modes": "On-site / Wet Lab / Biosafety Facilities (BSL-2 / BSL-3)",
            "minimum_qualification": "Postgraduate (M.Sc in Microbiology / Medical Microbiology)",
            "preferred_streams": "Science (PCB)",
            "required_subjects": "Biology, Chemistry, Microbiology",
            "technical_skills": "Microbial Culturing, Gram Staining, Sterility Testing, Endotoxin Testing (LAL), Antimicrobial Susceptibility, Biosafety Standards, PCR",
            "soft_skills": "Aseptic Discipline, Meticulous Observation, Patience, Safety Focus",
            "tools": "Autoclaves, Biosafety Cabinets, Incubators, Microscopes, Colony Counters",
            "certifications": "CSIR-UGC NET JRF in Life Sciences, Medical Microbiologist Registration",
            "experience_level": "Entry-Level to Senior",
            "career_growth": "Broad career path progressing to Chief Microbiologist, Sterility Assurance Manager, or Infectious Disease Research Director.",
            "internship_roles": "Microbiology Lab Intern, Sterility Assurance Trainee",
            "entry_level_roles": "Quality Control Microbiologist, Lab Microbiologist, Research Assistant",
            "average_salary": "₹3.8 - ₹10 LPA (Indicative range)",
            "salary_indicative": "Entry-Level Microbiologist (0-2 yrs): ₹3.5 - 5 LPA | Senior QC Microbiologist (3-6 yrs): ₹6.5 - 12 LPA | Head of Sterility Assurance (7+ yrs): ₹16 - 30+ LPA. Indicative figures from Association of Microbiologists of India 2024.",
            "future_scope": "High sustained demand across infectious disease surveillance, vaccine manufacturing, and pharmaceutical sterile injectables.",
            "government_opportunities": "National Institute of Virology (NIV Pune), ICMR institutes, AIIMS Hospital Microbiology, FSSAI.",
            "private_opportunities": "Serum Institute of India, Bharat Biotech, Biocon, Sun Pharma, Dr. Reddy's, pathology diagnostic chains.",
            "higher_study_options": "Ph.D. in Microbiology / Virology, Post-Doctoral Fellowships.",
            "entrepreneurship_options": "Commercial microbiological testing lab, probiotic culture production startup, bio-fertilizer enterprise.",
            "source": "Association of Microbiologists of India (AMI) / ICMR",
            "official_url": "https://amiindia.info",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 6, "type": "COMMON"}, {"course_id": 41, "type": "COMMON"}],
            "exams": [{"exam_id": 81, "importance": "PRIMARY"}, {"exam_id": 79, "importance": "ALTERNATIVE"}],
            "routes": [{"title": "Path A: M.Sc Microbiology Route", "type": "COMMON", "steps": "B.Sc Microbiology / Biotechnology -> M.Sc Microbiology -> Cleanroom Sterility Training -> Pharmaceutical QC Microbiologist."}],
            "ladder": [
                {"stage": "QC Microbiologist", "exp": "0-2 Years", "desc": "Performs environmental monitoring in cleanrooms, pours agar plates, counts colonies."},
                {"stage": "Microbiology Specialist", "exp": "2-5 Years", "desc": "Handles sterility investigations, validates autoclaves, tests water for injection (WFI)."},
                {"stage": "Sterility Assurance Manager", "exp": "5-8 Years", "desc": "Directs sterile injectable cleanroom protocols, ensures regulatory compliance with US FDA."},
                {"stage": "Director of Microbiology & Biosafety", "exp": "8+ Years", "desc": "Directs corporate infection control and vaccine quality assurance across manufacturing plants."}
            ],
            "roadmaps": {
                "Class 10": "Focus on cell biology, infectious diseases, and microscopes.",
                "Class 12": "Choose Science with Biology and Chemistry for board exams.",
                "Graduation": "Complete B.Sc in Microbiology, Botany/Zoology, or Biotechnology. Complete M.Sc in Microbiology with aseptic technique training.",
                "Working Professional": "Master sterile injectable manufacturing regulations (US FDA cGMP) and cleanroom environmental monitoring."
            }
        },
        {
            "title": "Geologist & Earth Scientist",
            "slug": "geologist-earth-scientist",
            "short_name": "Geologist",
            "category": "Science, Research & Mathematics",
            "sub_category": "Geosciences & Earth Resources",
            "industry": "Mining, Mineral Exploration & Groundwater",
            "icon": "globe",
            "short_description": "Studies earth processes, rock formations, tectonic plates, and locates underground mineral, oil, and groundwater resources.",
            "description": "Geologists examine the history, structure, and composition of planet Earth. They conduct field geological mapping, explore for mineral deposits (iron ore, copper, lithium), locate subsurface aquifers, and evaluate geological hazards (landslides, earthquakes).",
            "what_they_do": "They map rock outcrops in the field, analyze core drill samples, use GIS and remote sensing satellite data, locate mineral reserves, and advise on foundation stability for dams, tunnels, and highways.",
            "day_to_day_work": "• Conducting geological field mapping and rock sampling in remote terrains.\n• Examining rock thin-sections under polarizing petrological microscopes.\n• Logging diamond drill core samples and estimating mineral ore grades.\n• Interpreting satellite hyperspectral imagery and seismic surveys in GIS.\n• Advising civil engineers on fault lines and tunnel stability.",
            "work_environment": "Mineral exploration field sites, mining operations, geotechnical laboratories, geological survey offices.",
            "work_modes": "Field Expeditions / Remote Site Rotations / Lab",
            "minimum_qualification": "Postgraduate (M.Sc in Applied Geology / Geology)",
            "preferred_streams": "Science (PCM / PCB)",
            "required_subjects": "Geology, Physics, Chemistry, Mathematics",
            "technical_skills": "Geological Field Mapping, Petrology, Stratigraphy, Mineral Exploration, Core Logging, GIS & Remote Sensing, Hydrogeology",
            "soft_skills": "Rugged Outdoor Endurance, Keen Spatial Observation, Patience, Field Independence",
            "tools": "Geological Hammer, Clinometer Compass, Hand Lens, Polarizing Microscope, ArcGIS, GPS",
            "certifications": "Selected through UPSC Combined Geo-Scientist Examination (CGSE)",
            "experience_level": "Geologist to Director General (GSI)",
            "career_growth": "Prestige-filled sovereign career progressing to Superintending Geologist, Deputy Director General, or Director General of the Geological Survey of India.",
            "internship_roles": "Geological Field Mapping Camp (Mandatory in M.Sc Geology)",
            "entry_level_roles": "Geologist (Group A Gazetted - GSI / CGWB), Exploration Geologist, Mine Geologist",
            "average_salary": "₹7 - ₹16 LPA (Official Central Government Pay Level 10 Basic ₹56,100 + DA + Field Hardship Allowances)",
            "salary_indicative": "Geologist (Level 10): Basic ₹56,100 + DA (50%+) + HRA + Field Survey Allowances = ~₹85,000 - ₹1,00,000/month gross. Mining MNCs pay ₹8 - 25+ LPA.",
            "future_scope": "Surging national priority driven by India's Critical Minerals Mission (lithium, rare earths, cobalt exploration for energy transition).",
            "government_opportunities": "Geological Survey of India (GSI - via UPSC CGSE), Central Ground Water Board (CGWB), ONGC, Atomic Minerals Directorate (AMD).",
            "private_opportunities": "Vedanta, Tata Steel (Mining), Rio Tinto, Coal India, NMDC, geotechnical engineering firms.",
            "higher_study_options": "Ph.D. in Economic Geology / Structural Geology, Post-Doctoral Fellowships.",
            "entrepreneurship_options": "Groundwater exploration consultancy, geotechnical soil and rock testing laboratory, mining consultancy.",
            "source": "Geological Survey of India (GSI) / UPSC",
            "official_url": "https://www.gsi.gov.in",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 2, "type": "COMMON"}, {"course_id": 3, "type": "COMMON"}],
            "exams": [{"exam_id": 51, "importance": "ALTERNATIVE"}, {"exam_id": 82, "importance": "PRIMARY"}],
            "routes": [{"title": "Path A: M.Sc Geology to UPSC Combined Geo-Scientist Exam", "type": "COMMON", "steps": "B.Sc Geology -> M.Sc Applied Geology -> Clear UPSC Combined Geo-Scientist Examination -> Appointed as Geologist (Group A) in Geological Survey of India (GSI)."}],
            "ladder": [
                {"stage": "Geologist (Group A Gazetted)", "exp": "0-5 Years", "desc": "Conducts baseline geological mapping, logs diamond drill cores, maps critical mineral deposits."},
                {"stage": "Senior Geologist", "exp": "5-10 Years", "desc": "Heads mineral exploration field camps, calculates JORC-compliant ore resource estimates."},
                {"stage": "Superintending Geologist / Director", "exp": "10-18 Years", "desc": "Directs regional geological survey missions, leads marine and seismic survey expeditions."},
                {"stage": "Director General of Geological Survey of India (GSI)", "exp": "18+ Years", "desc": "Directs national earth science policy, sovereign mineral resource inventory, and international treaties."}
            ],
            "roadmaps": {
                "Class 10": "Develop love for mountains, rocks, physical geography, and outdoor exploration.",
                "Class 12": "Choose Science (PCM or PCB) for board exams.",
                "Graduation": "Complete B.Sc in Geology with extensive geological field camps. Complete M.Sc in Applied Geology from premier institutes (IIT Roorkee, IIT Kharagpur, BHU, Presidency).",
                "Working Professional": "Prepare for the prestigious UPSC Combined Geo-Scientist Examination (CGSE) for direct appointment into GSI."
            }
        },

        # --- GOVERNMENT (Remaining 2) ---
        {
            "title": "PSU Executive Engineer (GATE)",
            "short_name": "PSU Executive Engineer",
            "slug": "psu-executive-engineer",
            "category": "Government, Defence & Civil Services",
            "sub_category": "Public Sector Engineering & Energy Management",
            "industry": "Public Sector Undertakings (Maharatna / Navratna PSUs)",
            "icon": "shield",
            "short_description": "Manages core national energy, oil, power, and manufacturing infrastructure in premier Maharatna public sector corporations.",
            "description": "Executive Engineers in India's Maharatna and Navratna Public Sector Undertakings (ONGC, IOCL, NTPC, POWERGRID, BHEL, GAIL, HPCL) manage critical energy and industrial infrastructure. Selected through top GATE ranks, they direct power stations, oil refineries, and national electrical grids.",
            "what_they_do": "They manage thermal and renewable power generation plants, operate oil and gas refineries, maintain national electrical transmission substations, oversee equipment overhauls, and lead engineering teams.",
            "day_to_day_work": "• Supervising plant operations and monitoring DCS (Distributed Control System) consoles.\n• Directing preventive maintenance shutdowns for turbines, transformers, and compressors.\n• Ensuring environmental emission standards and industrial safety compliance.\n• Managing engineering vendor contracts, procurement, and inventory.\n• Coordinating with state electricity distribution companies and load dispatch centers.",
            "work_environment": "Power thermal stations, oil refineries, electrical substations, gas pipelines, corporate PSU headquarters.",
            "work_modes": "On-site / Plant Operations / Shift Incharge",
            "minimum_qualification": "Undergraduate (B.Tech / B.E. 60%+ in Mechanical / Electrical / Civil / Chemical / CS)",
            "preferred_streams": "Science (PCM)",
            "required_subjects": "Engineering discipline (Mechanical, Electrical, Civil, Chemical, Electronics)",
            "technical_skills": "Plant Operations, DCS / SCADA Systems, Industrial Safety (OSHA), Preventive Maintenance, Power Systems, Equipment Reliability",
            "soft_skills": "Operational Decisiveness, Safety Discipline, Team Leadership, Crisis Composure",
            "tools": "DCS/SCADA Control Interfaces, SAP ERP, Engineering Blueprints, Vibration Analyzers",
            "certifications": "Top Rank in Graduate Aptitude Test in Engineering (GATE)",
            "experience_level": "Executive Trainee to General Manager / Director",
            "career_growth": "Highly prestigious sovereign corporate path progressing to Plant Head, Executive Director, or Chairman & Managing Director (CMD) of Maharatna PSU.",
            "internship_roles": "PSU Graduate Apprenticeship (1 Year)",
            "entry_level_roles": "Executive Trainee (ET), Assistant Executive Engineer (AEE)",
            "average_salary": "₹12 - ₹24 LPA (Official Maharatna PSU Executive Pay Scale: E-2 Level Basic ₹50,000 - ₹1,60,000 + Perks, Housing, Medical)",
            "salary_indicative": "Executive Trainee (E-2): Basic ₹50,000 + Industrial DA (45%+) + 35% Perks + PRP (Performance Related Pay) = ~₹12 - 18 LPA CTC. Exceptional company housing township, free medical for family, and job security.",
            "future_scope": "Permanent, highly prestigious engineering career at the helm of India's multi-lakh-crore sovereign energy and infrastructure backbone.",
            "government_opportunities": "IOCL, ONGC, NTPC, POWERGRID, BHEL, GAIL, HPCL, BPCL, BARC, NPCIL (via GATE).",
            "private_opportunities": "Not applicable (Central Public Sector Enterprise).",
            "higher_study_options": "Sponsored M.Tech / MBA at IIMs/IITs under PSU executive sponsorship.",
            "entrepreneurship_options": "Not applicable (Government PSU Service).",
            "source": "Department of Public Enterprises (DPE) / GATE",
            "official_url": "https://dpe.gov.in",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 9, "type": "COMMON"}, {"course_id": 11, "type": "COMMON"}, {"course_id": 12, "type": "COMMON"}, {"course_id": 13, "type": "COMMON"}],
            "exams": [{"exam_id": 69, "importance": "PRIMARY"}],
            "routes": [{"title": "Path A: GATE Examination to Maharatna PSU Route", "type": "COMMON", "steps": "B.Tech in Engineering (60%+) -> Top 200-500 All India Rank in GATE -> PSU Group Discussion & Personal Interview -> Executive Trainee in IOCL / ONGC / NTPC / POWERGRID."}],
            "ladder": [
                {"stage": "Executive Trainee / Assistant Manager (E-2)", "exp": "0-3 Years", "desc": "Completes plant rotational training, operates shift DCS consoles, handles plant maintenance."},
                {"stage": "Deputy Manager / Manager (E-3/E-4)", "exp": "3-8 Years", "desc": "Heads operational unit (boiler turbine generator, distillation column), leads safety shutdowns."},
                {"stage": "Chief Manager / DGM (E-5/E-6)", "exp": "8-15 Years", "desc": "Oversees full plant division, manages multi-crore annual maintenance contracts."},
                {"stage": "General Manager / Plant Head / Director (E-7 to Board)", "exp": "15+ Years", "desc": "Heads 2,000 MW power plant or 15 MMTPA refinery, appointed to Board of Directors."}
            ],
            "roadmaps": {
                "Class 10": "Focus on Physics, Mathematics, and understanding how machines and power stations work.",
                "Class 12": "Top scores in PCM. Enter premier engineering institutions through JEE.",
                "Graduation": "Complete B.Tech in Mechanical, Electrical, Civil, or Chemical Engineering with high core conceptual mastery. Prepare rigorously for GATE.",
                "Working Professional": "Achieve a top All India Rank in GATE to secure interview calls from premier Maharatna PSUs."
            }
        },
        {
            "title": "Indian Forest Service Officer (IFS)",
            "short_name": "Forest Officer (IFS)",
            "slug": "indian-forest-service-officer",
            "category": "Government, Defence & Civil Services",
            "sub_category": "Forestry, Wildlife & Environmental Governance",
            "industry": "Ministry of Environment, Forest & Climate Change",
            "icon": "tree-fill",
            "short_description": "Protects national tiger reserves, conserves wildlife ecosystems, manages timber forests, and enforces environmental conservation laws.",
            "description": "Indian Forest Service (IFS) officers are All India Service leaders who manage the nation's vast natural heritage. They command national parks, tiger reserves, wildlife sanctuaries, and reserve forests, enforcing the Wildlife Protection Act and combating environmental crimes.",
            "what_they_do": "They manage tiger reserves as Field Directors, combat wildlife poaching and illegal timber logging, execute compensatory afforestation programs, mitigate human-wildlife conflict, and conserve biodiversity catchments.",
            "day_to_day_work": "• Patrolling wildlife sanctuaries and inspecting forest beat outposts.\n• Reviewing anti-poaching operations and wildlife camera trap monitoring.\n• Resolving human-wildlife conflicts (tiger, elephant, leopard mitigation).\n• Managing forest fire prevention lines and controlled burning.\n• Directing afforestation nurseries and watershed management programs.",
            "work_environment": "National parks, wildlife sanctuaries, reserve forests, state forest headquarters.",
            "work_modes": "On-site / Forest Field Patrol / Wilderness Command / Office",
            "minimum_qualification": "Undergraduate (Degree in Science / Engineering / Forestry)",
            "preferred_streams": "Science (PCB / PCM) / Engineering",
            "required_subjects": "Degree with at least one subject among Forestry, Botany, Chemistry, Geology, Mathematics, Physics, Zoology, or Engineering",
            "technical_skills": "Wildlife Management, Forestry Silviculture, Wildlife Protection Act 1972, Forest Fire Control, GIS Wildlife Tracking, Anti-Poaching Tactics",
            "soft_skills": "Supreme Courage, Passion for Wildlife, Physical Endurance, Leadership in Wilderness",
            "tools": "Camera Traps, GIS Mapping, Anti-Poaching GPS Navigators, Forest Range Wireless Radios",
            "certifications": "Selected through UPSC Indian Forest Service (IFS) Examination, Trained at IGNFA Dehradun",
            "experience_level": "Assistant Conservator of Forests to Principal Chief Conservator of Forests (PCCF)",
            "career_growth": "Apex All India Service trajectory progressing to Field Director of Tiger Reserve, Chief Wildlife Warden, or Principal Chief Conservator of Forests (Head of Forest Force - PCCF).",
            "internship_roles": "IGNFA Dehradun Institutional & Wildnerness Field Training (2 Years)",
            "entry_level_roles": "Assistant Conservator of Forests (ACF), Divisional Forest Officer (DFO)",
            "average_salary": "₹10 - ₹24 LPA (Official 7th CPC All India Service Pay Scale: Level 10 to Level 17 + Forest Bungalow, Security, 4x4 Gypsy)",
            "salary_indicative": "DFO (Level 11/12): Basic ₹67,700 - ₹78,800 + DA + Special Forest Allowances | Chief Wildlife Warden (Level 15): Basic ₹1,82,200 | PCCF (Level 17): Fixed ₹2,25,000 + apex benefits.",
            "future_scope": "Paramount national and global necessity protecting India's 75% tiger population, carbon sinks, and biodiversity against climate change.",
            "government_opportunities": "UPSC Indian Forest Service Examination (Conducted alongside UPSC CSE Prelims).",
            "private_opportunities": "Not applicable (Sovereign All India Service). Post-retirement: WWF, Wildlife Conservation Society (WCS), UNEP.",
            "higher_study_options": "Master's / Fellowships in Wildlife Management at Wildlife Institute of India (WII Dehradun).",
            "entrepreneurship_options": "Not applicable (Government Service).",
            "source": "Ministry of Environment, Forest and Climate Change / IGNFA / UPSC",
            "official_url": "https://ignfa.gov.in",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 40, "type": "COMMON"}, {"course_id": 41, "type": "COMMON"}, {"course_id": 7, "type": "COMMON"}, {"course_id": 11, "type": "COMMON"}],
            "exams": [{"exam_id": 34, "importance": "PRIMARY"}, {"exam_id": 55, "importance": "PRIMARY"}],
            "routes": [{"title": "Path A: UPSC Indian Forest Service Examination Route", "type": "COMMON", "steps": "Degree in Science or Engineering -> Clear UPSC CSE Prelims with high cut-off -> Clear UPSC IFS Mains (General English, General Knowledge, plus Two Optional Subjects from Forestry/Botany/Zoology/Engg) -> Interview -> IGNFA Dehradun Training -> Allotted Cadre as ACF/DFO."}],
            "ladder": [
                {"stage": "Assistant Conservator of Forests (ACF)", "exp": "0-4 Years", "desc": "Commands forest ranges, directs anti-poaching patrols, investigates timber smuggling."},
                {"stage": "Divisional Forest Officer (DFO)", "exp": "4-9 Years", "desc": "Heads an entire Forest Division / Wildlife Division, manages hundreds of forest guards."},
                {"stage": "Conservator / Field Director of Tiger Reserve", "exp": "9-18 Years", "desc": "Directs famous tiger reserves (Corbett, Ranthambore, Kaziranga, Kanha), protects endangered wildlife."},
                {"stage": "Principal Chief Conservator of Forests (PCCF - Head of Forest Force)", "exp": "18+ Years", "desc": "Apex head of the entire forest department of a state, directs state environmental conservation policy."}
            ],
            "roadmaps": {
                "Class 10": "Develop love for forests, national parks, wildlife, and outdoor trekking.",
                "Class 12": "Choose Science (PCB or PCM) for board exams.",
                "Graduation": "Complete graduation in Science (Botany, Zoology, Forestry, Chemistry, Physics) or any Engineering discipline (mandatory UPSC eligibility criteria).",
                "Working Professional": "Prepare for the UPSC Indian Forest Service exam focusing on optional subjects like Forestry, Botany, Zoology, or Agricultural Engineering."
            }
        }
    ]

print("Catalog builder part 10 ready.")
