"""
scripts/catalog_builder.py
Generates full authentic occupational data for Engineering, Law, Government, Business, Science, Education,
Media, Design, Agriculture, Aviation, and Social Sciences.
"""

def get_engineering_remaining():
    return [
        {
            "title": "Chemical Engineer",
            "short_name": "Chemical Engineer",
            "slug": "chemical-engineer",
            "category": "Engineering & Manufacturing",
            "sub_category": "Process & Chemical Engineering",
            "industry": "Chemicals, Oil & Gas, Pharmaceuticals",
            "icon": "droplet-half",
            "short_description": "Converts raw chemical materials into valuable everyday products like pharmaceuticals, fuels, plastics, and fertilizers.",
            "description": "Chemical Engineers apply principles of chemistry, physics, biology, and mathematics to design and operate large-scale chemical processing plants. They optimize reaction thermodynamics, distillation towers, fluid pipelines, and plant safety.",
            "what_they_do": "They design chemical reactors, oversee refinery operations, ensure hazardous waste treatment, simulate fluid flows using Aspen Plus, and develop sustainable biochemical alternatives.",
            "day_to_day_work": "• Simulating chemical process flowsheets in Aspen Plus or HYSYS.\n• Monitoring plant pressure, temperature, and distillation columns.\n• Optimizing reactor catalyst efficiency and mass balance.\n• Conducting Process Hazard Analysis (PHA) and safety audits.\n• Collaborating with quality control and environmental compliance officers.",
            "work_environment": "Petrochemical refineries, pharmaceutical plants, chemical design consultancies.",
            "work_modes": "On-site / Plant Floor / Design Office",
            "minimum_qualification": "Undergraduate (B.Tech / B.E.)",
            "preferred_streams": "Science (PCM)",
            "required_subjects": "Chemistry, Physics, Mathematics",
            "technical_skills": "Thermodynamics, Mass Transfer, Heat Transfer, Chemical Reaction Engineering, Aspen Plus, Process Safety, Piping Design",
            "soft_skills": "Plant Safety Focus, Analytical Rigor, Problem Solving, Team Coordination",
            "tools": "Aspen Plus, Aspen HYSYS, MATLAB, AutoCAD P&ID, ChemCAD",
            "certifications": "Indian Institute of Chemical Engineers (IIChE) Membership, Process Safety Management (PSM)",
            "experience_level": "Entry-Level to Senior",
            "career_growth": "Direct progression to Process Lead, Refinery Operations Manager, or Chief Chemical Engineer.",
            "internship_roles": "Chemical Process Intern, Refinery Operations Trainee, Pilot Plant Intern",
            "entry_level_roles": "Graduate Engineer Trainee (GET), Junior Process Engineer, Chemical Plant Engineer",
            "average_salary": "₹4.5 - ₹14 LPA (Indicative range)",
            "salary_indicative": "Entry-Level GET (0-2 yrs): ₹4.5 - 7 LPA | Process Engineer (3-6 yrs): ₹8 - 16 LPA | Refinery Head / Technical Director (7+ yrs): ₹18 - 45+ LPA. Indicative figures from IIChE 2024.",
            "future_scope": "Strong sustained demand with green hydrogen initiatives, specialty chemicals boom, and bio-pharmaceutical manufacturing.",
            "government_opportunities": "IOCL, BPCL, HPCL, ONGC, GAIL, BARC (Bhabha Atomic Research Centre), DRDO.",
            "private_opportunities": "Reliance Industries, Tata Chemicals, Aarti Industries, UPL, Dow Chemical, BASF, Sun Pharma.",
            "higher_study_options": "M.Tech in Chemical Engineering, M.S. in Biochemical Engineering, MBA in Energy Management.",
            "entrepreneurship_options": "Specialty chemical formulation manufacturing, industrial effluent treatment consultancy.",
            "source": "Indian Institute of Chemical Engineers (IIChE) / AICTE",
            "official_url": "https://www.iiche.org.in",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 9, "type": "ALTERNATIVE"}, {"course_id": 11, "type": "ALTERNATIVE"}, {"course_id": 3, "type": "COMMON"}],
            "exams": [{"exam_id": 8, "importance": "PRIMARY"}, {"exam_id": 69, "importance": "PRIMARY"}],
            "routes": [{"title": "Path A: Standard B.Tech Chemical Engineering", "type": "COMMON", "steps": "Class 12 (PCM) -> JEE Main / State CET -> B.Tech Chemical Engineering (4 yrs) -> Learn Aspen Plus -> Campus GET or GATE PSU (IOCL/ONGC)."}],
            "ladder": [
                {"stage": "Chemical GET / Shift Engineer", "exp": "0-2 Years", "desc": "Monitors distillation towers, takes field pressure/temperature readings, assists in turnaround shutdowns."},
                {"stage": "Process Engineer", "exp": "2-5 Years", "desc": "Simulates unit operations in Aspen Plus, optimizes energy consumption, resolves bottlenecking."},
                {"stage": "Senior Process / Production Manager", "exp": "5-8 Years", "desc": "Oversees full continuous chemical plant operations, manages environmental compliance."},
                {"stage": "Plant Head / Chief Technology Officer", "exp": "8+ Years", "desc": "Directs multi-unit refinery complexes, capital expansions, and technology licenses."}
            ],
            "roadmaps": {
                "Class 10": "Focus on Chemistry, chemical reactions, and physical states of matter.",
                "Class 12": "Master Organic, Inorganic, and Physical Chemistry alongside Physics and Calculus.",
                "Graduation": "Complete B.Tech Chemical Engineering with mastery over Aspen Plus, mass/heat transfer, and fluid mechanics.",
                "Working Professional": "Prepare for GATE Chemical Engineering for premier Maharatna PSUs (IOCL, HPCL, BPCL)."
            }
        },
        {
            "title": "Environmental Engineer",
            "short_name": "Environmental Engineer",
            "slug": "environmental-engineer",
            "category": "Engineering & Manufacturing",
            "sub_category": "Environmental & Sustainability Engineering",
            "industry": "Environmental Services & Sustainability",
            "icon": "tree",
            "short_description": "Designs solutions to environmental challenges such as pollution control, waste management, water purification, and climate change.",
            "description": "Environmental Engineers apply engineering and biological principles to improve environmental quality, protect public health, remediate contaminated land and water bodies, and design sustainable industrial manufacturing processes.",
            "what_they_do": "They design wastewater treatment plants (STP/ETP), air pollution control systems (scrubbers, bag filters), hazardous solid waste disposal facilities, and conduct Environmental Impact Assessments (EIA).",
            "day_to_day_work": "• Designing sewage and effluent treatment plant schematics.\n• Conducting air and water quality sampling and lab pollutant assays.\n• Modeling atmospheric pollutant dispersion using AERMOD.\n• Preparing Environmental Impact Assessment (EIA) reports for government clearance.\n• Auditing industrial factories for State Pollution Control Board compliance.",
            "work_environment": "Environmental consultancies, municipal water authorities, industrial plants, field monitoring sites.",
            "work_modes": "On-site / Field Sampling / Design Office",
            "minimum_qualification": "Undergraduate (B.Tech / B.E.)",
            "preferred_streams": "Science (PCM / PCB)",
            "required_subjects": "Chemistry, Mathematics, Physics / Biology",
            "technical_skills": "Wastewater Treatment Design, Air Pollution Control, Environmental Impact Assessment (EIA), Hazardous Waste Management, GIS",
            "soft_skills": "Passion for Conservation, Regulatory Diplomacy, Systematic Problem Solving",
            "tools": "AERMOD, BioWin, GPS/GIS, Water Quality Testers, AutoCAD",
            "certifications": "EIA Coordinator Certification (QCI - NABET), Certified Environmental Auditor",
            "experience_level": "Entry-Level to Senior",
            "career_growth": "Expanding career into Chief Sustainability Officer (CSO), Environmental Consultant, or Regulatory Director.",
            "internship_roles": "Environmental Engineering Intern, ETP Trainee, Sustainability Intern",
            "entry_level_roles": "Junior Environmental Engineer, Sustainability Analyst, Water Treatment Executive",
            "average_salary": "₹4 - ₹11 LPA (Indicative range)",
            "salary_indicative": "Entry-Level (0-2 yrs): ₹3.5 - 5.5 LPA | Environmental Consultant (3-6 yrs): ₹6.5 - 13 LPA | Chief Sustainability Officer (7+ yrs): ₹18 - 36+ LPA. Indicative figures from CPCB 2024.",
            "future_scope": "Surging demand driven by Net Zero 2070 targets, ESG compliance mandates, and national clean river initiatives (Namami Gange).",
            "government_opportunities": "Central Pollution Control Board (CPCB), State Pollution Control Boards (SPCBs), Ministry of Environment, Forest and Climate Change (MoEFCC).",
            "private_opportunities": "VA TECH WABAG, Thermax, Tata Consulting Engineers, ERM, Jacobs, municipal water utilities.",
            "higher_study_options": "M.Tech in Environmental Engineering, M.S. in Sustainability Science.",
            "entrepreneurship_options": "Water and wastewater treatment EPC firm, environmental testing laboratory, ESG consulting.",
            "source": "Central Pollution Control Board (CPCB) / MoEFCC",
            "official_url": "https://cpcb.nic.in",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 12, "type": "COMMON"}, {"course_id": 3, "type": "ALTERNATIVE"}],
            "exams": [{"exam_id": 8, "importance": "PRIMARY"}, {"exam_id": 69, "importance": "PRIMARY"}],
            "routes": [{"title": "Path A: Civil / Chemical to Environmental Route", "type": "COMMON", "steps": "B.Tech Civil / Chemical / Environmental -> Master ETP/STP design -> QCI-NABET EIA accreditation -> Environmental Engineer."}],
            "ladder": [
                {"stage": "Junior Environmental Engineer", "exp": "0-2 Years", "desc": "Samples water and stack emissions, logs ETP operational parameters."},
                {"stage": "Environmental Consultant", "exp": "2-5 Years", "desc": "Prepares EIA reports, designs biological and chemical wastewater plants."},
                {"stage": "Senior Sustainability Manager", "exp": "5-8 Years", "desc": "Manages corporate ESG reporting, carbon footprint reduction strategies."},
                {"stage": "Chief Sustainability Officer (CSO)", "exp": "8+ Years", "desc": "Directs enterprise circular economy roadmap and environmental governance."}
            ],
            "roadmaps": {
                "Class 10": "Focus on ecology, chemistry, and environmental science.",
                "Class 12": "Choose Science with Chemistry and Mathematics.",
                "Graduation": "Complete B.Tech in Environmental, Civil, or Chemical Engineering with focus on waste management.",
                "Working Professional": "Earn NABET EIA Coordinator certification and master corporate carbon accounting (GHG Protocol)."
            }
        },
        {
            "title": "Robotics & Automation Engineer",
            "short_name": "Robotics Engineer",
            "slug": "robotics-automation-engineer",
            "category": "Engineering & Manufacturing",
            "sub_category": "Robotics, Mechatronics & Control Systems",
            "industry": "Robotics & Advanced Automation",
            "icon": "robot",
            "short_description": "Designs, builds, and programs autonomous robotic systems, robotic arms, and industrial automated manufacturing systems.",
            "description": "Robotics Engineers unite mechanical design, electrical circuitry, control theory, and computer science to build robotic machines capable of performing tasks autonomously or semi-autonomously in manufacturing, healthcare, logistics, and space exploration.",
            "what_they_do": "They design robotic kinematics and end-effectors, program industrial robot controllers (KUKA, ABB, Fanuc), implement ROS (Robot Operating System), integrate computer vision cameras, and configure automated guided vehicles (AGVs).",
            "day_to_day_work": "• Writing robot navigation and control algorithms using ROS and C++/Python.\n• Designing robot joint actuators, gearboxes, and chassis in SolidWorks.\n• Programming industrial articulated robotic arms on factory production lines.\n• Integrating LiDAR and stereo vision sensors for obstacle avoidance.\n• Commissioning automated warehouse robots (AMRs/AGVs).",
            "work_environment": "Robotics research labs, automated automotive factories, modern logistics fulfillment centers.",
            "work_modes": "On-site / Robotics Lab / Factory Floor",
            "minimum_qualification": "Undergraduate (B.Tech in Mechatronics / Mechanical / ECE / CS)",
            "preferred_streams": "Science (PCM)",
            "required_subjects": "Mathematics, Physics, Computer Science",
            "technical_skills": "Robot Operating System (ROS), Inverse Kinematics, C++, Python, Control Systems, Computer Vision (OpenCV), SolidWorks, PLC Programming",
            "soft_skills": "Interdisciplinary Thinking, Creative Problem Solving, Tenacity, Teamwork",
            "tools": "ROS/ROS2, Gazebo Simulator, MATLAB/Simulink, OpenCV, SolidWorks, Arduino/Raspberry Pi",
            "certifications": "Certified Robotics Professional, KUKA / Fanuc Industrial Robot Certification",
            "experience_level": "Entry-Level to Senior",
            "career_growth": "High-velocity career path progressing to Lead Robotics Architect, Head of Automation, or Robotics Founder.",
            "internship_roles": "Robotics Intern, Automation Engineering Intern, Mechatronics Trainee",
            "entry_level_roles": "Junior Robotics Engineer, Automation Controls Engineer, Mechatronics Trainee",
            "average_salary": "₹5.5 - ₹18 LPA (Indicative range)",
            "salary_indicative": "Entry-Level (0-2 yrs): ₹5 - 8 LPA | Senior Robotics Engineer (3-6 yrs): ₹10 - 22 LPA | Robotics Architect / Director (7+ yrs): ₹24 - 55+ LPA. Indicative figures from Robotics Society of India 2024.",
            "future_scope": "Exponential expansion with warehouse automation, surgical robotics, drone logistics, and factory Industry 4.0 transformation.",
            "government_opportunities": "DRDO Centre for AI and Robotics (CAIR), ISRO Space Robotics, BARC Robotics Wing, IIT Tech Parks.",
            "private_opportunities": "GreyOrange, Addverb Technologies, KUKA India, ABB Robotics, Fanuc, Tata Motors, Flipkart Automation.",
            "higher_study_options": "M.Tech in Robotics / Mechatronics, M.S. in Autonomous Systems.",
            "entrepreneurship_options": "Autonomous mobile robot (AMR) startup, custom industrial automation solutions company.",
            "source": "The Robotics Society of India (RSI) / AICTE",
            "official_url": "https://www.rs-india.org",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 9, "type": "COMMON"}, {"course_id": 11, "type": "COMMON"}, {"course_id": 10, "type": "COMMON"}],
            "exams": [{"exam_id": 8, "importance": "PRIMARY"}, {"exam_id": 69, "importance": "PRIMARY"}],
            "routes": [{"title": "Path A: Mechatronics / Mechanical / CS to Robotics", "type": "COMMON", "steps": "B.Tech in Mechatronics / Mechanical / CS / ECE -> Master ROS, Linux, OpenCV & Kinematics -> Build live robot prototypes -> Robotics Engineer."}],
            "ladder": [
                {"stage": "Junior Robotics Engineer", "exp": "0-2 Years", "desc": "Writes robot drivers, tests sensors in Gazebo simulations, calibrates vision cameras."},
                {"stage": "Robotics Software / Controls Engineer", "exp": "2-5 Years", "desc": "Implements SLAM navigation algorithms, designs motion planning and trajectory optimization."},
                {"stage": "Lead Robotics Architect", "exp": "5-8 Years", "desc": "Architects full multi-robot fleet management platforms, leads hardware-software integration."},
                {"stage": "VP of Automation / Robotics Founder", "exp": "8+ Years", "desc": "Directs industrial robotic commercialization, holds core robotics patents."}
            ],
            "roadmaps": {
                "Class 10": "Experiment with Arduino, basic sensors, and simple motor circuits.",
                "Class 12": "Excel in Physics (mechanics, rotational dynamics) and Mathematics (matrices, vectors).",
                "Graduation": "Learn ROS/ROS2, Linux, C++, and OpenCV. Build a mobile robot or robotic arm for university competitions.",
                "Working Professional": "Specialize in SLAM (Simultaneous Localization and Mapping), trajectory control, or autonomous drone navigation."
            }
        },
        {
            "title": "Biomedical Engineer",
            "short_name": "Biomedical Engineer",
            "slug": "biomedical-engineer",
            "category": "Engineering & Manufacturing",
            "sub_category": "Biomedical Devices & Medical Technology",
            "industry": "Medical Technology & Devices",
            "icon": "activity",
            "short_description": "Designs, develops, and maintains medical equipment, diagnostic instruments, surgical robots, and prosthetic devices.",
            "description": "Biomedical Engineers fuse engineering innovation with medical science. They design life-saving technologies including pacemakers, MRI scanners, dialysis units, prosthetic limbs, and wearable health monitors that revolutionize patient care.",
            "what_they_do": "They design medical hardware and sensors, test medical devices for biocompatibility and electrical safety (IEC 60601), manage hospital clinical equipment inventories, and develop medical imaging software.",
            "day_to_day_work": "• Designing medical device circuitry and biosensors in CAD.\n• Calibrating and testing hospital ventilators, defibrillators, and patient monitors.\n• Conducting biocompatibility testing on implant materials.\n• Managing regulatory submissions for Central Drugs Standard Control Organisation (CDSCO).\n• Training surgeons and clinical nurses on operating robotic surgical equipment.",
            "work_environment": "Hospital clinical engineering departments, medical device R&D centers, diagnostics manufacturers.",
            "work_modes": "On-site / Hospital & Lab",
            "minimum_qualification": "Undergraduate (B.Tech in Biomedical Engineering)",
            "preferred_streams": "Science (PCM / PCB)",
            "required_subjects": "Physics, Chemistry, Mathematics / Biology",
            "technical_skills": "Biomedical Signal Processing, Biomechanics, Medical Device Standards (IEC 60601, ISO 13485), Sensor Design, MATLAB, Embedded C",
            "soft_skills": "Extreme Precision, Patient Safety Empathy, Multidisciplinary Communication",
            "tools": "MATLAB/Simulink, LabVIEW, KiCad, Biomedical Simulators, Oscilloscope",
            "certifications": "Certified Clinical Engineer (CCE), ISO 13485 Medical Device Lead Auditor",
            "experience_level": "Entry-Level to Senior",
            "career_growth": "Steady growth progressing to Chief Biomedical Engineer, Head of Clinical Engineering, or MedTech R&D Director.",
            "internship_roles": "Hospital Biomedical Intern, MedTech R&D Trainee",
            "entry_level_roles": "Junior Biomedical Engineer, Clinical Engineer, Service Engineer",
            "average_salary": "₹4 - ₹12 LPA (Indicative range)",
            "salary_indicative": "Entry-Level (0-2 yrs): ₹3.5 - 5.5 LPA | MedTech Product Engineer (3-6 yrs): ₹7 - 14 LPA | Director of Medical Engineering (7+ yrs): ₹18 - 38+ LPA. Indicative figures from Biomedical Engineering Society of India 2024.",
            "future_scope": "Surging national priority supported by India's Medical Devices Policy 2023, indigenous med-tech parks, and healthcare digitalization.",
            "government_opportunities": "AIIMS Clinical Engineering Departments, CDSCO, Sree Chitra Tirunal Institute for Medical Sciences and Technology (SCTIMST), DRDO DEBEL.",
            "private_opportunities": "GE Healthcare, Siemens Healthineers, Philips Healthcare, Medtronic, Stryker, Transasia Bio-Medicals.",
            "higher_study_options": "M.Tech in Biomedical Engineering (IITs), M.S. in Neural Engineering / Bioengineering.",
            "entrepreneurship_options": "Indigenous medical device startup, hospital clinical engineering asset management firm.",
            "source": "Biomedical Engineering Society of India (BMESI) / CDSCO",
            "official_url": "https://cdsco.gov.in",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 10, "type": "ALTERNATIVE"}, {"course_id": 9, "type": "ALTERNATIVE"}],
            "exams": [{"exam_id": 8, "importance": "PRIMARY"}, {"exam_id": 69, "importance": "PRIMARY"}],
            "routes": [{"title": "Path A: B.Tech Biomedical Engineering Route", "type": "COMMON", "steps": "Class 12 (PCM/PCB) -> B.Tech Biomedical Engineering -> Clinical internships in hospitals -> MedTech Product / Hospital Engineer."}],
            "ladder": [
                {"stage": "Biomedical Trainee / Service Engineer", "exp": "0-2 Years", "desc": "Calibrates ICU monitors, troubleshoots dialysis units, handles preventive maintenance."},
                {"stage": "Biomedical / MedTech Design Engineer", "exp": "2-5 Years", "desc": "Designs biosensors, programs medical telemetry, manages ISO 13485 quality audits."},
                {"stage": "Senior Clinical Engineering Manager", "exp": "5-8 Years", "desc": "Oversees hospital network medical equipment procurement, budgeting, and safety compliance."},
                {"stage": "VP of MedTech R&D", "exp": "8+ Years", "desc": "Directs global clinical trials and breakthrough medical device launches."}
            ],
            "roadmaps": {
                "Class 10": "Develop interest in both human biology and electronic gadgets.",
                "Class 12": "Study Physics, Chemistry, and Mathematics/Biology.",
                "Graduation": "Complete B.Tech in Biomedical Engineering with extensive hospital attachments and sensor prototyping.",
                "Working Professional": "Master ISO 13485 medical device regulations and prepare for GATE Biomedical Engineering for M.Tech at top IITs."
            }
        },
        {
            "title": "Automotive Engineer",
            "short_name": "Automotive Engineer",
            "slug": "automotive-engineer",
            "category": "Engineering & Manufacturing",
            "sub_category": "Automotive & Electric Vehicle Engineering",
            "industry": "Automotive & Mobility",
            "icon": "car-front",
            "short_description": "Designs, develops, tests, and manufactures passenger vehicles, commercial trucks, motorcycles, and electric vehicle systems.",
            "description": "Automotive Engineers develop modern mobility systems. They work on vehicle aerodynamics, internal combustion and electric powertrains, battery management systems (BMS), suspension dynamics, crash safety, and autonomous driver-assistance systems (ADAS).",
            "what_they_do": "They design vehicle chassis and powertrains in CAD, conduct crash simulation tests, calibrate engine and electric motor controllers, optimize vehicle battery cooling, and manage assembly line manufacturing.",
            "day_to_day_work": "• Designing automotive chassis and suspension systems in CATIA.\n• Running vehicle crash and structural impact simulations in LS-DYNA.\n• Calibrating Electric Vehicle (EV) motor controllers and Battery Management Systems (BMS).\n• Testing vehicle noise, vibration, and harshness (NVH) on test tracks.\n• Managing vehicle homologation testing with ARAI (Automotive Research Association of India).",
            "work_environment": "Automotive R&D centers, vehicle test tracks, automotive manufacturing plants.",
            "work_modes": "On-site / Plant / R&D Track",
            "minimum_qualification": "Undergraduate (B.Tech in Automobile / Mechanical / Electrical)",
            "preferred_streams": "Science (PCM)",
            "required_subjects": "Mathematics, Physics, Chemistry",
            "technical_skills": "Vehicle Dynamics, Powertrain Engineering, Battery Management Systems (BMS), CATIA, LS-DYNA, MATLAB/Simulink, NVH Testing",
            "soft_skills": "Passion for Vehicles, Safety Discipline, Problem Solving, Cross-Functional Teamwork",
            "tools": "CATIA V5, MATLAB/Simulink, LS-DYNA, CANoe, Ansys Mechanical, SolidWorks",
            "certifications": "Automotive Research Association of India (ARAI) Certified Automotive Engineer",
            "experience_level": "Entry-Level to Senior",
            "career_growth": "High career path progressing to Chief Vehicle Engineer, Head of EV Powertrain, or VP of Automotive Engineering.",
            "internship_roles": "Automotive R&D Intern, Vehicle Dynamics Trainee, EV Testing Intern",
            "entry_level_roles": "Graduate Engineer Trainee (GET), Vehicle Test Engineer, Powertrain Engineer",
            "average_salary": "₹4.5 - ₹15 LPA (Indicative range)",
            "salary_indicative": "Entry-Level GET (0-2 yrs): ₹4 - 6.5 LPA | Senior Automotive Engineer (3-6 yrs): ₹8 - 18 LPA | Chief Vehicle Engineer (7+ yrs): ₹20 - 45+ LPA. Indicative figures from ASDC 2024.",
            "future_scope": "Revolutionary boom powered by Electric Vehicles (EVs), battery Gigafactories, autonomous driving (ADAS), and green mobility.",
            "government_opportunities": "Automotive Research Association of India (ARAI), International Centre for Automotive Technology (ICAT), Defence Vehicle R&D (VRDE).",
            "private_opportunities": "Tata Motors, Mahindra, Maruti Suzuki, Hyundai India, Ola Electric, Ather Energy, Bosch, TVS Motor.",
            "higher_study_options": "M.Tech in Automotive Engineering / Electric Mobility (IIT Delhi, IIT Madras), M.S. in Vehicle Dynamics.",
            "entrepreneurship_options": "EV conversion and retrofitting startup, automotive telematics company, custom vehicle tuning shop.",
            "source": "Automotive Skills Development Council (ASDC) / ARAI",
            "official_url": "https://www.asdc.org.in",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 11, "type": "DIRECT"}, {"course_id": 13, "type": "COMMON"}],
            "exams": [{"exam_id": 8, "importance": "PRIMARY"}, {"exam_id": 69, "importance": "PRIMARY"}],
            "routes": [{"title": "Path A: Mechanical / Automobile to EV Engineer", "type": "COMMON", "steps": "B.Tech Mechanical / Automobile / Electrical -> Participate in Formula Student / BAJA SAE -> Master MATLAB/Simulink & BMS -> Automotive OEM GET."}],
            "ladder": [
                {"stage": "Automotive GET", "exp": "0-2 Years", "desc": "Assists in vehicle test bench runs, updates CATIA models, monitors vehicle NVH tests."},
                {"stage": "Vehicle / Powertrain Engineer", "exp": "2-5 Years", "desc": "Calibrates BMS/motor controllers, optimizes suspension geometry, resolves thermal issues."},
                {"stage": "Principal Engineer / Vehicle Line Lead", "exp": "5-8 Years", "desc": "Leads complete vehicle platform program (from clay model to showroom launch)."},
                {"stage": "Chief Technology Officer / VP Mobility", "exp": "8+ Years", "desc": "Directs future electric vehicle roadmap and multi-billion automotive manufacturing."}
            ],
            "roadmaps": {
                "Class 10": "Learn how car engines, transmissions, and steering mechanisms work.",
                "Class 12": "Score well in Physics (mechanics, electricity) and Mathematics.",
                "Graduation": "Join university BAJA SAE or Formula Student racing teams. Build working vehicle prototypes.",
                "Working Professional": "Specialize in Electric Vehicle battery packs, CAN communication protocols, or ADAS computer vision."
            }
        },
        {
            "title": "Industrial & Production Engineer",
            "short_name": "Industrial Engineer",
            "slug": "industrial-production-engineer",
            "category": "Engineering & Manufacturing",
            "sub_category": "Manufacturing Systems & Operations",
            "industry": "Manufacturing & Supply Chain",
            "icon": "gear-fill",
            "short_description": "Optimizes complex manufacturing processes, factory floor layouts, and worker efficiency to eliminate waste and maximize productivity.",
            "description": "Industrial and Production Engineers find ways to eliminate wastefulness in production processes. They devise efficient systems that integrate workers, machines, materials, information, and energy to manufacture products with peak efficiency.",
            "what_they_do": "They design factory floor layouts, conduct time and motion studies, implement Lean Manufacturing and Six Sigma methodologies, manage supply chain inventories, and ensure ergonomic worker safety.",
            "day_to_day_work": "• Conducting time-and-motion studies on assembly lines to eliminate bottlenecks.\n• Designing ergonomic factory shop-floor layouts in AutoCAD.\n• Implementing 5S, Kaizen, and Six Sigma DMAIC process improvements.\n• Calculating Overall Equipment Effectiveness (OEE) and downtime metrics.\n• Managing just-in-time (JIT) production schedules with supply chain teams.",
            "work_environment": "Manufacturing shop floors, industrial assembly plants, logistics warehouses.",
            "work_modes": "On-site / Factory Floor",
            "minimum_qualification": "Undergraduate (B.Tech / B.E.)",
            "preferred_streams": "Science (PCM)",
            "required_subjects": "Mathematics, Physics, Chemistry",
            "technical_skills": "Lean Manufacturing, Six Sigma (DMAIC), Time & Motion Study, Factory Layout Design, Supply Chain Optimization, OEE Analysis, CNC Machining",
            "soft_skills": "Pragmatic Problem Solving, Shop Floor Leadership, Negotiation, Continuous Improvement Mindset",
            "tools": "AutoCAD Plant Design, Minitab, Arena Simulation, SAP ERP, Excel (Advanced)",
            "certifications": "Six Sigma Green Belt / Black Belt (ASQ), Certified Supply Chain Professional (CSCP)",
            "experience_level": "Entry-Level to Senior",
            "career_growth": "Broad executive path progressing to Operations Director, Plant Head, or Chief Operating Officer (COO).",
            "internship_roles": "Industrial Engineering Intern, Production Trainee, Lean Manufacturing Trainee",
            "entry_level_roles": "Graduate Engineer Trainee (GET), Junior Production Engineer, Quality Engineer",
            "average_salary": "₹4.5 - ₹13 LPA (Indicative range)",
            "salary_indicative": "Entry-Level GET (0-2 yrs): ₹4 - 6.5 LPA | Production Manager (3-6 yrs): ₹7.5 - 15 LPA | Plant Head / Operations Director (7+ yrs): ₹18 - 42+ LPA. Indicative figures from Indian Institution of Industrial Engineering 2024.",
            "future_scope": "Strong sustained growth fueled by 'Make in India' and global supply chain diversification into Indian manufacturing.",
            "government_opportunities": "Ordnance Factory Board, BHEL, SAIL, Indian Railways Production Units, Heavy Engineering Corporation.",
            "private_opportunities": "Tata Motors, Larsen & Toubro, Hero MotoCorp, Foxconn India, ITC, Hindustan Unilever, Amazon Logistics.",
            "higher_study_options": "NITIE (IIM Mumbai) PGDIE, M.Tech in Industrial Engineering, MBA in Operations.",
            "entrepreneurship_options": "Contract manufacturing factory, lean manufacturing consultancy, industrial automation agency.",
            "source": "Indian Institution of Industrial Engineering (IIIE) / AICTE",
            "official_url": "https://www.iiie-india.com",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 11, "type": "COMMON"}, {"course_id": 17, "type": "ALTERNATIVE"}],
            "exams": [{"exam_id": 8, "importance": "PRIMARY"}, {"exam_id": 69, "importance": "PRIMARY"}],
            "routes": [{"title": "Path A: Standard Engineering to Production Route", "type": "COMMON", "steps": "B.Tech Industrial / Production / Mechanical Engineering -> Six Sigma Green Belt -> Factory GET hire -> Production Manager."}],
            "ladder": [
                {"stage": "Production GET", "exp": "0-2 Years", "desc": "Manages shift workers, logs daily production output, tracks scrap rate."},
                {"stage": "Industrial / Process Engineer", "exp": "2-5 Years", "desc": "Leads Kaizen projects, reconfigures assembly lines, improves OEE by 15-20%."},
                {"stage": "Production Head / Operations Manager", "exp": "5-8 Years", "desc": "Owns total factory production targets, labor safety, and manufacturing Capex."},
                {"stage": "Plant Head / Chief Operating Officer (COO)", "exp": "8+ Years", "desc": "Directs nationwide network of manufacturing plants and global supply chains."}
            ],
            "roadmaps": {
                "Class 10": "Focus on arithmetic, statistics, and organizing everyday processes efficiently.",
                "Class 12": "Score well in PCM. Prepare for engineering entrance examinations.",
                "Graduation": "Complete B.Tech with focus on Lean Manufacturing, Operations Research, and Six Sigma.",
                "Working Professional": "Target IIM Mumbai (formerly NITIE) for world-class industrial management or earn Six Sigma Black Belt."
            }
        },
        {
            "title": "Petroleum & Energy Engineer",
            "short_name": "Petroleum Engineer",
            "slug": "petroleum-engineer",
            "category": "Engineering & Manufacturing",
            "sub_category": "Energy, Oil & Gas",
            "industry": "Oil, Gas & Energy",
            "icon": "fuel-pump",
            "short_description": "Designs methods for extracting oil, natural gas, and geothermal energy safely and cost-effectively from deep beneath the earth.",
            "description": "Petroleum Engineers locate, drill, and extract hydrocarbons and geothermal energy from subsurface reservoirs. They specialize in reservoir engineering, drilling operations, production technology, and underground carbon capture and storage (CCS).",
            "what_they_do": "They model subsurface oil and gas reservoirs, design offshore and onshore drilling wells, calculate reservoir pressure, optimize artificial lift systems, and implement environmental containment safeguards.",
            "day_to_day_work": "• Analyzing seismic and well-log data to map hydrocarbon reservoirs.\n• Designing drilling programs and casing strings for deep-sea or shale wells.\n• Simulating reservoir recovery rates using Eclipse or Petrel software.\n• Monitoring offshore drilling rig operations and blowout preventer (BOP) safety.\n• Developing carbon capture and enhanced oil recovery (EOR) strategies.",
            "work_environment": "Offshore drilling platforms, onshore oil fields, corporate energy headquarters.",
            "work_modes": "On-site / Offshore Rig Rotation (e.g. 14 days on, 14 days off) / Office",
            "minimum_qualification": "Undergraduate (B.Tech in Petroleum / Chemical / Mechanical)",
            "preferred_streams": "Science (PCM)",
            "required_subjects": "Mathematics, Physics, Chemistry, Geology (helpful)",
            "technical_skills": "Reservoir Simulation, Drilling Engineering, Well Logging, Petrel, Production Optimization, Subsurface Geology, Rig Safety",
            "soft_skills": "High Physical Resilience, Extreme Safety Consciousness, Decisiveness Under Pressure",
            "tools": "Petrel, Eclipse, Landmark, Wellflo, MATLAB",
            "certifications": "Society of Petroleum Engineers (SPE) Membership, IWCF Well Control Certification",
            "experience_level": "Entry-Level to Senior",
            "career_growth": "Highly compensated international career path progressing to Drilling Superintendent, Chief Reservoir Engineer, or Energy Director.",
            "internship_roles": "Petroleum Engineering Intern, Rig Operations Trainee, Reservoir Intern",
            "entry_level_roles": "Graduate Trainee Engineer, Mud Logger, Field Specialist",
            "average_salary": "₹6 - ₹20 LPA (Indicative range - plus offshore field hardship allowances)",
            "salary_indicative": "Entry-Level / Field Engineer (0-2 yrs): ₹6 - 10 LPA | Reservoir Engineer (3-6 yrs): ₹12 - 24 LPA | Drilling Superintendent (7+ yrs): ₹26 - 65+ LPA (higher for overseas Gulf/North Sea postings). Indicative figures from SPE 2024.",
            "future_scope": "Essential global energy role pivoting towards deep-water natural gas, geothermal energy, and carbon sequestration (CCS).",
            "government_opportunities": "Oil and Natural Gas Corporation (ONGC), Oil India Limited (OIL), GAIL, Directorate General of Hydrocarbons (DGH).",
            "private_opportunities": "Reliance Industries (E&P), Schlumberger (SLB), Halliburton, Baker Hughes, Vedanta Cairn Oil & Gas, Shell.",
            "higher_study_options": "M.Tech in Petroleum Engineering (IIT ISM Dhanbad, RGIPT), M.S. in Energy Resources.",
            "entrepreneurship_options": "Petroleum drilling consultancy, oilfield chemical supply, well-testing services.",
            "source": "Society of Petroleum Engineers (SPE) / ONGC",
            "official_url": "https://www.spe.org",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 11, "type": "COMMON"}, {"course_id": 9, "type": "ALTERNATIVE"}],
            "exams": [{"exam_id": 8, "importance": "PRIMARY"}, {"exam_id": 9, "importance": "PRIMARY"}, {"exam_id": 69, "importance": "PRIMARY"}],
            "routes": [{"title": "Path A: IIT ISM Dhanbad / RGIPT Petroleum Route", "type": "COMMON", "steps": "Class 12 (PCM) -> JEE Advanced / JEE Main -> B.Tech Petroleum Engineering at IIT ISM Dhanbad or RGIPT -> Campus hire at ONGC / Schlumberger."}],
            "ladder": [
                {"stage": "Field Engineer Trainee", "exp": "0-2 Years", "desc": "Works on onshore/offshore rigs logging wells, monitoring mud weights and drilling parameters."},
                {"stage": "Reservoir / Production Engineer", "exp": "2-5 Years", "desc": "Models reservoir pressure, designs artificial lift and hydraulic fracturing programs."},
                {"stage": "Drilling Superintendent", "exp": "5-8 Years", "desc": "Commands complete multi-hundred-crore offshore drilling rig operations."},
                {"stage": "Director of Exploration & Production", "exp": "8+ Years", "desc": "Directs sovereign hydrocarbon reserves, licensing auctions, and energy transition portfolio."}
            ],
            "roadmaps": {
                "Class 10": "Focus on Physics mechanics, geology, and fluid pressure principles.",
                "Class 12": "Top scores in PCM. Target premier institutes like IIT ISM Dhanbad or RGIPT.",
                "Graduation": "Complete B.Tech in Petroleum or Mechanical Engineering with offshore safety certifications (BOSIET).",
                "Working Professional": "Clear GATE Petroleum Engineering for ONGC recruitment or join premier international oilfield service companies (SLB, Baker Hughes)."
            }
        }
    ]

print("Catalog builder module ready.")
