"""
scripts/catalog_expanded_part5.py
Domain L: Media & Communication (7 careers)
Domain M: Creative & Design (6 careers)
Domain N: Fine Arts (5 careers)
Domain O: Performing Arts (6 careers)
Domain P: Film & Entertainment (5 careers)
"""

def get_media_and_communication_careers():
    return [
        {
            "title": "Documentary Photojournalist",
            "short_name": "Photojournalist",
            "slug": "documentary-photojournalist",
            "category": "Media, Journalism & Digital Marketing",
            "sub_category": "Visual Journalism & Photography",
            "industry": "News Media, Documentary & Photojournalism",
            "icon": "camera",
            "short_description": "Tells visual stories through powerful photographs capturing breaking news, social conflicts, and human culture.",
            "description": "Documentary Photojournalists use visual imagery to capture truthful, compelling, and ethically verified news events, humanitarian crises, environmental changes, and cultural traditions. Working for national news agencies, magazines, and international wire services (Reuters, AP, AFP), they operate under strict journalistic ethics prohibiting staged or digitally manipulated scenes.",
            "what_they_do": "They cover breaking political and social events, document environmental transformations, photograph conflict and natural disasters, write precise factual captions, and pitch long-form photo essays.",
            "day_to_day_work": "• Traveling to news locations with professional DSLR/mirrorless camera gear and prime lenses.\n• Capturing real-time candid moments of civic protests, elections, or cultural festivals.\n• Editing, color-grading, and writing AP-standard factual captions with time/location data.\n• Transmitting high-resolution images via mobile satellite/cellular uplinks to newsdesks.\n• Researching and shooting long-form documentary projects on climate and rural livelihoods.",
            "work_environment": "Field locations (outdoors in all weather, conflict zones, public rallies), newsroom photo desks.",
            "work_modes": "Field / Outdoor / Remote",
            "minimum_qualification": "Undergraduate (B.A. / B.Sc in Photography / Journalism / Mass Communication or Portfolio-based Entry)",
            "preferred_streams": "Any Stream",
            "required_subjects": "Photography, Visual Communication, Journalism Ethics",
            "technical_skills": "Photojournalism Ethics, Manual Camera Exposure, Prime Lens Optics, Rapid Street Composition, Adobe Lightroom, Photo Captioning Standards, Digital Asset Management",
            "soft_skills": "Courage in Crises, Unobtrusive Observation, Deep Empathy, Rapid Reflexes",
            "tools": "Professional Mirrorless Cameras (Sony A7 IV, Canon R5, Nikon Z8), 24-70mm & 70-200mm f/2.8 Lenses, Adobe Lightroom, Photo Mechanic",
            "certifications": "Press Council of India Accreditation, Indian Photojournalists Association",
            "experience_level": "Entry to Senior Photojournalist",
            "career_growth": "Advance to Senior Staff Photojournalist, Photo Editor, Chief of Photography, or National Geographic Contributor.",
            "internship_roles": "Photojournalism Intern, News Photo Stringer",
            "entry_level_roles": "Staff Photographer, Junior Photojournalist, Wire Service Contributor",
            "average_salary": "₹4.0 - ₹12.0 LPA (Indicative range)",
            "salary_indicative": "Entry-Level Staff Photographer: ₹4.0 - 6 LPA | Experienced Photojournalist (3-6 yrs): ₹7 - 11 LPA | Senior Wire Service / International Assignment Contributor: ₹12 - 25+ LPA (International assignment rates $300-$700/day). Indicative figures from press journalist unions.",
            "future_scope": "Visual storytelling remains the most impactful medium in journalism across digital news, magazines, and documentaries.",
            "government_opportunities": "Press Information Bureau (PIB Photo Division), Photo Division (Ministry of Information & Broadcasting), Lok Sabha TV / Sansad TV.",
            "private_opportunities": "Reuters, Associated Press (AP), Agence France-Presse (AFP), The Hindu, Indian Express, Hindustan Times, National Geographic, Bloomberg.",
            "higher_study_options": "Master in Photojournalism (e.g. Light & Life Academy, AJK MCRC Jamia), International Visual Journalism Fellowships.",
            "entrepreneurship_options": "Founding an independent visual documentary collective, commercial editorial photography agency, or publishing photo books.",
            "source": "Press Council of India / Press Information Bureau (PIB)",
            "official_url": "https://pib.gov.in",
            "verification_status": "VERIFIED",
            "is_lesser_known": False,
            "career_family": "Media & Storytelling",
            "interest_clusters": "Media, Creativity, Art, Outdoor, Culture",
            "work_style": "Field, Outdoor",
            "reality_check": "Not commercial wedding or glamour photography: Demands rigorous adherence to journalistic truth (zero Photoshop manipulation of reality allowed).\nInvolves working under harsh, unpredictable, and sometimes physically hazardous conditions (crowds, teargas, monsoons).\nRequires sharp initiative: the best photojournalists spot stories and moments before others do.",
            "next_steps": "Invest in a basic manual camera and shoot daily documentary street photography.\nBuild a curated portfolio website featuring 3 distinct, cohesive photo essays with factual captions.\nPitch stories to local newspapers, digital media portals, or intern with veteran press photographers.",
            "courses": [{"course_id": 57, "type": "PRIMARY"}],
            "exams": [],
            "routes": [{"title": "Path A: Journalism Degree to Photojournalist", "type": "PRIMARY", "steps": "12th (Any Stream) -> BJMC (3 yrs) -> Photo Portfolio Building -> Stringer for Wire Services -> Staff Photojournalist."}],
            "ladder": [
                {"stage": "Freelance Stringer / Junior Photographer", "exp": "0-2 Years", "desc": "Covers daily city news, protests, and sports; submits captioned photos to regional newspapers."},
                {"stage": "Staff Photojournalist", "exp": "2-6 Years", "desc": "Covers national political rallies, state elections, humanitarian features; assigned to major national events."},
                {"stage": "Photo Editor / International Wire Contributor", "exp": "6+ Years", "desc": "Directs newsroom photo coverage, commissions photo essays, wins national and international press awards."}
            ]
        },
        {
            "title": "Technical Writer & Documentation Architect",
            "short_name": "Technical Writer",
            "slug": "technical-writer-architect",
            "category": "Media, Journalism & Digital Marketing",
            "sub_category": "Technical Communication & Writing",
            "industry": "Software, Aerospace & Technology Documentation",
            "icon": "file-earmark-code",
            "short_description": "Translates complex software architectures, APIs, and engineering systems into clear user guides and developer docs.",
            "description": "Technical Writers and Documentation Architects bridge the gap between software engineers, system architects, and end-users. They transform complex source code, API frameworks, hardware schematics, and engineering whitepapers into crystal-clear developer documentation, SDK integration guides, user manuals, and online knowledge bases.",
            "what_they_do": "They write developer API documentation using Docs-as-Code workflows (Markdown, Git), create user troubleshooting manuals, write software release notes, and structure enterprise knowledge architecture.",
            "day_to_day_work": "• Testing software API endpoints and writing clear code request/response integration samples.\n• Collaborating with software engineering leads and product managers to document new product releases.\n• Writing structured developer documentation in Markdown and committing to GitHub repositories.\n• Creating flowcharts, architecture diagrams, and illustrated step-by-step configuration tutorials.\n• Auditing technical documentation clarity, consistency, and search engine findability.",
            "work_environment": "Software tech companies, cloud computing firms, aerospace manufacturing, remote home office.",
            "work_modes": "Remote / Hybrid / Office",
            "minimum_qualification": "Undergraduate (B.A. English / B.Tech / B.Sc Computer Science / Any Graduate with strong writing and technical aptitude)",
            "preferred_streams": "Any Stream (Computer Science or English Literature)",
            "required_subjects": "Technical Writing, English Communication, Basic Computer Systems",
            "technical_skills": "Docs-as-Code Workflow, Markdown, REST API Documentation, Git / GitHub, OpenAPI / Swagger, Information Architecture, DITA XML",
            "soft_skills": "Simplification of Complex Systems, Extreme Clarity of Thought, Analytical Inquisitiveness",
            "tools": "GitHub, Markdown, Swagger / Postman, Docusaurus, MadCap Flare, Confluence, Grammarly",
            "certifications": "Certified Professional Technical Communicator (CPTC) by STC, TWIN (Technical Writers India Network)",
            "experience_level": "Entry to Senior Level",
            "career_growth": "Advance to Senior Technical Writer, Documentation Manager, or Director of Developer Experience (DevRel).",
            "internship_roles": "Technical Writing Intern, Documentation Contributor in Open Source",
            "entry_level_roles": "Associate Technical Writer, Junior Documentation Specialist, Content Engineer",
            "average_salary": "₹6.0 - ₹16.0 LPA (Indicative range)",
            "salary_indicative": "Associate Technical Writer: ₹6.0 - 8.5 LPA | Senior Technical Writer (3-6 yrs): ₹10 - 16 LPA | Lead Documentation Architect / DevRel Lead (7+ yrs): ₹18 - 32+ LPA. Indicative figures from Indian IT and software product compensation benchmarks.",
            "future_scope": "Surging global demand as every software product, cloud API, and AI model requires comprehensive, developer-friendly documentation.",
            "government_opportunities": "ISRO, DRDO, National Informatics Centre (NIC technical documentation wings).",
            "private_opportunities": "Google India, Microsoft, Amazon Web Services (AWS), Atlassian, Adobe, Cisco, Razorpay, Freshworks, Postman.",
            "higher_study_options": "Master in Technical Communication, M.Sc in Information Systems.",
            "entrepreneurship_options": "Founding an independent technical documentation and developer content agency.",
            "source": "Society for Technical Communication (STC India) / TWIN",
            "official_url": "https://www.stc.org",
            "verification_status": "VERIFIED",
            "is_lesser_known": True,
            "career_family": "Media & Storytelling",
            "interest_clusters": "Writing, Technology, Language, Science",
            "work_style": "Office, Remote",
            "reality_check": "Not creative fiction writing: Demands absolute logical clarity, precise syntax, and zero ambiguity.\nRequires willingness to test software code, inspect API endpoints in Postman, and understand basic software architecture.\nExcellent, high-paying career path for humanities/literature graduates with an affinity for technology.",
            "next_steps": "Learn Markdown, Git basics, and explore API documentation tools like Swagger / Postman.\nContribute to open-source software documentation on GitHub (e.g. documentation pull requests).\nBuild a developer documentation portfolio demonstrating how to set up an API or software tool.",
            "courses": [{"course_id": 31, "type": "PRIMARY"}, {"course_id": 1, "type": "RELATED"}],
            "exams": [],
            "routes": [{"title": "Path A: Writing to Tech Route", "type": "PRIMARY", "steps": "B.A. English / B.Tech -> Learn Markdown & Git -> Open Source Docs Contributions -> Associate Technical Writer -> Doc Architect."}],
            "ladder": [
                {"stage": "Associate Technical Writer", "exp": "0-2 Years", "desc": "Drafts software release notes, writes user guides, edits engineering design documents for clarity."},
                {"stage": "Senior Technical Writer", "exp": "2-6 Years", "desc": "Authors comprehensive developer API documentation, builds code integration samples, manages Docs-as-Code pipelines."},
                {"stage": "Documentation Architect / DevRel Lead", "exp": "6+ Years", "desc": "Architects company-wide developer portals, directs technical communications, shapes developer adoption."}
            ]
        }
    ]

def get_creative_and_design_careers():
    return [
        {
            "title": "Industrial & Hardware Product Designer",
            "short_name": "Industrial Designer",
            "slug": "industrial-product-designer",
            "category": "Design, Animation & Creative Arts",
            "sub_category": "Industrial & Product Design",
            "industry": "Consumer Electronics, Automotive & Hardware Manufacturing",
            "icon": "palette",
            "short_description": "Designs physical consumer products, smart appliances, electric vehicles, and ergonomic hardware devices.",
            "description": "Industrial and Product Designers conceptualize, engineer, and refine physical products that millions of consumers interact with daily—including smartphones, wearable fitness trackers, electric scooters, medical devices, ergonomic office chairs, and kitchen appliances. They balance aesthetics, human ergonomics, material manufacturing processes, and user functionality.",
            "what_they_do": "They conduct user ethnographic research, sketch rapid concept forms, build physical foam prototypes, model 3D CAD parametric surfaces (Rhino, SolidWorks), select sustainable materials, and collaborate with manufacturing tooling engineers.",
            "day_to_day_work": "• Sketching dozens of ergonomic concept ideas with digital stylus on drawing tablets.\n• Building physical scale mockups using 3D printers, laser cutters, and high-density foam.\n• Creating Class-A surface CAD models in Rhino 3D or SolidWorks.\n• Conducting user ergonomics testing for grip comfort, tactile button feel, and weight balance.\n• Collaborating with injection molding toolmakers on draft angles and parting lines.",
            "work_environment": "Design studios, hardware tech prototyping workshops, automotive styling centers.",
            "work_modes": "Studio / Workshop / Hybrid",
            "minimum_qualification": "Undergraduate (Bachelor of Design - B.Des in Industrial / Product Design - 4 Years)",
            "preferred_streams": "Any Stream (Science, Arts, or Commerce)",
            "required_subjects": "Design Aptitude, Sketching, Physics / Materials",
            "technical_skills": "Design Thinking, Rapid Ideation Sketching, Ergonomics & Anthropometry, 3D CAD Modeling (SolidWorks/Rhino), Rapid 3D Prototyping, Materials & Manufacturing Processes (Injection Molding, Sheet Metal)",
            "soft_skills": "Spatial Visualization, Human-Centric Empathy, Aesthetic Sophistication, Cross-Functional Collaboration",
            "tools": "SolidWorks, Rhino 3D, KeyShot (3D Rendering), Wacom Cintiq Tablets, 3D Printers (FDM/SLA)",
            "certifications": "India Design Council Accreditation, B.Des from National Institute of Design (NID) / IIT IDC",
            "experience_level": "Entry to Senior Design Director",
            "career_growth": "Advance to Senior Industrial Designer, Head of Hardware Design, or Chief Design Officer (CDO).",
            "internship_roles": "Industrial Design Intern, Prototyping Workshop Trainee",
            "entry_level_roles": "Junior Industrial Designer, Hardware Product Stylist, CAD Design Associate",
            "average_salary": "₹6.0 - ₹18.0 LPA (Indicative range)",
            "salary_indicative": "Junior Product Designer (NID/IIT graduate): ₹6.0 - 9.5 LPA | Senior Industrial Designer (3-6 yrs): ₹11 - 18 LPA | Chief Design Officer / Principal Consultant: ₹22 - 45+ LPA. Indicative figures from design council surveys.",
            "future_scope": "Explosive growth as India emerges as a global hardware manufacturing powerhouse for electric vehicles, consumer electronics, and smart home appliances.",
            "government_opportunities": "National Institute of Design (NID), IIT Industrial Design Centres, Defence DRDO Human Engineering Labs.",
            "private_opportunities": "Tata Elxsi, Ather Energy, Titan Company, Havells India, Godrej & Boyce, Samsung Design India, Philips Innovation.",
            "higher_study_options": "Master of Design (M.Des in Industrial Design via CEED / NID DAT), Royal College of Art (RCA) London.",
            "entrepreneurship_options": "Founding an independent industrial design consultancy or launching a proprietary consumer hardware brand.",
            "source": "National Institute of Design (NID) / India Design Council",
            "official_url": "https://www.nid.edu",
            "verification_status": "VERIFIED",
            "is_lesser_known": False,
            "career_family": "Design & Aesthetics",
            "interest_clusters": "Design, Creativity, Machines, Hands-on, Art",
            "work_style": "Studio, Workshop",
            "reality_check": "Industrial design is about physical manufacturing constraints (mold draft angles, material strengths, cost), not just pretty digital sketches.\nRequires hands-on model making: getting your hands dirty in the workshop with sandpaper, foam, resin, and 3D printers.\nEntrance to top institutes (NID, IITs) requires clearing highly competitive creative design aptitude exams (NID DAT, UCEED).",
            "next_steps": "Practice daily observational sketching, human hand anatomy, and perspective drawing.\nPrepare for entrance exams: NID DAT (Design Aptitude Test) and UCEED (Undergraduate Common Entrance Examination for Design).\nBuild a physical creative design portfolio demonstrating sketching, problem solving, and hands-on making.",
            "courses": [{"course_id": 30, "type": "PRIMARY"}],
            "exams": [],
            "routes": [{"title": "Path A: NID / IIT Design Route", "type": "PRIMARY", "steps": "12th (Any Stream) -> NID DAT / UCEED -> B.Des in Industrial Design (4 yrs) -> Studio Internship -> Industrial Designer."}],
            "ladder": [
                {"stage": "Junior Industrial Designer", "exp": "0-2 Years", "desc": "Creates initial sketches, builds physical prototypes, refines 3D CAD parts for production."},
                {"stage": "Senior Industrial Designer", "exp": "2-6 Years", "desc": "Leads product form and ergonomics design for flagship appliances or EVs; works directly with manufacturing plants."},
                {"stage": "Head of Design / Chief Design Officer", "exp": "6+ Years", "desc": "Directs overall physical brand aesthetic, leads industrial design studio teams, wins global Red Dot design awards."}
            ]
        },
        {
            "title": "Fashion Designer & Couturier",
            "short_name": "Fashion Designer",
            "slug": "fashion-designer-couturier",
            "category": "Design, Animation & Creative Arts",
            "sub_category": "Fashion & Apparel Design",
            "industry": "Fashion, Haute Couture, Ready-to-Wear & Apparel Retail",
            "icon": "scissors",
            "short_description": "Creates original clothing, seasonal apparel collections, bridal couture, and sustainable textile garments.",
            "description": "Fashion Designers and Couturiers conceptualize and create complete apparel and clothing collections—ranging from high-end handcrafted bridal couture and luxury runway fashion to commercial ready-to-wear lines for mass retail brands. They forecast seasonal color and silhouette trends, source fabrics, master garment draping, patternmaking, and direct fashion shows.",
            "what_they_do": "They create thematic moodboards, sketch garment illustrations, drape fabrics on mannequins, develop production pattern templates, supervise sewing and embroidery craftsmanship, and manage collection launches.",
            "day_to_day_work": "• Researching international and traditional Indian fashion trends, weaves, and color palettes.\n• Sketching fashion figures and garment construction technical flats.\n• Sourcing silks, cottons, linens, and handwoven textiles from artisanal weavers.\n• Draping fabrics directly on dress forms and adjusting garment fits during live model trials.\n• Directing master tailors (karigars) on zardozi embroidery, seam finishes, and garment assembly.",
            "work_environment": "Fashion ateliers, garment design studios, apparel export houses, fashion week runways.",
            "work_modes": "Studio / Atelier / Workshop",
            "minimum_qualification": "Undergraduate (Bachelor of Design - B.Des in Fashion Design - 4 Years)",
            "preferred_streams": "Any Stream (Class 12 pass in Arts, Commerce, or Science)",
            "required_subjects": "Fashion Design, Patternmaking, Garment Construction, Textiles",
            "technical_skills": "Garment Draping, Flat Patternmaking, Fashion Illustration, Textile Knowledge, Trend Forecasting (WGSN), Tech Pack Creation, Adobe Illustrator",
            "soft_skills": "Aesthetic Vision, Color Sensibility, Attention to Fabric Fall, Creative Tenacity",
            "tools": "Dress Forms / Mannequins, Pattern Paper & Graders, Sewing Machines, Adobe Illustrator, CLO 3D",
            "certifications": "National Institute of Fashion Technology (NIFT) Degree, Fashion Design Council of India (FDCI) Membership",
            "experience_level": "Entry to Couture Director",
            "career_growth": "Advance to Senior Fashion Designer, Creative Director of Apparel Brand, or Celebrity Fashion Couturier.",
            "internship_roles": "Fashion Atelier Intern, Apparel Design Trainee",
            "entry_level_roles": "Assistant Fashion Designer, Junior Stylist, Apparel Tech Pack Designer",
            "average_salary": "₹4.5 - ₹15.0+ LPA (Indicative range)",
            "salary_indicative": "Assistant Designer post-NIFT: ₹4.5 - 7.5 LPA | Senior Designer in Retail Brand (3-6 yrs): ₹9 - 16 LPA | Independent Couture Label Owner / Creative Director: ₹18 - 50+ LPA. Indicative figures from NIFT placement reports and FDCI surveys.",
            "future_scope": "Continuous strong demand in India's massive wedding/festive couture market and the booming $100B domestic apparel retail industry.",
            "government_opportunities": "NIFT Faculty, Central Cottage Industries Corporation, Handlooms and Handicrafts Export Corporation.",
            "private_opportunities": "Aditya Birla Fashion (Pantaloons, Louis Philippe), Reliance Brands, Fabindia, Sabyasachi, Manish Malhotra, Anita Dongre, Zara India.",
            "higher_study_options": "Master of Design (M.Des in Fashion), International Fashion Master's (Polimoda Florence, Central Saint Martins).",
            "entrepreneurship_options": "Launching an independent sustainable fashion label, bespoke bridal atelier, or direct-to-consumer (D2C) clothing brand.",
            "source": "National Institute of Fashion Technology (NIFT) / FDCI",
            "official_url": "https://www.nift.ac.in",
            "verification_status": "VERIFIED",
            "is_lesser_known": False,
            "career_family": "Design & Aesthetics",
            "interest_clusters": "Design, Art, Creativity, Culture, Hands-on",
            "work_style": "Studio, Workshop",
            "reality_check": "Demands intense physical labor: Cutting fabric, pinning patterns, sewing muslins, and adjusting seams for hours on your feet.\nFashion is an intensely competitive industry: Success requires building a distinct aesthetic signature and understanding business pricing.\nEntrance to top national institutes (NIFT) requires clearing rigorous creative and general ability aptitude examinations.",
            "next_steps": "Practice daily fashion sketching, understanding human body proportions, and studying fabric textures.\nPrepare for the NIFT Entrance Examination (Creative Ability Test - CAT and General Ability Test - GAT).\nEnroll in a 4-year B.Des in Fashion Design at NIFT or accredited design institutions and build a graduation runway collection.",
            "courses": [{"course_id": 30, "type": "PRIMARY"}],
            "exams": [],
            "routes": [{"title": "Path A: NIFT Fashion Route", "type": "PRIMARY", "steps": "12th (Any Stream) -> NIFT Entrance Exam -> B.Des Fashion Design (4 yrs) -> Atelier Internship -> Assistant Designer -> Creative Director."}],
            "ladder": [
                {"stage": "Assistant Fashion Designer", "exp": "0-2 Years", "desc": "Prepares technical tech-packs, sources fabrics and buttons, assists in garment fitting sessions."},
                {"stage": "Fashion Designer / Category Lead", "exp": "2-6 Years", "desc": "Designs complete seasonal collections, manages runway showcase presentations, works with garment merchandisers."},
                {"stage": "Creative Director / Label Owner", "exp": "6+ Years", "desc": "Heads fashion house, dictates brand design philosophy, showcases at national and international Fashion Weeks."}
            ]
        }
    ]

def get_fine_arts_careers():
    return [
        {
            "title": "Art Conservator & Painting Restorer",
            "short_name": "Art Conservator",
            "slug": "art-conservator-restorer",
            "category": "Design, Animation & Creative Arts",
            "sub_category": "Fine Arts & Conservation",
            "industry": "Art Conservation, Museums & Heritage Preservation",
            "icon": "brush",
            "short_description": "Scientifically analyzes, repairs, and restores historical oil paintings, ancient murals, and paper artworks.",
            "description": "Art Conservators combine fine art craftsmanship with advanced analytical chemistry and materials science to preserve and restore deteriorating historical paintings, ancient frescoes, miniature manuscripts, and sculptures. They repair flaking paint layers, remove oxidized yellowed varnish, consolidate canvas tears, and arrest fungal decay adhering to reversible conservation ethics.",
            "what_they_do": "They examine paintings under ultraviolet and infrared reflectography, conduct chemical pigment cross-section testing, clean fragile surface varnishes, reline deteriorating canvases, and retouch paint losses invisibly.",
            "day_to_day_work": "• Examining paintings under UV fluorescence and surgical stereomicroscopes to detect old restorations.\n• Conducting solvent micro-swab testing to safely remove darkened 100-year-old varnish layers.\n• Consolidating flaking tempera or oil paint layers using reversible conservation adhesives (Beva 371).\n• In-painting and chromatic reintegration of paint losses using stable, non-yellowing conservation pigments.\n• Documenting every step of the restoration process with photographic and chemical analysis reports.",
            "work_environment": "Museum conservation laboratories, art restoration studios, ancient monument heritage sites.",
            "work_modes": "Lab / Studio / On-site",
            "minimum_qualification": "Postgraduate (M.A. / M.Sc in Art Conservation / Conservation of Cultural Property)",
            "preferred_streams": "Fine Arts (BFA) / Chemistry / History / Humanities",
            "required_subjects": "Fine Arts, Organic Chemistry, Art History",
            "technical_skills": "Micro-Chemical Testing, Stereomicroscopy, Varnish Removal, Canvas Relining, Pigment Identification, Chromatic In-Painting, Reversible Conservation Ethics",
            "soft_skills": "Surgical Fine Hand Dexterity, Infinite Patience, Respect for Original Art, Meticulous Precision",
            "tools": "Surgical Microscopes, UV Lamps, Heated Spatulas, Specialized Conservation Solvents, Fine Kolinsky Sable Brushes",
            "certifications": "National Museum Institute (NMI) Conservation Degree, Indian Association for the Study of Conservation of Cultural Property (IASC)",
            "experience_level": "Entry to Senior Conservator",
            "career_growth": "Advance to Senior Painting Conservator, Chief of Conservation in National Museum, or Private Art Consultant.",
            "internship_roles": "Conservation Lab Intern, Paper Conservation Trainee",
            "entry_level_roles": "Assistant Conservator, Junior Art Restorer, Conservation Scientist",
            "average_salary": "₹4.5 - ₹13.0 LPA (Indicative range)",
            "salary_indicative": "Assistant Conservator: ₹4.5 - 7 LPA | Conservator in Major Museum (3-7 yrs): ₹8 - 14 LPA | Independent Senior Conservator for High-Value Private Collections: ₹15 - 30+ LPA. Indicative figures from National Museum and heritage trusts.",
            "future_scope": "Growing rapidly as private art collectors, royal palace trusts, corporate collections, and national museums prioritize preserving invaluable art treasures.",
            "government_opportunities": "National Research Laboratory for Conservation of Cultural Property (NRLC Lucknow), National Museum New Delhi, National Gallery of Modern Art (NGMA).",
            "private_opportunities": "INTACH Art Conservation Centre, CSMVS Art Conservation Lab Mumbai, Alkazi Foundation, Private Art Auction Houses (Sotheby's, Christie's, Saffronart).",
            "higher_study_options": "Ph.D. in Conservation Science, International Fellowships (Getty Conservation Institute, Courtauld Institute London).",
            "entrepreneurship_options": "Establishing an independent art restoration studio catering to high-net-worth collectors, galleries, and auction houses.",
            "source": "National Museum Institute (NMI) / NRLC Lucknow",
            "official_url": "https://nmi.gov.in",
            "verification_status": "VERIFIED",
            "is_lesser_known": True,
            "career_family": "Design & Aesthetics",
            "interest_clusters": "Art, Science, History, Hands-on, Culture",
            "work_style": "Lab, Studio",
            "reality_check": "Conservation is scientific preservation, NOT repainting: The golden ethical rule is reversibility—any restored paint must be easily removable by future conservators.\nDemands hours of intense microscopic manual focus using scalpels and micro-swabs under surgical magnification.\nRequires deep respect for history: you are touching and restoring original works by centuries-old masters.",
            "next_steps": "Complete a Bachelor of Fine Arts (BFA) or Bachelor's in Chemistry/History.\nEnroll in M.A. in Conservation of Works of Art at National Museum Institute (NMI New Delhi) or accredited universities.\nComplete practical apprenticeships at recognized conservation laboratories (e.g. INTACH or CSMVS Mumbai).",
            "courses": [{"course_id": 58, "type": "PRIMARY"}, {"course_id": 13, "type": "RELATED"}],
            "exams": [],
            "routes": [{"title": "Path A: Fine Arts to Conservation", "type": "PRIMARY", "steps": "BFA Painting / B.Sc Chemistry -> M.A. Art Conservation (NMI) -> Conservation Internship -> Assistant Conservator -> Master Restorer."}],
            "ladder": [
                {"stage": "Assistant Conservator", "exp": "0-3 Years", "desc": "Prepares chemical solutions, carries out surface cleaning, cleans paper prints and textiles under supervision."},
                {"stage": "Painting Conservator", "exp": "3-8 Years", "desc": "Independently restores damaged oil and canvas paintings, treats tears, executes microscopic chromatic reintegration."},
                {"stage": "Chief Conservator / Laboratory Head", "exp": "8+ Years", "desc": "Directs museum conservation laboratories, oversees preservation of national art treasures, authenticates antiquities."}
            ]
        }
    ]

def get_performing_arts_careers():
    return [
        {
            "title": "Professional Classical Dancer",
            "short_name": "Classical Dancer",
            "slug": "classical-dancer",
            "category": "Design, Animation & Creative Arts",
            "sub_category": "Performing Arts & Dance",
            "industry": "Classical Arts, Dance Performance & Cultural Diplomacy",
            "icon": "music-note",
            "short_description": "Performs classical Indian dance traditions (Kathak, Bharatanatyam, Odissi) on national and global stages.",
            "description": "Professional Classical Dancers are dedicated performing artists trained in one of India's classical dance traditions recognized by the Sangeet Natak Akademi (such as Bharatanatyam, Kathak, Odissi, Kathakali, Kuchipudi, or Manipuri). Grounded in the Natyashastra, they master complex rhythmic footwork (Tala), expressive mime (Abhinaya), and convey deep philosophical and emotional narratives.",
            "what_they_do": "They practice daily physical riyaz (rigorous body conditioning), choreograph classical recitals, perform solo and ensemble productions at prestigious dance festivals, tour internationally, and teach disciples.",
            "day_to_day_work": "• Conducting daily 3-4 hour rigorous dance physical conditioning and rhythmic footwork practice (Riyaz).\n• Rehearsing expressive facial abhinaya and hand mudras based on classical poetry and Sanskrit slokas.\n• Collaborating with live classical accompanists (Mridangam / Pakhawaj, Violin, Carnatic / Hindustani vocalists).\n• Performing headline evening recitals at national and international dance festivals.\n• Conducting masterclasses and training young disciples in the traditional Guru-Shishya parampara.",
            "work_environment": "Performance auditoriums, dance studios, cultural centers, national festivals.",
            "work_modes": "Studio / Stage / Touring",
            "minimum_qualification": "Formal Training under Master Gurus + Bachelor of Performing Arts (BPA / B.Dance - 3-4 Years)",
            "preferred_streams": "Any Stream (Lifelong artistic passion and rigorous training matter most)",
            "required_subjects": "Dance Theory (Natyashastra, Abhinaya Darpana), Rhythms (Tala), Music",
            "technical_skills": "Classical Footwork & Speed, Abhinaya (Expressive Acting), Tala & Rhythmic Complexity, Choreography, Stage Production, Costume & Aharya",
            "soft_skills": "Immense Physical Stamina, Emotional Expressiveness, Guru-Bhakti & Humility, Stage Presence",
            "tools": "Ghungroos (Dancing Bells), Dance Studio Mirrors, Audio Sound Systems, Classical Stage Costumes",
            "certifications": "Doordarshan / ICCR Empaneled Artist ('A' / 'Top' Grade), Sangeet Natak Akademi Recognition",
            "experience_level": "Debuting Artist (Arangetram / Manch Pravesh) to Renowned Guru",
            "career_growth": "Advance to Nationally Acclaimed Soloist, Choreographer of Dance Ensembles, and Founder of Dance Academy.",
            "internship_roles": "Apprentice in Dance Company, Guru Shishya Trainee",
            "entry_level_roles": "Junior Ensemble Dancer, Solo Performer, Dance Teacher",
            "average_salary": "₹3.5 - ₹15.0+ LPA (Performance & Teaching Model)",
            "salary_indicative": "Ensemble Dancer / Junior Performer: ₹3.5 - 6 LPA | Empaneled Festival Performer: ₹7 - 12 LPA (Performance fees ₹25,000 - ₹1,50,000 per concert) | Renowned Master Artist / Academy Director: ₹15 - 35+ LPA through international tours and workshops. Indicative figures from performing arts circles.",
            "future_scope": "Growing global appreciation through ICCR cultural diplomacy tours, national cultural festivals (Khajuraho, Konark), and expanding dance academies worldwide.",
            "government_opportunities": "Indian Council for Cultural Relations (ICCR Cultural Ambassadors), Sangeet Natak Akademi, Kalakshetra Foundation, Kathak Kendra New Delhi, State Cultural Academies.",
            "private_opportunities": "Independent Dance Troupes, International Arts Residencies, University Dance Departments, Private Dance Academies.",
            "higher_study_options": "Master of Performing Arts (MPA), Ph.D. in Dance Jurisprudence / Dance Studies.",
            "entrepreneurship_options": "Founding an independent classical dance academy, cultural residency center, or international touring dance company.",
            "source": "Sangeet Natak Akademi / ICCR",
            "official_url": "https://sangeetnatak.gov.in",
            "verification_status": "VERIFIED",
            "is_lesser_known": False,
            "career_family": "Performing Arts",
            "interest_clusters": "Art, Culture, Creativity, People, Movement",
            "work_style": "Studio, Stage, Travel",
            "reality_check": "Requires 8 to 12+ years of disciplined daily training starting from childhood or youth under master gurus.\nPhysical demands equal those of professional athletes: requires peak cardiovascular stamina, flexibility, and footwork speed.\nIncome in early career is built by combining solo festival performances with running a dance teaching academy.",
            "next_steps": "Dedicate yourself to rigorous daily practice under a recognized Guru or enroll in a Bachelor of Performing Arts (BPA).\nPrepare for your formal solo stage debut (Arangetram / Manch Pravesh).\nApply for grading and empanelment with Doordarshan, Ministry of Culture Senior/Junior Fellowships, and ICCR.",
            "courses": [{"course_id": 59, "type": "PRIMARY"}],
            "exams": [],
            "routes": [{"title": "Path A: Classical Gurukul to Stage", "type": "PRIMARY", "steps": "Rigorous Guru Training / BPA -> Arangetram Solo Debut -> ICCR Empanelment -> National Festival Performer -> Dance Guru."}],
            "ladder": [
                {"stage": "Emerging Dancer / Ensemble Artist", "exp": "0-4 Years", "desc": "Performs in guru's dance productions, tours in group choreography, performs initial solo recitals."},
                {"stage": "Established Solo Performer", "exp": "4-12 Years", "desc": "Headlines national dance festivals (Khajuraho, Konark, Music Academy), tours internationally with ICCR."},
                {"stage": "Master Choreographer & Guru", "exp": "12+ Years", "desc": "Directs dance academies, choreographs major ballets, receives national honors (Sangeet Natak Akademi Award)."}
            ]
        }
    ]

def get_film_and_entertainment_careers():
    return [
        {
            "title": "Director of Photography (Cinematographer)",
            "short_name": "Cinematographer",
            "slug": "cinematographer-dop",
            "category": "Design, Animation & Creative Arts",
            "sub_category": "Film & Entertainment",
            "industry": "Feature Films, OTT Series, Documentaries & Commercials",
            "icon": "camera-reels",
            "short_description": "Controls camera framing, cinematic lighting, and visual moods for feature films, web series, and commercials.",
            "description": "Directors of Photography (DoPs / Cinematographers) are the chief visual architects of motion pictures. Working in intimate creative collaboration with the Film Director, they translate script emotions into moving visual imagery. They select cinema cameras and lenses, design elaborate lighting schemes, determine camera movements, and oversee camera and grip crews.",
            "what_they_do": "They design lighting setups, choose cinema camera sensor formats and anamorphic/spherical lenses, operate camera dollies and gimbals, supervise gaffers and camera operators, and direct digital color grading.",
            "day_to_day_work": "• Breaking down screenplay scenes into visual shot lists and lighting moodboards with the Director.\n• Directing the gaffer and electric crew on setting up key, fill, and rim cinematic lighting.\n• Calibrating camera exposure, color temperature, and depth-of-field on high-end cinema cameras.\n• Operating camera movements on dollies, cranes, Steadicam rigs, or shoulder-mounted setups.\n• Supervising the final digital color grading (DI) session with the colorist in post-production.",
            "work_environment": "Film sets, soundstages, outdoor remote film locations, post-production color suites.",
            "work_modes": "On-site / Film Set / Location",
            "minimum_qualification": "Undergraduate (FTII / SRFTI Diploma in Cinematography or B.Sc in Cinema / Mass Media)",
            "preferred_streams": "Any Stream (Visual eye, camera understanding, and lighting passion matter most)",
            "required_subjects": "Cinematography, Visual Optics, Film Lighting, Art of Motion Pictures",
            "technical_skills": "Cinema Camera Operation (ARRI Alexa, RED, Sony Venice), Lighting Theory, Optical Lens Characteristics (Anamorphic vs Spherical), Camera Movement (Gimbals, Dollies), Color Grading (DaVinci Resolve)",
            "soft_skills": "Visual Poetry, Decisive Set Leadership, High Stamina, Creative Problem Solving",
            "tools": "ARRI Alexa Mini LF, RED V-Raptor, Master Prime Lenses, Light Meters, DaVinci Resolve, Teradek Wireless",
            "certifications": "Indian Society of Cinematographers (ISC) Membership, Western India Cinematographers Association (WICA)",
            "experience_level": "Camera Assistant to Leading DoP",
            "career_growth": "Advance from Focus Puller / 1st AC to Camera Operator, Independent DoP, and Renowned Feature Film Cinematographer.",
            "internship_roles": "Camera Department Trainee, 2nd Assistant Camera (2nd AC)",
            "entry_level_roles": "1st Assistant Camera (Focus Puller), Camera Operator, Music Video DoP",
            "average_salary": "₹6.0 - ₹25.0+ LPA (Day-Rate Project Model)",
            "salary_indicative": "Camera Assistant: ₹3.5 - 6 LPA | Independent Web Series / Indie DoP: ₹8 - 18 LPA | Leading Feature Film / Commercials DoP: ₹25 - 60+ LPA (Day rates ₹50,000 - ₹2,50,000 per shoot day). Indicative figures from WICA and film industry surveys.",
            "future_scope": "Explosive demand with the proliferation of cinematic OTT streaming series (Netflix, Prime Video, Hotstar), feature films, and big-budget commercials.",
            "government_opportunities": "Films Division of India, Doordarshan, National Film Development Corporation (NFDC).",
            "private_opportunities": "Feature Film Production Houses (Dharma Productions, Yash Raj Films, Excel Entertainment), OTT Networks, Top Ad Commercial Agencies.",
            "higher_study_options": "Specialized Post-Graduate Diploma at Film and Television Institute of India (FTII Pune) or Satyajit Ray Film & Television Institute (SRFTI).",
            "entrepreneurship_options": "Founding an independent cinema equipment rental house or commercial production boutique.",
            "source": "Film and Television Institute of India (FTII) / Indian Society of Cinematographers (ISC)",
            "official_url": "https://www.ftii.ac.in",
            "verification_status": "VERIFIED",
            "is_lesser_known": False,
            "career_family": "Media & Storytelling",
            "interest_clusters": "Art, Creativity, Media, Technology, Hands-on",
            "work_style": "Studio, Outdoor, Travel",
            "reality_check": "Involves exhausting 12 to 16-hour shooting shifts on film sets in extreme environments (rain, deserts, freezing nights).\nCinematography is fundamentally about LIGHTING, not just pointing a camera: mastering shadows and lighting fixtures is 80% of the craft.\nRequires starting at the bottom as a camera trainee or focus puller before getting trusted with multi-crore film budgets.",
            "next_steps": "Learn manual photography exposure, prime lenses, and experiment with cinema lighting techniques.\nApply for the 3-year Cinematography Diploma at premier institutes like FTII Pune or SRFTI Kolkata via JET exam.\nApprentice under established Directors of Photography as a camera assistant to build set experience.",
            "courses": [{"course_id": 57, "type": "PRIMARY"}],
            "exams": [],
            "routes": [{"title": "Path A: FTII Cinematography Route", "type": "PRIMARY", "steps": "Any Degree -> FTII JET Entrance Exam -> 3-Yr Cinematography Diploma -> Assistant Camera -> Independent DoP."}],
            "ladder": [
                {"stage": "Camera Trainee / 1st AC (Focus Puller)", "exp": "0-3 Years", "desc": "Maintains camera lenses, pulls critical focus on fast-moving actors during live takes."},
                {"stage": "Independent DoP (Commercials & Music Videos)", "exp": "3-7 Years", "desc": "Shoots TV commercials, indie films, and music videos; designs original lighting aesthetics."},
                {"stage": "Leading Feature Film / OTT DoP", "exp": "7+ Years", "desc": "Commands visual design of big-budget feature films and OTT series, nominated for National Film Awards."}
            ]
        }
    ]
