"""
scripts/catalog_builder_part12.py
Final 6 careers bringing total to exactly 126 authentic careers.
"""

def get_final_6_careers():
    return [
        {
            "title": "Precision Agriculture & Agri-Tech Specialist",
            "short_name": "Agri-Tech Specialist",
            "slug": "precision-agri-tech-specialist",
            "category": "Agriculture, Food Technology & Environment",
            "sub_category": "AgriTech & Smart Farming",
            "industry": "Agriculture & Technology",
            "icon": "cpu",
            "short_description": "Deploys agricultural drones, IoT soil moisture sensors, satellite imagery, and AI to optimize farm yields and resource conservation.",
            "description": "Precision Agriculture Specialists deploy cutting-edge technological tools into farming. They fly multispectral agricultural drones to detect crop stress, configure IoT soil moisture sensors for automated drip irrigation, and use satellite data to map farm fertility.",
            "what_they_do": "They operate agricultural drones for targeted pesticide and fertilizer spraying, calibrate IoT soil telemetry nodes, analyze satellite NDVI vegetative indices, and train farmers on digital farm management applications.",
            "day_to_day_work": "• Piloting DGCA-certified agricultural drones for precise nano-urea spraying.\n• Analyzing multispectral drone imagery to calculate NDVI crop health indices.\n• Installing and maintaining wireless IoT soil moisture and weather stations in farm fields.\n• Interpreting satellite soil moisture maps and designing variable rate application (VRA) maps.\n• Advising corporate farms and farmer producer organizations (FPOs) on yield optimization.",
            "work_environment": "Commercial smart farms, agricultural technology startups, greenhouse facilities.",
            "work_modes": "Field Engineering / Drone Flights / Farm Office",
            "minimum_qualification": "Undergraduate (B.Tech Agricultural Engg / B.Sc Agri + Drone Pilot License)",
            "preferred_streams": "Science (PCM / PCB)",
            "required_subjects": "Agriculture, Physics, Computer Applications",
            "technical_skills": "Drone Piloting (DGCA RPC), GIS & Remote Sensing, IoT Sensor Calibration, Multispectral Image Processing (NDVI), Python/QGIS, Variable Rate Application",
            "soft_skills": "Technological Practicality, Rural Adaptability, Problem Solving, Farmer Communication",
            "tools": "Agricultural Drones (Kisan Drones), QGIS, Pix4D, IoT Soil Sensors, Weather Stations",
            "certifications": "DGCA Remote Pilot Certificate (RPC), Precision Agriculture Certification",
            "experience_level": "Entry-Level to Senior",
            "career_growth": "Rapid growth with progression to Head of AgriTech Solutions, Precision Farming Director, or Agri-Drone Startup Founder.",
            "internship_roles": "AgriTech Drone Intern, Precision Farming Trainee",
            "entry_level_roles": "Precision Agriculture Specialist, Agri-Drone Pilot, Smart Farming Associate",
            "average_salary": "₹4.5 - ₹12 LPA (Indicative range)",
            "salary_indicative": "Entry-Level Specialist (0-2 yrs): ₹4 - 6 LPA | Senior AgriTech Lead (3-6 yrs): ₹7.5 - 14 LPA | Head of AgriTech (7+ yrs): ₹18 - 36+ LPA. Indicative figures from AgriTech India Association 2024.",
            "future_scope": "Explosive national growth powered by the Sub-Mission on Agricultural Mechanization (SMAM), Kisan Drone subsidies, and smart agriculture missions.",
            "government_opportunities": "ICAR Precision Farming Centers, State Agriculture Drone Missions, Krishi Vigyan Kendras.",
            "private_opportunities": "DeHaat, Ninjacart, Fasal, Garuda Aerospace, IoTechWorld, Mahindra Agri Solutions, Bayer CropScience.",
            "higher_study_options": "M.Tech in Farm Machinery & Power Engineering / Remote Sensing & GIS.",
            "entrepreneurship_options": "Custom hiring drone spraying enterprise, farm IoT telemetry consulting firm.",
            "source": "Ministry of Agriculture & Farmers Welfare / ICAR",
            "official_url": "https://agricoop.nic.in",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 7, "type": "DIRECT"}, {"course_id": 9, "type": "COMMON"}],
            "exams": [{"exam_id": 95, "importance": "PRIMARY"}],
            "routes": [{"title": "Path A: Agriculture / Engineering to AgriTech", "type": "COMMON", "steps": "B.Sc Agriculture / B.Tech Agri Engg -> Earn DGCA Remote Pilot Certificate (RPC) -> Master QGIS & Drone Analytics -> AgriTech Specialist."}],
            "ladder": [
                {"stage": "Agri-Drone Pilot / Field Technician", "exp": "0-2 Years", "desc": "Operates spray drones, maps village farm clusters, logs sensor telemetry."},
                {"stage": "Precision Farming Specialist", "exp": "2-5 Years", "desc": "Generates variable rate fertilizer prescriptions, advises 100+ FPO farm clusters."},
                {"stage": "Head of AgriTech Solutions", "exp": "5-8 Years", "desc": "Manages enterprise digital agriculture contracts across thousands of acres."},
                {"stage": "VP of Technology / Smart Agriculture Founder", "exp": "8+ Years", "desc": "Heads autonomous farm equipment commercialization and AI crop models."}
            ],
            "roadmaps": {
                "Class 10": "Focus on science, computer applications, and modern farming methods.",
                "Class 12": "Choose Science (PCM or PCB) for Class 12 board exams.",
                "Graduation": "Complete B.Sc Agriculture or B.Tech Agricultural Engineering. Learn drone piloting at a DGCA-authorized drone school.",
                "Working Professional": "Master multispectral image processing (Pix4D) and variable rate technology for commercial farming."
            }
        },
        {
            "title": "Environmental Impact Assessor",
            "short_name": "EIA Assessor",
            "slug": "environmental-impact-assessor",
            "category": "Agriculture, Food Technology & Environment",
            "sub_category": "Environmental Governance & Impact Assessment",
            "industry": "Environmental Consulting & Regulatory Auditing",
            "icon": "shield-shaded",
            "short_description": "Evaluates the environmental impact of major infrastructure projects (highways, mines, ports, dams) for statutory government clearances.",
            "description": "Environmental Impact Assessors evaluate how large-scale industrial and infrastructure developments will affect air quality, water bodies, wildlife habitats, and local human communities. Under the Environment Protection Act 1986, they author mandatory EIA reports.",
            "what_they_do": "They collect baseline environmental data, model pollutant dispersion, predict ecological disturbances, design Environmental Management Plans (EMP), and represent projects during public hearings.",
            "day_to_day_work": "• Measuring baseline air quality, groundwater levels, and noise levels around project sites.\n• Modeling air emission dispersion using AERMOD and water discharge dilution.\n• Conducting socio-economic surveys and rehabilitation assessments for project-affected families.\n• Drafting comprehensive Environmental Impact Assessment (EIA) and EMP reports.\n• Presenting findings before State Expert Appraisal Committees (SEAC) for clearance.",
            "work_environment": "Environmental consultancies, industrial project sites, government appraisal committee hearings.",
            "work_modes": "On-site / Field Sampling / Regulatory Office",
            "minimum_qualification": "Postgraduate (M.Sc Environmental Science / M.Tech Environmental Engg)",
            "preferred_streams": "Science (PCM / PCB)",
            "required_subjects": "Environmental Science, Chemistry, Biology",
            "technical_skills": "EIA Notification 2006, Environmental Management Plans (EMP), Air/Water Quality Modeling, Public Hearing Procedures, Environmental Law, Biodiversity Mapping",
            "soft_skills": "Rigorous Objectivity, Public Presentation, Analytical Precision, Scientific Integrity",
            "tools": "AERMOD, QGIS, Water Sampling Equipment, Sound Level Meters, High-Volume Air Samplers",
            "certifications": "EIA Coordinator (QCI-NABET Accredited) in specific industrial sectors",
            "experience_level": "Entry-Level to Senior",
            "career_growth": "Broad consulting path progressing to Functional Area Expert (FAE), EIA Coordinator, or Environmental Director.",
            "internship_roles": "EIA Trainee, Environmental Field Sampling Intern",
            "entry_level_roles": "Junior Environmental Consultant, Field Sampling Specialist",
            "average_salary": "₹4.5 - ₹13 LPA (Indicative range)",
            "salary_indicative": "Entry-Level Consultant (0-2 yrs): ₹4 - 6 LPA | NABET EIA Coordinator (3-6 yrs): ₹8 - 16 LPA | Director of Environmental Clearances (7+ yrs): ₹20 - 45+ LPA. Indicative figures from QCI-NABET 2024.",
            "future_scope": "Mandatory statutory requirement under the Environment Protection Act for every highway, mine, airport, power plant, and township.",
            "government_opportunities": "Ministry of Environment, Forest and Climate Change (MoEFCC), Expert Appraisal Committees (EAC), Central Pollution Control Board (CPCB).",
            "private_opportunities": "Tata Consulting Engineers, ERM India, WAPCOS, Jacobs, AECOM, certified NABET environmental consultancies.",
            "higher_study_options": "Ph.D. in Environmental Science, Post Graduate Diploma in Environmental Law (NLSIU).",
            "entrepreneurship_options": "QCI-NABET accredited environmental consultancy, environmental testing laboratory.",
            "source": "Quality Council of India (QCI-NABET) / MoEFCC",
            "official_url": "https://nabet.qci.org.in",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 3, "type": "COMMON"}, {"course_id": 12, "type": "COMMON"}],
            "exams": [{"exam_id": 79, "importance": "PRIMARY"}],
            "routes": [{"title": "Path A: Environmental Science to NABET Coordinator", "type": "COMMON", "steps": "B.Sc -> M.Sc Environmental Science / Chemistry -> Join NABET consultancy -> Complete sectoral audits -> QCI-NABET Accredited EIA Coordinator."}],
            "ladder": [
                {"stage": "Junior Environmental Consultant", "exp": "0-2 Years", "desc": "Samples air and water quality, conducts baseline surveys, assists in drafting EMP chapters."},
                {"stage": "Functional Area Expert (FAE - NABET)", "exp": "2-5 Years", "desc": "Approved by QCI in specific sectors (Air Pollution, Ecology, Water), presents at public hearings."},
                {"stage": "EIA Coordinator (NABET Accredited)", "exp": "5-8 Years", "desc": "Legally signs off on environmental clearance submissions before MoEFCC Expert Appraisal Committees."},
                {"stage": "Director of Environmental Clearances", "exp": "8+ Years", "desc": "Directs environmental compliance for multi-billion-dollar national infrastructure megaprojects."}
            ],
            "roadmaps": {
                "Class 10": "Focus on ecology, chemistry, and environmental balance.",
                "Class 12": "Choose Science with Chemistry and Biology/Maths.",
                "Graduation": "Complete B.Sc and M.Sc in Environmental Science or Civil/Chemical Engineering.",
                "Working Professional": "Clear QCI-NABET accreditation interviews to become a certified Functional Area Expert (FAE) and EIA Coordinator."
            }
        },
        {
            "title": "Aviation Operations Coordinator",
            "short_name": "Aviation Operations Coordinator",
            "slug": "aviation-operations-coordinator",
            "category": "Aviation, Logistics & Supply Chain",
            "sub_category": "Airport Ground Operations & Dispatch",
            "industry": "Commercial Aviation & Airports",
            "icon": "airplane-engines",
            "short_description": "Coordinates aircraft turnaround, ramp safety, baggage logistics, fueling, and passenger boarding at airport terminals.",
            "description": "Aviation Operations Coordinators are the nerve center of airport tarmac and terminal operations. They orchestrate aircraft turnarounds in 25-45 minutes: coordinating fueling, catering, baggage handling, pushback tugs, and passenger boarding.",
            "what_they_do": "They manage aircraft turnaround milestones, coordinate with flight dispatchers and gate agents, ensure ramp safety adhering to DGCA regulations, and handle flight delay recovery operations.",
            "day_to_day_work": "• Monitoring on-time performance (OTP) and turnarounds from the Airport Operations Control Centre (AOCC).\n• Inspecting tarmac ramps for Foreign Object Debris (FOD) and safety hazards.\n• Coordinating passenger boarding, baggage loading balance, and fueling schedules.\n• Liaising with Air Traffic Control (ATC) and ground handling agencies.\n• Managing emergency operations during weather diversions and mechanical delays.",
            "work_environment": "Airport terminals, tarmac ramp control centers, Airport Operations Control Centers (AOCC).",
            "work_modes": "On-site / Airport Shift Rotations / 24x7 Operations",
            "minimum_qualification": "Undergraduate (BBA Aviation / Any Degree)",
            "preferred_streams": "Any Stream",
            "required_subjects": "Aviation Management, English, Mathematics",
            "technical_skills": "Aircraft Turnaround Management, Airport Ramp Safety, DGCA Safety Standards, Flight Operations Dispatch, Baggage Reconciliation, AOCC Systems",
            "soft_skills": "Crisis Composure, Fast Coordination Under Pressure, Communication, Situational Awareness",
            "tools": "Airport Collaborative Decision Making (A-CDM) Software, Ramp Radios, Flight Info Displays",
            "certifications": "IATA Airport Operations Diploma, DGCA Ramp Safety Certification",
            "experience_level": "Entry-Level to Senior",
            "career_growth": "Direct progression to Duty Terminal Manager (DTM), Head of Airport Operations, or Chief Operating Officer (Airport).",
            "internship_roles": "Airport Ground Operations Intern, Airline Station Trainee",
            "entry_level_roles": "Ramp Operations Associate, Customer Service Officer, Flight Operations Assistant",
            "average_salary": "₹4 - ₹11 LPA (Indicative range)",
            "salary_indicative": "Operations Associate (0-2 yrs): ₹3.5 - 5 LPA | Duty Terminal Manager (3-6 yrs): ₹7 - 14 LPA | Head of Airport Operations (7+ yrs): ₹18 - 38+ LPA. Indicative figures from GMR & AAI Airport Audits 2024.",
            "future_scope": "Rapid growth as India builds dozens of greenfield international airports (Jewar, Navi Mumbai, Bhogapuram) and passenger traffic doubles.",
            "government_opportunities": "Airports Authority of India (AAI Operations), State Airport Infrastructure Development Corporations.",
            "private_opportunities": "IndiGo Operations, Air India, GMR Group (Delhi/Hyderabad Airports), Adani Airports, Menzies Aviation, AISATS.",
            "higher_study_options": "MBA in Aviation Management, IATA Senior Airport Management Diplomas.",
            "entrepreneurship_options": "Aviation ground support equipment leasing, airport hospitality and VIP concierge agency.",
            "source": "Airports Authority of India (AAI) / IATA",
            "official_url": "https://www.aai.aero",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 17, "type": "COMMON"}, {"course_id": 18, "type": "ALTERNATIVE"}],
            "exams": [{"exam_id": 79, "importance": "PRIMARY"}],
            "routes": [{"title": "Path A: Aviation Management to Airport Operations", "type": "COMMON", "steps": "BBA Aviation / Any Graduation -> IATA Airport Operations certification -> Airline / Airport Ground Handling hire -> Operations Coordinator."}],
            "ladder": [
                {"stage": "Ramp Operations Associate", "exp": "0-2 Years", "desc": "Coordinates aircraft pushback, monitors fueling, ensures baggage loading balance."},
                {"stage": "Station Operations Coordinator", "exp": "2-5 Years", "desc": "Manages on-time performance (OTP) for 50+ daily flights, resolves gate conflicts."},
                {"stage": "Duty Terminal Manager (DTM)", "exp": "5-8 Years", "desc": "Heads terminal operations during shift, manages emergency diversions and VIP protocols."},
                {"stage": "Head of Airport Operations (AOCC)", "exp": "8+ Years", "desc": "Directs overall airport airside and terminal operations for millions of passengers."}
            ],
            "roadmaps": {
                "Class 10": "Develop interest in airlines, airports, and logistics coordination.",
                "Class 12": "Complete Class 12 in any stream of your choice.",
                "Graduation": "Complete BBA Aviation or any degree. Earn the IATA Airport Operations diploma and intern at a major airport.",
                "Working Professional": "Master Airport Collaborative Decision Making (A-CDM) systems and crisis management."
            }
        },
        {
            "title": "Merchant Navy Officer / Marine Chief Engineer",
            "short_name": "Merchant Navy Officer",
            "slug": "merchant-navy-officer",
            "category": "Aviation, Logistics & Supply Chain",
            "sub_category": "Maritime Navigation & Marine Engineering",
            "industry": "Commercial Shipping & Global Maritime Transport",
            "icon": "water",
            "short_description": "Commands commercial container ships, oil tankers, and bulk carriers navigating international ocean trade lanes.",
            "description": "Merchant Navy Officers command commercial ocean vessels carrying 90% of global trade. Deck Officers navigate container ships and manage vessel safety; Marine Engineers operate massive marine diesel engines, power generators, and desalination systems.",
            "what_they_do": "They navigate ocean ships using electronic charts (ECDIS) and celestial navigation, maintain marine diesel propulsion engines, manage cargo loading and ballast balance, and handle high-seas navigation safety adhering to IMO regulations.",
            "day_to_day_work": "• Navigating ocean vessels on the bridge using radar, ECDIS, and GPS.\n• Monitoring cargo holds (container lashings, crude oil pumps, grain stability).\n• Operating and overhauling 2-stroke marine diesel propulsion engines.\n• Conducting fire safety and lifeboat drills complying with SOLAS treaties.\n• Managing ship clearance with international port authorities.",
            "work_environment": "Commercial container ships, oil tankers, bulk carriers, ship engine control rooms.",
            "work_modes": "At Sea / Contract Rotations (typically 4-6 months at sea, followed by 2-3 months paid vacation)",
            "minimum_qualification": "Class 12 (PCM 60%+) + B.Sc Nautical Science / B.Tech Marine Engineering",
            "preferred_streams": "Science (PCM)",
            "required_subjects": "Physics, Mathematics, Chemistry",
            "technical_skills": "Marine Navigation (ECDIS, Radar/ARPA), Marine Diesel Engines, Ballast Water Management, Ship Stability, SOLAS & MARPOL Conventions, Celestial Navigation",
            "soft_skills": "High Mental Resilience, Seamanship Leadership, Strict Discipline, Physical Fitness",
            "tools": "ECDIS Electronic Charts, Marine Radars, Engine Telegraph, Bunkering Systems, Sextant",
            "certifications": "Certificate of Competency (CoC) issued by Directorate General of Shipping (DGS India) / IMO",
            "experience_level": "Deck / Engine Cadet to Captain (Master Mariner) / Chief Engineer",
            "career_growth": "Highly lucrative international trajectory progressing to Chief Mate, Captain (Master Mariner), or Marine Superintendent.",
            "internship_roles": "Sea-Time Cadet Training (12-18 Months Sea Service)",
            "entry_level_roles": "Third Officer (Deck) / Fourth Engineer (Engine), Deck Cadet",
            "average_salary": "₹12 - ₹35 LPA (Indicative range - tax-free under Non-Resident Indian - NRI maritime tax regulations)",
            "salary_indicative": "Junior Officer (0-3 yrs): ₹10 - 18 LPA | Chief Officer / Second Engineer (3-6 yrs): ₹24 - 45 LPA | Captain / Chief Engineer (7+ yrs): ₹50 - 1.2 Crore/year (tax-free in USD under NRI criteria). Indicative figures from DG Shipping & Shipping Lines 2024.",
            "future_scope": "Permanent, vital global carrier role as global maritime trade expands and ships adopt green methanol and LNG propulsion.",
            "government_opportunities": "Shipping Corporation of India (SCI), Directorate General of Shipping (DGS), Port Trusts (Marine Pilots).",
            "private_opportunities": "Maersk Line, Mediterranean Shipping Company (MSC), Anglo-Eastern, Teekay Tankers, Synergy Marine Group, Fleet Management.",
            "higher_study_options": "Master Mariner / Chief Engineer CoC examinations, Master's in Maritime Law.",
            "entrepreneurship_options": "Ship crewing agency, maritime technical surveying firm, marine safety equipment servicing.",
            "source": "Directorate General of Shipping (DGS India) / Indian Maritime University (IMU)",
            "official_url": "https://www.dgshipping.gov.in",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 11, "type": "COMMON"}, {"course_id": 2, "type": "COMMON"}],
            "exams": [{"exam_id": 8, "importance": "ALTERNATIVE"}],
            "routes": [
                {"title": "Path A: IMU-CET Nautical Science Route (Deck Side)", "type": "COMMON", "steps": "Class 12 (PCM 60%+) -> IMU-CET Examination -> B.Sc Nautical Science (3 yrs) at Indian Maritime University -> 12 Months Sea-Time as Cadet -> Clear DG Shipping 2nd Mate Oral & Written Exams -> Third Officer."},
                {"title": "Path B: Marine Engineering Route (Engine Side)", "type": "COMMON", "steps": "Class 12 (PCM 60%+) -> B.Tech Marine Engineering (4 yrs) -> 6 Months Sea-Time -> Clear Class IV Marine Engineer exam -> Fourth Engineer."}
            ],
            "ladder": [
                {"stage": "Deck / Engine Cadet", "exp": "0-1.5 Years", "desc": "Undergoes mandatory sea-time training on commercial ships, completes Training Record Book."},
                {"stage": "Third Officer / Fourth Engineer", "exp": "1.5-4 Years", "desc": "Keeps navigational bridge watch, inspects life-saving appliances, manages auxiliary engines."},
                {"stage": "Chief Mate / Second Engineer", "exp": "4-8 Years", "desc": "Second-in-command of ship, directs cargo operations and heavy marine engine maintenance."},
                {"stage": "Captain (Master Mariner) / Chief Engineer", "exp": "8+ Years", "desc": "Commands the entire commercial ship and crew, holds absolute sovereign nautical authority on the high seas."}
            ],
            "roadmaps": {
                "Class 10": "Maintain high physical fitness, excellent swimming skills, and strong eyesight (6/6).",
                "Class 12": "Score at least 60% aggregate in Physics, Chemistry, and Mathematics (mandatory DG Shipping eligibility).",
                "Graduation": "Appear for the IMU-CET entrance examination. Complete B.Sc Nautical Science or B.Tech Marine Engineering at Indian Maritime University (IMU) or premier maritime academies.",
                "Working Professional": "Accumulate mandatory sea-time hours, pass DG Shipping Certificate of Competency (CoC) examinations, and progress to Master Mariner."
            }
        },
        {
            "title": "Urban & Regional Planner",
            "short_name": "Urban Planner",
            "slug": "urban-regional-planner",
            "category": "Social Sciences, Psychology & Public Policy",
            "sub_category": "Urban Design, Town Planning & Spatial Development",
            "industry": "Urban Development, Town Planning & Architecture",
            "icon": "buildings",
            "short_description": "Designs sustainable city master plans, public transit networks, zoning regulations, and smart urban infrastructure.",
            "description": "Urban and Regional Planners design the future of human settlements. They formulate city master plans, plan mass rapid transit systems (Metro, Bus Rapid Transit), designate industrial and residential zoning, and revitalize heritage urban centers to create sustainable, liveable cities.",
            "what_they_do": "They analyze demographic growth trends, create 20-year city master development plans, design transport mobility corridors, assess housing affordability, and ensure compliance with environmental and disaster zoning laws.",
            "day_to_day_work": "• Creating land use zoning and spatial master plans in GIS.\n• Conducting urban mobility and public transit origin-destination surveys.\n• Reviewing real estate development blueprints against local building bylaws.\n• Formulating urban climate resilience and stormwater drainage plans.\n• Presenting development plans at public municipal stakeholder hearings.",
            "work_environment": "Urban development authorities (DDA, MMRDA, BDA), smart city corporations, infrastructure consultancies.",
            "work_modes": "Hybrid / Office / Urban Field Surveys",
            "minimum_qualification": "Undergraduate (B.Plan - Bachelor of Planning / B.Arch)",
            "preferred_streams": "Science (PCM) / Any with Maths",
            "required_subjects": "Mathematics, Urban Planning, Architecture",
            "technical_skills": "City Master Planning, Land Use Zoning, GIS (ArcGIS / QGIS), Transport Planning, Urban Economics, Building Bylaws, Urban Drainage Modeling",
            "soft_skills": "Long-Term Vision, Public Diplomacy, Multidisciplinary Coordination, Environmental Care",
            "tools": "ArcGIS, QGIS, AutoCAD, TransCAD, CityEngine, SketchUp",
            "certifications": "Associate Member of Institute of Town Planners, India (AITPI)",
            "experience_level": "Entry-Level to Senior",
            "career_growth": "Broad, prestigious trajectory progressing to Senior Town Planner, Chief Urban Planner, or Metropolitan Development Commissioner.",
            "internship_roles": "Urban Planning Intern, Town Planning Trainee, GIS Mapping Intern",
            "entry_level_roles": "Assistant Town Planner, Urban Analyst, GIS Planning Associate",
            "average_salary": "₹5 - ₹14 LPA (Indicative range)",
            "salary_indicative": "Assistant Town Planner (0-2 yrs): ₹4.5 - 7 LPA | Urban Planning Specialist (3-6 yrs): ₹8 - 16 LPA | Chief Town Planner / Planning Director (7+ yrs): ₹20 - 45+ LPA. Indicative figures from ITPI 2024.",
            "future_scope": "Surging national growth driven by India's rapid urbanization (400M+ urban citizens), Smart Cities Mission, and transit-oriented development (TOD).",
            "government_opportunities": "Delhi Development Authority (DDA), MMRDA Mumbai, State Town & Country Planning Departments, Smart City SPVs, NITI Aayog.",
            "private_opportunities": "PwC Urban Infrastructure, Ernst & Young, AECOM, Jacobs, WSP India, Lea Associates, real estate developers.",
            "higher_study_options": "M.Plan in Urban / Transport / Housing Planning (School of Planning and Architecture - SPA New Delhi / CEPT University).",
            "entrepreneurship_options": "Urban planning and GIS consultancy, sustainable mobility advisory firm.",
            "source": "Institute of Town Planners, India (ITPI) / SPA New Delhi",
            "official_url": "https://www.itpi.org.in",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 32, "type": "COMMON"}, {"course_id": 12, "type": "COMMON"}, {"course_id": 20, "type": "ALTERNATIVE"}],
            "exams": [{"exam_id": 8, "importance": "PRIMARY"}, {"exam_id": 69, "importance": "PRIMARY"}],
            "routes": [{"title": "Path A: JEE Main Paper 2B (B.Plan) to Town Planner", "type": "COMMON", "steps": "Class 12 (Maths) -> JEE Main Paper 2B -> B.Plan (Bachelor of Planning - 4 yrs) at SPA New Delhi / CEPT -> State Town Planning Assistant / Urban Consultant."}],
            "ladder": [
                {"stage": "Assistant Town Planner / Planning Analyst", "exp": "0-2 Years", "desc": "Maps land use in QGIS, analyzes demographic census data, assists in zoning reviews."},
                {"stage": "Urban / Transport Planner", "exp": "2-5 Years", "desc": "Designs transit-oriented development corridors, drafts municipal local area plans."},
                {"stage": "Senior Town Planner", "exp": "5-9 Years", "desc": "Directs 20-year metropolitan master development plan revisions, advises municipal commissioners."},
                {"stage": "Chief Town Planner / Metropolitan Planning Director", "exp": "9+ Years", "desc": "Heads state town and country planning policy, directs urban infrastructure investments."}
            ],
            "roadmaps": {
                "Class 10": "Observe city traffic, buildings, parks, and understand how neighborhoods are organized.",
                "Class 12": "Choose Science or any stream with Mathematics. Score well in JEE Main Paper 2B (B.Plan).",
                "Graduation": "Complete B.Plan at premier institutions like SPA New Delhi, SPA Bhopal, or CEPT University. Master QGIS and urban economics.",
                "Working Professional": "Prepare for the State Town Planning Service exams or join global urban planning infrastructure consultancies."
            }
        },
        {
            "title": "Non-Governmental Organization (NGO) Program Director",
            "short_name": "NGO Program Director",
            "slug": "ngo-program-director",
            "category": "Social Sciences, Psychology & Public Policy",
            "sub_category": "Social Impact Leadership & Philanthropy",
            "industry": "Non-Profit & International Development",
            "icon": "people-fill",
            "short_description": "Leads large-scale humanitarian non-profit operations, secures philanthropic grants, and drives measurable social change.",
            "description": "NGO Program Directors design, fund, and scale social impact initiatives that improve millions of lives in health, education, poverty eradication, and human rights. They manage multi-million dollar grants from global foundations and coordinate with government welfare ministries.",
            "what_they_do": "They formulate organizational social impact strategies, write grant proposals for institutional donors (Gates Foundation, Ford Foundation), manage countrywide field teams, and oversee financial compliance with the FCRA and CSR regulations.",
            "day_to_day_work": "• Meeting corporate CSR heads and philanthropic foundations to pitch major grant proposals.\n• Reviewing quarterly field impact milestones and randomized control evaluations.\n• Overseeing multimillion-rupee program budgets and auditing FCRA compliance.\n• Inspiring and mentoring hundreds of grassroots field coordinators and volunteers.\n• Advocating for policy reforms before parliamentary committees and ministries.",
            "work_environment": "Non-profit headquarters, rural program field sites, international donor summits.",
            "work_modes": "Hybrid / Office & Frequent Rural Field Monitoring",
            "minimum_qualification": "Postgraduate (MSW / Master in Public Policy / Development Studies / MBA)",
            "preferred_streams": "Humanities / Social Sciences / Management",
            "required_subjects": "Social Sciences, Public Policy, Management",
            "technical_skills": "Grant Proposal Writing, Monitoring & Evaluation (M&E), Theory of Change, FCRA Compliance, Philanthropic Fundraising, Stakeholder Coalition Building",
            "soft_skills": "Mission-Driven Leadership, Deep Moral Compassion, High Resilience, Diplomatic Persuasion",
            "tools": "LogFrame, KoboToolbox, Salesforce for Nonprofits, Excel, Impact Dashboards",
            "certifications": "TISS Social Work Fellowships / Global Philanthropy Management",
            "experience_level": "Program Manager to Executive Director / CEO",
            "career_growth": "Noble and highly influential leadership trajectory progressing to Country Director, Executive Director, or UN Senior Representative.",
            "internship_roles": "Social Program Intern, Grant Writing Trainee",
            "entry_level_roles": "Project Associate, Program Officer, Field Monitoring Specialist",
            "average_salary": "₹6 - ₹18 LPA (Indicative range)",
            "salary_indicative": "Program Officer (0-3 yrs): ₹5 - 8 LPA | Senior Program Director (4-8 yrs): ₹12 - 24 LPA | Country Director / Executive Director (8+ yrs): ₹28 - 60+ LPA. Indicative figures from TISS & Philanthropy India 2024.",
            "future_scope": "Surging scale supported by India's mandatory 2% CSR expenditure, philanthropic family offices, and global climate adaptation funds.",
            "government_opportunities": "National Health Mission State Societies, NITI Aayog Aspirational Districts Program, Tribal Welfare Boards.",
            "private_opportunities": "Pratham, Teach For India, Goonj, Akshaya Patra, Child Rights and You (CRY), Care India, Oxfam India.",
            "higher_study_options": "Ph.D. in Development Studies / Social Work, Executive Non-Profit Leadership at Harvard.",
            "entrepreneurship_options": "Founding an impactful non-profit organization (NGO), social impact accelerator.",
            "source": "Tata Institute of Social Sciences (TISS) / GuideStar India",
            "official_url": "https://www.tiss.edu",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 20, "type": "COMMON"}, {"course_id": 22, "type": "COMMON"}, {"course_id": 18, "type": "COMMON"}],
            "exams": [{"exam_id": 79, "importance": "PRIMARY"}],
            "routes": [{"title": "Path A: Development Studies to NGO Leadership", "type": "COMMON", "steps": "Graduation -> Master in Social Work (MSW - TISS) or Development Studies -> Program Officer at grassroots NGO -> NGO Program Director."}],
            "ladder": [
                {"stage": "Program Officer", "exp": "0-3 Years", "desc": "Manages field district implementation, coordinates training workshops, collects M&E data."},
                {"stage": "State / Thematic Program Manager", "exp": "3-7 Years", "desc": "Leads multi-crore program grants, manages donor reporting, coordinates with state ministries."},
                {"stage": "Program Director", "exp": "7-12 Years", "desc": "Heads national program strategy across multiple states, secures new institutional funding."},
                {"stage": "Executive Director / CEO of NGO", "exp": "12+ Years", "desc": "Leads entire non-profit organization, shapes national social impact agenda, serves on government panels."}
            ],
            "roadmaps": {
                "Class 10": "Participate actively in community social work, tree planting, and child education volunteering.",
                "Class 12": "Choose any stream for Class 12 board exams.",
                "Graduation": "Complete graduation with volunteer experience in active NGOs. Complete Master in Social Work (MSW) or Development Studies at TISS.",
                "Working Professional": "Master grant proposal writing, Theory of Change frameworks, and impact measurement (Randomized Evaluations)."
            }
        }
    ]

print("Catalog builder part 12 ready.")
