"""
scripts/catalog_expanded_part2.py
Domain C: Law & Legal Services (8 careers)
Domain D: Government & Public Service (10 careers)
Domain E: Defence & Uniformed Services (8 careers)
"""

def get_law_and_legal_careers():
    return [
        {
            "title": "Civil Judge & Judicial Magistrate",
            "short_name": "Civil Judge",
            "slug": "civil-judge-magistrate",
            "category": "Law & Legal Services",
            "sub_category": "Judiciary & Courts",
            "industry": "Judicial Services & Courts of Law",
            "icon": "shield",
            "short_description": "Presides over civil disputes, trials, and criminal bail hearings in district and subordinate courts.",
            "description": "Civil Judges and Judicial Magistrates are state judicial officers who preside over subordinate courts of first instance. They conduct civil and criminal trials, evaluate sworn evidence, adjudicate contract and property disputes, issue search warrants and summons, frame legal charges, and pronounce judicial judgments adhering to Indian substantive and procedural law.",
            "what_they_do": "Judges conduct daily courtroom proceedings, evaluate witness testimonies under the Indian Evidence Act, adjudicate civil suits under the Code of Civil Procedure (CPC), pass sentences under the Bharatiya Nyaya Sanhita (BNS / IPC), and author reasoned judgments.",
            "day_to_day_work": "• Presiding over courtroom hearings, interim injunction petitions, and bail applications.\n• Examining witnesses and recording depositions under oath.\n• Reviewing written legal submissions, precedents, and Supreme Court rulings cited by advocates.\n• Authoring detailed, reasoned judicial judgments and decrees in chamber.\n• Overseeing court administrative registry staff and managing case pendency.",
            "work_environment": "District Courts, Sub-Divisional Courts, Judicial Chambers.",
            "work_modes": "On-site / Court / Chamber",
            "minimum_qualification": "Undergraduate (LL.B. - 3 Years or 5-Year Integrated B.A. LL.B. / BBA LL.B.)",
            "preferred_streams": "Any Stream (Arts / Humanities / Commerce / Science)",
            "required_subjects": "Constitutional Law, Civil Law, Criminal Law, Evidence Law",
            "technical_skills": "Judicial Adjudication, Evidence Evaluation, Civil Procedure (CPC), Criminal Procedure (CrPC/BNSS), Penal Law, Constitutional Reasoning, Legal Draftsmanship",
            "soft_skills": "Absolute Impartiality, Uncompromising Integrity, Deep Listening, Emotional Composure, Decisiveness",
            "tools": "e-Courts Case Information System (CIS), Supreme Court Cases (SCC Online), Manupatra, Bare Acts",
            "certifications": "Provincial Civil Services Judicial (PCS-J) Selection, State High Court Judicial Academy Training",
            "experience_level": "Entry Judicial Officer to Senior District Judge",
            "career_growth": "Advance to Senior Civil Judge, Chief Judicial Magistrate (CJM), District & Sessions Judge, and High Court Judge.",
            "internship_roles": "Judicial Clerkship Intern, High Court Bench Shadowing Intern",
            "entry_level_roles": "Civil Judge (Junior Division) / Judicial Magistrate (First Class)",
            "average_salary": "₹9.0 - ₹22.0 LPA (National Judicial Pay Commission)",
            "salary_indicative": "Civil Judge Junior Division (Entry): ₹77,840 basic + DA + allowances (~₹10 - 13 LPA in hand) | Senior Civil Judge / CJM: ₹14 - 18 LPA | District Judge / Principal Sessions Judge: ₹18 - 25+ LPA plus government accommodation, vehicle, and judicial security.",
            "future_scope": "Continuous national recruitment across every state judiciary under the National Judicial Data Grid (NJDG) expansion.",
            "government_opportunities": "State Subordinate Judiciaries (Delhi Judicial Service, UP PCS-J, Maharashtra Judicial Service, etc.), Armed Forces Tribunal, Lok Adalats.",
            "private_opportunities": "Judicial officers hold permanent constitutional public offices; post-retirement roles include Arbitrators and Tribunal Members.",
            "higher_study_options": "LL.M. in Judicial Studies, Ph.D. in Law.",
            "entrepreneurship_options": "Commercial arbitration panelist, independent dispute mediator post-service.",
            "source": "Supreme Court of India / State High Courts / National Judicial Pay Commission",
            "official_url": "https://main.sci.gov.in",
            "verification_status": "VERIFIED",
            "is_lesser_known": False,
            "career_family": "Law & Justice",
            "interest_clusters": "Law, Government, Society, Writing, Leadership",
            "work_style": "Court, Government Office",
            "reality_check": "Clearing Judicial Services Examination (PCS-J) requires intense legal study across dozens of substantive and procedural bare acts.\nJudges live under strict judicial conduct codes: restricted private social engagements and frequent district transfers.\nHeavy caseloads require disciplined stamina to manage hundreds of active court matters.",
            "next_steps": "Earn a recognized law degree (5-year Integrated B.A. LL.B. or 3-year LL.B.) from a BCI-approved institution.\nEnroll with the State Bar Council and master procedural codes (CPC, CrPC/BNSS, Indian Evidence Act).\nAppear for State Judicial Services Examination (PCS-J) Preliminary, Mains, and Interview.",
            "courses": [{"course_id": 26, "type": "PRIMARY"}, {"course_id": 27, "type": "PRIMARY"}],
            "exams": [{"exam_id": 1, "importance": "RECOMMENDED"}],
            "routes": [{"title": "Path A: Direct PCS-J Entry", "type": "PRIMARY", "steps": "12th (Any Stream) -> CLAT / Law CET -> 5-Yr B.A. LL.B. -> State PCS-J Exam -> Judicial Academy Training -> Civil Judge (Junior Division)."}],
            "ladder": [
                {"stage": "Civil Judge (Junior Division) / JMFC", "exp": "0-5 Years", "desc": "Presides over civil suits of specified monetary valuation and criminal offenses punishable up to 3 years."},
                {"stage": "Senior Civil Judge / Chief Judicial Magistrate", "exp": "5-10 Years", "desc": "Handles higher pecuniary jurisdiction civil suits, serious criminal cases, supervises subordinate magistrates."},
                {"stage": "District & Sessions Judge", "exp": "10+ Years", "desc": "Principal judicial officer of the district, conducts murder and felony trials, hears civil appeals."}
            ]
        },
        {
            "title": "Arbitrator & Mediator",
            "short_name": "Arbitrator & Mediator",
            "slug": "arbitrator-mediator",
            "category": "Law & Legal Services",
            "sub_category": "Dispute Resolution & ADR",
            "industry": "Alternative Dispute Resolution (ADR) & Commercial Arbitration",
            "icon": "handshake",
            "short_description": "Resolves multi-crore commercial disputes, corporate conflicts, and civil disagreements outside traditional courtrooms.",
            "description": "Arbitrators and Mediators are trained legal neutrals who facilitate out-of-court resolutions of high-stakes commercial, corporate, construction, and maritime disputes under the Arbitration and Conciliation Act 1996 and Mediation Act 2023. Unlike court litigation that can drag on for decades, ADR offers private, confidential, enforceable, and time-bound conflict resolution.",
            "what_they_do": "Arbitrators hear evidence and issue legally binding arbitral awards enforceable as court decrees; Mediators act as neutral facilitators guiding adversarial parties to mutually agreed settlement contracts.",
            "day_to_day_work": "• Reviewing arbitration claim statements, counterclaims, and commercial contracts.\n• Conducting procedural arbitration hearings with counsels from both sides.\n• Questioning technical expert witnesses (quantity surveyors, financial auditors).\n• Facilitating private caucuses in mediation sessions to explore commercial settlement options.\n• Drafting legally watertight, enforceable arbitral awards with detailed reasoning.",
            "work_environment": "Arbitration chambers, International Arbitration Centers (MCIA, DIAC, SIAC), law offices.",
            "work_modes": "Hybrid / Chamber / Office",
            "minimum_qualification": "Undergraduate (LL.B.) / Professional Degree + ADR Accreditation",
            "preferred_streams": "Any Stream (Law / Engineering / Finance / Corporate)",
            "required_subjects": "Contract Law, Arbitration Law, Commercial Jurisprudence",
            "technical_skills": "Arbitration Proceedings, Mediation Techniques, Contract Interpretation, Evidence Analysis, Arbitral Award Drafting, UNCITRAL Model Law",
            "soft_skills": "Active Listening, Neutrality, Persuasive Negotiation, High Integrity, Patience",
            "tools": "Arbitration Case Portals, SCC Online, Virtual Hearing Platforms, Settlement Drafting Templates",
            "certifications": "Chartered Institute of Arbitrators (CIArb) Fellowship (FCIArb), MCIA Panel Accreditation, BIMACC Certified Mediator",
            "experience_level": "Mid to Senior Level",
            "career_growth": "Advance to Internationally Empaneled Arbitrator (SIAC, LCIA, ICC), Senior Partner (ADR Practice).",
            "internship_roles": "Arbitration Research Intern, ADR Center Case Trainee",
            "entry_level_roles": "ADR Associate, Arbitration Registry Case Manager, Junior Dispute Specialist",
            "average_salary": "₹7.0 - ₹25.0+ LPA (Case Sitting Fee Model)",
            "salary_indicative": "Young ADR Associate: ₹7 - 12 LPA | Empaneled Commercial Arbitrator: ₹15 - 40+ LPA (Sitting fees often ₹50,000 - ₹3,00,000 per hearing session plus reading fees under 4th Schedule scales). Indicative figures from MCIA and High Court arbitration fee rules.",
            "future_scope": "Explosive growth with India's Mediation Act 2023 mandates and corporate preference for private international commercial arbitration.",
            "government_opportunities": "National Company Law Tribunal (NCLT) mediation panels, Public Sector Undertaking (PSU) dispute panels, High Court Mediation Centers.",
            "private_opportunities": "Mumbai Centre for International Arbitration (MCIA), Delhi International Arbitration Centre (DIAC), Tier-1 Law Firms (Shardul Amarchand, Cyril Amarchand, Trilegal).",
            "higher_study_options": "LL.M. in International Commercial Arbitration, Diploma in International Dispute Resolution (CIArb UK).",
            "entrepreneurship_options": "Establishing an independent boutique ADR firm or institutional dispute resolution center.",
            "source": "Chartered Institute of Arbitrators (CIArb) / MCIA",
            "official_url": "https://mcia.org.in",
            "verification_status": "VERIFIED",
            "is_lesser_known": True,
            "career_family": "Law & Justice",
            "interest_clusters": "Law, Business, Helping, Society",
            "work_style": "Chamber, Office",
            "reality_check": "Being appointed as a primary sole arbitrator usually requires 10-15+ years of established legal or technical standing.\nYoung professionals enter this field as arbitration associates, case managers at arbitration institutions (MCIA), or tribunal secretaries.\nDemands deep mastery of complex commercial contracts, engineering disputes, and international arbitration treaties.",
            "next_steps": "Complete LL.B. (3-year or 5-year integrated law degree).\nObtain accreditation from institutions like CIArb (Chartered Institute of Arbitrators) or Indian Institute of Arbitration & Mediation.\nWork as a Tribunal Secretary or ADR Associate under senior empaneled arbitrators.",
            "courses": [{"course_id": 26, "type": "PRIMARY"}, {"course_id": 27, "type": "PRIMARY"}],
            "exams": [],
            "routes": [{"title": "Path A: Commercial ADR Route", "type": "PRIMARY", "steps": "LL.B. Degree -> ADR Specialization / CIArb Certification -> Arbitration Associate -> Tribunal Secretary -> Empaneled Arbitrator."}],
            "ladder": [
                {"stage": "Arbitration Associate / Tribunal Secretary", "exp": "0-4 Years", "desc": "Assists arbitral tribunals in organizing proceedings, drafting procedural orders, researching precedent."},
                {"stage": "Accredited Commercial Mediator & Arbitrator", "exp": "4-10 Years", "desc": "Mediates commercial disputes, handles domestic contract and construction arbitrations independently."},
                {"stage": "Senior Fellow (CIArb) / International Arbitrator", "exp": "10+ Years", "desc": "Presides over multi-million dollar cross-border disputes empaneled with SIAC, ICC, and MCIA."}
            ]
        },
        {
            "title": "Corporate In-House Legal Counsel",
            "short_name": "Corporate Counsel",
            "slug": "corporate-legal-counsel",
            "category": "Law & Legal Services",
            "sub_category": "Corporate & Commercial Law",
            "industry": "Corporate Business & Enterprise Legal Affairs",
            "icon": "briefcase",
            "short_description": "Protects company legal interests, negotiates commercial contracts, and manages corporate regulatory risks.",
            "description": "Corporate In-House Legal Counsels work directly inside corporations, conglomerates, startups, and financial institutions as primary legal advisors to executive management. They structure and negotiate multi-million dollar commercial transactions, ensure compliance with statutory laws, manage outside litigation counsel, and safeguard the company's legal reputation.",
            "what_they_do": "They draft Master Services Agreements (MSAs), nondisclosure agreements, technology licenses, advise on employment and data privacy laws, manage corporate governance, and mitigate commercial dispute risks.",
            "day_to_day_work": "• Drafting and negotiating high-value commercial supplier and client contracts.\n• Advising business product teams on regulatory compliance and data protection laws.\n• Conducting legal due diligence for mergers, acquisitions (M&A), and venture financing.\n• Managing corporate disputes, legal notices, and coordinating with external courtroom litigators.\n• Formulating internal corporate governance policies and whistleblower compliance.",
            "work_environment": "Corporate headquarters, multinational enterprises, tech company offices.",
            "work_modes": "Hybrid / Office",
            "minimum_qualification": "Undergraduate (LL.B. - 3 Years or 5-Year Integrated B.A. LL.B. / BBA LL.B.)",
            "preferred_streams": "Any Stream (Commerce, Arts, or Science)",
            "required_subjects": "Company Law, Contract Law, Intellectual Property",
            "technical_skills": "Contract Drafting & Negotiation, Companies Act 2013, Regulatory Compliance, M&A Due Diligence, Data Privacy (DPDP Act), Risk Mitigation",
            "soft_skills": "Business Acumen, Strategic Negotiation, Cross-Functional Communication, Decisiveness Under Pressure",
            "tools": "Contract Lifecycle Management (CLM) software, DocuSign, Manupatra, SCC Online",
            "certifications": "Bar Council of India Enrollment, In-House Counsel Certification",
            "experience_level": "Entry to Executive Level",
            "career_growth": "Advance to Senior Legal Counsel, Legal Director, and Chief Legal Officer (General Counsel).",
            "internship_roles": "Corporate Legal Intern, In-House Legal Trainee",
            "entry_level_roles": "Junior Legal Counsel, Legal Analyst, Corporate Legal Executive",
            "average_salary": "₹6.5 - ₹20.0 LPA (Indicative range)",
            "salary_indicative": "Legal Analyst (0-2 yrs): ₹6.5 - 9.5 LPA | Senior Legal Counsel (4-7 yrs): ₹12 - 22 LPA | General Counsel (CLO) of major MNC (8+ yrs): ₹25 - 60+ LPA. Indicative figures from corporate legal salary benchmarks.",
            "future_scope": "Immense demand as corporations navigate increasingly complex data privacy, compliance, and international cross-border trade.",
            "government_opportunities": "Legal Officer in Public Sector Enterprises (ONGC, BHEL, NTPC, IOCL), SEBI, RBI Legal Department.",
            "private_opportunities": "Tata Group, Reliance Industries, Google India, Infosys, Amazon, HDFC Bank, Flipkart, Unilever.",
            "higher_study_options": "LL.M. in Corporate Law, MBA in Finance / General Management.",
            "entrepreneurship_options": "Legal-tech startup founder, independent corporate compliance and contract management consultancy.",
            "source": "Bar Council of India (BCI) / Indian Corporate Counsel Association (ICCA)",
            "official_url": "https://www.barcouncilofindia.org",
            "verification_status": "VERIFIED",
            "is_lesser_known": False,
            "career_family": "Law & Justice",
            "interest_clusters": "Law, Business, Leadership, Writing",
            "work_style": "Office, Remote",
            "reality_check": "In-house lawyers must think like business partners, not just courtroom advocates: advice must enable commercial deals safely.\nContract negotiations involve aggressive pressure and rapid turnaround times from sales teams.\nDoes not involve courtroom advocacy; focuses on proactive dispute avoidance.",
            "next_steps": "Complete a 5-year integrated law degree (B.A. LL.B. / BBA LL.B.) from a reputed law school.\nMaster commercial contract drafting, company law, and take corporate law internships.\nJoin a corporate legal department or law firm corporate practice group as a junior associate.",
            "courses": [{"course_id": 26, "type": "PRIMARY"}, {"course_id": 27, "type": "PRIMARY"}],
            "exams": [],
            "routes": [{"title": "Path A: Law School to Corporate Counsel", "type": "PRIMARY", "steps": "B.A. LL.B. / BBA LL.B. (5 yrs) -> Bar Council Enrollment -> Junior Legal Counsel -> Senior Counsel -> General Counsel."}],
            "ladder": [
                {"stage": "Legal Analyst / Associate Counsel", "exp": "0-3 Years", "desc": "Reviews standard NDAs, vendor contracts, maintains corporate compliance filings."},
                {"stage": "Senior Legal Counsel", "exp": "3-7 Years", "desc": "Leads major client contract negotiations, handles M&A due diligence, resolves disputes."},
                {"stage": "General Counsel / Chief Legal Officer", "exp": "7+ Years", "desc": "Directs overall corporate legal strategy, advises the Board of Directors, leads legal team."}
            ]
        },
        {
            "title": "Intellectual Property & Patent Attorney",
            "short_name": "IP & Patent Attorney",
            "slug": "ip-patent-attorney",
            "category": "Law & Legal Services",
            "sub_category": "Intellectual Property Law",
            "industry": "Intellectual Property, Patents & Technology Law",
            "icon": "lightbulb",
            "short_description": "Protects inventions, patents, trademarks, copyrights, and trade secrets for innovators and creators.",
            "description": "Intellectual Property (IP) and Patent Attorneys help scientists, engineers, tech startups, pharmaceutical firms, and creative artists protect their proprietary inventions, brand identities, and artistic works. Patent attorneys holding scientific/technical degrees draft detailed patent claims and prosecute them before the Indian Patent Office and global patent offices.",
            "what_they_do": "They perform prior art searches, draft technical patent specifications and claims, prosecute trademark and patent applications, negotiate IP licensing deals, and litigate patent/trademark infringement before High Courts.",
            "day_to_day_work": "• Reviewing engineering blueprints, pharmaceutical chemical formulas, or software algorithms with inventors.\n• Conducting prior art searches in global patent databases (WIPO, USPTO, Indian Patent Office).\n• Drafting technical patent claims establishing novelty and non-obvious inventive steps.\n• Responding to First Examination Reports (FER) and attending patent hearings.\n• Enforcing trademarks and trade dress against counterfeit infringers.",
            "work_environment": "IP law firms, corporate R&D patent departments, patent prosecution chambers.",
            "work_modes": "Hybrid / Office",
            "minimum_qualification": "Undergraduate (LL.B. + B.Sc / B.Tech for Patent Agent eligibility)",
            "preferred_streams": "Science (PCM / PCB) + Law",
            "required_subjects": "Patent Law, Trademark Law, Chemistry/Physics/Computer Science",
            "technical_skills": "Patent Claim Drafting, Prior Art Search, Patent Prosecution, Trademark Filing, Freedom to Operate (FTO) Analysis, Patent Litigation, Technology Licensing",
            "soft_skills": "Sharp Analytical Thinking, Precise Technical Writing, Attention to Inventive Nuance",
            "tools": "Patent Search Databases (Derwent, PatBase, Espacenet, Google Patents), Indian IP Office Portal",
            "certifications": "Registered Indian Patent Agent (clearing Indian Patent Agent Exam conducted by CGPDTM), Bar Council of India Enrollment",
            "experience_level": "Entry to Senior Level",
            "career_growth": "Advance to Senior IP Partner, Head of Corporate Patent Portfolio, or Technology Transfer Director.",
            "internship_roles": "Patent Search Intern, IP Law Trainee",
            "entry_level_roles": "Junior Patent Associate, Patent Analyst, IP Trainee",
            "average_salary": "₹6.0 - ₹18.0 LPA (Indicative range)",
            "salary_indicative": "Junior Patent Analyst: ₹6 - 8.5 LPA | Registered Patent Attorney (3-6 yrs): ₹9 - 16 LPA | Senior IP Partner / Lead Patent Counsel: ₹18 - 35+ LPA. Indicative figures from IP law firm surveys.",
            "future_scope": "Tremendous demand in Indian pharma, biotech, artificial intelligence, electric vehicles, and deep-tech innovation.",
            "government_opportunities": "Examiner of Patents and Designs (UPSC / CGPDTM), Indian Patent Office, CSIR Innovation Protection Unit.",
            "private_opportunities": "Anand and Anand, Remfry & Sagar, K&S Partners, LexOrbis, Sun Pharma, Biocon, Google Patents, Qualcomm.",
            "higher_study_options": "LL.M. in Intellectual Property Law, International Patent Law certifications.",
            "entrepreneurship_options": "Founding a boutique patent prosecution agency or IP valuation consultancy.",
            "source": "Controller General of Patents, Designs and Trade Marks (CGPDTM) / Bar Council of India",
            "official_url": "https://ipindia.gov.in",
            "verification_status": "VERIFIED",
            "is_lesser_known": True,
            "career_family": "Law & Justice",
            "interest_clusters": "Law, Science, Technology, Writing",
            "work_style": "Office, Remote",
            "reality_check": "To become a registered 'Patent Agent' qualified to draft patent claims, Indian law requires a science, pharmacy, or engineering degree.\nA pure law graduate without a science background can handle trademarks and copyrights, but cannot become a registered patent agent.\nDemands meticulous, painstaking technical writing: a single ambiguously chosen word can invalidate a multi-crore patent.",
            "next_steps": "Earn a degree in Science (B.Sc), Pharmacy (B.Pharm), or Engineering (B.Tech).\nComplete an LL.B. degree to become an advocate.\nAppear for the Indian Patent Agent Examination conducted by CGPDTM and secure patent agent registration.",
            "courses": [{"course_id": 26, "type": "PRIMARY"}, {"course_id": 9, "type": "RELATED"}],
            "exams": [],
            "routes": [{"title": "Path A: Science/Engg to Patent Attorney", "type": "PRIMARY", "steps": "B.Tech / B.Sc / B.Pharm -> LL.B. Degree -> Indian Patent Agent Exam -> Patent Prosecution Associate -> Senior IP Partner."}],
            "ladder": [
                {"stage": "Patent Analyst / Trainee", "exp": "0-2 Years", "desc": "Conducts novelty patent searches, analyzes prior art citations, assists in patent drafting."},
                {"stage": "Registered Patent Attorney", "exp": "2-6 Years", "desc": "Drafts complete patent specifications, handles patent prosecution hearings before the Controller of Patents."},
                {"stage": "Senior IP Partner / Head of Patents", "exp": "6+ Years", "desc": "Manages global patent portfolios for multinational pharma and tech giants, leads patent litigation."}
            ]
        },
        {
            "title": "Cyber Law Specialist",
            "short_name": "Cyber Lawyer",
            "slug": "cyber-law-specialist",
            "category": "Law & Legal Services",
            "sub_category": "Technology & Cyber Law",
            "industry": "Cybercrime, Data Privacy & Internet Governance",
            "icon": "shield-lock",
            "short_description": "Handles cybercrime litigation, electronic evidence, data privacy compliance, and IT Act disputes.",
            "description": "Cyber Law Specialists navigate the intersection of law, internet technology, electronic commerce, and digital crime. They advise organizations on compliance with India's Digital Personal Data Protection (DPDP) Act, represent victims of financial cyberfraud and hacking under the Information Technology Act 2000, and handle electronic evidence in criminal and civil trials.",
            "what_they_do": "They draft data protection policies, handle cyber forensics and electronic evidence verification (Section 65B Certificate), advise on cybersecurity breach notifications, and litigate cyber offenses.",
            "day_to_day_work": "• Advising enterprises on compliance with the Digital Personal Data Protection (DPDP) Act.\n• Drafting response strategies for ransomware incidents, data breaches, and CERT-In reporting.\n• Formulating Section 65B electronic evidence affidavits for computer data presented in court.\n• Representing clients in cybercrime complaints regarding financial fraud, identity theft, and defamatory content.\n• Drafting website terms of use, privacy policies, and software cloud hosting agreements.",
            "work_environment": "Law firms, corporate cybersecurity offices, cyber crime police cells, hybrid home office.",
            "work_modes": "Hybrid / Office / Court",
            "minimum_qualification": "Undergraduate (LL.B.) + Specialized Certification in Cyber Law & Data Privacy",
            "preferred_streams": "Any Stream (Law with interest in Computer Technology)",
            "required_subjects": "Information Technology Law, Data Privacy, Criminal Law",
            "technical_skills": "Information Technology Act 2000, DPDP Act 2023, Digital Forensics Basics, Section 65B Indian Evidence Act, Incident Response, GDPR Compliance",
            "soft_skills": "Analytical Acumen, Rapid Incident Response, Clear Technical Communication, Discretion",
            "tools": "Digital Evidence Hashes (MD5/SHA256), CERT-In Portals, E-Discovery Software, SCC Online",
            "certifications": "Certified Information Privacy Professional (CIPP/E, CIPP/A), Post Graduate Diploma in Cyber Law (NLSIU / NALSAR)",
            "experience_level": "Entry to Senior Level",
            "career_growth": "Advance to Data Protection Officer (DPO), Senior Cyber Law Partner, or Government Cyber Policy Advisor.",
            "internship_roles": "Cyber Law Research Intern, Privacy Compliance Trainee",
            "entry_level_roles": "Junior Cyber Legal Associate, Data Privacy Analyst, Technology Law Associate",
            "average_salary": "₹5.5 - ₹16.0 LPA (Indicative range)",
            "salary_indicative": "Junior Privacy Associate: ₹5.5 - 8 LPA | Experienced Cyber Lawyer (3-6 yrs): ₹9 - 15 LPA | Data Protection Officer (DPO) / Partner: ₹16 - 32+ LPA. Indicative figures from legal market surveys.",
            "future_scope": "Surging exponential demand with strict regulatory penalties under the DPDP Act and rising nationwide digital transactions.",
            "government_opportunities": "Ministry of Electronics and Information Technology (MeitY), CERT-In, Data Protection Board of India, State Cyber Crime Police Advisories.",
            "private_opportunities": "Big 4 Consulting Firms (PwC, EY, Deloitte, KPMG), Tier-1 Law Firms, Tech Giants (Meta, Amazon, Microsoft, Paytm, PhonePe).",
            "higher_study_options": "LL.M. in Technology & Cyber Law, International Certifications by IAPP (International Association of Privacy Professionals).",
            "entrepreneurship_options": "Independent boutique data privacy consultancy or specialized cybercrime litigation chamber.",
            "source": "Bar Council of India / MeitY / Data Security Council of India (DSCI)",
            "official_url": "https://www.meity.gov.in",
            "verification_status": "VERIFIED",
            "is_lesser_known": False,
            "career_family": "Law & Justice",
            "interest_clusters": "Law, Technology, Society, Writing",
            "work_style": "Office, Remote, Court",
            "reality_check": "Cyber lawyers do not write code, but must understand technical concepts like encryption, IP addresses, server logs, and hashing.\nDemands continuous study as digital crimes and privacy regulations evolve faster than traditional statutory law.\nHigh accountability during live enterprise data breach crises where regulatory notification deadlines are as tight as 6 hours.",
            "next_steps": "Complete an LL.B. degree (3-year or 5-year integrated law program).\nPursue a PG Diploma in Cyber Law & Data Protection from national law universities (NLSIU, NALSAR, WBNUJS).\nGain practical internship exposure in technology law practices or privacy teams at consulting firms.",
            "courses": [{"course_id": 26, "type": "PRIMARY"}, {"course_id": 27, "type": "PRIMARY"}],
            "exams": [],
            "routes": [{"title": "Path A: Law to Cyber Specialist", "type": "PRIMARY", "steps": "B.A. LL.B. (5 yrs) -> PG Diploma in Cyber Law -> CIPP Certification -> Technology Law Associate -> Data Protection Officer."}],
            "ladder": [
                {"stage": "Junior Cyber Legal Associate", "exp": "0-2 Years", "desc": "Audits privacy policies, drafts standard data processing agreements, handles electronic evidence filing."},
                {"stage": "Cyber Law Specialist & Litigator", "exp": "2-6 Years", "desc": "Advises on enterprise breach responses, coordinates cyber forensics, argues cyber disputes in court."},
                {"stage": "Data Protection Officer (DPO) / Senior Partner", "exp": "6+ Years", "desc": "Heads enterprise privacy governance, liaises with Data Protection Board, directs technology law practice."}
            ]
        },
        {
            "title": "Human Rights Advocate",
            "short_name": "Human Rights Advocate",
            "slug": "human-rights-advocate",
            "category": "Law & Legal Services",
            "sub_category": "Constitutional & Public Interest Law",
            "industry": "Public Interest Litigation (PIL) & Human Rights",
            "icon": "shield-check",
            "short_description": "Advocates for fundamental constitutional rights, marginalized communities, and public interest justice.",
            "description": "Human Rights Advocates are public interest lawyers who use constitutional law and judicial remedies (Writ Petitions under Article 32 and Article 226) to defend fundamental freedoms, environmental justice, minority rights, prisoners' rights, and freedom of expression. They appear before the Supreme Court, High Courts, and National Human Rights Commission (NHRC).",
            "what_they_do": "They draft Public Interest Litigations (PILs), represent indigent and marginalized undertrials, investigate custodial and civil rights violations, advocate for statutory policy reforms, and file complaints before statutory rights commissions.",
            "day_to_day_work": "• Drafting comprehensive Writ Petitions and PILs invoking fundamental rights in High Courts.\n• Representing vulnerable clients pro bono in bail and illegal detention matters.\n• Conducting fact-finding field missions in cases of communal or environmental displacement.\n• Submitting legal briefs before the National Human Rights Commission (NHRC) and State Commissions.\n• Advocating for systemic legislative reforms regarding child protection, gender rights, and bonded labor.",
            "work_environment": "High Courts, Supreme Court of India, human rights legal collectives, NGO offices.",
            "work_modes": "Hybrid / Court / Field / Office",
            "minimum_qualification": "Undergraduate (LL.B. - 3 Years or 5-Year Integrated B.A. LL.B.)",
            "preferred_streams": "Arts / Humanities / Any Stream",
            "required_subjects": "Constitutional Law, International Human Rights Law, Criminal Law",
            "technical_skills": "Constitutional Writ Practice, Public Interest Litigation (PIL) Drafting, Fact-Finding Investigation, Human Rights Conventions (UDHR, ICCPR), Legal Aid Advocacy",
            "soft_skills": "Fierce Ethical Courage, Empathy for Underprivileged, Persuasive Oratory, Emotional Resilience",
            "tools": "Supreme Court Cases (SCC), Bare Acts, Legal Aid Clinic Databases, Fact-Finding Documentation Tools",
            "certifications": "Bar Council of India Enrollment, All India Bar Examination (AIBE) Certificate",
            "experience_level": "Entry to Senior Level",
            "career_growth": "Advance to Senior Public Interest Litigator, UN Human Rights Expert, or High Court Judge.",
            "internship_roles": "Human Rights Legal Intern, Pro Bono Clinic Trainee",
            "entry_level_roles": "Legal Aid Associate, Public Interest Junior Advocate, Rights Researcher",
            "average_salary": "₹3.5 - ₹10.0 LPA (Social Impact & Pro Bono Model)",
            "salary_indicative": "Legal Aid / NGO Associate: ₹3.5 - 6 LPA | Experienced Public Interest Advocate (3-6 yrs): ₹6 - 12 LPA | Renowned Senior PIL Litigators: High private commercial retainers while handling major human rights cases pro bono. Indicative figures from legal aid collectives.",
            "future_scope": "Vital pillar of constitutional democracy, legal aid mechanisms (NALSA), and environmental social justice.",
            "government_opportunities": "National Human Rights Commission (NHRC), National Legal Services Authority (NALSA), State Human Rights Commissions, Public Prosecutor / Legal Aid Counsel panels.",
            "private_opportunities": "Amnesty International, Human Rights Law Network (HRLN), Centre for Policy Research, International Commission of Jurists (ICJ).",
            "higher_study_options": "LL.M. in Human Rights Law, Ph.D. in Constitutional Jurisprudence.",
            "entrepreneurship_options": "Founding an independent public interest legal collective, human rights litigation trust, or social justice clinic.",
            "source": "National Human Rights Commission (NHRC) / NALSA / Bar Council of India",
            "official_url": "https://nhrc.nic.in",
            "verification_status": "VERIFIED",
            "is_lesser_known": False,
            "career_family": "Law & Justice",
            "interest_clusters": "Law, Helping, Society, Leadership, Writing",
            "work_style": "Court, Field, Office",
            "reality_check": "Driven by passion and constitutional ideals rather than commercial corporate profit.\nEarly career can involve financial austerity when working primarily with non-profits or legal aid clinics.\nRequires courage and resilience when taking on powerful institutional adversaries in public interest litigation.",
            "next_steps": "Complete an LL.B. degree from a recognized institution, actively engaging in legal aid clinics.\nEnroll with the State Bar Council and clear the All India Bar Examination (AIBE).\nApprentice under experienced constitutional lawyers or public interest legal organizations (e.g. HRLN).",
            "courses": [{"course_id": 26, "type": "PRIMARY"}, {"course_id": 27, "type": "PRIMARY"}],
            "exams": [],
            "routes": [{"title": "Path A: Public Interest Law Route", "type": "PRIMARY", "steps": "B.A. LL.B. (5 yrs) -> AIBE Clearing -> Apprenticeship with Senior PIL Advocate -> Independent Human Rights Practice."}],
            "ladder": [
                {"stage": "Legal Aid Associate / Junior Advocate", "exp": "0-3 Years", "desc": "Handles remand bail applications, conducts legal aid fact-finding, drafts basic writ petitions."},
                {"stage": "Human Rights Litigator", "exp": "3-8 Years", "desc": "Argues independent PILs in High Courts, represents victims of state excess, files NHRC petitions."},
                {"stage": "Senior Public Interest Counsel", "exp": "8+ Years", "desc": "Argues landmark constitutional bench matters in the Supreme Court, shapes national human rights jurisprudence."}
            ]
        },
        {
            "title": "Labour & Industrial Relations Legal Advisor",
            "short_name": "Labour Law Advisor",
            "slug": "labour-law-advisor",
            "category": "Law & Legal Services",
            "sub_category": "Labour & Employment Law",
            "industry": "Manufacturing, Corporate HR & Industrial Tribunals",
            "icon": "people",
            "short_description": "Advises factories, corporations, and trade unions on labor codes, workplace safety, and industrial disputes.",
            "description": "Labour and Industrial Relations Legal Advisors specialize in labor legislation, industrial dispute resolution, factory compliance, and employment contracts. They guide corporations and factories through India's modernized Labour Codes (Wages, Industrial Relations, Social Security, Occupational Safety), negotiate collective bargaining agreements with trade unions, and represent parties before Industrial Tribunals and Labour Courts.",
            "what_they_do": "They audit factory safety and minimum wage compliance, structure employment contracts, represent management or unions in collective bargaining, conduct disciplinary inquiries, and handle industrial dispute litigation.",
            "day_to_day_work": "• Auditing corporate and factory compliance against the 4 Labour Codes.\n• Conducting domestic inquiry proceedings regarding employee misconduct or industrial strikes.\n• Representing clients before the Labour Commissioner, Industrial Tribunal, and High Court.\n• Drafting executive employment contracts, non-compete clauses, and severance agreements.\n• Advising on POSH (Prevention of Sexual Harassment at Workplace) compliance and Internal Committees.",
            "work_environment": "Industrial factory complexes, corporate headquarters, Labour Courts, law firms.",
            "work_modes": "Hybrid / Office / Factory / Court",
            "minimum_qualification": "Undergraduate (LL.B.) / Postgraduate in Labour Law & Industrial Relations",
            "preferred_streams": "Any Stream (Commerce / Arts / Law)",
            "required_subjects": "Labour Law, Industrial Relations, Administrative Law",
            "technical_skills": "4 New Labour Codes, Industrial Disputes Act, Factories Act, POSH Act, Collective Bargaining, Domestic Inquiry Conduct, Gratuity & PF Rules",
            "soft_skills": "Fairness, Conflict Mediation, Diplomatic Persuasion, Clear Interpersonal Communication",
            "tools": "Shram Suvidha Portal, EPFO Portals, ESIC Online, SCC Online Labour Cases",
            "certifications": "Bar Council of India Enrollment, POSH Certified External Member",
            "experience_level": "Entry to Senior Level",
            "career_growth": "Advance to Head of Industrial Relations, Senior Partner (Employment Law Practice), or Industrial Tribunal Member.",
            "internship_roles": "Industrial Relations Intern, Employment Law Trainee",
            "entry_level_roles": "Junior Labour Law Associate, Industrial Relations Officer, Compliance Executive",
            "average_salary": "₹5.0 - ₹14.0 LPA (Indicative range)",
            "salary_indicative": "Industrial Relations Officer: ₹5 - 7.5 LPA | Senior Labour Law Consultant (3-6 yrs): ₹8 - 14 LPA | Head of Employee Relations / Partner: ₹15 - 28+ LPA. Indicative figures from industrial federation surveys.",
            "future_scope": "High demand as India's manufacturing sector expands under Make in India and adopts the 4 unified National Labour Codes.",
            "government_opportunities": "Labour Commissionerate, Assistant Labour Commissioner (Central / State via UPSC / State PSC), EPFO Enforcement Officer.",
            "private_opportunities": "Manufacturing conglomerates (Tata Motors, Larsen & Toubro, Maruti Suzuki, Mahindra), IT giants, Tier-1 Employment Law practices.",
            "higher_study_options": "LL.M. in Labour Law, Master in Personnel Management & Industrial Relations (PMIR).",
            "entrepreneurship_options": "Establishing an independent factory labor compliance and POSH training consultancy.",
            "source": "Ministry of Labour & Employment / Bar Council of India",
            "official_url": "https://labour.gov.in",
            "verification_status": "VERIFIED",
            "is_lesser_known": False,
            "career_family": "Law & Justice",
            "interest_clusters": "Law, Business, People, Society",
            "work_style": "Office, Factory, Court",
            "reality_check": "Requires practical, on-the-ground diplomacy: resolving heated factory floor strikes and trade union tensions.\nDemands deep technical understanding of shop-floor working conditions, wages, overtime, and safety hazards.\nCombines legal expertise with human resource and industrial psychology dynamics.",
            "next_steps": "Complete an LL.B. degree with specialization in Labour and Industrial Law.\nTake internships with manufacturing plants or specialized employment law practices.\nEnroll with the State Bar Council and master the 4 National Labour Codes.",
            "courses": [{"course_id": 26, "type": "PRIMARY"}, {"course_id": 27, "type": "PRIMARY"}],
            "exams": [{"exam_id": 35, "importance": "RECOMMENDED"}],
            "routes": [{"title": "Path A: Employment Law Route", "type": "PRIMARY", "steps": "LL.B. Degree -> Labor Law Specialization -> Industrial Relations Officer / Associate -> Senior Labour Counsel."}],
            "ladder": [
                {"stage": "Junior Labour Law Associate", "exp": "0-2 Years", "desc": "Audits factory statutory registers (PF, ESI, gratuity), assists in Industrial Tribunal filings."},
                {"stage": "Industrial Relations Specialist / Advocate", "exp": "2-6 Years", "desc": "Conducts domestic disciplinary inquiries, represents clients in conciliation proceedings before Labour Commissioners."},
                {"stage": "Head of Employee Relations / Practice Partner", "exp": "6+ Years", "desc": "Negotiates corporate-wide long-term wage settlements with unions, designs nationwide compliance."}
            ]
        },
        {
            "title": "Tax & GST Law Practitioner",
            "short_name": "Tax Lawyer",
            "slug": "tax-law-practitioner",
            "category": "Law & Legal Services",
            "sub_category": "Taxation Law",
            "industry": "Taxation, Corporate Advisory & Appellate Tribunals",
            "icon": "cash-coin",
            "short_description": "Represents clients in direct tax (Income Tax) and indirect tax (GST) assessments, appeals, and litigation.",
            "description": "Tax & GST Law Practitioners specialize in the complex legal architecture of direct taxation (Income Tax Act) and indirect taxation (Central & State GST Acts, Customs). They structure commercial transactions for tax efficiency, represent corporate and individual taxpayers during revenue audits, and litigate tax appeals before the ITAT, GST Appellate Tribunal, High Courts, and Supreme Court.",
            "what_they_do": "They advise on cross-border transfer pricing, corporate restructuring tax implications, respond to tax evasion notices, prepare appellate paper books, and argue tax appeals before judicial tribunals.",
            "day_to_day_work": "• Analyzing complex corporate financial statements and tax assessment orders.\n• Drafting appellate memorandums for Income Tax Appellate Tribunal (ITAT) hearings.\n• Appearing before GST appellate authorities to contest input tax credit (ITC) reversals.\n• Advising multinational companies on international tax treaties (DTAA) and BEPS guidelines.\n• Arguing substantial questions of tax law before the High Court.",
            "work_environment": "Tax law firms, corporate tax chambers, appellate tribunals (ITAT, CESTAT, High Courts).",
            "work_modes": "Hybrid / Office / Tribunal",
            "minimum_qualification": "Undergraduate (LL.B.) / Dual Degree (B.Com LL.B. or LL.B. + CA)",
            "preferred_streams": "Commerce / Any Stream with Numerical Acumen",
            "required_subjects": "Direct Tax Law, Indirect Tax Law (GST), Corporate Accounting",
            "technical_skills": "Income Tax Act 1961, CGST/SGST Acts, Transfer Pricing, Cross-Border Taxation (DTAA), ITAT Appellate Advocacy, Tax Structuring",
            "soft_skills": "Analytical Acumen, Financial Literacy, Meticulous Scrutiny, Persuasive Oral Argument",
            "tools": "Income Tax Portal, GST Portal, Taxmann, SCC Online, CCH Wolters Kluwer",
            "certifications": "Bar Council of India Enrollment, All India Bar Examination (AIBE) Certificate",
            "experience_level": "Entry to Senior Level",
            "career_growth": "Advance to Senior Tax Partner, ITAT Judicial Member, or Senior Counsel at the Bar.",
            "internship_roles": "Tax Litigation Intern, Corporate Tax Advisory Trainee",
            "entry_level_roles": "Junior Tax Associate, Direct Tax Analyst, GST Legal Executive",
            "average_salary": "₹6.0 - ₹20.0 LPA (Indicative range)",
            "salary_indicative": "Junior Tax Associate: ₹6 - 9 LPA | Experienced Tax Advocate (3-6 yrs): ₹10 - 18 LPA | Senior Tax Partner / ITAT Counsel: ₹20 - 45+ LPA. Indicative figures from specialized tax law practices.",
            "future_scope": "Continuous strong demand as tax statutes, GST rules, and international digital tax regulations expand in complexity.",
            "government_opportunities": "Judicial Member in Income Tax Appellate Tribunal (ITAT via Ministry of Law), Standing Counsel for Income Tax / CBIC in High Courts.",
            "private_opportunities": "Big 4 Tax Practices (EY, Deloitte, PwC, KPMG), Tier-1 Tax Law Firms (Vaish Associates, Lakshmikumaran & Sridharan), Corporate Tax Houses.",
            "higher_study_options": "LL.M. in International Taxation, Advanced Diplomas in Transfer Pricing.",
            "entrepreneurship_options": "Founding an independent boutique tax litigation and corporate GST advisory firm.",
            "source": "Bar Council of India / Income Tax Appellate Tribunal (ITAT)",
            "official_url": "https://itat.gov.in",
            "verification_status": "VERIFIED",
            "is_lesser_known": False,
            "career_family": "Law & Justice",
            "interest_clusters": "Law, Numbers, Business, Writing",
            "work_style": "Office, Court",
            "reality_check": "Combines intensive legal interpretation with detailed accounting balance sheets and numerical tax schedules.\nTax laws change annually with every Union Budget, requiring lifelong re-reading of amendments and notifications.\nHigh-stakes litigation: tax disputes routinely involve crores in revenue demands and penalties.",
            "next_steps": "Complete a law degree (preferably B.Com LL.B. or 5-year integrated law with strong accounting foundation).\nIntern with leading tax litigation advocates or Big 4 tax advisory teams.\nMaster the Income Tax Act, GST rules, and enroll with the State Bar Council.",
            "courses": [{"course_id": 26, "type": "PRIMARY"}, {"course_id": 27, "type": "PRIMARY"}],
            "exams": [],
            "routes": [{"title": "Path A: Tax Law Specialist", "type": "PRIMARY", "steps": "B.Com LL.B. / LL.B. -> Tax Internship -> AIBE Clearing -> Tax Associate -> ITAT Appellate Counsel -> Senior Tax Partner."}],
            "ladder": [
                {"stage": "Junior Tax Associate", "exp": "0-2 Years", "desc": "Drafts responses to tax scrutiny notices, prepares ITAT paper books, researches high court tax precedents."},
                {"stage": "Tax & GST Advocate", "exp": "2-6 Years", "desc": "Independently argues appeals before Commissioner (Appeals) and ITAT benches; structures commercial M&A tax."},
                {"stage": "Senior Tax Partner / Designated Senior Counsel", "exp": "6+ Years", "desc": "Leads multi-crore transfer pricing and constitutional tax challenges in High Courts and the Supreme Court."}
            ]
        }
    ]

def get_government_and_public_service_careers():
    return [
        {
            "title": "Indian Revenue Service (IRS) Officer",
            "short_name": "IRS Officer",
            "slug": "irs-revenue-officer",
            "category": "Government, Defence & Civil Services",
            "sub_category": "Civil Services & Revenue Administration",
            "industry": "Public Finance & Central Revenue Administration",
            "icon": "cash-coin",
            "short_description": "Administers direct taxes (Income Tax) or indirect taxes & customs across India.",
            "description": "Indian Revenue Service (IRS) Officers are premier Group 'A' central civil servants responsible for the collection, administration, and policy enforcement of direct taxes (IRS-IT under CBDT) or customs and indirect taxes (IRS-C&IT under CBIC). They investigate financial tax evasion, unearth unaccounted wealth, combat money laundering, and formulate national fiscal revenue policies.",
            "what_they_do": "They manage tax commissionerates, lead corporate tax evasion search and seizure operations (raids), direct customs enforcement at international airports and seaports, and represent India in bilateral tax treaty forums.",
            "day_to_day_work": "• Supervising tax assessment scrutiny across corporate and individual tax circles.\n• Leading search, seizure, and investigative operations against illicit financial networks.\n• Directing customs anti-smuggling vigilance at maritime container terminals and air cargo ports.\n• Formulating revenue collection targets and analyzing fiscal economic data.\n• Conducting appellate quasi-judicial hearings as Commissioner of Income Tax (Appeals).",
            "work_environment": "Central government revenue offices (Aayakar Bhawan), international ports, ministry headquarters.",
            "work_modes": "On-site / Government Office / Field Enforcement",
            "minimum_qualification": "Undergraduate (Any Bachelor's Degree - B.A., B.Sc, B.Com, B.Tech, MBBS)",
            "preferred_streams": "Any Stream (All graduates eligible for UPSC CSE)",
            "required_subjects": "General Studies, Optional Subject for UPSC CSE",
            "technical_skills": "Tax Administration, Fiscal Policy, Financial Forensics, Prevention of Money Laundering Act (PMLA), Customs Enforcement, Quasi-Judicial Adjudication",
            "soft_skills": "Uncompromising Integrity, Executive Leadership, Analytical Investigation, Discretion Under Pressure",
            "tools": "Project Insight (CBDT Data Analytics Platform), Customs EDI Systems, Financial Investigation Databases",
            "certifications": "UPSC Civil Services Examination (CSE) Selection, Induction Training at NADT Nagpur / NACIN Faridabad",
            "experience_level": "Entry Civil Servant to Secretary to Government of India",
            "career_growth": "Advance to Joint Commissioner, Commissioner of Income Tax, Principal Chief Commissioner, or CBDT/CBIC Chairman.",
            "internship_roles": "Officer Trainee at NADT / NACIN, District Field Attachment Trainee",
            "entry_level_roles": "Assistant Commissioner of Income Tax / Assistant Commissioner of Customs & GST",
            "average_salary": "₹10.0 - ₹25.0+ LPA (7th Central Pay Commission Scale)",
            "salary_indicative": "Assistant Commissioner (Pay Level 10): ₹56,100 basic + DA + HRA (~₹10 - 13 LPA in hand) | Commissioner (Level 14): ₹18 - 22 LPA | Principal Chief Commissioner / Chairman CBDT (Level 17): ₹25 - 28+ LPA plus official government bungalow, staff, and vehicle.",
            "future_scope": "Core sovereign function of the government: Essential for funding national infrastructure, social welfare, and economic security.",
            "government_opportunities": "Central Board of Direct Taxes (CBDT), Central Board of Indirect Taxes and Customs (CBIC), Enforcement Directorate (ED), Financial Intelligence Unit (FIU-IND).",
            "private_opportunities": "Constitutional public service. Post-retirement/deputation roles include multilateral organizations (IMF, World Bank, OECD).",
            "higher_study_options": "Master in Public Policy / Fiscal Economics sponsored by Government (IIMs, Harvard Kennedy School, LSE).",
            "entrepreneurship_options": "Not applicable during active government tenure.",
            "source": "Union Public Service Commission (UPSC) / NADT Nagpur",
            "official_url": "https://www.upsc.gov.in",
            "verification_status": "VERIFIED",
            "is_lesser_known": False,
            "career_family": "Public Administration",
            "interest_clusters": "Government, Numbers, Leadership, Society, Law",
            "work_style": "Government Office, Field",
            "reality_check": "Selection is through the fiercely competitive UPSC Civil Services Examination (acceptance rate under 0.1%).\nRequires managing massive revenue targets and complex corporate financial litigation.\nSubject to nationwide transfers every 3-4 years across regional directorates.",
            "next_steps": "Earn a Bachelor's degree in any discipline from a recognized university.\nPrepare thoroughly for the UPSC Civil Services Examination (Prelims, Mains, and Personality Test).\nUndergo 16 months of rigorous induction training at the National Academy of Direct Taxes (NADT Nagpur) or NACIN.",
            "courses": [{"course_id": 31, "type": "RELATED"}, {"course_id": 16, "type": "RELATED"}],
            "exams": [{"exam_id": 1, "importance": "PRIMARY"}],
            "routes": [{"title": "Path A: UPSC Civil Services Route", "type": "PRIMARY", "steps": "Any Degree -> UPSC CSE Prelims & Mains -> Personality Test -> IRS Allotment -> NADT Nagpur Training -> Assistant Commissioner."}],
            "ladder": [
                {"stage": "Assistant Commissioner", "exp": "0-4 Years", "desc": "Manages assessment circles, conducts tax scrutiny, issues assessment orders, leads field search teams."},
                {"stage": "Joint / Additional Commissioner", "exp": "4-10 Years", "desc": "Supervises multi-circle ranges, guides major corporate anti-evasion investigations and customs intelligence."},
                {"stage": "Commissioner / Principal Chief Commissioner", "exp": "10+ Years", "desc": "Heads state-wide revenue regions, adjudicates major appeals, advises Union Finance Ministry on direct/indirect tax policy."}
            ]
        },
        {
            "title": "Municipal Commissioner",
            "short_name": "Municipal Commissioner",
            "slug": "municipal-commissioner",
            "category": "Government, Defence & Civil Services",
            "sub_category": "Civil Services & Urban Administration",
            "industry": "Urban Governance & Local Municipal Administration",
            "icon": "buildings",
            "short_description": "Directs city municipal corporations, public utilities, urban infrastructure, and civic amenities.",
            "description": "Municipal Commissioners (often senior IAS or State Administrative Service officers) are chief executive officers of urban municipal corporations. They manage city infrastructure, solid waste management, drinking water supply, urban road networks, building regulation enforcement, property tax collections, and smart city modernization for millions of urban citizens.",
            "what_they_do": "They lead municipal corporation departments, implement city master plans, manage multi-crore civic budgets, respond to urban flooding and public health crises, and coordinate with elected city mayors and councilors.",
            "day_to_day_work": "• Reviewing city water supply, sanitation, and municipal solid waste processing metrics.\n• Inspecting ongoing urban infrastructure projects (flyovers, sewage treatment plants, storm drains).\n• Conducting municipal budget allocation and monitoring city property tax revenue.\n• Enforcing municipal building bylaws, anti-encroachment drives, and slum rehabilitation schemes.\n• Directing emergency civic disaster response during urban flash floods and disease outbreaks.",
            "work_environment": "Municipal Corporation headquarters, city field inspection sites.",
            "work_modes": "On-site / Government Office / Field",
            "minimum_qualification": "Undergraduate (Any Bachelor's Degree)",
            "preferred_streams": "Any Stream",
            "required_subjects": "Public Administration, Urban Governance",
            "technical_skills": "Urban Master Planning, Municipal Finance, Public Health Engineering, Solid Waste Logistics, Disaster Mitigation, Civic Law Enforcement",
            "soft_skills": "High Crisis Leadership, Political Navigational Tact, Citizen Empathy, Decisiveness",
            "tools": "Geographic Information Systems (GIS) Urban Portals, Municipal ERP, Smart City Command & Control Centers (ICCC)",
            "certifications": "UPSC Civil Services (IAS) / State Public Service Commission (State Administrative Service)",
            "experience_level": "Mid to Senior Executive Level",
            "career_growth": "Advance to Principal Secretary (Urban Development), Chief Secretary, or Union Urban Affairs Secretary.",
            "internship_roles": "IAS Probationer Urban Attachment, Municipal Governance Intern",
            "entry_level_roles": "Assistant Municipal Commissioner, Sub-Divisional Magistrate (SDM), Executive Officer",
            "average_salary": "₹11.0 - ₹25.0+ LPA (7th CPC Pay Scale)",
            "salary_indicative": "Executive Officer / Assistant Commissioner: ₹8 - 12 LPA | Municipal Commissioner (IAS Pay Level 11-13): ₹12 - 18 LPA | Commissioner of Tier-1 Mega Corporation (Level 14): ₹18 - 25+ LPA plus government bungalow, official vehicle, and administrative staff.",
            "future_scope": "Tremendous demand with rapid Indian urbanization, Smart Cities Mission, and large-scale urban infrastructure investments.",
            "government_opportunities": "Municipal Corporations across India (BMC Mumbai, BBMP Bengaluru, MCD Delhi, GHMC Hyderabad, Pune Municipal Corp, etc.), Ministry of Housing and Urban Affairs.",
            "private_opportunities": "Constitutional/Statutory public post; post-retirement advisory in global urban institutions (World Bank Urban Practice, UN-Habitat).",
            "higher_study_options": "Master in Urban Planning (M.Plan), Executive Urban Management Fellowships (LSE Cities, CEPT).",
            "entrepreneurship_options": "Not applicable during active government tenure.",
            "source": "Ministry of Housing and Urban Affairs (MoHUA) / State Urban Development Departments",
            "official_url": "https://mohua.gov.in",
            "verification_status": "VERIFIED",
            "is_lesser_known": False,
            "career_family": "Public Administration",
            "interest_clusters": "Government, Leadership, Society, Architecture, People",
            "work_style": "Government Office, Field",
            "reality_check": "One of the most intense, high-visibility public governance roles: Every pothole, water cut, or garbage delay brings immediate public and media scrutiny.\nRequires balancing administrative rules with elected political representatives (Mayors, Corporators, MLAs).\n24/7 on-call duty during monsoon flooding, civic emergencies, and building collapse crises.",
            "next_steps": "Earn a Bachelor's degree in any discipline.\nPrepare for and crack the UPSC Civil Services Examination (for IAS) or State Public Service Commission (for State Administrative Service).\nServe in district subdivisions before posting as Chief Executive of Municipal Councils or Corporations.",
            "courses": [{"course_id": 31, "type": "RELATED"}, {"course_id": 63, "type": "RELATED"}],
            "exams": [{"exam_id": 1, "importance": "PRIMARY"}],
            "routes": [{"title": "Path A: Civil Services Route", "type": "PRIMARY", "steps": "Bachelor's Degree -> UPSC CSE / State PSC -> Administrative Service Allotment -> SDM / Assistant Commissioner -> Municipal Commissioner."}],
            "ladder": [
                {"stage": "Assistant Municipal Commissioner / SDM", "exp": "0-4 Years", "desc": "Oversees municipal ward operations, anti-encroachment actions, revenue recovery, citizen grievance redressed."},
                {"stage": "Municipal Commissioner (Tier-2 City)", "exp": "4-10 Years", "desc": "Heads city municipal corporation, directs Smart City projects, manages sanitation and water utilities."},
                {"stage": "Commissioner (Metropolitan Mega-City)", "exp": "10+ Years", "desc": "Commands billion-dollar municipal budgets for metro cities (Mumbai, Bengaluru, Delhi), directs urban master plans."}
            ]
        },
        {
            "title": "Block Development Officer (BDO)",
            "short_name": "BDO",
            "slug": "block-development-officer",
            "category": "Government, Defence & Civil Services",
            "sub_category": "Rural Administration & Development",
            "industry": "Rural Development & Panchayati Raj",
            "icon": "tree",
            "short_description": "Executes government rural development, poverty alleviation, and Panchayati Raj schemes across rural blocks.",
            "description": "Block Development Officers (BDOs) are key grassroots administrative officers who coordinate and implement government development initiatives across a rural development block (covering 50 to 100+ villages). They oversee MGNREGA employment, rural housing (PMAY-G), rural road construction (PMGSY), drinking water supply, and empower Panchayati Raj village institutions.",
            "what_they_do": "They manage rural development block staff, supervise village Panchayat secretaries, inspect rural public works projects, disburse welfare pensions, and coordinate district rural development agencies (DRDA).",
            "day_to_day_work": "• Inspecting rural MGNREGA worksites, check-dams, and community pond construction.\n• Reviewing construction progress of rural houses under Pradhan Mantri Awas Yojana (PMAY-G).\n• Convening monthly Block Development Committee meetings with elected Panchayat Pramukhs.\n• Auditing government welfare pension disbursements and rural self-help group (SHG) microcredit.\n• Directing rural disaster relief during droughts, locust invasions, and monsoon floods.",
            "work_environment": "Block Development Office, rural village inspections, District Collectorate meetings.",
            "work_modes": "On-site / Field / Government Office",
            "minimum_qualification": "Undergraduate (Any Bachelor's Degree)",
            "preferred_streams": "Any Stream",
            "required_subjects": "General Studies, Rural Economy, Public Administration",
            "technical_skills": "Panchayati Raj Administration, MGNREGA Work Verification, Rural Housing Schemes, Public Fund Auditing, Grassroots Grievance Redressal",
            "soft_skills": "Community Empathy, Field Leadership, Resolving Rural Disputes, Administrative Stamina",
            "tools": "NREGA Soft Portal, AwaasSoft, e-GramSwaraj Portal, GIS Village Asset Trackers",
            "certifications": "State Public Service Commission (State PSC / State Civil Services Examination)",
            "experience_level": "Entry to Mid Level",
            "career_growth": "Advance to District Development Officer (DDO), Chief Development Officer (CDO), and Joint Secretary in Rural Development.",
            "internship_roles": "Rural Attachment Trainee, State Administrative Training Institute (ATI) Trainee",
            "entry_level_roles": "Block Development Officer (BDO), Assistant Project Officer (DRDA)",
            "average_salary": "₹6.5 - ₹13.0 LPA (State 7th Pay Commission Scale)",
            "salary_indicative": "Entry-Level BDO (Pay Level 9/10): ₹53,100 basic + DA + allowances (~₹6.5 - 9 LPA in hand) | Senior BDO / CDO: ₹10 - 15 LPA plus government staff quarter and official inspection vehicle.",
            "future_scope": "Indispensable anchor of India's rural economy: Responsible for the last-mile delivery of government welfare funds to millions.",
            "government_opportunities": "State Rural Development & Panchayati Raj Departments (UP, Bihar, MP, Rajasthan, Maharashtra, etc.), National Institute of Rural Development (NIRDPR).",
            "private_opportunities": "State civil service post. Later transitions include rural philanthropy foundations (Tata Trusts, Aga Khan Rural Support).",
            "higher_study_options": "PG Diploma in Rural Development, Master in Development Studies.",
            "entrepreneurship_options": "Not applicable during active civil service.",
            "source": "State Public Service Commissions / Ministry of Rural Development",
            "official_url": "https://rural.nic.in",
            "verification_status": "VERIFIED",
            "is_lesser_known": False,
            "career_family": "Public Administration",
            "interest_clusters": "Government, Society, Helping, Outdoor, Leadership",
            "work_style": "Field, Government Office",
            "reality_check": "Extensive rural field inspections on rough country roads in all weather conditions.\nRequires managing complex local village politics and intense pressure from local political representatives.\nVital role for candidates who want to make a real, visible difference in rural villagers' lives.",
            "next_steps": "Earn a Bachelor's degree in any discipline from a recognized university.\nPrepare for your State Public Service Commission (State PCS / Combined State Civil Services Examination).\nComplete state administrative academy training and take charge of your assigned rural development block.",
            "courses": [{"course_id": 31, "type": "RELATED"}, {"course_id": 66, "type": "RELATED"}],
            "exams": [{"exam_id": 1, "importance": "RECOMMENDED"}],
            "routes": [{"title": "Path A: State PCS Route", "type": "PRIMARY", "steps": "Any Degree -> State PSC Civil Services Exam -> Rural Development Service Allotment -> ATI Training -> Block Development Officer (BDO)."}],
            "ladder": [
                {"stage": "Block Development Officer (BDO)", "exp": "0-6 Years", "desc": "Administers development schemes across 50-100 villages, inspects MGNREGA, coordinates village Panchayats."},
                {"stage": "District Development Officer (DDO) / Deputy Collector", "exp": "6-12 Years", "desc": "Supervises multiple blocks, directs district poverty alleviation programs, audits rural expenditures."},
                {"stage": "Chief Development Officer (CDO) / Joint Secretary", "exp": "12+ Years", "desc": "Leads all rural development across an entire district, formulates state-level Panchayati Raj policies."}
            ]
        },
        {
            "title": "Government Statistician (Indian Statistical Service - ISS)",
            "short_name": "Government Statistician",
            "slug": "government-statistician-iss",
            "category": "Government, Defence & Civil Services",
            "sub_category": "Statistical & Economic Administration",
            "industry": "National Statistics & Economic Planning",
            "icon": "graph-up-arrow",
            "short_description": "Designs national sample surveys, computes GDP, inflation (CPI), and guides government economic policy.",
            "description": "Indian Statistical Service (ISS) Officers are specialized Group 'A' central civil servants who manage India's official statistical system under the Ministry of Statistics and Programme Implementation (MoSPI). They design nationwide socio-economic surveys (NSSO), calculate Gross Domestic Product (GDP), Consumer Price Index (CPI inflation), Index of Industrial Production (IIP), and census analytics.",
            "what_they_do": "They design rigorous mathematical survey sampling methodologies, audit national economic indicators, manage large-scale data systems, and advise NITI Aayog and central ministries on data-driven policy planning.",
            "day_to_day_work": "• Formulating sampling design and stratification for National Sample Survey (NSS) rounds.\n• Analyzing large-scale economic data to compute quarterly GDP estimates and retail inflation indices.\n• Auditing field survey data collected across states using statistical error checks.\n• Collaborating with international statistical agencies (UN Statistical Commission, IMF).\n• Publishing the Annual Survey of Industries (ASI) and Periodic Labour Force Survey (PLFS).",
            "work_environment": "MoSPI headquarters (Sardar Patel Bhawan, New Delhi), National Statistical Office (NSO) regional centers, NITI Aayog.",
            "work_modes": "On-site / Government Office / Hybrid",
            "minimum_qualification": "Undergraduate / Postgraduate with Statistics / Mathematical Statistics / Applied Statistics",
            "preferred_streams": "Science / Arts (with Statistics / Mathematics)",
            "required_subjects": "Statistics, Mathematical Statistics, Mathematics, Economics",
            "technical_skills": "Survey Sampling Theory, Econometrics, Biostatistics, National Income Accounting, R / Python / STATA, Big Data Analytics in Governance",
            "soft_skills": "Mathematical Rigor, Intellectual Objectivity, Analytical Integrity, Clear Quantitative Presentation",
            "tools": "R, Python, STATA, SAS, MoSPI Data Portals, Official Microdata Portals",
            "certifications": "UPSC Indian Statistical Service (ISS) Examination Selection",
            "experience_level": "Entry Civil Servant to Chief Statistician of India",
            "career_growth": "Advance to Joint Director, Deputy Director General (DDG), Additional Director General (ADG), and Chief Statistician of India.",
            "internship_roles": "ISS Probationer at NASA (National Academy of Statistical Administration), NSSO Field Trainee",
            "entry_level_roles": "Assistant Director (ISS), Statistical Officer",
            "average_salary": "₹10.0 - ₹24.0+ LPA (7th Central Pay Commission Scale)",
            "salary_indicative": "Assistant Director (Pay Level 10): ₹56,100 basic + DA + allowances (~₹10 - 13 LPA in hand) | Deputy Director General (Level 14): ₹18 - 22 LPA | Chief Statistician of India (Secretary Rank, Level 17): ₹25 - 28+ LPA plus official government perks.",
            "future_scope": "Critically essential as governance becomes completely data-driven and algorithmic across welfare targeting and national planning.",
            "government_opportunities": "Ministry of Statistics & Programme Implementation (MoSPI), NITI Aayog, Reserve Bank of India (DSIM), Ministry of Finance, Ministry of Health.",
            "private_opportunities": "Sovereign civil service post; international career opportunities with United Nations Statistics Division, World Bank, and IMF.",
            "higher_study_options": "Ph.D. in Statistics / Econometrics, International Fellowships in Official Statistics.",
            "entrepreneurship_options": "Not applicable during active government tenure.",
            "source": "Union Public Service Commission (UPSC) / MoSPI",
            "official_url": "https://www.mospi.gov.in",
            "verification_status": "VERIFIED",
            "is_lesser_known": True,
            "career_family": "Public Administration",
            "interest_clusters": "Numbers, Science, Government, Research",
            "work_style": "Government Office",
            "reality_check": "Requires formal university qualification in Statistics or Mathematical Statistics (unlike general civil services which allow any degree).\nSelection is through the rigorous UPSC Indian Statistical Service (ISS) competitive exam testing advanced mathematical statistics.\nDemands unwavering commitment to scientific data integrity and statistical accuracy.",
            "next_steps": "Earn a Bachelor's degree with Statistics/Mathematical Statistics as a major subject, or pursue M.Sc in Statistics.\nPrepare for the UPSC Indian Statistical Service (ISS) Examination (covering General English, General Studies, Statistics I, II, III & IV).\nComplete 2 years of probationary training at the National Academy of Statistical Administration (NASA Greater Noida).",
            "courses": [{"course_id": 16, "type": "PRIMARY"}, {"course_id": 31, "type": "RELATED"}],
            "exams": [{"exam_id": 40, "importance": "PRIMARY"}],
            "routes": [{"title": "Path A: UPSC ISS Route", "type": "PRIMARY", "steps": "B.Sc / M.Sc Statistics -> UPSC ISS Examination -> Interview -> NASA Training -> Assistant Director (ISS)."}],
            "ladder": [
                {"stage": "Assistant Director", "exp": "0-4 Years", "desc": "Manages field survey validation, oversees sample tabulations, analyzes socio-economic data."},
                {"stage": "Deputy Director / Joint Director", "exp": "4-10 Years", "desc": "Directs national index computations (CPI, IIP), designs survey methodologies, liaises with central ministries."},
                {"stage": "Deputy Director General / Chief Statistician of India", "exp": "10+ Years", "desc": "Heads the National Statistical Office (NSO), advises Cabinet on GDP data, represents India at the UN."}
            ]
        }
    ]

def get_defence_and_uniformed_careers():
    return [
        {
            "title": "Indian Army Commissioned Officer",
            "short_name": "Army Officer",
            "slug": "army-commissioned-officer",
            "category": "Government, Defence & Civil Services",
            "sub_category": "Defence & Armed Forces",
            "industry": "National Defence & Military Operations",
            "icon": "shield-shaded",
            "short_description": "Commands combat troops, armor, artillery, and tactical operations protecting national sovereignty.",
            "description": "Indian Army Commissioned Officers are military leaders who command combat arms (Infantry, Armoured Corps, Artillery, Mechanized Infantry), combat support arms (Engineers, Signals, Army Aviation), and services. They lead soldiers in high-altitude border security, counter-insurgency operations, tactical warfare, international UN peacekeeping, and national disaster relief.",
            "what_they_do": "Officers lead tactical infantry platoons and battalions, direct artillery firepower, plan air-ground military maneuvers, inspire and command troops under live fire, and defend territorial borders.",
            "day_to_day_work": "• Leading morning physical training (PT), weapon drills, and tactical field maneuvers.\n• Inspecting border operational defense preparedness at forward Line of Control (LoC) posts.\n• Planning live-fire tactical firing exercises and counter-terrorism cordons.\n• Managing troop welfare, discipline, armory security, and field equipment maintenance.\n• Directing emergency civilian rescue and relief operations during national natural catastrophes.",
            "work_environment": "Forward border posts (Himalayan high-altitude, deserts, jungles), military cantonments, field stations.",
            "work_modes": "Field / On-site / High-Altitude / Combat Post",
            "minimum_qualification": "Undergraduate (Any Bachelor's Degree) for CDS / Class 12 (PCM) for NDA and TES Entry",
            "preferred_streams": "Any Stream (for NDA/CDS Army Wing); PCM for Technical Arms",
            "required_subjects": "General Studies, English, Mathematics (for NDA)",
            "technical_skills": "Tactical Military Strategy, Small Arms & Heavy Weaponry, Map Reading & Land Navigation, High-Altitude Survival, Combat Leadership, Military Logistics",
            "soft_skills": "Indomitable Courage, Selfless Loyalty, Decisiveness in Chaos, Moral Integrity, Physical Stamina",
            "tools": "Military Communication Radios, Tactical Weapons, GPS / Night Vision Optics, Armored Vehicles",
            "certifications": "Commission from President of India upon graduation from IMA Dehradun / OTA Chennai / NDA Khadakwasla",
            "experience_level": "Lieutenant to General (Chief of Army Staff)",
            "career_growth": "Advance from Lieutenant to Captain, Major, Lieutenant Colonel, Colonel (Commanding Officer), Brigadier, Major General, and Lieutenant General.",
            "internship_roles": "Gentleman Cadet at Indian Military Academy (IMA) / Officer Training Academy (OTA)",
            "entry_level_roles": "Lieutenant (Platoon Commander)",
            "average_salary": "₹11.0 - ₹28.0+ LPA (Military Pay Matrix Level 10 + MSP)",
            "salary_indicative": "Lieutenant (Entry): ₹56,100 basic + ₹15,500 Military Service Pay (MSP) + High Altitude / Field Area Allowance + DA (~₹11 - 15 LPA in hand) | Colonel: ₹20 - 24 LPA | Lt. General: ₹25 - 30+ LPA plus complete military cantonment housing, medical (ECHS), canteen, and orderly support.",
            "future_scope": "Prestigious, permanent sovereign leadership career defending the nation across modernized land, drone, and electronic warfare environments.",
            "government_opportunities": "Indian Army (Infantry, Armoured, Artillery, Engineers, Signals, Army Aviation, Intelligence Corps), UN Peacekeeping Forces.",
            "private_opportunities": "Sovereign military service. Post-service career opportunities include corporate security, aerospace leadership, and defense manufacturing.",
            "higher_study_options": "Defense Services Staff College (DSSC Wellington), Higher Command Course, National Defence College (NDC).",
            "entrepreneurship_options": "Defense technology startup, private security and risk advisory post-service.",
            "source": "Indian Army / Join Indian Army Portal",
            "official_url": "https://joinindianarmy.nic.in",
            "verification_status": "VERIFIED",
            "is_lesser_known": False,
            "career_family": "Defence & Security",
            "interest_clusters": "Government, Outdoor, Leadership, Sports, Hands-on",
            "work_style": "Outdoor, Field",
            "reality_check": "Involves supreme physical and mental rigors: Leading troops in extreme conditions (-40°C in Siachen glaciers to 50°C in Thar desert).\nSupreme personal commitment: Facing live-fire combat risks and prolonged separation from family during field postings.\nEntry through UPSC NDA / CDS followed by the rigorous 5-day Services Selection Board (SSB) interview.",
            "next_steps": "After Class 12: Appear for UPSC NDA Examination (National Defence Academy, Pune).\nAfter Graduation: Appear for UPSC CDS Examination (Combined Defence Services) for IMA Dehradun or OTA Chennai.\nClear the 5-day Services Selection Board (SSB) interview, medical examination, and complete military academy training.",
            "courses": [{"course_id": 31, "type": "RELATED"}, {"course_id": 1, "type": "RELATED"}],
            "exams": [{"exam_id": 1, "importance": "RECOMMENDED"}],
            "routes": [
                {"title": "Path A: After 12th via NDA", "type": "PRIMARY", "steps": "Class 12 -> UPSC NDA Exam -> 5-Day SSB Interview -> NDA Khadakwasla (3 yrs) -> IMA Dehradun (1 yr) -> Commissioned as Lieutenant."},
                {"title": "Path B: After Graduation via CDS", "type": "ALTERNATIVE", "steps": "Any Graduation -> UPSC CDS Exam -> 5-Day SSB Interview -> IMA Dehradun (1.5 yrs) -> Commissioned as Lieutenant."}
            ],
            "ladder": [
                {"stage": "Lieutenant / Captain", "exp": "0-6 Years", "desc": "Commands combat platoons of 30 soldiers, leads forward patrols, coordinates company-level firepower."},
                {"stage": "Major / Lieutenant Colonel", "exp": "6-13 Years", "desc": "Second-in-Command of combat battalions, plans brigade-level logistics, attends Staff College (DSSC)."},
                {"stage": "Colonel / Brigadier / General", "exp": "13+ Years", "desc": "Commands 1,000+ soldier infantry/armored battalions, leads independent brigades, commands military divisions."}
            ]
        },
        {
            "title": "Indian Air Force Flying Branch Officer (Fighter / Transport / Helicopter Pilot)",
            "short_name": "Air Force Pilot",
            "slug": "air-force-flying-officer",
            "category": "Government, Defence & Civil Services",
            "sub_category": "Defence & Armed Forces",
            "industry": "Military Aviation & Air Defence",
            "icon": "airplane",
            "short_description": "Pilots supersonic fighter aircraft, transport planes, and combat helicopters defending sovereign skies.",
            "description": "Indian Air Force (IAF) Flying Branch Officers are elite military pilots who operate multi-role supersonic fighter aircraft (Rafale, Su-30MKI, Tejas), heavy strategic transport aircraft (C-17 Globemaster, C-130J), and tactical combat helicopters (Apache, Chinook, Mi-17). They execute air combat maneuvers, precision aerial strikes, air defense interception, and humanitarian airlift operations.",
            "what_they_do": "They fly complex high-speed aerial missions, perform tactical low-altitude bombing, conduct air-to-air refueling, execute search and rescue, and coordinate air defense radar networks.",
            "day_to_day_work": "• Pre-flight mission briefing on weather, tactical airspace, and radar threats.\n• Piloting supersonic fighter jets or tactical transport sorties during daytime and night missions.\n• Practicing high-G air combat maneuvering (ACM) and simulated aerial dogfights.\n• Operating flight simulators to rehearse complex emergency and bad-weather landings.\n• Debriefing flight telemetry, target camera recordings, and weapon delivery accuracy.",
            "work_environment": "IAF Forward Air Bases, cockpits, tactical flight simulation complexes.",
            "work_modes": "Cockpit / Military Airbase / High-G Aviation",
            "minimum_qualification": "Undergraduate (B.Tech / B.E. or B.Sc with Physics & Maths) or Class 12 (PCM) for NDA",
            "preferred_streams": "Science (PCM)",
            "required_subjects": "Physics, Mathematics",
            "technical_skills": "Supersonic Flight Dynamics, Aerial Combat Tactics, Avionics Systems, Radar Interception, Cockpit Instrument Flight (IFR), Night Vision Flying",
            "soft_skills": "Exceptional Spatial Awareness, Instantaneous Reflexes, Calmness Under 9G Stress, Mission Dedication",
            "tools": "Fighter Aircraft Cockpits (HUD, Fly-By-Wire), Flight Simulators, Helmet Mounted Cueing Systems (HMCS)",
            "certifications": "President's Commission, Wings of the Indian Air Force awarded by Air Force Academy (AFA Dundigal)",
            "experience_level": "Flying Officer to Air Chief Marshal",
            "career_growth": "Advance from Flying Officer to Flight Lieutenant, Squadron Leader, Wing Commander, Group Captain, Air Commodore, and Air Vice Marshal.",
            "internship_roles": "Flight Cadet at Air Force Academy (AFA Dundigal)",
            "entry_level_roles": "Flying Officer (Pilot)",
            "average_salary": "₹12.0 - ₹30.0+ LPA (Military Pay Matrix Level 10 + Flying Allowance)",
            "salary_indicative": "Flying Officer (Entry): ₹56,100 basic + ₹15,500 MSP + ₹25,000 Flying Branch Allowance + DA (~₹12 - 16 LPA in hand) | Wing Commander: ₹22 - 26 LPA | Air Marshal: ₹26 - 32+ LPA plus military cantonment housing and flight officer privileges.",
            "future_scope": "Prestigious sovereign aviation career at the cutting-edge of supersonic fifth-generation stealth fighters and drone combat wingmen.",
            "government_opportunities": "Indian Air Force (Fighter, Transport, and Helicopter Squadrons), Defence Research & Development Organisation (DRDO flight test centers).",
            "private_opportunities": "Military service. Post-service transition to commercial airline captaincy (Air India, IndiGo) is seamless due to thousands of pilot flight hours.",
            "higher_study_options": "Air Force Test Pilot School (ASTE Bengaluru), Defense Services Staff College (DSSC).",
            "entrepreneurship_options": "Aviation consulting, unmanned aerial vehicle (drone) systems post-service.",
            "source": "Indian Air Force / AFCAT Portal",
            "official_url": "https://afcat.cdac.in",
            "verification_status": "VERIFIED",
            "is_lesser_known": False,
            "career_family": "Defence & Security",
            "interest_clusters": "Machines, Travel, Leadership, Government, Hands-on",
            "work_style": "Cockpit, Airport, Outdoor",
            "reality_check": "CPSS (Computerised Pilot Selection System) testing: You get only ONE attempt in your entire lifetime to clear the CPSS/PABT pilot aptitude test.\nStrict physical and medical standards: Flawless eyesight (6/6 vision criteria for fighter stream), spinal health, and high-G tolerance.\nRequires rigorous 18-month intense flight training at Air Force Academy Dundigal.",
            "next_steps": "After Class 12: Clear UPSC NDA Exam (Air Force Flying Branch - requires Physics & Maths).\nAfter Graduation: Appear for AFCAT (Air Force Common Admission Test) or UPSC CDS (Air Force Academy).\nClear the 5-day Air Force Selection Board (AFSB), pass the one-chance CPSS pilot test, and graduate from Air Force Academy Dundigal.",
            "courses": [{"course_id": 1, "type": "PRIMARY"}, {"course_id": 12, "type": "RELATED"}],
            "exams": [{"exam_id": 24, "importance": "PRIMARY"}],
            "routes": [
                {"title": "Path A: NDA Air Force Wing", "type": "PRIMARY", "steps": "Class 12 (PCM) -> NDA Exam -> AFSB & CPSS -> NDA (3 yrs) + AFA (1.5 yrs) -> Commissioned as Flying Officer."},
                {"title": "Path B: AFCAT / CDS Entry", "type": "ALTERNATIVE", "steps": "B.Tech / B.Sc (Physics & Maths) -> AFCAT / CDS Exam -> AFSB & CPSS -> AFA Dundigal Flight Training -> Fighter / Transport Pilot."}
            ],
            "ladder": [
                {"stage": "Flying Officer / Flight Lieutenant", "exp": "0-6 Years", "desc": "Flies operational fighter, transport, or helicopter sorties; masters formation flying and low-level tactical navigation."},
                {"stage": "Squadron Leader / Wing Commander", "exp": "6-13 Years", "desc": "Commands flight squadrons, plans air operations, conducts advanced weapon delivery missions."},
                {"stage": "Group Captain / Air Commodore", "exp": "13+ Years", "desc": "Commands entire frontline Air Force Operational Stations/Bases, directs air defense wings."}
            ]
        },
        {
            "title": "Central Armed Police Forces (CAPF) Assistant Commandant",
            "short_name": "CAPF Assistant Commandant",
            "slug": "capf-assistant-commandant",
            "category": "Government, Defence & Civil Services",
            "sub_category": "Paramilitary & Border Security",
            "industry": "Internal Security & Border Enforcement",
            "icon": "shield-lock",
            "short_description": "Commands armed paramilitary companies in BSF, CRPF, CISF, ITBP, and SSB for border and internal security.",
            "description": "Assistant Commandants in the Central Armed Police Forces (CAPF - BSF, CRPF, CISF, ITBP, SSB) are Group 'A' central gazetted officers who command armed paramilitary companies of 135+ troops. Under the Ministry of Home Affairs (MHA), they safeguard international land borders, combat Left-Wing Extremism (Naxalism), protect vital nuclear/space/industrial infrastructure, and conduct anti-terrorist counter-insurgency operations.",
            "what_they_do": "They command paramilitary armed companies, lead border security patrols along Pakistan/Bangladesh/China/Nepal borders, manage civil riot control, and secure critical airports and industrial assets.",
            "day_to_day_work": "• Leading armed border patrols and tactical ambush operations along international borders.\n• Directing anti-Naxalite search-and-destroy jungle warfare patrols in central India.\n• Supervising terminal aviation security, frisking protocols, and anti-hijack teams at airports (CISF).\n• Conducting company weapon maintenance, physical training, and troop grievance durbars.\n• Coordinating with state civil police during election security and communal riot control duties.",
            "work_environment": "International borders, jungle warfare outposts, commercial international airports, industrial complexes.",
            "work_modes": "Field / Border Post / On-site",
            "minimum_qualification": "Undergraduate (Any Bachelor's Degree)",
            "preferred_streams": "Any Stream",
            "required_subjects": "General Studies, Essay & Comprehension",
            "technical_skills": "Paramilitary Company Tactics, Border Management, Counter-Insurgency, Riot Control (L&O), Weapons Handling, Critical Asset Security",
            "soft_skills": "Physical Bravery, Command Leadership, Unwavering Discipline, High Stamina",
            "tools": "Assault Rifles, Night Vision Monoculars, Thermal Imagers, Anti-Drone Systems, Company Wireless Radios",
            "certifications": "UPSC CAPF (Assistant Commandants) Examination Selection, Academy Graduation",
            "experience_level": "Entry Officer to Director General (DG)",
            "career_growth": "Advance to Deputy Commandant, Second-in-Command (2IC), Commandant (Battalion Commander), and Inspector General (IG).",
            "internship_roles": "Officer Trainee at BSF Academy Tekanpur / CRPF Academy Kadarpur",
            "entry_level_roles": "Assistant Commandant (Company Commander)",
            "average_salary": "₹9.5 - ₹22.0 LPA (7th Central Pay Commission Scale)",
            "salary_indicative": "Assistant Commandant (Pay Level 10): ₹56,100 basic + DA + Hard Area / Risk Allowances (~₹9.5 - 13 LPA in hand) | Commandant (Battalion Commander): ₹16 - 20 LPA | Inspector General: ₹22 - 26+ LPA plus government accommodation, staff, and official transport.",
            "future_scope": "Continuous national recruitment to protect growing borders, secure critical national assets, and maintain internal security.",
            "government_opportunities": "Ministry of Home Affairs - Border Security Force (BSF), Central Reserve Police Force (CRPF), Central Industrial Security Force (CISF), Indo-Tibetan Border Police (ITBP), Sashastra Seema Bal (SSB).",
            "private_opportunities": "Paramilitary service. Post-service opportunities in corporate enterprise security (Tata, Reliance, Adani Ports).",
            "higher_study_options": "Internal Security Diplomas at Rashtriya Raksha University (RRU).",
            "entrepreneurship_options": "Not applicable during active government tenure.",
            "source": "Union Public Service Commission (UPSC) / Ministry of Home Affairs",
            "official_url": "https://www.upsc.gov.in",
            "verification_status": "VERIFIED",
            "is_lesser_known": False,
            "career_family": "Defence & Security",
            "interest_clusters": "Government, Outdoor, Leadership, Sports, Hands-on",
            "work_style": "Field, Outdoor",
            "reality_check": "Demanding operational postings in remote border posts (Rann of Kutch deserts, snowy Ladakh heights, dense Bastar jungles).\nRigorous physical efficiency test (PET) includes 100m sprint, 800m run, long jump, and shot put.\nHigh responsibility: Directly commands over 135 armed soldiers from day one after academy graduation.",
            "next_steps": "Earn a Bachelor's degree in any discipline from a recognized university.\nPrepare for the UPSC CAPF (Assistant Commandants) Examination (Paper I: General Ability & Intelligence, Paper II: General Studies, Essay & Comprehension).\nClear the Physical Efficiency Test (PET), Medical Standards Test, and UPSC Personality Interview.",
            "courses": [{"course_id": 31, "type": "RELATED"}, {"course_id": 16, "type": "RELATED"}],
            "exams": [{"exam_id": 1, "importance": "RECOMMENDED"}],
            "routes": [{"title": "Path A: UPSC CAPF (AC) Route", "type": "PRIMARY", "steps": "Any Degree -> UPSC CAPF (AC) Exam -> Physical Test (PET) -> Interview -> Force Academy (BSF/CRPF/CISF) -> Assistant Commandant."}],
            "ladder": [
                {"stage": "Assistant Commandant (AC)", "exp": "0-5 Years", "desc": "Commands an armed company of 135 troops, conducts active border vigilance and internal security operations."},
                {"stage": "Deputy Commandant / 2IC", "exp": "5-11 Years", "desc": "Second-in-Command of a 1,000-strong battalion, plans operations, supervises battalion logistics and intelligence."},
                {"stage": "Commandant (CO) / DIG", "exp": "11+ Years", "desc": "Commands entire armed battalion, oversees multi-battalion sectors along international frontiers or conflict zones."}
            ]
        }
    ]
