"""
scripts/catalog_expanded_part4.py
Domain I: Agriculture & Rural Economy (9 careers)
Domain J: Environment & Sustainability (8 careers)
Domain K: Social Science (7 careers)
"""

def get_agriculture_and_rural_careers():
    return [
        {
            "title": "Agronomist & Field Crop Scientist",
            "short_name": "Agronomist",
            "slug": "agronomist-crop-scientist",
            "category": "Agriculture, Food Technology & Environment",
            "sub_category": "Agronomy & Crop Science",
            "industry": "Agriculture, Seed Technology & Agri-Inputs",
            "icon": "flower2",
            "short_description": "Optimizes crop yields, soil fertility, irrigation scheduling, and sustainable cropping systems.",
            "description": "Agronomists are agricultural scientists who specialize in crop production, field soil management, weed control, and sustainable crop rotation. They conduct agricultural field trials, diagnose plant nutrient deficiencies, develop climate-resilient crop varieties, and advise commercial farmers and agribusinesses on maximizing harvest yields while conserving natural resources.",
            "what_they_do": "They design crop management plans, formulate targeted chemical/biological fertilizer schedules, conduct field efficacy trials for seed and pesticide companies, and implement precision farming techniques.",
            "day_to_day_work": "• Inspecting agricultural field plots for pest infestations, fungal rusts, and nitrogen deficiencies.\n• Designing multi-crop rotation and drip irrigation schedules based on soil moisture sensors.\n• Setting up randomized block design (RBD) field trial plots for new hybrid crop seeds.\n• Advising farmer producer organizations (FPOs) on sustainable agronomic practices.\n• Analyzing soil chemistry reports and formulating micronutrient foliar spray schedules.",
            "work_environment": "Agricultural research stations, corporate experimental seed farms, rural field plots, greenhouses.",
            "work_modes": "Field / Farm / Research Station",
            "minimum_qualification": "Undergraduate (B.Sc Hons Agriculture - 4 Years) / M.Sc Agronomy",
            "preferred_streams": "Science (PCB / PCM / Agriculture stream)",
            "required_subjects": "Agriculture, Biology, Chemistry",
            "technical_skills": "Crop Physiology, Soil Fertility Management, Weed Science, Irrigation Water Scheduling, Integrated Nutrient Management (INM), Field Trial Statistical Design",
            "soft_skills": "Farmer Communication, Field Observation, Passion for Nature, Scientific Problem Solving",
            "tools": "Soil Moisture Tensiometers, Chlorophyll Meters (SPAD), Drone Multispectral Imagery, Handheld Soil Testing Kits",
            "certifications": "Indian Council of Agricultural Research (ICAR) Accreditation, Certified Crop Advisor (CCA)",
            "experience_level": "Entry to Senior Scientist",
            "career_growth": "Advance to Senior Agronomist, Lead Crop Scientist, Agronomy Director, or ICAR Principal Scientist.",
            "internship_roles": "Rural Agricultural Work Experience (RAWE) Trainee, Seed Farm Intern",
            "entry_level_roles": "Junior Agronomist, Agricultural Officer, Field Technical Executive",
            "average_salary": "₹4.5 - ₹12.0 LPA (Indicative range)",
            "salary_indicative": "Field Agronomist (Agri-Inputs): ₹4.5 - 7 LPA | Research Agronomist in Seed MNC (3-6 yrs): ₹8 - 14 LPA | Lead Agronomist / ICAR Scientist: ₹15 - 26+ LPA. Indicative figures from ICAR and agribusiness salary surveys.",
            "future_scope": "Critically essential to guarantee national food security, combat climate change droughts, and adopt sustainable regenerative agriculture.",
            "government_opportunities": "ICAR Institutes (IARI Pusa, CRIDA, CRRI), State Agricultural Universities (SAUs), NABARD, State Agriculture Departments (Agricultural Development Officer - ADO).",
            "private_opportunities": "Syngenta India, Bayer CropScience, UPL Limited, Coromandel International, Godrej Agrovet, Mahindra Agri Solutions.",
            "higher_study_options": "M.Sc in Agronomy, Ph.D. in Agronomy / Crop Physiology (via ICAR AIEEA-PG / JRF).",
            "entrepreneurship_options": "Founding a precision agronomy advisory company, soil testing laboratory, or customized organic fertilizer firm.",
            "source": "Indian Council of Agricultural Research (ICAR)",
            "official_url": "https://icar.org.in",
            "verification_status": "VERIFIED",
            "is_lesser_known": False,
            "career_family": "Agriculture & Rural",
            "interest_clusters": "Nature, Science, Agriculture, Outdoor, Hands-on",
            "work_style": "Farm, Field, Lab",
            "reality_check": "Not just traditional farming: A rigorous, high-tech applied biological and soil science profession.\nRequires significant outdoor field work under blazing sun and humid monsoon field conditions.\nRequires ICAR-accredited B.Sc (Hons) Agriculture for eligibility in top government and corporate seed scientist roles.",
            "next_steps": "Pass Class 12 with Physics, Chemistry, and Biology/Maths or Agriculture with at least 50% marks.\nAppear for ICAR CUET-UG or State Agricultural Entrance Tests (e.g. KCET, MHT-CET, MP PAT) for B.Sc (Hons) Agriculture.\nComplete the compulsory Rural Agricultural Work Experience (RAWE) semester and pursue M.Sc in Agronomy.",
            "courses": [{"course_id": 8, "type": "PRIMARY"}],
            "exams": [],
            "routes": [{"title": "Path A: ICAR Agriculture Route", "type": "PRIMARY", "steps": "12th (PCB/PCM) -> CUET / State Agri CET -> B.Sc (Hons) Agriculture (4 yrs) -> RAWE Internship -> ICAR JRF -> M.Sc Agronomy -> Crop Scientist."}],
            "ladder": [
                {"stage": "Field Agronomist / Officer", "exp": "0-3 Years", "desc": "Conducts crop demonstration trials in villages, advises farmers on fertilizer schedules, monitors pest outbreaks."},
                {"stage": "Research Agronomist / Manager", "exp": "3-8 Years", "desc": "Designs new crop management protocols, evaluates hybrid seed performance, manages regional farm trials."},
                {"stage": "Lead Crop Scientist / VP Agronomy", "exp": "8+ Years", "desc": "Directs nationwide agronomy research, develops climate-resilient farming packages, advises government policy."}
            ]
        },
        {
            "title": "Soil Scientist & Pedologist",
            "short_name": "Soil Scientist",
            "slug": "soil-scientist-pedologist",
            "category": "Agriculture, Food Technology & Environment",
            "sub_category": "Soil Science & Agricultural Chemistry",
            "industry": "Soil Health, Agriculture & Environmental Remediation",
            "icon": "layers",
            "short_description": "Analyzes soil chemistry, microbiology, and soil profiles to protect soil health and remediate degraded land.",
            "description": "Soil Scientists and Pedologists study the chemical, physical, and biological properties of soils. They map soil profiles, evaluate soil microbial biodiversity, analyze nutrient depletion, investigate industrial heavy-metal soil contamination, and formulate Soil Health Card recommendations to restore degraded agricultural and forest soils.",
            "what_they_do": "They take core soil profile samples, conduct analytical spectroscopic laboratory tests (pH, electrical conductivity, organic carbon, NPK, micronutrients), map digital soil fertility maps, and design soil conservation plans.",
            "day_to_day_work": "• Digging soil survey profile pits and analyzing horizon layers (A, B, C horizons).\n• Operating flame photometers and atomic absorption spectrophotometers (AAS) for soil analysis.\n• Interpreting soil organic carbon levels and soil microbiome biological activity.\n• Generating digital GIS soil fertility heatmaps for district agricultural planning.\n• Advising environmental engineering firms on bio-remediation of chemically contaminated soils.",
            "work_environment": "Soil testing laboratories, agricultural universities, land reclamation field sites, ICAR institutes.",
            "work_modes": "Lab / Field / Office",
            "minimum_qualification": "Postgraduate (M.Sc in Soil Science & Agricultural Chemistry / Pedology)",
            "preferred_streams": "Science (PCB / Chemistry / Agriculture)",
            "required_subjects": "Chemistry, Geology, Soil Science, Microbiology",
            "technical_skills": "Pedology (Soil Morphology), Soil Chemistry, Atomic Absorption Spectroscopy (AAS), Soil Microbiology, GIS Soil Mapping, Land Degradation Neutrality (LDN)",
            "soft_skills": "Chemical Laboratory Precision, Observant Field Analysis, Meticulous Recordkeeping, Environmental Passion",
            "tools": "Atomic Absorption Spectrophotometer, Flame Photometer, Core Soil Samplers, QGIS Soil Mapping",
            "certifications": "Indian Society of Soil Science (ISSS) Membership, Agricultural Scientists Recruitment Board (ASRB NET)",
            "experience_level": "Entry to Senior Scientist",
            "career_growth": "Advance to Senior Soil Scientist, Head of Soil Testing Bureau, or ICAR National Professor.",
            "internship_roles": "Soil Testing Lab Trainee, Soil Survey Intern",
            "entry_level_roles": "Junior Soil Chemist, Soil Survey Officer, Lab Technical Officer",
            "average_salary": "₹4.5 - ₹13.0 LPA (Indicative range)",
            "salary_indicative": "Soil Lab Chemist: ₹4.5 - 6.5 LPA | Agricultural Scientist (ARS via ASRB): ₹8 - 14 LPA | Senior Pedologist / Environmental Soil Consultant: ₹14 - 25+ LPA. Indicative figures from ICAR-IISS and ASRB pay scales.",
            "future_scope": "Growing exponentially with the global focus on soil carbon sequestration, regenerative farming, and the national Soil Health Card scheme.",
            "government_opportunities": "ICAR-Indian Institute of Soil Science (IISS Bhopal), National Bureau of Soil Survey and Land Use Planning (NBSS&LUP Nagpur), State Soil Testing Labs.",
            "private_opportunities": "Coromandel International, IFFCO, Deepak Fertilisers, Environmental consulting firms, Global carbon offset verification registries.",
            "higher_study_options": "Ph.D. in Soil Science / Soil Microbiology, International Postdoctoral Research in Carbon Sequestration.",
            "entrepreneurship_options": "Establishing an automated commercial soil and water testing laboratory or organic soil amendment manufacturing company.",
            "source": "ICAR-Indian Institute of Soil Science (IISS) / ISSS",
            "official_url": "https://iiss.icar.gov.in",
            "verification_status": "VERIFIED",
            "is_lesser_known": True,
            "career_family": "Agriculture & Rural",
            "interest_clusters": "Science, Nature, Agriculture, Research, Lab",
            "work_style": "Lab, Field",
            "reality_check": "Involves detailed analytical laboratory chemistry: pipetting reagents, titrating chemical solutions, and operating spectrometers.\nRequires field pedology: digging deep 1.5-meter soil profile trenches in fields and classifying soil taxonomies.\nCrucial for climate change mitigation: soil is the Earth's largest terrestrial carbon sink.",
            "next_steps": "Earn a Bachelor's degree in B.Sc (Hons) Agriculture or B.Sc Chemistry/Geology.\nPursue M.Sc in Soil Science & Agricultural Chemistry from an ICAR-accredited agricultural university.\nClear the ASRB NET / ARS Examination to become an Agricultural Research Scientist.",
            "courses": [{"course_id": 8, "type": "PRIMARY"}, {"course_id": 13, "type": "RELATED"}],
            "exams": [],
            "routes": [{"title": "Path A: Soil Science Research Route", "type": "PRIMARY", "steps": "B.Sc Agriculture / Chemistry -> M.Sc Soil Science -> ASRB NET / ARS Exam -> ICAR Scientist (Soil Science)."}],
            "ladder": [
                {"stage": "Junior Soil Chemist / Analyst", "exp": "0-3 Years", "desc": "Conducts standard NPK and micronutrient testing, calibrates lab equipment, issues soil test cards."},
                {"stage": "Scientist / Soil Surveyor", "exp": "3-8 Years", "desc": "Maps regional soil classification orders, investigates heavy metal soil toxicity, models carbon sequestration."},
                {"stage": "Principal Scientist / Lab Director", "exp": "8+ Years", "desc": "Heads national soil conservation programs, formulates national fertilizer subsidy policies."}
            ]
        },
        {
            "title": "Commercial Horticulturist",
            "short_name": "Horticulturist",
            "slug": "commercial-horticulturist",
            "category": "Agriculture, Food Technology & Environment",
            "sub_category": "Horticulture & Floriculture",
            "industry": "Commercial Horticulture, High-Value Fruits & Floriculture",
            "icon": "flower3",
            "short_description": "Manages commercial cultivation of fruits, high-value vegetables, exotic flowers, and polyhouse crops.",
            "description": "Commercial Horticulturists manage the science and business of cultivating high-value fruits (pomology), vegetables (olericulture), flowers (floriculture), and ornamental landscaping. They operate climate-controlled polyhouses, automated vertical hydroponic farms, manage orchard grafting and pruning, and ensure post-harvest cold chain logistics for export markets.",
            "what_they_do": "They design commercial greenhouse operations, manage micro-irrigation fertigation systems, propagate disease-free tissue culture plantlets, control orchard flowering and fruiting cycles, and prepare export consignments.",
            "day_to_day_work": "• Monitoring automated temperature, humidity, and fertigation in climate-controlled polyhouses.\n• Managing high-density fruit orchard grafting, canopy pruning, and pest management.\n• Supervising harvest maturity indices and cold-storage pre-cooling of exotic vegetables.\n• Designing aesthetic landscape master plans for resorts, golf courses, and corporate campuses.\n• Inspecting commercial cut flower (roses, orchids, carnations) shipments for export.",
            "work_environment": "Commercial polyhouses, fruit orchards, floriculture estates, tissue culture labs, corporate landscaping sites.",
            "work_modes": "Field / Farm / Greenhouse / Nursery",
            "minimum_qualification": "Undergraduate (B.Sc Hons Horticulture - 4 Years) / M.Sc Horticulture",
            "preferred_streams": "Science (PCB / Agriculture)",
            "required_subjects": "Horticulture, Plant Physiology, Botany, Chemistry",
            "technical_skills": "Polyhouse Management, Fertigation & Drip Irrigation, Plant Propagation (Grafting/Budding), Post-Harvest Cold Chain Technology, Hydroponics, Floriculture Export Standards",
            "soft_skills": "Botanical Observation, Commercial Acumen, Aesthetic Eye for Landscaping, Hands-on Energy",
            "tools": "Automated Climate Controllers, Refractometers (Brix sugar meters), Pruning Shears, Hydroponic Sensors",
            "certifications": "National Horticulture Board (NHB) Project Certification",
            "experience_level": "Entry to Senior Level",
            "career_growth": "Advance to Commercial Estate Manager, Head of Protected Cultivation, or Agri-Export Director.",
            "internship_roles": "Greenhouse Trainee, Orchard Management Intern",
            "entry_level_roles": "Horticulture Officer, Greenhouse Supervisor, Nursery Manager",
            "average_salary": "₹4.0 - ₹11.0 LPA (Indicative range)",
            "salary_indicative": "Greenhouse Supervisor: ₹4.0 - 6 LPA | Commercial Orchard Manager (3-6 yrs): ₹7 - 12 LPA | Commercial Agribusiness Director / Exporter: ₹12 - 25+ LPA. Indicative figures from National Horticulture Board surveys.",
            "future_scope": "Booming sector with consumer demand for exotic berries, avocado, dragon fruit, hydroponic microgreens, and corporate urban greening.",
            "government_opportunities": "National Horticulture Board (NHB), State Horticulture Departments (District Horticulture Officer - DHO), ICAR-IIHR Bengaluru.",
            "private_opportunities": "Mahindra Agri Solutions, Namdhari Seeds, INI Farms, Jain Irrigation, Reliance Retail Fresh, Top Export Orchards.",
            "higher_study_options": "M.Sc in Fruit Science / Floriculture / Post-Harvest Technology, Ph.D. in Horticulture.",
            "entrepreneurship_options": "Establishing an automated hydroponic salad farm, high-tech plant nursery, or exotic fruit orchard.",
            "source": "National Horticulture Board (NHB) / ICAR-IIHR",
            "official_url": "https://nhb.gov.in",
            "verification_status": "VERIFIED",
            "is_lesser_known": False,
            "career_family": "Agriculture & Rural",
            "interest_clusters": "Nature, Agriculture, Outdoor, Business, Hands-on",
            "work_style": "Farm, Outdoor, Greenhouse",
            "reality_check": "High-value crops require daily scientific precision: a single pump failure in a hydroponic polyhouse can ruin an entire harvest.\nInvolves hands-on physical involvement in nurseries, pruning trees, and handling delicate flowering plants.\nCombines biological science with sharp commercial marketing and cold-chain timing.",
            "next_steps": "Pass Class 12 with Physics, Chemistry, and Biology.\nAppear for ICAR CUET-UG or State Agricultural CETs to secure admission into B.Sc (Hons) Horticulture (4 yrs).\nGain practical greenhouse training and explore National Horticulture Board (NHB) subsidized venture projects.",
            "courses": [{"course_id": 8, "type": "PRIMARY"}, {"course_id": 68, "type": "RELATED"}],
            "exams": [],
            "routes": [{"title": "Path A: Standard Horticulture Route", "type": "PRIMARY", "steps": "12th (PCB) -> B.Sc (Hons) Horticulture (4 yrs) -> Practical Greenhouse Residency -> Horticulture Officer / Greenhouse Lead."}],
            "ladder": [
                {"stage": "Horticulture Officer / Nursery Supervisor", "exp": "0-3 Years", "desc": "Manages seedling propagation, monitors fertigation cycles, enforces greenhouse climate parameters."},
                {"stage": "Commercial Orchard / Estate Manager", "exp": "3-8 Years", "desc": "Directs 100+ acre fruit orchards, manages harvest schedules, negotiates supermarket procurement contracts."},
                {"stage": "Director of Protected Agriculture / Entrepreneur", "exp": "8+ Years", "desc": "Heads commercial hi-tech farming ventures, exports fruits globally, sets up automated hydroponic facilities."}
            ]
        },
        {
            "title": "Dairy Plant Technologist & Processing Manager",
            "short_name": "Dairy Technologist",
            "slug": "dairy-plant-technologist",
            "category": "Agriculture, Food Technology & Environment",
            "sub_category": "Dairy Science & Technology",
            "industry": "Dairy Processing, FMCG & Food Manufacturing",
            "icon": "cup-straw",
            "short_description": "Manages industrial pasteurization, cheese/butter manufacturing, milk quality analysis, and dairy plant processing.",
            "description": "Dairy Technologists are specialized food engineers who manage the industrial processing of milk into diverse commercial products like pasteurized milk, butter, cheese, ghee, ice cream, baby formulas, and whey proteins. Trained under Dairy Technology programs (B.Tech Dairy Technology), they manage automated milk processing plants, enforce strict microbiological safety, and formulate innovative dairy foods.",
            "what_they_do": "They supervise milk procurement chilling centers, manage continuous pasteurizers and homogenizers, test fat/SNF percentages, ensure FSSAI dairy safety compliance, and direct automated packaging lines.",
            "day_to_day_work": "• Testing incoming raw milk tankers for antibiotic residues, aflatoxins, fat, and SNF.\n• Operating High-Temperature Short-Time (HTST) pasteurizers and vacuum evaporators.\n• Managing cheese fermentations, bacterial starter cultures, and butter churns.\n• Auditing CIP (Clean-in-Place) automated chemical sanitization cycles across stainless steel pipelines.\n• Ensuring Zero-Defect compliance with FSSAI microbiological food safety standards.",
            "work_environment": "Industrial dairy processing plants, milk chilling centers, food quality testing labs.",
            "work_modes": "On-site / Plant Floor / Dairy Lab",
            "minimum_qualification": "Undergraduate (B.Tech Dairy Technology - 4 Years)",
            "preferred_streams": "Science (PCM / PCB)",
            "required_subjects": "Chemistry, Physics, Mathematics / Biology",
            "technical_skills": "Dairy Processing Engineering, Milk Chemistry & Microbiology, HTST Pasteurization, Starter Culture Fermentation, Clean-in-Place (CIP) Protocols, FSSAI Dairy Standards",
            "soft_skills": "Strict Food Hygiene Discipline, Plant Team Leadership, Crisis Problem Solving, Precision",
            "tools": "Milko-Testers, Gerber Centrifuges, HTST Pasteurizers, Spray Dryers, Automated Bottling Lines",
            "certifications": "Indian Dairy Association (IDA) Membership, FSSAI Food Safety Supervisor Certification",
            "experience_level": "Entry to Senior Level",
            "career_growth": "Advance to Dairy Plant Manager, Head of Quality Assurance, or General Manager (Dairy Operations).",
            "internship_roles": "Dairy Plant In-Plant Trainee, Milk Quality Intern",
            "entry_level_roles": "Technical Officer (Dairy), Plant Shift Supervisor, Dairy Quality Analyst",
            "average_salary": "₹4.5 - ₹12.5 LPA (Indicative range)",
            "salary_indicative": "Technical Officer post-B.Tech: ₹4.5 - 7 LPA | Dairy Plant Manager (4-7 yrs): ₹8 - 14 LPA | General Manager of Large Dairy Cooperative: ₹16 - 30+ LPA. Indicative figures from Amul, Mother Dairy, and IDA surveys.",
            "future_scope": "India is the world's largest milk producer with a massive, unstoppable domestic demand for packaged dairy, cheese, and functional probiotic yogurts.",
            "government_opportunities": "National Dairy Development Board (NDDB), National Dairy Research Institute (ICAR-NDRI Karnal), State Cooperative Milk Federations (Amul/GCMMF, Nandini/KMF, Verka, Sudha).",
            "private_opportunities": "Nestlé India, Danone, Britannia Dairy, Hatsun Agro, Parag Milk Foods (Gowardhan), Heritage Foods.",
            "higher_study_options": "M.Tech in Dairy Technology / Dairy Engineering, MBA in Agribusiness Management.",
            "entrepreneurship_options": "Founding a boutique farmstead artisanal cheese creamery, A2 dairy brand, or organic ice cream label.",
            "source": "National Dairy Development Board (NDDB) / ICAR-NDRI",
            "official_url": "https://www.nddb.coop",
            "verification_status": "VERIFIED",
            "is_lesser_known": False,
            "career_family": "Agriculture & Rural",
            "interest_clusters": "Food, Science, Agriculture, Machines, Hands-on",
            "work_style": "Factory, Lab",
            "reality_check": "Industrial manufacturing environment: Dairy plants operate 24x7x365, requiring rotating shift duties (morning, evening, night shifts).\nStrict zero-contamination tolerance: A single batch of spoiled milk or bacterial culture contamination can lead to massive financial losses.\nCombines mechanical and chemical engineering with biochemistry and food hygiene.",
            "next_steps": "Pass Class 12 with Physics, Chemistry, and Mathematics (PCM).\nAppear for ICAR CUET-UG or State CETs for admission into B.Tech Dairy Technology (4 yrs).\nComplete 6 months of mandatory in-plant industrial training in a cooperative or corporate dairy plant.",
            "courses": [{"course_id": 1, "type": "RELATED"}, {"course_id": 8, "type": "RELATED"}],
            "exams": [],
            "routes": [{"title": "Path A: Standard Dairy Tech Route", "type": "PRIMARY", "steps": "12th (PCM) -> B.Tech Dairy Technology (4 yrs) -> In-Plant Dairy Training -> Technical Officer in Dairy -> Plant General Manager."}],
            "ladder": [
                {"stage": "Technical Officer / Shift In-Charge", "exp": "0-3 Years", "desc": "Manages milk reception, operates pasteurizers and separators, monitors automated packaging lines."},
                {"stage": "Production Manager / Quality Head", "exp": "3-8 Years", "desc": "Supervises multi-ton daily cheese, butter, and milk powder production; audits FSSAI quality benchmarks."},
                {"stage": "Dairy Plant General Manager", "exp": "8+ Years", "desc": "Heads multi-crore industrial dairy processing operations, directs procurement from thousands of village farmers."}
            ]
        }
    ]

def get_environment_and_sustainability_careers():
    return [
        {
            "title": "Wildlife Biologist & Reserve Conservationist",
            "short_name": "Wildlife Biologist",
            "slug": "wildlife-biologist",
            "category": "Agriculture, Food Technology & Environment",
            "sub_category": "Wildlife Biology & Ecology",
            "industry": "Wildlife Conservation, National Parks & Ecological Research",
            "icon": "binoculars",
            "short_description": "Studies wild animal populations, tracks endangered species, and protects forest biodiversity ecosystems.",
            "description": "Wildlife Biologists study the behavior, physiology, genetics, and habitat requirements of wild animals in their natural forest, grassland, and aquatic ecosystems. They monitor endangered species (tigers, elephants, snow leopards, rhinos), conduct camera trap surveys, mitigate human-wildlife conflicts, and formulate wildlife management plans for National Parks and Tiger Reserves.",
            "what_they_do": "They set up field camera-trap grids, track radio-collared wildlife using telemetry, analyze animal scat for DNA/hormones, model habitat corridors using GIS, and advise state forest departments.",
            "day_to_day_work": "• Trekking through reserve forests to service automated motion-sensor camera traps.\n• Analyzing photographic capture-recapture data in statistical packages (Mark, Spatially Explicit Capture-Recapture).\n• Radio-tracking tranquilized and collared leopards or elephants via satellite VHF telemetry.\n• Investigating crop-raiding or livestock depredation incidents and implementing mitigation measures.\n• Publishing peer-reviewed scientific studies on wildlife population genetics and habitat fragmentation.",
            "work_environment": "National Parks, Tiger Reserves, Wildlife Sanctuaries, dense forests, research laboratories.",
            "work_modes": "Field / Jungle / Outdoor / Lab",
            "minimum_qualification": "Postgraduate (M.Sc in Wildlife Science / Zoology / Forestry / Ecology)",
            "preferred_streams": "Science (PCB / Life Sciences / Zoology)",
            "required_subjects": "Zoology, Ecology, Wildlife Biology, Genetics",
            "technical_skills": "Camera Trapping, Radiotelemetry Tracking, Population Modeling (SECR), Non-Invasive Fecal DNA Genetics, QGIS Habitat Mapping, Human-Wildlife Conflict Mitigation",
            "soft_skills": "Physical Bravery, Wilderness Survival Skills, Extreme Patience, Deep Empathy for Nature",
            "tools": "Field Camera Traps, VHF Radio Receivers, Handheld GPS, Night Vision Scopes, QGIS, R software",
            "certifications": "Wildlife Institute of India (WII) Credentials, National Eligibility Test (CSIR-UGC NET)",
            "experience_level": "Field Researcher to Chief Wildlife Scientist",
            "career_growth": "Advance to Senior Wildlife Scientist, National Tiger Conservation Authority (NTCA) Advisor, or Conservation Director.",
            "internship_roles": "Field Research Assistant, Tiger Census Volunteer",
            "entry_level_roles": "Junior Research Fellow (JRF), Field Biologist, Conservation Associate",
            "average_salary": "₹4.5 - ₹12.0 LPA (Indicative range)",
            "salary_indicative": "Field Biologist / JRF (WII / WWF): ₹4.5 - 6.5 LPA stipend/salary | Project Scientist (3-6 yrs): ₹7.5 - 11 LPA | Senior Scientist / International Conservation Lead: ₹12 - 22+ LPA. Indicative figures from Wildlife Institute of India.",
            "future_scope": "Critically in demand to save India's fragile biodiversity, combat human-wildlife conflict, and maintain national ecological corridors.",
            "government_opportunities": "Wildlife Institute of India (WII Dehradun), National Tiger Conservation Authority (NTCA), Zoological Survey of India (ZSI), State Forest Departments.",
            "private_opportunities": "WWF India, Wildlife Conservation Society (WCS India), Wildlife Trust of India (WTI), Nature Conservation Foundation (NCF), Aaranyak.",
            "higher_study_options": "Ph.D. in Wildlife Science / Ecology, International Conservation Postdoctoral Fellowships.",
            "entrepreneurship_options": "Eco-tourism and wildlife expedition consultancy, ecological impact assessment firm.",
            "source": "Wildlife Institute of India (WII) / Ministry of Environment, Forest and Climate Change",
            "official_url": "https://wii.gov.in",
            "verification_status": "VERIFIED",
            "is_lesser_known": True,
            "career_family": "Ecology & Earth",
            "interest_clusters": "Animals, Nature, Science, Outdoor, Research",
            "work_style": "Field, Outdoor, Lab",
            "reality_check": "Not a leisurely tourist safari: Involves rigorous, physically exhausting walking through dense jungles in extreme heat, cold, and rain.\nEncounter risks with wild predators, poisonous snakes, and vector-borne diseases like malaria in remote forest camps.\nDriven by deep, unwavering passion for animal conservation rather than high commercial wealth.",
            "next_steps": "Earn a Bachelor's degree in Zoology, Life Sciences, Forestry, or Environmental Science.\nAppear for national entrance for M.Sc in Wildlife Science at Wildlife Institute of India (WII Dehradun) or NCBS Bengaluru.\nUndertake field research projects in protected reserves and clear CSIR NET for doctoral research.",
            "courses": [{"course_id": 15, "type": "PRIMARY"}, {"course_id": 68, "type": "RELATED"}],
            "exams": [{"exam_id": 33, "importance": "PRIMARY"}],
            "routes": [{"title": "Path A: WII Wildlife Science Route", "type": "PRIMARY", "steps": "B.Sc Zoology/Life Sciences -> M.Sc Wildlife Science (WII) -> Field Biologist -> CSIR NET / Ph.D. -> Senior Wildlife Scientist."}],
            "ladder": [
                {"stage": "Field Biologist / JRF", "exp": "0-3 Years", "desc": "Sets up camera traps, conducts line-transect animal density surveys, collects non-invasive DNA scat samples."},
                {"stage": "Research Biologist / Project Head", "exp": "3-8 Years", "desc": "Directs species conservation projects, models wildlife movement corridors, works with forest rangers."},
                {"stage": "Lead Wildlife Scientist / Conservation Director", "exp": "8+ Years", "desc": "Advises Union Environment Ministry on protected area boundaries, leads national wildlife censuses."}
            ]
        },
        {
            "title": "Climate Change Policy Analyst & Carbon Verifier",
            "short_name": "Climate Change Analyst",
            "slug": "climate-change-analyst",
            "category": "Agriculture, Food Technology & Environment",
            "sub_category": "Climate Science & Sustainability",
            "industry": "Carbon Markets, Climate Finance & Sustainability Advisory",
            "icon": "cloud-sun",
            "short_description": "Models greenhouse gas emissions, verifies carbon offset credits, and advises on national Net-Zero policies.",
            "description": "Climate Change Policy Analysts and Carbon Verifiers operate at the intersection of climate science, international environmental treaties (UNFCCC Paris Agreement), and global carbon credit markets. They calculate corporate greenhouse gas (GHG) footprints, audit renewable energy and afforestation projects for carbon credit issuance (Verra, Gold Standard), and design national climate adaptation policies.",
            "what_they_do": "They quantify Scope 1, 2, and 3 carbon emissions, verify Clean Development Mechanism (CDM) / Article 6 carbon offset projects, build climate risk scenario models, and draft corporate Net-Zero transition strategies.",
            "day_to_day_work": "• Calculating corporate GHG inventories adhering to the GHG Protocol and ISO 14064 standards.\n• Conducting on-site technical audits of solar farms, biogas plants, and mangrove afforestation projects.\n• Modeling physical and transition climate risks under IPCC climate scenarios (RCP 4.5/8.5).\n• Verifying carbon offset credits for listing on voluntary and compliance carbon registries.\n• Formulating state-level climate change action plans (SAPCC) for government agencies.",
            "work_environment": "Sustainability consultancies, carbon trading exchanges, climate think tanks, hybrid offices.",
            "work_modes": "Hybrid / Office / Field",
            "minimum_qualification": "Postgraduate (M.Sc / M.Tech in Environmental Science / Climate Science / Sustainable Development)",
            "preferred_streams": "Science / Engineering / Economics / Public Policy",
            "required_subjects": "Climate Science, Environmental Economics, Energy Systems",
            "technical_skills": "GHG Accounting (Scope 1, 2, 3), Carbon Offsetting Standards (Verra VCS, Gold Standard), ISO 14064 Carbon Verification, IPCC Climate Modeling, Task Force on Climate-related Financial Disclosures (TCFD)",
            "soft_skills": "Analytical Acumen, Scientific Rigor, Policy Translation, Persuasive Advisory",
            "tools": "GHG Protocol Calculation Tools, SimCLIM, Climate Analytics Dashboards, Excel Carbon Models",
            "certifications": "ISO 14064 Lead Carbon Verifier, Certified Sustainability Professional (GRI / ISSB)",
            "experience_level": "Entry to Senior Level",
            "career_growth": "Advance to Senior Climate Consultant, Head of Carbon Trading, or Chief Sustainability Officer (CSO).",
            "internship_roles": "Climate Analytics Intern, Carbon Project Trainee",
            "entry_level_roles": "Junior Climate Analyst, Carbon Accounting Associate, Sustainability Consultant",
            "average_salary": "₹6.0 - ₹18.0 LPA (Indicative range)",
            "salary_indicative": "Junior Carbon Analyst: ₹6.0 - 8.5 LPA | Carbon Verification Specialist (3-6 yrs): ₹10 - 16 LPA | Head of Climate Practice / Carbon Fund Manager: ₹18 - 35+ LPA. Indicative figures from global sustainability consulting benchmarks.",
            "future_scope": "Massive global demand driven by global Net-Zero deadlines, the European Union's Carbon Border Tax (CBAM), and India's Carbon Credit Trading Scheme (CCTS).",
            "government_opportunities": "Bureau of Energy Efficiency (BEE - administering Indian carbon market), Ministry of Environment, Forest and Climate Change (MoEFCC), NITI Aayog.",
            "private_opportunities": "Big 4 Sustainability Practices (PwC, EY, Deloitte, KPMG), South Pole, Climate Impact Partners, EKI Energy Services, Tata Sustainability Group.",
            "higher_study_options": "Ph.D. in Climate Economics, Master in Environmental Policy (TERI SAS, Oxford, Columbia).",
            "entrepreneurship_options": "Founding a carbon project development agency, climate-tech monitoring platform, or carbon credit brokerage.",
            "source": "Bureau of Energy Efficiency (BEE) / UNFCCC",
            "official_url": "https://beeindia.gov.in",
            "verification_status": "VERIFIED",
            "is_lesser_known": True,
            "career_family": "Ecology & Earth",
            "interest_clusters": "Environment, Science, Business, Analysis, Government",
            "work_style": "Office, Remote, Field",
            "reality_check": "Combines deep climate physics and ecology with rigorous quantitative financial accounting and international law.\nRequires auditing physical field projects (e.g. counting planted trees in forestry carbon projects) to prevent greenwashing.\nFastest-growing sector at the intersection of finance, corporate strategy, and planetary survival.",
            "next_steps": "Complete a Bachelor's degree in Environmental Science, Engineering, Economics, or Life Sciences.\nPursue a Master's degree in Climate Science, Environmental Studies, or Sustainability from institutions like TERI SAS or CEPT.\nEarn an accredited ISO 14064 GHG Lead Auditor certification and join a sustainability consulting practice.",
            "courses": [{"course_id": 13, "type": "PRIMARY"}, {"course_id": 14, "type": "RELATED"}],
            "exams": [],
            "routes": [{"title": "Path A: Climate Analytics Route", "type": "PRIMARY", "steps": "B.Sc / B.Tech -> Master in Climate Studies / Sustainability -> ISO 14064 Auditor -> Carbon Verifier -> Chief Sustainability Officer."}],
            "ladder": [
                {"stage": "Junior Carbon Analyst", "exp": "0-2 Years", "desc": "Calculates corporate energy emissions, compiles GHG activity data, assists in carbon credit project documentation."},
                {"stage": "Carbon Verification Specialist", "exp": "2-6 Years", "desc": "Audits renewable energy and forestry projects on-site, validates carbon offsets against Verra/Gold Standard rules."},
                {"stage": "Practice Leader / Chief Climate Officer", "exp": "6+ Years", "desc": "Advises Fortune 500 corporations on multi-billion dollar Net-Zero roadmaps, manages climate investment portfolios."}
            ]
        }
    ]

def get_social_sciences_careers():
    return [
        {
            "title": "Development Economist",
            "short_name": "Development Economist",
            "slug": "development-economist",
            "category": "Social Sciences, Psychology & Public Policy",
            "sub_category": "Economics & Public Policy",
            "industry": "International Development, Public Policy & Economic Research",
            "icon": "graph-up",
            "short_description": "Researches poverty alleviation, social safety nets, healthcare economics, and evaluates public welfare policies.",
            "description": "Development Economists study the fiscal, social, and institutional mechanisms that promote sustainable economic growth and human development in low- and middle-income countries. Using rigorous econometric analysis and Randomized Controlled Trials (RCTs popularized by Nobel laureates Abhijit Banerjee and Esther Duflo), they evaluate government anti-poverty policies.",
            "what_they_do": "They design large-scale field experiments and household surveys, evaluate the impact of direct benefit transfers (DBT) and educational interventions, construct macroeconomic econometric models, and advise governments.",
            "day_to_day_work": "• Designing Randomized Controlled Trials (RCT) to evaluate government healthcare or education schemes.\n• Analyzing large-scale household survey microdata (NSSO, NFHS, IHDS) using STATA or R.\n• Writing econometric models to estimate treatment effects and causal policy impacts.\n• Conducting field visits to interview beneficiaries and audit baseline survey enumerators.\n• Drafting policy white papers and briefs for the Ministry of Finance, NITI Aayog, or World Bank.",
            "work_environment": "International development institutions, economic research think tanks, universities, government ministries.",
            "work_modes": "Hybrid / Office / Field",
            "minimum_qualification": "Postgraduate (M.A. / M.Sc in Economics -> Ph.D. in Development Economics)",
            "preferred_streams": "Economics / Mathematics / Statistics / Commerce",
            "required_subjects": "Microeconomics, Macroeconomics, Econometrics, Mathematical Statistics",
            "technical_skills": "Econometrics, Randomized Controlled Trials (RCT), STATA / R Programming, Survey Design, Causal Inference, Public Finance, Microdata Analysis (NFHS, NSSO)",
            "soft_skills": "Rigorous Critical Thinking, Social Empathy, Intellectual Objectivity, Clear Policy Communication",
            "tools": "STATA, R, SurveyCTO, Python, QGIS, National Sample Survey (NSS) Datasets",
            "certifications": "UGC NET / JRF in Economics, Indian Economic Association (IEA) Membership",
            "experience_level": "Mid to Senior Level",
            "career_growth": "Advance to Senior Economist, Lead Policy Fellow, Chief Economic Advisor, or World Bank Lead Economist.",
            "internship_roles": "Economic Research Intern, Field Research Trainee (J-PAL / CEGIS)",
            "entry_level_roles": "Research Associate (Economics), Policy Analyst, Junior Economist",
            "average_salary": "₹6.5 - ₹20.0 LPA (Indicative range)",
            "salary_indicative": "Research Associate (J-PAL / CPR): ₹6.5 - 9 LPA | Economist at Multilateral Bank (World Bank / ADB): ₹14 - 25 LPA | Senior Research Fellow / Professor of Economics: ₹18 - 35+ LPA. Indicative figures from top economic think tanks.",
            "future_scope": "Crucial intellectual discipline shaping the future of welfare schemes, universal healthcare, and equitable national growth.",
            "government_opportunities": "Indian Economic Service (IES via UPSC), NITI Aayog, Ministry of Finance, Reserve Bank of India (DEPR), State Planning Boards.",
            "private_opportunities": "Abdul Latif Jameel Poverty Action Lab (J-PAL South Asia), World Bank, Asian Development Bank (ADB), International Monetary Fund (IMF), Centre for Policy Research (CPR).",
            "higher_study_options": "Ph.D. in Development Economics (DSE, ISI, JNU, LSE, Harvard, MIT).",
            "entrepreneurship_options": "Founding an independent monitoring and evaluation (M&E) research consulting firm.",
            "source": "Indian Economic Service (IES) / J-PAL South Asia",
            "official_url": "https://ies.gov.in",
            "verification_status": "VERIFIED",
            "is_lesser_known": False,
            "career_family": "Social Sciences",
            "interest_clusters": "Numbers, Society, Research, Government, Helping",
            "work_style": "Office, Field, School",
            "reality_check": "Not pure abstract theory: Modern development economics is heavily mathematical, statistical, and empirical.\nRequires deep mastery of software (STATA, R) and econometric proofs (regression discontinuity, instrumental variables).\nInvolves both high-level statistical modeling and dusty grassroots rural field survey verification.",
            "next_steps": "Earn a Bachelor's degree in Economics with strong mathematics and statistics foundations (e.g. B.A. Hons Economics).\nPursue a premier Master's degree in Economics (e.g. Delhi School of Economics, ISI, JNU, MSE, IGIDR).\nAppear for UPSC Indian Economic Service (IES) Examination or join top research centers like J-PAL as a Research Associate.",
            "courses": [{"course_id": 31, "type": "PRIMARY"}, {"course_id": 16, "type": "RELATED"}],
            "exams": [{"exam_id": 41, "importance": "PRIMARY"}],
            "routes": [{"title": "Path A: Economic Research Route", "type": "PRIMARY", "steps": "B.A. Economics -> M.A. Economics (DSE/ISI) -> J-PAL Research Associate -> Ph.D. / IES Exam -> Development Economist."}],
            "ladder": [
                {"stage": "Research Associate / Junior Economist", "exp": "0-3 Years", "desc": "Cleans large household survey datasets, runs econometric regressions in STATA, manages field survey teams."},
                {"stage": "Economist / Policy Specialist", "exp": "3-8 Years", "desc": "Designs independent research studies, publishes peer-reviewed journal papers, advises ministries on welfare designs."},
                {"stage": "Lead Economist / Think Tank Director", "exp": "8+ Years", "desc": "Shapes national fiscal and social welfare policy, heads international development research portfolios."}
            ]
        },
        {
            "title": "Medical & Psychiatric Social Worker (MSW)",
            "short_name": "Psychiatric Social Worker",
            "slug": "medical-psychiatric-social-worker",
            "category": "Social Sciences, Psychology & Public Policy",
            "sub_category": "Social Work & Mental Health",
            "industry": "Mental Health, Hospitals & Community Rehabilitation",
            "icon": "heart-pulse",
            "short_description": "Provides psychosocial interventions, crisis counselling, and rehabilitation support in psychiatric hospitals.",
            "description": "Medical and Psychiatric Social Workers (holding an MSW and specialized M.Phil in Psychiatric Social Work) are clinical mental health professionals. Working in psychiatric hospitals, oncology wards, and de-addiction centers alongside psychiatrists and clinical psychologists, they assess family dynamics, provide psycho-education, deliver crisis interventions, and rehabilitate patients into society.",
            "what_they_do": "They conduct psychosocial family assessments, provide individual and group counseling, organize de-addiction rehabilitation, coordinate disability welfare pensions, and facilitate patient discharge and community reintegration.",
            "day_to_day_work": "• Conducting comprehensive psychosocial assessments of psychiatric and medical inpatients.\n• Providing supportive psychotherapy and psychoeducation to families of patients with schizophrenia/bipolar.\n• Facilitating group therapy sessions in substance abuse de-addiction centers.\n• Connecting disadvantaged patients with government emergency medical welfare funds.\n• Conducting home visits to evaluate family recovery environments before hospital discharge.",
            "work_environment": "Psychiatric hospitals, multi-specialty government hospitals, cancer institutes, de-addiction centers.",
            "work_modes": "On-site / Hospital / Clinic / Community",
            "minimum_qualification": "Postgraduate (MSW - Master of Social Work -> M.Phil in Psychiatric Social Work from NIMHANS / CIP)",
            "preferred_streams": "Any Stream (Graduation in Social Work, Sociology, Psychology, or Humanities)",
            "required_subjects": "Psychiatric Social Work, Mental Health, Clinical Social Case Work",
            "technical_skills": "Psychosocial Assessment, Family Therapy, Crisis Intervention, De-addiction Rehabilitation, Social Case Work, Community Mental Health, RPwD Act Provisions",
            "soft_skills": "Profound Empathy, Non-Judgmental Listening, Emotional Resilience, Crisis De-escalation",
            "tools": "Psychosocial Assessment Protocols, Family Genograms, Rehabilitation Scales, Mental Healthcare Portals",
            "certifications": "Rehabilitation Council of India (RCI) Professional Registration (for M.Phil Psychiatric Social Work)",
            "experience_level": "Entry to Senior Level",
            "career_growth": "Advance to Senior Psychiatric Social Worker, Head of Medical Social Services, or Professor of Social Work.",
            "internship_roles": "Psychiatric Hospital Social Work Intern, De-addiction Center Trainee",
            "entry_level_roles": "Medical Social Worker (MSW), Psychiatric Social Work Associate, Community Mental Health Worker",
            "average_salary": "₹4.0 - ₹10.5 LPA (Indicative range)",
            "salary_indicative": "Medical Social Worker (MSW in Hospital): ₹4.0 - 6.5 LPA | Psychiatric Social Worker (NIMHANS/AIIMS Pay Level 7-10): ₹7 - 12 LPA | Senior Clinical Consultant / NGO Director: ₹10 - 18+ LPA. Indicative figures from AIIMS and NIMHANS recruitment scales.",
            "future_scope": "Recognized under the Mental Healthcare Act 2017 as one of the 4 statutory mental health professionals in India (alongside Psychiatrists, Clinical Psychologists, and Psychiatric Nurses).",
            "government_opportunities": "NIMHANS Bengaluru, AIIMS Medical Social Service Departments, Central Institute of Psychiatry (CIP Ranchi), State Mental Health Hospitals, Tele-MANAS.",
            "private_opportunities": "Tata Memorial Centre, Fortis Mental Health, Cadabam's, Medanta, The Banyan, Sangath Goa.",
            "higher_study_options": "Ph.D. in Psychiatric Social Work, Advanced Clinical Fellowships.",
            "entrepreneurship_options": "Founding an independent mental health rehabilitation transitional home or psychosocial counseling center.",
            "source": "Rehabilitation Council of India (RCI) / NIMHANS Bengaluru",
            "official_url": "https://nimhans.ac.in",
            "verification_status": "VERIFIED",
            "is_lesser_known": False,
            "career_family": "Social Sciences",
            "interest_clusters": "Helping, People, Healthcare, Society, Psychology",
            "work_style": "Hospital, Clinic, Community",
            "reality_check": "Deals with severe human distress: acute psychosis, suicide attempts, terminal cancer diagnoses, and domestic violence.\nRequires deep emotional resilience and healthy boundaries to avoid personal caregiver burnout.\nStatutory clinical recognition in India requires completing the 2-year M.Phil in Psychiatric Social Work from institutes like NIMHANS.",
            "next_steps": "Complete a Bachelor's degree in any stream (BSW, Psychology, Sociology, or Arts).\nPursue Master of Social Work (MSW) with medical & psychiatric specialization.\nAppear for national entrance for the 2-year M.Phil in Psychiatric Social Work at NIMHANS, CIP Ranchi, or LGBRIMH Tezpur.",
            "courses": [{"course_id": 66, "type": "PRIMARY"}, {"course_id": 67, "type": "RELATED"}],
            "exams": [],
            "routes": [{"title": "Path A: Clinical Social Work Route", "type": "PRIMARY", "steps": "Undergraduate Degree -> MSW (2 yrs) -> M.Phil Psychiatric Social Work (NIMHANS - 2 yrs) -> RCI Registration -> Psychiatric Social Worker."}],
            "ladder": [
                {"stage": "Medical Social Worker", "exp": "0-3 Years", "desc": "Conducts patient intake interviews, arranges financial aid for indigent patients, facilitates family counseling."},
                {"stage": "Psychiatric Social Worker", "exp": "3-8 Years", "desc": "Conducts structured family therapy, leads de-addiction recovery groups, runs community mental health camps."},
                {"stage": "Chief Medical Social Service Officer / Professor", "exp": "8+ Years", "desc": "Heads social service departments in premier medical institutes, shapes national mental healthcare policies."}
            ]
        }
    ]
