"""
scripts/catalog_builder_part4.py
Authentic occupational profiles for Business, Science, Education, Media,
Design, Agriculture, Aviation, and Social Sciences.
"""

def get_business_careers():
    return [
        {
            "title": "Management Consultant",
            "short_name": "Management Consultant",
            "slug": "management-consultant",
            "category": "Business, Management & Consulting",
            "sub_category": "Strategic Consulting & Advisory",
            "industry": "Management Consulting",
            "icon": "briefcase",
            "short_description": "Advises corporate executives and boards on strategic pivots, operational turnaround, profitability, and market entry.",
            "description": "Management Consultants solve the toughest strategic, operational, and organizational dilemmas for Fortune 500 corporations and governments. They analyze complex market data, conduct benchmarking studies, interview stakeholders, and present data-backed recommendations.",
            "what_they_do": "They structure business problems into MECE frameworks, analyze financial spreadsheets, conduct customer research, build financial turnaround models, and author executive board presentations.",
            "day_to_day_work": "• Structuring complex business client issues using hypothesis-driven problem solving.\n• Interviewing company managers and frontline staff to understand operational bottlenecks.\n• Building financial and cost-reduction scenario models in Excel.\n• Creating structured, persuasive executive slide decks in PowerPoint.\n• Presenting turnaround strategies directly to the client CEO and board.",
            "work_environment": "Global consulting offices (McKinsey, BCG, Bain) and client corporate boardrooms worldwide.",
            "work_modes": "On-site / Heavy Client Travel (Monday-Thursday travel) / Hybrid",
            "minimum_qualification": "Postgraduate (Top Tier MBA) or Premier Undergraduate Degree",
            "preferred_streams": "Any Stream (Engineering / Economics / Commerce preferred)",
            "required_subjects": "Graduation + Top-Tier MBA",
            "technical_skills": "Hypothesis-Driven Problem Solving, Financial Modeling, Market Sizing, Value Chain Analysis, Executive Presentation, Change Management",
            "soft_skills": "Exceptional Structured Thinking, Client Poise, Persuasion, Fast Adaptability",
            "tools": "Microsoft Excel, PowerPoint, Alteryx, Tableau, Think-Cell",
            "certifications": "MBA from Top B-Schools (IIM A/B/C, ISB, Harvard, INSEAD)",
            "experience_level": "Associate to Senior Partner",
            "career_growth": "Premier executive trajectory progressing to Partner, Director, or Fortune 500 Corporate CEO.",
            "internship_roles": "Summer Consultant Intern, Business Analyst Summer Associate",
            "entry_level_roles": "Business Analyst (pre-MBA), Associate Consultant (post-MBA)",
            "average_salary": "₹16 - ₹40 LPA (Indicative range)",
            "salary_indicative": "Business Analyst (0-2 yrs): ₹12 - 22 LPA | Post-MBA Associate (2-5 yrs): ₹25 - 45 LPA | Partner (7+ yrs): ₹1 - 3+ Crores. Indicative figures from MBB Consulting Placement Reports 2024.",
            "future_scope": "Consistently prestigious and high demand as enterprises undergo AI transformations and supply chain re-shoring.",
            "government_opportunities": "NITI Aayog Young Professionals, Government PMUs, National Investment and Infrastructure Fund (NIIF).",
            "private_opportunities": "MBB (McKinsey & Company, Boston Consulting Group, Bain & Company), Strategy&, Oliver Wyman, Kearney, Big 4 Strategy teams.",
            "higher_study_options": "MBA from Global Premier B-Schools, Master's in Management.",
            "entrepreneurship_options": "Founding venture-backed startups, strategic boutique consulting, venture capital investing.",
            "source": "Consulting Careers Association / Top B-School Placement Audits",
            "official_url": "https://www.ncs.gov.in",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 18, "type": "DIRECT"}, {"course_id": 9, "type": "COMMON"}, {"course_id": 16, "type": "COMMON"}, {"course_id": 20, "type": "COMMON"}],
            "exams": [{"exam_id": 77, "importance": "PRIMARY"}, {"exam_id": 78, "importance": "ALTERNATIVE"}],
            "routes": [
                {"title": "Path A: Top Engineering + IIM MBA Route", "type": "COMMON", "steps": "B.Tech from top IIT/NIT -> CAT 99.5%+ -> MBA from IIM Ahmedabad/Bangalore/Calcutta -> On-campus MBB placement -> Associate Consultant."},
                {"title": "Path B: Top Undergraduate to Business Analyst", "type": "COMMON", "steps": "B.A. Economics / B.Com from SRCC / St. Stephen's / IIT -> Direct campus hire as Business Analyst -> Sponsored MBA -> Consultant."}
            ],
            "ladder": [
                {"stage": "Business Analyst / Junior Associate", "exp": "0-2 Years", "desc": "Conducts data analysis, builds financial models, synthesizes expert interviews into slides."},
                {"stage": "Consultant / Project Leader", "exp": "2-5 Years", "desc": "Manages day-to-day client workstreams, guides analysts, presents weekly findings to client VPs."},
                {"stage": "Associate Partner / Principal", "exp": "5-8 Years", "desc": "Leads client relationships, sells new consulting engagements, shapes industry practice."},
                {"stage": "Senior Partner / Managing Director", "exp": "8+ Years", "desc": "Senior equity partner of firm, trusted advisor to CEOs and government cabinet ministers."}
            ],
            "roadmaps": {
                "Class 10": "Develop exceptional academic discipline, mental math speed, and reading breadth.",
                "Class 12": "Score top percentiles in Class 12 board exams. Target top-tier undergraduate colleges.",
                "Graduation": "Practice case interviews (profitability, market entry, guesstimates) and prepare for CAT for admission to top IIMs.",
                "Working Professional": "Master structured communication (Pyramid Principle), executive presence, and industry specialization."
            }
        },
        {
            "title": "Human Resources (HR) Specialist",
            "short_name": "HR Specialist",
            "slug": "hr-specialist",
            "category": "Business, Management & Consulting",
            "sub_category": "Human Capital & People Operations",
            "industry": "Corporate Human Resources",
            "icon": "people",
            "short_description": "Manages talent acquisition, employee relations, compensation & benefits, organizational development, and labor compliance.",
            "description": "HR Specialists build and nurture an organization's human capital. They recruit top talent, design competitive salary structures, foster employee engagement, manage performance appraisal cycles, and ensure statutory compliance with labor laws.",
            "what_they_do": "They screen and interview candidates, structure employee compensation and benefits (ESOPs, health insurance), conduct onboarding, mediate workplace grievances, and organize learning and leadership development programs.",
            "day_to_day_work": "• Sourcing, interviewing, and negotiating job offers for key corporate roles.\n• Designing employee performance review cycles (OKRs, 360-degree feedback).\n• Resolving employee grievances and ensuring workplace POSH compliance.\n• Benchmarking market compensation and structuring salary bands.\n• Managing employee retention strategies and analyzing attrition data.",
            "work_environment": "Corporate headquarters, regional office hubs, technology campuses.",
            "work_modes": "Hybrid / Office",
            "minimum_qualification": "Undergraduate (Any Stream) + MBA in HR preferred",
            "preferred_streams": "Any Stream (Commerce / Psychology / Management)",
            "required_subjects": "Human Resource Management, Psychology, Business Studies",
            "technical_skills": "Talent Acquisition, Compensation & Benefits (Total Rewards), HR Analytics, Performance Management, Labor Law Compliance, POSH Act",
            "soft_skills": "High Emotional Intelligence, Active Listening, Conflict Mediation, Discretion, Cultural Sensitivity",
            "tools": "Workday, Darwinbox, LinkedIn Recruiter, BambooHR, Excel",
            "certifications": "SHRM Certified Professional (SHRM-CP), Professional in Human Resources (PHR)",
            "experience_level": "Entry-Level to Senior",
            "career_growth": "Broad corporate career progressing to HR Business Partner (HRBP), Head of Talent, or Chief Human Resources Officer (CHRO).",
            "internship_roles": "HR Intern, Talent Acquisition Intern, Employee Engagement Trainee",
            "entry_level_roles": "HR Associate, Recruiter, HR Generalist, People Operations Assistant",
            "average_salary": "₹4.5 - ₹14 LPA (Indicative range)",
            "salary_indicative": "Entry-Level HR Associate (0-2 yrs): ₹4 - 6.5 LPA | HR Business Partner (3-6 yrs): ₹8 - 16 LPA | Chief Human Resources Officer (7+ yrs): ₹25 - 65+ LPA. Indicative figures from SHRM India 2024.",
            "future_scope": "Vital long-term corporate necessity adapting to hybrid work cultures, AI talent sourcing, and employee wellness priorities.",
            "government_opportunities": "HR Officer in PSUs (IOCL, BHEL, ONGC via UGC-NET / GATE), Personnel Officer in Public Sector Banks.",
            "private_opportunities": "TCS, Infosys, Hindustan Unilever, Google, Amazon, Reliance, top multinational capability centers.",
            "higher_study_options": "MBA in Human Resources (XLRI Jamshedpur, TISS Mumbai, SCMHRD), Ph.D. in Organizational Behavior.",
            "entrepreneurship_options": "Executive recruitment firm, HR tech startup, corporate team building consultancy.",
            "source": "Society for Human Resource Management (SHRM India) / XLRI",
            "official_url": "https://www.shrm.org",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 18, "type": "DIRECT"}, {"course_id": 17, "type": "COMMON"}, {"course_id": 16, "type": "ALTERNATIVE"}],
            "exams": [{"exam_id": 77, "importance": "PRIMARY"}, {"exam_id": 78, "importance": "PRIMARY"}],
            "routes": [{"title": "Path A: Top HR MBA Route (XLRI / TISS)", "type": "COMMON", "steps": "Graduation in any stream -> XAT / CAT / CUET-PG -> MBA in HR from XLRI Jamshedpur or TISS Mumbai -> Campus hire as HR Business Partner."}],
            "ladder": [
                {"stage": "HR Associate / Recruiter", "exp": "0-2 Years", "desc": "Screens resumes, coordinates candidate interviews, manages onboarding paperwork."},
                {"stage": "HR Business Partner (HRBP)", "exp": "2-5 Years", "desc": "Partners with engineering/sales leadership to drive retention, performance, and appraisals."},
                {"stage": "Head of Talent Acquisition / Total Rewards", "exp": "5-8 Years", "desc": "Designs enterprise compensation frameworks and multinational hiring strategies."},
                {"stage": "Chief Human Resources Officer (CHRO)", "exp": "8+ Years", "desc": "Directs organizational culture, leadership succession, and board executive compensation."}
            ],
            "roadmaps": {
                "Class 10": "Build strong interpersonal communication skills and interest in psychology.",
                "Class 12": "Choose any stream for Class 12 board exams.",
                "Graduation": "Complete graduation with focus on Psychology, Commerce, or Management. Prepare for XAT for XLRI Jamshedpur (India's premier HR school).",
                "Working Professional": "Earn SHRM-CP certification and develop expertise in people analytics and automated HRMS tools."
            }
        },
        {
            "title": "Supply Chain & Logistics Analyst",
            "short_name": "Supply Chain Analyst",
            "slug": "supply-chain-analyst",
            "category": "Business, Management & Consulting",
            "sub_category": "Supply Chain, Logistics & Procurement",
            "industry": "Supply Chain & E-Commerce",
            "icon": "truck",
            "short_description": "Optimizes end-to-end flow of raw materials and finished goods from suppliers to warehouses and consumers.",
            "description": "Supply Chain Analysts optimize the complex web of sourcing, manufacturing, warehousing, freight transportation, and final customer delivery. They forecast product demand, minimize inventory holding costs, and resolve delivery bottlenecks.",
            "what_they_do": "They analyze historical sales trends to forecast inventory demand, evaluate vendor lead times, track freight logistics performance, optimize warehouse rack utilization, and design supply chain disaster backup plans.",
            "day_to_day_work": "• Forecasting SKU inventory demand using statistical time-series models in Excel.\n• Tracking freight shipment delays and negotiating carrier freight rates.\n• Auditing warehouse inventory turnover ratios and stockouts.\n• Managing supplier purchase orders and evaluating on-time delivery metrics.\n• Analyzing transportation routes to reduce logistics fuel costs and carbon footprints.",
            "work_environment": "Corporate e-commerce headquarters, logistics dispatch centers, fulfillment hubs.",
            "work_modes": "Hybrid / Office / Warehouse Inspections",
            "minimum_qualification": "Undergraduate (Engineering / Commerce / BBA / Economics)",
            "preferred_streams": "Science (PCM) / Commerce with Maths",
            "required_subjects": "Mathematics, Operations Research, Statistics",
            "technical_skills": "Demand Forecasting, Inventory Management (EOQ, Safety Stock), Supply Chain Analytics, SQL, Advanced Excel, SAP SCM, Route Optimization",
            "soft_skills": "Analytical Thinking, Problem Solving Under Pressure, Vendor Negotiation, Coordination",
            "tools": "SAP (MM/SCM modules), Microsoft Excel, SQL, Tableau, Power BI, WMS Systems",
            "certifications": "Certified Supply Chain Professional (CSCP - ASCM), Six Sigma Green Belt",
            "experience_level": "Entry-Level to Senior",
            "career_growth": "Broad, vital career progressing to Supply Chain Manager, Director of Logistics, or Chief Supply Chain Officer (CSCO).",
            "internship_roles": "Supply Chain Intern, Logistics Operations Trainee, Procurement Intern",
            "entry_level_roles": "Junior Supply Chain Analyst, Logistics Coordinator, Procurement Associate",
            "average_salary": "₹4.5 - ₹13 LPA (Indicative range)",
            "salary_indicative": "Entry-Level (0-2 yrs): ₹4 - 6.5 LPA | Supply Chain Manager (3-6 yrs): ₹8 - 15 LPA | Director of Supply Chain (7+ yrs): ₹18 - 40+ LPA. Indicative figures from ASCM & E-Commerce Logistics Audits 2024.",
            "future_scope": "Surging national growth driven by India's National Logistics Policy, PM Gati Shakti, e-commerce expansion, and quick-commerce delivery networks.",
            "government_opportunities": "Food Corporation of India (FCI), Central Warehousing Corporation (CWC), Container Corporation of India (CONCOR).",
            "private_opportunities": "Amazon, Flipkart, Blinkit, Zepto, Delhivery, Blue Dart, Tata Motors, Unilever, Maersk.",
            "higher_study_options": "MBA in Supply Chain / Operations Management (IIM Mumbai, SCMHRD), Master's in Global Logistics.",
            "entrepreneurship_options": "Third-party logistics (3PL) warehousing agency, specialized cold-chain freight company.",
            "source": "Association for Supply Chain Management (ASCM) / Logistics Sector Skill Council",
            "official_url": "https://www.ascm.org",
            "verification_status": "VERIFIED",
            "courses": [{"course_id": 11, "type": "COMMON"}, {"course_id": 17, "type": "COMMON"}, {"course_id": 18, "type": "SPECIALIZED"}],
            "exams": [{"exam_id": 77, "importance": "PRIMARY"}, {"exam_id": 37, "importance": "ALTERNATIVE"}],
            "routes": [{"title": "Path A: Engineering / Commerce to Supply Chain", "type": "COMMON", "steps": "B.Tech / B.Com / BBA -> Learn SQL & Supply Chain Modeling -> Earn CSCP certification -> E-Commerce Supply Chain Analyst."}],
            "ladder": [
                {"stage": "Supply Chain Analyst", "exp": "0-2 Years", "desc": "Pulls daily inventory reports, tracks shipment transit times, calculates re-order levels."},
                {"stage": "Supply Chain Manager", "exp": "2-5 Years", "desc": "Leads regional warehouse fulfillment, optimizes fleet logistics, negotiates 3PL contracts."},
                {"stage": "Head of Logistics & Procurement", "exp": "5-8 Years", "desc": "Directs nationwide fulfillment network, reduces end-to-end logistics costs by 15-20%."},
                {"stage": "Chief Supply Chain Officer (CSCO)", "exp": "8+ Years", "desc": "Owns global supply chain resilience, supplier partnerships, and sustainability."}
            ],
            "roadmaps": {
                "Class 10": "Focus on arithmetic, percentages, and logical problem-solving.",
                "Class 12": "Choose Science or Commerce with Mathematics.",
                "Graduation": "Complete B.Tech or BBA/B.Com. Learn SQL, advanced Excel, and study inventory management algorithms (EOQ, safety stock).",
                "Working Professional": "Earn the ASCM CSCP (Certified Supply Chain Professional) credential and master SAP SCM."
            }
        }
    ]

print("Catalog builder part 4 ready.")
