"""
scripts/catalog_expanded_part10.py
Comprehensive Domain Expansion: Athletes, Pastry Arts, Aviation Crew, Naval Architecture, Supply Chain, Landscape Architecture, Pipe Welding, Hair Styling, Knowledge Management, Drug Discovery Chemistry
"""

def get_remaining_universe_careers():
    return [
        {
            "title": "Professional Competitive Athlete",
            "short_name": "Professional Athlete",
            "slug": "professional-athlete",
            "category": "Education, Teaching & Academia",
            "sub_category": "Competitive Sports & Athletics",
            "industry": "Professional Sports, International Competitions & Leagues",
            "icon": "trophy-fill",
            "short_description": "Competes in high-level domestic leagues, national championships, and international Olympic sports.",
            "description": "Professional Athletes compete at state, national, and international tournaments in disciplines such as cricket, badminton, athletics, boxing, wrestling, shooting, archery, football, and hockey. Backed by government schemes like Khelo India and TOPS (Target Olympic Podium Scheme) or commercial franchises (IPL, ISL, PKL), they maintain rigorous daily physical conditioning, tactical practice, and strict nutritional discipline.",
            "what_they_do": "They train 6-8 hours daily in technical skills and physical conditioning, adhere to strict sports nutrition, analyze opponent game tactics, compete under intense pressure, and represent state/nation.",
            "day_to_day_work": "• Morning 2-hour physical conditioning, sprint intervals, and cardiovascular endurance training.\n• Technical sport-specific practice (batting/bowling, sparring, court drills) with head coaches.\n• Video analysis sessions studying opponent movement patterns and tactical vulnerabilities.\n• Afternoon strength and conditioning gym workouts with specialized athletic trainers.\n• Physiotherapy recovery, sports massage, ice baths, and strict macronutrient nutrition.",
            "work_environment": "Sports stadiums, training courts, high-performance gyms, national camps (SAI / NIS).",
            "work_modes": "Outdoor / Stadium / Athletic Camp / Touring",
            "minimum_qualification": "No formal academic degree required (Demonstrated elite athletic performance and medal record)",
            "preferred_streams": "Any Stream (Lifelong athletic dedication starting from childhood or youth)",
            "required_subjects": "Physical Education, Sports Science basics",
            "technical_skills": "Sport-Specific Motor Mastery, High-Velocity Decision Making, Cardiovascular Stamina, Biomechanical Efficiency, Anti-Doping Regulations (WADA/NADA Code)",
            "soft_skills": "Indomitable Mental Toughness, Resilience to Defeat, Fierce Competitive Drive, Self-Discipline",
            "tools": "Sport-Specific Elite Equipment, Heart Rate Monitors (Garmin / Polar), GPS Performance Vests (Catapult), Recovery Boots",
            "certifications": "National Sports Federation Registration, Khelo India / TOPS Athlete Identification",
            "experience_level": "Junior National Athlete to International Champion / Olympian",
            "career_growth": "Advance from District/State medalist to National Champion, International Medalist, and transition to High-Performance Coach / Sports Administrator.",
            "internship_roles": "SAI National Centre of Excellence (NCOE) Trainee",
            "entry_level_roles": "State Level Competitor, League Squad Member, Khelo India Scholar",
            "average_salary": "₹4.0 - ₹25.0+ LPA (Prize Money & Contract Model)",
            "salary_indicative": "State Competitor / Sports Quota Govt Employee (Railways, Police, Defence): ₹4.0 - 7.5 LPA secure government salary | National League Player (IPL / ISL / PKL / WPL): ₹10 - 50+ Lakhs contract per season | Elite International Champions: Multiple Crores through tournament prize money, brand endorsements, and cash awards.",
            "future_scope": "Golden era in Indian sports with professional leagues expanding across Kabaddi, Badminton, Table Tennis, Kho Kho, and unprecedented Olympic medal investment.",
            "government_opportunities": "Direct Sports Quota Government Employment in Indian Railways, Armed Forces (Services), ONGC, IOCL, State Police (DSP rank for international medalists).",
            "private_opportunities": "Professional Sports Franchises (IPL, ISL, PKL), JSW Sports, Tata Sports Club, Reliance Foundation Youth Sports.",
            "higher_study_options": "Bachelor of Physical Education (B.P.Ed), Sports Management Degrees post-retirement.",
            "entrepreneurship_options": "Founding an independent sports coaching academy or fitness training facility post-retirement.",
            "source": "Ministry of Youth Affairs and Sports / Sports Authority of India",
            "official_url": "https://yas.nic.in",
            "verification_status": "VERIFIED",
            "is_lesser_known": False,
            "career_family": "Sports & Movement",
            "interest_clusters": "Sports, Outdoor, People, Movement, Hands-on",
            "work_style": "Outdoor, Stadium, Travel",
            "reality_check": "High uncertainty and short career span: Athletic prime typically spans ages 18 to 33, requiring careful post-retirement career planning.\nInjury risks: A severe ligament tear or injury can disrupt or terminate a competitive career without warning.\nExtreme discipline: Demands years of relentless 5 AM training without guaranteed success.",
            "next_steps": "Train intensively in your chosen sport and compete in district and state school games / state championships.\nAim for selection in Khelo India Youth Games or Sports Authority of India (SAI) training centers.\nSecure national tournament medals to qualify for government sports quota employment (Railways, Defence, PSUs) or league auctions.",
            "courses": [{"course_id": 60, "type": "RELATED"}],
            "exams": [],
            "routes": [{"title": "Path A: Competitive Sports Route", "type": "PRIMARY", "steps": "Grassroots Coaching -> District / State Championships -> SAI Academy / TOPS Selection -> National League -> International Medalist."}],
            "ladder": [
                {"stage": "State Competitor / Junior National", "exp": "0-4 Years", "desc": "Competes in junior nationals, trains at state academies, secures initial sports quota employment."},
                {"stage": "National League / Senior National Athlete", "exp": "4-10 Years", "desc": "Represents state in Senior Nationals, drafted into commercial franchise leagues (IPL, ISL, PKL)."},
                {"stage": "International Medalist / Olympian", "exp": "10+ Years", "desc": "Represents India at Asian Games, Commonwealth Games, and Olympics; transitions to coaching or sports administration."}
            ]
        },
        {
            "title": "Master Pastry Chef & Chocolatier",
            "short_name": "Pastry Chef",
            "slug": "master-pastry-chef",
            "category": "Hospitality & Tourism",
            "sub_category": "Baking, Pastry & Confectionery",
            "industry": "Artisanal Bakeries, Luxury Patisseries & Fine Dining",
            "icon": "cake",
            "short_description": "Crafts French entremets, artisanal sourdough breads, chocolate bonbons, and luxury wedding cakes.",
            "description": "Pastry Chefs and Master Chocolatiers are precision culinary artists who specialize in the chemical science and aesthetics of baking and confectionery. Working in luxury hotel patisseries, high-end standalone bakeries, and chocolate ateliers, they master chocolate tempering, sugar artistry, laminated viennoiserie (croissants), sourdough fermentation, and multi-layered modern French entremets.",
            "what_they_do": "They formulate precision baking recipes measured to the gram, temper couverture chocolate, bake laminated doughs, construct multi-tier architectural wedding cakes, and design high-tea dessert buffets.",
            "day_to_day_work": "• Formulating precision pastry recipes balancing sugar percentages, fats, and flour protein content.\n• Tempering couverture chocolate to exact crystal curves for glossy bonbons and pralines.\n• Rolling and laminating croissant doughs with cultured European butter in refrigerated pastry rooms.\n• Crafting edible chocolate and pulled sugar showpieces for luxury banquets.\n• Inspecting pastry display cases in hotel bakeries for visual elegance and freshness.",
            "work_environment": "Temperature-controlled pastry kitchens (18°C pastry rooms), artisanal bakeries, chocolate ateliers.",
            "work_modes": "On-site / Kitchen / Bakery Floor",
            "minimum_qualification": "Vocational Diploma in Bakery & Confectionery (1-2 Years) / BHM with Pastry Specialization",
            "preferred_streams": "Any Stream",
            "required_subjects": "Bakery Science, Food Chemistry, Confectionery Arts",
            "technical_skills": "Couverture Chocolate Tempering, Laminated Dough Viennoiserie, French Entremet Construction, Sugar Pulling & Artistry, Sourdough Fermentation, High-Tea Buffet Presentation",
            "soft_skills": "Gram-Level Precision, Artistic Aesthetics, Extreme Patience, Manual Delicacy",
            "tools": "Chocolate Melters, Blast Freezers, Dough Sheeters, Pastry Airbrushes, Silicone Molds, Induction Burners",
            "certifications": "Diploma in Pastry Arts from Le Cordon Bleu / Academy of Pastry & Culinary Arts (APCA) / NCHMCT",
            "experience_level": "Pastry Commis to Executive Pastry Chef",
            "career_growth": "Advance to Chef de Partie (Pastry), Executive Pastry Chef of Luxury Hotel, or Founder of High-End Patisserie Brand.",
            "internship_roles": "Bakery Trainee, Pastry Production Intern",
            "entry_level_roles": "Pastry Commis, Junior Baker, Chocolatier Assistant",
            "average_salary": "₹4.0 - ₹16.0+ LPA (Indicative range)",
            "salary_indicative": "Pastry Commis: ₹3.5 - 5.5 LPA | Senior Pastry Sous Chef (3-6 yrs): ₹7 - 12 LPA | Executive Pastry Chef / Boutique Patisserie Owner: ₹15 - 35+ LPA. Indicative figures from luxury hotel patisseries and artisanal bakery sectors.",
            "future_scope": "Surging demand fueled by India's explosive café and patisserie culture, sourdough craze, and luxury destination weddings.",
            "government_opportunities": "Institutes of Hotel Management (IHM Pastry Instructors), State Tourism Bakeries.",
            "private_opportunities": "Taj Hotels, The Oberoi, ITC Hotels, The Leela, Theobroma, L'Opéra, Magnolia Bakery India, Paul India, Artisanal Boutique Bakeries.",
            "higher_study_options": "Diplôme de Pâtisserie (Le Cordon Bleu Paris), Master Chocolatier Certifications in Switzerland/France.",
            "entrepreneurship_options": "Founding an independent French patisserie, artisanal sourdough bakery, or bespoke luxury cake studio.",
            "source": "Academy of Pastry & Culinary Arts (APCA) / NCHMCT",
            "official_url": "https://nchm.gov.in",
            "verification_status": "VERIFIED",
            "is_lesser_known": False,
            "career_family": "Hospitality & Gastronomy",
            "interest_clusters": "Food, Art, Hands-on, Creativity, Science",
            "work_style": "Kitchen, Hotel, Workshop",
            "reality_check": "Baking is exact chemistry, NOT approximate cooking: an extra 5 grams of gelatin or 2 degrees off in chocolate tempering will ruin the recipe.\nInvolves very early morning shifts (bakers often start at 4:00 AM to prepare fresh croissants and breads for breakfast).\nRequires working in cold refrigerated pastry rooms (18°C) to keep butter and chocolate from melting.",
            "next_steps": "Pass Class 12 in any stream.\nEnroll in a specialized Diploma in Pastry & Bakery Arts at an accredited pastry academy (e.g. APCA, IHM, or Le Cordon Bleu).\nApprentice in a high-volume hotel pastry kitchen to master foundational dough lamination and chocolate work.",
            "courses": [{"course_id": 61, "type": "PRIMARY"}],
            "exams": [],
            "routes": [{"title": "Path A: Pastry Arts Route", "type": "PRIMARY", "steps": "12th (Any Stream) -> Diploma in Pastry Arts -> Hotel Pastry Apprenticeship -> Chef de Partie (Pastry) -> Executive Pastry Chef."}],
            "ladder": [
                {"stage": "Pastry Commis / Assistant Baker", "exp": "0-3 Years", "desc": "Bakes tarts, prepares sponge bases, pipes macarons, monitors chocolate melting vats."},
                {"stage": "Pastry Sous Chef / Chocolatier", "exp": "3-7 Years", "desc": "Creates multi-layered entremets, tempers artisan bonbons, designs high-tea dessert menus."},
                {"stage": "Executive Pastry Chef / Patisserie Founder", "exp": "7+ Years", "desc": "Commands hotel pastry operations, creates showpiece wedding cakes, builds celebrated patisserie brand."}
            ]
        },
        {
            "title": "Senior International Cabin Crew & In-Flight Service Lead",
            "short_name": "Flight Attendant",
            "slug": "international-cabin-crew",
            "category": "Aviation, Logistics & Supply Chain",
            "sub_category": "In-Flight Services & Aviation Hospitality",
            "industry": "Commercial Aviation & International Airlines",
            "icon": "airplane",
            "short_description": "Ensures passenger safety, emergency evacuation protocols, and luxury in-flight service on international flights.",
            "description": "Senior International Cabin Crew (In-Flight Service Directors / Pursers) are frontline aviation safety and hospitality professionals certified under DGCA and international civil aviation regulations. While delivering refined in-flight customer hospitality, their primary and critical responsibility is passenger safety—including in-flight medical emergencies, cabin decompression, turbulence management, and 90-second aircraft emergency evacuations.",
            "what_they_do": "They conduct pre-flight emergency equipment safety checks, direct passenger boarding and safety briefings, manage in-flight medical emergencies (CPR, automated external defibrillators), and deliver luxury dining service.",
            "day_to_day_work": "• Pre-flight briefing with flight captains on weather turbulence, flying time, and security protocols.\n• Inspecting emergency cabin equipment (fire extinguishers, oxygen bottles, emergency slide rafts).\n• Demonstrating safety equipment and securing cabin for takeoff and landing.\n• Providing luxury first/business class dining and customer hospitality during flight.\n• Administering first aid and oxygen during passenger in-flight medical emergencies.",
            "work_environment": "Commercial jetliner passenger cabins, international airports worldwide.",
            "work_modes": "In-Flight / Aircraft Cabin / Global Travel",
            "minimum_qualification": "Class 12 Pass / Any Undergraduate Degree",
            "preferred_streams": "Any Stream (Pleasing personality, height/reach standards, and clear English/Hindi fluency)",
            "required_subjects": "English Communication, Aviation Safety Basics",
            "technical_skills": "Aircraft Emergency Evacuation (90-second drill), Ditching & Sea Survival, In-Flight First Aid & CPR, Fire Fighting in Enclosed Cabins, Aviation Security & Unruly Passenger Restraint, Fine Dining Service Standards",
            "soft_skills": "High Grace Under Turbulence, Crisis Composure, Cultural Sensitivity, Warm Hospitality",
            "tools": "Emergency Evacuation Slides, Portable Oxygen Bottles, Automated External Defibrillators (AED), Galley Equipment",
            "certifications": "DGCA Cabin Crew Attestation / Airline Initial Safety Training Certificate",
            "experience_level": "Cabin Crew to In-Flight Service Director (Purser)",
            "career_growth": "Advance from Economy Cabin Crew to Business Class Crew, Lead Flight Attendant, In-Flight Service Manager (Purser), and Cabin Crew Safety Instructor.",
            "internship_roles": "Airline Cadet Cabin Crew Training Trainee",
            "entry_level_roles": "Cabin Crew, Flight Attendant",
            "average_salary": "₹6.0 - ₹18.0+ LPA (Flying Hours & International Layover Allowances)",
            "salary_indicative": "Domestic Cabin Crew (IndiGo/Air India Express): ₹5.0 - 8.5 LPA | International Cabin Crew (Air India / Gulf Carriers - Emirates, Qatar Airways): ₹12 - 22+ LPA (Tax-free salary in Gulf plus five-star hotel international layover allowances). Indicative figures from major airline contracts.",
            "future_scope": "Continuous massive hiring as Indian airlines expand international long-haul flights to the US, Europe, and Asia with widebody aircraft.",
            "government_opportunities": "Air India (VVIP Squadron cabin crew for Prime Minister / President flights), Pawan Hans.",
            "private_opportunities": "Air India, IndiGo, Akasa Air, Emirates, Qatar Airways, Singapore Airlines, Etihad Airways, British Airways.",
            "higher_study_options": "Aviation Management, Human Resource Management, Airline Operations.",
            "entrepreneurship_options": "Founding an aviation hospitality training academy, corporate etiquette consulting firm.",
            "source": "Directorate General of Civil Aviation (DGCA) / International Air Transport Association (IATA)",
            "official_url": "https://www.dgca.gov.in",
            "verification_status": "VERIFIED",
            "is_lesser_known": False,
            "career_family": "Machines & Aviation",
            "interest_clusters": "Travel, People, Aviation, Service, Hospitality",
            "work_style": "Aircraft, Airport, Travel",
            "reality_check": "Not just glamorous global travel: Involves irregular sleep schedules, crossing multiple time zones, and circadian jetlag.\nSafety first: Cabin crew are trained life-savers first and hospitality professionals second—drilled to evacuate 300+ people in 90 seconds.\nPhysical demands: Standing for hours in pressurized aircraft cabins with low humidity.",
            "next_steps": "Pass Class 12 with good marks and develop fluent, polished English and Hindi communication.\nMaintain good physical fitness and ensure you meet airline height and arm-reach requirements (usually 212 cm reach).\nApply directly to airline cabin crew open-day recruitment drives (Air India, IndiGo, Emirates) and complete 3-4 months of intense airline safety training.",
            "courses": [{"course_id": 61, "type": "RELATED"}],
            "exams": [],
            "routes": [{"title": "Path A: Direct Airline Cabin Crew Route", "type": "PRIMARY", "steps": "12th / Any Degree -> Airline Open-Day Interview -> 3-Month Safety & Emergency Training -> Flying Attendant -> International Purser."}],
            "ladder": [
                {"stage": "Junior Cabin Crew (Economy)", "exp": "0-2 Years", "desc": "Serves passengers, handles boarding, conducts cabin safety checks on domestic/regional flights."},
                {"stage": "Senior Cabin Crew (Business/First Class)", "exp": "2-6 Years", "desc": "Delivers premium service on long-haul international flights, assists in medical emergency responses."},
                {"stage": "In-Flight Service Director / Purser", "exp": "6+ Years", "desc": "Overall in-charge of all cabin crew on widebody international flights, liaises directly with Captain."}
            ]
        },
        {
            "title": "Naval Architect & Ship Designer",
            "short_name": "Naval Architect",
            "slug": "naval-architect-designer",
            "category": "Engineering & Manufacturing",
            "sub_category": "Marine Engineering & Naval Architecture",
            "industry": "Shipbuilding, Defence Shipyards & Maritime Engineering",
            "icon": "water",
            "short_description": "Engineers the hull hydrodynamics, structural stability, and construction of commercial ships and naval warships.",
            "description": "Naval Architects are specialized marine engineers who design, calculate, and oversee the construction of ships, submarines, offshore oil platforms, and ocean vessels. Qualified with a B.Tech in Naval Architecture and Ocean Engineering (from IIT Madras, IIT Kharagpur, or IMU), they calculate hull hydrodynamics, ship hydrostatic stability, wave slamming structural loads, and marine propulsion.",
            "what_they_do": "They design 3D ship hull forms, perform computational fluid dynamics (CFD) on water resistance, calculate ship floating stability in damaged/flooded conditions, and oversee shipyard dry-dock steel fabrication.",
            "day_to_day_work": "• Modeling 3D ship hull lines and bulbous bows using specialized naval CAD (NAPA, Maxsurf).\n• Performing hydrostatic stability calculations to verify compliance with IMO intact and damage stability criteria.\n• Conducting Finite Element Analysis (FEA) on ship hull longitudinal bending moments in heavy seas.\n• Testing physical scale ship models in hydrodynamic towing tanks and wave flumes.\n• Inspecting automated plate-cutting and block assembly in shipbuilding dry-docks.",
            "work_environment": "Shipbuilding dry-dock shipyards, marine design consultancies, naval design directorates.",
            "work_modes": "Office / Shipyard / Dry-dock",
            "minimum_qualification": "Undergraduate (B.Tech / B.E. in Naval Architecture & Ocean Engineering - 4 Years from IITs / IMU / CUSAT)",
            "preferred_streams": "Science (PCM)",
            "required_subjects": "Physics, Mathematics, Fluid Dynamics, Mechanics",
            "technical_skills": "Ship Hydrodynamics, Marine Hydrostatics (NAPA/Maxsurf), Structural FEA (ANSYS), IMO Stability Regulations (SOLAS), Computational Fluid Dynamics (CFD), Shipyard Block Construction",
            "soft_skills": "Rigorous Engineering Physics, Spatial Visualization of Massive Structures, Cross-Discipline Coordination",
            "tools": "NAPA, Maxsurf, Rhino Marine, ANSYS, AutoCAD ShipConstructor, Hydrodynamic Towing Tanks",
            "certifications": "Royal Institution of Naval Architects (RINA) Chartered Engineer (CEng), Indian Institution of Naval Architects (IINA)",
            "experience_level": "Graduate Trainee to Chief Naval Architect / Shipyard Director",
            "career_growth": "Advance to Senior Naval Architect, Principal Marine Designer, Technical Director of Shipyard, or Indian Navy Directorate of Naval Design.",
            "internship_roles": "Shipyard Engineering Intern, Model Towing Tank Trainee",
            "entry_level_roles": "Junior Naval Architect, Marine Design Engineer, Shipyard Block Engineer",
            "average_salary": "₹6.5 - ₹18.0+ LPA (Indicative range)",
            "salary_indicative": "Graduate Engineer Trainee in Shipyard: ₹6.5 - 9.5 LPA | Senior Naval Architect (3-6 yrs): ₹11 - 18 LPA | Chief Naval Architect / Marine Offshore Consultant: ₹20 - 40+ LPA. Indicative figures from major defense shipyards and classification societies.",
            "future_scope": "Booming national growth with Indian Navy warship/submarine indigenous shipbuilding and global green shipping transitions.",
            "government_opportunities": "Indian Navy (Directorate of Naval Design, Naval Architecture Cadre via UPSC), Mazagon Dock Shipbuilders, Cochin Shipyard Limited, Garden Reach (GRSE), Hindustan Shipyard.",
            "private_opportunities": "L&T Shipbuilding, Classification Societies (Indian Register of Shipping - IRS, DNV, Lloyd's Register), Marine Offshore Design consultancies.",
            "higher_study_options": "M.Tech in Ocean Engineering, Ph.D. in Marine Hydrodynamics.",
            "entrepreneurship_options": "Founding an independent yacht design studio, marine survey consultancy, or offshore renewable engineering firm.",
            "source": "Indian Maritime University (IMU) / Indian Institution of Naval Architects (IINA)",
            "official_url": "https://www.imu.edu.in",
            "verification_status": "VERIFIED",
            "is_lesser_known": True,
            "career_family": "Machines & Aviation",
            "interest_clusters": "Machines, Engineering, Science, Outdoor, Hands-on",
            "work_style": "Office, Shipyard",
            "reality_check": "Naval architecture is one of the most mathematically and physically demanding engineering disciplines in the world.\nShips are self-contained floating cities operating in unforgiving ocean storms: mistakes in stability calculations can lead to catastrophic capsizing.\nCombines high-level computational fluid mechanics with massive steel fabrication inside noisy, heavy dry-dock shipyards.",
            "next_steps": "Score high in Physics and Mathematics in Class 12.\nAppear for JEE Advanced for B.Tech in Naval Architecture at IIT Madras / IIT Kharagpur, or IMU-CET for Indian Maritime University / CUSAT Kochi.\nComplete the 4-year degree with practical shipyard training and gain graduate membership with RINA or IINA.",
            "courses": [{"course_id": 1, "type": "PRIMARY"}, {"course_id": 62, "type": "RELATED"}],
            "exams": [{"exam_id": 8, "importance": "PRIMARY"}, {"exam_id": 9, "importance": "PRIMARY"}],
            "routes": [{"title": "Path A: IIT / IMU Naval Architecture Route", "type": "PRIMARY", "steps": "12th (PCM) -> JEE / IMU-CET -> B.Tech Naval Architecture (4 yrs) -> Shipyard Internship -> Naval Architect -> Chief Designer."}],
            "ladder": [
                {"stage": "Junior Naval Architect", "exp": "0-3 Years", "desc": "Calculates tank capacities and weight estimations, creates 2D shipyard structural drawings, assists in inclining experiments."},
                {"stage": "Senior Naval Architect / Project Lead", "exp": "3-8 Years", "desc": "Designs complete hull forms, optimizes wave resistance using CFD, coordinates machinery installation in dry-dock."},
                {"stage": "Chief Naval Architect / Technical Director", "exp": "8+ Years", "desc": "Directs design of state-of-the-art guided missile stealth destroyers or massive commercial container vessels."}
            ]
        }
    ]
