"""
scripts/catalog_expanded_part3.py
Domain F: Education & Teaching (9 careers)
Domain G: Commerce, Accounting & Finance (8 careers)
Domain H: Business & Management (7 careers)
"""

def get_education_and_teaching_careers():
    return [
        {
            "title": "Primary School Teacher (PRT)",
            "short_name": "Primary Teacher",
            "slug": "primary-school-teacher-prt",
            "category": "Education, Teaching & Academia",
            "sub_category": "School Education",
            "industry": "Primary & Elementary School Education",
            "icon": "mortarboard",
            "short_description": "Teaches foundational literacy, numeracy, and social development to children in Classes 1 to 5.",
            "description": "Primary School Teachers (PRTs) educate young children in their critical formative years (Classes 1 through 5, ages 6 to 11). They teach foundational literacy, numeracy, environmental studies, and basic social-emotional development. Using play-based pedagogy, storytelling, activity sheets, and educational aids aligned with NEP 2020, they create nurturing classroom learning environments.",
            "what_they_do": "They plan age-appropriate lesson plans, teach foundational reading, writing, and mathematics, evaluate student progress through formative assessments, and engage with parents on child development.",
            "day_to_day_work": "• Delivering interactive lessons in language, arithmetic, and environmental studies (EVS).\n• Organizing collaborative group activities, educational games, and creative art sessions.\n• Observing and recording individual children's learning milestones and behavioral growth.\n• Preparing teaching-learning materials (TLM), flashcards, and digital audio-visual aids.\n• Conducting parent-teacher meetings to discuss child social and academic progress.",
            "work_environment": "Primary schools, government elementary schools (KVS, NVS, State Primary Schools), private schools.",
            "work_modes": "On-site / School Classroom",
            "minimum_qualification": "Diploma in Elementary Education (D.El.Ed / D.Ed - 2 Years) or B.El.Ed + CTET Paper I",
            "preferred_streams": "Any Stream (Class 12 in Arts, Science, or Commerce with 50%+)",
            "required_subjects": "Foundational Pedagogy, Child Development, Elementary Maths & Language",
            "technical_skills": "Early Childhood Pedagogy, Foundational Literacy and Numeracy (FLN), Classroom Management, Lesson Planning, Continuous & Comprehensive Evaluation (CCE)",
            "soft_skills": "Immense Patience, Warmth & Empathy, Enthusiastic Storytelling, Positive Reinforcement",
            "tools": "Classroom Smartboards, Teaching Learning Materials (TLM), Storybooks, Phonics Kits",
            "certifications": "Central Teacher Eligibility Test (CTET Paper I) or State TET (Paper I) Qualified",
            "experience_level": "Entry to Senior Teacher",
            "career_growth": "Advance to Senior Primary Teacher, Headmaster / Headmistress of Primary School, or Primary Academic Coordinator.",
            "internship_roles": "Student Teaching Practice Trainee, Elementary Classroom Intern",
            "entry_level_roles": "Primary Teacher (PRT), Assistant Primary Teacher",
            "average_salary": "₹3.5 - ₹8.0 LPA (Indicative range)",
            "salary_indicative": "Private School PRT: ₹3.0 - 5.5 LPA | Government PRT (KVS / DSSSB Pay Level 6): ₹6.0 - 8.5 LPA (Basic ₹35,400 + DA + HRA). Indicative figures from Kendriya Vidyalaya Sangathan (KVS) pay matrix.",
            "future_scope": "National Education Policy (NEP 2020) places massive emphasis on Foundational Literacy and Numeracy (FLN), creating continuous nationwide demand.",
            "government_opportunities": "Kendriya Vidyalaya Sangathan (KVS), Navodaya Vidyalaya Samiti (NVS), Delhi Subordinate Services (DSSSB), State Government Primary Schools.",
            "private_opportunities": "DPS Society, DAV Schools, Ryan International, Podar Education, EuroKids, Heritage Xperiential Learning Schools.",
            "higher_study_options": "Bachelor of Education (B.Ed), M.Ed, Master in Elementary Education.",
            "entrepreneurship_options": "Founding an early-childhood learning center, after-school activity academy, or phonics learning hub.",
            "source": "National Council for Teacher Education (NCTE) / CBSE CTET",
            "official_url": "https://ncte.gov.in",
            "verification_status": "VERIFIED",
            "is_lesser_known": False,
            "career_family": "Education & Pedagogy",
            "interest_clusters": "Teaching, People, Helping, Language",
            "work_style": "School",
            "reality_check": "Requires tremendous day-to-day emotional energy and patience when managing 30-40 energetic young children.\nGovernment PRT posts require clearing CTET Paper-I or State TET; a simple degree without teacher training is not eligible.\nTeaching is one of the most socially impactful careers: you build the foundational base of every child's future.",
            "next_steps": "Complete Class 12 with at least 50% marks in any stream.\nEnroll in a 2-year Diploma in Elementary Education (D.El.Ed) or 4-year B.El.Ed recognized by NCTE.\nClear the Central Teacher Eligibility Test (CTET Paper 1) and apply for government school (KVS, DSSSB) or private school vacancies.",
            "courses": [{"course_id": 31, "type": "RELATED"}],
            "exams": [{"exam_id": 25, "importance": "PRIMARY"}],
            "routes": [{"title": "Path A: Standard PRT Route", "type": "PRIMARY", "steps": "12th (Any Stream) -> D.El.Ed (2 yrs) -> CTET Paper-I -> KVS / DSSSB PRT Exam -> Primary School Teacher."}],
            "ladder": [
                {"stage": "Primary Teacher (PRT)", "exp": "0-5 Years", "desc": "Teaches fundamental language, numeracy, and environmental studies; organizes annual school days and sports."},
                {"stage": "Senior Primary Teacher / Coordinator", "exp": "5-10 Years", "desc": "Mentors junior teachers, designs primary school curricula, coordinates grade-level academic assessments."},
                {"stage": "Primary Headmaster / Headmistress", "exp": "10+ Years", "desc": "Heads the primary school wing, manages teacher scheduling, leads parent-community councils."}
            ]
        },
        {
            "title": "Special Education Teacher",
            "short_name": "Special Educator",
            "slug": "special-education-teacher",
            "category": "Education, Teaching & Academia",
            "sub_category": "Inclusive & Special Education",
            "industry": "Inclusive Education & Child Rehabilitation",
            "icon": "heart",
            "short_description": "Educates and adapts learning for children with autism, ADHD, cerebral palsy, visual/hearing, or intellectual disabilities.",
            "description": "Special Education Teachers design and deliver specialized, adapted education for children and youth with a wide range of learning differences, sensory impairments, and neurodivergent conditions (including Autism Spectrum Disorder, Down Syndrome, ADHD, Dyslexia, and Cerebral Palsy). They create Individualized Education Plans (IEPs) to foster academic, communication, and life-skills independence.",
            "what_they_do": "They assess children's cognitive and functional abilities, draft individualized education programs (IEPs), adapt standard textbooks and curricula, teach assistive technologies (Braille, sign language), and collaborate with general educators in inclusive classrooms.",
            "day_to_day_work": "• Formulating and updating customized Individualized Education Plans (IEPs) for each student.\n• Teaching sensory-adapted reading, writing, and daily life independence skills.\n• Implementing multisensory teaching methods (visual schedules, tactile cards, adaptive software).\n• Co-teaching with mainstream teachers to integrate differently abled children into general classrooms.\n• Counseling parents and coordinating with speech and occupational therapists.",
            "work_environment": "Special education schools, inclusive mainstream schools, child development clinics, rehabilitation centers.",
            "work_modes": "On-site / School / Therapy Centre",
            "minimum_qualification": "Undergraduate (B.Ed in Special Education - 2 Years recognized by RCI)",
            "preferred_streams": "Any Stream (Graduation in Psychology, Arts, Science, or Commerce)",
            "required_subjects": "Special Education, Developmental Psychology, Disability Studies",
            "technical_skills": "Individualized Education Plan (IEP) Design, Applied Behavior Analysis (ABA) Basics, Assistive Learning Technology, Multi-Sensory Instruction, Sensory Integration Adaptation",
            "soft_skills": "Boundless Patience, Compassion, Positive Reinforcement, Resilience, Observant Attentiveness",
            "tools": "Braille slates, Assistive Speech Software, Sensory Weighted Blankets, Visual Communication Cards (PECS)",
            "certifications": "Rehabilitation Council of India (RCI) Professional Registration (Mandatory)",
            "experience_level": "Entry to Senior Level",
            "career_growth": "Advance to Head of Inclusive Education, Special Education Director, or Rehabilitation Consultant.",
            "internship_roles": "Special School Student Teacher, Inclusive Classroom Intern",
            "entry_level_roles": "Special Educator, Resource Room Teacher, Inclusive Education Facilitator",
            "average_salary": "₹4.0 - ₹9.5 LPA (Indicative range)",
            "salary_indicative": "Private Inclusive School Special Educator: ₹4.0 - 6.5 LPA | Government Special Educator (DSSSB / State Govts): ₹6.5 - 9.5 LPA (Pay Level 7) | Private Therapy Clinic Consultant: ₹7 - 14+ LPA. Indicative figures from RCI and DSSSB.",
            "future_scope": "Surging demand: Mandatory court directives (Supreme Court of India) and the RPwD Act 2016 require every mainstream school to appoint qualified special educators.",
            "government_opportunities": "Delhi Subordinate Services Selection Board (DSSSB Special Educator), KVS Inclusive Wings, State Education Directorates, National Institutes (NIEPVD, NIEPMD).",
            "private_opportunities": "Inclusive private schools (Vasant Valley, Step by Step, Heritage School), Tamana Special School, Action for Autism (AFA), Amar Jyoti Charitable Trust.",
            "higher_study_options": "M.Ed in Special Education, Ph.D. in Disability Studies, Advanced Certifications in Autism/ADHD.",
            "entrepreneurship_options": "Founding an independent child development and learning support center or inclusive activity school.",
            "source": "Rehabilitation Council of India (RCI) / Ministry of Social Justice and Empowerment",
            "official_url": "https://rehabcouncil.nic.in",
            "verification_status": "VERIFIED",
            "is_lesser_known": True,
            "career_family": "Education & Pedagogy",
            "interest_clusters": "Teaching, Helping, People, Psychology",
            "work_style": "School, Clinic",
            "reality_check": "Must hold mandatory registration with the Rehabilitation Council of India (RCI) to practice legally in India.\nRequires tremendous emotional patience, resilience, and celebratory joy over small, hard-won developmental milestones.\nOne of the most deeply noble, respected, and personally fulfilling callings in education.",
            "next_steps": "Earn a Bachelor's degree in any discipline (Psychology, Arts, Science, or Commerce).\nEnroll in a 2-year B.Ed in Special Education (Mental Retardation / Autism / Hearing / Visual Impairment) at an RCI-recognized college.\nComplete teaching practice, register with the Rehabilitation Council of India (RCI), and clear CTET/State TET.",
            "courses": [{"course_id": 31, "type": "RELATED"}],
            "exams": [{"exam_id": 25, "importance": "PRIMARY"}],
            "routes": [{"title": "Path A: Standard Special Educator Route", "type": "PRIMARY", "steps": "Graduation (Any Stream) -> B.Ed Special Education (2 yrs) -> RCI Registration -> CTET -> Special Educator in School."}],
            "ladder": [
                {"stage": "Special Educator / Resource Teacher", "exp": "0-3 Years", "desc": "Assesses learning differences, conducts resource room remedial sessions, implements IEPs."},
                {"stage": "Senior Inclusive Education Specialist", "exp": "3-8 Years", "desc": "Guides mainstream teachers on differentiated instruction, trains parents, manages assistive technology."},
                {"stage": "Head of Inclusive Education / Director", "exp": "8+ Years", "desc": "Directs school-wide disability inclusion policies, conducts national workshops, advises education boards."}
            ]
        },
        {
            "title": "Instructional Designer",
            "short_name": "Instructional Designer",
            "slug": "instructional-designer",
            "category": "Education, Teaching & Academia",
            "sub_category": "EdTech & Learning Design",
            "industry": "EdTech, Corporate Learning & Digital Pedagogy",
            "icon": "laptop",
            "short_description": "Designs digital learning experiences, online course curriculum, interactive modules, and training simulations.",
            "description": "Instructional Designers (Learning Experience Designers - LXDs) apply educational psychology, adult learning theories (Andragogy), and pedagogical frameworks (ADDIE, Bloom's Taxonomy) to create effective digital courses, e-learning simulations, interactive multimedia modules, and corporate training programs.",
            "what_they_do": "They collaborate with Subject Matter Experts (SMEs), write storyboards for video animations and simulations, architect online learning pathways, design formative knowledge quizzes, and evaluate learning outcomes.",
            "day_to_day_work": "• Interviewing domain subject matter experts (engineers, professors, doctors) to extract learning concepts.\n• Structuring pedagogical course architecture and writing detailed multimedia storyboards.\n• Building interactive modules in authoring tools (Articulate Storyline, Adobe Captivate).\n• Designing microlearning bite-sized lessons, branching scenario simulations, and gamified assessments.\n• Reviewing learner analytics on Learning Management Systems (LMS) to optimize course completion rates.",
            "work_environment": "EdTech companies, corporate learning & development (L&D) offices, universities, remote home office.",
            "work_modes": "Hybrid / Remote / Office",
            "minimum_qualification": "Undergraduate / Postgraduate in Education, English, Psychology, Mass Communication, or IT",
            "preferred_streams": "Any Stream (Arts, Humanities, Science, or Engineering)",
            "required_subjects": "Learning Theories, Educational Technology, English Communication",
            "technical_skills": "ADDIE Model, Bloom's Taxonomy, Storyboarding, Articulate Storyline, Adobe Captivate, SCORM Compliance, Learning Management Systems (Canvas, Moodle), Gamification",
            "soft_skills": "Pedagogical Empathy, Clear Conceptual Simplification, Creative Storytelling, Cross-Functional Collaboration",
            "tools": "Articulate 360 (Storyline, Rise), Adobe Captivate, Canva, Moodle, Miro, Camtasia",
            "certifications": "Certified Instructional Designer (ATD / Dale Carnegie), PG Diploma in Instructional Design (Symbiosis / IGNOU)",
            "experience_level": "Entry to Senior Level",
            "career_growth": "Advance to Senior Learning Architect, Head of Instructional Design, or Chief Learning Officer (CLO).",
            "internship_roles": "Instructional Design Intern, E-Learning Content Trainee",
            "entry_level_roles": "Associate Instructional Designer, E-Learning Content Developer, Curriculum Writer",
            "average_salary": "₹5.0 - ₹15.0 LPA (Indicative range)",
            "salary_indicative": "Associate Instructional Designer: ₹5.0 - 7.5 LPA | Senior Instructional Designer (3-6 yrs): ₹8.5 - 14 LPA | Learning Architect / L&D Director (7+ yrs): ₹16 - 28+ LPA. Indicative figures from corporate EdTech and L&D salary surveys.",
            "future_scope": "Explosive global demand driven by workplace upskilling, online university degrees, and digital corporate training.",
            "government_opportunities": "SWAYAM / NPTEL (Ministry of Education), IGNOU, NCERT Digital Wings (DIKSHA portal), State Educational Technology Institutes.",
            "private_opportunities": "Accenture, Deloitte, Infosys Learning, Coursera, upGrad, NIIT, Wiley, Pearson, Tata Consultancy Services.",
            "higher_study_options": "Master in Educational Technology, Ph.D. in Learning Sciences.",
            "entrepreneurship_options": "Founding a bespoke e-learning content agency or corporate microlearning development studio.",
            "source": "Association for Talent Development (ATD) / IGNOU",
            "official_url": "https://www.td.org",
            "verification_status": "VERIFIED",
            "is_lesser_known": True,
            "career_family": "Education & Pedagogy",
            "interest_clusters": "Teaching, Technology, Writing, Design, Creativity",
            "work_style": "Office, Remote",
            "reality_check": "Not a graphic designer or software programmer: Focused primarily on cognitive science—how human brains absorb and retain knowledge.\nRequires interviewing sometimes impatient subject experts to simplify complex concepts into accessible lessons.\nHeavy desk-based work writing detailed slide-by-slide pedagogical storyboards.",
            "next_steps": "Earn a Bachelor's degree in English, Psychology, Education, Communication, or any field.\nComplete a professional certification or diploma in Instructional Design (e.g. Symbiosis SCDL or ATD).\nBuild a portfolio with interactive e-learning samples created using Articulate Rise/Storyline.",
            "courses": [{"course_id": 31, "type": "PRIMARY"}, {"course_id": 57, "type": "RELATED"}],
            "exams": [],
            "routes": [{"title": "Path A: Content/Psychology to ID", "type": "PRIMARY", "steps": "Bachelor's Degree -> Diploma in Instructional Design -> Build Storyboard Portfolio -> Associate Instructional Designer -> Learning Architect."}],
            "ladder": [
                {"stage": "Associate Instructional Designer", "exp": "0-2 Years", "desc": "Writes scripts and storyboards, creates quizzes, builds interactive slides in Articulate Rise."},
                {"stage": "Senior Instructional Designer", "exp": "2-6 Years", "desc": "Architects end-to-end multi-module online curricula, conducts learner needs analysis with corporate clients."},
                {"stage": "Chief Learning Architect / L&D Lead", "exp": "6+ Years", "desc": "Directs enterprise-wide organizational learning strategies, oversees teams of designers and multimedia artists."}
            ]
        }
    ]

def get_commerce_accounting_and_finance_careers():
    return [
        {
            "title": "Cost and Management Accountant (CMA)",
            "short_name": "Cost Accountant (CMA)",
            "slug": "cost-management-accountant-cma",
            "category": "Finance, Banking & Accounting",
            "sub_category": "Accounting & Cost Audit",
            "industry": "Manufacturing, Corporate Finance & Strategic Costing",
            "icon": "calculator",
            "short_description": "Controls manufacturing product costs, conducts statutory cost audits, and optimizes operational profitability.",
            "description": "Cost and Management Accountants (CMAs) are statutory financial specialists qualified under The Institute of Cost Accountants of India (ICMAI). They specialize in cost determination, cost control, operational efficiency, pricing strategies, and statutory Cost Audits mandated by the Companies Act. They work inside factories, manufacturing giants, and energy complexes to optimize production economics.",
            "what_they_do": "They calculate unit production costs, conduct inventory and operational cost audits, evaluate capital project investments, identify operational wastages, and formulate competitive product pricing.",
            "day_to_day_work": "• Preparing monthly Cost Sheets and analyzing variances between standard and actual costs.\n• Conducting statutory Cost Audits under Section 148 of the Companies Act 2013.\n• Analyzing plant capacity utilization, idle labor hours, and machine maintenance expenses.\n• Formulating marginal costing and break-even models to guide product launch pricing.\n• Advising corporate leadership on supply chain expenditure reduction and working capital.",
            "work_environment": "Manufacturing industrial plants, corporate headquarters, cost accounting audit firms.",
            "work_modes": "Hybrid / Plant Floor / Office",
            "minimum_qualification": "Professional Qualification (CMA by ICMAI - Foundation -> Intermediate -> Final)",
            "preferred_streams": "Commerce / Any Stream (Open to 12th pass & Graduates)",
            "required_subjects": "Cost Accounting, Financial Management, Taxation, Company Law",
            "technical_skills": "Standard Costing, Variance Analysis, Statutory Cost Audit (CRA-1 to CRA-4), Activity Based Costing (ABC), Financial Modeling, ERP (SAP CO module)",
            "soft_skills": "Operational Scrutiny, Business Commercial Sense, Analytical Rigor, Objective Skepticism",
            "tools": "SAP ERP (CO / FICO Modules), Microsoft Excel (Advanced Cost Models), ICMAI Portals",
            "certifications": "Associate Member of the Institute of Cost Accountants of India (ACMA), Fellow (FCMA)",
            "experience_level": "Entry CMA to Chief Financial Officer (CFO)",
            "career_growth": "Advance to Senior Cost Analyst, Plant Finance Controller, Head of Costing, or CFO.",
            "internship_roles": "CMA Practical Trainee (3 years mandatory practical training)",
            "entry_level_roles": "Cost Trainee, Management Trainee (Finance), Plant Accountant",
            "average_salary": "₹7.0 - ₹18.0 LPA (Indicative range)",
            "salary_indicative": "Newly Qualified CMA: ₹7.0 - 10.5 LPA campus placement | Experienced Plant Controller (4-7 yrs): ₹12 - 20 LPA | Chief Financial Officer / Cost Auditor: ₹22 - 45+ LPA. Indicative figures from ICMAI campus placement records.",
            "future_scope": "Essential statutory requirement across core manufacturing, steel, cement, pharma, and automotive industries under Make in India.",
            "government_opportunities": "Indian Cost Accounts Service (ICoAS via UPSC), Maharatna PSUs (ONGC, BHEL, Coal India, IOCL, SAIL, NTPC).",
            "private_opportunities": "Tata Steel, Reliance Industries, Larsen & Toubro, Maruti Suzuki, Hindustan Unilever, Aditya Birla Group.",
            "higher_study_options": "Chartered Institute of Management Accountants (CIMA UK), Executive MBA.",
            "entrepreneurship_options": "Founding an independent Practicing Cost Accountant (PCA) firm for statutory cost audits and management consultancy.",
            "source": "The Institute of Cost Accountants of India (ICMAI)",
            "official_url": "https://icmai.in",
            "verification_status": "VERIFIED",
            "is_lesser_known": False,
            "career_family": "Finance & Accountancy",
            "interest_clusters": "Numbers, Business, Analysis, Leadership",
            "work_style": "Office, Factory",
            "reality_check": "Rigorous multi-stage examination (Foundation, Inter, Final) with rigorous national passing percentages.\nRequires mandatory 3 years of practical industrial training inside manufacturing units or corporate finance.\nDistinct from Chartered Accountants (CAs): While CAs focus on statutory financial accounting, CMAs focus deeply on internal manufacturing cost efficiency and operational pricing.",
            "next_steps": "Register for CMA Foundation after Class 12 (or direct entry to CMA Intermediate after graduation).\nClear CMA Intermediate (Group 1 & Group 2) and complete mandatory computer and industrial training.\nClear CMA Final (Group 3 & Group 4), complete 3 years of practical training, and obtain ACMA membership.",
            "courses": [{"course_id": 28, "type": "RELATED"}],
            "exams": [],
            "routes": [{"title": "Path A: ICMAI CMA Route", "type": "PRIMARY", "steps": "12th Commerce / Any Stream -> CMA Foundation -> CMA Intermediate -> 3-Yr Industrial Training -> CMA Final -> Qualified CMA."}],
            "ladder": [
                {"stage": "Cost Trainee / Management Trainee", "exp": "0-3 Years", "desc": "Calculates bill of materials (BOM), reconciles inventory valuations, tracks plant variance reports."},
                {"stage": "Plant Finance Controller / Cost Manager", "exp": "3-8 Years", "desc": "Manages plant financial budgeting, optimizes manufacturing line costs, conducts statutory cost audits."},
                {"stage": "Chief Financial Officer (CFO) / Partner", "exp": "8+ Years", "desc": "Directs enterprise-wide financial and cost strategy, advises Board on capital expansions and pricing."}
            ]
        },
        {
            "title": "Company Secretary (CS)",
            "short_name": "Company Secretary (CS)",
            "slug": "company-secretary-cs",
            "category": "Finance, Banking & Accounting",
            "sub_category": "Corporate Governance & Compliance",
            "industry": "Corporate Governance, Board Advisory & Securities Law",
            "icon": "shield-check",
            "short_description": "Serves as the chief corporate governance advisor to Board of Directors and ensures statutory legal compliance.",
            "description": "Company Secretaries (CS) are statutory corporate officers recognized under the Companies Act 2013 as Key Managerial Personnel (KMP) alongside the CEO and CFO. Qualified through The Institute of Company Secretaries of India (ICSI), they advise the Board of Directors on corporate governance, conduct secretarial audits, manage SEBI stock exchange compliances, and handle investor relations.",
            "what_they_do": "They organize and record Board of Directors and shareholder general meetings, ensure statutory filings with the Registrar of Companies (ROC), ensure listing regulations compliance (SEBI LODR), and manage corporate mergers.",
            "day_to_day_work": "• Preparing agendas and drafting Board resolutions for Board and Committee meetings.\n• Ensuring mandatory quarterly compliance with SEBI Listing Obligations (LODR).\n• Conducting Secretarial Audits for listed and public companies under Section 204 of Companies Act.\n• Filing annual statutory returns, financial statements, and director changes on MCA-21 portal.\n• Managing corporate shares allotment, dividend distribution, and insider trading compliance.",
            "work_environment": "Corporate boardrooms, corporate headquarters, practicing CS firms.",
            "work_modes": "Hybrid / Office / Boardroom",
            "minimum_qualification": "Professional Qualification (CS by ICSI - CSEET -> Executive -> Professional)",
            "preferred_streams": "Commerce / Arts / Any Stream (Open to 12th pass & Graduates)",
            "required_subjects": "Company Law, Securities Law, Jurisprudence, Economic & Commercial Laws",
            "technical_skills": "Companies Act 2013, SEBI LODR Regulations, Secretarial Standards (SS-1, SS-2), Secretarial Audit, Board Meeting Minutes Drafting, Corporate Due Diligence, MCA-21",
            "soft_skills": "High Corporate Integrity, Discretion with Board Secrets, Precise Legal Draftsmanship, Diplomatic Tact",
            "tools": "MCA-21 Portal, BSE/NSE Listing Portals, BoardPaq, Secretarial Compliance Trackers",
            "certifications": "Associate Member of the Institute of Company Secretaries of India (ACS), Fellow (FCS)",
            "experience_level": "Entry CS to Chief Corporate Governance Officer",
            "career_growth": "Advance to Head of Secretarial & Legal, Chief Compliance Officer (CCO), or Board Executive Director.",
            "internship_roles": "CS Trainee (21 months mandatory practical training with corporate/firm)",
            "entry_level_roles": "Assistant Company Secretary, Secretarial Officer, Compliance Executive",
            "average_salary": "₹6.5 - ₹18.0 LPA (Indicative range)",
            "salary_indicative": "Newly Qualified CS: ₹6.5 - 9.5 LPA campus placement | Mid-Level Company Secretary (4-7 yrs): ₹11 - 18 LPA | Group Company Secretary of Nifty 50 Conglomerate: ₹25 - 60+ LPA. Indicative figures from ICSI campus recruitment records.",
            "future_scope": "Statutorily mandatory: Under Section 203 of Companies Act 2013, every listed company and public company with paid-up capital of ₹10+ Crore MUST appoint a whole-time Company Secretary.",
            "government_opportunities": "Ministry of Corporate Affairs (MCA), SEBI, National Company Law Tribunal (NCLT benches), Central PSUs.",
            "private_opportunities": "Reliance Industries, Tata Sons, HDFC Bank, Infosys, Mahindra, ICICI Bank, Practicing CS Firms.",
            "higher_study_options": "LL.B. (frequent powerful dual qualification: CS + LL.B.), Corporate Governance Fellowships.",
            "entrepreneurship_options": "Establishing an independent Practicing Company Secretary (PCS) firm providing secretarial audit and incorporation services.",
            "source": "The Institute of Company Secretaries of India (ICSI)",
            "official_url": "https://www.icsi.edu",
            "verification_status": "VERIFIED",
            "is_lesser_known": False,
            "career_family": "Finance & Accountancy",
            "interest_clusters": "Business, Law, Government, Leadership, Writing",
            "work_style": "Office, Government Office",
            "reality_check": "Professional statutory examination with rigorous testing of corporate, tax, and securities law.\nRequires 21 months of rigorous practical training under a practicing CS or recognized corporate company.\nDirect proximity to company promoters and Board of Directors from early in career: requires maturity and absolute confidentiality.",
            "next_steps": "Appear for CSEET (Company Secretary Executive Entrance Test) after Class 12 (or direct entry for graduates).\nClear CS Executive Program (Group 1 & Group 2).\nClear CS Professional Program, complete 21-month mandatory practical training, and obtain ACS membership.",
            "courses": [{"course_id": 28, "type": "RELATED"}],
            "exams": [],
            "routes": [{"title": "Path A: ICSI CS Route", "type": "PRIMARY", "steps": "12th (Any Stream) -> CSEET Entrance -> CS Executive -> 21-Month Practical Training -> CS Professional -> Qualified CS."}],
            "ladder": [
                {"stage": "Secretarial Trainee / Assistant CS", "exp": "0-3 Years", "desc": "Drafts board notices, prepares annual filing forms on MCA portal, maintains statutory member registers."},
                {"stage": "Company Secretary / Compliance Head", "exp": "3-8 Years", "desc": "Directs Board and AGM meetings, manages SEBI stock exchange disclosures, conducts Secretarial Audits."},
                {"stage": "Group Company Secretary & Chief Governance Officer", "exp": "8+ Years", "desc": "Key Managerial Personnel (KMP) advising the Board of Directors, leads major cross-border corporate mergers."}
            ]
        },
        {
            "title": "Actuary & Risk Modeler",
            "short_name": "Actuary",
            "slug": "actuary-risk-modeler",
            "category": "Finance, Banking & Accounting",
            "sub_category": "Actuarial Science & Risk",
            "industry": "Life & General Insurance, Pensions & Risk Analytics",
            "icon": "shield-slash",
            "short_description": "Uses advanced mathematics, probability, and financial statistics to price insurance policies and evaluate financial risks.",
            "description": "Actuaries are elite mathematical and financial risk professionals qualified through the Institute of Actuaries of India (IAI) or IFoA (UK). They analyze the financial consequences of future uncertain events—such as death, disability, property catastrophe, medical claims, and financial market crashes. They design and price insurance policies, calculate financial reserves, and manage pension funds.",
            "what_they_do": "They build complex stochastic models, analyze mortality and morbidity statistical tables, determine insurance premium rates, evaluate pension solvency, and model climate catastrophe insurance risks.",
            "day_to_day_work": "• Constructing actuarial cash-flow models in Prophet or Python.\n• Analyzing historical claims data to set insurance loss reserves (IBNR - Incurred But Not Reported).\n• Modeling longevity and mortality trends for life insurance and annuity products.\n• Evaluating capital adequacy ratios under statutory solvency regulations (IRDAI).\n• Pricing general insurance policies for motor vehicles, crop insurance, and catastrophic floods.",
            "work_environment": "Insurance headquarters, multinational reinsurance firms, actuarial consulting firms, investment banks.",
            "work_modes": "Hybrid / Office",
            "minimum_qualification": "Undergraduate (Mathematics, Statistics, Economics, Commerce, or Any Stream with strong mathematical aptitude)",
            "preferred_streams": "Science (PCM) / Commerce with Mathematics",
            "required_subjects": "Mathematics, Statistics, Probability",
            "technical_skills": "Stochastic Modeling, Probability & Statistics, Financial Mathematics, Life Contingencies, Loss Reserving, Actuarial Software (Prophet, MoSes), Python / R / SQL",
            "soft_skills": "Exceptional Quantitative Acumen, Intellectual Stamina, Business Pragmatism, Communication of Complex Risk",
            "tools": "Prophet, MoSes, R, Python, Advanced Excel VBA, SQL",
            "certifications": "Fellow of the Institute of Actuaries of India (FIAI) / IFoA (passing 13 Core, Specialist, and Practice exams)",
            "experience_level": "Actuarial Analyst to Appointed Actuary / Chief Risk Officer",
            "career_growth": "Advance from Actuarial Analyst to Associate Actuary (AIAI), Fellow Actuary (FIAI), and Appointed Actuary.",
            "internship_roles": "Actuarial Intern, Risk Analytics Trainee",
            "entry_level_roles": "Actuarial Analyst, Junior Risk Modeler, Pricing Analyst",
            "average_salary": "₹8.0 - ₹30.0+ LPA (Indicative range)",
            "salary_indicative": "Entry-Level Actuarial Analyst (3-5 papers passed): ₹8.0 - 12 LPA | Associate Actuary (8-10 papers): ₹14 - 22 LPA | Fully Qualified Fellow Actuary (FIAI / Appointed Actuary): ₹25 - 60+ LPA. Indicative figures from Institute of Actuaries of India salary surveys.",
            "future_scope": "Among the highest-earning, most intellectually prestigious professions in global finance with immense scarcity of fully qualified actuaries in India.",
            "government_opportunities": "Insurance Regulatory and Development Authority of India (IRDAI), Life Insurance Corporation of India (LIC), GIC Re.",
            "private_opportunities": "HDFC Life, ICICI Prudential, SBI Life, Swiss Re, Munich Re, Milliman, Willis Towers Watson, Mercer.",
            "higher_study_options": "Fellowship in Actuarial Science (FIAI / FIA), M.Sc in Actuarial Science / Quantitative Finance.",
            "entrepreneurship_options": "Founding an independent actuarial consulting firm for pension fund valuations and insurtech startups.",
            "source": "Institute of Actuaries of India (IAI)",
            "official_url": "https://actuariesindia.org",
            "verification_status": "VERIFIED",
            "is_lesser_known": True,
            "career_family": "Finance & Accountancy",
            "interest_clusters": "Numbers, Science, Business, Analysis",
            "work_style": "Office, Remote",
            "reality_check": "Extremely demanding professional journey: Requires clearing 13 rigorous national examinations while working full-time in an actuarial job.\nRequires exceptional aptitude and love for pure mathematical statistics, calculus, and probability theory.\nHigh rewards: Massive career security and global portability of credentials.",
            "next_steps": "Score exceptionally well in Mathematics in Class 12 (90%+ recommended).\nAppear for ACET (Actuarial Common Entrance Test) conducted by the Institute of Actuaries of India (IAI).\nPursue a degree in Mathematics, Statistics, or Actuarial Science while studying for and clearing early actuarial papers (Core Principles CS1, CM1).",
            "courses": [{"course_id": 16, "type": "PRIMARY"}, {"course_id": 28, "type": "RELATED"}],
            "exams": [],
            "routes": [{"title": "Path A: IAI Actuarial Route", "type": "PRIMARY", "steps": "B.Sc Maths/Stats -> ACET Exam -> Clear Core Papers (CS1, CM1) -> Actuarial Analyst -> Clear All 13 Papers -> Fellow Actuary (FIAI)."}],
            "ladder": [
                {"stage": "Actuarial Analyst (3-6 Papers)", "exp": "0-3 Years", "desc": "Runs insurance projection models in Prophet, analyzes mortality and loss ratios, prepares reporting tables."},
                {"stage": "Associate Actuary (AIAI)", "exp": "3-7 Years", "desc": "Prices complex insurance products, models solvency capital, validates technical reinsurance agreements."},
                {"stage": "Appointed Actuary / Chief Risk Officer (FIAI)", "exp": "7+ Years", "desc": "Statutory custodian of insurance financial health, signs off on company reserves, advises Board of Directors."}
            ]
        },
        {
            "title": "Forensic Accountant & Fraud Investigator",
            "short_name": "Forensic Accountant",
            "slug": "forensic-accountant-investigator",
            "category": "Finance, Banking & Accounting",
            "sub_category": "Forensic Accounting & Auditing",
            "industry": "Financial Crime Investigation & Forensic Advisory",
            "icon": "search",
            "short_description": "Investigates corporate financial fraud, embezzlement, money laundering, and tracks hidden assets.",
            "description": "Forensic Accountants combine accounting, auditing, and investigative legal skills to unearth complex corporate financial fraud, bribery, fund diversion, shell company networks, and white-collar embezzlement. They analyze manipulated financial records, trace illicit funds through offshore shell entities, and testify as expert accounting witnesses in economic offense courts.",
            "what_they_do": "They analyze altered accounting ledgers, conduct digital forensic email investigations, perform asset-tracing across banks, write forensic audit reports for regulatory enforcement agencies, and assist insolvency resolution professionals.",
            "day_to_day_work": "• Reconstructing manipulated financial records and identifying round-tripping of bank funds.\n• Analyzing thousands of corporate bank statements to trace diverted loan proceeds.\n• Interviewing suspects and company whistleblowers regarding procurement kickbacks.\n• Reviewing confiscated digital accounting server backups with forensic software.\n• Preparing forensic investigation reports for Serious Fraud Investigation Office (SFIO) or CBI.",
            "work_environment": "Forensic consulting firms, Big 4 advisory offices, law enforcement agencies, corporate risk departments.",
            "work_modes": "Hybrid / Office / Investigative Site",
            "minimum_qualification": "Undergraduate / Professional (Chartered Accountant - CA / CMA / M.Com) + Forensic Certification",
            "preferred_streams": "Commerce / Finance (with Accounting background)",
            "required_subjects": "Auditing, Financial Accounting, Law of Financial Crimes",
            "technical_skills": "Financial Statement Fraud Analysis, Fund Tracing, Asset Recovery, Digital Forensics, Prevention of Money Laundering Act (PMLA), Bank Reconciliation Auditing",
            "soft_skills": "Inquisitive Skepticism, Tenacious Persistence, Objective Analysis, Discretion Under Pressure",
            "tools": "ACL Analytics, IDEA Data Analysis, Forensic Email Analyzers, i2 Analyst's Notebook, Excel",
            "certifications": "Certified Fraud Examiner (CFE) by ACFE, Forensic Accounting and Fraud Detection (FAFD) by ICAI",
            "experience_level": "Entry to Senior Level",
            "career_growth": "Advance to Forensic Senior Manager, Forensic Advisory Partner, or Chief Ethics & Compliance Officer.",
            "internship_roles": "Forensic Audit Intern, Financial Crime Analytics Trainee",
            "entry_level_roles": "Forensic Accounting Associate, Fraud Analyst, Forensic Investigator",
            "average_salary": "₹6.5 - ₹18.0 LPA (Indicative range)",
            "salary_indicative": "Forensic Associate: ₹6.5 - 9 LPA | Senior Forensic Investigator (3-6 yrs): ₹10 - 16 LPA | Partner (Forensic Advisory in Big 4): ₹20 - 45+ LPA. Indicative figures from forensic accounting industry benchmarks.",
            "future_scope": "Explosive demand with the rise of corporate insolvencies (IBC), banking non-performing asset (NPA) forensic mandates, and strict SEBI/SFIO scrutiny.",
            "government_opportunities": "Serious Fraud Investigation Office (SFIO), Enforcement Directorate (ED), Central Bureau of Investigation (CBI Economic Offences Wing), Income Tax Investigation Wings.",
            "private_opportunities": "Big 4 Forensic Practices (EY, Deloitte, PwC, KPMG), Alvarez & Marsal, Kroll, Grant Thornton, BDO India, Top Banking Fraud Risk Units.",
            "higher_study_options": "Master in Forensic Science & Accounting, Certified Financial Crime Specialist (CFCS).",
            "entrepreneurship_options": "Establishing an independent boutique corporate fraud investigation and dispute litigation advisory firm.",
            "source": "Institute of Chartered Accountants of India (ICAI FAFD) / ACFE",
            "official_url": "https://www.icai.org",
            "verification_status": "VERIFIED",
            "is_lesser_known": True,
            "career_family": "Finance & Accountancy",
            "interest_clusters": "Numbers, Law, Analysis, Research, Government",
            "work_style": "Office, Government Office",
            "reality_check": "Not like TV crime drama: Involves painstaking, highly meticulous analysis of thousands of Excel rows, journal entries, and bank vouchers.\nRequires dealing with adversarial corporate environments where suspects attempt to conceal records.\nDemands deep technical understanding of accounting standards to detect deliberate manipulation.",
            "next_steps": "Earn a degree in Commerce (B.Com) or qualify as a Chartered Accountant (CA) / CMA.\nPursue the Certified Fraud Examiner (CFE) credential or ICAI's Forensic Accounting and Fraud Detection (FAFD) certification.\nJoin the forensic and dispute advisory practice of a consulting firm (Big 4 or specialist firm).",
            "courses": [{"course_id": 28, "type": "PRIMARY"}, {"course_id": 29, "type": "PRIMARY"}],
            "exams": [],
            "routes": [{"title": "Path A: CA / Commerce to Forensic Route", "type": "PRIMARY", "steps": "B.Com / CA -> Forensic Accounting Certification (CFE/FAFD) -> Forensic Associate -> Senior Fraud Investigator -> Forensic Partner."}],
            "ladder": [
                {"stage": "Forensic Associate / Analyst", "exp": "0-3 Years", "desc": "Conducts data analytics on journal entries, reconciles bank accounts, analyzes electronic invoice trails."},
                {"stage": "Senior Forensic Investigator", "exp": "3-7 Years", "desc": "Leads field fraud investigations, interviews witnesses, authors comprehensive forensic reports for regulatory agencies."},
                {"stage": "Partner / Head of Forensic Services", "exp": "7+ Years", "desc": "Testifies as expert witness in commercial tribunals, advises enterprise boards on major integrity crises."}
            ]
        }
    ]

def get_business_and_management_careers():
    return [
        {
            "title": "Social Enterprise Founder & Impact Entrepreneur",
            "short_name": "Social Entrepreneur",
            "slug": "social-enterprise-entrepreneur",
            "category": "Business, Management & Consulting",
            "sub_category": "Social Enterprise & Sustainability",
            "industry": "Social Entrepreneurship, Clean Tech & Rural Innovation",
            "icon": "globe-americas",
            "short_description": "Builds sustainable, revenue-generating businesses solving social, healthcare, educational, or environmental problems.",
            "description": "Social Entrepreneurs combine the mission-driven heart of an NGO with the financial discipline and scalability of a commercial enterprise. Rather than relying on charitable donations, they build viable business models delivering affordable clean energy, rural healthcare access, sustainable agriculture inputs, clean water, or accessible education for underserved populations.",
            "what_they_do": "They design double-bottom-line business models (financial profit + measurable social impact), develop low-cost products for underserved markets, secure impact investment funding, and measure ESG impact metrics.",
            "day_to_day_work": "• Field testing low-cost technological products in rural villages and peri-urban communities.\n• Pitching to impact venture capital funds (Acumen, Omidyar, Aavishkaar Capital) and angel networks.\n• Managing sales distribution networks through grassroots women self-help groups (SHGs).\n• Tracking quantitative social impact metrics (CO2 tons mitigated, households electrified, farmers' income increased).\n• Overseeing supply chain operations, manufacturing quality, and financial cash-flow sustainability.",
            "work_environment": "Grassroots rural field locations, startup incubators, urban enterprise offices.",
            "work_modes": "Field / Office / Hybrid",
            "minimum_qualification": "Any Educational Background (Engineering, Business, Social Sciences, Agriculture, or Arts)",
            "preferred_streams": "Any Stream",
            "required_subjects": "Entrepreneurship, Business Management, Social Development",
            "technical_skills": "Impact Measurement & Management (IMM), Lean Startup Methodology, Unit Economics, Grassroots Distribution, Grant & Impact Equity Fundraising, ESG Frameworks",
            "soft_skills": "Deep Social Empathy, Indomitable Resilience, Persuasive Storytelling, Community Trust Building",
            "tools": "Impact Dashboards, Lean Canvas, Financial Cashflow Models, Mobile Field Survey Tools (KoboToolbox)",
            "certifications": "Social Enterprise Accelerator Fellowship (UnLtd India, Villgro, Acumen Fellows)",
            "experience_level": "Startup Founder to Enterprise CEO",
            "career_growth": "Advance from early-stage pilot founder to scaled enterprise CEO impacting millions of lives nationwide.",
            "internship_roles": "Social Enterprise Fellow, Impact Investment Intern",
            "entry_level_roles": "Operations Manager, Field Project Lead, Impact Associate",
            "average_salary": "₹4.0 - ₹18.0+ LPA (Founder Equity & Mission Model)",
            "salary_indicative": "Early-Stage Seed Stage Founder: ₹4 - 7 LPA (modest founder salary while conserving runway) | Scaled Series A/B Funded Enterprise Founder: ₹12 - 25+ LPA plus substantial enterprise equity value. Indicative figures from Indian impact startup ecosystem.",
            "future_scope": "Enormous growth supported by India's expanding Social Stock Exchange (SSE), corporate CSR funding mandates, and global climate transition funds.",
            "government_opportunities": "Startup India Seed Fund, NITI Aayog Atal Innovation Mission (AIM), BIRAC Social Innovation Grants, NABARD Rural Innovation Funds.",
            "private_opportunities": "Aavishkaar Capital, Villgro, Tata Social Enterprise Challenge, SELCO India, Goonj, Phool.co, Frontier Markets.",
            "higher_study_options": "MBA in Social Entrepreneurship (TISS Mumbai), Master in Social Innovation (Oxford / Stanford).",
            "entrepreneurship_options": "Direct founder career path: launching innovative clean-tech, health-tech, or agri-tech social enterprises.",
            "source": "Atal Innovation Mission (NITI Aayog) / Villgro Innovations",
            "official_url": "https://aim.gov.in",
            "verification_status": "VERIFIED",
            "is_lesser_known": False,
            "career_family": "Social Sciences",
            "interest_clusters": "Business, Helping, Society, Leadership, Nature",
            "work_style": "Field, Office, Outdoor",
            "reality_check": "Harder than conventional commercial business: Must achieve both commercial profitability and measurable positive social impact.\nRequires spending significant time listening to and working alongside rural and low-income communities.\nHigh uncertainty during the early pilot phase before achieving product-market fit.",
            "next_steps": "Identify a real, painful problem faced by underserved communities (e.g. farm waste burning, menstrual hygiene, solar irrigation).\nBuild a simple, low-cost prototype and test it directly with 50-100 grassroots community users.\nApply to social incubators like Villgro, T-Hub, or Atal Incubation Centers to secure seed funding and mentorship.",
            "courses": [{"course_id": 36, "type": "PRIMARY"}, {"course_id": 66, "type": "RELATED"}],
            "exams": [],
            "routes": [{"title": "Path A: Direct Venture Creation", "type": "PRIMARY", "steps": "Identify Social Problem -> Build Pilot Prototype -> Incubator Selection -> Seed Funding -> Scaled Social Enterprise."}],
            "ladder": [
                {"stage": "Pilot Founder", "exp": "0-2 Years", "desc": "Tests grassroots prototype, validates user willingness to pay, secures incubator grant funding."},
                {"stage": "Growth-Stage Enterprise CEO", "exp": "2-6 Years", "desc": "Expands distribution to multiple districts, hires operations team, raises institutional impact capital."},
                {"stage": "National Impact Leader", "exp": "6+ Years", "desc": "Scales enterprise across multiple states, influences national welfare policy, mentors upcoming founders."}
            ]
        },
        {
            "title": "Human Resources Business Partner (HRBP)",
            "short_name": "HRBP",
            "slug": "hr-business-partner",
            "category": "Business, Management & Consulting",
            "sub_category": "Human Resources Management",
            "industry": "Corporate Human Resources & Talent Strategy",
            "icon": "person-lines-fill",
            "short_description": "Aligns company talent strategy, executive leadership, organizational culture, and employee performance.",
            "description": "Human Resources Business Partners (HRBPs) act as strategic talent advisors to corporate business unit heads and executive leadership. Rather than handling basic personnel paperwork, HRBPs drive organizational design, workforce capability planning, high-potential leadership development, employee retention strategies, and change management during corporate transformations.",
            "what_they_do": "They partner with business leaders to forecast talent needs, manage performance appraisal cycles, design executive compensation and incentives, coach managers on people leadership, and resolve workplace conflicts.",
            "day_to_day_work": "• Meeting business leaders to diagnose team productivity, attrition drivers, and hiring requirements.\n• Facilitating annual talent reviews, 9-box performance-potential matrix evaluations, and promotions.\n• Coaching managers on constructive employee feedback, conflict resolution, and leadership development.\n• Designing employee engagement programs, diversity and inclusion initiatives, and retention plans.\n• Managing organizational restructuring and change management during business pivots.",
            "work_environment": "Corporate headquarters, regional offices, technology parks, hybrid work environments.",
            "work_modes": "Hybrid / Office",
            "minimum_qualification": "Postgraduate (MBA in Human Resources / PGDM from premier institutes like XLRI, TISS, IIMs)",
            "preferred_streams": "Any Stream (Graduation in Psychology, Commerce, Arts, or Engineering)",
            "required_subjects": "Human Resource Management, Organizational Behavior, Industrial Psychology",
            "technical_skills": "Strategic Workforce Planning, 9-Box Talent Review, Competency Mapping, Employee Engagement Metrics (eNPS), HR Analytics, Performance Management Systems",
            "soft_skills": "High Emotional Intelligence (EQ), Strategic Communication, Conflict Mediation, Executive Presence",
            "tools": "Workday, SAP SuccessFactors, Darwinbox, Lattice, Culture Amp, PowerBI HR Dashboards",
            "certifications": "SHRM-CP / SHRM-SCP (Society for Human Resource Management), HRCI (PHR/SPHR)",
            "experience_level": "Entry to Chief Human Resources Officer (CHRO)",
            "career_growth": "Advance to Senior HRBP, Head of HR for Business Division, and Chief Human Resources Officer (CHRO).",
            "internship_roles": "HR Management Trainee, Talent Strategy Intern",
            "entry_level_roles": "Associate HRBP, HR Generalist, Talent Specialist",
            "average_salary": "₹7.0 - ₹22.0 LPA (Indicative range)",
            "salary_indicative": "Management Trainee (HR post-MBA): ₹7.0 - 12 LPA | HRBP (3-6 yrs): ₹12 - 20 LPA | Head of HR / CHRO (8+ yrs): ₹25 - 60+ LPA. Indicative figures from national HR compensation surveys.",
            "future_scope": "Essential corporate function as competition for top talent, hybrid work cultures, and employee well-being take center stage.",
            "government_opportunities": "Senior HR / Personnel Officer in PSUs (ONGC, IOCL, Coal India, NTPC, BHEL).",
            "private_opportunities": "Hindustan Unilever, Tata Group, Google India, Microsoft, Infosys, ITC, Aditya Birla Group, Reliance Retail.",
            "higher_study_options": "Executive Education in Strategic HR Leadership, Ph.D. in Organizational Behavior.",
            "entrepreneurship_options": "Founding an executive talent search agency or organizational culture consulting practice.",
            "source": "National HRD Network (NHRDN) / SHRM India",
            "official_url": "https://www.nationalhrd.org",
            "verification_status": "VERIFIED",
            "is_lesser_known": False,
            "career_family": "Business & Management",
            "interest_clusters": "People, Business, Leadership, Helping",
            "work_style": "Office, Remote",
            "reality_check": "Modern HR is a strategic business discipline, not just organizing office events and festivals.\nRequires balancing employee empathy with tough commercial business decisions (layoffs, performance exits).\nMastering data analytics (predicting attrition, measuring productivity) is increasingly essential.",
            "next_steps": "Complete a Bachelor's degree in any stream (Psychology, Commerce, Arts, or Engineering).\nAppear for CAT, XAT, or national entrances to secure admission in MBA HR (XLRI Jamshedpur, TISS Mumbai, SCMHRD, IIMs).\nComplete corporate summer internships in talent strategy and join as an HR Management Trainee.",
            "courses": [{"course_id": 36, "type": "PRIMARY"}, {"course_id": 67, "type": "RELATED"}],
            "exams": [],
            "routes": [{"title": "Path A: MBA HR to HRBP", "type": "PRIMARY", "steps": "Undergraduate Degree -> MBA in HR (2 yrs) -> Management Trainee -> HRBP -> Head of HR -> CHRO."}],
            "ladder": [
                {"stage": "HR Management Trainee / Associate HRBP", "exp": "0-3 Years", "desc": "Facilitates onboarding, manages employee query resolution, supports performance appraisal reviews."},
                {"stage": "Senior HR Business Partner", "exp": "3-8 Years", "desc": "Partners with VP of Engineering / Sales, leads talent succession planning, executes retention strategies."},
                {"stage": "Chief Human Resources Officer (CHRO)", "exp": "8+ Years", "desc": "Member of Executive Committee, shapes company-wide culture, reports directly to CEO and Board."}
            ]
        }
    ]
