"""
scripts/catalog_expanded_part8.py
Comprehensive Domain Expansion (55+ Authentic Non-Tech Occupational Pathways)
"""

def get_additional_school_education_careers():
    return [
        {
            "title": "Trained Graduate Teacher (TGT)",
            "short_name": "TGT Teacher",
            "slug": "trained-graduate-teacher-tgt",
            "category": "Education, Teaching & Academia",
            "sub_category": "School Education",
            "industry": "Secondary School Education",
            "icon": "book-half",
            "short_description": "Teaches subject-specific curriculum (Maths, Science, English, Social Science) to secondary school students in Classes 6 to 10.",
            "description": "Trained Graduate Teachers (TGTs) educate students in middle and secondary school grades (Classes 6 through 10, ages 11 to 16). Specialized in a primary academic subject such as Mathematics, Science, Social Science, Hindi, or English, they prepare adolescent students for board examinations, guide laboratory experiments, and foster critical inquiry.",
            "what_they_do": "They deliver subject-specialized classroom lectures, manage laboratory practicals, prepare students for CBSE/ICSE/State 10th board exams, and assess cognitive learning outcomes.",
            "day_to_day_work": "• Teaching 4-5 subject-specialized classes daily using interactive pedagogical methods.\n• Conducting science laboratory experiments or mathematical problem-solving workshops.\n• Preparing question papers, grading unit tests, and maintaining board exam progress records.\n• Mentoring students through adolescent peer pressures and learning difficulties.\n• Participating in school remedial teaching programs for struggling learners.",
            "work_environment": "Secondary schools (KVS, NVS, State Secondary, Private CBSE/ICSE schools).",
            "work_modes": "On-site / School / Lab",
            "minimum_qualification": "Undergraduate (Bachelor's Degree in relevant subject + B.Ed - 2 Years) + CTET Paper II",
            "preferred_streams": "Any Stream matching subject specialization (B.Sc for Science/Maths, B.A. for Social Science/Languages)",
            "required_subjects": "Teaching Subject (Maths / Physics / Chemistry / Biology / History / Geography / English), B.Ed Pedagogy",
            "technical_skills": "Subject Didactics, Lab Demonstration, CBSE/NCERT Curriculum Architecture, Formative & Summative Assessments, Digital Classroom Tools",
            "soft_skills": "Patience with Adolescents, Inspiring Oratory, Impartial Discipline, Empathy",
            "tools": "Science Lab Apparatus, Interactive Whiteboards, NCERT Exemplar Problem Books, Google Classroom",
            "certifications": "CTET Paper II (Central Teacher Eligibility Test) or State TET Paper II Qualified",
            "experience_level": "Entry to Senior TGT",
            "career_growth": "Advance to Post Graduate Teacher (PGT), Secondary Academic Coordinator, or Vice-Principal.",
            "internship_roles": "B.Ed School Internship Trainee (4 months mandatory teaching practice)",
            "entry_level_roles": "TGT (Science / Maths / English / SST), Secondary Assistant Teacher",
            "average_salary": "₹4.5 - ₹9.5 LPA (Indicative range)",
            "salary_indicative": "Private School TGT: ₹4.0 - 6.5 LPA | Government TGT (KVS / DSSSB Pay Level 7): ₹7.0 - 10.0 LPA (Basic ₹44,900 + DA + HRA). Indicative figures from KVS and state education directorates.",
            "future_scope": "Continuous massive recruitment nationwide across thousands of Kendriya Vidyalayas, Navodaya Vidyalayas, and private schools.",
            "government_opportunities": "Kendriya Vidyalaya Sangathan (KVS TGT), Navodaya Vidyalaya Samiti (NVS), DSSSB Delhi, State Secondary Education Boards.",
            "private_opportunities": "DPS Society, DAV Public Schools, Amity International, Birla Vidya Mandir, Modern Schools.",
            "higher_study_options": "Master's Degree (M.Sc / M.A. in teaching subject) leading to PGT, M.Ed.",
            "entrepreneurship_options": "Founding a secondary academic coaching institute or online subject tutoring platform.",
            "source": "NCTE / Kendriya Vidyalaya Sangathan",
            "official_url": "https://kvsangathan.nic.in",
            "verification_status": "VERIFIED",
            "is_lesser_known": False,
            "career_family": "Education & Pedagogy",
            "interest_clusters": "Teaching, People, Science, Language, Helping",
            "work_style": "School, Lab",
            "reality_check": "Demands strong subject mastery: Secondary students ask challenging questions in physics, algebra, and world history.\nRequires clearing both B.Ed and CTET Paper II to be legally eligible for government and accredited CBSE schools.\nInvolves significant homework checking, test creation, and parent-teacher accountability.",
            "next_steps": "Earn a Bachelor's degree (B.Sc or B.A.) in your chosen subject with at least 50% aggregate.\nComplete a 2-year Bachelor of Education (B.Ed) recognized by NCTE.\nClear CTET Paper II and apply for KVS, NVS, or state TGT recruitment examinations.",
            "courses": [{"course_id": 31, "type": "PRIMARY"}, {"course_id": 13, "type": "RELATED"}],
            "exams": [{"exam_id": 25, "importance": "PRIMARY"}, {"exam_id": 26, "importance": "PRIMARY"}],
            "routes": [{"title": "Path A: Standard TGT Route", "type": "PRIMARY", "steps": "B.A. / B.Sc -> B.Ed (2 yrs) -> CTET Paper-II -> KVS / DSSSB TGT Exam -> Secondary School Teacher."}],
            "ladder": [
                {"stage": "Trained Graduate Teacher (TGT)", "exp": "0-5 Years", "desc": "Teaches secondary classes 6-10, conducts science practicals, prepares students for board exams."},
                {"stage": "Senior TGT / Subject Department Head", "exp": "5-10 Years", "desc": "Coordinates subject curricula across secondary classes, conducts teacher workshops, mentors intern teachers."},
                {"stage": "Vice Principal / PGT Promotion", "exp": "10+ Years", "desc": "Promoted to Post Graduate Teacher or Vice-Principal overseeing secondary school administration."}
            ]
        },
        {
            "title": "Post Graduate Teacher (PGT)",
            "short_name": "PGT Teacher",
            "slug": "post-graduate-teacher-pgt",
            "category": "Education, Teaching & Academia",
            "sub_category": "School Education",
            "industry": "Higher Secondary & Senior Secondary School Education",
            "icon": "mortarboard-fill",
            "short_description": "Teaches advanced academic subjects to senior secondary students in Classes 11 and 12.",
            "description": "Post Graduate Teachers (PGTs) are master's-qualified senior educators who teach senior secondary students (Classes 11 and 12). Specialized in disciplines such as Physics, Chemistry, Mathematics, Biology, Accountancy, Economics, History, or Political Science, they guide students through competitive board syllabi and prepare them for national university entrance examinations.",
            "what_they_do": "They teach rigorous higher secondary concepts (calculus, organic chemistry, macroeconomic theory), conduct advanced school laboratory practicals, evaluate Class 12 board examination papers, and mentor students on college streams.",
            "day_to_day_work": "• Delivering conceptual lectures on advanced Class 11 and 12 CBSE/State curricula.\n• Conducting laboratory practical sessions in Physics, Chemistry, Biology, or Computer Science.\n• Designing rigorous mock exams and practicing past 10-year board examination question sets.\n• Serving as external or internal examiner for Class 12 board practical examinations.\n• Providing academic counselling on undergraduate course choices and career streams.",
            "work_environment": "Senior secondary schools, junior colleges, pre-university colleges (PUCs).",
            "work_modes": "On-site / School / Lab",
            "minimum_qualification": "Postgraduate (Master's Degree - M.Sc / M.A. / M.Com in relevant subject + B.Ed - 2 Years)",
            "preferred_streams": "Postgraduate in relevant stream (Science / Commerce / Arts)",
            "required_subjects": "Master's Degree Subject + B.Ed Pedagogy",
            "technical_skills": "Advanced Subject Mastery, Higher Secondary Board Exam Evaluation, Practical Lab Direction, Pedagogical Scaffolding",
            "soft_skills": "Intellectual Authority, Academic Mentorship, Engaging Exposition, Student Encouragement",
            "tools": "Higher Secondary Laboratory Equipment, Smartboards, NCERT Master Texts, Question Bank Generators",
            "certifications": "B.Ed Degree (Mandatory), KVS/NVS/State PGT Selection",
            "experience_level": "Entry to Senior PGT",
            "career_growth": "Advance to Senior PGT, School Vice-Principal, Principal, or Education Officer.",
            "internship_roles": "PGT Student Teacher Intern",
            "entry_level_roles": "Post Graduate Teacher (PGT Physics/Maths/Chem/Eco/History), Lecturer in Junior College",
            "average_salary": "₹5.5 - ₹11.5 LPA (Indicative range)",
            "salary_indicative": "Private Senior Secondary School PGT: ₹4.5 - 8.0 LPA | Government PGT (KVS / DSSSB Pay Level 8): ₹8.0 - 12.0 LPA (Basic ₹47,600 + DA + HRA). Indicative figures from KVS pay matrix.",
            "future_scope": "Continuous national demand as senior secondary education expands across government and private institutions.",
            "government_opportunities": "Kendriya Vidyalaya Sangathan (KVS PGT), Navodaya Vidyalaya Samiti (NVS PGT), Delhi Subordinate Services (DSSSB PGT), State Higher Secondary Schools.",
            "private_opportunities": "Delhi Public School, The Cathedral and John Connon School, Bishop Cotton, Mayo College, FIITJEE/Allen Senior Secondary Schools.",
            "higher_study_options": "M.Ed, Ph.D. in Subject Discipline (enabling transition to College Professorship).",
            "entrepreneurship_options": "Establishing a specialized Class 11-12 board and competitive entrance coaching academy.",
            "source": "Kendriya Vidyalaya Sangathan / CBSE",
            "official_url": "https://kvsangathan.nic.in",
            "verification_status": "VERIFIED",
            "is_lesser_known": False,
            "career_family": "Education & Pedagogy",
            "interest_clusters": "Teaching, Science, Numbers, Language, People",
            "work_style": "School, Lab",
            "reality_check": "Requires profound subject mastery: Teaching calculus, wave optics, or macroeconomic balance of payments leaves no room for superficial knowledge.\nHigh pressure: Student Class 12 board marks determine college admissions and carry high expectations from parents.\nRequires both a postgraduate Master's degree (M.A., M.Sc, M.Com) AND a B.Ed.",
            "next_steps": "Complete a Bachelor's and Master's degree (M.Sc / M.A. / M.Com) in your chosen subject with at least 50-55% aggregate.\nComplete a 2-year Bachelor of Education (B.Ed) recognized by NCTE.\nAppear for KVS PGT, NVS PGT, or State PGT competitive teacher selection examinations.",
            "courses": [{"course_id": 31, "type": "PRIMARY"}, {"course_id": 13, "type": "RELATED"}, {"course_id": 14, "type": "RELATED"}],
            "exams": [{"exam_id": 26, "importance": "PRIMARY"}, {"exam_id": 32, "importance": "PRIMARY"}],
            "routes": [{"title": "Path A: Standard PGT Route", "type": "PRIMARY", "steps": "B.Sc/B.A. -> M.Sc/M.A. in Subject -> B.Ed (2 yrs) -> KVS / DSSSB PGT Recruitment Exam -> PGT Teacher."}],
            "ladder": [
                {"stage": "Post Graduate Teacher (PGT)", "exp": "0-5 Years", "desc": "Teaches Class 11 and 12, conducts board practicals, guides board examination preparation."},
                {"stage": "Senior PGT / Academic In-Charge", "exp": "5-10 Years", "desc": "Leads senior school academic planning, coordinates competitive test prep, audits internal marking."},
                {"stage": "Vice-Principal / Principal", "exp": "10+ Years", "desc": "Heads higher secondary school administration, leads faculty recruitment, directs overall institutional vision."}
            ]
        },
        {
            "title": "Vocational & Industrial Skill Trainer",
            "short_name": "Vocational Trainer",
            "slug": "vocational-skill-trainer",
            "category": "Education, Teaching & Academia",
            "sub_category": "Vocational & Technical Training",
            "industry": "Skill Development, ITIs & Industrial Training",
            "icon": "tools",
            "short_description": "Instructs youth in technical vocational trades (welding, CNC machining, electrical, solar) in ITIs and PMKVY centers.",
            "description": "Vocational and Industrial Skill Trainers (Craft Instructors) train youth in practical, hands-on trades—such as Electrician, Fitter, Welder, Machinist, Solar Technician, and Automotive Mechanic. Operating in Industrial Training Institutes (ITIs), National Skill Training Institutes (NSTIs), and PMKVY centers under the Ministry of Skill Development & Entrepreneurship (MSDE), they teach workshop safety, machine operation, and industrial blueprint reading.",
            "what_they_do": "They demonstrate workshop machine operations, teach trade theory and engineering drawing, supervise student shop-floor practicals, enforce safety rules, and conduct All India Trade Tests (AITT).",
            "day_to_day_work": "• Delivering daily workshop practical demonstrations on lathes, milling machines, or wiring benches.\n• Teaching trade theory, engineering mathematics, and industrial blueprint schematics.\n• Inspecting student machined metal jobs using vernier calipers, micrometers, and gauges.\n• Maintaining industrial workshop machinery, tooling consumables, and safety gear.\n• Liaising with local manufacturing industries for student apprenticeship placements.",
            "work_environment": "Industrial Training Institutes (ITIs), National Skill Training Institutes (NSTIs), corporate apprenticeship workshops.",
            "work_modes": "On-site / Workshop / Lab",
            "minimum_qualification": "National Craft Instructor Certificate (NCIC) from NSTI / Polytechnic Diploma / B.Tech in relevant engineering trade",
            "preferred_streams": "Vocational / Engineering (Mechanical, Electrical, Automotive, etc.)",
            "required_subjects": "Trade Theory, Trade Practical, Workshop Calculation, Engineering Drawing",
            "technical_skills": "Workshop Machine Operation, Engineering Blueprint Reading, Precision Metrology, Industrial Safety Protocols, Craft Instructor Pedagogy",
            "soft_skills": "Clear Hands-on Demonstration, Patient Coaching, Uncompromising Safety Vigilance",
            "tools": "Lathe Machines, Milling Cutters, Welding Rigs, Micrometers, Multimeters, Safety Gear",
            "certifications": "Craft Instructor Training Scheme (CITS) Certificate from NSTI (Mandatory for government ITI instructors)",
            "experience_level": "Entry to Senior Principal of ITI",
            "career_growth": "Advance from Craft Instructor to Senior Training Officer, Vice-Principal of ITI, and Principal of Government ITI.",
            "internship_roles": "CITS Practical Teaching Trainee at NSTI",
            "entry_level_roles": "Junior Craft Instructor, Trade Trainer, Workshop Assistant",
            "average_salary": "₹3.5 - ₹8.5 LPA (Indicative range)",
            "salary_indicative": "Private PMKVY Skill Trainer: ₹3.0 - 5.0 LPA | Government ITI Instructor (State Directorate of Training, Pay Level 6-7): ₹5.5 - 8.5 LPA (Basic ₹35,400 + DA + allowances). Indicative figures from Directorate General of Training (DGT).",
            "future_scope": "High national priority under Skill India Mission to skill millions of Indian youth for manufacturing and infrastructure jobs.",
            "government_opportunities": "Directorate General of Training (DGT), National Skill Training Institutes (NSTIs), State Government Industrial Training Institutes (ITIs).",
            "private_opportunities": "Maruti Suzuki Training Academy, L&T Skill Trainers, Tata Motors Skill Centres, PMKVY Partner Training Providers.",
            "higher_study_options": "Advanced Diploma in Vocational Training, B.Voc in Vocational Education.",
            "entrepreneurship_options": "Founding an accredited private vocational skill development center or specialized CNC training lab.",
            "source": "Directorate General of Training (DGT) / MSDE",
            "official_url": "https://dgt.gov.in",
            "verification_status": "VERIFIED",
            "is_lesser_known": False,
            "career_family": "Education & Pedagogy",
            "interest_clusters": "Teaching, Hands-on, Trades, Machines",
            "work_style": "Workshop, School",
            "reality_check": "Hands-on, workshop-based teaching: Spending most of the day in noisy machine shops with metal chips, lubricants, and welding arcs.\nZero safety tolerance: Strict accountability to ensure trainees follow eye protection and machine safety to prevent injuries.\nRequires passing the 1-year Craft Instructor Training Scheme (CITS) at an NSTI for government appointment eligibility.",
            "next_steps": "Complete ITI (National Trade Certificate) + National Apprenticeship Certificate, or a Polytechnic Diploma / B.Tech in engineering.\nAppear for the All India Common Entrance Test (AICET) to enroll in the 1-year CITS program at an NSTI (National Skill Training Institute).\nClear the All India Trade Test for Craft Instructors (AITT CITS) and apply for state ITI instructor posts.",
            "courses": [{"course_id": 64, "type": "PRIMARY"}, {"course_id": 1, "type": "RELATED"}],
            "exams": [],
            "routes": [{"title": "Path A: CITS Craft Instructor Route", "type": "PRIMARY", "steps": "ITI / Diploma -> 1-Yr CITS Training at NSTI -> National Craft Instructor Certificate -> State ITI Instructor Selection."}],
            "ladder": [
                {"stage": "Craft Instructor (Trade Trainer)", "exp": "0-5 Years", "desc": "Conducts workshop practicals, trains batches in trade skills, grades weekly machine jobs."},
                {"stage": "Senior Training Officer (STO)", "exp": "5-10 Years", "desc": "Manages multiple trade workshops, oversees ITI equipment procurement, coordinates campus industrial hiring."},
                {"stage": "Principal of Industrial Training Institute", "exp": "10+ Years", "desc": "Heads entire government or private ITI, leads institutional accreditation, interfaces with state skill ministries."}
            ]
        }
    ]

def get_additional_commerce_and_finance_careers():
    return [
        {
            "title": "Banking Credit Analyst & Commercial Underwriter",
            "short_name": "Credit Analyst",
            "slug": "credit-analyst-underwriter",
            "category": "Finance, Banking & Accounting",
            "sub_category": "Banking & Lending",
            "industry": "Commercial Banking, NBFCs & Credit Rating",
            "icon": "bank",
            "short_description": "Evaluates corporate loan applications, assesses balance sheet solvency, and approves multi-crore business credit.",
            "description": "Banking Credit Analysts and Commercial Underwriters evaluate the financial health and debt repayment capacity of corporate businesses, MSMEs, and commercial real estate developers applying for bank loans. Working in commercial banks, non-banking financial companies (NBFCs), and credit rating agencies (CRISIL, ICRA), they analyze audited financial statements, calculate financial ratios, and make loan underwriting recommendations.",
            "what_they_do": "They analyze balance sheets and cash flow statements, calculate debt service coverage ratios (DSCR), evaluate collateral valuations, write Credit Appraisal Memos (CAM), and conduct promoter background checks.",
            "day_to_day_work": "• Spreading audited corporate balance sheets into financial credit appraisal models.\n• Calculating liquidity ratios, Debt-to-Equity, Interest Coverage, and DSCR metrics.\n• Reviewing credit bureau reports (CIBIL Commercial) and legal property title verification.\n• Drafting detailed Credit Appraisal Memos (CAM) recommending loan sanction or rejection.\n• Monitoring existing loan portfolios for covenant breaches and early warning non-performing signs.",
            "work_environment": "Commercial bank headquarters, corporate credit processing centers, NBFC offices.",
            "work_modes": "Hybrid / Office",
            "minimum_qualification": "Postgraduate (MBA in Finance / Chartered Accountant - CA / M.Com)",
            "preferred_streams": "Commerce / Finance / Economics",
            "required_subjects": "Financial Statement Analysis, Corporate Finance, Banking Law, Ratio Analysis",
            "technical_skills": "Credit Appraisal Memo (CAM) Drafting, Debt Service Coverage Ratio (DSCR), Working Capital Assessment (Tandon/Chore Committee norms), Cash Flow Modeling, Collateral Evaluation, RBI Prudential Lending Norms",
            "soft_skills": "Financial Skepticism, Attention to Nuance, Objective Risk Judgment, Decisiveness",
            "tools": "Microsoft Excel Financial Models, Finacle Core Banking, CIBIL Commercial Portals, MCA-21 Due Diligence",
            "certifications": "Certified Credit Professional (CCP) by Indian Institute of Banking & Finance (IIBF), CA / CFA",
            "experience_level": "Entry Credit Analyst to Chief Credit Officer (CCO)",
            "career_growth": "Advance to Senior Credit Manager, Head of Commercial Underwriting, and Chief Credit Officer (CCO).",
            "internship_roles": "Credit Appraisal Intern, Banking Risk Trainee",
            "entry_level_roles": "Junior Credit Analyst, Commercial Underwriter, Credit Officer",
            "average_salary": "₹5.5 - ₹16.0 LPA (Indicative range)",
            "salary_indicative": "Junior Credit Analyst post-MBA: ₹5.5 - 8 LPA | Senior Commercial Underwriter (3-6 yrs): ₹9 - 15 LPA | Head of Corporate Credit (7+ yrs): ₹18 - 32+ LPA. Indicative figures from commercial banking salary benchmarks.",
            "future_scope": "Essential heart of commercial banking: Sound credit underwriting is the primary safeguard preventing non-performing assets (NPAs).",
            "government_opportunities": "State Bank of India (SBI Specialist Credit Officers), Punjab National Bank, Bank of Baroda, NABARD, SIDBI.",
            "private_opportunities": "HDFC Bank, ICICI Bank, Axis Bank, Kotak Mahindra Bank, Bajaj Finance, CRISIL, ICRA, Tata Capital.",
            "higher_study_options": "Chartered Financial Analyst (CFA USA), Executive Programs in Corporate Credit.",
            "entrepreneurship_options": "Founding an independent corporate debt syndication and financial advisory firm.",
            "source": "Indian Institute of Banking & Finance (IIBF) / Reserve Bank of India",
            "official_url": "https://www.iibf.org.in",
            "verification_status": "VERIFIED",
            "is_lesser_known": False,
            "career_family": "Finance & Accountancy",
            "interest_clusters": "Numbers, Business, Analysis, Government",
            "work_style": "Office",
            "reality_check": "Not sales or client relationship management: Credit analysts have the crucial responsibility to say 'NO' to risky loans despite sales pressure.\nRequires examining complex corporate ledgers, searching for hidden liabilities, promoter related-party transactions, and diversion of funds.\nHigh accountability: Sanctioning bad loans that turn into NPAs leads to severe career and regulatory scrutiny.",
            "next_steps": "Earn a Bachelor's degree in Commerce (B.Com) or Economics/Finance.\nComplete an MBA in Finance or clear Chartered Accountancy (CA) / CFA.\nComplete the Certified Credit Professional (CCP) certification from IIBF and apply for credit analyst roles in banks.",
            "courses": [{"course_id": 28, "type": "PRIMARY"}, {"course_id": 36, "type": "RELATED"}],
            "exams": [{"exam_id": 3, "importance": "RECOMMENDED"}, {"exam_id": 17, "importance": "RECOMMENDED"}],
            "routes": [{"title": "Path A: MBA Finance to Credit Analyst", "type": "PRIMARY", "steps": "B.Com / Any Degree -> MBA Finance -> IIBF Certified Credit Professional -> Bank Credit Officer -> Chief Credit Officer."}],
            "ladder": [
                {"stage": "Credit Analyst / Associate", "exp": "0-3 Years", "desc": "Spreads balance sheets, verifies borrower KYC and bank statements, drafts initial credit memos."},
                {"stage": "Senior Credit Manager / Underwriter", "exp": "3-7 Years", "desc": "Sanctions corporate loans up to delegated financial limits, conducts factory site visits, structures credit covenants."},
                {"stage": "Chief Credit Officer (CCO)", "exp": "7+ Years", "desc": "Oversees bank-wide corporate lending risk, chairs Credit Committee, reports to Board on NPA prevention."}
            ]
        },
        {
            "title": "Corporate Treasury Manager",
            "short_name": "Treasury Manager",
            "slug": "corporate-treasury-manager",
            "category": "Finance, Banking & Accounting",
            "sub_category": "Corporate Finance & Treasury",
            "industry": "Corporate Finance, Forex & Working Capital Management",
            "icon": "cash-stack",
            "short_description": "Manages enterprise cash liquidity, foreign exchange (Forex) currency hedging, and short-term investments.",
            "description": "Corporate Treasury Managers manage the multi-crore cash reserves, foreign currency risks, and short-term capital liquidity of large multinational enterprises and conglomerates. They forecast daily cash inflows and outflows, invest surplus corporate funds in liquid mutual funds and commercial paper, and hedge foreign exchange currency volatility (USD/INR, EUR/INR) using currency forwards and options.",
            "what_they_do": "They manage liquidity cash flows, execute foreign exchange hedging contracts with bank dealing rooms, oversee working capital credit lines, and ensure enterprise interest rate risk management.",
            "day_to_day_work": "• Forecasting daily, weekly, and monthly enterprise global cash liquidity positions.\n• Executing foreign exchange forward contracts and currency options to hedge import/export exposures.\n• Investing surplus cash balances in overnight liquid debt funds and treasury bills.\n• Negotiating interest rate spreads and letter of credit (LC) limits with banking consortiums.\n• Monitoring global interest rate movements (RBI repo rate, US Federal Reserve policy) and commodity prices.",
            "work_environment": "Corporate headquarters finance departments, multinational treasury centers.",
            "work_modes": "Hybrid / Office",
            "minimum_qualification": "Postgraduate (Chartered Accountant - CA / MBA in Finance / CFA)",
            "preferred_streams": "Commerce / Finance / Mathematics / Engineering",
            "required_subjects": "Treasury Management, Financial Derivatives, Forex Markets, Corporate Finance",
            "technical_skills": "Forex Hedging Strategies, Cash Flow Forecasting, Money Market Investments (CP, CD, T-Bills), Interest Rate Swaps, Bloomberg Terminal, Working Capital Management",
            "soft_skills": "Rapid Market Decision-Making, Financial Composure, Tough Negotiation with Banks, High Precision",
            "tools": "Bloomberg Terminal, Refinitiv Eikon, Treasury Management Systems (Kyriba, SAP Treasury), Excel VBA",
            "certifications": "Certified Treasury Professional (CTP), Chartered Financial Analyst (CFA USA), CA",
            "experience_level": "Entry to Head of Treasury / CFO",
            "career_growth": "Advance to Senior Treasury Manager, Head of Global Treasury, and Chief Financial Officer (CFO).",
            "internship_roles": "Treasury Operations Intern, Corporate Finance Trainee",
            "entry_level_roles": "Treasury Analyst, Junior Forex Dealer, Liquidity Management Executive",
            "average_salary": "₹7.5 - ₹22.0+ LPA (Indicative range)",
            "salary_indicative": "Treasury Analyst: ₹7.5 - 11 LPA | Corporate Treasury Manager (4-7 yrs): ₹14 - 22 LPA | Head of Global Treasury of Large Conglomerate: ₹25 - 50+ LPA. Indicative figures from corporate finance recruitment benchmarks.",
            "future_scope": "Critically essential as Indian corporations expand global supply chains, international borrowings, and foreign exports.",
            "government_opportunities": "Reserve Bank of India (Internal Debt Management Department), Treasury Divisions of Maharatna PSUs (ONGC, IOCL, NTPC).",
            "private_opportunities": "Tata Sons, Reliance Industries, Larsen & Toubro, Infosys, Wipro, ITC Limited, Maruti Suzuki, Global In-House Centers (GICs).",
            "higher_study_options": "Chartered Financial Analyst (CFA), Executive Leadership in International Finance.",
            "entrepreneurship_options": "Founding an independent corporate treasury advisory and foreign exchange risk consulting boutique.",
            "source": "Association of Financial Professionals (AFP / CTP) / Reserve Bank of India",
            "official_url": "https://www.rbi.org.in",
            "verification_status": "VERIFIED",
            "is_lesser_known": False,
            "career_family": "Finance & Accountancy",
            "interest_clusters": "Numbers, Business, Analysis, Leadership",
            "work_style": "Office",
            "reality_check": "High financial velocity: A 10-paisa adverse swing in the US Dollar exchange rate can mean a multi-crore loss on unhedged corporate imports.\nRequires monitoring global macroeconomic news, geopolitical conflicts, and central bank interest rate announcements continuously.\nDemands profound understanding of complex financial derivatives (currency swaps, options, forwards).",
            "next_steps": "Earn a Bachelor's degree in Commerce (B.Com) or Economics/Engineering.\nQualify as a Chartered Accountant (CA) or earn an MBA in Finance from a top business school.\nGain practical experience in banking forex dealing rooms or corporate treasury operations.",
            "courses": [{"course_id": 28, "type": "PRIMARY"}, {"course_id": 29, "type": "PRIMARY"}],
            "exams": [],
            "routes": [{"title": "Path A: CA / MBA to Treasury Manager", "type": "PRIMARY", "steps": "B.Com / Any Degree -> CA or MBA Finance -> Treasury Analyst -> Certified Treasury Professional (CTP) -> Head of Treasury."}],
            "ladder": [
                {"stage": "Treasury Analyst / Dealer", "exp": "0-3 Years", "desc": "Calculates daily cash balances, tracks bank account reconciliations, executes routine money market deposits."},
                {"stage": "Corporate Treasury Manager", "exp": "3-8 Years", "desc": "Executes multi-million dollar forex hedging contracts, manages banking consortium credit facilities."},
                {"stage": "Head of Global Treasury / Treasurer", "exp": "8+ Years", "desc": "Directs worldwide enterprise capital structure, advises Board on billion-dollar international bond issuances."}
            ]
        }
    ]

def get_additional_agriculture_and_environment_careers():
    return [
        {
            "title": "Precision Agriculture & Drone Pilot Specialist",
            "short_name": "Agri Drone Specialist",
            "slug": "precision-agri-drone-pilot",
            "category": "Agriculture, Food Technology & Environment",
            "sub_category": "Precision Farming & Agri-Tech",
            "industry": "Agri-Tech, Precision Farming & Drone Technology",
            "icon": "broadcast",
            "short_description": "Operates agricultural spraying drones, analyzes multispectral crop health imagery, and guides precision farming.",
            "description": "Precision Agriculture and Drone Specialists combine drone robotics, multispectral remote sensing, and agronomy to modernize farming. Certified through DGCA Remote Pilot Training Organizations (RPTO), they fly automated agricultural drones to spray micronutrients and bio-pesticides with centimeter precision, analyze NDVI (Normalized Difference Vegetation Index) satellite/drone imagery to detect crop stress before it is visible to human eyes, and guide variable-rate fertilizer application.",
            "what_they_do": "They pilot commercial agricultural drones, program autonomous GPS flight paths, map farm health using multispectral cameras, calculate NDVI vegetation indices, and provide data-driven spraying services.",
            "day_to_day_work": "• Surveying farm boundaries and programming autonomous RTK-GPS flight paths in drone apps.\n• Operating 10-30 liter agricultural spraying drones across paddy, cotton, and sugarcane fields.\n• Stitching multispectral drone aerial photographs in photogrammetry software (Pix4D, WebODM).\n• Generating NDVI crop health maps highlighting nitrogen deficiency and water stress patches.\n• Maintaining drone lithium-polymer (LiPo) battery packs, brushless motors, and spray nozzles.",
            "work_environment": "Farmlands, rural agricultural estates, agri-tech drone hubs, field demonstration sites.",
            "work_modes": "Field / Outdoor / Farm",
            "minimum_qualification": "Class 10 / 12 Pass + DGCA Remote Pilot Certificate (RPC) / B.Sc Agriculture / B.Tech Agricultural Engineering",
            "preferred_streams": "Agriculture / Science / Any Stream with Drone Passion",
            "required_subjects": "Basic Physics, Agriculture, Remote Sensing Basics",
            "technical_skills": "Drone Piloting (DGCA RPC), Multispectral Image Analysis, NDVI Crop Health Mapping, GIS Software (QGIS), Drone Maintenance, Variable Rate Application (VRA)",
            "soft_skills": "Hands-on Technical Troubleshooting, Farmer Communication, Weather Awareness, Focus",
            "tools": "Agricultural Spraying Drones (IoTechWorld, Garuda Aerospace), Multispectral Sensors, Pix4Dfields, QGIS, RTK Base Stations",
            "certifications": "DGCA Remote Pilot Certificate (RPC - Medium Category for Agriculture), Kisan Drone Certification",
            "experience_level": "Entry Drone Pilot to Agri-Tech Fleet Operations Lead",
            "career_growth": "Advance to Senior Precision Agriculture Specialist, Drone Fleet Operations Lead, or Agri-Tech Entrepreneur.",
            "internship_roles": "Drone Flight Apprentice, Precision Agriculture Field Trainee",
            "entry_level_roles": "Agricultural Drone Pilot, Field Imagery Analyst, Agri-Tech Technician",
            "average_salary": "₹3.5 - ₹9.0 LPA (Indicative range)",
            "salary_indicative": "Certified Agricultural Drone Pilot: ₹3.5 - 5.5 LPA | Precision Agriculture Specialist (3-5 yrs): ₹6.0 - 9.5 LPA | Drone Custom Hiring Center Owner / Fleet Lead: ₹10 - 18+ LPA. Indicative figures from Agri-Tech industry surveys.",
            "future_scope": "Explosive growth supported by government subsidies (Kisan Drone Scheme, Sub-Mission on Agricultural Mechanization) targeting precision farming in every Indian district.",
            "government_opportunities": "ICAR Institutes, Krishi Vigyan Kendras (KVKs), State Agriculture Departments, Central Farm Machinery Training and Testing Institute.",
            "private_opportunities": "Garuda Aerospace, IoTechWorld Avigation, DeHaat, CropIn, Syngenta India, Drone Federation of India members, Farmer Producer Organizations (FPOs).",
            "higher_study_options": "Advanced Remote Sensing & GIS Certification (IIRS Dehradun), M.Tech in Agricultural Engineering.",
            "entrepreneurship_options": "Founding a rural Drone Custom Hiring Centre (CHC) offering on-demand spraying and crop health mapping to farmers.",
            "source": "Directorate General of Civil Aviation (DGCA) / Ministry of Agriculture",
            "official_url": "https://digitalsky.dgca.gov.in",
            "verification_status": "VERIFIED",
            "is_lesser_known": True,
            "career_family": "Agriculture & Rural",
            "interest_clusters": "Agriculture, Machines, Technology, Nature, Hands-on",
            "work_style": "Farm, Field, Outdoor",
            "reality_check": "Active outdoor field work: Operating drones from dusty field boundaries in high humidity and summer heat.\nRequires passing the official DGCA Remote Pilot Certificate (RPC) examination from an authorized drone training school.\nHigh-technology green career transforming traditional Indian agriculture through robotics.",
            "next_steps": "Pass Class 10 or 12 with a valid Indian passport.\nEnroll in a 5-day DGCA-approved Remote Pilot Training Organization (RPTO) to earn your Remote Pilot Certificate (RPC).\nGain hands-on flight experience on agricultural multi-rotor spraying drones and learn NDVI multispectral image processing.",
            "courses": [{"course_id": 8, "type": "RELATED"}, {"course_id": 64, "type": "RELATED"}],
            "exams": [],
            "routes": [{"title": "Path A: Kisan Drone Specialist Route", "type": "PRIMARY", "steps": "10th/12th/Agri Degree -> DGCA RPTO Drone Training -> Remote Pilot Certificate (RPC) -> Agri Drone Pilot -> Custom Hiring Center Owner."}],
            "ladder": [
                {"stage": "Certified Agri Drone Pilot", "exp": "0-2 Years", "desc": "Flies automated spraying drones, manages battery charging in fields, conducts routine nozzle cleanups."},
                {"stage": "Precision Agriculture Specialist", "exp": "2-5 Years", "desc": "Processes multispectral drone maps, creates prescription fertilizer zones, advises FPOs on yield optimization."},
                {"stage": "Drone Fleet Operations Lead / Entrepreneur", "exp": "5+ Years", "desc": "Manages a fleet of 50+ spraying drones, runs rural custom hiring centers, secures corporate spraying contracts."}
            ]
        },
        {
            "title": "Hydrologist & Groundwater Resource Specialist",
            "short_name": "Hydrologist",
            "slug": "hydrologist-groundwater-specialist",
            "category": "Agriculture, Food Technology & Environment",
            "sub_category": "Hydrology & Water Resources",
            "industry": "Water Resources, Groundwater Management & Irrigation Engineering",
            "icon": "droplet",
            "short_description": "Studies groundwater aquifers, river basin flows, rainwater harvesting, and prevents water crises.",
            "description": "Hydrologists and Groundwater Resource Specialists study the distribution, circulation, and physical/chemical properties of the Earth's water systems. They monitor underground aquifer water tables, model watershed river basin discharges, design managed aquifer recharge (MAR) rainwater harvesting projects, and formulate drought mitigation policies to secure drinking and irrigation water.",
            "what_they_do": "They conduct hydrogeological aquifer mapping surveys, operate acoustic Doppler river flow meters, model underground water seepage using MODFLOW, evaluate industrial groundwater withdrawal permits, and design artificial recharge structures.",
            "day_to_day_work": "• Measuring piezometric groundwater levels and water salinity in monitoring borewells.\n• Constructing numerical groundwater flow models in MODFLOW or Visual MODFLOW.\n• Calculating watershed water balance (precipitation, evapotranspiration, runoff, recharge).\n• Reviewing Central Ground Water Authority (CGWA) industrial water extraction clearance permits.\n• Designing artificial groundwater recharge structures (check dams, injection wells).",
            "work_environment": "Central Ground Water Board regional directorates, water testing labs, river basin field sites.",
            "work_modes": "Field / Lab / Office",
            "minimum_qualification": "Postgraduate (M.Sc / M.Tech in Hydrogeology / Hydrology / Geology / Water Resource Engineering)",
            "preferred_streams": "Science (Geology, Physics, Chemistry, Mathematics, or Civil Engineering)",
            "required_subjects": "Hydrology, Hydrogeology, Fluid Mechanics, Geology",
            "technical_skills": "Groundwater Modeling (MODFLOW), Hydrogeological Mapping, Pumping Test Analysis (Theis equation), Watershed Management, GIS Hydrological Spatial Analysis, Water Quality Testing",
            "soft_skills": "Analytical Acumen, Field Resilience, Scientific Problem-Solving, Environmental Dedication",
            "tools": "MODFLOW, QGIS / ArcGIS Hydrology Tools, Water Level Indicators, Flow Meters, Spectrophotometers",
            "certifications": "UGC-CSIR NET in Earth Sciences, UPSC Combined Geo-Scientist Examination Selection",
            "experience_level": "Entry to Senior Hydrogeologist",
            "career_growth": "Advance to Senior Hydrogeologist, Regional Director (CGWB), or Chairman of Central Ground Water Board.",
            "internship_roles": "Hydrogeology Intern, Watershed Project Trainee",
            "entry_level_roles": "Junior Hydrogeologist, Water Resource Officer, Hydrological Analyst",
            "average_salary": "₹5.5 - ₹14.0 LPA (Indicative range)",
            "salary_indicative": "Junior Hydrogeologist (UPSC Geo-Scientist, Pay Level 10): ₹56,100 basic + DA + allowances (~₹10 - 13 LPA in hand) | Environmental Water Consultant in Private Sector: ₹6 - 12 LPA | Regional Director / Chief Hydrogeologist: ₹18 - 25+ LPA. Indicative figures from Central Ground Water Board.",
            "future_scope": "Critically essential: Groundwater depletion is India's most urgent environmental crisis, demanding thousands of scientific hydrologists under the Jal Jeevan Mission.",
            "government_opportunities": "Central Ground Water Board (CGWB via UPSC Combined Geo-Scientist Exam), National Institute of Hydrology (NIH Roorkee), Central Water Commission (CWC), State Ground Water Departments.",
            "private_opportunities": "Environmental Engineering consultancies (AECOM, Jacobs, WSP), Mining companies, Water Treatment infrastructure giants (Tata Projects, VA Tech Wabag).",
            "higher_study_options": "Ph.D. in Hydrogeology / Groundwater Modeling, Advanced International Water Fellowships.",
            "entrepreneurship_options": "Establishing an environmental groundwater surveying, rainwater harvesting engineering, and CGWA clearance consultancy.",
            "source": "Central Ground Water Board (CGWB) / UPSC",
            "official_url": "https://cgwb.gov.in",
            "verification_status": "VERIFIED",
            "is_lesser_known": True,
            "career_family": "Ecology & Earth",
            "interest_clusters": "Science, Nature, Environment, Research, Outdoor",
            "work_style": "Field, Lab, Office",
            "reality_check": "Combines extensive outdoor field work (surveying borewells, conducting 24-hour pumping tests in remote villages) with computer simulation.\nGroundwater is hidden beneath the earth: requires high mathematical and geological visualization to map underground aquifer strata.\nVital scientific career saving Indian villages and cities from running out of drinking water.",
            "next_steps": "Earn a Bachelor's degree in Geology, Earth Science, or Civil Engineering.\nPursue M.Sc in Applied Geology / Hydrogeology or M.Tech in Water Resources Engineering.\nPrepare for the UPSC Combined Geo-Scientist Examination (Hydrogeology stream) to join the Central Ground Water Board as a Scientist.",
            "courses": [{"course_id": 13, "type": "PRIMARY"}, {"course_id": 14, "type": "RELATED"}],
            "exams": [{"exam_id": 33, "importance": "PRIMARY"}],
            "routes": [{"title": "Path A: UPSC Geo-Scientist Route", "type": "PRIMARY", "steps": "B.Sc Geology -> M.Sc Applied Geology -> UPSC Combined Geo-Scientist Exam -> Assistant Hydrogeologist (CGWB) -> Regional Director."}],
            "ladder": [
                {"stage": "Assistant Hydrogeologist", "exp": "0-4 Years", "desc": "Conducts field pumping tests, logs borehole lithology, monitors seasonal aquifer water levels."},
                {"stage": "Senior Hydrogeologist / Scientist", "exp": "4-10 Years", "desc": "Builds regional groundwater flow models, designs aquifer recharge schemes, processes industrial extraction clearances."},
                {"stage": "Regional Director / Member (CGWB)", "exp": "10+ Years", "desc": "Heads state-wide groundwater regulation, formulates national water security policy, advises Ministry of Jal Shakti."}
            ]
        }
    ]
