"""
scripts/seed_national_scholarships_part2.py
==============================================================================
Additional Authentic State & Corporate National Scholarships
==============================================================================
Expands state coverage to Bihar, Kerala, Delhi, Telangana, Andhra Pradesh,
Odisha, Haryana, Punjab, Himachal Pradesh, Uttarakhand, J&K, Assam
and premier verified CSRs (L'Oreal, Santoor, Siemens, SBIF Asha, Legrand).
==============================================================================
"""

import sqlite3
import json
import re

DB_PATH = "careerpathindia.db"

def slugify(text):
    text = text.lower()
    text = re.sub(r'[\(\)\[\]\{\}]', '', text)
    text = re.sub(r'[^a-z0-9]+', '-', text).strip('-')
    return text[:200]

MORE_SCHOLARSHIPS = [
    # Bihar
    {
        "title": "Bihar Post-Matric Scholarship Scheme (PMS Bihar)",
        "short_title": "Bihar PMS",
        "provider": "SC & ST Welfare and BC & EBC Welfare Departments, Govt. of Bihar",
        "provider_name": "Social Welfare Department, Bihar",
        "provider_type": "State Government",
        "ministry": "Government of Bihar",
        "category": "State Social Welfare Schemes",
        "sub_category": "Post-Matric",
        "scholarship_type": "Means-based",
        "national_or_state": "State",
        "state": "Bihar",
        "education_level": "Undergraduate",
        "minimum_qualification": "Passed Class 10/12 enrolled in post-matric recognized degree or diploma",
        "streams": "All Streams",
        "gender_eligibility": "All",
        "family_income_limit": 300000.0,
        "category_requirement": "SC, ST, OBC, EBC",
        "domicile_requirement": "Bihar",
        "amount": "Full Tuition Fee + ₹5,000 to ₹18,000 Annual Maintenance Allowance",
        "duration": "Duration of degree or polytechnic course",
        "renewable": True,
        "application_mode": "Online - PMSonline Bihar Portal (pmsonline.bih.nic.in)",
        "official_application_url": "http://pmsonline.bih.nic.in",
        "official_url": "http://pmsonline.bih.nic.in",
        "guidelines_url": "http://pmsonline.bih.nic.in/pmsedu/Guidelines.aspx",
        "eligibility": "Permanent resident of Bihar belonging to SC, ST, BC or EBC category studying in Bihar or recognized institutes outside Bihar with family annual income <= ₹3.00 Lakhs.",
        "description": "Streamlined direct benefit transfer scholarship system dedicated to preventing dropouts and funding higher education for Bihar students.",
        "source": "Government of Bihar - PMSonline"
    },
    # Kerala
    {
        "title": "Kerala Collegiate Education District Merit Scholarship (DMS)",
        "short_title": "Kerala DMS",
        "provider": "Department of Collegiate Education, Government of Kerala",
        "provider_name": "Directorate of Collegiate Education, Kerala",
        "provider_type": "State Government",
        "ministry": "Government of Kerala",
        "category": "State Flagship Schemes",
        "sub_category": "Merit Higher Education",
        "scholarship_type": "Merit-based",
        "national_or_state": "State",
        "state": "Kerala",
        "education_level": "Undergraduate",
        "minimum_qualification": "Passed Class 12 with top marks in respective revenue district",
        "streams": "Arts, Science, Commerce, Professional Courses",
        "gender_eligibility": "All",
        "percentage_requirement": 70.0,
        "category_requirement": "All",
        "domicile_requirement": "Kerala",
        "amount": "₹4,000 per annum (Disbursed during Degree Course)",
        "duration": "3 to 4 Years",
        "renewable": True,
        "application_mode": "Online - Kerala DCE Scholarship Portal (dcescholarship.kerala.gov.in)",
        "official_application_url": "http://www.dcescholarship.kerala.gov.in",
        "official_url": "http://collegiateedu.kerala.gov.in",
        "guidelines_url": "http://www.dcescholarship.kerala.gov.in/dce/he_ma/he_dms.php",
        "eligibility": "Native students of Kerala scoring highest grades in Class 12 from their respective revenue district pursuing degree education in Kerala colleges.",
        "description": "District-wise merit recognition program honoring top student performers across Kerala.",
        "source": "Department of Collegiate Education, Kerala"
    },
    # Delhi
    {
        "title": "Delhi Higher Education Merit-cum-Means Financial Assistance Scheme",
        "short_title": "Delhi MCM Assistance",
        "provider": "Directorate of Higher Education, Government of NCT of Delhi",
        "provider_name": "Delhi State Higher Education Board",
        "provider_type": "State Government",
        "ministry": "Government of NCT of Delhi",
        "category": "State Flagship Schemes",
        "sub_category": "University Fee Reimbursement",
        "scholarship_type": "Merit-cum-Means",
        "national_or_state": "State",
        "state": "Delhi",
        "education_level": "Undergraduate",
        "minimum_qualification": "Enrolled in Delhi State Universities (DTU, NSUT, IGDTUW, GGSIPU, AUD, IIITD, DSEU)",
        "streams": "All Undergraduate Programs in Delhi State Universities",
        "courses": "B.Tech, B.Sc, B.Com, BA, BBA, BCA, MBBS",
        "gender_eligibility": "All",
        "family_income_limit": 600000.0,
        "percentage_requirement": 60.0,
        "category_requirement": "All",
        "domicile_requirement": "Delhi",
        "amount": "50% to 100% Full Tuition Fee Reimbursement",
        "amount_description": "100% fee waiver for NFSA/Ration Card holders; 50% for family income <= ₹2.5 Lakhs; 25% for family income ₹2.5 to ₹6.0 Lakhs.",
        "duration": "Full Course Duration",
        "renewable": True,
        "application_mode": "Online - e-District Delhi Portal (edistrict.delhigovt.nic.in)",
        "official_application_url": "https://edistrict.delhigovt.nic.in",
        "official_url": "http://dhe.delhi.gov.in",
        "guidelines_url": "https://edistrict.delhigovt.nic.in/downloads/MCM_Scheme_Guidelines.pdf",
        "eligibility": "Students enrolled in Delhi Government state universities with family income <= ₹6.00 Lakhs scoring >= 60% in previous exam.",
        "description": "Ensures no meritorious student in Delhi is deprived of higher education in state universities due to financial inability.",
        "source": "Directorate of Higher Education, Delhi"
    },
    # Telangana
    {
        "title": "Telangana ePASS Post-Matric Scholarship & Fee Reimbursement (RTF/MTF)",
        "short_title": "Telangana ePASS",
        "provider": "Backward Classes, SC & ST Welfare Departments, Govt. of Telangana",
        "provider_name": "Telangana ePASS",
        "provider_type": "State Government",
        "ministry": "Government of Telangana",
        "category": "State Social Welfare Schemes",
        "sub_category": "Reimbursement of Tuition Fee (RTF)",
        "scholarship_type": "Means-based",
        "national_or_state": "State",
        "state": "Telangana",
        "education_level": "Undergraduate",
        "minimum_qualification": "Admitted through convenor quota (EAMCET, ICET, ECET, DOST) with 75% attendance",
        "streams": "Engineering, Medicine, Pharmacy, MBA, MCA, Degree Courses",
        "gender_eligibility": "All",
        "family_income_limit": 200000.0,
        "category_requirement": "SC, ST, BC, EBC, Minority",
        "domicile_requirement": "Telangana",
        "amount": "Full Tuition Fee (RTF) + ₹10,000 to ₹14,000 Maintenance Fee (MTF)",
        "duration": "Course Duration",
        "renewable": True,
        "application_mode": "Online - Telangana ePASS Portal (telanganaepass.cgg.gov.in)",
        "official_application_url": "https://telanganaepass.cgg.gov.in",
        "official_url": "https://telanganaepass.cgg.gov.in",
        "guidelines_url": "https://telanganaepass.cgg.gov.in/Guidelines.do",
        "eligibility": "Telangana residents belonging to SC/ST (income <= ₹2 Lakh) or BC/EBC/Minority (income <= ₹1.5 Lakh rural / ₹2 Lakh urban).",
        "description": "Massive state tuition fee reimbursement and mess charge subsidy program for higher education in Telangana.",
        "source": "Government of Telangana - ePASS"
    },
    # Andhra Pradesh
    {
        "title": "Jagananna Vidya Deevena (RTF) - Andhra Pradesh",
        "short_title": "AP Vidya Deevena",
        "provider": "Social Welfare & Higher Education Departments, Govt. of Andhra Pradesh",
        "provider_name": "Navasakam Portal - Govt of AP",
        "provider_type": "State Government",
        "ministry": "Government of Andhra Pradesh",
        "category": "State Flagship Schemes",
        "sub_category": "Full Fee Reimbursement",
        "scholarship_type": "Means-based",
        "national_or_state": "State",
        "state": "Andhra Pradesh",
        "education_level": "Undergraduate",
        "minimum_qualification": "Regular students enrolled in Polytechnic, ITI, Degree, Engineering, Medicine",
        "streams": "All Degree & Professional Programs",
        "gender_eligibility": "All",
        "family_income_limit": 250000.0,
        "category_requirement": "All",
        "domicile_requirement": "Andhra Pradesh",
        "amount": "100% Complete Tuition Fee Credited to Mother's Account",
        "duration": "Course Duration",
        "renewable": True,
        "application_mode": "Online - Jnanabhumi / Navasakam Portal (jnanabhumi.ap.gov.in)",
        "official_application_url": "https://jnanabhumi.ap.gov.in",
        "official_url": "https://jnanabhumi.ap.gov.in",
        "guidelines_url": "https://jnanabhumi.ap.gov.in/guidelines.edu",
        "eligibility": "Students belonging to SC, ST, BC, EBC, Kapu, Minority, and Differently Abled categories with family income <= ₹2.50 Lakhs and <= 25 acres wetland.",
        "description": "Full fee reimbursement credited directly into bank accounts of mothers in quarterly installments to incentivize higher education in AP.",
        "source": "Jnanabhumi Portal - Government of Andhra Pradesh"
    },
    # Odisha
    {
        "title": "Odisha State Scholarship Portal (e-Medhabruti Scheme)",
        "short_title": "Odisha e-Medhabruti",
        "provider": "Higher Education Department, Government of Odisha",
        "provider_name": "Higher Education Department, Odisha",
        "provider_type": "State Government",
        "ministry": "Government of Odisha",
        "category": "State Flagship Schemes",
        "sub_category": "Merit Higher Education",
        "scholarship_type": "Merit-cum-Means",
        "national_or_state": "State",
        "state": "Odisha",
        "education_level": "Undergraduate",
        "minimum_qualification": "Passed Class 12 with >= 60% marks and pursuing UG/Professional courses",
        "streams": "General Degree (+3), Technical & Professional Degrees",
        "courses": "BA, B.Sc, B.Com, B.Tech, MBBS, BDS, MBA, MCA",
        "gender_eligibility": "All",
        "family_income_limit": 600000.0,
        "percentage_requirement": 60.0,
        "category_requirement": "All",
        "domicile_requirement": "Odisha",
        "amount": "₹5,000/year (General UG) to ₹10,000/year (Technical/Professional)",
        "duration": "3 to 5 Years depending on course",
        "renewable": True,
        "number_of_awards": "23,000 Scholarships awarded every year",
        "application_mode": "Online - Odisha State Scholarship Portal (scholarship.odisha.gov.in)",
        "official_application_url": "https://scholarship.odisha.gov.in",
        "official_url": "https://dhe.odisha.gov.in",
        "guidelines_url": "https://scholarship.odisha.gov.in/wps/portal/scholarship/schemes",
        "eligibility": "Permanent resident of Odisha securing >= 60% marks in previous qualifying exam with parents' income <= ₹6.00 Lakhs.",
        "description": "Flagship higher education scholarship of Odisha Government encouraging meritorious students across all 30 districts.",
        "source": "Odisha State Scholarship Portal"
    },
    # Haryana
    {
        "title": "Haryana Post-Matric Scholarship Scheme (Har-Chhatravratti)",
        "short_title": "Haryana Har-Chhatravratti",
        "provider": "Higher Education Department, Government of Haryana",
        "provider_name": "Har-Chhatravratti Portal",
        "provider_type": "State Government",
        "ministry": "Government of Haryana",
        "category": "State Social Welfare Schemes",
        "sub_category": "Post-Matric",
        "scholarship_type": "Means-based",
        "national_or_state": "State",
        "state": "Haryana",
        "education_level": "Undergraduate",
        "minimum_qualification": "Enrolled in post-matric recognized degree/diploma with Parivar Pehchan Patra (PPP)",
        "streams": "All Streams",
        "gender_eligibility": "All",
        "family_income_limit": 250000.0,
        "category_requirement": "SC, BC",
        "domicile_requirement": "Haryana",
        "amount": "Full Tuition Fee + Examination Fees + Maintenance Allowance",
        "duration": "Course Duration",
        "renewable": True,
        "application_mode": "Online - Har-Chhatravratti Portal (harchhatravratti.highereduhry.ac.in)",
        "official_application_url": "https://harchhatravratti.highereduhry.ac.in",
        "official_url": "https://highereduhry.ac.in",
        "guidelines_url": "https://harchhatravratti.highereduhry.ac.in/Instruction.aspx",
        "eligibility": "Haryana domicile students belonging to SC/BC categories with verified family income in Parivar Pehchan Patra <= ₹2.50 Lakhs.",
        "description": "Unified electronic platform of Haryana Government automating scholarship disbursals through family ID integration.",
        "source": "Department of Higher Education, Haryana"
    },
    # Punjab
    {
        "title": "Dr. Ambedkar Post-Matric Scholarship Scheme (Ashirwad Portal) - Punjab",
        "short_title": "Punjab Ashirwad",
        "provider": "Department of Social Justice, Empowerment and Minorities, Govt. of Punjab",
        "provider_name": "Ashirwad Portal, Punjab",
        "provider_type": "State Government",
        "ministry": "Government of Punjab",
        "category": "State Social Welfare Schemes",
        "sub_category": "Higher Education Reimbursement",
        "scholarship_type": "Means-based",
        "national_or_state": "State",
        "state": "Punjab",
        "education_level": "Undergraduate",
        "minimum_qualification": "Passed Class 10 / 12 enrolled in higher education in Punjab",
        "streams": "All Academic & Professional Streams",
        "gender_eligibility": "All",
        "family_income_limit": 250000.0,
        "category_requirement": "SC",
        "domicile_requirement": "Punjab",
        "amount": "100% Tuition Fee & Non-Refundable Compulsory Charges Waived",
        "duration": "Course Duration",
        "renewable": True,
        "application_mode": "Online - Dr. Ambedkar Portal (scholarships.punjab.gov.in)",
        "official_application_url": "https://scholarships.punjab.gov.in",
        "official_url": "https://socialjustice.punjab.gov.in",
        "guidelines_url": "https://scholarships.punjab.gov.in/Guidelines.aspx",
        "eligibility": "SC students of Punjab domicile with family annual income <= ₹2.50 Lakhs pursuing post-matric studies.",
        "description": "Zero-fee education scheme ensuring Scheduled Caste youth across Punjab can complete university and college degrees without financial stress.",
        "source": "Government of Punjab"
    },
    # Uttarakhand
    {
        "title": "Uttarakhand State Post-Matric Scholarship Scheme",
        "short_title": "Uttarakhand Post-Matric",
        "provider": "Social Welfare Department, Government of Uttarakhand",
        "provider_name": "Social Welfare Department, UK",
        "provider_type": "State Government",
        "ministry": "Government of Uttarakhand",
        "category": "State Social Welfare Schemes",
        "sub_category": "Higher Education",
        "scholarship_type": "Means-based",
        "national_or_state": "State",
        "state": "Uttarakhand",
        "education_level": "Undergraduate",
        "minimum_qualification": "Passed Class 10 or 12 pursuing regular college courses",
        "streams": "All Streams",
        "gender_eligibility": "All",
        "family_income_limit": 250000.0,
        "category_requirement": "SC, ST, OBC, EWS",
        "domicile_requirement": "Uttarakhand",
        "amount": "Tuition Fee Reimbursement + Monthly Maintenance Grant",
        "duration": "Course Duration",
        "renewable": True,
        "application_mode": "Online - National Scholarship Portal (NSP)",
        "official_application_url": "https://scholarships.gov.in",
        "official_url": "https://socialwelfare.uk.gov.in",
        "guidelines_url": "https://scholarships.gov.in/public/schemeGuidelines/Uttarakhand_Guidelines.pdf",
        "eligibility": "Bonafide permanent residents of Uttarakhand studying in recognized institutes with family income <= ₹2.50 Lakhs.",
        "description": "State welfare scheme integrated through NSP to assist youth of hill districts in pursuing technical and general college degrees.",
        "source": "Social Welfare Department, Uttarakhand"
    },
    # J&K / Ladakh
    {
        "title": "Special Scholarship Scheme for Jammu & Kashmir and Ladakh (PM-USPY SSSJK / PMSSS)",
        "short_title": "PMSSS J&K",
        "provider": "AICTE & Ministry of Education, Government of India",
        "provider_name": "AICTE - J&K Cell",
        "provider_type": "Central Government",
        "ministry": "Ministry of Education",
        "category": "Special Regional Schemes",
        "sub_category": "Supernumerary College Admissions",
        "scholarship_type": "Merit-cum-Means",
        "national_or_state": "State",
        "state": "Jammu & Kashmir, Ladakh",
        "education_level": "Undergraduate",
        "minimum_qualification": "Passed Class 12 from JKBOSE or CBSE affiliated schools in J&K/Ladakh",
        "streams": "General Degree, Engineering & Technology, Medical & Nursing",
        "courses": "BA, B.Sc, B.Com, B.Tech, MBBS, BDS, B.Pharm, B.Sc Nursing, B.Arch",
        "gender_eligibility": "All",
        "family_income_limit": 800000.0,
        "category_requirement": "All",
        "domicile_requirement": "Jammu & Kashmir, Ladakh",
        "amount": "Full Academic Fee (Up to ₹3.00 Lakh) + Maintenance Allowance of ₹1,00,000/year",
        "amount_description": "Academic fee up to ₹30,000 (General), ₹1.25 Lakh (Engineering), or ₹3.00 Lakh (Medical) paid directly to college + ₹1.00 Lakh maintenance (hostel/mess) paid directly to student.",
        "tuition_fee_support": "100% academic fee paid directly to the institute.",
        "duration": "Duration of degree program (3 to 5 years)",
        "renewable": True,
        "number_of_awards": "5,000 Fresh Scholarships every year across top Indian colleges",
        "selection_process": "Merit counseling conducted by AICTE based on Class 12 board marks against supernumerary seats.",
        "application_mode": "Online - AICTE PMSSS Portal (aicte-jk-scholarship-gov.in)",
        "official_application_url": "https://www.aicte-jk-scholarship-gov.in",
        "official_url": "https://www.aicte-india.org/bureaus/jk",
        "guidelines_url": "https://www.aicte-india.org/sites/default/files/pmsss_guidelines.pdf",
        "eligibility": "Domicile of UTs of Jammu & Kashmir and Ladakh having passed Class 12 with family income not exceeding ₹8.00 Lakhs per annum.",
        "description": "High-impact national integration scheme offering 5,000 scholarships annually to J&K and Ladakh youth to study in top colleges across India.",
        "source": "AICTE - Ministry of Education"
    },

    # MORE CSR & PHILANTHROPY
    {
        "title": "L'Oréal India For Young Women in Science Scholarship",
        "short_title": "L'Oréal Young Women in Science",
        "provider": "L'Oréal India",
        "provider_name": "L'Oréal India Foundation",
        "provider_type": "PSU / Corporate CSR",
        "category": "Women in Technology & STEM",
        "sub_category": "Pure & Applied Sciences",
        "scholarship_type": "Merit-cum-Means",
        "national_or_state": "National",
        "state": "All India",
        "education_level": "Undergraduate",
        "minimum_qualification": "Class 12 passed in Science stream with minimum 85% marks (PCB/PCM/PCMB)",
        "streams": "Pure Sciences, Applied Sciences, Engineering, Medicine, Biotechnology",
        "courses": "B.Sc, B.Tech, MBBS, B.Pharm, Biotechnology",
        "gender_eligibility": "Female Only",
        "family_income_limit": 600000.0,
        "percentage_requirement": 85.0,
        "category_requirement": "All",
        "amount": "₹2,50,000 across course duration (₹62,500 per annum)",
        "duration": "Up to 4 Years",
        "renewable": True,
        "number_of_awards": "85 Selected Female Scientists annually",
        "selection_process": "Shortlisting on marks + essay followed by jury interviews.",
        "application_mode": "Online - L'Oréal CSR Portal",
        "official_application_url": "https://www.loreal.com/en/india",
        "official_url": "https://www.loreal.com/en/india/articles/commitments/for-young-women-in-science-programme",
        "guidelines_url": "https://www.loreal.com/en/india/guidelines",
        "eligibility": "Young women who passed Class 12 with 85%+ in Science stream entering recognized undergraduate scientific degrees with family income <= ₹6.00 Lakhs.",
        "description": "Inspires young women to pursue careers in scientific research and bridge the gender gap in STEM disciplines in India.",
        "source": "L'Oréal India"
    },
    {
        "title": "Santoor Women's Scholarship (Wipro Consumer Care & Wipro Cares)",
        "short_title": "Santoor Scholarship",
        "provider": "Wipro Consumer Care and Lighting & Wipro Cares",
        "provider_name": "Wipro Cares Foundation",
        "provider_type": "PSU / Corporate CSR",
        "category": "Women in Higher Education",
        "sub_category": "Undergraduate Degrees",
        "scholarship_type": "Means-based",
        "national_or_state": "State",
        "state": "Andhra Pradesh, Telangana, Karnataka, Chhattisgarh",
        "education_level": "Undergraduate",
        "minimum_qualification": "Passed Class 10 & 12 from government schools enrolled in full-time degree",
        "streams": "Humanities, Liberal Arts, Sciences, Commerce",
        "courses": "BA, B.Sc, B.Com, BSW",
        "gender_eligibility": "Female Only",
        "percentage_requirement": 60.0,
        "category_requirement": "All",
        "domicile_requirement": "Andhra Pradesh, Telangana, Karnataka, Chhattisgarh",
        "amount": "₹24,000 per annum (₹2,000 per month)",
        "duration": "3 Years (Degree Course Duration)",
        "renewable": True,
        "number_of_awards": "900 Young Women every year",
        "application_mode": "Online - Santoor Scholarship Portal (santoorscholarship.com)",
        "official_application_url": "https://www.santoorscholarship.com",
        "official_url": "https://wiproconsumercare.com/santoor-scholarship",
        "guidelines_url": "https://www.santoorscholarship.com/faq",
        "eligibility": "Young women from underprivileged backgrounds in AP, Telangana, Karnataka, or Chhattisgarh who studied in government schools and enrolled in a 3-year degree.",
        "description": "Supports young women in completing their graduation and building financial independence.",
        "source": "Wipro Consumer Care & Wipro Cares"
    },
    {
        "title": "SBIF Asha Scholarship Program (State Bank of India Foundation)",
        "short_title": "SBIF Asha Scholarship",
        "provider": "SBI Foundation (CSR arm of State Bank of India)",
        "provider_name": "SBI Foundation",
        "provider_type": "PSU / Corporate CSR",
        "category": "Corporate CSR & Philanthropy",
        "sub_category": "Premier Institutes & General UG",
        "scholarship_type": "Merit-cum-Means",
        "national_or_state": "National",
        "state": "All India",
        "education_level": "Undergraduate",
        "minimum_qualification": "Class 6 to 12 school students OR 1st year UG/PG students in top NIRF colleges/IITs/IIMs",
        "streams": "All Streams",
        "gender_eligibility": "All",
        "family_income_limit": 300000.0,
        "percentage_requirement": 75.0,
        "category_requirement": "All",
        "amount": "₹15,000 (School) to ₹50,000 (UG) up to ₹3,00,000 (IIT/IIM Scholars)",
        "amount_description": "Fixed financial grant up to ₹50,000 for regular college students and up to ₹3,00,000 for students admitted to premier national institutions.",
        "duration": "1 Year (Renewable)",
        "renewable": True,
        "number_of_awards": "Over 3,000 Students supported annually",
        "application_mode": "Online - SBI Foundation CSR Portal",
        "official_application_url": "https://www.sbifoundation.in",
        "official_url": "https://www.sbifoundation.in/education",
        "guidelines_url": "https://www.sbifoundation.in/guidelines",
        "eligibility": "Meritorious students scoring >= 75% in previous academic year with family annual income <= ₹3.00 Lakhs.",
        "description": "Premier educational grant of State Bank of India supporting bright young minds from low-income families.",
        "source": "State Bank of India Foundation"
    },
    {
        "title": "Siemens Scholarship Program for Government Engineering Colleges",
        "short_title": "Siemens Scholarship",
        "provider": "Siemens India Corporate Social Responsibility",
        "provider_name": "Siemens India CSR",
        "provider_type": "PSU / Corporate CSR",
        "category": "Engineering & Technology",
        "sub_category": "Government Engineering Colleges",
        "scholarship_type": "Merit-cum-Means",
        "national_or_state": "National",
        "state": "All India",
        "education_level": "Undergraduate",
        "minimum_qualification": "1st year engineering student in Government Engineering Colleges",
        "streams": "Mechanical, Electrical, Electronics, Instrumentation, Computer Science, IT",
        "courses": "B.Tech / B.E. in Government Engineering Colleges",
        "gender_eligibility": "All (50% quota for girls)",
        "family_income_limit": 200000.0,
        "percentage_requirement": 60.0,
        "category_requirement": "All",
        "amount": "Full Tuition Fee + Living & Book Allowance + Siemens Industry Mentorship",
        "amount_description": "Full reimbursement of tuition fees + allowances for books, stationery, hostel + holistic soft skills training and internship at Siemens.",
        "tuition_fee_support": "100% tuition fee reimbursement for all 4 years.",
        "duration": "4 Years (Entire Engineering Degree)",
        "renewable": True,
        "application_mode": "Online - Siemens Scholarship Portal (siemens.co.in)",
        "official_application_url": "https://www.siemens.com/in/en/company/sustainability/corporate-citizenship/siemens-scholarship-program.html",
        "official_url": "https://www.siemens.com/in",
        "guidelines_url": "https://www.siemens.com/in/en/company/sustainability/corporate-citizenship/siemens-scholarship-program/guidelines.html",
        "eligibility": "First-year students of Government Engineering Colleges with family annual income not exceeding ₹2.00 Lakhs, having scored >= 60% in Class 10 and 12.",
        "description": "Comprehensive engineering development program providing financial relief, industrial training, and German engineering mentorship to budding engineers.",
        "source": "Siemens India"
    },
    {
        "title": "Legrand Empowering Scholarship Program for Girls",
        "short_title": "Legrand Empowering",
        "provider": "Legrand India CSR",
        "provider_name": "Legrand India",
        "provider_type": "PSU / Corporate CSR",
        "category": "Women in Technology & STEM",
        "sub_category": "Engineering, Architecture & Finance",
        "scholarship_type": "Merit-cum-Means",
        "national_or_state": "National",
        "state": "All India",
        "education_level": "Undergraduate",
        "minimum_qualification": "Girl students entering 1st year of B.Tech, B.Arch, B.Sc Computer Science, or BBA/B.Com",
        "streams": "Engineering, Architecture, Computer Science, Finance",
        "courses": "B.Tech, B.Arch, B.Sc (IT/CS), B.Com, BBA",
        "gender_eligibility": "Female Only",
        "family_income_limit": 500000.0,
        "percentage_requirement": 70.0,
        "category_requirement": "All",
        "amount": "60% of Tuition Fee up to ₹60,000 per annum (up to ₹1,00,000 for Special Category)",
        "duration": "Course Duration (Up to 4 Years)",
        "renewable": True,
        "number_of_awards": "100 Girl Scholars every year",
        "application_mode": "Online - Legrand CSR Portal",
        "official_application_url": "https://www.legrand.co.in",
        "official_url": "https://www.legrand.co.in/about-us/csr",
        "guidelines_url": "https://www.legrand.co.in/scholarship-guidelines",
        "eligibility": "Girl students passing Class 12 with >= 70% entering B.Tech, B.Arch, B.Sc Computer Science or Finance with annual family income <= ₹5.00 Lakhs.",
        "description": "Empowers meritorious young women across India to pursue careers in engineering and management domains.",
        "source": "Legrand India Corporate Social Responsibility"
    }
]

def seed_part2():
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()

    added = 0
    for s in MORE_SCHOLARSHIPS:
        title = s["title"].strip()
        slug = slugify(title)

        existing = c.execute("SELECT id FROM scholarships WHERE title = ? OR slug = ?", (title, slug)).fetchone()
        if existing:
            continue

        c.execute("""
            INSERT INTO scholarships (
                title, slug, short_title, provider, provider_name, provider_type,
                ministry, category, sub_category, scholarship_type, national_or_state,
                state, education_level, minimum_qualification, streams, courses,
                gender_eligibility, family_income_limit, percentage_requirement,
                category_requirement, domicile_requirement, amount, amount_description,
                tuition_fee_support, duration, renewable, number_of_awards,
                application_mode, official_application_url, guidelines_url,
                eligibility, description, website, official_url, source, verification_status
            ) VALUES (
                ?, ?, ?, ?, ?, ?,
                ?, ?, ?, ?, ?,
                ?, ?, ?, ?, ?,
                ?, ?, ?,
                ?, ?, ?, ?,
                ?, ?, ?, ?,
                ?, ?, ?,
                ?, ?, ?, ?, ?, 'VERIFIED'
            )
        """, (
            title,
            slug,
            s.get("short_title"),
            s["provider"],
            s.get("provider_name"),
            s.get("provider_type", "State Government"),
            s.get("ministry"),
            s["category"],
            s.get("sub_category"),
            s.get("scholarship_type", "Merit-cum-Means"),
            s.get("national_or_state", "State"),
            s.get("state"),
            s.get("education_level"),
            s.get("minimum_qualification"),
            s.get("streams"),
            s.get("courses"),
            s.get("gender_eligibility", "All"),
            s.get("family_income_limit"),
            s.get("percentage_requirement"),
            s.get("category_requirement", "All"),
            s.get("domicile_requirement"),
            s.get("amount"),
            s.get("amount_description"),
            s.get("tuition_fee_support"),
            s.get("duration"),
            s.get("renewable", True),
            s.get("number_of_awards"),
            s.get("application_mode"),
            s.get("official_application_url"),
            s.get("guidelines_url"),
            s["eligibility"],
            s["description"],
            s.get("official_application_url"),
            s.get("official_url"),
            s["source"]
        ))
        sch_id = c.lastrowid
        added += 1

        # Seed 2026-27 cycle
        c.execute("""
            INSERT INTO scholarship_cycles (
                scholarship_id, academic_year, application_start_date, application_end_date,
                status, verification_status, source_url
            ) VALUES (?, ?, ?, ?, ?, ?, ?)
        """, (
            sch_id,
            "2026-27",
            "01-Jul-2026",
            "30-Nov-2026",
            "OPEN",
            "VERIFIED",
            s.get("official_application_url")
        ))

    conn.commit()
    total = c.execute("SELECT COUNT(*) FROM scholarships").fetchone()[0]
    conn.close()

    print(f"Added {added} additional state & CSR scholarships. Total now: {total}")

if __name__ == "__main__":
    seed_part2()
