"""
scripts/seed_national_scholarships.py
==============================================================================
MPath National Scholarship Platform - Real & Traceable Dataset Seeder
==============================================================================
Populates authentic national scholarship records across:
- Central Government Ministries (MoE, MSJE, MoTA, MoMA, MHA, MoD, Railways)
- Statutory Bodies (UGC, AICTE, DST, ICAR)
- State Government Flagship Portals (MP, UP, Rajasthan, MH, KA, TN, WB, etc.)
- Top Corporate CSR / Philanthropic Foundations (Tata, Reliance, Infosys, HDFC, ONGC)
- International Fellowships for Indian Citizens (Commonwealth, Fulbright, Chevening)
==============================================================================
"""

import sqlite3
import json
import re
from datetime import datetime

DB_PATH = "careerpathindia.db"

def slugify(text):
    text = text.lower()
    text = re.sub(r'[\(\)\[\]\{\}]', '', text)
    text = re.sub(r'[^a-z0-9]+', '-', text).strip('-')
    return text[:200]

# Complete Catalog of Authentic National & State Scholarships
SCHOLARSHIPS_DATA = [
    # =========================================================================
    # A. CENTRAL GOVERNMENT (MoE, MSJE, MoTA, MoMA, DEPwD, MHA, Railways, MoD)
    # =========================================================================
    {
        "title": "Central Sector Scheme of Scholarship for College and University Students (PM-USP CSSS)",
        "short_title": "PM-USP CSSS",
        "provider": "Department of Higher Education, Ministry of Education, Govt. of India",
        "provider_name": "Department of Higher Education (DoHE)",
        "provider_type": "Central Government",
        "ministry": "Ministry of Education",
        "department": "Department of Higher Education",
        "category": "Merit-cum-Means",
        "sub_category": "Higher Education",
        "scholarship_type": "Merit-cum-Means",
        "national_or_state": "National",
        "state": "All India",
        "education_level": "Undergraduate",
        "minimum_qualification": "Class 12 Pass (Top 20th Percentile of respective Board)",
        "streams": "Science, Commerce, Humanities, Engineering, Medical",
        "courses": "All Regular UG Degrees (B.Sc, B.Tech, MBBS, B.Com, BA, BCA)",
        "gender_eligibility": "All",
        "family_income_limit": 450000.0,
        "percentage_requirement": 80.0,
        "academic_requirement": "Above 80th percentile of successful candidates in the relevant stream from respective State/Central Education Board in Class 12.",
        "category_requirement": "All",
        "disability_requirement": "None",
        "amount": "₹12,000 to ₹20,000 per annum",
        "amount_description": "₹12,000 per annum at Graduation level for first 3 years, and ₹20,000 per annum at Post-Graduation level.",
        "tuition_fee_support": "Direct financial assistance disbursed directly to student Aadhaar-linked bank account (DBT).",
        "duration": "Up to 5 Years (Graduation + Post-Graduation)",
        "renewable": True,
        "number_of_awards": "82,000 Fresh Scholarships per year (50% reserved for girls)",
        "selection_process": "Strict merit quota allocated across State Education Boards based on 18-25 population proportion.",
        "application_mode": "Online - National Scholarship Portal (NSP)",
        "official_application_url": "https://scholarships.gov.in",
        "official_url": "https://www.education.gov.in/higher_education",
        "guidelines_url": "https://scholarships.gov.in/public/schemeGuidelines/CSSS_Guidelines.pdf",
        "requires_otr": True,
        "requires_institute_verification": True,
        "requires_nodal_verification": True,
        "eligibility": "Class 12 passed regular students scoring above 80th percentile in relevant board stream, pursuing regular full-time degree in recognized college/university. Gross family income <= ₹4.50 Lakhs per annum.",
        "description": "Prestigious central scholarship scheme to provide financial assistance to meritorious students from economically weaker sections to meet day-to-day college expenses while pursuing higher studies.",
        "source": "Ministry of Education - National Scholarship Portal",
        "documents_required": json.dumps([
            "Class 12 Marksheet & Passing Certificate",
            "Aadhaar Card with linked active bank account",
            "Valid Family Income Certificate issued by Revenue Authority",
            "College Bonafide Student Certificate / Admission Fee Receipt",
            "Current Year College ID Card"
        ]),
        "common_mistakes": json.dumps([
            "Selecting wrong State Education Board in OTR registration.",
            "Bank account not being Aadhaar-seeded for Direct Benefit Transfer (DBT).",
            "Failure by college nodal officer to verify application before State cutoff date."
        ]),
        "faqs": json.dumps([
            {"q": "Can students pursuing distance or private degrees apply?", "a": "No, only regular full-time students enrolled in UGC/AICTE recognized institutions are eligible."},
            {"q": "Is renewal dependent on college performance?", "a": "Yes, minimum 50% marks in semester examinations and 75% attendance are required for annual renewal."}
        ])
    },
    {
        "title": "National Means-cum-Merit Scholarship Scheme (NMMSS)",
        "short_title": "NMMSS",
        "provider": "Department of School Education and Literacy, Ministry of Education",
        "provider_name": "Department of School Education & Literacy",
        "provider_type": "Central Government",
        "ministry": "Ministry of Education",
        "category": "Means-based",
        "sub_category": "Secondary Education",
        "scholarship_type": "Means-based",
        "national_or_state": "National",
        "state": "All India",
        "education_level": "Class 9-10",
        "minimum_qualification": "Class 7 & 8 passed from State Government / Local Body / Aided School",
        "streams": "General Schooling",
        "gender_eligibility": "All",
        "family_income_limit": 350000.0,
        "percentage_requirement": 55.0,
        "academic_requirement": "Minimum 55% marks in Class 7 and Class 8 (50% for SC/ST candidates) and clearing state-level MAT and SAT selection exam.",
        "category_requirement": "All",
        "amount": "₹12,000 per annum (₹1,000 per month)",
        "amount_description": "₹12,000 per annum disbursed quarterly to student bank account via Public Financial Management System (PFMS).",
        "duration": "4 Years (Class 9 to Class 12)",
        "renewable": True,
        "number_of_awards": "1,00,000 Fresh Scholarships every year",
        "selection_process": "State-level competitive examination comprising Mental Ability Test (MAT) and Scholastic Aptitude Test (SAT).",
        "application_mode": "Online - National Scholarship Portal (NSP)",
        "official_application_url": "https://scholarships.gov.in",
        "official_url": "https://dsel.education.gov.in",
        "guidelines_url": "https://scholarships.gov.in/public/schemeGuidelines/NMMSS_Guidelines.pdf",
        "requires_otr": True,
        "requires_institute_verification": True,
        "eligibility": "Studying as regular student in Class 9 in a Government, Local Body or Government-aided school. Parent annual income <= ₹3,50,000.",
        "description": "Awarded to meritorious students of economically weaker sections to arrest dropouts at Class 8 and encourage continuation of study through secondary stage.",
        "source": "National Scholarship Portal - Ministry of Education"
    },
    {
        "title": "Top Class Education Scheme for SC Students",
        "short_title": "Top Class SC",
        "provider": "Ministry of Social Justice and Empowerment, Govt. of India",
        "provider_name": "Ministry of Social Justice & Empowerment",
        "provider_type": "Central Government",
        "ministry": "Ministry of Social Justice and Empowerment",
        "category": "Social Justice & SC Welfare",
        "sub_category": "Premier Institutes",
        "scholarship_type": "Merit-based",
        "national_or_state": "National",
        "state": "All India",
        "education_level": "Undergraduate",
        "minimum_qualification": "Admission secured in notified Premier Institutions (IITs, IIMs, NITs, AIIMS, NLUs, etc.)",
        "streams": "Engineering, Medicine, Management, Law, Architecture",
        "courses": "B.Tech, MBBS, MBA, BA LLB, B.Arch, MD",
        "gender_eligibility": "All",
        "family_income_limit": 800000.0,
        "percentage_requirement": 50.0,
        "category_requirement": "SC",
        "amount": "Full Tuition Fee + ₹86,000 Annual Living & Device Allowance",
        "amount_description": "Full non-refundable tuition fees up to ₹2.00 Lakh (Private) or actual (Govt) + Living expenses ₹3,000/month + Books ₹5,000/year + One-time computer ₹45,000.",
        "tuition_fee_support": "Full tuition fee and non-refundable institutional charges covered directly.",
        "duration": "Entire duration of the degree course",
        "renewable": True,
        "number_of_awards": "4,100 Fresh Slots annually across 260+ premier institutions",
        "selection_process": "Merit based on entrance examination ranking (JEE Adv, NEET, CLAT, CAT) secured for admission to notified institutions.",
        "application_mode": "Online - National Scholarship Portal (NSP)",
        "official_application_url": "https://scholarships.gov.in",
        "official_url": "https://socialjustice.gov.in",
        "guidelines_url": "https://socialjustice.gov.in/writereaddata/UploadFile/Top_Class_SC.pdf",
        "requires_otr": True,
        "requires_institute_verification": True,
        "eligibility": "Belonging to Scheduled Caste (SC) community with total family annual income not exceeding ₹8.00 Lakhs, having gained admission to recognized premier institutions.",
        "description": "Recognizes and promotes quality education among SC students by fully financing their education at notified premier institutions across India.",
        "source": "Ministry of Social Justice and Empowerment"
    },
    {
        "title": "National Fellowship and Scholarship for Higher Education of ST Students",
        "short_title": "NFST Higher Education",
        "provider": "Ministry of Tribal Affairs, Govt. of India",
        "provider_name": "Ministry of Tribal Affairs",
        "provider_type": "Central Government",
        "ministry": "Ministry of Tribal Affairs",
        "category": "Tribal Welfare & ST Schemes",
        "sub_category": "Higher Education & Fellowships",
        "scholarship_type": "Merit-cum-Means",
        "national_or_state": "National",
        "state": "All India",
        "education_level": "Undergraduate",
        "minimum_qualification": "Admission to notified Top-Class Institutions or M.Phil/Ph.D enrollment",
        "streams": "Engineering, Medicine, Management, Law, Pure Sciences",
        "gender_eligibility": "All",
        "family_income_limit": 600000.0,
        "percentage_requirement": 50.0,
        "category_requirement": "ST",
        "amount": "Full Tuition Fee + Living Allowance of ₹36,000/year",
        "amount_description": "Full tuition fees + living allowance ₹3,000/month + books & stationery ₹5,000/year + computer assistance ₹45,000 one-time.",
        "duration": "Course Duration (Up to 5 Years)",
        "renewable": True,
        "number_of_awards": "1,000 Fresh Scholarships + 750 Fellowships annually",
        "application_mode": "Online - National Scholarship Portal (NSP)",
        "official_application_url": "https://scholarships.gov.in",
        "official_url": "https://tribal.nic.in",
        "guidelines_url": "https://tribal.nic.in/downloads/Scholarship/SchemeGuidelines.pdf",
        "requires_otr": True,
        "requires_institute_verification": True,
        "eligibility": "Scheduled Tribe (ST) students securing admission to notified institutes of national importance or pursuing M.Phil/Ph.D. Family income <= ₹6.00 Lakhs/annum.",
        "description": "Flagship scheme of Ministry of Tribal Affairs empowering ST youth to pursue graduate, post-graduate, and doctoral research in premier institutions.",
        "source": "Ministry of Tribal Affairs"
    },
    {
        "title": "PM-YASASVI Post-Matric Scholarship for OBC, EBC and DNT",
        "short_title": "PM-YASASVI",
        "provider": "Ministry of Social Justice and Empowerment, Govt. of India",
        "provider_name": "Department of Social Justice and Empowerment",
        "provider_type": "Central Government",
        "ministry": "Ministry of Social Justice and Empowerment",
        "category": "Social Justice & OBC Welfare",
        "sub_category": "Post-Matric",
        "scholarship_type": "Means-based",
        "national_or_state": "National",
        "state": "All India",
        "education_level": "Undergraduate",
        "minimum_qualification": "Class 10 or Class 12 Pass pursuing post-matriculation courses",
        "streams": "All Streams",
        "gender_eligibility": "All",
        "family_income_limit": 250000.0,
        "category_requirement": "OBC, EWS",
        "amount": "₹5,000 to ₹20,000 per annum + Academic Allowances",
        "amount_description": "Maintenance allowance ranging from ₹5,000 to ₹20,000 based on course group (Group 1: Medicine/Engg to Group 4: General BA/BSc).",
        "duration": "Duration of degree / diploma course",
        "renewable": True,
        "application_mode": "Online - National Scholarship Portal (NSP)",
        "official_application_url": "https://scholarships.gov.in",
        "official_url": "https://socialjustice.gov.in",
        "guidelines_url": "https://socialjustice.gov.in/writereaddata/UploadFile/PM_YASASVI.pdf",
        "requires_otr": True,
        "requires_institute_verification": True,
        "eligibility": "OBC, Economically Backward Class (EBC) and De-notified, Nomadic Tribes (DNT) candidates with parental income <= ₹2.50 Lakhs per annum.",
        "description": "Comprehensive umbrella scheme for education and socio-economic empowerment of other backward classes and nomadic tribes.",
        "source": "Ministry of Social Justice & Empowerment"
    },
    {
        "title": "Post-Matric Scholarship for Students with Disabilities",
        "short_title": "DEPwD Post-Matric",
        "provider": "Department of Empowerment of Persons with Disabilities, MSJE",
        "provider_name": "Department of Empowerment of Persons with Disabilities",
        "provider_type": "Central Government",
        "ministry": "Ministry of Social Justice and Empowerment",
        "category": "Disability & Inclusion",
        "sub_category": "Higher Education",
        "scholarship_type": "Special / Disability",
        "national_or_state": "National",
        "state": "All India",
        "education_level": "Undergraduate",
        "minimum_qualification": "Matriculation / Class 10 passed with recognized disability",
        "streams": "All Streams",
        "gender_eligibility": "All",
        "family_income_limit": 250000.0,
        "category_requirement": "All",
        "disability_requirement": "Mandatory",
        "amount": "₹4,000 to ₹12,000 per annum + Disability Aids Allowance",
        "amount_description": "Maintenance allowance + book grant + disability allowances (Reader allowance, escort allowance, helper allowance).",
        "duration": "Course Duration",
        "renewable": True,
        "number_of_awards": "17,000 Slots annually",
        "application_mode": "Online - National Scholarship Portal (NSP)",
        "official_application_url": "https://scholarships.gov.in",
        "official_url": "https://disabilityaffairs.gov.in",
        "guidelines_url": "https://scholarships.gov.in/public/schemeGuidelines/Disability_Guidelines.pdf",
        "requires_otr": True,
        "requires_institute_verification": True,
        "eligibility": "Students with 40% or more benchmark disability certified by Competent Medical Authority (UDID Card holders prioritized) with annual family income <= ₹2.50 Lakhs.",
        "description": "Supports higher education among students with disabilities to ensure barrier-free access to post-matric education and vocational tracks.",
        "source": "DEPwD, Government of India"
    },
    {
        "title": "Prime Minister's Scholarship Scheme for Central Armed Police Forces & Assam Rifles (WARB PMSS)",
        "short_title": "WARB PMSS",
        "provider": "Welfare and Rehabilitation Board (WARB), Ministry of Home Affairs",
        "provider_name": "Welfare & Rehabilitation Board (WARB)",
        "provider_type": "Central Government",
        "ministry": "Ministry of Home Affairs",
        "category": "Defense & Security Personnel",
        "sub_category": "Professional Education",
        "scholarship_type": "Merit-based",
        "national_or_state": "National",
        "state": "All India",
        "education_level": "Undergraduate",
        "minimum_qualification": "Class 12 Pass (Minimum 60% marks)",
        "streams": "Engineering, Medicine, Dental, Veterinary, Pharmacy, Nursing, MBA, MCA",
        "courses": "B.Tech, MBBS, BDS, B.Pharm, B.Sc Nursing, MCA, MBA",
        "gender_eligibility": "All",
        "percentage_requirement": 60.0,
        "category_requirement": "All",
        "amount": "₹3,000/month for Girls, ₹2,500/month for Boys (₹30,000 - ₹36,000/year)",
        "amount_description": "₹36,000 per year for female students and ₹30,000 per year for male students paid annually.",
        "duration": "1 to 5 Years depending on professional course duration",
        "renewable": True,
        "number_of_awards": "2,000 Fresh Scholarships (Equal quota for girls & boys)",
        "selection_process": "Priority order: Wards of personnel killed in action -> disabled -> gallantry awardees -> ex-CAPF.",
        "application_mode": "Online - National Scholarship Portal (NSP)",
        "official_application_url": "https://scholarships.gov.in",
        "official_url": "https://warb-mha.gov.in",
        "guidelines_url": "https://scholarships.gov.in/public/schemeGuidelines/WARB_PMSS_Guidelines.pdf",
        "requires_otr": True,
        "requires_institute_verification": True,
        "eligibility": "Dependent wards and widows of deceased or retired Central Armed Police Forces (CRPF, BSF, CISF, ITBP, SSB, Assam Rifles). Min 60% in Class 12.",
        "description": "Encourages higher technical and professional education for dependent wards and widows of Central Armed Police Forces and Assam Rifles personnel.",
        "source": "Ministry of Home Affairs - WARB"
    },
    {
        "title": "Prime Minister's Scholarship Scheme for Wards of Ex-Servicemen (KSB PMSS)",
        "short_title": "KSB PMSS",
        "provider": "Kendriya Sainik Board, Department of Ex-Servicemen Welfare, Ministry of Defence",
        "provider_name": "Kendriya Sainik Board Secretariat",
        "provider_type": "Central Government",
        "ministry": "Ministry of Defence",
        "category": "Defense & Security Personnel",
        "sub_category": "Professional Education",
        "scholarship_type": "Merit-based",
        "national_or_state": "National",
        "state": "All India",
        "education_level": "Undergraduate",
        "minimum_qualification": "Class 12 / Diploma / Graduation with minimum 60% marks",
        "streams": "Engineering, Medicine, Dental, Architecture, Agriculture, Management",
        "gender_eligibility": "All",
        "percentage_requirement": 60.0,
        "category_requirement": "All",
        "amount": "₹3,000/month for Girls, ₹2,500/month for Boys",
        "amount_description": "₹36,000 per year for girls and ₹30,000 per year for boys.",
        "duration": "Full professional degree duration (2 to 5 years)",
        "renewable": True,
        "number_of_awards": "5,500 Fresh Scholarships every year",
        "selection_process": "Strict priority category matrix defined by Ministry of Defence.",
        "application_mode": "Online - KSB Portal (ksb.gov.in)",
        "official_application_url": "https://ksb.gov.in",
        "official_url": "https://desw.gov.in",
        "guidelines_url": "https://ksb.gov.in/guidelines-pmss.htm",
        "eligibility": "Wards and widows of Ex-Servicemen / Ex-Coast Guard personnel pursuing first professional degree recognized by regulatory bodies (AICTE, NMC, UGC).",
        "description": "Established under National Defence Fund to promote higher technical education for wards of ex-servicemen of Indian Army, Navy, Air Force and Coast Guard.",
        "source": "Department of Ex-Servicemen Welfare - Ministry of Defence"
    },
    {
        "title": "Prime Minister's Scholarship Scheme for Ministry of Railways (RPF/RPSF)",
        "short_title": "RPF PMSS",
        "provider": "Security Directorate, Railway Board, Ministry of Railways",
        "provider_name": "Ministry of Railways (Railway Board)",
        "provider_type": "Central Government",
        "ministry": "Ministry of Railways",
        "category": "Defense & Security Personnel",
        "sub_category": "Railway Personnel Wards",
        "scholarship_type": "Merit-based",
        "national_or_state": "National",
        "state": "All India",
        "education_level": "Undergraduate",
        "minimum_qualification": "Class 12 Pass (60% minimum marks)",
        "streams": "Professional Technical Courses (Engineering, Medical, Dental, MCA, MBA)",
        "gender_eligibility": "All",
        "percentage_requirement": 60.0,
        "amount": "₹2,250 to ₹2,500 per month",
        "amount_description": "₹30,000/year for male students and ₹36,000/year for female students.",
        "duration": "Course Duration",
        "renewable": True,
        "number_of_awards": "150 Slots annually",
        "application_mode": "Online - National Scholarship Portal (NSP)",
        "official_application_url": "https://scholarships.gov.in",
        "official_url": "https://indianrailways.gov.in",
        "guidelines_url": "https://scholarships.gov.in/public/schemeGuidelines/RPF_Guidelines.pdf",
        "requires_otr": True,
        "requires_institute_verification": True,
        "eligibility": "Dependent wards of serving and retired RPF/RPSF personnel pursuing regular technical degrees.",
        "description": "Dedicated financial grant for professional education of children of Railway Protection Force personnel.",
        "source": "Ministry of Railways"
    },

    # =========================================================================
    # B. AICTE SCHOLARSHIPS (Pragati, Saksham, Swanath)
    # =========================================================================
    {
        "title": "AICTE Pragati Scholarship Scheme for Girl Students (Degree & Diploma)",
        "short_title": "AICTE Pragati",
        "provider": "All India Council for Technical Education (AICTE)",
        "provider_name": "AICTE - Ministry of Education",
        "provider_type": "UGC / AICTE",
        "ministry": "Ministry of Education",
        "category": "Women in Technology & STEM",
        "sub_category": "Engineering & Technology",
        "scholarship_type": "Merit-cum-Means",
        "national_or_state": "National",
        "state": "All India",
        "education_level": "Undergraduate",
        "minimum_qualification": "1st year Degree/Diploma or Lateral Entry (2nd year) in AICTE approved institution",
        "streams": "Engineering, Technology, Architecture, Pharmacy, Hotel Management",
        "courses": "B.Tech, B.E., B.Arch, B.Pharm, Polytechnic Diploma",
        "gender_eligibility": "Female Only",
        "family_income_limit": 800000.0,
        "percentage_requirement": 50.0,
        "category_requirement": "All",
        "amount": "₹50,000 per annum",
        "amount_description": "₹50,000 per year towards payment of college tuition fees, purchase of computers, stationery, books, equipment, and exam fees.",
        "tuition_fee_support": "Lump sum grant of ₹50,000 per year directly to girl student's account.",
        "duration": "Maximum 4 Years for Degree (3 Years for Lateral Entry) / 3 Years for Diploma",
        "renewable": True,
        "number_of_awards": "10,000 Scholarships per annum (plus all eligible girls from 23 special states/UTs)",
        "selection_process": "Merit list based on qualifying Class 12 / 10th marks for admission to AICTE approved institution.",
        "application_mode": "Online - National Scholarship Portal (NSP)",
        "official_application_url": "https://scholarships.gov.in",
        "official_url": "https://www.aicte-india.org/schemes/students-development-schemes/Pragati",
        "guidelines_url": "https://www.aicte-india.org/sites/default/files/pragati_degree_guidelines.pdf",
        "requires_otr": True,
        "requires_institute_verification": True,
        "eligibility": "Female candidate admitted to 1st year degree/diploma course in an AICTE approved college. Maximum two girls per family. Family income <= ₹8.00 Lakhs per annum.",
        "description": "Empowers young women to pursue technical education, breaking financial hurdles in engineering and applied technologies across India.",
        "source": "AICTE - National Scholarship Portal"
    },
    {
        "title": "AICTE Saksham Scholarship Scheme for Specially-Abled Students",
        "short_title": "AICTE Saksham",
        "provider": "All India Council for Technical Education (AICTE)",
        "provider_name": "AICTE - Ministry of Education",
        "provider_type": "UGC / AICTE",
        "ministry": "Ministry of Education",
        "category": "Disability & Inclusion",
        "sub_category": "Engineering & Technology",
        "scholarship_type": "Special / Disability",
        "national_or_state": "National",
        "state": "All India",
        "education_level": "Undergraduate",
        "minimum_qualification": "1st year Degree/Diploma student in AICTE approved college with >= 40% disability",
        "streams": "Engineering, Technology, Architecture, Pharmacy, Management",
        "gender_eligibility": "All",
        "family_income_limit": 800000.0,
        "category_requirement": "All",
        "disability_requirement": "Mandatory",
        "amount": "₹50,000 per annum",
        "amount_description": "₹50,000 per year towards tuition fees, specialized assistive devices, software, books and study equipment.",
        "duration": "Duration of degree or diploma course",
        "renewable": True,
        "number_of_awards": "All eligible specially-abled candidates are awarded",
        "application_mode": "Online - National Scholarship Portal (NSP)",
        "official_application_url": "https://scholarships.gov.in",
        "official_url": "https://www.aicte-india.org/schemes/students-development-schemes/Saksham",
        "guidelines_url": "https://www.aicte-india.org/sites/default/files/saksham_guidelines.pdf",
        "requires_otr": True,
        "requires_institute_verification": True,
        "eligibility": "Specially-abled students having disability not less than 40% admitted to 1st year of technical degree/diploma in AICTE institution. Family income <= ₹8.00 Lakhs.",
        "description": "Aimed at encouraging and supporting specially-abled children to pursue technical education with dignity and necessary assistive tools.",
        "source": "AICTE - National Scholarship Portal"
    },
    {
        "title": "AICTE Swanath Scholarship Scheme",
        "short_title": "AICTE Swanath",
        "provider": "All India Council for Technical Education (AICTE)",
        "provider_name": "AICTE - Ministry of Education",
        "provider_type": "UGC / AICTE",
        "ministry": "Ministry of Education",
        "category": "Special / Vulnerable Youth",
        "sub_category": "Orphans & Armed Forces Wards",
        "scholarship_type": "Means-based",
        "national_or_state": "National",
        "state": "All India",
        "education_level": "Undergraduate",
        "minimum_qualification": "1st to 4th year regular student in AICTE approved institution",
        "streams": "Technical Degree & Diploma Programs",
        "gender_eligibility": "All",
        "family_income_limit": 800000.0,
        "category_requirement": "All",
        "amount": "₹50,000 per annum",
        "amount_description": "₹50,000 every year for each year of study.",
        "duration": "Entire duration of program",
        "renewable": True,
        "number_of_awards": "2,000 Scholarships every year (1,000 Degree + 1,000 Diploma)",
        "application_mode": "Online - National Scholarship Portal (NSP)",
        "official_application_url": "https://scholarships.gov.in",
        "official_url": "https://www.aicte-india.org/schemes/students-development-schemes/Swanath",
        "guidelines_url": "https://www.aicte-india.org/sites/default/files/swanath_guidelines.pdf",
        "requires_otr": True,
        "requires_institute_verification": True,
        "eligibility": "Orphaned students, children whose both parents died due to Covid-19, or wards of Armed Forces and Central Paramilitary Personnel martyred in action. Family income <= ₹8.00 Lakhs.",
        "description": "Supports orphaned and martyred personnel's children to continue technical education without interruption.",
        "source": "AICTE - Ministry of Education"
    },

    # =========================================================================
    # C. UGC SCHOLARSHIPS (Single Girl Child, Rank Holders, Ishan Uday)
    # =========================================================================
    {
        "title": "Post-Graduate Indira Gandhi Scholarship for Single Girl Child",
        "short_title": "UGC Single Girl Child",
        "provider": "University Grants Commission (UGC)",
        "provider_name": "University Grants Commission",
        "provider_type": "UGC / AICTE",
        "ministry": "Ministry of Education",
        "category": "Postgraduate & Gender Equity",
        "sub_category": "Master's Degrees",
        "scholarship_type": "Single Girl Child",
        "national_or_state": "National",
        "state": "All India",
        "education_level": "Postgraduate",
        "minimum_qualification": "Enrolled in 1st year of regular Master's program in recognized University",
        "streams": "Non-Professional PG Courses (MA, M.Sc, M.Com)",
        "gender_eligibility": "Female Only",
        "age_max": 30,
        "category_requirement": "All",
        "amount": "₹36,200 per annum (₹3,100 per month for 20 months)",
        "amount_description": "₹3,100 per month for a period of two years (10 months per year).",
        "duration": "2 Years (Duration of Master's program)",
        "renewable": True,
        "number_of_awards": "3,000 Fresh Scholarships every year",
        "selection_process": "Strict verification of single girl child affidavit before Executive Magistrate.",
        "application_mode": "Online - National Scholarship Portal (NSP)",
        "official_application_url": "https://scholarships.gov.in",
        "official_url": "https://www.ugc.gov.in",
        "guidelines_url": "https://scholarships.gov.in/public/schemeGuidelines/UGC_SingleGirlChild_Guidelines.pdf",
        "requires_otr": True,
        "requires_institute_verification": True,
        "eligibility": "Girl student who is the only child of her parents (twin/fraternal daughters also eligible) admitted to first year of regular PG degree. Age limit: 30 years.",
        "description": "Established to compensate for the direct costs of higher education especially for girls through single child families and promote higher studies.",
        "source": "University Grants Commission - UGC"
    },
    {
        "title": "Post Graduate Merit Scholarship for University Rank Holders",
        "short_title": "UGC Rank Holders",
        "provider": "University Grants Commission (UGC)",
        "provider_name": "University Grants Commission",
        "provider_type": "UGC / AICTE",
        "ministry": "Ministry of Education",
        "category": "Academic Merit & University Excellence",
        "sub_category": "Postgraduate",
        "scholarship_type": "Merit-based",
        "national_or_state": "National",
        "state": "All India",
        "education_level": "Postgraduate",
        "minimum_qualification": "1st or 2nd Rank in Bachelor's Degree in University examination",
        "streams": "Basic Sciences, Life Sciences, Physical Sciences, Chemical Sciences, Earth Sciences, Social Sciences, Languages, Commerce",
        "gender_eligibility": "All",
        "age_max": 30,
        "percentage_requirement": 60.0,
        "category_requirement": "All",
        "amount": "₹3,100 per month (₹37,200 per annum)",
        "duration": "2 Years (PG Course Duration)",
        "renewable": True,
        "number_of_awards": "3,100 Slots per year",
        "application_mode": "Online - National Scholarship Portal (NSP)",
        "official_application_url": "https://scholarships.gov.in",
        "official_url": "https://www.ugc.gov.in",
        "guidelines_url": "https://scholarships.gov.in/public/schemeGuidelines/UGC_RankHolders_Guidelines.pdf",
        "requires_otr": True,
        "requires_institute_verification": True,
        "eligibility": "Holders of 1st and 2nd rank at undergraduate university level in non-professional streams admitted into regular post-graduate programs.",
        "description": "Promotes academic brilliance and rewards university top rank holders pursuing post-graduate education.",
        "source": "University Grants Commission"
    },
    {
        "title": "Ishan Uday Special Scholarship Scheme for North Eastern Region",
        "short_title": "Ishan Uday NER",
        "provider": "University Grants Commission (UGC) & Ministry of Education",
        "provider_name": "UGC - NER Division",
        "provider_type": "UGC / AICTE",
        "ministry": "Ministry of Education",
        "category": "Regional Equity & North East India",
        "sub_category": "General & Professional Degrees",
        "scholarship_type": "Merit-cum-Means",
        "national_or_state": "State",
        "state": "Assam, Meghalaya, Manipur, Mizoram, Nagaland, Tripura, Arunachal Pradesh, Sikkim",
        "education_level": "Undergraduate",
        "minimum_qualification": "Class 12 pass with domicile of North Eastern States",
        "streams": "General Degree (Arts, Humanities, Science, Commerce) and Technical/Professional Degrees",
        "gender_eligibility": "All",
        "family_income_limit": 450000.0,
        "category_requirement": "All",
        "domicile_requirement": "Assam, Meghalaya, Manipur, Mizoram, Nagaland, Tripura, Arunachal Pradesh, Sikkim",
        "amount": "₹5,400/month (General) to ₹7,800/month (Technical/Medical) for 10 months/year",
        "amount_description": "₹54,000 per annum for general degree courses and ₹78,000 per annum for technical, medical and professional courses.",
        "duration": "Duration of Undergraduate course (3 to 5 years)",
        "renewable": True,
        "number_of_awards": "10,000 Fresh Scholarships annually",
        "application_mode": "Online - National Scholarship Portal (NSP)",
        "official_application_url": "https://scholarships.gov.in",
        "official_url": "https://www.ugc.gov.in",
        "guidelines_url": "https://scholarships.gov.in/public/schemeGuidelines/Ishan_Uday_Guidelines.pdf",
        "requires_otr": True,
        "requires_institute_verification": True,
        "eligibility": "Permanent residents of North Eastern Region having passed Class 12 and admitted to 1st year of any regular degree program. Family income <= ₹4.50 Lakhs/annum.",
        "description": "Special initiative of UGC to improve gross enrollment ratio and provide equal higher education opportunities for youth of North Eastern states.",
        "source": "UGC - Ministry of Education"
    },

    # =========================================================================
    # D. SCIENCE & AGRICULTURE (DST INSPIRE, ICAR NTS)
    # =========================================================================
    {
        "title": "INSPIRE Scholarship for Higher Education (SHE)",
        "short_title": "DST INSPIRE-SHE",
        "provider": "Department of Science and Technology (DST), Govt. of India",
        "provider_name": "Department of Science and Technology",
        "provider_type": "Central Government",
        "ministry": "Ministry of Science and Technology",
        "category": "Basic & Natural Sciences Research",
        "sub_category": "Pure Sciences",
        "scholarship_type": "Merit-based",
        "national_or_state": "National",
        "state": "All India",
        "education_level": "Undergraduate",
        "minimum_qualification": "Class 12 Pass (Top 1% of respective Class 12 Board or top ranks in JEE/NEET/KVPY)",
        "streams": "Natural and Basic Sciences (Physics, Chemistry, Mathematics, Biology, Statistics, Geology, Astrophysics)",
        "courses": "B.Sc, B.Sc (Hons), Integrated M.Sc, MS",
        "gender_eligibility": "All",
        "age_min": 17,
        "age_max": 22,
        "percentage_requirement": 85.0,
        "academic_requirement": "Top 1% in Class 12 board examination OR top 10,000 ranks in JEE Main/Advanced or NEET pursuing basic sciences.",
        "category_requirement": "All",
        "amount": "₹80,000 per annum (₹60,000 scholarship + ₹20,000 summer mentorship project grant)",
        "amount_description": "₹5,000 per month (₹60,000 per annum) deposited directly + ₹20,000 mentorship project grant for active research internship.",
        "duration": "Up to 5 Years (B.Sc + M.Sc / Integrated M.Sc)",
        "renewable": True,
        "number_of_awards": "10,000 Scholarships every year",
        "selection_process": "Strict board top 1% cutoff scores announced annually by DST across all 32 school examination boards.",
        "application_mode": "Online - INSPIRE Portal (online-inspire.gov.in)",
        "official_application_url": "https://online-inspire.gov.in",
        "official_url": "https://dst.gov.in",
        "guidelines_url": "https://online-inspire.gov.in/Content/Guideline_SHE.pdf",
        "eligibility": "Students within top 1% of their respective Class 12 board enrolled in natural/basic sciences degrees at recognized colleges, IISERs, NISER, IITs, universities.",
        "description": "Flagship program of Government of India to inspire creative youth to study basic and natural sciences at university level and embark on research careers.",
        "source": "Department of Science and Technology (DST)"
    },
    {
        "title": "ICAR National Talent Scholarship (UG & PG)",
        "short_title": "ICAR NTS",
        "provider": "Indian Council of Agricultural Research (ICAR)",
        "provider_name": "Indian Council of Agricultural Research",
        "provider_type": "Central Government",
        "ministry": "Ministry of Agriculture and Farmers Welfare",
        "category": "Agriculture & Allied Sciences",
        "sub_category": "Agricultural Universities",
        "scholarship_type": "Merit-based",
        "national_or_state": "National",
        "state": "All India",
        "education_level": "Undergraduate",
        "minimum_qualification": "Admitted through ICAR AIEEA to an Agricultural University outside home state",
        "streams": "Agriculture, Horticulture, Forestry, Fisheries, Dairy Technology, Agricultural Engineering",
        "courses": "B.Sc (Hons) Agriculture, B.Tech Agricultural Engg, B.F.Sc, B.V.Sc",
        "gender_eligibility": "All",
        "category_requirement": "All",
        "amount": "₹3,000/month for UG (₹36,000/year); ₹5,000/month for PG (₹60,000/year)",
        "duration": "Course Duration (4 Years for UG, 2 Years for PG)",
        "renewable": True,
        "selection_process": "Rank secured in ICAR All India Entrance Examination for Admission (AIEEA).",
        "application_mode": "Online - ICAR Portal / Agricultural University",
        "official_application_url": "https://icar.org.in",
        "official_url": "https://icar.org.in",
        "guidelines_url": "https://icar.org.in/guidelines-nts",
        "eligibility": "Admitted into accredited State Agricultural University (SAU), Central Agricultural University (CAU) or ICAR Institute located outside domicile state.",
        "description": "Encourages national integration and high academic standards in agricultural sciences by supporting students studying outside their home states.",
        "source": "Indian Council of Agricultural Research"
    },

    # =========================================================================
    # E. STATE GOVERNMENT SCHOLARSHIPS (MP, UP, Rajasthan, Maharashtra, etc.)
    # =========================================================================
    {
        "title": "Mukhyamantri Medhavi Vidyarthi Yojana (MMVY) - Madhya Pradesh",
        "short_title": "MP MMVY",
        "provider": "Department of Technical Education & Skill Development, Govt. of Madhya Pradesh",
        "provider_name": "Department of Technical Education, MP",
        "provider_type": "State Government",
        "ministry": "Government of Madhya Pradesh",
        "category": "State Flagship Schemes",
        "sub_category": "Higher Education Fee Waiver",
        "scholarship_type": "Merit-cum-Means",
        "national_or_state": "State",
        "state": "Madhya Pradesh",
        "education_level": "Undergraduate",
        "minimum_qualification": "Class 12 passed with >= 70% (MP Board) or >= 85% (CBSE/ICSE)",
        "streams": "Engineering, Medical, Law, Management, Poly, Degree Courses",
        "courses": "B.Tech (JEE rank <= 1.5 Lakh), MBBS (NEET rank in govt/pvt), CLAT (NLUs), B.Sc, B.Com, BA",
        "gender_eligibility": "All",
        "family_income_limit": 600000.0,
        "percentage_requirement": 70.0,
        "category_requirement": "All",
        "domicile_requirement": "Madhya Pradesh",
        "amount": "Full Tuition Fee Reimbursed (Up to 100% of Academic Fees)",
        "amount_description": "Complete tuition fee and institutional fee reimbursement paid directly to institution by MP Government.",
        "tuition_fee_support": "100% tuition fee reimbursement in both Government and recognized Private institutions.",
        "duration": "Full Course Duration",
        "renewable": True,
        "application_mode": "Online - MP State Scholarship Portal (scholarshipportal.mp.nic.in)",
        "official_application_url": "http://scholarshipportal.mp.nic.in/MedhaviChhatra/Default.aspx",
        "official_url": "http://scholarshipportal.mp.nic.in",
        "guidelines_url": "http://scholarshipportal.mp.nic.in/MedhaviChhatra/Public/Rules.aspx",
        "eligibility": "Permanent resident of Madhya Pradesh scoring >= 70% in MP Board or >= 85% in CBSE/ICSE in Class 12 with parental annual income <= ₹6.00 Lakhs.",
        "description": "Landmark welfare program of Madhya Pradesh Government bearing complete educational fees of meritorious students admitted to engineering, medical, law, and degree colleges.",
        "source": "State Scholarship Portal 2.0 - Government of Madhya Pradesh"
    },
    {
        "title": "Post Matric Scholarship Scheme for SC/ST/OBC - Madhya Pradesh (MP Taas)",
        "short_title": "MP Taas Post-Matric",
        "provider": "Tribal Affairs & Scheduled Caste Welfare Department, Govt. of Madhya Pradesh",
        "provider_name": "MP Tribal Affairs Automation System (MPTAAS)",
        "provider_type": "State Government",
        "ministry": "Government of Madhya Pradesh",
        "category": "State Social Welfare Schemes",
        "sub_category": "Post-Matric",
        "scholarship_type": "Means-based",
        "national_or_state": "State",
        "state": "Madhya Pradesh",
        "education_level": "Undergraduate",
        "minimum_qualification": "Class 10 / 12 passed enrolled in post-matric recognized degree or diploma",
        "streams": "All Streams",
        "gender_eligibility": "All",
        "family_income_limit": 300000.0,
        "category_requirement": "SC, ST, OBC",
        "domicile_requirement": "Madhya Pradesh",
        "amount": "Full Tuition Fee + ₹5,000 to ₹15,000 Annual Maintenance Allowance",
        "duration": "Duration of degree or polytechnic course",
        "renewable": True,
        "application_mode": "Online - MPTAAS Portal (tribal.mp.gov.in/mptaas)",
        "official_application_url": "https://www.tribal.mp.gov.in/mptaas",
        "official_url": "https://www.tribal.mp.gov.in",
        "guidelines_url": "https://www.tribal.mp.gov.in/mptaas/Public/Rules.aspx",
        "eligibility": "Native residents of MP belonging to SC, ST or OBC categories with valid Digital Samagra ID, Caste Certificate, and Income Certificate under ₹3 Lakhs.",
        "description": "Integrated automated scholarship portal ensuring transparent delivery of tuition reimbursements and living allowances to backward community students in MP.",
        "source": "MPTAAS - Government of Madhya Pradesh"
    },
    {
        "title": "Gaon Ki Beti Yojana - Madhya Pradesh",
        "short_title": "MP Gaon Ki Beti",
        "provider": "Higher Education Department, Government of Madhya Pradesh",
        "provider_name": "Higher Education Department, MP",
        "provider_type": "State Government",
        "ministry": "Government of Madhya Pradesh",
        "category": "Rural Girl Child Education",
        "sub_category": "Undergraduate Degrees",
        "scholarship_type": "Merit-based",
        "national_or_state": "State",
        "state": "Madhya Pradesh",
        "education_level": "Undergraduate",
        "minimum_qualification": "Class 12 passed in 1st division (>= 60%) from a rural school in MP",
        "streams": "Arts, Science, Commerce, Engineering, Medical",
        "gender_eligibility": "Female Only",
        "percentage_requirement": 60.0,
        "category_requirement": "All",
        "domicile_requirement": "Madhya Pradesh",
        "amount": "₹500 per month for 10 months (₹5,000 per year) / ₹7,500 for Medical/Engg",
        "duration": "Entire duration of graduation degree (3 to 4 years)",
        "renewable": True,
        "application_mode": "Online - State Scholarship Portal 2.0 (scholarshipportal.mp.nic.in)",
        "official_application_url": "http://scholarshipportal.mp.nic.in",
        "official_url": "http://highereducation.mp.gov.in",
        "guidelines_url": "http://scholarshipportal.mp.nic.in/Public/Rules/GaonKiBeti_Rules.pdf",
        "eligibility": "Rural girl students residing in villages of Madhya Pradesh who passed Class 12 with 60%+ marks from village schools and entered college.",
        "description": "Incentivizes rural girls across MP villages to enter university education and reduce female dropout rates after Class 12.",
        "source": "Department of Higher Education, MP"
    },
    {
        "title": "Uttar Pradesh Post-Matric Scholarship Scheme (UP Scholarship - SAKSHAM)",
        "short_title": "UP Post-Matric SAKSHAM",
        "provider": "Social Welfare Department, Government of Uttar Pradesh",
        "provider_name": "Social Welfare Department, UP",
        "provider_type": "State Government",
        "ministry": "Government of Uttar Pradesh",
        "category": "State Social Welfare Schemes",
        "sub_category": "Higher Education Reimbursement",
        "scholarship_type": "Means-based",
        "national_or_state": "State",
        "state": "Uttar Pradesh",
        "education_level": "Undergraduate",
        "minimum_qualification": "Passed Class 12 or graduation enrolled in recognized UP institute",
        "streams": "All Academic & Technical Streams",
        "gender_eligibility": "All",
        "family_income_limit": 250000.0,
        "category_requirement": "General, SC, ST, OBC, Minority",
        "domicile_requirement": "Uttar Pradesh",
        "amount": "Full Fee Reimbursement + Annual Living Allowance (₹6,000 to ₹30,000)",
        "duration": "Course Duration",
        "renewable": True,
        "application_mode": "Online - UP Scholarship Portal (scholarship.up.gov.in)",
        "official_application_url": "https://scholarship.up.gov.in",
        "official_url": "https://scholarship.up.gov.in",
        "guidelines_url": "https://scholarship.up.gov.in/GeneralInstruction.aspx",
        "eligibility": "Domicile of Uttar Pradesh pursuing post-matric courses with annual family income up to ₹2.00 Lakhs (General/OBC/Minority) or ₹2.50 Lakhs (SC/ST).",
        "description": "Massive state educational welfare scheme covering university tuition fees and hostel allowances for lakhs of college students in Uttar Pradesh.",
        "source": "Government of Uttar Pradesh - SAKSHAM"
    },
    {
        "title": "Mukhyamantri Sarvajan Uchcha Shiksha Chhatravritti Yojana - Rajasthan",
        "short_title": "Rajasthan Sarvajan",
        "provider": "College Education Department, Government of Rajasthan",
        "provider_name": "Department of College Education, Rajasthan",
        "provider_type": "State Government",
        "ministry": "Government of Rajasthan",
        "category": "State Flagship Schemes",
        "sub_category": "Higher Education",
        "scholarship_type": "Merit-cum-Means",
        "national_or_state": "State",
        "state": "Rajasthan",
        "education_level": "Undergraduate",
        "minimum_qualification": "Passed Class 12 with >= 60% marks and in top merit of RBSE",
        "streams": "Arts, Science, Commerce, Technical Degrees",
        "gender_eligibility": "All",
        "family_income_limit": 250000.0,
        "percentage_requirement": 60.0,
        "category_requirement": "All",
        "domicile_requirement": "Rajasthan",
        "amount": "₹5,000 per annum (₹10,000 for students with disabilities)",
        "duration": "Duration of Undergraduate course (Up to 3-5 Years)",
        "renewable": True,
        "number_of_awards": "Over 1,00,000 Students supported annually",
        "application_mode": "Online - SSO Rajasthan (sso.rajasthan.gov.in)",
        "official_application_url": "https://sso.rajasthan.gov.in",
        "official_url": "https://hte.rajasthan.gov.in",
        "guidelines_url": "https://hte.rajasthan.gov.in/dept/dce/scholarship_guidelines.pdf",
        "eligibility": "Bonafide resident of Rajasthan scoring >= 60% in Class 12 from RBSE board with family income <= ₹2.50 Lakhs per annum.",
        "description": "Provides financial cushion to low-income meritorious students across Rajasthan pursuing regular undergraduate university programs.",
        "source": "Higher & Technical Education Department, Rajasthan"
    },
    {
        "title": "Rajarshi Chhatrapati Shahu Maharaj Shikshan Shulkh Shishyavrutti Yojna (EBC) - Maharashtra",
        "short_title": "MahaDBT Shahu Maharaj",
        "provider": "Directorate of Higher Education / DTE, Govt. of Maharashtra",
        "provider_name": "MahaDBT - Government of Maharashtra",
        "provider_type": "State Government",
        "ministry": "Government of Maharashtra",
        "category": "State Social Welfare Schemes",
        "sub_category": "Technical & Higher Education",
        "scholarship_type": "Means-based",
        "national_or_state": "State",
        "state": "Maharashtra",
        "education_level": "Undergraduate",
        "minimum_qualification": "Admitted through CAP rounds in recognized university or technical institute",
        "streams": "Engineering, Medicine, Agriculture, Pharmacy, Architecture, Law, General Degree",
        "courses": "B.Tech, MBBS, B.Sc, B.Com, BA, MBA, MCA",
        "gender_eligibility": "All",
        "family_income_limit": 800000.0,
        "percentage_requirement": 50.0,
        "category_requirement": "General, EWS, OBC, SEBC",
        "domicile_requirement": "Maharashtra",
        "amount": "50% to 100% Tuition Fee & Exam Fee Waiver",
        "amount_description": "50% tuition and examination fee waiver for students with income <= ₹8.00 Lakhs; up to 100% for government colleges.",
        "tuition_fee_support": "50% of the approved course fee directly reimbursed to college.",
        "duration": "Course Duration",
        "renewable": True,
        "application_mode": "Online - MahaDBT Portal (mahadbt.maharashtra.gov.in)",
        "official_application_url": "https://mahadbt.maharashtra.gov.in",
        "official_url": "https://mahadbt.maharashtra.gov.in",
        "guidelines_url": "https://mahadbt.maharashtra.gov.in/SchemeData/SchemeData?str=EBC_Guidelines",
        "eligibility": "Domicile of Maharashtra admitted through Centralized Admission Process (CAP) with family income <= ₹8.00 Lakhs.",
        "description": "Flagship higher education reimbursement scheme of Maharashtra Government benefiting lakhs of students across engineering, medical, and general degrees.",
        "source": "MahaDBT - Government of Maharashtra"
    },
    {
        "title": "Swami Vivekananda Merit-cum-Means Scholarship (SVMCM) - West Bengal",
        "short_title": "WB SVMCM",
        "provider": "Higher Education Department, Government of West Bengal",
        "provider_name": "Higher Education Department, WB",
        "provider_type": "State Government",
        "ministry": "Government of West Bengal",
        "category": "State Flagship Schemes",
        "sub_category": "Higher Education & Professional",
        "scholarship_type": "Merit-cum-Means",
        "national_or_state": "State",
        "state": "West Bengal",
        "education_level": "Undergraduate",
        "minimum_qualification": "Passed Class 12 with >= 60% marks in WB Council or recognized boards",
        "streams": "Undergraduate Arts, Science, Commerce, Engineering, Medical, Diploma",
        "gender_eligibility": "All",
        "family_income_limit": 250000.0,
        "percentage_requirement": 60.0,
        "category_requirement": "All",
        "domicile_requirement": "West Bengal",
        "amount": "₹1,000 to ₹5,000 per month (₹12,000 to ₹60,000 per annum)",
        "amount_description": "UG General: ₹1,000/month; UG Professional/Engg: ₹1,500/month; Medical MBBS: ₹5,000/month.",
        "duration": "Entire duration of the degree course",
        "renewable": True,
        "application_mode": "Online - SVMCM Portal (svmcm.wbhed.gov.in)",
        "official_application_url": "https://svmcm.wbhed.gov.in",
        "official_url": "https://wbhed.gov.in",
        "guidelines_url": "https://svmcm.wbhed.gov.in/page/guidelines.php",
        "eligibility": "Resident of West Bengal pursuing higher education in the state after scoring >= 60% in Class 12 or graduation. Family income <= ₹2.50 Lakhs/annum.",
        "description": "Premier scholarship scheme in West Bengal supporting students pursuing higher secondary, undergraduate, postgraduate, and doctoral studies.",
        "source": "Government of West Bengal - Higher Education Department"
    },
    {
        "title": "State Scholarship Portal (SSP) Post-Matric Scheme - Karnataka",
        "short_title": "Karnataka SSP",
        "provider": "Social Welfare & Backward Classes Departments, Govt. of Karnataka",
        "provider_name": "Center for e-Governance, Karnataka",
        "provider_type": "State Government",
        "ministry": "Government of Karnataka",
        "category": "State Social Welfare Schemes",
        "sub_category": "Fee Reimbursement & Maintenance",
        "scholarship_type": "Means-based",
        "national_or_state": "State",
        "state": "Karnataka",
        "education_level": "Undergraduate",
        "minimum_qualification": "Admitted to post-matric degree/diploma course in Karnataka",
        "streams": "All Streams",
        "gender_eligibility": "All",
        "family_income_limit": 250000.0,
        "category_requirement": "SC, ST, OBC, EWS, Minority",
        "domicile_requirement": "Karnataka",
        "amount": "Course Fee Reimbursement + Hostel & Living Grant",
        "duration": "Course Duration",
        "renewable": True,
        "application_mode": "Online - Karnataka SSP (ssp.postmatric.karnataka.gov.in)",
        "official_application_url": "https://ssp.postmatric.karnataka.gov.in",
        "official_url": "https://ssp.karnataka.gov.in",
        "guidelines_url": "https://ssp.postmatric.karnataka.gov.in/docs/UserManual.pdf",
        "eligibility": "Karnataka domicile students with Kutumba ID and Caste/Income certificate verified via automated electronic database.",
        "description": "Single unified direct benefit transfer portal for post-matric scholarships across SC, ST, Backward Classes and Minority departments in Karnataka.",
        "source": "State Scholarship Portal - Government of Karnataka"
    },
    {
        "title": "Moovalur Ramamirtham Ammaiyar Higher Education Assurance Scheme (Pudhumai Penn) - Tamil Nadu",
        "short_title": "TN Pudhumai Penn",
        "provider": "Social Welfare & Women Empowerment Department, Govt. of Tamil Nadu",
        "provider_name": "Social Welfare Department, TN",
        "provider_type": "State Government",
        "ministry": "Government of Tamil Nadu",
        "category": "Women in Higher Education",
        "sub_category": "Direct Cash Assistance",
        "scholarship_type": "Merit-based",
        "national_or_state": "State",
        "state": "Tamil Nadu",
        "education_level": "Undergraduate",
        "minimum_qualification": "Studied from Class 6 to 12 in Government Schools of Tamil Nadu",
        "streams": "Arts, Science, Commerce, Engineering, Medical, Paramedical, Law, Diploma",
        "gender_eligibility": "Female Only",
        "category_requirement": "All",
        "domicile_requirement": "Tamil Nadu",
        "amount": "₹1,000 per month (₹12,000 per annum)",
        "amount_description": "₹1,000 per month directly deposited to girl student's bank account every month until completion of degree.",
        "duration": "3 to 5 Years (Entire degree course)",
        "renewable": True,
        "number_of_awards": "Over 3,50,000 Girl Students currently enrolled",
        "application_mode": "Online - Penkalvi Portal (pudhumaipenn.tn.gov.in)",
        "official_application_url": "https://pudhumaipenn.tn.gov.in",
        "official_url": "https://www.tn.gov.in",
        "guidelines_url": "https://pudhumaipenn.tn.gov.in/guidelines",
        "eligibility": "Girl students who studied in Tamil Nadu Government schools from Class 6 to Class 12 and enrolled in regular undergraduate degree or diploma courses.",
        "description": "Revolutionary welfare initiative in Tamil Nadu providing ₹1,000 monthly cash assistance to prevent female dropout and enable financial independence during college.",
        "source": "Government of Tamil Nadu"
    },
    {
        "title": "Mukhyamantri Yuva Swavalamban Yojana (MYSY) - Gujarat",
        "short_title": "Gujarat MYSY",
        "provider": "Education Department, Government of Gujarat",
        "provider_name": "Knowledge Consortium of Gujarat (KCG)",
        "provider_type": "State Government",
        "ministry": "Government of Gujarat",
        "category": "State Flagship Schemes",
        "sub_category": "Higher & Professional Education",
        "scholarship_type": "Merit-cum-Means",
        "national_or_state": "State",
        "state": "Gujarat",
        "education_level": "Undergraduate",
        "minimum_qualification": "Class 12 passed with >= 80 percentile or Diploma with >= 65%",
        "streams": "Medical (MBBS/BDS), Engineering, Pharmacy, Architecture, General Degree",
        "courses": "MBBS, B.Tech, B.Pharm, B.Sc, B.Com, BA",
        "gender_eligibility": "All",
        "family_income_limit": 600000.0,
        "percentage_requirement": 80.0,
        "category_requirement": "All",
        "domicile_requirement": "Gujarat",
        "amount": "50% Tuition Fee up to ₹2,00,000/year (Medical) or ₹50,000/year (Engg) + ₹12,000 Hostel",
        "duration": "Course Duration",
        "renewable": True,
        "application_mode": "Online - MYSY Portal (mysy.guj.nic.in)",
        "official_application_url": "https://mysy.guj.nic.in",
        "official_url": "https://mysy.guj.nic.in",
        "guidelines_url": "https://mysy.guj.nic.in/pdf/MYSY_Resolution.pdf",
        "eligibility": "Gujarat residents scoring >= 80 percentile in Class 12 entering degree courses with annual family income up to ₹6.00 Lakhs.",
        "description": "Comprehensive scholarship scheme helping bright youth across Gujarat afford fees for medical, engineering, and graduation education.",
        "source": "Government of Gujarat - Education Department"
    },

    # =========================================================================
    # F. TOP CORPORATE CSR & PHILANTHROPIC FOUNDATIONS
    # =========================================================================
    {
        "title": "Tata Trusts Means-cum-Merit Scholarship for Higher Education",
        "short_title": "Tata Trusts Scholarship",
        "provider": "Sir Ratan Tata Trust & Allied Trusts",
        "provider_name": "Tata Trusts",
        "provider_type": "Philanthropic Trust / NGO",
        "ministry": "Tata Philanthropies",
        "category": "Corporate CSR & Philanthropy",
        "sub_category": "Higher Education",
        "scholarship_type": "Merit-cum-Means",
        "national_or_state": "National",
        "state": "All India",
        "education_level": "Undergraduate",
        "minimum_qualification": "Enrolled in recognized undergraduate or postgraduate program",
        "streams": "Engineering, Medicine, Nursing, Special Education, Social Work",
        "courses": "B.Tech, MBBS, B.Sc Nursing, MSW, B.Ed Special Education",
        "gender_eligibility": "All",
        "family_income_limit": 400000.0,
        "percentage_requirement": 60.0,
        "category_requirement": "All",
        "amount": "30% to 80% of College Tuition Fee",
        "amount_description": "Direct financial aid towards tuition fee calculated based on verified financial need and academic record.",
        "tuition_fee_support": "Direct partial or full payment of institutional tuition fees.",
        "duration": "1 Year (Renewable annually based on marks)",
        "renewable": True,
        "application_mode": "Online - Tata Trusts Portal (tatatrusts.org)",
        "official_application_url": "https://www.tatatrusts.org",
        "official_url": "https://www.tatatrusts.org/our-work/individual-grants-programme/education-grants",
        "guidelines_url": "https://www.tatatrusts.org/education-grants/guidelines",
        "eligibility": "Students with genuine financial constraints pursuing degree studies in recognized Indian universities. Minimum 60% in previous year exam.",
        "description": "Continuing Jamsetji Tata's philanthropic legacy of over a century, providing merit-based fee relief to deserving students across India.",
        "source": "Tata Trusts Individual Grants Programme"
    },
    {
        "title": "Reliance Foundation Undergraduate & Postgraduate Scholarships",
        "short_title": "Reliance Foundation Scholarship",
        "provider": "Reliance Foundation (CSR Initiative of Reliance Industries)",
        "provider_name": "Reliance Foundation",
        "provider_type": "PSU / Corporate CSR",
        "category": "Corporate CSR & Philanthropy",
        "sub_category": "Merit-cum-Means National Scholarship",
        "scholarship_type": "Merit-cum-Means",
        "national_or_state": "National",
        "state": "All India",
        "education_level": "Undergraduate",
        "minimum_qualification": "Passed Class 12 with >= 60% and enrolled in 1st year regular UG degree",
        "streams": "All Undergraduate Degree Streams (Science, Commerce, Arts, Engineering, Law, Medicine)",
        "courses": "All Regular UG Degrees",
        "gender_eligibility": "All",
        "family_income_limit": 1500000.0,
        "percentage_requirement": 60.0,
        "category_requirement": "All",
        "amount": "Up to ₹2,00,000 for UG / Up to ₹6,00,000 for PG (Full Course Duration)",
        "amount_description": "Grant of up to ₹2.00 Lakh for UG students disbursed across course duration + leadership development workshops.",
        "duration": "Entire duration of undergraduate study (3 to 4 years)",
        "renewable": True,
        "number_of_awards": "5,000 Undergraduate Scholars & 100 Postgraduate Scholars selected annually",
        "selection_process": "Online aptitude test + academic scores + socio-economic background evaluation.",
        "application_mode": "Online - Reliance Foundation Portal",
        "official_application_url": "https://www.scholarships.reliancefoundation.org",
        "official_url": "https://www.reliancefoundation.org",
        "guidelines_url": "https://www.scholarships.reliancefoundation.org/UG_Scholarship.aspx",
        "eligibility": "First-year regular undergraduate students in any stream scoring >= 60% in Class 12 with household income < ₹15 Lakhs (priority given to income < ₹2.5 Lakhs).",
        "description": "One of India's largest private scholarship initiatives creating a dynamic alumni network of young leaders committed to nation-building.",
        "source": "Reliance Foundation Official Portal"
    },
    {
        "title": "Infosys Foundation STEM Stars Scholarship for Women",
        "short_title": "Infosys STEM Stars",
        "provider": "Infosys Foundation",
        "provider_name": "Infosys Foundation",
        "provider_type": "PSU / Corporate CSR",
        "category": "Women in Technology & STEM",
        "sub_category": "Engineering & Technology",
        "scholarship_type": "Merit-cum-Means",
        "national_or_state": "National",
        "state": "All India",
        "education_level": "Undergraduate",
        "minimum_qualification": "Female students admitted to 1st year of B.Tech / MBBS / Integrated STEM degrees",
        "streams": "Computer Science, Electrical, Mechanical, Civil, Aerospace, Medicine (MBBS)",
        "courses": "B.Tech, B.E., MBBS, Integrated M.Sc in STEM",
        "gender_eligibility": "Female Only",
        "family_income_limit": 800000.0,
        "percentage_requirement": 75.0,
        "category_requirement": "All",
        "amount": "Up to ₹1,00,000 per annum",
        "amount_description": "Up to ₹1.00 Lakh per annum covering tuition fees, books, living expenses and examination costs.",
        "duration": "Entire duration of the course (Up to 4-5 Years)",
        "renewable": True,
        "number_of_awards": "Over 2,000 Female Scholars nationwide",
        "application_mode": "Online - Infosys Foundation Portal",
        "official_application_url": "https://www.infosys.com/infosys-foundation/stem-stars.html",
        "official_url": "https://www.infosys.com/infosys-foundation.html",
        "guidelines_url": "https://www.infosys.com/infosys-foundation/stem-stars/guidelines.html",
        "eligibility": "Female Indian citizen enrolled in 1st year at NIRF top-accredited engineering/medical institutes with family income <= ₹8.00 Lakhs and GPA >= 7.0 / 75% in Class 12.",
        "description": "Inspiring young women from underserved communities to break stereotypes and become future technology and medical pioneers.",
        "source": "Infosys Foundation CSR Initiative"
    },
    {
        "title": "HDFC Bank Parivartan's ECSS (Educational Crisis Scholarship Support)",
        "short_title": "HDFC Parivartan ECSS",
        "provider": "HDFC Bank Parivartan CSR",
        "provider_name": "HDFC Bank CSR",
        "provider_type": "PSU / Corporate CSR",
        "category": "Corporate CSR & Philanthropy",
        "sub_category": "Crisis & Means Relief",
        "scholarship_type": "Means-based",
        "national_or_state": "National",
        "state": "All India",
        "education_level": "Undergraduate",
        "minimum_qualification": "School (Class 1 to 12), Diploma, Undergraduate or Postgraduate students",
        "streams": "All Academic & Professional Programs",
        "gender_eligibility": "All",
        "family_income_limit": 250000.0,
        "percentage_requirement": 55.0,
        "category_requirement": "All",
        "amount": "₹35,000 to ₹75,000 per annum",
        "amount_description": "₹35,000 to ₹50,000 for UG courses; ₹75,000 for professional degrees like Engineering/Medical.",
        "duration": "1 Year (Renewable on application)",
        "renewable": True,
        "application_mode": "Online - HDFC CSR Partner Portal",
        "official_application_url": "https://www.hdfcbank.com/personal/about-us/corporate-social-responsibility",
        "official_url": "https://www.hdfcbank.com",
        "guidelines_url": "https://www.hdfcbank.com/csr/ecss-guidelines",
        "eligibility": "Students facing personal, family or financial crises (loss of earning parent, medical emergencies) with annual family income <= ₹2.50 Lakhs.",
        "description": "Assists students going through critical life challenges to continue their education without dropping out due to monetary hardship.",
        "source": "HDFC Bank Parivartan"
    },
    {
        "title": "ONGC Foundation Scholarship for SC/ST/OBC/General EWS",
        "short_title": "ONGC Scholarship",
        "provider": "Oil and Natural Gas Corporation (ONGC) Foundation",
        "provider_name": "ONGC Foundation",
        "provider_type": "PSU / Corporate CSR",
        "category": "Public Sector Undertakings (PSU)",
        "sub_category": "Engineering, MBBS, MBA, Geophysics",
        "scholarship_type": "Merit-cum-Means",
        "national_or_state": "National",
        "state": "All India",
        "education_level": "Undergraduate",
        "minimum_qualification": "1st year regular student in Engineering (B.Tech), MBBS, MBA, or Master's in Geology/Geophysics",
        "streams": "Engineering, Medicine, Business Administration, Earth Sciences",
        "courses": "B.Tech, MBBS, MBA, M.Sc Geology, M.Sc Geophysics",
        "gender_eligibility": "All (50% quota for female candidates)",
        "family_income_limit": 200000.0,
        "percentage_requirement": 60.0,
        "category_requirement": "All",
        "amount": "₹48,000 per annum (₹4,000 per month)",
        "duration": "Entire duration of the professional degree course",
        "renewable": True,
        "number_of_awards": "2,000 Scholarships annually (1,000 SC/ST + 500 OBC + 500 EWS)",
        "selection_process": "Zone-wise merit list based on qualifying examination percentage.",
        "application_mode": "Online - ONGC Foundation Portal (ongcscholar.org)",
        "official_application_url": "https://www.ongcscholar.org",
        "official_url": "https://www.ongcindia.com",
        "guidelines_url": "https://www.ongcscholar.org/guidelines",
        "eligibility": "Indian national admitted to 1st year of professional degree with minimum 60% in Class 12 or graduation. Family income <= ₹2.00 Lakhs/annum.",
        "description": "Prestigious CSR initiative of national energy giant ONGC to bridge educational disparities in engineering and medical disciplines.",
        "source": "ONGC Foundation"
    },
    {
        "title": "LIC Golden Jubilee Scholarship Scheme",
        "short_title": "LIC Golden Jubilee",
        "provider": "Life Insurance Corporation of India (LIC)",
        "provider_name": "LIC Golden Jubilee Foundation",
        "provider_type": "PSU / Corporate CSR",
        "category": "Public Sector Undertakings (PSU)",
        "sub_category": "Higher Education",
        "scholarship_type": "Means-based",
        "national_or_state": "National",
        "state": "All India",
        "education_level": "Undergraduate",
        "minimum_qualification": "Passed Class 10 or 12 with >= 60% marks",
        "streams": "Medicine, Engineering, Graduation in any discipline, Diploma, ITI",
        "gender_eligibility": "All (Special scholarship for Girl child)",
        "family_income_limit": 250000.0,
        "percentage_requirement": 60.0,
        "category_requirement": "All",
        "amount": "₹15,000 to ₹40,000 per annum",
        "amount_description": "₹40,000/year for Medicine; ₹30,000/year for Engineering; ₹20,000/year for General Graduation; ₹15,000/year for Special Girl Scholar.",
        "duration": "Entire duration of the degree or diploma program",
        "renewable": True,
        "number_of_awards": "Over 2,500 Scholars awarded across all 113 divisional centers",
        "application_mode": "Online - LIC India Portal (licindia.in)",
        "official_application_url": "https://licindia.in",
        "official_url": "https://licindia.in/Bottom-Links/Golden-Jubilee-Foundation",
        "guidelines_url": "https://licindia.in/guidelines-gjf",
        "eligibility": "Economically weaker students securing >= 60% in Class 10/12 entering higher studies. Family income <= ₹2.50 Lakhs per annum.",
        "description": "CSR flagship of LIC supporting youth from economically distressed backgrounds in completing professional and graduation courses.",
        "source": "LIC Golden Jubilee Foundation"
    },
    {
        "title": "Kotak Kanya Scholarship (Kotak Education Foundation)",
        "short_title": "Kotak Kanya",
        "provider": "Kotak Education Foundation",
        "provider_name": "Kotak Mahindra Bank CSR",
        "provider_type": "PSU / Corporate CSR",
        "category": "Women in Professional Education",
        "sub_category": "Professional Degrees",
        "scholarship_type": "Merit-cum-Means",
        "national_or_state": "National",
        "state": "All India",
        "education_level": "Undergraduate",
        "minimum_qualification": "Class 12 passed with >= 85% marks admitted to 1st year professional degree",
        "streams": "Engineering, Medicine, Architecture, Design, Integrated LLB",
        "courses": "B.Tech, MBBS, BDS, B.Arch, BA LLB, B.Des",
        "gender_eligibility": "Female Only",
        "family_income_limit": 600000.0,
        "percentage_requirement": 85.0,
        "category_requirement": "All",
        "amount": "Up to ₹1,50,000 per annum",
        "amount_description": "Up to ₹1.50 Lakh per year covering academic tuition fees, hostel, stationery and living expenses.",
        "duration": "Entire duration of the professional degree course (Up to 4-5 Years)",
        "renewable": True,
        "application_mode": "Online - Kotak Education Foundation Portal",
        "official_application_url": "https://kotakeducation.org",
        "official_url": "https://kotakeducation.org/kotak-kanya-scholarship",
        "guidelines_url": "https://kotakeducation.org/guidelines",
        "eligibility": "Meritorious girl students scoring >= 85% in Class 12 board examination entering 1st year of professional degree. Family income <= ₹6.00 Lakhs.",
        "description": "Helps meritorious young women from financially constrained backgrounds realize their dreams of becoming engineers, doctors, and legal professionals.",
        "source": "Kotak Education Foundation"
    },
    {
        "title": "Sitaram Jindal Foundation Scholarship Scheme",
        "short_title": "Jindal Scholarship",
        "provider": "Sitaram Jindal Foundation",
        "provider_name": "Sitaram Jindal Foundation",
        "provider_type": "Philanthropic Trust / NGO",
        "category": "Corporate CSR & Philanthropy",
        "sub_category": "General & Professional Degrees",
        "scholarship_type": "Means-based",
        "national_or_state": "National",
        "state": "All India",
        "education_level": "Undergraduate",
        "minimum_qualification": "Class 11 to Post-Graduation students in regular courses",
        "streams": "All Streams (Arts, Science, Commerce, Engineering, Medicine, Diploma, ITI)",
        "gender_eligibility": "All",
        "family_income_limit": 400000.0,
        "percentage_requirement": 60.0,
        "category_requirement": "All",
        "amount": "₹500 to ₹3,200 per month (₹6,000 to ₹38,400 per annum)",
        "duration": "Course Duration",
        "renewable": True,
        "application_mode": "Offline & Online - Sitaram Jindal Portal (sitaramjindalfoundation.org)",
        "official_application_url": "https://www.sitaramjindalfoundation.org",
        "official_url": "https://www.sitaramjindalfoundation.org",
        "guidelines_url": "https://www.sitaramjindalfoundation.org/scholarships-for-students-in-bangalore.php",
        "eligibility": "Regular students enrolled in recognized institutions without other major scholarships. Family income <= ₹4.00 Lakhs per annum.",
        "description": "One of India's most respected charitable trusts providing educational stipends to thousands of needy students across all Indian states.",
        "source": "Sitaram Jindal Foundation"
    },

    # =========================================================================
    # G. PRESTIGIOUS INTERNATIONAL SCHOLARSHIPS FOR INDIAN CITIZENS
    # =========================================================================
    {
        "title": "Commonwealth Scholarship for Master's and PhD Study in the UK (Indian Citizens)",
        "short_title": "Commonwealth UK",
        "provider": "Commonwealth Scholarship Commission (CSC) & Ministry of Education, India",
        "provider_name": "Commonwealth Scholarship Commission",
        "provider_type": "International",
        "ministry": "Ministry of Education (India) & FCDO (UK)",
        "category": "International Fellowships & Study Abroad",
        "sub_category": "Master's & Doctoral Degrees",
        "scholarship_type": "Merit-based",
        "national_or_state": "International",
        "state": "All India",
        "education_level": "Postgraduate",
        "minimum_qualification": "Bachelor's Degree with minimum 60% marks in relevant subject",
        "streams": "Science & Tech, Health Systems, Global Prosperity, Crisis Resilience, Governance",
        "courses": "One-year Master's degree or 3-year PhD at UK Universities",
        "gender_eligibility": "All",
        "percentage_requirement": 60.0,
        "category_requirement": "All",
        "amount": "Full Tuition Fee + Airfare + Monthly Stipend (£1,347 to £1,652 per month)",
        "amount_description": "Approved airfare to and from the UK + full approved tuition fees + living allowance (stipend) + warm clothing allowance + study travel grant.",
        "tuition_fee_support": "100% full tuition fees covered directly by Commonwealth Commission.",
        "duration": "1 Year (Master's) or 3 Years (PhD)",
        "renewable": False,
        "number_of_awards": "Around 50-65 Nominations from India annually",
        "selection_process": "Preliminary nomination by Ministry of Education, India followed by final selection by CSC UK.",
        "application_mode": "Online - Ministry of Education SAKSHAT Portal & CSC Portal",
        "official_application_url": "https://cscuk.fcdo.gov.uk/apply",
        "official_url": "https://cscuk.fcdo.gov.uk",
        "guidelines_url": "https://cscuk.fcdo.gov.uk/scholarships/commonwealth-masters-scholarships",
        "eligibility": "Indian citizen who holds a recognized Bachelor's degree and cannot afford to study in the UK without scholarship assistance.",
        "description": "Funded by UK Foreign, Commonwealth & Development Office to support talented individuals who have the potential to make a positive impact on the global stage.",
        "source": "Commonwealth Scholarship Commission in the UK"
    },
    {
        "title": "Fulbright-Nehru Master's Fellowships (USIEF)",
        "short_title": "Fulbright-Nehru",
        "provider": "United States-India Educational Foundation (USIEF)",
        "provider_name": "USIEF - Fulbright Commission",
        "provider_type": "International",
        "ministry": "US Department of State & Govt. of India",
        "category": "International Fellowships & Study Abroad",
        "sub_category": "Master's in USA",
        "scholarship_type": "Merit-based",
        "national_or_state": "International",
        "state": "All India",
        "education_level": "Postgraduate",
        "minimum_qualification": "Equivalent to US Bachelor's degree with >= 55% + minimum 3 years work experience",
        "streams": "Arts & Culture, Economics, Environmental Science, Higher Education Admin, International Affairs, Journalism, Public Health, Public Policy, Urban Planning, Women's Studies",
        "courses": "Master's Degree at selected US Colleges and Universities",
        "gender_eligibility": "All",
        "percentage_requirement": 55.0,
        "category_requirement": "All",
        "amount": "Full Tuition + Living Stipend + J-1 Visa Support + Health Insurance + Roundtrip Airfare",
        "amount_description": "Comprehensive grant covering full tuition, living expenses, accident/sickness coverage, and air travel.",
        "duration": "1 to 2 Years",
        "renewable": False,
        "selection_process": "Multi-tier evaluation: Written application review, expert panels, and national interview rounds.",
        "application_mode": "Online - USIEF Portal (usief.org.in)",
        "official_application_url": "https://www.usief.org.in/Fulbright-Nehru-Master-Fellowships.aspx",
        "official_url": "https://www.usief.org.in",
        "guidelines_url": "https://www.usief.org.in/Fellowships/Fulbright-Nehru-Fellowships.aspx",
        "eligibility": "Indian citizens with outstanding leadership qualities, completed 4-year degree (or Master's), and at least 3 years of substantial full-time professional experience.",
        "description": "Flagship bilateral fellowship empowering future Indian leaders through world-class academic immersion in United States universities.",
        "source": "United States-India Educational Foundation (USIEF)"
    },
    {
        "title": "Chevening Scholarships for One-Year Master's in the UK",
        "short_title": "Chevening UK",
        "provider": "Foreign, Commonwealth and Development Office (FCDO), UK Government",
        "provider_name": "Chevening Secretariat",
        "provider_type": "International",
        "ministry": "UK Government",
        "category": "International Fellowships & Study Abroad",
        "sub_category": "Leadership Master's",
        "scholarship_type": "Merit-based",
        "national_or_state": "International",
        "state": "All India",
        "education_level": "Postgraduate",
        "minimum_qualification": "Undergraduate degree that enables entry into a UK postgraduate course + 2 years work experience",
        "streams": "All Academic Fields",
        "courses": "Any One-Year Taught Master's Course at any UK University",
        "gender_eligibility": "All",
        "category_requirement": "All",
        "amount": "Full Tuition Fees + Monthly Living Allowance + Return Economy Flights",
        "duration": "1 Year",
        "renewable": False,
        "selection_process": "Global selection based on demonstrated leadership potential and strong academic vision.",
        "application_mode": "Online - Chevening Portal (chevening.org)",
        "official_application_url": "https://www.chevening.org/scholarship/india",
        "official_url": "https://www.chevening.org",
        "guidelines_url": "https://www.chevening.org/guidance",
        "eligibility": "Indian citizens with minimum 2 years of work experience (2,800 hours), holding an undergraduate degree, and committed to returning to India for at least two years after study.",
        "description": "UK government's global scholarship programme, funded by FCDO and partner organizations, developing future international leaders since 1983.",
        "source": "British High Commission / Chevening Secretariat"
    }
]


def seed_national_scholarships():
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()

    print("==============================================================================")
    print("SEEDING COMPREHENSIVE NATIONAL SCHOLARSHIP ECOSYSTEM")
    print("==============================================================================")

    created_count = 0
    updated_count = 0

    for s in SCHOLARSHIPS_DATA:
        title = s["title"].strip()
        slug = slugify(title)

        # Check if already exists by title or slug
        existing = c.execute("SELECT id FROM scholarships WHERE title = ? OR slug = ?", (title, slug)).fetchone()

        if existing:
            # Update existing record with rich structured attributes
            sch_id = existing[0]
            c.execute("""
                UPDATE scholarships SET
                    short_title = ?,
                    provider_name = ?,
                    provider_type = ?,
                    ministry = ?,
                    department = ?,
                    category = ?,
                    sub_category = ?,
                    scholarship_type = ?,
                    national_or_state = ?,
                    state = ?,
                    education_level = ?,
                    minimum_qualification = ?,
                    streams = ?,
                    courses = ?,
                    gender_eligibility = ?,
                    family_income_limit = ?,
                    percentage_requirement = ?,
                    academic_requirement = ?,
                    category_requirement = ?,
                    disability_requirement = ?,
                    domicile_requirement = ?,
                    amount = ?,
                    amount_description = ?,
                    tuition_fee_support = ?,
                    duration = ?,
                    renewable = ?,
                    number_of_awards = ?,
                    selection_process = ?,
                    application_mode = ?,
                    official_application_url = ?,
                    guidelines_url = ?,
                    requires_otr = ?,
                    requires_institute_verification = ?,
                    documents_required = ?,
                    common_mistakes = ?,
                    faqs = ?,
                    source = ?,
                    verification_status = 'VERIFIED',
                    last_verified_at = CURRENT_TIMESTAMP
                WHERE id = ?
            """, (
                s.get("short_title"),
                s.get("provider_name"),
                s.get("provider_type", "Central Government"),
                s.get("ministry"),
                s.get("department"),
                s.get("category"),
                s.get("sub_category"),
                s.get("scholarship_type", "Merit-cum-Means"),
                s.get("national_or_state", "National"),
                s.get("state"),
                s.get("education_level"),
                s.get("minimum_qualification"),
                s.get("streams"),
                s.get("courses"),
                s.get("gender_eligibility", "All"),
                s.get("family_income_limit"),
                s.get("percentage_requirement"),
                s.get("academic_requirement"),
                s.get("category_requirement", "All"),
                s.get("disability_requirement", "None"),
                s.get("domicile_requirement"),
                s.get("amount"),
                s.get("amount_description"),
                s.get("tuition_fee_support"),
                s.get("duration"),
                s.get("renewable", True),
                s.get("number_of_awards"),
                s.get("selection_process"),
                s.get("application_mode"),
                s.get("official_application_url"),
                s.get("guidelines_url"),
                s.get("requires_otr", False),
                s.get("requires_institute_verification", True),
                s.get("documents_required"),
                s.get("common_mistakes"),
                s.get("faqs"),
                s.get("source"),
                sch_id
            ))
            updated_count += 1
        else:
            # Insert new record
            c.execute("""
                INSERT INTO scholarships (
                    title, slug, short_title, provider, provider_name, provider_type,
                    ministry, department, category, sub_category, scholarship_type,
                    national_or_state, state, education_level, minimum_qualification,
                    streams, courses, gender_eligibility, family_income_limit,
                    percentage_requirement, academic_requirement, category_requirement,
                    disability_requirement, domicile_requirement, amount, amount_description,
                    tuition_fee_support, duration, renewable, number_of_awards,
                    selection_process, application_mode, official_application_url,
                    guidelines_url, requires_otr, requires_institute_verification,
                    documents_required, common_mistakes, faqs, source, eligibility,
                    description, website, official_url, verification_status
                ) VALUES (
                    ?, ?, ?, ?, ?, ?,
                    ?, ?, ?, ?, ?,
                    ?, ?, ?, ?,
                    ?, ?, ?, ?,
                    ?, ?, ?,
                    ?, ?, ?, ?,
                    ?, ?, ?, ?,
                    ?, ?, ?,
                    ?, ?, ?,
                    ?, ?, ?, ?, ?,
                    ?, ?, ?, 'VERIFIED'
                )
            """, (
                s["title"],
                slug,
                s.get("short_title"),
                s["provider"],
                s.get("provider_name"),
                s.get("provider_type", "Central Government"),
                s.get("ministry"),
                s.get("department"),
                s["category"],
                s.get("sub_category"),
                s.get("scholarship_type", "Merit-cum-Means"),
                s.get("national_or_state", "National"),
                s.get("state"),
                s.get("education_level"),
                s.get("minimum_qualification"),
                s.get("streams"),
                s.get("courses"),
                s.get("gender_eligibility", "All"),
                s.get("family_income_limit"),
                s.get("percentage_requirement"),
                s.get("academic_requirement"),
                s.get("category_requirement", "All"),
                s.get("disability_requirement", "None"),
                s.get("domicile_requirement"),
                s.get("amount"),
                s.get("amount_description"),
                s.get("tuition_fee_support"),
                s.get("duration"),
                s.get("renewable", True),
                s.get("number_of_awards"),
                s.get("selection_process"),
                s.get("application_mode"),
                s.get("official_application_url"),
                s.get("guidelines_url"),
                s.get("requires_otr", False),
                s.get("requires_institute_verification", True),
                s.get("documents_required"),
                s.get("common_mistakes"),
                s.get("faqs"),
                s["source"],
                s["eligibility"],
                s["description"],
                s.get("official_application_url"),
                s.get("official_url"),
            ))
            sch_id = c.lastrowid
            created_count += 1

        # Seed or refresh 2026-27 cycle
        cyc = c.execute("SELECT id FROM scholarship_cycles WHERE scholarship_id = ? AND academic_year = '2026-27'", (sch_id,)).fetchone()
        if not cyc:
            c.execute("""
                INSERT INTO scholarship_cycles (
                    scholarship_id, academic_year, application_start_date, application_end_date,
                    status, verification_status, source_url
                ) VALUES (?, ?, ?, ?, ?, ?, ?)
            """, (
                sch_id,
                "2026-27",
                "01-Jul-2026",
                "31-Oct-2026",
                "OPEN",
                "VERIFIED",
                s.get("official_application_url") or "https://scholarships.gov.in"
            ))

    # Seed default configurable fields if none exist
    fields_cnt = c.execute("SELECT COUNT(*) FROM scholarship_fields").fetchone()[0]
    if fields_cnt == 0:
        print("Populating standard configurable dynamic scholarship application fields...")
        standard_fields = [
            ("full_name", "Applicant Full Name (As on Aadhaar / 10th Certificate)", "text", True, "PERSONAL", 1, "user.full_name", "Must match your matriculation records exactly."),
            ("dob", "Date of Birth", "date", True, "PERSONAL", 2, "user.dob", "As recorded on birth / 10th certificate."),
            ("gender", "Gender", "select", True, "PERSONAL", 3, "user.gender", "Select gender identity for specialized girl/transgender schemes."),
            ("state", "State of Permanent Domicile", "select", True, "PERSONAL", 4, "student_profile.state", "State where you hold valid residential domicile."),
            ("district", "District", "text", True, "PERSONAL", 5, "student_profile.district", "Home district for regional quotas."),
            ("social_category", "Social Reservation Category", "select", True, "PERSONAL", 6, "user.category", "General, SC, ST, OBC (Creamy/Non-Creamy), EWS."),
            ("disability_status", "Person with Benchmark Disability (PwD 40%+)", "select", True, "PERSONAL", 7, "student_profile.is_disabled", "UDID Certificate required if Yes."),
            ("current_course", "Current Course / Degree Name", "text", True, "ACADEMIC", 8, "user.course", "e.g., B.Sc Mathematics, B.Tech CSE, MBBS."),
            ("institution_name", "Enrolled College / University / School Name", "text", True, "INSTITUTION", 9, "user.college_name", "Must be recognized by UGC/AICTE/State Board."),
            ("current_year", "Current Year of Study", "select", True, "ACADEMIC", 10, "user.class_grade", "1st Year, 2nd Year, 3rd Year, etc."),
            ("previous_percentage", "Qualifying Examination Percentage / CGPA", "number", True, "ACADEMIC", 11, "user.percentage", "Aggregate score in Class 12 or last semester."),
            ("family_annual_income", "Gross Family Annual Income (in Rupees)", "number", True, "FAMILY_INCOME", 12, "student_profile.family_income", "Must not exceed statutory ceiling on income certificate."),
            ("bank_account_holder", "Bank Account Holder Name (Must be in Student's Name)", "text", True, "DECLARATION", 13, None, "Account must be Aadhaar-seeded for DBT."),
            ("otr_reference", "One-Time Registration (OTR) / State Portal ID (If generated)", "text", False, "DECLARATION", 14, None, "Reference number from scholarships.gov.in or State portal.")
        ]
        for fname, flabel, ftype, freq, fsec, forder, fsource, fhelp in standard_fields:
            c.execute("""
                INSERT INTO scholarship_fields (
                    scholarship_id, field_name, label, field_type, required,
                    section, "order", autofill_source, help_text
                ) VALUES (NULL, ?, ?, ?, ?, ?, ?, ?, ?)
            """, (fname, flabel, ftype, freq, fsec, forder, fsource, fhelp))

    conn.commit()

    total_scholarships = c.execute("SELECT COUNT(*) FROM scholarships").fetchone()[0]
    total_cycles = c.execute("SELECT COUNT(*) FROM scholarship_cycles").fetchone()[0]
    verified_cnt = c.execute("SELECT COUNT(*) FROM scholarships WHERE verification_status = 'VERIFIED'").fetchone()[0]
    central_cnt = c.execute("SELECT COUNT(*) FROM scholarships WHERE provider_type = 'Central Government'").fetchone()[0]
    state_cnt = c.execute("SELECT COUNT(*) FROM scholarships WHERE provider_type = 'State Government'").fetchone()[0]
    csr_cnt = c.execute("SELECT COUNT(*) FROM scholarships WHERE provider_type LIKE '%CSR%' OR provider_type LIKE '%Trust%'").fetchone()[0]
    intl_cnt = c.execute("SELECT COUNT(*) FROM scholarships WHERE provider_type = 'International'").fetchone()[0]

    conn.close()

    print(f"Seeding completed successfully!")
    print(f"Created: {created_count} new scholarship records")
    print(f"Enriched/Updated: {updated_count} existing records")
    print(f"Total Scholarships in Database: {total_scholarships}")
    print(f"Verified Records: {verified_cnt}")
    print(f"Central Government: {central_cnt}")
    print(f"State Government: {state_cnt}")
    print(f"CSR & Philanthropic Trusts: {csr_cnt}")
    print(f"International Fellowships: {intl_cnt}")
    print(f"Active Application Cycles: {total_cycles}")

if __name__ == "__main__":
    seed_national_scholarships()
