"""
scripts/seed_comprehensive_careers.py
==============================================================================
MPath Career Counselling - Comprehensive National Career Discovery & Seeding
==============================================================================
Populates 126 authentic occupations across 14 official sectors.
Integrates relational mappings:
  - Career -> Course (via career_courses)
  - Career -> Exam (via career_exams)
  - Career -> Skills (via career_skills)
  - Career -> Roadmaps (via career_roadmaps)
==============================================================================
"""

import sqlite3
import json
from datetime import datetime

DB_PATH = "careerpathindia.db"

# Import technology data from career_dataset
from scripts.career_dataset import CAREERS_DATA as TECH_CAREERS

ADDITIONAL_CAREERS = [
    # Remaining 3 Tech Careers
    {
        "title": "Backend Developer",
        "short_name": "Backend Dev",
        "slug": "backend-developer",
        "category": "Technology & Computer Science",
        "sub_category": "Software Engineering & Architecture",
        "industry": "Information Technology",
        "icon": "server",
        "short_description": "Builds and maintains core application logic, database architectures, server configurations, and API interfaces.",
        "description": "Backend Developers construct the engine behind modern digital applications. They design scalable databases, write server-side algorithms, handle data encryption, and ensure lightning-fast API responses for millions of concurrent users.",
        "what_they_do": "They build RESTful and gRPC APIs, design database schemas, implement message queues (Kafka, RabbitMQ), optimize server response latency, and manage cloud microservice deployments.",
        "day_to_day_work": "• Writing server-side services in Java, Python, Go, or Node.js.\n• Designing relational and document database tables and queries.\n• Setting up caching layers using Redis or Memcached.\n• Implementing authentication and role-based access control.\n• Writing automated integration tests and stress-testing APIs.",
        "work_environment": "Modern tech offices or remote workspaces.",
        "work_modes": "Hybrid / Remote / On-site",
        "minimum_qualification": "Undergraduate",
        "preferred_streams": "Science (PCM)",
        "required_subjects": "Computer Science, Mathematics",
        "technical_skills": "Java/Go/Python/Node.js, SQL, REST/gRPC APIs, Redis, Docker, System Design, Microservices",
        "soft_skills": "Logical Rigor, Problem Solving, Tenacity, Teamwork",
        "tools": "VS Code, Postman, Docker, Git, PostgreSQL, Redis, Kafka",
        "certifications": "Oracle Certified Professional: Java SE, AWS Certified Developer",
        "experience_level": "Entry-Level to Senior",
        "career_growth": "Direct progression to Senior Backend Engineer, Backend Architect, or Principal Systems Engineer.",
        "internship_roles": "Backend Engineering Intern, Server-Side Developer Intern, API Development Intern",
        "entry_level_roles": "Junior Backend Developer, Associate Software Engineer",
        "average_salary": "₹4.5 - ₹16 LPA (Indicative range)",
        "salary_indicative": "Entry-Level (0-2 yrs): ₹4 - 7.5 LPA | Mid-Level (3-6 yrs): ₹8 - 18 LPA | Senior Architect (7+ yrs): ₹20 - 45+ LPA. Indicative figures from NCS & Tech Job Audits 2024.",
        "future_scope": "Essential universal role powering all web, mobile, enterprise, and fintech applications.",
        "government_opportunities": "NIC, CDAC, UIDAI, NPCI, Indian Railways CRIS backend teams.",
        "private_opportunities": "Flipkart, Amazon, Swiggy, Paytm, Zerodha, Razorpay, Google.",
        "higher_study_options": "M.Tech in CSE, M.S. in Distributed Systems.",
        "entrepreneurship_options": "BaaS (Backend-as-a-Service) tooling, API development consultancy.",
        "source": "National Career Service (NCS) / NASSCOM",
        "official_url": "https://www.ncs.gov.in",
        "verification_status": "VERIFIED",
        "courses": [{"course_id": 9, "type": "COMMON"}, {"course_id": 14, "type": "COMMON"}, {"course_id": 15, "type": "ALTERNATIVE"}],
        "exams": [{"exam_id": 8, "importance": "PRIMARY"}, {"exam_id": 69, "importance": "ALTERNATIVE"}],
        "routes": [
            {"title": "Path A: Standard Engineering to Backend", "type": "COMMON", "steps": "Class 12 (PCM) -> B.Tech CSE -> Master OOP, DBMS, OS & Networks -> Build 3 robust API projects -> Junior Backend Developer."},
            {"title": "Path B: BCA / B.Sc to Backend", "type": "COMMON", "steps": "Class 12 -> BCA / B.Sc CS -> Learn Node.js / Go / Python -> Build database-driven backends -> Backend Developer."}
        ],
        "ladder": [
            {"stage": "Junior Backend Developer", "exp": "0-2 Years", "desc": "Implements CRUD endpoints, writes database migrations, fixes API bugs."},
            {"stage": "Backend Engineer", "exp": "2-5 Years", "desc": "Designs microservices, implements caching and asynchronous job workers."},
            {"stage": "Senior Backend Architect", "exp": "5-8 Years", "desc": "Designs distributed system architecture, tunes high-throughput queues."},
            {"stage": "Staff / Principal Systems Engineer", "exp": "8+ Years", "desc": "Sets technical vision for organization-wide service reliability and throughput."}
        ],
        "roadmaps": {
            "Class 10": "Build strong interest in programming logic and mathematical functions.",
            "Class 12": "Master object-oriented programming (C++ or Java) and relational database theory.",
            "Graduation": "Build RESTful APIs with relational databases (PostgreSQL) and caching (Redis). Deploy backend services on cloud platforms.",
            "Working Professional": "Master Low-Level and High-Level System Design, distributed transaction consensus, and Kafka event streaming."
        }
    },
    {
        "title": "Frontend Developer",
        "short_name": "Frontend Dev",
        "slug": "frontend-developer",
        "category": "Technology & Computer Science",
        "sub_category": "Software Engineering & Architecture",
        "industry": "Information Technology",
        "icon": "window-desktop",
        "short_description": "Builds interactive, high-performance client-side web interfaces using modern JavaScript frameworks.",
        "description": "Frontend Developers translate designer mockups into dynamic web applications that run smoothly in web browsers. They focus on web accessibility, responsive cross-device layouts, fast rendering speed, and state management.",
        "what_they_do": "They code in HTML, CSS, JavaScript, and TypeScript, implement state management using Redux or Zustand, optimize Core Web Vitals, and connect visual screens to backend APIs.",
        "day_to_day_work": "• Building reusable UI components in React, Vue, or Next.js.\n• Styling interfaces with CSS, TailwindCSS, or CSS Modules.\n• Connecting client screens to REST and GraphQL backend services.\n• Auditing Lighthouse scores for page load speed and accessibility.\n• Debugging cross-browser quirks and mobile responsive issues.",
        "work_environment": "Software development studios, corporate IT headquarters, or remote.",
        "work_modes": "Remote / Hybrid / On-site",
        "minimum_qualification": "Undergraduate",
        "preferred_streams": "Any Stream",
        "required_subjects": "Computer Applications / English",
        "technical_skills": "JavaScript, TypeScript, React, Next.js, HTML5, CSS3, Web Performance, Git",
        "soft_skills": "Visual Eye, Collaboration, Problem Solving, Communication",
        "tools": "VS Code, Chrome DevTools, Figma, Git, Vercel, npm/yarn",
        "certifications": "Meta Front-End Developer Professional Certificate",
        "experience_level": "Entry-Level to Senior",
        "career_growth": "Broad career avenues transitioning to Senior Frontend Engineer, UI Architect, or Frontend Engineering Manager.",
        "internship_roles": "Frontend Intern, UI Developer Intern, React Intern",
        "entry_level_roles": "Junior Frontend Developer, Associate Web Developer",
        "average_salary": "₹4 - ₹14 LPA (Indicative range)",
        "salary_indicative": "Entry-Level (0-2 yrs): ₹3.5 - 6.5 LPA | Mid-Level (3-6 yrs): ₹7 - 15 LPA | Frontend Architect (7+ yrs): ₹18 - 38+ LPA. Indicative figures from NCS & Web Developer Surveys 2024.",
        "future_scope": "Continuous strong demand as every company needs intuitive digital portals and web apps.",
        "government_opportunities": "National Informatics Centre (NIC), Digital India portals, State e-Governance portals.",
        "private_opportunities": "Flipkart, MakeMyTrip, Swiggy, Zoho, Freshworks, top web design and SaaS firms.",
        "higher_study_options": "M.Tech in CSE, MCA.",
        "entrepreneurship_options": "Frontend development agency, component library creator, theme developer.",
        "source": "National Career Service (NCS) / NASSCOM",
        "official_url": "https://www.ncs.gov.in",
        "verification_status": "VERIFIED",
        "courses": [{"course_id": 14, "type": "COMMON"}, {"course_id": 9, "type": "COMMON"}, {"course_id": 4, "type": "COMMON"}],
        "exams": [{"exam_id": 8, "importance": "PRIMARY"}, {"exam_id": 79, "importance": "ALTERNATIVE"}],
        "routes": [
            {"title": "Path A: Computer Science Degree to Frontend", "type": "COMMON", "steps": "Class 12 -> BCA / B.Tech CSE -> Learn Modern JS & React -> Build responsive web apps -> Frontend Developer."},
            {"title": "Path B: Self-Taught Developer Route", "type": "ALTERNATIVE", "steps": "Any Class 12 / Degree -> Complete web development roadmaps -> Build 4+ live portfolio websites on GitHub -> Junior Frontend Developer."}
        ],
        "ladder": [
            {"stage": "Junior Frontend Developer", "exp": "0-2 Years", "desc": "Implements pixel-perfect components, fixes layout bugs, connects APIs."},
            {"stage": "Frontend Engineer", "exp": "2-5 Years", "desc": "Manages complex application state, optimizes client-side caching and bundle sizes."},
            {"stage": "Senior Frontend Architect", "exp": "5-8 Years", "desc": "Builds enterprise component design systems, ensures strict accessibility standards."},
            {"stage": "Director of Web Engineering", "exp": "8+ Years", "desc": "Directs cross-platform web technology choices and web platform performance."}
        ],
        "roadmaps": {
            "Class 10": "Learn HTML and CSS fundamentals. Design a personal hobby webpage.",
            "Class 12": "Learn JavaScript fundamentals (arrays, objects, functions, DOM events).",
            "Graduation": "Master React or Next.js with TypeScript. Build 3 complete web applications with modern state management.",
            "Working Professional": "Master Server-Side Rendering (SSR), Core Web Vitals optimization, and micro-frontend architectures."
        }
    },
    {
        "title": "Full Stack Developer",
        "short_name": "Full Stack Dev",
        "slug": "full-stack-developer",
        "category": "Technology & Computer Science",
        "sub_category": "Software Engineering & Architecture",
        "industry": "Information Technology",
        "icon": "layers",
        "short_description": "Engineers complete web software systems end-to-end, integrating intuitive frontends with robust backends and databases.",
        "description": "Full Stack Developers master the entire spectrum of web engineering. They effortlessly switch between designing frontend components, writing server business logic, querying databases, and deploying software on modern cloud platforms.",
        "what_they_do": "They architect end-to-end features, write both client and server code, manage database schemas, optimize overall system throughput, and ensure software security across all tiers.",
        "day_to_day_work": "• Building frontend user interfaces with React, Vue, or Angular.\n• Implementing backend APIs in Node.js, Python, or Java.\n• Writing database queries and migrations in PostgreSQL or MongoDB.\n• Automating build and deployment pipelines on cloud platforms.\n• Debugging full system issues spanning client, server, and network.",
        "work_environment": "High-growth tech startups, software engineering campuses, or remote.",
        "work_modes": "Remote / Hybrid / On-site",
        "minimum_qualification": "Undergraduate",
        "preferred_streams": "Science (PCM) / Any with CS",
        "required_subjects": "Computer Science, Mathematics",
        "technical_skills": "React/Next.js, Node.js/Python, SQL, MongoDB, RESTful APIs, Git, Docker, System Architecture",
        "soft_skills": "Versatility, Autonomy, Fast Learner, Problem Solving",
        "tools": "VS Code, Postman, Git, Docker, Vercel, AWS, GitHub",
        "certifications": "AWS Certified Developer, Meta Full-Stack Professional Certificate",
        "experience_level": "Entry-Level to Senior",
        "career_growth": "Broad, flexible career with progression to Tech Lead, Engineering Manager, or Startup CTO.",
        "internship_roles": "Full Stack Intern, Web Engineering Intern, Software Developer Intern",
        "entry_level_roles": "Associate Full Stack Developer, Junior Software Engineer",
        "average_salary": "₹5 - ₹17 LPA (Indicative range)",
        "salary_indicative": "Entry-Level (0-2 yrs): ₹4 - 7.5 LPA | Mid-Level (3-6 yrs): ₹8 - 18 LPA | Lead Full Stack (7+ yrs): ₹20 - 45+ LPA. Indicative figures based on NCS & Tech Compensation Audits 2024.",
        "future_scope": "Consistently one of the most versatile and sought-after engineering roles globally.",
        "government_opportunities": "NIC, Centre for Development of Telematics (C-DOT), State e-Governance teams.",
        "private_opportunities": "Swiggy, Zomato, Razorpay, Flipkart, Infosys, top global software agencies and venture-backed startups.",
        "higher_study_options": "M.Tech in Computer Science, MCA, MBA in IT.",
        "entrepreneurship_options": "Founding tech startups, building digital SaaS products, independent technical consulting.",
        "source": "National Career Service (NCS) / NASSCOM",
        "official_url": "https://www.ncs.gov.in",
        "verification_status": "VERIFIED",
        "courses": [{"course_id": 9, "type": "COMMON"}, {"course_id": 14, "type": "COMMON"}, {"course_id": 15, "type": "ALTERNATIVE"}],
        "exams": [{"exam_id": 8, "importance": "PRIMARY"}, {"exam_id": 69, "importance": "ALTERNATIVE"}],
        "routes": [
            {"title": "Path A: Standard Engineering to Full Stack", "type": "COMMON", "steps": "Class 12 (PCM) -> B.Tech CSE -> Full-stack JavaScript stack (MERN / PERN) -> Deploy full projects -> Full Stack Developer."},
            {"title": "Path B: BCA to Full Stack Route", "type": "COMMON", "steps": "Class 12 -> BCA -> Intensive hands-on full-stack development -> Internship -> Full Stack Developer."}
        ],
        "ladder": [
            {"stage": "Junior Full Stack Developer", "exp": "0-2 Years", "desc": "Implements UI screens and basic API endpoints under senior supervision."},
            {"stage": "Full Stack Developer", "exp": "2-5 Years", "desc": "Owns end-to-end features from database migration to UI deployment."},
            {"stage": "Senior Full Stack Tech Lead", "exp": "5-8 Years", "desc": "Makes architectural decisions, guides junior developers, oversees code quality."},
            {"stage": "Principal Architect / CTO", "exp": "8+ Years", "desc": "Directs complete technical vision, technology investments, and infrastructure scaling."}
        ],
        "roadmaps": {
            "Class 10": "Learn fundamental coding logic and build basic web pages with HTML and CSS.",
            "Class 12": "Learn JavaScript and basic database concepts.",
            "Graduation": "Learn React/Next.js and Node.js/Python. Build 3 deployed end-to-end applications with PostgreSQL and authentication.",
            "Working Professional": "Master system design, cloud container deployments (Docker/Kubernetes), and microservice patterns."
        }
    },

    # =========================================================================
    # 2. HEALTHCARE & MEDICAL SCIENCES (12 Careers)
    # =========================================================================
    {
        "title": "General Physician / Medical Doctor",
        "short_name": "Doctor (MBBS)",
        "slug": "doctor",
        "category": "Healthcare & Medical Sciences",
        "sub_category": "Clinical Medicine & Surgery",
        "industry": "Healthcare & Hospitals",
        "icon": "heart-pulse",
        "short_description": "Diagnoses, treats, and helps prevent illnesses, disorders, and injuries to promote human health and well-being.",
        "description": "General Physicians are primary healthcare practitioners who examine patients, diagnose illnesses, interpret medical tests, prescribe medications, and coordinate specialized treatment. They serve as the cornerstone of community healthcare.",
        "what_they_do": "They examine patients, order laboratory investigations, prescribe pharmacological treatments, perform minor surgical procedures, provide preventive health advice, and refer patients to medical specialists.",
        "day_to_day_work": "• Conducting clinical patient consultations and physical examinations.\n• Reviewing diagnostic test results (blood work, X-rays, ECGs).\n• Prescribing medications and therapeutic treatment plans.\n• Managing acute emergencies and monitoring chronic diseases.\n• Maintaining precise electronic medical records (EMR).",
        "work_environment": "Government and private hospitals, primary healthcare centers (PHCs), medical clinics.",
        "work_modes": "On-site / Hospital Ward & OPD / Emergency Rotations",
        "minimum_qualification": "Undergraduate (MBBS)",
        "preferred_streams": "Science (PCB)",
        "required_subjects": "Physics, Chemistry, Biology / Biotechnology",
        "technical_skills": "Clinical Diagnosis, Pharmacology, Emergency Care, Medical Ethics, Patient History Taking, Basic Life Support (BLS)",
        "soft_skills": "Empathy, Emotional Resilience, Critical Thinking, Patient Communication",
        "tools": "Stethoscope, Sphygmomanometer, Ophthalmoscope, EMR Software, Diagnostic Panels",
        "certifications": "National Medical Commission (NMC) State Medical Council Registration, BLS/ACLS Certification",
        "experience_level": "Entry-Level to Senior",
        "career_growth": "Exceptional lifetime career progression through postgraduate specialization (MD/MS) and superspecialization (DM/MCh).",
        "internship_roles": "Compulsory Rotating Medical Internship (CRMI - 1 Year)",
        "entry_level_roles": "Junior Resident (JR), Medical Officer (MO), General Duty Medical Officer (GDMO)",
        "average_salary": "₹7 - ₹18 LPA (Indicative range)",
        "salary_indicative": "Junior Resident / Medical Officer (0-2 yrs): ₹6 - 10 LPA | Specialist MD/MS (3-6 yrs): ₹12 - 24 LPA | Senior Consultant (7+ yrs): ₹25 - 60+ LPA. Indicative figures from National Medical Commission & Public Health Audits 2024.",
        "future_scope": "Critical permanent universal demand across public and private healthcare sectors.",
        "government_opportunities": "UPSC Combined Medical Services (CMS), AIIMS, State Public Service Medical Officers, Armed Forces Medical Services (AFMS), Railway Hospitals.",
        "private_opportunities": "Apollo Hospitals, Fortis Healthcare, Max Healthcare, Manipal Hospitals, private clinical practice.",
        "higher_study_options": "MD (Doctor of Medicine), MS (Master of Surgery), DNB (Diplomate of National Board), MPH (Public Health).",
        "entrepreneurship_options": "Establishing private clinical dispensaries, multi-specialty nursing homes, healthcare diagnostics centers.",
        "source": "National Medical Commission (NMC) / Ministry of Health & Family Welfare",
        "official_url": "https://www.nmc.org.in",
        "verification_status": "VERIFIED",
        "courses": [{"course_id": 25, "type": "DIRECT"}, {"course_id": 28, "type": "SPECIALIZED"}],
        "exams": [{"exam_id": 7, "importance": "PRIMARY"}, {"exam_id": 71, "importance": "PRIMARY"}, {"exam_id": 72, "importance": "SPECIALIZED"}],
        "routes": [
            {"title": "Path A: Standard National Medical Route", "type": "COMMON", "steps": "Class 12 (PCB) -> NEET-UG Examination -> MBBS Degree (4.5 yrs + 1 yr Internship) -> State Medical Council Registration -> Medical Officer or MD/MS via NEET-PG."}
        ],
        "ladder": [
            {"stage": "Medical Intern / Junior Resident", "exp": "0-2 Years", "desc": "Completes rotatory hospital postings in medicine, surgery, pediatrics, obstetrics under consultants."},
            {"stage": "Medical Officer / Resident Specialist", "exp": "2-5 Years", "desc": "Manages OPD/IPD departments, handles acute cases, pursues MD/MS specialization."},
            {"stage": "Senior Consultant / Surgeon", "exp": "5-10 Years", "desc": "Performs complex treatments, oversees medical wards, trains junior doctors."},
            {"stage": "Medical Director / Chief of Medicine", "exp": "10+ Years", "desc": "Directs clinical governance, hospital administration, and medical ethics board."}
        ],
        "roadmaps": {
            "Class 10": "Cultivate strong command over Biology, Chemistry, and Human Anatomy fundamentals.",
            "Class 12": "Score high in PCB (Physics, Chemistry, Biology). Dedicate structured preparation for NEET-UG.",
            "Graduation": "Complete 4.5 years of rigorous MBBS coursework and 1 year of compulsory rotating internship. Register with NMC.",
            "Working Professional": "Prepare for NEET-PG / INI-CET to specialize in Medicine, Surgery, Pediatrics, or Radiology."
        }
    },
    {
        "title": "Dental Surgeon (Dentist)",
        "short_name": "Dentist (BDS)",
        "slug": "dentist",
        "category": "Healthcare & Medical Sciences",
        "sub_category": "Dental Medicine & Surgery",
        "industry": "Healthcare / Dentistry",
        "icon": "shield-plus",
        "short_description": "Diagnoses, prevents, and treats diseases, injuries, and malformations of teeth, gums, and oral maxillofacial structures.",
        "description": "Dental Surgeons are oral healthcare specialists who treat oral diseases, perform restorative and cosmetic procedures, conduct dental surgeries, and educate patients on preventive oral hygiene.",
        "what_they_do": "They examine teeth and gum tissues, fill cavities, perform root canal treatments (RCT), extract impacted teeth, fit orthodontic appliances, and perform oral maxillofacial surgeries.",
        "day_to_day_work": "• Conducting oral examinations and interpreting dental radiographs (OPG, IOPA).\n• Performing dental restorations, root canal treatments, and crowns.\n• Extracting diseased or impacted teeth under local anesthesia.\n• Providing preventive dental cleaning and scaling.\n• Advising patients on oral healthcare regimens.",
        "work_environment": "Dental clinics, multi-specialty hospitals, or dental college research facilities.",
        "work_modes": "On-site / Clinical",
        "minimum_qualification": "Undergraduate (BDS)",
        "preferred_streams": "Science (PCB)",
        "required_subjects": "Physics, Chemistry, Biology",
        "technical_skills": "Oral Diagnosis, Endodontics, Periodontics, Tooth Extraction, Dental Radiography, Prosthodontics",
        "soft_skills": "Manual Dexterity, Patient Empathy, Precision, Calm Demeanor",
        "tools": "Dental Drill, Mouth Mirror, Scaler, Dental Forceps, RVG Digital Radiography",
        "certifications": "Dental Council of India (DCI) State Registration",
        "experience_level": "Entry-Level to Senior",
        "career_growth": "Steady growth with postgraduate MDS specialization (Orthodontics, Oral Surgery, Prosthodontics) or private clinic ownership.",
        "internship_roles": "Compulsory Rotatory Dental Internship (1 Year)",
        "entry_level_roles": "Junior Dental Surgeon, Associate Dentist, Clinical Assistant",
        "average_salary": "₹4 - ₹12 LPA (Indicative range)",
        "salary_indicative": "Associate Dentist (0-2 yrs): ₹3.5 - 6 LPA | MDS Specialist (3-6 yrs): ₹8 - 16 LPA | Established Private Clinic Owner (7+ yrs): ₹15 - 35+ LPA. Indicative figures from Dental Council of India 2024.",
        "future_scope": "Growing demand fueled by aesthetic dentistry, implantology, and rising awareness of oral hygiene.",
        "government_opportunities": "Army Dental Corps, State Public Service Commissions Dental Officers, Railway Hospitals, ESI Dental Units.",
        "private_opportunities": "Clove Dental, Apollo White Dental, private dental hospitals, private dental clinic practice.",
        "higher_study_options": "MDS (Master of Dental Surgery), Fellowship in Implantology / Cosmetic Dentistry.",
        "entrepreneurship_options": "Independent private dental clinic, dental aesthetic studio, mobile dental clinic services.",
        "source": "Dental Council of India (DCI)",
        "official_url": "https://www.dciindia.gov.in",
        "verification_status": "VERIFIED",
        "courses": [{"course_id": 26, "type": "DIRECT"}],
        "exams": [{"exam_id": 7, "importance": "PRIMARY"}, {"exam_id": 71, "importance": "PRIMARY"}],
        "routes": [
            {"title": "Path A: Standard BDS Route", "type": "COMMON", "steps": "Class 12 (PCB) -> NEET-UG Examination -> BDS Degree (4 yrs + 1 yr Internship) -> State Dental Council Registration -> Practice or MDS via NEET-MDS."}
        ],
        "ladder": [
            {"stage": "Dental Intern / Junior Associate", "exp": "0-2 Years", "desc": "Performs routine cleanings, simple fillings, assists senior dental surgeons."},
            {"stage": "Dental Surgeon", "exp": "2-5 Years", "desc": "Performs root canals, crown fittings, extractions independently."},
            {"stage": "MDS Specialist / Clinic Owner", "exp": "5-8 Years", "desc": "Specializes in orthodontics, periodontics, or oral surgery; leads clinic practice."},
            {"stage": "Chief Dental Consultant / Professor", "exp": "8+ Years", "desc": "Teaches at dental colleges, performs complex maxillofacial surgeries."}
        ],
        "roadmaps": {
            "Class 10": "Focus on Biology, hand-eye coordination, and general science.",
            "Class 12": "Study Physics, Chemistry, and Biology thoroughly. Prepare for NEET-UG.",
            "Graduation": "Complete 4 years of BDS academic training and 1 year of compulsory rotating dental internship.",
            "Working Professional": "Pursue MDS in Orthodontics, Prosthodontics, or Endodontics, or set up a modern private dental clinic."
        }
    },
    {
        "title": "Pharmacist",
        "short_name": "Pharmacist (B.Pharm)",
        "slug": "pharmacist",
        "category": "Healthcare & Medical Sciences",
        "sub_category": "Pharmacy & Pharmaceutical Sciences",
        "industry": "Pharmaceuticals & Healthcare",
        "icon": "capsule",
        "short_description": "Prepares, dispenses, and monitors medications, ensuring optimal pharmacological therapeutic outcomes and drug safety.",
        "description": "Pharmacists are healthcare professionals who understand drug composition, manufacture, chemical properties, interactions, and therapeutic usage. They dispense medications in healthcare settings and drive pharmaceutical drug discovery in industry.",
        "what_they_do": "They review doctor prescriptions for drug interactions, dispense medications, counsel patients on dosage and side effects, and manage pharmaceutical research and manufacturing in factories.",
        "day_to_day_work": "• Dispensing prescription and over-the-counter pharmaceuticals.\n• Reviewing patient drug regimens for dosage errors and contraindications.\n• Conducting quality control assays in pharmaceutical manufacturing labs.\n• Counseling patients regarding administration schedules and side effects.\n• Maintaining precise regulatory registers for controlled substances.",
        "work_environment": "Hospital pharmacies, community retail pharmacies, pharmaceutical R&D labs, and manufacturing plants.",
        "work_modes": "On-site / Shift-based in hospital pharmacies",
        "minimum_qualification": "Undergraduate (B.Pharm)",
        "preferred_streams": "Science (PCB / PCM)",
        "required_subjects": "Chemistry, Biology / Mathematics, Physics",
        "technical_skills": "Pharmacology, Medicinal Chemistry, Drug Formulation, Pharmacovigilance, Quality Assurance (QA/QC), Clinical Trials",
        "soft_skills": "Meticulous Attention to Detail, Patient Communication, Ethics, Critical Thinking",
        "tools": "HPLC, Dissolution Apparatus, Spectrophotometer, Pharmacy Dispensing ERP",
        "certifications": "Pharmacy Council of India (PCI) State Pharmacy Council Registration",
        "experience_level": "Entry-Level to Senior",
        "career_growth": "Strong advancement into Drug Regulatory Affairs, Clinical Research, QA/QC Management, or Industrial Pharmacy Leadership.",
        "internship_roles": "Pharmacy Intern, Clinical Research Trainee, QA/QC Intern",
        "entry_level_roles": "Registered Pharmacist, Quality Control Analyst, Medical Representative, Pharmacovigilance Associate",
        "average_salary": "₹3.5 - ₹10 LPA (Indicative range)",
        "salary_indicative": "Entry-Level (0-2 yrs): ₹3 - 5 LPA | Mid-Level / QA Manager (3-6 yrs): ₹6 - 12 LPA | Regulatory Affairs / Plant Head (7+ yrs): ₹14 - 30+ LPA. Indicative figures from Pharmacy Council of India & Pharmexcil 2024.",
        "future_scope": "Very strong continuous growth supported by India's position as the 'Pharmacy of the World'.",
        "government_opportunities": "Government Hospital Pharmacist, Drug Inspector (UPSC/State PSC), CDSCO, Central Research Institutes.",
        "private_opportunities": "Sun Pharma, Dr. Reddy's Laboratories, Cipla, Lupin, Biocon, Apollo Pharmacy, MedPlus.",
        "higher_study_options": "M.Pharm (Pharmaceutics / Pharmacology), Pharm.D (Post-Baccalaureate), MBA in Pharmaceutical Management.",
        "entrepreneurship_options": "Licensed retail/wholesale pharmacy chain, pharmaceutical manufacturing unit, third-party distribution.",
        "source": "Pharmacy Council of India (PCI)",
        "official_url": "https://www.pci.nic.in",
        "verification_status": "VERIFIED",
        "courses": [{"course_id": 27, "type": "DIRECT"}],
        "exams": [{"exam_id": 74, "importance": "PRIMARY"}, {"exam_id": 79, "importance": "ALTERNATIVE"}],
        "routes": [
            {"title": "Path A: Standard B.Pharm Route", "type": "COMMON", "steps": "Class 12 (PCB/PCM) -> State CET / GPAT -> B.Pharm (4 yrs) -> State Pharmacy Council Registration -> Industrial / Clinical Pharmacist."},
            {"title": "Path B: Diploma in Pharmacy to B.Pharm Lateral", "type": "ALTERNATIVE", "steps": "Class 12 -> D.Pharm (2 yrs) -> Lateral entry to 2nd year B.Pharm -> Licensed Pharmacist."}
        ],
        "ladder": [
            {"stage": "Junior Pharmacist / QC Analyst", "exp": "0-2 Years", "desc": "Dispenses medications, carries out standard wet chemistry and raw material testing."},
            {"stage": "Regulatory Affairs / QA Officer", "exp": "2-5 Years", "desc": "Prepares drug dossiers for FDA/CDSCO submissions, audits GMP compliance."},
            {"stage": "Production Manager / Head Pharmacist", "exp": "5-8 Years", "desc": "Oversees formulation lines, manages pharmaceutical supply chain."},
            {"stage": "Director of Regulatory Affairs / VP Quality", "exp": "8+ Years", "desc": "Heads global drug approvals, compliance, and international plant audits."}
        ],
        "roadmaps": {
            "Class 10": "Focus on Chemistry, Biology, and arithmetic.",
            "Class 12": "Excel in Chemistry and Biology/Maths. Prepare for state pharmacy entrance exams or CUET.",
            "Graduation": "Complete B.Pharm with hands-on lab experiments in organic chemistry and pharmacology. Register with State Pharmacy Council.",
            "Working Professional": "Clear GPAT for M.Pharm, or specialize in Pharmacovigilance, Regulatory Affairs, or Clinical Research."
        }
    },
    {
        "title": "Registered Nurse",
        "short_name": "Nurse (B.Sc Nursing)",
        "slug": "registered-nurse",
        "category": "Healthcare & Medical Sciences",
        "sub_category": "Nursing & Patient Care",
        "industry": "Healthcare & Hospitals",
        "icon": "clipboard-pulse",
        "short_description": "Provides professional patient care, administers medications, monitors vital signs, and coordinates clinical treatments.",
        "description": "Registered Nurses are critical healthcare providers who administer hands-on care across emergency departments, operating theaters, intensive care units (ICUs), and community health clinics.",
        "what_they_do": "They monitor patient health metrics, administer intravenous fluids and prescribed medications, assist surgeons during operations, educate patients and families on post-discharge care, and manage hospital ward care plans.",
        "day_to_day_work": "• Administering medications and IV drips per physician orders.\n• Monitoring and recording temperature, pulse, blood pressure, and oxygen saturation.\n• Assisting in surgical procedures and wound dressing.\n• Operating life-support and clinical monitoring equipment in ICUs.\n• Providing compassionate comfort and emotional support to patients.",
        "work_environment": "Hospital wards, ICUs, emergency rooms, surgical theaters, and outpatient clinics.",
        "work_modes": "On-site / 24x7 Shift Rotations",
        "minimum_qualification": "Undergraduate (B.Sc Nursing)",
        "preferred_streams": "Science (PCB)",
        "required_subjects": "Biology, Chemistry, Physics, English",
        "technical_skills": "Vital Signs Monitoring, Medication Administration, Infection Control, Emergency Triage, ICU Protocol, Wound Care",
        "soft_skills": "Empathy, Emotional Resilience, Calm Under Pressure, Communication, Physical Stamina",
        "tools": "Vital Signs Monitors, Infusion Pumps, Defibrillators, Syringes, Catheters, EMR Software",
        "certifications": "Indian Nursing Council (INC) State Nursing Council Registration",
        "experience_level": "Entry-Level to Senior",
        "career_growth": "Broad domestic and massive international career opportunities progressing to Nursing Superintendent, Nurse Educator, or Clinical Nurse Specialist.",
        "internship_roles": "Clinical Nursing Internship (Integrated in B.Sc)",
        "entry_level_roles": "Staff Nurse, Junior Ward Nurse, ICU Nurse Trainee",
        "average_salary": "₹3.5 - ₹9 LPA (Indicative range - substantially higher in international positions)",
        "salary_indicative": "Staff Nurse (0-2 yrs): ₹3 - 5 LPA | Senior ICU/OT Nurse (3-6 yrs): ₹5 - 9 LPA | Nursing Superintendent (7+ yrs): ₹10 - 20+ LPA. Indicative figures from INC & Healthcare Surveys 2024. Significantly higher in overseas markets (UK, Gulf, US, Germany).",
        "future_scope": "Surging universal global demand with high migration opportunities to the UK, Europe, Australia, and North America.",
        "government_opportunities": "AIIMS NORCET (Nursing Officer Recruitment Common Eligibility Test), Railway Hospitals, Military Nursing Services (MNS), State Health Departments.",
        "private_opportunities": "Apollo Hospitals, Fortis, Max Healthcare, Medanta, Manipal, Columbia Asia.",
        "higher_study_options": "M.Sc Nursing (Critical Care, Community Health, Obstetrics), Post-Basic B.Sc Nursing.",
        "entrepreneurship_options": "Home healthcare nursing services, specialized elderly care and palliative centers.",
        "source": "Indian Nursing Council (INC)",
        "official_url": "https://www.indiannursingcouncil.org",
        "verification_status": "VERIFIED",
        "courses": [{"course_id": 8, "type": "DIRECT"}],
        "exams": [{"exam_id": 27, "importance": "PRIMARY"}, {"exam_id": 28, "importance": "PRIMARY"}],
        "routes": [
            {"title": "Path A: Standard B.Sc Nursing Route", "type": "COMMON", "steps": "Class 12 (PCB) -> B.Sc Nursing Entrance Exam (AIIMS / State CET) -> B.Sc Nursing (4 yrs) -> State Nursing Council Registration -> AIIMS NORCET or Private Hospital Nurse."},
            {"title": "Path B: GNM to Post-Basic Nursing", "type": "ALTERNATIVE", "steps": "Class 12 -> General Nursing & Midwifery (GNM - 3 yrs) -> Register as RN/RM -> Post-Basic B.Sc Nursing (2 yrs) -> Senior Nursing Officer."}
        ],
        "ladder": [
            {"stage": "Staff Nurse Grade II", "exp": "0-2 Years", "desc": "Provides bedside care in general wards, records patient charts, administers medications."},
            {"stage": "Senior Staff Nurse / ICU Specialist", "exp": "2-5 Years", "desc": "Manages intensive care units, handles ventilator settings, mentors junior nurses."},
            {"stage": "Assistant Nursing Superintendent", "exp": "5-8 Years", "desc": "Supervises hospital nursing staff rosters, maintains hospital accreditation standards."},
            {"stage": "Chief Nursing Officer / Nursing Superintendent", "exp": "8+ Years", "desc": "Heads the hospital's entire nursing administration and clinical training."}
        ],
        "roadmaps": {
            "Class 10": "Build strong biology and general science foundations. Develop empathy and dedication to service.",
            "Class 12": "Score at least 50% in Physics, Chemistry, Biology, and English. Prepare for AIIMS B.Sc Nursing or State CET.",
            "Graduation": "Complete 4 years of B.Sc Nursing including hospital ward rotations. Register with the State Nursing Council.",
            "Working Professional": "Clear AIIMS NORCET for prestigious central government postings or clear IELTS/OET for UK/USA/Gulf licensing exams."
        }
    },
    {
        "title": "Physiotherapist",
        "short_name": "Physiotherapist (BPT)",
        "slug": "physiotherapist",
        "category": "Healthcare & Medical Sciences",
        "sub_category": "Allied Health Sciences & Rehabilitation",
        "industry": "Healthcare & Sports Medicine",
        "icon": "person-walking",
        "short_description": "Helps patients recover mobility, manage chronic pain, and rehabilitate physical function following injuries or neuromuscular disorders.",
        "description": "Physiotherapists assess and treat individuals with movement limitations caused by trauma, surgery, aging, stroke, or sports injuries. They employ physical exercise regimens, manual therapy, and electrotherapy modalities to restore movement and functional independence.",
        "what_they_do": "They examine patient muscular strength, joint range of motion, and posture, design customized rehabilitation regimens, perform joint mobilizations, and monitor neurological recovery.",
        "day_to_day_work": "• Assessing patient gait, balance, joint flexibility, and muscle power.\n• Administering manual physical therapy, trigger-point release, and spinal adjustments.\n• Applying electrotherapy (TENS, ultrasound therapy, traction).\n• Designing therapeutic home exercise regimens.\n• Educating patients on ergonomic posture and injury prevention.",
        "work_environment": "Rehabilitation centers, orthopedic hospitals, sports fitness centers, private clinics.",
        "work_modes": "On-site / Clinical / Home Visits",
        "minimum_qualification": "Undergraduate (BPT)",
        "preferred_streams": "Science (PCB)",
        "required_subjects": "Physics, Chemistry, Biology",
        "technical_skills": "Musculoskeletal Assessment, Manual Therapy, Neurological Rehabilitation, Exercise Physiology, Electrotherapy, Sports Taping",
        "soft_skills": "Patience, Encouragement, Active Listening, Physical Stamina",
        "tools": "TENS Machine, Ultrasound Therapy Device, Goniometer, Resistance Bands, Exercise Balls",
        "certifications": "National Commission for Allied and Healthcare Professions (NCAHP) Registration",
        "experience_level": "Entry-Level to Senior",
        "career_growth": "Steady expansion into Sports Physiotherapy (BCCI, Olympic teams), Neuro-Rehabilitation, or private clinic ownership.",
        "internship_roles": "Compulsory Rotatory Physiotherapy Internship (6 Months)",
        "entry_level_roles": "Junior Physiotherapist, Clinical Physiotherapy Assistant, Fitness Rehabilitation Specialist",
        "average_salary": "₹3.5 - ₹9 LPA (Indicative range)",
        "salary_indicative": "Entry-Level (0-2 yrs): ₹3 - 4.5 LPA | Sports/Clinical Specialist (3-6 yrs): ₹6 - 10 LPA | Established Private Clinic / Sports Consultant (7+ yrs): ₹12 - 25+ LPA. Indicative figures from NCAHP 2024.",
        "future_scope": "Growing rapidly due to aging populations, lifestyle musculoskeletal disorders, and India's thriving sports ecosystem.",
        "government_opportunities": "Sports Authority of India (SAI), Army Rehabilitation Centers, AIIMS Allied Health wings, Railway Hospitals.",
        "private_opportunities": "Sports franchises (IPL, ISL, PKL), Apollo Hospitals, Fortis, fitness chains, private clinics.",
        "higher_study_options": "MPT (Master of Physiotherapy in Sports, Neurology, Orthopedics, or Cardiopulmonary).",
        "entrepreneurship_options": "Independent physiotherapy clinic, sports rehabilitation center, corporate ergonomics consultancy.",
        "source": "National Commission for Allied and Healthcare Professions (NCAHP)",
        "official_url": "https://www.mohfw.gov.in",
        "verification_status": "VERIFIED",
        "courses": [{"course_id": 6, "type": "ALTERNATIVE"}],
        "exams": [{"exam_id": 7, "importance": "PRIMARY"}, {"exam_id": 79, "importance": "ALTERNATIVE"}],
        "routes": [
            {"title": "Path A: Standard BPT Route", "type": "COMMON", "steps": "Class 12 (PCB) -> NEET-UG / State CET -> BPT (4.5 yrs including 6 months internship) -> Register with NCAHP -> Clinical / Sports Physiotherapist."}
        ],
        "ladder": [
            {"stage": "Physiotherapy Intern / Assistant", "exp": "0-2 Years", "desc": "Assists with patient exercises, applies electrotherapy modalities under senior physios."},
            {"stage": "Clinical Physiotherapist", "exp": "2-5 Years", "desc": "Conducts independent assessments, designs post-surgical rehabilitation plans."},
            {"stage": "Senior Sports / Neuro Physiotherapist", "exp": "5-8 Years", "desc": "Works with athletic teams or neuro-ICUs, leads rehabilitation teams."},
            {"stage": "Director of Rehabilitation / Clinic Founder", "exp": "8+ Years", "desc": "Owns sports rehabilitation facilities, directs multi-center clinical therapy."}
        ],
        "roadmaps": {
            "Class 10": "Build interest in human anatomy, biology, and athletics.",
            "Class 12": "Score well in Physics, Chemistry, and Biology. Prepare for NEET-UG or State CETs.",
            "Graduation": "Complete BPT (4 years academic + 6 months internship) with intensive clinical training in hospital wards.",
            "Working Professional": "Pursue MPT in Sports or Orthopedics, earn certifications in Dry Needling / Kinesiology Taping, or work with sports academies."
        }
    },
    {
        "title": "Medical Laboratory Technologist",
        "short_name": "Lab Technologist (BMLT)",
        "slug": "medical-lab-technologist",
        "category": "Healthcare & Medical Sciences",
        "sub_category": "Allied Health Sciences & Diagnostics",
        "industry": "Healthcare / Diagnostics",
        "icon": "eyedropper",
        "short_description": "Performs complex biochemical, hematological, microbiological, and immunochemical clinical diagnostic testing on patient samples.",
        "description": "Medical Laboratory Technologists conduct clinical laboratory tests that provide vital data for diagnosing, treating, and preventing human disease. They operate automated diagnostic analyzers, examine blood smears under microscopes, and maintain strict laboratory quality control.",
        "what_they_do": "They analyze blood, tissue, and bodily fluids, perform blood grouping and cross-matching, identify infectious microorganisms, calibrate diagnostic instruments, and validate test result accuracy.",
        "day_to_day_work": "• Operating automated hematology and biochemistry analyzers.\n• Examining stained peripheral blood smears and body fluids under microscopes.\n• Performing microbiological bacterial cultures and antibiotic sensitivity tests.\n• Calibrating and maintaining clinical laboratory instrumentation.\n• Recording test results and flagging critical panic values to pathologists.",
        "work_environment": "Diagnostic clinical laboratories, hospital pathology departments, blood banks.",
        "work_modes": "On-site / Shift Rotations",
        "minimum_qualification": "Undergraduate (BMLT / B.Sc MLT)",
        "preferred_streams": "Science (PCB)",
        "required_subjects": "Chemistry, Biology, Physics",
        "technical_skills": "Hematology, Clinical Biochemistry, Medical Microbiology, Histopathology, Blood Banking, Quality Control (NABL)",
        "soft_skills": "Meticulous Attention to Detail, Integrity, Problem Solving, Cleanliness",
        "tools": "Automated Hematology Analyzers, Centrifuges, Microscopes, Autoclaves, LIMS Software",
        "certifications": "National Commission for Allied and Healthcare Professions (NCAHP) Registration",
        "experience_level": "Entry-Level to Senior",
        "career_growth": "Progression to Senior Technologist, Laboratory Quality Manager, or Chief Technical Officer in diagnostics.",
        "internship_roles": "Laboratory Internship (6 Months)",
        "entry_level_roles": "Junior Lab Technologist, Phlebotomist, Medical Lab Assistant",
        "average_salary": "₹3 - ₹7 LPA (Indicative range)",
        "salary_indicative": "Entry-Level (0-2 yrs): ₹2.8 - 4.2 LPA | Senior Technologist (3-6 yrs): ₹4.5 - 8 LPA | Lab Operations Manager (7+ yrs): ₹9 - 16+ LPA. Indicative figures from NCAHP 2024.",
        "future_scope": "Consistently essential as over 70% of clinical medical decisions rely on accurate laboratory diagnostics.",
        "government_opportunities": "AIIMS, ESIC Hospitals, Central Government Health Scheme (CGHS), State Public Health Laboratories.",
        "private_opportunities": "Dr Lal PathLabs, SRL Diagnostics, Metropolis Healthcare, Apollo Diagnostics, hospital pathology units.",
        "higher_study_options": "M.Sc Medical Laboratory Technology, M.Sc Microbiology / Biochemistry.",
        "entrepreneurship_options": "NABL-accredited diagnostic collection center, pathology testing laboratory.",
        "source": "National Commission for Allied and Healthcare Professions (NCAHP)",
        "official_url": "https://www.mohfw.gov.in",
        "verification_status": "VERIFIED",
        "courses": [{"course_id": 6, "type": "ALTERNATIVE"}, {"course_id": 3, "type": "COMMON"}],
        "exams": [{"exam_id": 79, "importance": "PRIMARY"}],
        "routes": [
            {"title": "Path A: BMLT Degree Route", "type": "COMMON", "steps": "Class 12 (PCB) -> B.Sc MLT / BMLT (3 yrs + 6 mo internship) -> Registration -> Diagnostic Lab Technologist."},
            {"title": "Path B: DMLT Diploma Route", "type": "ALTERNATIVE", "steps": "Class 12 (Science) -> DMLT (2 yrs) -> Junior Lab Assistant -> Lateral BMLT -> Senior Technologist."}
        ],
        "ladder": [
            {"stage": "Junior Lab Technologist", "exp": "0-2 Years", "desc": "Prepares reagents, loads automated analyzers, collects blood specimens."},
            {"stage": "Medical Lab Technologist", "exp": "2-5 Years", "desc": "Performs differential blood counts, cultures, cross-matching, verifies calibrations."},
            {"stage": "Senior Technologist / Lab Supervisor", "exp": "5-8 Years", "desc": "Manages laboratory inventory, handles NABL accreditation audits, resolves discrepancies."},
            {"stage": "Chief Technical Officer / Lab Director", "exp": "8+ Years", "desc": "Directs overall technical diagnostics operations across hospital network."}
        ],
        "roadmaps": {
            "Class 10": "Focus on General Science, Biology, and basic laboratory techniques.",
            "Class 12": "Study Chemistry and Biology diligently.",
            "Graduation": "Complete B.Sc MLT with rigorous hands-on rotations in Biochemistry, Pathology, and Microbiology.",
            "Working Professional": "Master automated molecular diagnostic platforms (RT-PCR, GeneXpert) and NABL ISO 15189 compliance."
        }
    },
    {
        "title": "Clinical Nutritionist & Dietitian",
        "short_name": "Dietitian / Nutritionist",
        "slug": "clinical-nutritionist",
        "category": "Healthcare & Medical Sciences",
        "sub_category": "Allied Health Sciences & Nutrition",
        "industry": "Healthcare & Wellness",
        "icon": "apple",
        "short_description": "Designs personalized nutritional therapies and diet plans to prevent and manage chronic diseases and optimize health.",
        "description": "Clinical Nutritionists evaluate patient nutritional requirements and formulate evidence-based dietary regimens. They manage medical nutrition therapy for diabetes, cardiovascular disease, renal failure, obesity, and oncological recovery.",
        "what_they_do": "They assess patient metabolic profiles and dietary habits, calculate macronutrient and micronutrient targets, design meal plans, and collaborate with physicians on medical nutrition management.",
        "day_to_day_work": "• Conducting detailed dietary and body composition assessments.\n• Calculating caloric, protein, and mineral needs based on clinical status.\n• Designing specialized diets (diabetic, renal, enteral tube feeding, low-sodium).\n• Counseling patients on lifestyle modifications and nutritional balance.\n• Auditing hospital food service kitchens for hygienic dietary preparation.",
        "work_environment": "Hospitals, wellness clinics, sports academies, or digital tele-nutrition practices.",
        "work_modes": "Hybrid / On-site / Remote Consultations",
        "minimum_qualification": "Undergraduate (B.Sc Nutrition & Dietetics)",
        "preferred_streams": "Science (PCB / Home Science)",
        "required_subjects": "Biology, Chemistry, Home Science / Nutrition",
        "technical_skills": "Medical Nutrition Therapy, Macronutrient Calculation, Food Chemistry, Clinical Dietetics, Metabolic Health",
        "soft_skills": "Empathy, Persuasive Counseling, Active Listening, Cultural Dietary Awareness",
        "tools": "Diet Planning Software, Body Composition Analyzers, Nutritional Tables, EMR",
        "certifications": "Registered Dietitian (RD) - Indian Dietetic Association (IDA)",
        "experience_level": "Entry-Level to Senior",
        "career_growth": "Broad career pathways into Hospital Chief Dietitian, Sports Nutritionist, or independent private practice.",
        "internship_roles": "Clinical Dietetics Internship (6 Months)",
        "entry_level_roles": "Junior Dietitian, Assistant Nutritionist, Wellness Counselor",
        "average_salary": "₹3.5 - ₹8 LPA (Indicative range)",
        "salary_indicative": "Junior Dietitian (0-2 yrs): ₹3 - 4.5 LPA | Clinical Specialist (3-6 yrs): ₹5 - 9 LPA | Celebrity / Sports Nutritionist (7+ yrs): ₹12 - 28+ LPA. Indicative figures from Indian Dietetic Association 2024.",
        "future_scope": "Surging demand driven by lifestyle disorders (diabetes, hypertension, obesity) and preventive health focus.",
        "government_opportunities": "AIIMS, State Government Hospitals, National Institute of Nutrition (NIN - ICMR), Sports Authority of India.",
        "private_opportunities": "Apollo Hospitals, Fortis, Max, HealthifyMe, Cult.fit, sports teams, private clinics.",
        "higher_study_options": "M.Sc Clinical Nutrition & Dietetics, PG Diploma in Sports Nutrition.",
        "entrepreneurship_options": "Private clinical nutrition clinic, digital diet counseling app, specialized healthy meal delivery brand.",
        "source": "Indian Dietetic Association (IDA) / ICMR-NIN",
        "official_url": "https://www.idaindia.com",
        "verification_status": "VERIFIED",
        "courses": [{"course_id": 6, "type": "ALTERNATIVE"}, {"course_id": 3, "type": "ALTERNATIVE"}],
        "exams": [{"exam_id": 79, "importance": "PRIMARY"}],
        "routes": [
            {"title": "Path A: B.Sc to Registered Dietitian (RD) Route", "type": "COMMON", "steps": "Class 12 (Science/Home Science) -> B.Sc Nutrition & Dietetics -> M.Sc Foods & Nutrition -> 6-month hospital internship -> Clear IDA RD Exam -> Registered Dietitian."}
        ],
        "ladder": [
            {"stage": "Intern / Assistant Dietitian", "exp": "0-2 Years", "desc": "Calculates standard patient meals, takes dietary histories under senior dietitians."},
            {"stage": "Clinical Dietitian", "exp": "2-5 Years", "desc": "Handles ICU nutrition, manages complex therapeutic meal planning for renal/diabetic wards."},
            {"stage": "Chief Dietitian / Sports Nutritionist", "exp": "5-8 Years", "desc": "Heads hospital dietary department, advises elite athletic organizations."},
            {"stage": "Consultant Nutrition Director", "exp": "8+ Years", "desc": "Leads corporate wellness programs, speaks internationally, runs premium private practice."}
        ],
        "roadmaps": {
            "Class 10": "Build interest in food science, biology, and human health.",
            "Class 12": "Choose Science (PCB) or Home Science with Chemistry.",
            "Graduation": "Complete B.Sc in Nutrition & Dietetics. Complete M.Sc and 6-month hospital internship in an IDA-approved hospital.",
            "Working Professional": "Clear the Registered Dietitian (RD) exam, gain specialization in Sports Nutrition or Pediatric Dietetics."
        }
    },
    {
        "title": "Public Health Specialist",
        "short_name": "Public Health Specialist",
        "slug": "public-health-specialist",
        "category": "Healthcare & Medical Sciences",
        "sub_category": "Public Health & Epidemiology",
        "industry": "Healthcare & Public Policy",
        "icon": "globe2",
        "short_description": "Designs, implements, and monitors population-level disease prevention programs, epidemic surveillance, and health policies.",
        "description": "Public Health Specialists focus on community-wide health outcomes rather than individual patient treatment. They track disease outbreaks, analyze epidemiological data, evaluate maternal and child health interventions, and shape national health policies.",
        "what_they_do": "They conduct epidemiological surveys, design vaccination campaigns, analyze healthcare equity, manage disaster health responses, and formulate health policy advisories for governments and international organizations.",
        "day_to_day_work": "• Analyzing district and national health survey datasets (NFHS, HMIS).\n• Investigating disease outbreak clusters and tracking transmission vectors.\n• Designing public health awareness campaigns on sanitation, nutrition, and vaccines.\n• Writing policy briefs and research reports for public health authorities.\n• Monitoring public healthcare delivery at Primary Health Centers (PHCs).",
        "work_environment": "Government health departments, international agencies (WHO, UNICEF), research institutes.",
        "work_modes": "Hybrid / Field Visits / Office",
        "minimum_qualification": "Postgraduate (MPH)",
        "preferred_streams": "Science (PCB / Any UG)",
        "required_subjects": "Biology, Health Sciences, Statistics",
        "technical_skills": "Epidemiology, Biostatistics, Health Policy, Program Monitoring & Evaluation, Survey Design, Public Health Surveillance",
        "soft_skills": "Strategic Vision, Communication, Cultural Competence, Leadership",
        "tools": "SPSS, R, STATA, Epi Info, GIS Mapping Software, Excel",
        "certifications": "Master of Public Health (MPH)",
        "experience_level": "Mid-Level to Senior",
        "career_growth": "Prestigious international career path with progression to WHO Technical Officer, State Health Consultant, or Director of Health Services.",
        "internship_roles": "Public Health Intern, Health Program Trainee, Epidemiological Field Trainee",
        "entry_level_roles": "Public Health Associate, District Epidemiologist, Health Data Analyst",
        "average_salary": "₹6 - ₹16 LPA (Indicative range)",
        "salary_indicative": "Entry-Level / District Officer (0-2 yrs): ₹5 - 8 LPA | Program Manager (3-6 yrs): ₹9 - 18 LPA | International Public Health Lead (7+ yrs): ₹20 - 45+ LPA. Indicative figures from National Health Mission & WHO 2024.",
        "future_scope": "Vital long-term national priority driven by pandemic preparedness, universal healthcare (Ayushman Bharat), and epidemiological surveillance.",
        "government_opportunities": "National Health Mission (NHM), National Centre for Disease Control (NCDC), ICMR, State Health Societies.",
        "private_opportunities": "World Health Organization (WHO), UNICEF, Bill & Melinda Gates Foundation, PATH, Public Health Foundation of India (PHFI).",
        "higher_study_options": "Ph.D. in Epidemiology / Public Health, Post-Doctoral Fellowships.",
        "entrepreneurship_options": "Public health analytics consulting, healthcare NGO, rural telemedicine enterprise.",
        "source": "Ministry of Health & Family Welfare / PHFI",
        "official_url": "https://www.phfi.org",
        "verification_status": "VERIFIED",
        "courses": [{"course_id": 25, "type": "ALTERNATIVE"}, {"course_id": 8, "type": "ALTERNATIVE"}, {"course_id": 27, "type": "ALTERNATIVE"}],
        "exams": [{"exam_id": 1, "importance": "ALTERNATIVE"}, {"exam_id": 79, "importance": "PRIMARY"}],
        "routes": [
            {"title": "Path A: Clinical to Master of Public Health (MPH)", "type": "COMMON", "steps": "MBBS / BDS / B.Sc Nursing / B.Pharm -> Master of Public Health (MPH) from AIIMS / PHFI / TISS -> Public Health Specialist."},
            {"title": "Path B: Social Sciences to Public Health", "type": "COMMON", "steps": "BA / B.Sc in Economics / Statistics / Sociology -> MPH / M.Sc Epidemiology -> Health Program Manager."}
        ],
        "ladder": [
            {"stage": "District Health Associate / Epidemiologist", "exp": "0-2 Years", "desc": "Monitors disease surveillance data, manages field immunization drives."},
            {"stage": "Public Health Program Manager", "exp": "2-5 Years", "desc": "Leads state-level public health interventions (maternal health, TB elimination)."},
            {"stage": "Senior Health Policy Consultant", "exp": "5-8 Years", "desc": "Advises government ministries, authors peer-reviewed public health studies."},
            {"stage": "Country Health Director / WHO Specialist", "exp": "8+ Years", "desc": "Sets multi-national disease elimination strategies and international health aid."}
        ],
        "roadmaps": {
            "Class 10": "Build broad curiosity about human biology, geography, and global societal challenges.",
            "Class 12": "Choose Science or Social Sciences with Mathematics.",
            "Graduation": "Complete an undergraduate degree in medicine, nursing, pharmacy, or statistics. Work with health NGOs.",
            "Working Professional": "Earn a Master of Public Health (MPH) from premier institutes (TISS, JIPMER, AIIMS, PHFI) and specialize in Epidemiology or Health Systems."
        }
    },
    {
        "title": "Radiologic Technologist",
        "short_name": "Radiology Tech (B.Sc MIT)",
        "slug": "radiologic-technologist",
        "category": "Healthcare & Medical Sciences",
        "sub_category": "Allied Health Sciences & Diagnostics",
        "industry": "Healthcare / Medical Imaging",
        "icon": "radioactive",
        "short_description": "Operates advanced medical imaging equipment such as X-rays, CT scanners, and MRI machines to assist in clinical diagnosis.",
        "description": "Radiologic Technologists are medical imaging specialists who prepare patients and operate sophisticated diagnostic radiation and magnetic resonance equipment. They ensure high-quality diagnostic scans while maintaining stringent radiation safety protocols.",
        "what_they_do": "They position patients for imaging scans, operate computerized tomography (CT) scanners and MRI equipment, calculate radiation doses, process digital scans, and assist radiologists with fluoroscopy.",
        "day_to_day_work": "• Operating CT scanners, 1.5T/3T MRI machines, and digital X-ray units.\n• Positioning patients correctly to obtain sharp diagnostic radiographic angles.\n• Administering IV contrast media under radiologist supervision.\n• Ensuring radiation safety protocols (ALARA principle, lead aprons).\n• Archiving imaging scans in Picture Archiving and Communication Systems (PACS).",
        "work_environment": "Hospital radiology departments, diagnostic imaging centers, trauma centers.",
        "work_modes": "On-site / Shift Rotations",
        "minimum_qualification": "Undergraduate (B.Sc Medical Imaging Tech)",
        "preferred_streams": "Science (PCM / PCB)",
        "required_subjects": "Physics, Chemistry, Biology / Mathematics",
        "technical_skills": "X-Ray Radiography, CT Scanning, MRI Physics, Radiation Protection, PACS Administration, Cross-Sectional Anatomy",
        "soft_skills": "Patient Care, Meticulous Safety Focus, Calm Demeanor, Precision",
        "tools": "CT Scanners, MRI Scanners, Digital Radiography (DR) Units, Lead Shielding, PACS Software",
        "certifications": "Atomic Energy Regulatory Board (AERB) Radiation Safety Certification, NCAHP Registration",
        "experience_level": "Entry-Level to Senior",
        "career_growth": "Direct growth into Senior MRI/CT Specialist, Radiology Department Lead, or Application Specialist for imaging manufacturers.",
        "internship_roles": "Medical Imaging Internship (6 Months)",
        "entry_level_roles": "Junior Radiographer, X-Ray Technician, MRI/CT Assistant",
        "average_salary": "₹3.5 - ₹8 LPA (Indicative range)",
        "salary_indicative": "Entry-Level (0-2 yrs): ₹3 - 4.5 LPA | Senior MRI/CT Specialist (3-6 yrs): ₹5 - 9 LPA | Radiology Applications Specialist (7+ yrs): ₹10 - 20+ LPA. Indicative figures from AERB & Healthcare Surveys 2024.",
        "future_scope": "Strong sustained demand as medical diagnosis increasingly relies on non-invasive advanced cross-sectional imaging.",
        "government_opportunities": "AIIMS, Central Government Hospitals, Railway Hospitals, State Trauma Care Centers, Defence Hospitals.",
        "private_opportunities": "Apollo Hospitals, Fortis, Max, Medanta, Mahajan Imaging, GE Healthcare, Siemens Healthineers.",
        "higher_study_options": "M.Sc Medical Imaging Technology, PG Diploma in Advanced MRI/CT.",
        "entrepreneurship_options": "Independent ultrasound and X-ray diagnostic center, mobile imaging unit services.",
        "source": "Atomic Energy Regulatory Board (AERB) / NCAHP",
        "official_url": "https://www.aerb.gov.in",
        "verification_status": "VERIFIED",
        "courses": [{"course_id": 2, "type": "ALTERNATIVE"}],
        "exams": [{"exam_id": 79, "importance": "PRIMARY"}],
        "routes": [
            {"title": "Path A: B.Sc Medical Imaging Technology", "type": "COMMON", "steps": "Class 12 (PCM/PCB) -> B.Sc Medical Imaging Technology / Radiology (3 yrs + 6 mo internship) -> AERB Certification -> Radiologic Technologist."}
        ],
        "ladder": [
            {"stage": "Junior Radiographer", "exp": "0-2 Years", "desc": "Performs standard X-rays, assists senior technologists in CT scanning."},
            {"stage": "Senior CT/MRI Technologist", "exp": "2-5 Years", "desc": "Operates high-field MRI, executes multi-slice cardiac and neuro CT protocols."},
            {"stage": "Radiology Department Incharge", "exp": "5-8 Years", "desc": "Supervises imaging staff, oversees AERB radiation safety audits."},
            {"stage": "Clinical Applications Specialist / Director", "exp": "8+ Years", "desc": "Works with GE/Siemens/Philips to train hospital staff on cutting-edge imaging hardware."}
        ],
        "roadmaps": {
            "Class 10": "Build interest in Physics, electromagnetic waves, and human biology.",
            "Class 12": "Focus on Physics and Chemistry/Biology. Understand radiation and magnetic fields.",
            "Graduation": "Complete B.Sc in Medical Imaging Technology with intensive clinical training in CT and MRI suites.",
            "Working Professional": "Earn AERB Radiological Safety Officer (RSO) certification and specialize in advanced 3T MRI sequences or PET-CT imaging."
        }
    },
    {
        "title": "Optometrist",
        "short_name": "Optometrist (B.Optom)",
        "slug": "optometrist",
        "category": "Healthcare & Medical Sciences",
        "sub_category": "Allied Health Sciences & Vision Care",
        "industry": "Healthcare / Vision Science",
        "icon": "eye",
        "short_description": "Examines eyes, diagnoses visual defects, prescribes corrective lenses, and manages non-surgical ocular disorders.",
        "description": "Optometrists are primary vision care practitioners who perform comprehensive eye examinations, detect ocular abnormalities (glaucoma, cataracts, retinal signs of diabetes), fit contact lenses, and prescribe corrective spectacles and low vision aids.",
        "what_they_do": "They conduct refraction tests, measure intraocular pressure, prescribe corrective eyeglasses and contact lenses, perform pediatric visual screenings, and provide pre- and post-operative eye care.",
        "day_to_day_work": "• Conducting subjective and objective refraction tests using phoropters.\n• Examining the anterior and posterior segments of the eye with slit lamps.\n• Measuring intraocular eye pressure using tonometry.\n• Fitting custom contact lenses and prescribing orthoptic vision therapies.\n• Referring patients with surgical eye conditions (cataracts, retinal detachment) to ophthalmologists.",
        "work_environment": "Eye hospitals, optometry clinics, optical retail stores, vision research labs.",
        "work_modes": "On-site / Clinical",
        "minimum_qualification": "Undergraduate (B.Optom)",
        "preferred_streams": "Science (PCB / PCM)",
        "required_subjects": "Physics, Chemistry, Biology / Mathematics",
        "technical_skills": "Refraction, Slit Lamp Biomicroscopy, Contact Lens Fitting, Tonometry, Visual Field Assessment, Ocular Pharmacology",
        "soft_skills": "Patience, Precise Communication, Empathy, Customer Service",
        "tools": "Phoropter, Slit Lamp, Autorefractometer, Tonometer, Retinoscope, Ophthalmoscope",
        "certifications": "Optometry Council of India (OCI) Registration, NCAHP Registration",
        "experience_level": "Entry-Level to Senior",
        "career_growth": "Steady growth with postgraduate M.Optom specialization (Contact Lenses, Pediatric Optometry) or optical chain management.",
        "internship_roles": "Optometry Clinical Internship (1 Year)",
        "entry_level_roles": "Junior Optometrist, Clinical Optometry Assistant, Optical Retail Specialist",
        "average_salary": "₹3.5 - ₹8 LPA (Indicative range)",
        "salary_indicative": "Entry-Level (0-2 yrs): ₹3 - 4.5 LPA | Senior Clinical Optometrist (3-6 yrs): ₹5 - 9 LPA | Optical Store Owner / Chain Lead (7+ yrs): ₹10 - 22+ LPA. Indicative figures from Optometry Council of India 2024.",
        "future_scope": "High sustained demand due to increased screen time, digital eye strain, myopia epidemic, and aging population.",
        "government_opportunities": "AIIMS Dr. RP Centre for Ophthalmic Sciences, District Eye Care Mobile Units, Railway Hospitals.",
        "private_opportunities": "Lenskart, Titan Eye+, Sankara Nethralaya, Aravind Eye Care System, Dr. Agarwal's Eye Hospital.",
        "higher_study_options": "M.Optom (Master of Optometry), Fellowship in Cornea & Contact Lenses.",
        "entrepreneurship_options": "Independent optical store and eye testing clinic, franchise optical retail ownership.",
        "source": "Optometry Council of India (OCI) / NCAHP",
        "official_url": "https://www.optometrycouncilofindia.org",
        "verification_status": "VERIFIED",
        "courses": [{"course_id": 2, "type": "ALTERNATIVE"}],
        "exams": [{"exam_id": 79, "importance": "PRIMARY"}],
        "routes": [
            {"title": "Path A: Standard Bachelor of Optometry (B.Optom)", "type": "COMMON", "steps": "Class 12 (PCB/PCM) -> B.Optom (3 yrs + 1 yr Internship) -> Register with OCI / NCAHP -> Clinical / Retail Optometrist."}
        ],
        "ladder": [
            {"stage": "Intern / Junior Optometrist", "exp": "0-2 Years", "desc": "Conducts standard refractions, auto-refractometer readings, dispenses lenses."},
            {"stage": "Senior Clinical Optometrist", "exp": "2-5 Years", "desc": "Performs specialized contact lens fittings, visual field exams, manages eye clinic."},
            {"stage": "Head Optometrist / Store Manager", "exp": "5-8 Years", "desc": "Supervises multi-unit optical center, trains junior optometrists."},
            {"stage": "Director of Vision Care / Optical Entrepreneur", "exp": "8+ Years", "desc": "Owns chain of eye care centers or heads clinical training for major eyewear brands."}
        ],
        "roadmaps": {
            "Class 10": "Focus on Physics (optics, lenses, refraction) and Human Biology.",
            "Class 12": "Study Physics and Biology/Mathematics. Score well in Class 12 board exams.",
            "Graduation": "Complete B.Optom (3 years academic + 1 year hospital internship) at premier eye institutes like Sankara Nethralaya or LVPEI.",
            "Working Professional": "Pursue M.Optom, earn specialized fellowships in Orthoptics or Low Vision, or open an independent optical clinic."
        }
    },
    {
        "title": "Clinical Psychologist",
        "short_name": "Clinical Psychologist",
        "slug": "clinical-psychologist",
        "category": "Healthcare & Medical Sciences",
        "sub_category": "Mental Health & Behavioral Sciences",
        "industry": "Healthcare / Mental Health",
        "icon": "person-heart",
        "short_description": "Diagnoses and treats mental, emotional, and behavioral disorders using evidence-based psychotherapeutic interventions.",
        "description": "Clinical Psychologists assess psychological disorders, conduct standardized psychometric testing, and deliver specialized psychotherapy (such as Cognitive Behavioral Therapy - CBT). They treat anxiety, depression, trauma, schizophrenia, and personality disorders.",
        "what_they_do": "They administer psychological assessment tests, provide psychotherapy sessions, design behavioral modification plans, conduct crisis interventions, and collaborate with psychiatrists.",
        "day_to_day_work": "• Conducting psychodiagnostic interviews and clinical assessments.\n• Administering psychological tests (Rorschach, MMPI, WAIS intelligence scales).\n• Conducting evidence-based psychotherapy sessions (CBT, DBT, Psychodynamic).\n• Formulating psychiatric case formulation reports.\n• Collaborating with medical doctors and psychiatrists on patient management.",
        "work_environment": "Psychiatric hospitals, private counseling chambers, universities, rehabilitation centers.",
        "work_modes": "On-site / Hybrid / Private Therapy Chamber",
        "minimum_qualification": "Postgraduate + Professional M.Phil / Psy.D (RCI Licensed)",
        "preferred_streams": "Any Stream (Arts / Science with Psychology preferred)",
        "required_subjects": "Psychology, English",
        "technical_skills": "Psychotherapy, Cognitive Behavioral Therapy (CBT), Psychometric Testing, Diagnostic Assessment, Crisis Intervention",
        "soft_skills": "Deep Empathy, Active Listening, Unconditional Positive Regard, Ethical Confidentiality",
        "tools": "Standardized Psychometric Test Batteries, Diagnostic Criteria (DSM-5, ICD-11), Therapy Notes EMR",
        "certifications": "Rehabilitation Council of India (RCI) License as Registered Clinical Psychologist",
        "experience_level": "Entry-Level to Senior",
        "career_growth": "High demand with transition into Senior Consultant Clinical Psychologist, Department Head, or independent private therapy practice.",
        "internship_roles": "Clinical Psychology Hospital Internship (Integrated in M.Phil)",
        "entry_level_roles": "Licensed Clinical Psychologist, Assistant Professor of Psychology, Behavioral Therapist",
        "average_salary": "₹5 - ₹14 LPA (Indicative range)",
        "salary_indicative": "Entry-Level RCI Licensed (0-2 yrs): ₹4.5 - 7.5 LPA | Established Psychotherapist (3-6 yrs): ₹8 - 15 LPA | Senior Consultant / Private Practice (7+ yrs): ₹16 - 35+ LPA. Indicative figures from Rehabilitation Council of India 2024.",
        "future_scope": "Exponential growth driven by surging mental health awareness, destigmatization, and corporate wellness initiatives.",
        "government_opportunities": "NIMHANS Bengaluru, AIIMS Psychiatry, Defence Institute of Psychological Research (DIPR - DRDO), State Mental Health Hospitals.",
        "private_opportunities": "Fortis Mental Health, Medanta, private therapy clinics, international digital therapy platforms.",
        "higher_study_options": "Psy.D (Doctor of Psychology), Ph.D. in Clinical Psychology.",
        "entrepreneurship_options": "Independent psychotherapy clinic, mental health wellness center, corporate mental wellness consultancy.",
        "source": "Rehabilitation Council of India (RCI) / NIMHANS",
        "official_url": "https://www.rehabcouncil.nic.in",
        "verification_status": "VERIFIED",
        "courses": [{"course_id": 21, "type": "ALTERNATIVE"}],
        "exams": [{"exam_id": 79, "importance": "PRIMARY"}, {"exam_id": 10, "importance": "ALTERNATIVE"}],
        "routes": [
            {"title": "Path A: Standard RCI Clinical Psychologist Pathway", "type": "COMMON", "steps": "Class 12 (Any stream) -> BA / B.Sc Psychology (3 yrs) -> MA / M.Sc Psychology (2 yrs) -> M.Phil in Clinical Psychology from an RCI-recognized institute (2 yrs) -> Obtain RCI Registration Number -> Practice as Clinical Psychologist."}
        ],
        "ladder": [
            {"stage": "Trainee / Resident Psychologist", "exp": "0-2 Years", "desc": "Administers psychometric test batteries, conducts structured clinical interviews under supervision."},
            {"stage": "Licensed Clinical Psychologist", "exp": "2-5 Years", "desc": "Conducts independent CBT and psychotherapy sessions for complex psychiatric conditions."},
            {"stage": "Senior Clinical Psychologist / Lead", "exp": "5-8 Years", "desc": "Supervises psychology residents, conducts forensic psychological evaluations."},
            {"stage": "Director of Mental Health / Department Chair", "exp": "8+ Years", "desc": "Heads hospital psychology services, shapes national mental health policies and research."}
        ],
        "roadmaps": {
            "Class 10": "Read introductory books on human behavior, emotions, and psychology.",
            "Class 12": "Choose Humanities or Science with Psychology if available. Build strong English expression.",
            "Graduation": "Complete BA/B.Sc and MA/M.Sc in Psychology with top academic grades. Complete clinical observerships.",
            "Working Professional": "Clear entrance for M.Phil in Clinical Psychology at premier institutes (NIMHANS, CIP Ranchi, IHBAS Delhi) to secure mandatory RCI license."
        }
    }
]
